### ISSUE TITLE
Provide a way to quickly delete a script in using

### ISSUE THREAD

**Issue by fireattack** [violentmonkey/violentmonkey#1000]
### What is the problem?

Currently, if you want to delete a script that is used on the current website, you have to:

1. Look and memorize the name of the script;
2. Go to the dashboard;
3. Search for the name manually;
4. Remove it from the dashboard.

I think if we provide either:

1. a remove button in the dropdown list
2. a remove/delete button in editor

This process can be shortened a lot, and no memorizing needed. 

Instead of go to the dashboard and search, one can directly remove it without leaving the website, or alternatively, open that script in editor by right click (or click edit button) and then delete it from there.

### Environment
- Browser: Chrome
- Browser version: 83
- Violentmonkey version: 2.12.7
- OS: Windows

**Comment by tophf** [comment]
Assuming we also implement #367, I guess we can do it the way Tampermonkey and other apps do: show a vertical three-dot icon at the end of each row, clicking which will show a small menu. Maybe we'll also move the edit button into this menu because there are already three alternative click methods to invoke it directly.

**Comment by fireattack** [comment]
Thanks!

I think the editor page needs some improvements too. Currently, lots of info and actions can only to be accessed in the dashboard (check update, delete, check last updated date etc.).

I understand we may want to keep editor page simple (rightfully so), but think it this way: when a user have lots of scripts (I personally have hundreds), they probably exclusively access to any individual script via popup from a site that is using it, instead of going through the long list in the dashboard. Therefore,  it would very beneficial if these information and actions can be accessed there.

**Comment by tophf** [comment]
We can add "Check for update" action in that mini-menu.
We can also show the version and the last update time there as well (as a "title" or "statusbar" of this mini-menu).
