### ISSUE TITLE
Prevent external js @require caching

### ISSUE THREAD

**Issue by thesummit** [violentmonkey/violentmonkey#1005]
### What is the problem?
External files get cache. Want to set cache timeout.

### How to reproduce it?
1. create a script and @require a js file an have it log a static text A
2. run the script by loading a page that runs it. see that it logs A.
3. update the required script to log static text B. see that reloading the page still logs A.
4. touch the violent monkey script (triggers a cache bust). reloading the page now logs B.

### What is the expected result?
Option A. Another annotation or something for @require tag such that they can be set to different cache timeouts, like 10mins.
Option B. Allow variable templating in the @require field so that we can just add a timestamp cachebust or something based on time components like an hour or day of week. like so: 
@require http://my.site/script.js?t={{hourOfDay}} // effectively setting cachebust to an hour

### What is the actual result?
It's cached. Don't always want that.

### Environment
- Browser: Google Chrome
- Browser version: Version 83.0.4103.97 (Official Build) (64-bit)
- Violentmonkey version: v2.12.7
- OS: macOS Catalina (10.15.2)

**Comment by tophf** [comment]
Should be fixed in the next version, AFAIK:
https://github.com/violentmonkey/violentmonkey/releases

**Comment by thesummit** [comment]
just tested the beta on firefox. doesn't seem to respect the following cache settings (also tried `no-cache`):

```
{
  status: 200,
  headers: {
    "Cache-control":"max-age=2"
  },
  body,
}
```

**Comment by tophf** [comment]
1. Did you test by clicking the update icon?
2. Please inspect the network request in [devtools for the background script](https://extensionworkshop.com/documentation/develop/debugging/)
