### ISSUE TITLE
Extension not working if the "Continue running background apps" option is turned on

### ISSUE THREAD

**Issue by kamekku14** [violentmonkey/violentmonkey#1007]
### What is the problem?
For some reason, when Google Chrome is running in the background with "Continue running background apps when Google Chrome is closed" option turned on, it causes some disastrous results.

### How to reproduce it?
1. Open Google Chrome.
2. Head to **Settings** \> **Advanced** \> **System** and select **"Continue running background apps when Google Chrome is closed"**.
3. Right click on the tray icon and click **Exit**.
4. Relaunch Chrome.

### What is the expected result?
Without the "Continue running background apps" option, the extension seems to be working fine.

### What is the actual result?
When I open the extensions settings page, it throws up an error in the Error Console when trying to configure:
```
Uncaught (in promise) Error: Violentmonkey cannot connect to the background page.
    at common.js:formatted:68
(anonymous) @ common.js:formatted:1
Promise.then (async)
ye @ index.js:1
(anonymous) @ index.js:1
131 @ index.js:1
i @ index.js:1
s @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
4

TypeError: this.revoke is not a function
    at a.beforeDestroy (index.js:1)
    at Ut (vue.js:1)
    at Ze (vue.js:1)
    at a.t.$destroy (vue.js:1)
    at destroy (vue.js:1)
    at b (vue.js:1)
    at b (vue.js:1)
    at a.__patch__ (vue.js:1)
    at a.t.$destroy (vue.js:1)
    at destroy (vue.js:1)
```

### Environment
- Browser: Google Chrome
- Browser version: Version 83.0.4103.116 (Official Build) (64-bit)
- Violentmonkey version: v2.12.7
- OS: Windows 10 Pro, Version 1909 (Build 18363\.900)

**Comment by tophf** [comment]
Can't reproduce. Violentmonkey doesn't use the `background` permission so this option shouldn't make any difference but since it does in your case, I guess it might be a bug in Chrome. See if you can reproduce it in a new empty profile with just Violentmonkey installed.
