### ISSUE TITLE
Collected errors

### ISSUE THREAD

**Issue by Kein** [violentmonkey/violentmonkey#1008]
Not sure if it bears any relevance so I dropped template. Running Vivaldi 3.1/Chromium 83, constantly getting this in the collected errors:
![image](https://user-images.githubusercontent.com/623756/86184820-95de6280-bb3d-11ea-94e5-afb66c2c59bf.png)

VM seems to be working fine tho but I dont know if the rest of manifest was parsed or it stopped at the error.

**Comment by tophf** [comment]
This warning may be safely ignored.
