### ISSUE TITLE
VM fails on special privileges pages that are non-internal

### ISSUE THREAD

**Issue by Kein** [violentmonkey/violentmonkey#1009]
I've searched issue for a few keywords but surprisingly no relevant hits.
Consider page: `https://chrome.google.com/webstore/*`
Vivaldi 3.1.1929.45 | Chrome/83.0.4103.119
Script:

```js
// ==UserScript==
// @name        Chrome Webstore Test
// @namespace   Violentmonkey Scripts
// @match       https://chrome.google.com/webstore/detail/*
// @grant       none
// @version     1.0
// @author      -
// @run-at       document-end
// ==/UserScript==

(function() {
	'use strict';
        console.log("Kweh!")
})();
```

No scripts matched, even match for all pages wont work. Now, I understand that there are some virtual pages like chrome://flags and so on, it makes sense, but `https://chrome.google.com/webstore/` is a web-resource, there has to be a way to make it work?

**Comment by tophf** [comment]
The CWS cannot be scripted in chromium, see [ChromeExtensionsClient::IsScriptableURL](https://cs.chromium.org/chromium/src/chrome/common/extensions/chrome_extensions_client.cc), just like AMO cannot be scripted in FF (they have an about:config though). In Stylus extension we explain this in the popup but here it's the first time someone reports the issue so we'll wait for a couple more reports probably.
