### ISSUE TITLE
The tooltip "check for updates" doesn't disappear.

### ISSUE THREAD

**Issue by Mehavoid** [violentmonkey/violentmonkey#1010]
### What is the problem?
![](https://i.imgur.com/oTNHnCi.gif)

### How to reproduce it?
1. Click on the button "check for updates"
2. While the button is disabled, move the mouse cursor from this button

### Environment
- Browser: Ungoogled Chromium
- Browser version: 80.0.3987.149 (Developer Build) 
- Violentmonkey version: v2.12.8rc13
- OS: Linux (Debian 10)

**Comment by tophf** [comment]
@gera2ld looks like a bug in your vueleton tooltip: it should probably always set `this.hovered = false` without `this.shouldHandleMouse` condition in [onLeave()](https://github.com/gera2ld/vueleton/blob/a632d090ded41fbd3a66cfc5015e9bde3892b59a/src/tooltip/tooltip.vue#L98). At least it works for me that way. Will you fix it yourself or should I open a PR there?

**Comment by gera2ld** [comment]
I'll fix this.

**Comment by Mehavoid** [comment]
Thanks, guys!
