### ISSUE TITLE
script with window.close in iframe close top window

### ISSUE THREAD

**Issue by dodying** [violentmonkey/violentmonkey#1011]
### What is the problem?
when i run script with window.close in iframe, it will close the top window/tab

### How to reproduce it?
1. create new script:
```js
// ==UserScript==
// @name        New script - google.com
// @namespace   Violentmonkey Scripts
// @match       https://example.com/*
// @grant       window.close
// ==/UserScript==
window.close()
```
2.  open some url, like https://www.google.com
3. run these following in console:
```js
let iframe=document.createElement('iframe')
document.body.appendChild(iframe)
iframe.src='https://example.com'
```

### What is the expected result?
do nothing

### What is the actual result?
the top window/tab closed.

### Environment
- Browser: Chrome
- Browser version: 80.0.3987.163
- Violentmonkey version: v2.12.7
- OS: win10x64

**Comment by tophf** [comment]
Fixed in 76a76fae.
