### ISSUE TITLE
GM.xmlHttpRequest can't parse response header field:Content-Disposition with non-ascii.

### ISSUE THREAD

**Issue by ZalerC** [violentmonkey/violentmonkey#1012]
When use GM_xmlhttpRequest request a remote file for download, the response headers will have a field: `Content-Disposition`, sometimes this field value will be set a non-ascii filename.
GM_xmlhttpRequest can't parse this field, when have a non-ascii value, and be set undefined in responseHeaders.

**Comment by tophf** [comment]
`GM_xmlhttpRequest` doesn't parse any response headers at all so I guess what you observe is a bug in the browser. Can't investigate further without a way to reproduce the issue.

**Comment by ZalerC** [comment]
I test the same script in TamperMonkey, and test the url with fetch, all the responses are right, the same as Chrome Network log.

**Comment by tophf** [comment]
Violentmonkey does not parse any headers, it just passes a string for all headers which is provided by the browser so if there are any problems it means a bug in the browser. Without a way to reproduce the problem there's nothing we can do.

**Comment by tophf** [comment]
FWIW, try the upcoming [release candidate](https://github.com/violentmonkey/violentmonkey/releases).
