### ISSUE TITLE
[Feature request] Support for semver pre-releases in metadata

### ISSUE THREAD

**Issue by benutzer193** [violentmonkey/violentmonkey#1013]
### What is the problem?
Currently only numbers separated by points can be compared with function compareVersion.
According to [semver specifications](https://semver.org), pre-releases may be denoted by appending a hyphen, leading e.g. to following order:
1.0.0 < 1.0.1-0 < 1.0.1-1 < 1.0.0

In compareVersion this leads to:
1.0.0 < 1.0.1 = 1.0.1 = 1.0.1

### How to reproduce it?
1. Upload a pre-release script with a version string according to semver specifications, e.g. 1.0.1-0
2. Upload a newer version of the script, with a newer preloaded (1.0.1-1) or a release version (1.0.1)
=> The newer version is not found as newer version

### Desired behavior
compareVersion supports version strings according to semver.

**Comment by gera2ld** [comment]
If I remember correctly, `@version` in userscripts, coming from Greasemonkey, does not respect semver.
It is just a bunch of numbers concatenated with dots. There are many userscripts using dates as version numbers, like `2020.7.8.12.0`. And many others using versions with more than three numbers. We could break lots of them if we migrate to semver.

So I think a quick workaround is just to append another `.1` to your normal version string as a pre-release.

**Comment by benutzer193** [comment]
You seem to be correct:
https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/

Currently I am doing your proposed workaround, but that means the version in `package.json` is e.g. `1.0.1-0`, while the version in the script is `1.0.0.1`.

You are probably right, that the semver compare should not replace the old logic, but it would be possible to have a `compareSemver`, that is called, if the version string matches a semver string.

**Comment by tophf** [comment]
I'll add handling for semver prerelease part after `-` and keep the old logic for the main part.

**Comment by benutzer193** [comment]
Thanks.
