### ISSUE TITLE
Any plan to search js on openuserjs.org

### ISSUE THREAD

**Issue by GoogleBeEvil** [violentmonkey/violentmonkey#1016]
prefer openuserjs than greasyfork, any plan to and options for custom search engine?

**Comment by tophf** [comment]
I don't see any reason to **prefer** or even add OUJS. Last time I checked they didn't have an end-point like GF does for searching by matching site/domain (using the userscript `@matches` algorithm internally). As far as I can tell OUJS only has an end-point for word search so it misses a lot of scripts and matches irrelevant ones.
