### ISSUE TITLE
editor: support html/css higglighting

### ISSUE THREAD

**Issue by orionlee** [violentmonkey/violentmonkey#1019]
It'd be great if the editor can highlight html/css in the userscript. E.g.,

![image](https://user-images.githubusercontent.com/250644/87232467-299d0380-c374-11ea-80af-539d65248ed7.png)

Note: I have something working in my personal dev version (that generates the above screenshot). If there are interests, I could further polish them and create a pull request.

**Comment by tophf** [comment]
If the code is neat, small, and doesn't cause lags when editing/scrolling then it'd be a good feature to have.

**Comment by orionlee** [comment]
- I'm fairly sure it doesn't cause lagging. The highlight is done in a way similar to `CodeMirror`'s existing support for mixed HTML, which works fairly well. The performance should be comparable. You can try out their [demo](https://codemirror.net/mode/htmlmixed/index.html)

- Regarding codes,
  - you can judge the main logic yourself. It's not big but not trivial either. See [`javascript-mixed.js`](https://github.com/orionlee/violentmonkey/blob/editor-highlight-html-css/src/common/ui/code_extras/mode/javascript-mixed/javascript-mixed.js)
  - it does require a minor patching of CodeMirror's main javascript highlight to expose some internal function. See the [patch](https://github.com/orionlee/violentmonkey/blob/e83a0b2fe2d3cc93d21b453599fa6348ec712dab/src/common/ui/code_extras/mode/javascript-mixed/javascript-patched.js#L870). So if we proceed forward, we'd probably want to ping CodeMirror's maintainer to see if he is willing to accept the patch.

**Comment by tophf** [comment]
I didn't analyze the code but at a glance it seems small enough to be acceptable.

> minor patching

Now this is definitely a no.
Can't you just hook (override) `CodeMirror.modes.javascript` to augment its returned object with your method?

**Comment by orionlee** [comment]
Regarding patching CodeMirror's javascript:
- augmenting `CodeMirror.modes.javascript` is not quite possible as the patch code uses `javascript`'s internal functions.
- if we feel the feature is warranted, we could check to see if CodeMirror's maintainer will accept such a pull request.
- Another option is to not to patch at all. The tradeoff is single line string template would cause highlight issue. The text after single-line string template would be incorrectly highlighted as string.

![image](https://user-images.githubusercontent.com/250644/87258316-86251f00-c457-11ea-8cc5-8513eb1e6105.png)

**Comment by orionlee** [comment]
creating a dummy parsing to extract tokenQuasi should be possible. I'll look into it.
