### ISSUE TITLE
Symbols hoisting not working across sources

### ISSUE THREAD

**Issue by trumpeta** [violentmonkey/violentmonkey#1029]
### What is the problem?

Call to function defined in main script source from external library results in reference error.

### What is the expected result?

Evaluate the names at runtime and lookup in all sources (within matching scope)

### What is the actual result?

Reference error

### Environment
- Browser: Edge
- Browser version: 84.0.522.50
- Violentmonkey version: 2.12.7
- OS: Windows 8.1

### Comment

In other script managers, names lookup is done at runtime:
```

function foo(x) {
  return x**2;
}

var bar = foo(2);
console.log("Result:", bar);

function foo(x) {
  return x**3;
}

```

Prints "Result: 8" in native browser JS interpreter. In VM there are two scenarios, either I declare empty foo definition in library code before it's used as function foo(x) { }, then I get no reference error, but the empty instance is called later, or I don't make empty declaration and get reference error.

In other script managers like Tampermonkey, the library code is injected before the main script code, and all names in script global scope are evaluated at time when it's launched, making all global names accessible from global scope in any module. I'd wish this could be handled same way in VM.
I would accept a method to make the main module symbol available.

**Comment by tophf** [comment]
I don't understand what exactly you're doing there. Please show a minimal userscript that exhibits the problem.

**Comment by gera2ld** [comment]
This is the expected behavior for now. In Violentmonkey the main script runs in an isolated scope:

```js
// required scripts
(() => {
  // main script
}());
```

You can share objects via `window` or `this`.

**Comment by tophf** [comment]
@gera2ld, actually why don't we remove the IIFE? Apparently you added it to safeguard against this exact use case but since other managers let the users shoot themselves in the leg then we can allow it too maybe?

**Comment by tophf** [comment]
On the other hand, Greasemonkey isolates the userscript, too...

**Comment by gera2ld** [comment]
@tophf It was added to support `'use strict'` at the beginning of a userscript. I'm not sure if this is still needed...
Anyways, I think this kind of change are likely to break existed userscripts, so I guess we'd better leave it as is and maybe update the documentation.
