### ISSUE TITLE
无法与 OneDrive 同步

### ISSUE THREAD

**Issue by NBOOK** [violentmonkey/violentmonkey#103]
已经给予授权，在 "正在同步... (0/1)" 的阶段提示 "同步出错！"。Dropbox 同步没有任何问题。
似乎和墙没有关系，OneDrive 能直接打开。

如果需要 log 之类的还望指点一下，谢谢。

**Comment by gera2ld** [comment]
能直接打开和能同步是两回事。。。一般这种情况就是网络的问题，试过翻墙能不能同步吗？

**Comment by ivysrono** [comment]
论WebDav的重要性O(∩_∩)O
才发现，那正好是 #100 啊~

**Comment by NBOOK** [comment]
挂了 SS，试过几个节点都不行。

**Comment by gera2ld** [comment]
我测试完全正常。。。如果还有问题可以看一下背景页的网络日志，网络问题与扩展无关，won't fix

**Comment by gera2ld** [comment]
确实还是存在一些问题。。我看看能不能再优化一下

**Comment by ivysrono** [comment]
2.7.1 chrome
2.6.3 Firefox 
问题依旧

**Comment by Chow-Ray** [comment]
2.7.1 chrome OneDrive同步依旧失败。
同网络环境下Tampermonkey同步数据可以成功。
暴力猴同步(0/1)就出错，还继续是网络的问题？
如开发者上文所说？
