### ISSUE TITLE
Add support for GM_info.script.icon

### ISSUE THREAD

**Issue by scholtzm** [violentmonkey/violentmonkey#1031]
# What is the problem?
`@icon` property can be used in Metadata Block but cannot be accessed via `GM_info.script.icon`.

See:
https://violentmonkey.github.io/api/metadata-block/#icon
https://violentmonkey.github.io/api/gm/#gm_info

### How to reproduce it?
1. Have a script with `@icon` value in Metadata Block
2. Try to access `GM_info.script.icon`
3. Value is `undefined`

### What is the expected result?

`GM_info.script.icon` returns `@icon` value from Metadata Block.

### What is the actual result?

`GM_info.script.icon` returns `undefined`.

**Comment by tophf** [comment]
Until the new version is released you can extract the icon name from `GM_info.scriptMetaStr`.

**Comment by scholtzm** [comment]
That was quick. Thanks!
