### ISSUE TITLE
Firefox: Badge number doesn't show on image links

### ISSUE THREAD

**Issue by KLaurence** [violentmonkey/violentmonkey#1037]
~~`// @match  *://*/*`~~

~~In Firefox, userscripts with this specific metadata -- while matches -- don't get applied on links that are links of images. [Here's a test link where the issue occurs.](https://upload.wikimedia.org/wikipedia/commons/d/de/HillHouse.jpg)~~

~~There's no specific extension causing this except VM itself, as far as I know.~~

It also is the case that there are no numbers written in the extension badge, even though there are at least one userscript matching.

This issue exists on Firefox 79.

**Comment by tophf** [comment]
Can't repro the first problem. The userscript runs for me just fine.
Can repro the badge number problem.

**Comment by KLaurence** [comment]
Just tried it again, and sure enough like you, userscripts _do_ work. I was just confused that my userscript didn't work, which was not because of an issue with VM but because of some issue regarding CSS.

I'll rename the issue now to the badge bug since the title is no longer accurate.
