### ISSUE TITLE
Firefox: Installations tracking local files show "Error loading script data" after some time; logs a Security Error in the console

### ISSUE THREAD

**Issue by KLaurence** [violentmonkey/violentmonkey#1039]
### What is the problem?
Userscript installations that have the option "Track local file before this window is closed" checked give off the message "Error loading script data." after some time.
As far as I'm aware, this doesn't happen if the option "Track local file before this window is closed" is not checked.

### How to reproduce it?
1. Drag a userscript into browser (which will show a Violentmonkey "Installing script" page)
2. Click Options and check the option "Track local file before this window is closed"
3. Click "Confirm installation"
4. Wait some time

### What is the expected result?
A message (still) shows "Script updated" along with the time of the latest installation/revision of the userscript. Revisions are also reflected on Violentmonkey.

### What is the actual result?
A message shows "Error loading script data.", and revisions of the local file are not being reflected on Violentmonkey.

### Log
`Security Error: Content at moz-extension://44c36673-e8f5-4707-be56-e77ee2f47168/confirm/index.html#`_`<userscript ID>`_`may not load or link to`_`<userscript file URI>.`_

### Environment
- Browser: Firefox
- Browser version: 79.0
- Violentmonkey version: v2.12.7
- OS: Windows 7

**Comment by tophf** [comment]
Should be fixed in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases).
