### ISSUE TITLE
Firefox for Android 79 support

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1042]
Violentmonkey is not yet part of [the few extensions / add-ons supported by the new Firefox for Android version 79](https://addons.mozilla.org/android/).

I keep my Firefox for Android in version 68 (deactivate Firefox auto-update in Play Store).

I don't know if you can do anything about it or if it is Firefox team who does this.

**Comment by tophf** [comment]
As far as I know it's compatible so... no idea. You can help us by investigating it.

**Comment by jesus2099** [comment]
If I come across an Android user who had not blocked their Firefox to version 68, I'll try to find Violentmonkey and why it wouldn't appear, how we could make it appear.

**Comment by leogama** [comment]
Hello, there! The current status of Firefox for Android is this:

### Firefox for Android with GeckoView
Firefox for Android version 79+ features a completely new browser engine named [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView) that's not based on Android's native WebView anymore. It's [available for alpha and beta testers since at least June 2019](https://blog.mozilla.org/futurereleases/2019/06/27/reinventing-firefox-for-android-a-preview/) and now, in August 2020, they are rolling it out to users. It's a major upgrade like Quantum was for desktops and brings really great advances in performance and privacy. But Mozilla hit hard on extensions...

### Extensions support
Initially, it had no support for extensions whatsoever, as they were still developing the new API (which shall support WebExtensions). They started working with extension developers of the most used "recommend extensions" in _addons.mozilla.org_ and, in February, announced that uBlock Origin would be the first officially supported extension. It was good news since uBlock is a quite complex extension.

But things did not go so well. As of the rolling out, there are **just about a dozen extensions available**, all part of the "recommended extensions" list, and many users (including me) were bitten by this last upgrade. [This is all they had to say about extensions](https://support.mozilla.org/en-US/kb/whats-new-firefox-android-79):

> We would like to enable support for more extensions on the new Firefox for Android experience and we are currently evaluating ways we can do so without introducing the compatibility and security issues from the previous version of our mobile browser for Android. We'll provide updates as soon as we have more details. 

The page "[Developing extensions for Firefox for Android](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/)" doesn't add much:

> At the time of launch, only a limited number of [Recommended Extensions](https://support.mozilla.org/en-US/kb/recommended-extensions-program) will be supported. We would like to support more extensions and we are currently evaluating how to best do that. New announcements around mobile extension support will be posted on the [Add-ons Blog](https://blog.mozilla.org/addons/category/mobile/).

I'll summarize the relevant bits posted on the cited blog in the following comment. **Please, keep this issue open** so we can follow up the news and look for solutions and workarounds.

**Comment by tophf** [comment]
@leogama, thanks. Since it's possible to follow closed issues just the same, I'll reopen it once it's clear there's something that we can actually do about the problem. So far it looks like there's nothing we can do.

**Comment by leogama** [comment]
# Summary of Mozilla's [Add-ons Blog](https://blog.mozilla.org/addons/category/mobile/) recent posts
The remarks are mine.

Jun 27, 2019 – **Reinventing Firefox for Android: a Preview**
https://blog.mozilla.org/futurereleases/2019/06/27/reinventing-firefox-for-android-a-preview/

> While continuously improving Firefox Focus over time, we realized that users demanded **a full-fledged mobile browsing experience, but more private and secure** than any existing app. So we decided to make Firefox more like Focus, _but with all the ease and amenities_ of a full-featured mobile browser.

Oct 23, 2019 – **Firefox Preview/GeckoView Add-ons Support**
https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/

> Not only is it faster than ever, it also **opens up many opportunities for building deeper privacy features** that we have already started exploring, and a lot of users were wondering what this step meant for add-ons. We’re happy to confirm that **GeckoView is currently building support for extensions through the WebExtensions API**.

> Bringing GeckoView and Firefox Preview up to par with the APIs that were supported previously in Firefox for Android won’t happen overnight. For the remainder of 2019 and **leading into 2020, we are focusing on building support for _a selection of content_ from our Recommended Extensions program** that work well on mobile and cover a variety of utilities and features.

> At the moment, Firefox Preview **does not yet officially support extensions**. While some members of the community have discovered that **some extensions inadvertently work in Firefox Preview, we do not recommend attempting to install them until they are officially supported** as other issues may arise.

Feb 6, 2020 – **uBlock Origin available soon in new Firefox for Android Nightly**
https://blog.mozilla.org/addons/2020/02/06/ublock-origin-for-firefox-android-nightly/

> As GeckoView builds more support for WebExtensions APIs, **we will continue to enable other Recommended Extensions** to work in the new Firefox for Android.

> We want to ensure that any add-on supported in the new Firefox for Android provides **an exceptional, secure mobile experience to our users**. To this end, we are prioritizing Recommended Extensions that are optimized for different screen sizes and cover common mobile use cases. For these reasons, it’s possible that **not all the add-ons you have previously installed in Firefox for Android will be supported in the near future**. When an add-on you previously installed becomes supported, we will notify you.

Feb 11, 2020 – **FAQ for extension support in new Firefox for Android**
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

> _Can I install extensions from addons.mozilla.org to Firefox for Android?_
> No, in the near term you will need to install extensions from the Add-ons Manager on the new Firefox for Android. **For the time being, you will not be able to install extensions directly from addons.mozilla.org.**

> _Will add-ons not part of the Recommended Extensions program ever be supported on the new Firefox for Android?_
> We would like to expand our support to other add-ons. At this time, **we don’t have details on enabling support for extensions not part of the Recommended Extensions program** in the new Firefox for Android.

Apr 14, 2020 – **April Extensions for Firefox Preview**
https://blog.mozilla.org/addons/2020/04/14/april-extensions-for-firefox-preview/

> While we’re pleased to offer these six highly recommended add-ons as a starting point, it’s clear that add-on developers have more great ideas for extensions that can enhance the mobile browsing experience. **We intend to enable more add-ons _from the Recommended Extensions program_ within the next few months** and will be reaching out to developers soon.

Jul 7, 2020 – **New Extensions in Firefox for Android Nightly**
https://blog.mozilla.org/addons/2020/07/07/new-extensions-in-firefox-for-android-nightly-previously-firefox-preview/

Nothing new, they just repeated:
> If you have more questions on extensions in Firefox for Android Nightly, please check out our FAQ [the February 11 post]. We will be posting further updates about our future plans on this blog.

Therefore, unless ViolentMonkey makes itself into the "Recommend Extensions" VIP club —what I find extremally unlikely given the program' policies—, we are doomed with stock Firefox for Android. We'll be restricted to either staying with Firefox 68 (blocking upgrades or installing it via APK) or sideloading the extension using developer tools.

Of course, there's a lot of user complaints in the blog post's comments. Personally, I think Mozilla is mostly right on its approach as the majority of users is mostly concerned with overall speed and privacy (both of which are covered by the new browser engine, the built-in tracking protection and the already available extensions like uBlock). Power users like us, who choose Firefox as a mobile browser for its extensions and personalization features, can find workarounds to get their things working to their like until extensions support improves. Actually, for userscript addicts, we already do this.

**Comment by leogama** [comment]
Firefox for Android 79+ is essentially a new browser. Thinking in the long term, some things can be done or planned:

1. Test whether the current Firefox extension can work, even if with minor tweaks, with the GeckoView API.
    1. If it works, write a tutorial for sideloading it with `adb` or whatever;
    2. If it's incompatible, maybe join this with the Firefox Userscript API issue (#604) and look forward to making the extension compatible using it (don't know if this API is currently supported in GeckoView, I suspect it's not, but it may be included sometime soon).
2. For userscripts targetting websites that run in a single browser tab, like Progressive Web Applications, a good solution may be to install Firefox 68, Violentmonkey and the specific userscripts, and then creating the corresponding "apps" using the "Add to Home Screen" feature. Users can use these alongside Firefox Beta for general browsing for example. Even if each step in this setup is straightforward, a good tutorial joining everything up would be welcome.

Well, these are some ideas I'm planning to try out. Would be willing to contribute with the tutorials things.

Note: if you agree, please add the `firefox` tag here too. Thanks for your attention.

**Comment by leogama** [comment]
Related issues on [Tampermonkey's repo](https://github.com/Tampermonkey/tampermonkey/issues?q=):

- [Content Script API and User Script API](https://github.com/Tampermonkey/tampermonkey/issues/523)
- [Firefox for Android 79+](https://github.com/Tampermonkey/tampermonkey/issues/940)
- [Addition to _Recommended Extensions_ on addons.mozilla.org](https://github.com/Tampermonkey/tampermonkey/issues/1011)

Found nothing on [Greasymonkey's](https://github.com/greasemonkey/greasemonkey/issues?q=)...

**Comment by jesus2099** [comment]
@tophf, could we keep this ticket open to avoid people who may file duplicate issues?
There is the [external](https://github.com/violentmonkey/violentmonkey/labels/external) tag, already, to say we cannot do anything about it yet.

BTW, here is a [related issue for Stylus](https://github.com/openstyles/stylus/issues/647).

**Comment by tophf** [comment]
People open duplicate issues anyway regardless of whether it's open or not so no point opening it just to avoid that. There's nothing we can do anyway. Just chill. No fuss.

**Comment by tophf** [comment]
So the problem is apparently solved, everyone can relax: all extensions will be enabled gradually whereas FF Nightly will load all extensions from AMO some time [later this month](https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/).

**Comment by jesus2099** [comment]
Apparently, I'm not sure, AMO would stand for _Mozilla add-ons_ (MAO).

**Comment by tophf** [comment]
AMO is a standard abbreviation in FF world which stands for **a**ddons.**m**ozilla.**o**rg

**Comment by eNV25** [comment]
Here is a fork of the new Firefox:
https://github.com/fork-maintainers/iceweasel
It uses a custom recommended list so you don't have to wait for Mozilla to allow more extensions. You can request to make this extension (or a testing version available) so it can be tested.

**Comment by jesus2099** [comment]
Some [testing instructions](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/) were posted on https://github.com/mozilla-mobile/fenix/issues/14034#issuecomment-696247661

**Comment by KrasnayaPloshchad** [comment]
Mozilla decided to made further support in the future releases.
https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/

**Comment by lorenzos** [comment]
Despite what they're saying, looks like they have no intention at all to make all of the extension available on the release channel.

> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Looks like they give us the ability to install AMO extensions on the Nigthly channel only, but the developer have to opt-in (i.e. create a "collection" on AMO, whatever it means) and users are required to access secret menus, enable debugging options and manually enter IDs in order to install the extension they want...

> However, we are continuously working on increasing support, taking into account usage and feedback to ensure we are making the most of our available resources.

Yeah, sure.

**Comment by tophf** [comment]
AFAICT Those arcane manipulations are for the users who want to install extensions so anyone can jump through the hoops without us developers doing anything.

**Comment by lorenzos** [comment]
> AFAICT Those arcane manipulations are for the users who want to install extensions so anyone can jump through the hoops without us developers doing anything. Including the bit about collections.

Right, I got it wrong and fixed my post, thanks. Doesn't change much, however, this still shows IMHO their unwillingness to make any AMO extension available to regular users. Given this was possible in the older version, I'm expecting a similar move on the desktop.

**Comment by orionlee** [comment]
In recent Firefox Nightly build, you can install violentmonkey (or any other addons on addons.mozilla.org). I have started using it.

- Instruction to enable Firefox Nightly to install any addons on addons.mozilla.org
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

- The scripts I run only use a couple of `GM_` APIs, so your mileage might vary. In particular, `GM_addStyle()` works. `GM_notification()` appears to be a no-op (it does not cause errors but it does not show anything either).

- There is a snag during script installation that might make you think it's not working. It is reported as https://github.com/mozilla-mobile/fenix/issues/16164

**Comment by jesus2099** [comment]
From a comment over there, there is a wiki that explains [how extensions can be added to their list of recommended extensions](https://wiki.mozilla.org/AMO/Featured_Board_Process).
I read it but I still don't really know what is the first step.
Apparently, waiting for some blog post but what blog? There is no URL.

> _Every 6 months, a call will go out via the Add-ons Blog for volunteers to participate in choosing recommended extensions._

**Comment by orionlee** [comment]
What they support is let you create your own collection of addons, then set Firefox Nightly to use it, rather than using the recommended one. In other words,
- Go to [Firefox' addon site](https://addons.mozilla.org/en-US/android/)
- Find the add on you need, e.g., [violentmonkey](https://addons.mozilla.org/en-US/android/addon/violentmonkey/)
- Add it/them to your own collection. You'd need to create an account there if you don't have one.
- Chances are you use other add-ons too. You'd need to add them to your own collection as well.
- Then on Firefox Nightly, change settings to use your own addon collection rather than the recommended one. Their [blog post](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) has the steps.

**Comment by jesus2099** [comment]
FWIW, I wrote to amo-featured@mozilla.org to request Violentmonkey addition to their recommended add-ons.

**Comment by jesus2099** [comment]
New email sent as I received no replies:

> Hello,
>
> I reiterate my request for Violentmonkey and Stylus extensions support.
> I have been using them now in Kiwi Browser for about a year, as I was strongly advised to stop using old Firefox 68, for security reasons.
>
> Regards,
> jesus2099
>
> https://violentmonkey.github.io
> https://add0n.com/stylus.html
> https://kiwibrowser.com

**Comment by Poopooracoocoo** [comment]
An update on this: Mozilla is planning general availability of MV3 extensions. _NOT_ MV2 extensions.

**Comment by rokejulianlockhart** [comment]
@tophf, regarding https://github.com/violentmonkey/violentmonkey/issues/1042#issuecomment-678805209, maybe close as unplanned rather than completed.

**Comment by jesus2099** [comment]
Apparently, [Firefox will support add-ons](https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/) back again “**soon**”.

**Comment by rokejulianlockhart** [comment]
Indeed, @jesus2099: https://bugzilla.mozilla.org/show_bug.cgi?id=1796184

**Comment by jesus2099** [comment]
Hi @tophf,
Apparently there are steps to make sure our add-on will be available in upcoming Firefox for Android:

https://blog.mozilla.org/addons/2023/11/01/is-your-extension-ready-for-firefox-for-android/
