### ISSUE TITLE
Violentmonkey not working on redirects

### ISSUE THREAD

**Issue by vdurante** [violentmonkey/violentmonkey#1046]
### What is the problem?
Google Drive links may be redirected back and forth based on authentication. Violentmonkey doesn't recognize those redirects and the script URL match is not recognized 

### How to reproduce it?
1. Log into multiple accounts
2. Create a Google Sheet document
3. Create a script for the URL `https://docs.google.com/spreadsheets/d/<spreadsheet-id>/*`
4. Reload page
5. Notice that Violentmonkey doesn't recognize the website's URL

### What is the expected result?
Violentmonkey should recognize the final URL after redirects

### What is the actual result?
When I access a google sheet using the URL above, it redirects me to `https://docs.google.com/spreadsheets/u/<user-number>/d/<spreadsheet-id>/*` and back to `https://docs.google.com/spreadsheets/d/<spreadsheet-id>/*`. This causes Violentmonkey to not recognize the URL

![ezgif-5-e8a0da65d77b](https://user-images.githubusercontent.com/5401232/90771497-bfa84000-e2c9-11ea-99a4-10129716f3fd.gif)

This may be a result of the website's redirect methods. Maybe Violentmonkey should detect URL changes that don't trigger a proper browser redirect event or something.

### Environment
- Browser: Edge
- Browser version: 84.0.522.61
- Violentmonkey version: v2.12.7
- OS: Windows

**Comment by tophf** [comment]
Sounds like a standard SPA site problem: the site opens its root path first e.g. https://docs.google.com/spreadsheets/ then instantly navigates via history.replaceState to the actual path. Violentmonkey, just like any other userscript engine, only runs scripts when the document is created for the first time.

In cases like this your `@match` should cover the entire site e.g. `https://docs.google.com/spreadsheets/*` and then you need to use various methods of detecting change in the page, for example MutationObserver and [other methods](https://stackoverflow.com/a/39508954).

See also #1028.
