### ISSUE TITLE
All my scripts vanished

### ISSUE THREAD

**Issue by Yoposoc** [violentmonkey/violentmonkey#1048]
### What is the problem?

All my scripts disappeared for some reason.

### How to reproduce it?
No idea. I hadn't used my browser that violentmonkey is on for a couple days. I just opened today and found that all my scripts are gone. Totally gone. Really sad as one was a private script that I got from a friend.
I found an old issue ticket https://github.com/violentmonkey/violentmonkey/issues/599 that is essentially the same as what I experienced AFAIK. No error, no issues, just poof.

### What is the expected result?
My scripts shouldn't disappear! At least not without even some sort of error notification.

### What is the actual result?
None of the scripts are left. I'm not sure where, if they exist, on my laptop they would be in. It's really my fault I didn't have and set up automatic cloud backup. I just found that and in a panic, set that up, and I guess I had been doing it before? It automatically restored a bunch of scripts from a while ago, but not the ones I was using.

Is there any way/place I should look in to try to restore them?

### Environment
- Browser: Waterfox 64-bit
- Browser version: 2020.07.02
- Violentmonkey version: 2.12.7
- OS:Windows 10

**Comment by tophf** [comment]
There's nothing we can do about it, unfortunately. You can try the generic tutorials for finding and restoring extension data in the browser profile. Personally, I'm using a daily backup of the entire data drive for the last 10 years...

**Comment by Yoposoc** [comment]
where does violentmonkey save the scripts/script data? I can't quite find it after reading about it online...

**Comment by tophf** [comment]
`Local Extension Settings` in the profile directory.

**Comment by Yoposoc** [comment]
I couldn't find this folder, oh well. I found profile folders for waterfox but did not find a trace of some of the scripts I had. Shame.
