### ISSUE TITLE
Violentmonkey beta in Chrome Web Store

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1052]
*(Continuing issue #5)*

My suggestion is to consider publishing Violentmonkey beta in Chrome Web Store (CWS).

Currently, with every new rc version (there can be a lot, 15 versions since last stable release v2.12.7 in last February), you have to manually install it as an unpacked extension in Chrome.

I believe it would be convenient and facilitate testing to have a separate Violentmonkey beta build. The stable version and the beta version will be installed as two distinct extensions: they will auto-update independently of each other, and won't share any settings or storage.

For reference, I use the beta/dev builds of uBlock Origin, Tampermonkey, and Stylus.
*(note: uBlock Origin publishes uBO beta builds for Firefox too, signed and self-hosted in its [GitHub repo](https://github.com/gorhill/uBlock/releases))*.

PS. Thank you for your tremendous work all this time!

**Comment by gera2ld** [comment]
Thank you for your suggestion.

I think self-hosted version on AMO is a good idea for testing, since it can be easily updated to the stable version if the beta channel is no longer needed. The only concern is that data might be unexpectedly lost when something goes wrong with the extension. But I think power users that choose to use a testing version should be able to handle it.

> I believe it would be convenient and facilitate testing to have a separate Violentmonkey beta build. The stable version and the beta version will be installed as two distinct extensions: they will auto-update independently of each other, and won't share any settings or storage.

Does that mean two versions for two different groups of users? It's like maintaining two independent extensions, and both need to be reviewed 😅.

When coming to a stable release, the two versions may be exactly the same. Will it be a problem if two different extensions have the same or similar code? I think I've read from somewhere that this is not recommended or even not allowed in CWS, but I can't find the reference any more.

**Comment by tophf** [comment]
In CWS you can have beta extensions with the same code without any problems.

**Comment by darkred** [comment]
Yes, the two variants of the extension will both have to pass the CWS review procedure.
But, there's an effort to improve that procedure in the last months *( see [1](https://github.com/uBlockOrigin/uBlock-issues/issues/745#issuecomment-545654074), [2](https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3g3jlq/)* )

And, I believe that, if a problem occurs with the version being stuck in 'rejected' status,
starting a discussion in the [chromium-extensions](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) list, or pinging someone like the so kind @dotproto in [Twitter](https://twitter.com/DotProto), 
will surely help in solving it.

In general, I think it's worth the effort, and will help get more users to install and test the beta version on a constant basis. CWS/Chrome's user base is way bigger than AMO/Firefox's.

&nbsp;

PS. For reference: [CWS spam policy FAQ | Can I have both a test version and a production version of my extension?](https://developer.chrome.com/webstore/spam-faq#can-i%20have%20both%20a%20test%20version%20and%20a%20production%20version%20of%20my%20extension?)

**Comment by gera2ld** [comment]
FYI the beta version was submitted to CWS on November 23 and has a status of `Pending review` now.
CWS says that the extension requires an in-depth review because it runs for `<all-url>`. So we'll just wait.

**Comment by darkred** [comment]
I'm so glad, thank you very much! (and, gotta love the ninja monkey icon!) 

---

I see in [the CWS page](https://chrome.google.com/webstore/detail/violentmonkey/opokoaglpekkimldnlggpoagmjegichg) that it's named exactly as the stable release: `Violentmonkey`, 
i.e. the word `Beta` is only in the description, not also in the name: 
<details>
<summary>Screenshot of CWS search results:</summary>

![2020-11-25_121920](https://user-images.githubusercontent.com/723651/100214515-a9d59700-2f18-11eb-86e4-311dc09c707d.jpg)
</details>

Shouldn't it named something like: 
`Violentmonkey (Beta)` *(as in [Stylus](https://chrome.google.com/webstore/detail/stylus-beta/apmmpaebfobifelkijhaljbmpcgbjbdo) and [Tampermonkey](https://chrome.google.com/webstore/detail/gcalenpjmijncebpfijmoaglllgpjagf) betas)* or 
`Violentmonkey (development build)` *(as in [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) beta)* ?

**Comment by gera2ld** [comment]
@darkred You are absolutely right. I noticed that right after submitted. I'll add `BETA` to the name in the next beta release.

**Comment by darkred** [comment]
With the new beta release the name in CWS is fixed now, thank you. 👍

**Comment by darkred** [comment]
This is minor, but would it be possible to display the current beta version in: Dashboard|About ?
Currently (beta v2.12.9.2 in Chrome) it displays the latest stable relevase version, 2.12.9 instead :  
![2020-12-29_174151](https://user-images.githubusercontent.com/723651/103295747-4817b980-49fd-11eb-8a60-b1a21ffd17c4.jpg)

**Comment by tophf** [comment]
Fixed in 2ffe90fb.

**Comment by darkred** [comment]
Thank you for the quick fix!
