### ISSUE TITLE
violentmonkey for Samsung internet browser (android) 

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#1053]
Samsung internet beta 13 just added webrequest api to his Android browser, is it possible to port violent monkey to it?
thanks.

**Comment by tophf** [comment]
Actually I'm closing this because having it open won't improve the near zero chance that someone will do it for us. This is one of those miraculous things that would be nice to have but there's no reason to expect them to happen in real life. If it happens, it happens.
