### ISSUE TITLE
Theme not applying on every refresh inside of a user script.

### ISSUE THREAD

**Issue by jboutin** [violentmonkey/violentmonkey#1054]
### What is the problem?

The custom theme specified in the advanced configuration doesn't load as expected on every page refresh. Seems to only apply the theme at random.

### How to reproduce it?
1. Set a custom theme in the advanced configuration (**I'm using** ```  "theme": "material-palenight",```)
2. Open a saved user script.
3. Refresh the page multiple times.

### What is the expected result?
The expected result would be for the custom theme to apply on every page refresh.

### What is the actual result?
The custom specified theme seems to apply at random. No indication of why it only loads sometimes.

### Screenshot / Video of bug:
[Zipped video of the defect in action.](https://github.com/violentmonkey/violentmonkey/files/5177430/Bug.zip)

### Environment
- **Browser**: Google Chrome Canary
- **Browser version**: Version 87.0.4254.2 (Official Build) 64-bit
- **Violentmonkey version**: Violentmonkey V2.12.7
- **OS**: Windows 10 X64 build 1909

**Comment by tophf** [comment]
Like the note says Violentmonkey does not support all parameters, specifically `theme` because we don't ship any of the themes. You can copy the theme contents into `custom CSS` input in Violentmonkey settings.

I'll investigate the intermittent behavior here though.

**Comment by jboutin** [comment]
> You can copy the theme contents into `custom CSS` input in Violentmonkey settings

Copying the CSS into the custom CSS input didn't seem to do anything. Not sure if I'd need to update selectors or anything.

**Comment by tophf** [comment]
Looks like it's fixed by d1539d3aa95fd17760657ef64ed5ba306f9a5e32, which also makes applying custom themes easier (no need to edit the CSS anymore). Will be included in the next [release candidate](https://github.com/violentmonkey/violentmonkey/releases).
