### ISSUE TITLE
Potential issues with how @requires get inlined

### ISSUE THREAD

**Issue by qimasho** [violentmonkey/violentmonkey#1057]
# What is the problem?

Some people reported that my userscript https://greasyfork.org/en/scripts/408038-thread-media-viewer
is not working in Violentmonkey on Chrome. Didn't catch it as I'm using Tampermonkey in FF atm, and everything is working fine there.

The error on initialization:

```
Uncaught TypeError: Illegal invocation
```

is coming from preact/hooks dependency inlined by violentmonkey, so I suspect the issue might be on this side?

Or am I doing something wrong?

### How to reproduce it?
1. Install https://greasyfork.org/en/scripts/408038-thread-media-viewer
2. Open https://boards.4channel.org/wsg/catalog
3. `Uncaught TypeError: Illegal invocation`
4. Cry T.T

### What is the expected result?

Happiness.

### What is the actual result?

Tears.

### Environment
- Browser: Chrome
- Browser version: 85.0.4183.102
- Violentmonkey version: 2.12.7
- OS: Win 10

**Comment by tophf** [comment]
I see it in 2.12.7, but I don't see it in the [upcoming RC](https://github.com/violentmonkey/violentmonkey/releases) so I guess we've fixed it.
