### ISSUE TITLE
能否对Greasyfork的安装按钮增加重装/更新版本的提示？

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#106]
Tampermonkey 一个非常出色的功能。
![default](https://cloud.githubusercontent.com/assets/2649544/26315709/91011992-3f44-11e7-9bb5-5d17f3a19a1a.png)
![default](https://cloud.githubusercontent.com/assets/2649544/26315718/9edc2002-3f44-11e7-8737-fede557fac61.png)
![default](https://cloud.githubusercontent.com/assets/2649544/26315739/ae17756c-3f44-11e7-9b19-f0dc4b7e973e.png)

**Comment by gera2ld** [comment]
这个是greasyfork专门为tampermonkey定制的。。。不知道擅自修改这个页面或者伪装成tampermonkey会不会有什么坑。

**Comment by ivysrono** [comment]
钦定？

**Comment by gera2ld** [comment]
感觉他们已经深度合作了。。Orz

**Comment by gera2ld** [comment]
这个不做在插件里了，毕竟没有官方合作。
考虑加一个类似TM的检测脚本是否安装的接口，然后允许第三方用脚本实现相关功能。

**Comment by gera2ld** [comment]
脚本已发布，请与暴力猴v2.6.4一起使用。

脚本链接：<https://greasyfork.org/zh-CN/scripts/30346-vm-detector>
