### ISSUE TITLE
Differences of VM to Greasemonkey, Tampermonkey and Firemonkey? Support for GM_addStyle()?

### ISSUE THREAD

**Issue by clsven** [violentmonkey/violentmonkey#1061]
What are the differences to Greasemonkey, Tampermonkey and FireMonkey?

Does ViolentMonkey support GM_addStyle() functions?

**Comment by tophf** [comment]
You can compile a comparison table yourself based on https://violentmonkey.github.io/api/ or find an existing one. GM_addStyle is supported.
