### ISSUE TITLE
Incorrect displaying of the cursor in the text editor

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1067]
_It's strange that there was no such issue here._

I rarely use ViolentMonkey (I use commonly [User JavaScript and CSS](https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld)), but sometime I need to write classic userscripts.

And every time I have used the editor in VM it always was a pain. 

Why?

Because of this:
![Screenshot](https://user-images.githubusercontent.com/16310547/94341856-82944380-0015-11eb-97a0-ad1d472f87ff.png)
![Screenshot_1](https://user-images.githubusercontent.com/16310547/94341857-845e0700-0015-11eb-8be2-19aa5243244f.png)
_coupled with the cursor teleportation to inside the brackets._

These pictures look the same thing. Probably. 
But **it represents the two different cursor positions** in the editor! 

This is a very annoying cursor behaviour.
Disable, remove or do something with it.

Also it doesn't look much better:
![Screenshot_2](https://user-images.githubusercontent.com/16310547/94341945-55946080-0016-11eb-83e6-0d1df72f5bca.png)

**Comment by gera2ld** [comment]
I don't see what is annoying and what is expected from your description. Please make it clear by filling the issue template.
Anyways, I think the current behavior of cursor next to brackets is commonly used, in many popular editors, e.g. VSCode.

ps. You can always [use your own editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/) with Violentmonkey.

**Comment by AlttiRi** [comment]
The jumping to inside the brackets is OK.

The problem is, that it's impossible to understand there is the cursor: inside the brackets or right of them.
Also when the cursor is left from the brackets it displays the second cursor inside the brackets.

**Comment by gera2ld** [comment]
So it is a problem of the [`eclipse` theme of CodeMirror](https://codemirror.net/demo/theme.html#eclipse).
Maybe we should change the default theme in light color scheme.

**Comment by AlttiRi** [comment]
I _**seeeee**_ now.

The cursor is always one. _But._
It is almost invisible in the right position. It's really hard to see its blinking.

The style of selected brackets creates the visibility of the cursor. So it look like the cursor is always inside.

**Comment by tophf** [comment]
CodeMirror no longer uses the bad pure green `#00ff00`, it switched to `#00bb00` so we can revert to the `default` theme now, I guess, gonna open a PR now...
