### ISSUE TITLE
Release the already existing fix of `GM_download` and `GM_xmlHttpRequest`

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1071]
### What is the problem?

`GM_download` and `GM_xmlHttpRequest` do not work with files over ~30 MB

### How to reproduce it?
```js
// ==UserScript==
// @name        Issue 1071
// @namespace   Violentmonkey Scripts
// @match       https://github.com/violentmonkey/violentmonkey/issues/1071
// @grant       GM_download
// ==/UserScript==

GM_download({
    url: "https://giant.gfycat.com/GrimGrossKoodoo.mp4", // 31.4 MiB (33_016_734 bytes)
    name: "33_016_734.mp4",
    onerror: e => console.error(e)
});

GM_download({
    url: "https://giant.gfycat.com/BonyFeminineLadybird.mp4", // 20.8 MiB (21_896_201 bytes)
    name: "21_896_201.mp4",
    onerror: e => console.error(e)
});

```

### What is the expected result?
It downloads both files with the release version of VM.
### What is the actual result?
The release version of VM downloads only the second file. But VM Release Candidate works OK.

### Env
- Chromium based browser.
---

Downloading of files is one of main functions of userscripts. And it does not work. It's even worse – it does not work in some cases (`onerror` callback is not triggered in this case). So a user can think that his userscript works (he see the downloaded files), but the script may do not download some files. And user will lose some data, because of he thinks that userscript works as planned.

I think it's major bug and the fix should release the fix as soon as possible. The fix already exists. 
The last update was more than half of the year ago. How long are you going to wait for?

**Comment by tophf** [comment]
I don't see people complaining which means this specific use case is really rare probably because most people use Tampermonkey. Also, no need to open a new issue: you can mention `@gera2ld` in any related issue.
