### ISSUE TITLE
[text editor] Brackets behaviour

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1072]
In short words.

I have `c(b(a(/*cursor is here*/))`.

I want to write `)`. I type `)`, and what happens? The cursor just moves to the right. For this example I need to type `)` 3 times to do that I would do in any other text editor with one time. It's even not default behaviour of CodeMirror.

**Comment by gera2ld** [comment]
It's the default behavior of CodeMirror's [closebracket feature](https://codemirror.net/demo/closebrackets.html). Maybe you should file an issue there.

VSCode has similar feature but seems to be more intelligent when deciding whether to add a new `)` or reuse the following one.

**Comment by tophf** [comment]
The same is observed in devtools which uses CodeMirror so indeed if a fix is possible it should be done in CodeMirror. Its author may reject the suggestion though so in that case we'll reopen this issue and try to fix it ourselves.
