### ISSUE TITLE
2.6.3 Firefox 版数据导出不正常

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#108]
Chrome没问题。
1、框内显示不换行。
2、导出为zip没反应。

**Comment by gera2ld** [comment]
1. 已知bug，下个版本会修复
2. Firefox的bug，过度限制了扩展页面的权限，暂时won't fix

ref: <https://bugzilla.mozilla.org/show_bug.cgi?id=1331176>

**Comment by ivysrono** [comment]
[Redirector :: Firefox 附加组件](https://addons.mozilla.org/zh-CN/firefox/addon/redirector/)
@gera2ld 终于想起来了，这个扩展能导入导出json，有没有参考价值？

**Comment by gera2ld** [comment]
看了一下他的代码，他的数据量小，直接把数据全部写在URL里了，所以可以导出。
VM脚本导出数据比较大，如果全部写到URL里会超过长度限制，导致浏览器卡死甚至崩溃。（最早的版本就是这么做的）

**Comment by ivysrono** [comment]
@gera2ld 
发现TM可以完整导出扩展和脚本的所有设置，他是怎么做到的。
![default](https://user-images.githubusercontent.com/2649544/27669084-846da818-5cb7-11e7-9302-1e6663dbb6c8.png)
