### ISSUE TITLE
userscript isn't installed for iframe on FireFox in some cases.   (Works on Chrome.)

### ISSUE THREAD

**Issue by fapnip** [violentmonkey/violentmonkey#1085]
### What is the problem?
Based on @include settings, Userscript should install for both the host page and an iframe on the page on Firefox.  Only installs for host page.  (Works as expected in Chrome.)

### How to reproduce it?
1. Install the following userscript on Firefox:
https://openuserjs.org/scripts/fapnip/EOS_Test_1

2. Open console in browser.

3. Visit this page:
https://milovana.com/webteases/showtease.php?id=47174&key=537c4e2f09

### What is the expected result?
On the console, you should see:
Running EOS Test #1 v0.1 on milovana.com
Running EOS Test #1 v0.1 on eosscript.com

### What is the actual result?
You only see:
Running EOS Test #1 v0.1 on milovana.com

No CSP errors or the like are reported.

### Environment
- Browser: FireFox
- Browser version: 81.0.2
- Violentmonkey version: 2.12.7
- Violentmonkey [pre-release behavior](https://github.com/violentmonkey/violentmonkey/releases): Same
- OS: Windows 10

**Comment by tophf** [comment]
Violentmonkey's own internal content scripts don't run there so evidently it's a bug in FF.

**Comment by tophf** [comment]
BTW there's a workaround for you: remove the `sandbox` attribute when running in the main document.
