### ISSUE TITLE
"incognito": "split"

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1086]
Currently the extension has no `"incognito": "split"` in `manifest.json` so all connections go through the common window even a userscript is running in the incognito tab.

It can be a problem if an Opera user that uses "Opera VPN" in an incognito tab with a userscript that loads some data from this site due to Violentmonkey that will load the data through the common window (instead the incognito one) where all connection does not go through that HTTPS proxy. It will disclose the site visiting to IPS, and IP to visited site.

Another case, not Opera related:
You open a site in the incognito tab that uses DDoS protection (Cloudflare's, or Google's one), you pass a captcha, but the userscript probably will not work due to you will not have the passed captcha in the common window, and the downloading of a content will be interrupted with 503 HTTP code.

Also it will allow to edit scripts in the incognito window.

It can be fixed with one line: add`"incognito": "split"` to `manifest.json` . 
Note: [It works only in Chrome.](https://bugzilla.mozilla.org/show_bug.cgi?id=1380812)

By the way, delete from the Chrome version manifest the Firefox related code: `browser_specific_settings: ...`. It's annoying to see all time in the extension's error log: `Unrecognized manifest key 'browser_specific_settings'.`.

---

It works OK, but there is one problem with the synchronisation of the GM storage (`GM_getValue`, `GM_setValue`).
The changes made in the other mode tab is visible only after the page reloading. The tabs in one mode have no such problem: after using of `GM_getValue` in one tab, `GM_setValue` returns the updated value in the other tab.
But this problem happens only if you interact with site in both private tab and common mode tab at the one moment.

Here is code to test it (do not forget to add `"incognito": "split"` in the manifest):
```js
// ==UserScript==
// @name        splite mode - example
// @namespace   Violentmonkey Scripts
// @match       *://example.com/
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// ==/UserScript==


document.querySelector("div").remove();
const btn = document.querySelector("body").insertAdjacentHTML("afterBegin", `
<div>
  <button id="clear-button">Clear</button>
  <button id="increment-button">Increment</button>
  <span id="value"></span>
</div>
`);

const incrementButton = document.querySelector("#increment-button");
const clearButton = document.querySelector("#clear-button");
const valueElem = document.querySelector("#value");

value.textContent = GM_getValue("value", 0);

incrementButton.addEventListener("click", _ => {
  const newValue = GM_getValue("value", 0) + 1;
  valueElem.textContent = newValue;
  GM_setValue("value", newValue);
});
clearButton.addEventListener("click", _ => {
  GM_deleteValue("value");
  valueElem.textContent = 0;
});

setInterval(_ =>  valueElem.textContent = GM_getValue("value", 0), 333);
```

**Comment by tophf** [comment]
Not sure we should implement it a Chrome-only feature that causes such a big difference in behavior. Thoughts, @gera2ld?

**Comment by tophf** [comment]
> It's annoying to see all time in the extension's error log: Unrecognized manifest key 'browser_specific_settings'..

It is, but gera2ld wants to have a single manifest.json for all browsers. Meanwhile, you can disable `Collect errors` in extension details page.

**Comment by gera2ld** [comment]
This is a low level and breaking change that will prevent us from keeping the current benefits. What if a userscript wants to make connections with shared credentials?

I think a better solution for this issue is to create another extension with intrinsic `"incognito": "split"`, or find a way to decide how the connections are made programmatically.
