### ISSUE TITLE
Incorrect UUID generation

### ISSUE THREAD

**Issue by b9a1** [violentmonkey/violentmonkey#1087]
https://github.com/violentmonkey/violentmonkey/blob/386aa7c09d23d0c1e7e6e88ebe16b81581bf890c/src/background/utils/db.js#L358-L361

This function does not always generate a valid UUID. A random UUID `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` should have `M`=`4` and `N` chosen from `8` to `b`.

### See also
* [Algorithm for creating a random UUID in RFC 4122](https://tools.ietf.org/html/rfc4122#section-4.4)
* [UUID on Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier)
* [Implementation of Greasemonkey](https://github.com/greasemonkey/greasemonkey/blob/e0caac00f34f39fe87e23e43df7c33d847f46e11/src/user-script-obj.js#L68-L88)

**Comment by tophf** [comment]
We can change the algorithm but what does "valid" mean here? Do you mean there's a high chance of collisions? If you mean it doesn't match the RFC then maybe it was never the intention so who cares.

**Comment by tophf** [comment]
Anyway, this is a good chance to get rid of getRnd4 :-) in favor of the faster crypto.getRandomValues

**Comment by b9a1** [comment]
Yes it’s about conformance, and maybe avoiding confusion, too.

Talking about randomness, may I ask what `0x10bde6a2` does? Why not pure random?

**Comment by tophf** [comment]
> what 0x10bde6a2 does? 

@gera2ld?

**Comment by gera2ld** [comment]
Just some magic number to mask IDs. It is useless indeed.
