### ISSUE TITLE
Firefox版本几个问题和建议

### ISSUE THREAD

**Issue by liuxb** [violentmonkey/violentmonkey#109]
1 建议在manifest.json中加入"applications": {"gecko": {"id": "{aecec67f-0d10-4fa7-b7c7-609a2db280cf}"}

2 问题，firefox 55a1 nightly，扩展2.6.3，从外部把一个.user.js脚本拖放入firefox窗口，并没有辨认出是猴子脚本并安装，而是直接在当前标签打开文件了。

3 安装本地脚本文件，并选择track local file。如果当前编辑窗口关闭后，再次打开，仍然可以和本地文件保持同步吗？ 如果本地文件删除了后，再次在同样路径重建一个同名文件，还能保持同步吗？

4 可以考虑支持@require file:///C:/test.js，这样的功能吗？这个感觉很灵活。

谢谢！

**Comment by gera2ld** [comment]
3. 关闭后不能同步。保持窗口的情况下，同路径文件可以保持同步。
4. 不能，脚本是跨设备的，不应有本地路径。

**Comment by gera2ld** [comment]
2 见 #114

**Comment by gera2ld** [comment]
1. 暂时没这个必要？如果你觉得有必要再打开此issue

**Comment by liuxb** [comment]
不好意思，打开一下。
1 有的时候，会打开设定xpinstall.signatures.required;false，并删除META-INF\，这时扩展安装会报错说损坏，加上"applications": {"gecko": {"id": "{aecec67f-0d10-4fa7-b7c7-609a2db280cf}"}就好了。另外好像其他webext扩展都有加。
4 这个主要是看见tampermonkey有这个功能，https://forum.tampermonkey.net/viewtopic.php?p=1832#p1832，调用外部编辑器的另一种方法，比起track local file的好处是可以随时更改外部js的路径。不过目前只有chrome才可以，firefox还不支持，https://github.com/Tampermonkey/tampermonkey/issues/347。以后再说吧。
最后，希望尽快出一个修复了拖放.user.js的firefox版本，谢谢。

**Comment by gera2ld** [comment]
新版已放出：<https://github.com/violentmonkey/violentmonkey/releases/tag/v2.6.4>
