### ISSUE TITLE
Dashboard: "Failed fetching update information" for my userscript

### ISSUE THREAD

**Issue by RudeySH** [violentmonkey/violentmonkey#1090]
I have a couple of userscripts, but Violentmonkey's dashboard can't seem to check for updates. I'm hosting these userscripts on my own domain. I'm confident there must be something wrong with the userscript, but I can't figure it out. There doesn't seem to be a way to debug it. There's no information in the console or network tab.

1. Install userscript: https://steamhunters.com/userscripts/steam-games-analyzer.user.js
2. Go to Violentmonkey dashboard
3. Click the "Check for updates" button underneath the userscript.

### Environment
- Browser: Chrome
- Browser version: 86.0.4240.111 (Official Build) (64-bit)
- Violentmonkey version: v2.12.7
- OS: Windows 10 Home

**Comment by tophf** [comment]
The problem is caused by our `Accept: text/x-userscript-meta` HTTP header. We will add a `*/*` fallback in the linked PR.
