### ISSUE TITLE
加载脚本依赖发生错误

### ISSUE THREAD

**Issue by BaiBuCYBGT** [violentmonkey/violentmonkey#1096]
### What is the problem?
有些脚本无法安装
正在加载脚本依赖...（1/2）
加载脚本依赖发生错误
### How to reproduce it?
1.用户脚本上找一个脚本
2.点击安装此脚本
3.正在加载脚本依赖...（1/2）
4.加载脚本依赖发生错误

### What is the expected result?
确认安装
### What is the actual result?
加载脚本依赖发生错误

### Environment
- Browser:Firefox
- Browser version:82.0.2
- Violentmonkey version:2.12.7
- Violentmonkey [pre-release behavior](https://github.com/violentmonkey/violentmonkey/releases):
- OS:windows10 20h2

**Comment by tophf** [comment]
Cannot reproduce. Probably a network problem. Try reloading the installer tab. Try the upcoming [release candidate](https://github.com/violentmonkey/violentmonkey/releases).
