### ISSUE TITLE
查看暴力猴的简介会导致fenix浏览器崩溃

### ISSUE THREAD

**Issue by mini536** [violentmonkey/violentmonkey#1099]
### What is the problem?
查看暴力猴的简介会导致fenix浏览器崩溃
### How to reproduce it?
1.把暴力猴添加到收藏夹
2.浏览器自定义为自己账号的收藏集
3.点开暴力猴介绍
4.浏览器崩溃

### Environment
- Browser:火狐
- Browser version:84
- Violentmonkey version:任何版本
- Violentmonkey [pre-release behavior](https://github.com/violentmonkey/violentmonkey/releases):
- OS:安卓

**Comment by gera2ld** [comment]
“暴力猴的简介”具体是指哪个页面？

**Comment by mini536** [comment]
> “暴力猴的简介”具体是指哪个页面？

![Screenshot_2020-11-03-10-29-31-455_org mozilla fenix](https://user-images.githubusercontent.com/32984303/97945531-c7548c80-1dc2-11eb-9e78-c149b1838fe5.png)

**Comment by gera2ld** [comment]
无法重现，请描述完整步骤。

另外，这个时候暴力猴还没有安装，应该是浏览器的问题，可以去fenix那边反馈。
