### ISSUE TITLE
Limitation in 1000 symbols when copying from editor

### ISSUE THREAD

**Issue by AlexBeLi** [violentmonkey/violentmonkey#110]
When I copy more than 1000 at paste inserted only symbol -
Firefox 55, latest Nightly. Violentmonkey 2.6.3

**Comment by gera2ld** [comment]
Not sure what you mean, I test copy and paste on Firefox Nightly but see nothing wrong. Can you explain it with a bit more detail please?

**Comment by AlexBeLi** [comment]
Hmm...After investigation I understood that it related with dom.event.clipboardevents.enabled;false... But if selected less than 1000 symbols copying works fine even with dom.event.clipboardevents.enabled;false. And copying is slow for large scripts like https://github.com/YePpHa/YouTubeCenter/wiki but this maybe is not fixable for webext.
I think this issue can be closed, though imo this pref not must touching moz-extension scheme, only sites.
Maybe you will be add bug to bugzilla?

**Comment by AlexBeLi** [comment]
Fixed by 2.8.7 (maybe before) on latest Nightly (2017.09.05).
