### ISSUE TITLE
[Firefox] Scripts share the same window wrapper if `@inject-into content` is used

### ISSUE THREAD

**Issue by chocolateboy** [violentmonkey/violentmonkey#1102]
**keywords**: leak, pollute, pollution, isolate, isolated, conflict, conflicting

### What is the problem?

The same `window` wrapper is shared across multiple scripts running on the same page if `@inject-into content` is used, i.e. if the [site uses CSP](https://github.com/violentmonkey/violentmonkey/issues/1001). This makes it impossible to run scripts which require incompatible dependencies, such as different versions of jQuery.

### How to reproduce it?

Load the following scripts in order and run on a page with no other scripts enabled. 

#### Script 1

```javascript
// ==UserScript==
// @name          Script 1
// @version       0.0.1
// @namespace     violentmonkey-test
// @require       https://code.jquery.com/jquery-2.2.4.min.js
// @include       *
// @grant         GM_log
// @inject-into   content
// ==/UserScript==

setTimeout(() => console.log('final script1 jQuery:', jQuery.fn.jquery), 1000)

console.log('inside script 1')
console.log('script1 jQuery:', jQuery.fn.jquery)
console.log('leaving script 1')
```

#### Script 2

```javascript
// ==UserScript==
// @name          Script 2
// @version       0.0.1
// @namespace     violentmonkey-test
// @require       https://code.jquery.com/jquery-3.5.1.slim.min.js
// @include       *
// @grant         GM_log
// @inject-into   content
// ==/UserScript==

setTimeout(() => console.log('final script2 jQuery:', jQuery.fn.jquery), 1000)

console.log('inside script 2')
console.log('script2 jQuery:', jQuery.fn.jquery)
console.log('leaving script 2')
```

### What is the expected result?

```
inside script 1
script1 jQuery: 2.2.4
leaving script 1

inside script 2
script2 jQuery: 3.5.1
leaving script 2

final script1 jQuery: 2.2.4
final script2 jQuery: 3.5.1
```

### What is the actual result?

```
inside script 1
script1 jQuery: 2.2.4
leaving script 1

inside script 2
script2 jQuery: 3.5.1
leaving script 2

final script1 jQuery: 3.5.1
final script2 jQuery: 3.5.1
```

Note that Tampermonkey for Firefox (v4.11.6120) produces the expected output, but Greasemonkey (v4.10.0) produces the same output as Violentmonkey.

### Environment

- Browser: Firefox v82.0.3
- Violentmonkey: v2.12.7
- OS: Linux (Arch)

**Comment by tophf** [comment]
I think this is already fixed in the upcoming version.

**Comment by chocolateboy** [comment]
Ah, great! I can confirm v2.12.8rc18 produces the expected output :tada:

(FYI: I'm getting some [warnings](https://gist.github.com/chocolateboy/4d0aa9ef08509a1eba8af14241d39730) when loading that version in Firefox v82.0.3.)

**Comment by tophf** [comment]
The warnings are for the Chrome-only permission declarativeContent and you can ignore them. It's because we're using the same manifest.json for better or worse in both browsers.
