### ISSUE TITLE
document-idle still executes too early

### ISSUE THREAD

**Issue by OhSoGood** [violentmonkey/violentmonkey#1107]
Hi,
My script below has been replacing href addresses by the url presents in the titles, if any of any link in the page, of a targeted website for months. But the website has changed, the links in the pages themselves are still modified on the fly but not the ones in the comment section of each pages. Theses comment are obviously loaded on the fly and not part of the main pages. Yet, setting script to execute for document-idle does not help.

Can someone help me? Would a solution be that the script itself wait, either for a predefinite time or for a specific event? If so, how?

Examples of concerned page: https://www.dealabs.com/bons-plans/accessoire-velo-3-en-1-lampe-klaxon-compteur-de-vitesse-2008853  (search for keyword '3500 lumens' : that comment hold a link that is not visible to my ViolentMonkey script). Actually, all pages detailing a single product face the same issue.

Thank you!

### My script
```
// ==UserScript==
// @name UpdateLinks
// @author noname120
// @namespace MyScripts
// @version 0.0.3
// @license Creative Commons BY-NC-SA
// @include http*://*dealabs.com/*
// @grant none
// @run-at document-idle
// ==/UserScript==

var links = document.getElementsByClassName('link');
for (var i=0, max=links.length; i < max; i++) {
  var title = links[i].getAttribute('title');
  // Si le titre est un lien, alors remplace le lien d'origine par ce titre.
  if (/http/.test(title)) {
    links[i].setAttribute('href', title); 
  }
}

```

**Comment by tophf** [comment]
It's not specific to Violentmonkey or userscripts in general, and `document-idle` was never a solution for this, it's basically the same as `document-end` but without forcing it to run at **exactly** the time DOMContentLoaded is fired.

In your case you need to wait for the elements to appear as they are created by the site's script dynamically. Use periodic checks (setInterval) or MutationObserver or waitForKeyElements.
