### ISSUE TITLE
GM_getValue uses cached storage with no way to get fresh values

### ISSUE THREAD

**Issue by Majura-fi** [violentmonkey/violentmonkey#1108]
### What is the problem?
GM_getValue seems to be using cached value and there is no way to get fresh values after initial fetch. If script is ran in different tabs at the same time, the stored value will not be updated. I need a way to fetch fresh stored values in different tabs.

### How to reproduce it?
1. Install example script at the bottom.
2. Go to [safebooru.org](https://safebooru.org/index.php?page=post&s=list&tags=all) and open multiple tabs in short succession.
3. Open developer console (F12) for each opened tabs and observe count of the stored keys.

### What is the expected result?
The example script attempts to store post ids for each opened post. The script polls saved values with GM_getValue and checks if post id is stored. If it is not stored, it will add it and then save values with GM_setValue. The collection of stored post ids should grow. Polling continues for 30 seconds.

The example script reports amount of stored keys. Each tab's console should report increasing value of the stored keys.
Tab 1
![image](https://user-images.githubusercontent.com/12672127/99809751-6a3f3180-2b4b-11eb-9951-9f1675f913e8.png)
Tab 2
![image](https://user-images.githubusercontent.com/12672127/99809772-71663f80-2b4b-11eb-91fc-023482732d03.png)

### What is the actual result?
Each tab console reports same amount of keys, even after fetching new values with GM_getValue. Even if changing collection between each polling won't refresh fetched values.

Tab 1
![image](https://user-images.githubusercontent.com/12672127/99809800-79be7a80-2b4b-11eb-86f5-0d1d6ca74fe5.png)
Tab 2
![image](https://user-images.githubusercontent.com/12672127/99809800-79be7a80-2b4b-11eb-86f5-0d1d6ca74fe5.png)

### Environment
- Browser: Firefox (64-bit)
- Browser version: 82.0.3
- Violentmonkey version: 2.12.7
- OS: Windows

```
// ==UserScript==
// @name        safebooru.org - Example script
// @namespace   majuraspace
// @match       https://safebooru.org/index.php?page=post&s=view&id=*
// @grant       GM_getValue
// @grant       GM_setValue
// @version     1.0
// @author      Majura
// @description 11/20/2020, 3:34:56 PM
// ==/UserScript==

(function() {
  const storageKey = 'example';
  
  let saveTicks = 0;
  const saveInterval = setInterval(() => {
    // Run for 30 seconds and then stop.
    if (saveTicks > 30) {
      clearInterval(saveInterval);
      return;
    }
    saveTicks += 1;
            
    // Expected to fetch latest storage state.
    let storedPostIds = JSON.parse(GM_getValue(storageKey, '{}'));
    
    // Get post ID from the url.
    const match = window.location.href.match(/id=(\d+)/i);
    
    // Do nothing if no match.
    if (!match) {
      return;
    }
    
    console.log('Keys in storage:', Object.keys(storedPostIds).length);
    
    const postId = match[1];
    
    // Do nothing if post id is already stored.
    if (storedPostIds[postId]) {
      return;
    }
    
    // Store post id.
    storedPostIds[postId] = true;
    
    // Save updated collection.
    GM_setValue(storageKey, JSON.stringify(storedPostIds));
    console.log('Saved post id.');
  }, 1000);
  
})();
```

**Comment by tophf** [comment]
This was fixed long time ago in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases). BTW maybe you can use [GM_addValueChangeListener](https://violentmonkey.github.io/api/gm/#gm_addvaluechangelistener).

**Comment by Majura-fi** [comment]
@tophf I tested GM_addValueChangeListener, but it seems that this is also limited to use current page's cached value. The script in other tabs did not receive change events. Basically, I made a script with one second intervals to change values and save them and tried to listen for changes on another tab.

I'll wait for the next release and test again then.

**Comment by tophf** [comment]
For userscripts running in one URL origin (same domain) you can use the simpler and faster standard DOM API `BroadcastChannel`.

**Comment by Majura-fi** [comment]
Sweet! That works. I didn't know that this even existed. Thank you.
