### ISSUE TITLE
@grant breaks xhook

### ISSUE THREAD

**Issue by S-Aarab** [violentmonkey/violentmonkey#1111]
### What is the problem?
I'm using [xhook](https://github.com/jpillora/xhook) to intercept and modify XMLHttpRequest but setting `@grant` break it.
maybe its related to this  #1080 !!
### How to reproduce it?
1. install this script
```
// ==UserScript==
// @name         testing xhook
// @require      https://jpillora.com/xhook/dist/xhook.min.js
// @grant        GM_getValue
// ==/UserScript==
xhook.after(function(request, response) {
    console.log('xhook');
});
```
2. goto http://www.youtube.com 
3. open the console _ctrl+shift+k_

### What is the expected result?
`xhook` message shows in the log.
### What is the actual result?
no message.

if I set the grant to none the script works.

### Environment
- Browser: Firefox
- Browser version: 83.0
- Violentmonkey version: 2.12.7
- OS: Linux

**Comment by tophf** [comment]
This is how userscripts work. See how to use `unsafeWindow` to access the original page context.
