### ISSUE TITLE
Editor options bug

### ISSUE THREAD

**Issue by b9a1** [violentmonkey/violentmonkey#1113]
### What is the problem?
The editor options are lost when saved without modification.

### How to reproduce it?
1. Open the Settings page.
2. Expand the advanced options.
3. Click ‘Save’ in the ‘Editor’ section directly.

### What is the expected result?
No options should be changed.

### What is the actual result?
The input area displays `null` and user options are lost.

https://github.com/violentmonkey/violentmonkey/blob/44d1ffbb602d087c1d5fb9c4278bd14892957483/src/common/ui/setting-text.vue#L40
The problem seems to be that `parseJson` is not invoked until the input area is changed.

### Environment
- Browser: Firefox
- Browser version: 83.0
- Violentmonkey version: 2.12.7
- Violentmonkey [pre-release behavior](https://github.com/violentmonkey/violentmonkey/releases): 2.12.7.18
- OS: Windows

**Comment by tophf** [comment]
Can't reproduce. I can't click `save` in the editor without modification.

**Comment by b9a1** [comment]
Maybe I didn’t make myself clear. I meant this editor options in the **Settings**:
![image](https://user-images.githubusercontent.com/48396683/100107493-a7d1f080-2ea4-11eb-9f70-1b88e394e226.png)

**Comment by tophf** [comment]
It's me reading it wrong and mistaking 'Editor' for the code editor.
