### ISSUE TITLE
Any plan to add support of GM_getTab/GM_saveTab/GM_getTabs?

### ISSUE THREAD

**Issue by lonelykid** [violentmonkey/violentmonkey#1120]
### What is the problem?
GM_getTab/GM_saveTab/GM_getTabs not supported. They are exclusive to Tampermonkey. Tampermonkey has more users for now. Many scripts are written with Tampermonkey in mind. Without support of these APIs, many scripts cannot run on violentmonkey. 

### How to reproduce it?
1. Any userscript using these APIs does not work

### What is the expected result?
userscript works properly. maximum compatibility with Tampermonkey.

### Environment
- Browser: Chromium
- Browser version:86
- Violentmonkey version: 2.12.7
- OS:macos

**Comment by tophf** [comment]
I'm skeptical about this. AFAIK There's only a few scripts that use this feature and it can be approximated by GM_setValue + gm_addValueChangeListener anyway even though it's not ideal.

**Comment by tophf** [comment]
There's just [24 scripts](https://greasyfork.org/en/scripts/code-search?c=GM_getTab) on greasyfork that use GM_getTab so we won't implement it.
