### ISSUE TITLE
Support file URLs in Firefox

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1122]
VM works now with local files, right?
For example, I can type `file:///home/username/path/to/file.html` in address bar and VM works with that page.
AFAIK, VM used to ignore local files. Did something change or I am wrong and VM always worked with local files?
Thank you.

**Comment by gera2ld** [comment]
It depends on your browser and whether you allow access to file URLs in Violentmonkey settings.
Nothing has changed about this.

**Comment by soviet-man** [comment]
Where can I find such settings for Firefox?

**Comment by gera2ld** [comment]
It seems that Firefox works in a different way with file URLs.

**Comment by soviet-man** [comment]
So can it be changed in Firefox? I'm just curious.

**Comment by tophf** [comment]
@gera2ld [their documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#%3Call_urls%3E) says `<all_urls>` includes `file://`

**Comment by soviet-man** [comment]
So, it means that in Firefox local files are accessible by default.

**Comment by gera2ld** [comment]
@tophf Ahhh, my fault, it's supported already. I'll revert that commit.

**Comment by tophf** [comment]
Judging by history of changes in https://github.com/violentmonkey/violentmonkey/blob/master/test/background/tester.test.js it was supported since 2017, however indeed 2.12.7 didn't run scripts in file:// URLs that should be running e.g. the ones with `@include *`. Now they run which is the correct result.

**Comment by soviet-man** [comment]
Why can't GM_openInTab open local file?
If I code `GM_openInTab('file:///home/username/htm?xyz')`, it redirects to `www.home.com/username/htm?xyz`. Although I have that local file in my home directory.

**Comment by tophf** [comment]
We don't allow opening file:// URLs because it'd be trivial for a userscript to open sensitive files with passwords and other personal info and then just run in those tabs to collect the data.

**Comment by soviet-man** [comment]
If you allow VM working on local files through `@include file:///...`, then why don't you allow open local files in tab? It is inconsistent.

**Comment by tophf** [comment]
Currently the user has to open the file in a tab explicitly and knowingly. What you suggest is a completely different thing as my previous comment explained.

**Comment by soviet-man** [comment]
Is there a way to open local file from userscript?

**Comment by gera2ld** [comment]
No, Firefox doesn't allow this for security reasons. [Ref](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create)
