### ISSUE TITLE
Why colors of comments, regexp and strings are now very similar?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1127]
Why colors of comments, regexp and strings are now very similar?
![изображение](https://user-images.githubusercontent.com/33825590/102267971-b2bff400-3f2b-11eb-9984-20810cb6e6bf.png)
**Can I change color theme?**

**Comment by tophf** [comment]
Both regexp and a template literal use the same type of CodeMirror token as you can see in devtools. It means there's no way to have different colors. Try asking the author of CodeMirror to add a separate token type for regexps. If they disagree for whatever reason, maybe I'll try to hack into CodeMirror javascript tokenizer and do something about it myself.

**Comment by tophf** [comment]
As for other colors, you can use CustomCSS in options. It's there for this exact purpose.

**Comment by tophf** [comment]
We're using the default theme of CodeMirror, which is why the colors are different: previously we were using a nonstandard `eclipse` theme which wasn't intentional - it was used only because the default theme use a bad color for matched parenthesis.

Now that I look at the comments near strings I see there's a readability problem indeed so I guess we can change string colors to greenish as it's the usual color for strings...

**Comment by tophf** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/1310400/102276427-cf622900-3f37-11eb-82f2-b824b4039c85.png)

**Comment by soviet-man** [comment]
Comments must be written in grey, but not in color, because they are not significant for code.

**Comment by soviet-man** [comment]
Corresponding parenthesis are in light green? Are you serious? I can't distinguish them!!!
![изображение](https://user-images.githubusercontent.com/33825590/102282128-27515d80-3f41-11eb-883d-fab81cc8d620.png)
This is how it was with eclipse theme
![изображение](https://user-images.githubusercontent.com/33825590/102282168-36381000-3f41-11eb-8474-fafd0617d7e7.png)

**Comment by soviet-man** [comment]
Changing default theme is definitely bad idea!

**Comment by tophf** [comment]
> parenthesis are in light green

This is the default theme.

>Changing default theme is definitely bad idea!

No, the default theme itself has bad colors so changing them is a good idea.
