### ISSUE TITLE
Export to zip Firefox

### ISSUE THREAD

**Issue by svnpenn** [violentmonkey/violentmonkey#113]
Clicking this button does nothing for me - Firefox 53

**Comment by svnpenn** [comment]
https://github.com/violentmonkey/violentmonkey/issues/43

**Comment by gera2ld** [comment]
Known issue, Firefox has limited the permission for extension to access to a `blob:` file, which does not make sense.

ref: <https://bugzilla.mozilla.org/show_bug.cgi?id=1331176>

**Comment by gera2ld** [comment]
dataURL is blocked too 😞
