### ISSUE TITLE
"window" global context 

### ISSUE THREAD

**Issue by endiom** [violentmonkey/violentmonkey#1133]
### What is the problem?
The new version v2.12.8 no longer works on my script
The variable existed on the target site no longer can be loadded due to its name conatins "window"(blue one) .
how to get rid of it? (without changing the variable name)
### How to reproduce it?
1. var window.NOW.name= "Violentmonkey";
   alert(window.NOW.name);

### What is the expected result?
Violentmonkey
### What is the actual result?
no alert promopt
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
no alert promopt

### Environment
- Browser: Firefox 
- Browser version: 83.0
- Violentmonkey version: v2.12.8 
- OS: Windows 10
![SS](https://user-images.githubusercontent.com/17062300/102359087-4efd0000-3feb-11eb-9718-d7156dc75178.png)

**Comment by tophf** [comment]
`var window.NOW.name = "Violentmonkey"` is invalid JavaScript code.

**Comment by endiom** [comment]
![图片](https://user-images.githubusercontent.com/17062300/102360731-57eed100-3fed-11eb-910b-40168b94e5cb.png)

Sorry maybe a bad example, previously on v2.12.7 the script can retrieve those variables (eg. 'window.NOW.user_name') based on the source code of the page. If I roll back to  v2.12.7 it works.

**Comment by tophf** [comment]
The actual behavior is determined by whether you're using `@grant none` or not. Previously, Violentmonkey was incorrectly sharing such variables with the global `window` object of the page. Now we've fixed that bug and `window` is isolated.

* If the script has only one `@grant` and it is `@grant none` then you can directly read/write any `window` property that belongs to the page.
* If the script doesn't have any `@grant` or it has some `@grant` that is not `@grant none` then the script is sandboxed and to access the global page context you should use `unsafeWindow` instead.

This is how userscripts have always been working.

**Comment by endiom** [comment]
Thanks tophf , understand.
Case closed.

**Comment by KaylaSolace** [comment]
> The actual behavior is determined by whether you're using `@grant none` or not. Previously, Violentmonkey was incorrectly sharing such variables with the global `window` object of the page. Now we've fixed that bug and `window` is isolated.
> 
>     * If the script has only one `@grant` and it is `@grant none` (or it doesn't have any `@grant` at all) then you can directly read/write any `window` property that belongs to the page.
> 
>     * If the script has some `@grant` and it's not `@grant none` then the script is sandboxed and to access the global page context you should use `unsafeWindow` instead.
> 
> 
> This is how userscripts have always been working.

Hello, this is inconsistent with tampermonkey and other userscript loaders.

IE: you are still sandboxing NEW properties. in tampermonkey, grant none is sufficient to access ``window.markdownProcessor`` (site creates it after the JS loads), however violentmonkey will prevent you from accessing it even with grant none, and will also prevent ``window.test = 'foo'`` from being visible to other scripts.

**Comment by tophf** [comment]
@KaylaSolace, no, Violentmonkey doesn't enable sandbox with `@grant none`. What happens I guess is that you have a website with a strict CSP where Violentmonkey can't inject scripts into the page context and does it in the isolated content context. Tampermonkey and some other managers can remove CSP header but it reduces security of the website, which is why Violentmonkey doesn't do it. If my guess is correct you can use `wrappedJSObject` which Firefox exposes on all DOM-shared objects including `window` e.g. `window.wrappedJSObject.test = 'foo'`. In the future Violentmonkey will use the dedicated `userScripts` API which hopefully would allow injecting scripts in the page context directly (maybe this is also what's used by the other managers, but I haven't investigated it yet).
