### ISSUE TITLE
(Suggestion) In the dashboard, move the `Sort by` dropdown menu outside Filters, and then remove `Filters` itself

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1135]
My suggestion is In the dashboard, to move the `Sort by` dropdown menu outside 'Filters', and then remove `Filters` itself.

The reason is that the word 'Filters' implies using criteria to look for matching subgroups in the installed scripts, while it actually only contains the irrelevant "Sort by" functionality.

Even if you plan to add more functionality inside Filters, I believe that "Sort by" is better separated.

Thank you

**Comment by tophf** [comment]
You can adjust it via CSS, here's mine:

![image](https://user-images.githubusercontent.com/1310400/102399567-d6e60880-3ff1-11eb-8cbf-229b8a7c3ef3.png)

I doubt this option is used a lot so it's better to keep it hidden. We could rename the tooltip to `Filters and sort` but somehow this doesn't seem worth the effort.

**Comment by darkred** [comment]
Could you please share your CSS?

**Comment by tophf** [comment]
It's in https://gist.github.com/tophf/ba26f98902ec54ffde4968c9c8b01eb2. There's a lot more than filters so delete the rest.

**Comment by darkred** [comment]
Thank you!

**Comment by tophf** [comment]
I expect this part of the UI will be [completely] reworked when we implement #287. Until then CustomCSS is an acceptable compromise (unless we see more reports about this particular problem of course).
