### ISSUE TITLE
Add New Syntax Option for Latest @run-at document-start Behavior

### ISSUE THREAD

**Issue by nyfair** [violentmonkey/violentmonkey#1137]
The feature is great, but it also break compatibility of many scripts that execute at document-start and do some DOM modification.

**Comment by tophf** [comment]
Without a demo script that reproduces the problem there's nothing we can do here.

**Comment by nyfair** [comment]
Are u kidding? this is fairly simple, just use document.querySelector to see the error message.
You can not persuade all the script contributors to update their scripts, right?

**Comment by tophf** [comment]
I'm not kidding. Without a demo script I can only guess and the only guess I have so far is that you misunderstood what `document-start` means.

**Comment by nyfair** [comment]
Yes, you are right. Let me say again, you can't persuade all the script contributors to update their scripts just because you are right.

**Comment by tophf** [comment]
It's not about me. It's about how `document-start` works and always worked for the last 20 years. You need to provide an example script that shows the problem, otherwise there's nothing we will do.

**Comment by nyfair** [comment]
And 20 years is much longer than 2days since the latest release. These scripts already existed for years.

**Comment by tophf** [comment]
We'll wait for someone who is reasonable to show us at least one script. I'm locking this issue for now.

**Comment by gera2ld** [comment]
So many useless messages without any snippet or a single link to one of your *many scripts*...

You shouldn't be able to `querySelector` at `document-start` by design. Maybe you can try `document-body`.
Please read the docs for more details.

**We don't patch for wrong use cases.**
