### ISSUE TITLE
'Installing script' tabs have no favicons

### ISSUE THREAD

**Issue by KLaurence** [violentmonkey/violentmonkey#1146]
### What is the problem?
There are no favicons for Violentmonkey 'Installing script' tabs.

### How to reproduce it?
1. Drag a .user.js file to the browser to create an 'Installing script' tab.

### What is the expected result?
The 'Installing script' tabs have the same favicon in their tabs as the home page and script editor tabs.

### What is the actual result?
The 'Installing script' tabs have no favicons.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
Same as above, in v2.12.9.

### Environment
- Browser: Firefox
- Browser version: v84
- Violentmonkey version: v2.12.8
- OS: Windows

**Comment by tophf** [comment]
That's a Firefox bug/deficiency, already fixed in #1139, available since [v2.12.9.1](https://github.com/violentmonkey/violentmonkey/releases).
