### ISSUE TITLE
Scripts are not executing on the first run if the site uses Chrome's standalone window feature

### ISSUE THREAD

**Issue by ni554n** [violentmonkey/violentmonkey#1149]
### What is the problem?
Chrome has a window feature that opens sites or PWAs like a standalone app.

If the sites are in `standalone` / `minimal-ui` [display mode](https://developer.mozilla.org/en-US/docs/Web/Manifest/display), Violentmonkey doesn't run any script on the first run. But any refresh after that will run the scripts normally.

### How to reproduce it?
1. Go to any website and create a standalone window using _Chrome Menu > More Tools > Create Shortcut..._
2. Close the window.
3. Create a VM script for that domain with a `console.log`.
4. Re-open the website using its icon from Desktop / Start Menu.
5. Open Dev Tools by pressing `Ctrl + Shift + i`.

### What is the expected result?
The log message in the console.

### What is the actual result?
No message from the script shows up on the first run. An error will show up (see below).
Subsequent refreshes will log the message as expected.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
Haven't tried it. But [comparing changes](https://github.com/violentmonkey/violentmonkey/compare/v2.12.9...v2.12.9.1) shows no commit related to this issue.

### Log
`The entry type 'frame' does not exist or isn't supported.
(anonymous) @ VM27:27`

### Environment
- Browser:  Google Chrome
- Browser version: 87.0.4280.88
- Violentmonkey version: 2.12.9
- OS: Windows 10 20H2

**Comment by tophf** [comment]
Can't reproduce. The error doesn't seem related to Violentmonkey as it's caused by using PerformanceEntry API.

**Comment by ni554n** [comment]
Sorry, my testing method was flawed. This problem is actually showing up only on Google Drive page.

I tried reproducing the steps on Github, but I made a mistake with the matching URL. So the script didn't run as expected, and I assumed the issue is with VM.

Can you please try the steps on https://drive.google.com/drive/my-drive and see if it is reproducible or not.

**Comment by tophf** [comment]
Works for me.

One of the common reasons is the bug in Chrome (or an inherent deficiency) that can be circumvented by removing the useless Drive app from `chrome://apps` as well as all other built-in apps except the web store.

**Comment by ni554n** [comment]
Thanks for the confirmation. I found the solution. The problem was with URL redirection.

_Create shortcut_ creates a https://drive.google.com link that redirects to [/drive/my-drive](https://drive.google.com/drive/my-drive). I changed the @match to https://drive.google.com/* and the script is working as expected. 🎉
