### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by rayman89** [violentmonkey/violentmonkey#115]
Is it possible to quickly put all the greasemonkey scripts I have into violent monkey?

**Comment by AlexBeLi** [comment]
1. Open Directory
	C:\Users\Name-Your-User\AppData\Roaming\Mozilla\Firefox\Profiles\Name-Your-Profile\gm_scripts\
2. Search in searching bar of filemanager *.user.js
3. Archive your scripts to archivename.zip
4. Violentmonkey - Open Dashboard - Settings - Import from zip
Import works fine, but export in Firefox does not work yet because of this:
	https://bugzilla.mozilla.org/show_bug.cgi?id=1331176
	https://github.com/violentmonkey/violentmonkey/issues/113

**Comment by rayman89** [comment]
@AlexBeLi Thanks a lot. BTW I'm a bit confused with the auto updates it seems that a lot of scripts cannot be auto updated now that they are on violent monkey but they were updated automatically when they were on greasemonkey do you know why?

**Comment by gera2ld** [comment]
@rayman89 Only scripts with `@updateURL` or installed from sites like Greasy Fork can be updated automatically. Otherwise we do not know where to check for updates.

**Comment by qwertier** [comment]
I've created an archive with all the *.user.js in the root, e.g. there were no subfolders in the archive:
`cd YOUR_FIREFOX_PROFILE/gm_scripts && zip -R -j greasemonkey_scripts '*.user.js'`
Next, I tried Violentmonkey - Open Dashboard - Settings - Import from zip
And... no any response, no scripts were installed!
System: Firefox 52 ESR
