### ISSUE TITLE
Inline editor requires clipboard events to use Primary Selection

### ISSUE THREAD

**Issue by haarp** [violentmonkey/violentmonkey#1150]
### What is the problem?

The inline script editor will not use the Primary Selection when clipboard events are disabled in the browser (e.g. `dom.event.clipboardevents.enabled` set to false in Firefox). This means that using the middle mouse button to paste the selection under Linux X11 will not work, nor will selections enter the same buffer.

Why would one disable clipboard events? on Linux X11, sites can hijack the middle mouse button to spy on selection contents. Try it out by middle-clicking on an emtpy spot on the main page of imgur.com! You'll see an "URL failed to upload" dialog.

### How to reproduce it?
1. Edit a script with the inline editor
2. Press middle mouse button

### What is the expected result?
Primary selection should work, regardless of clipboard events being disabled. Other extension do not rely on these. And as explained above, there's a very good reason to disable them.

### What is the actual result?
No primary selection support, middle-click pasting broken.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
Same

### Environment
- Browser: Firefox
- Browser version: 83
- Violentmonkey version: 2.12.8
- OS: Linux X11

Thanks!

**Comment by tophf** [comment]
I have no idea what that is so I can only guess it's the way CodeMirror works.

**Comment by tophf** [comment]
Try the demo editor on https://codemirror.net/

**Comment by tophf** [comment]
https://bugzil.la/1593761 "CodeMirror doesn't interact correctly with PRIMARY on Linux"

**Comment by haarp** [comment]
Yup, it is a CM limitation. I asked the CM maintainers, there seems to be nothing they can do about it. codemirror/CodeMirror#6538

Cheers!
