### ISSUE TITLE
Userscript throwing TypeError after recent updates

### ISSUE THREAD

**Issue by ramenchef** [violentmonkey/violentmonkey#1152]
### What is the problem?
Userscript no longer works with latest update v2.12.9 
(Tested on chrome 87.0.4280.88 and firefox 84.0.1)

### How to reproduce it?
1. Install Manga OnlineViewer [Github](https://github.com/TagoDR/MangaOnlineViewer) [Direct link](https://github.com/TagoDR/MangaOnlineViewer/raw/master/Manga_OnlineViewer.user.js)
2. Visit a supported website for loading images [Example](https://reader.kireicake.com/read/frieren_at_the_funeral/en/0/31/)
3. Let script load or hit ok to skip the timer.

### What is the expected result?
All the images are loaded on the page in a vertical script.

### What is the actual result?
Placeholders are loaded instead and an error in the console appears.
Chrome console error: Uncaught TypeError: 'deleteProperty' on proxy: trap returned falsish for property 'jQuery351053040718892159271'

Same issue firefox. Console error: Uncaught TypeError: can't delete property '"jQuery351081744739889223171"': proxy deleteProperty handler returned false

### What is the result in the [BETA v2.12.9.1](https://github.com/violentmonkey/violentmonkey/releases)?
Same issue firefox. Console error:  Uncaught TypeError: can't delete property '"jQuery351079404721409033821"': proxy deleteProperty handler returned false

### What is the result in the [v2.12.8](https://github.com/violentmonkey/violentmonkey/releases)?
Same issue firefox. Console error: Uncaught TypeError: can't delete property '"jQuery351063715856718524291"': proxy deleteProperty handler returned false

### What is the result in the [v2.12.7](https://github.com/violentmonkey/violentmonkey/releases)?
Works as expected

### Environment
- Browser: Chrome 
- Browser version: 87.0.4280.88
- Violentmonkey version: v2.12.9 
- OS: Windows 10

**Comment by tophf** [comment]
v2.12.9.2 will have the fix.
