### ISSUE TITLE
GM_xmlhttpRequest lost its response when type is text

### ISSUE THREAD

**Issue by dodying** [violentmonkey/violentmonkey#1154]
### What is the problem?
sometimes, resp.response removed

### How to reproduce it?
1. new script
```js
// ==UserScript==
// @name        test
// @include     *
// @version     1
// @run-at      document-end
// @grant       GM_xmlhttpRequest
// ==/UserScript==
/* global  */
/* global $ */
/* eslint-disable no-debugger  */
(function () {
  GM_xmlhttpRequest({
    method: 'GET',
    url: 'http://www.google.com',
    onload (resp) {
      console.log(resp);
    },
    onprogress (res) { // or onreadystatechange // i don't test others

    }
  });
})();
```
2. in console, you can find `resp.response` is `undefined`
3. but remove `onprogress`, it run

### What is the expected result?
get `resp.response` when set `onprogress` or others

### What is the actual result?
get `resp.response` `undefined`

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
same as stable version

### Environment
- Browser: Chrome
- Browser version: 86.0.4240.198
- Violentmonkey version: 2.12.9
- OS: win

**Comment by tophf** [comment]
v2.12.9.3 will have the fix when it's [released](https://github.com/violentmonkey/violentmonkey/releases).
