### ISSUE TITLE
regression from addon update: after some usage disabling script wont disable them.

### ISSUE THREAD

**Issue by rezad1393** [violentmonkey/violentmonkey#1159]
this is a weird and not always reproducable bug.

I recently noticed that after some firefox usage, violentmonkey scripts behave weirdly.
for example this:
https://github.com/Purfview/IMDb-Scout-Mod/issues/3
for this script after changing its setting from its setting menu and refreshing the page changes are not seemes to be saved but if I restart firefox that change are now applied (the change from before now get applied)

the second example is that use some scripts on a torrent site and when I was trying to enable and disable them I got this weird issue that when I disable or enabled scripts it seems that violentmonkey didnt seems to enable or disable them.
I even used the flip button from violentmonkey and disable all scripts with that, and ctrl-F5 the page but it seemed that violentmonkey got stuck in its last stage and the scripts were run again, when they should have not because they were disabled.

the only fixe that seems to un-stuck violentmonkey state is to disable the addon and re-enable it again.

I know this is a weird bug and I have many addon that may have cause that to happen to violentmonkey or maybe even firefox update regression.
but I have no way of finding out what is causing this.
I need to browse a lot to see this and I cant do that with a bare firefox profile.

any help will be great.

### Environment
- Browser:firefox
- Browser version:84.0.1 (64-bit)
- Violentmonkey version:2.12.8
- OS: archlinux x64

**Comment by tophf** [comment]
Nothing we can do without a reliable sequence of actions to reproduce the bug. From your current description I don't even understand how to identify the first problem. As for the second one I think I've seen it happening a couple of times but I couldn't reproduce it recently and thought it's fixed, so it'd be helpful if you could find how to reproduce it in a new browser profile.

**Comment by rezad1393** [comment]
you created a fix for the second issue?
I didnt notice the first issue until recently.
but the second one maybe existed beforef and I didnt notice.

should I wait for that fix that you created to test to see if it fixes the first one too? though I doubt they are related because you say that you saw the second issue before but I just saw the first one recently (I noticed after newest firefox update 84.0.1 but that may not be the actual cause)

**Comment by rezad1393** [comment]
maybe the best way to test this it for me to go back one version for firefox (before 84.0) and see if I see the issue again.

**Comment by rezad1393** [comment]
also another issue that happens after some use (as in right now that I am typing) I cant save edits to scripts setting in violentmonkey addon in setting tab of scripts.
so I cant change homepage or include exclude and so on for scripts.

**Comment by tophf** [comment]
The Save button problem was fixed recently in v2.12.9.2 which you can install [manually](https://github.com/violentmonkey/violentmonkey/releases). A simple workaround is to add a space in the code of the script.

**Comment by rezad1393** [comment]
> The Save button problem was fixed recently in v2.12.9.2 which you can install [manually](https://github.com/violentmonkey/violentmonkey/releases). A simple workaround is to add a space in the code of the script.

so that is separate from my issue?

**Comment by tophf** [comment]
Yes, you've listed a lot of issues here :-)

**Comment by rezad1393** [comment]
only two are there.
the setting of imdb scout script need violent monkey addon to disable re-enable (so very similar to that save button issue that your new update fixed).
also disable and re-enabling scripts dont work until (again) disable re-enable of addon.

**Comment by tophf** [comment]
I see a lot of comments with a lot of problems here but I don't see a definitive sequence of actions to reproduce neither one. So, I can only hope the fix I wrote will help.

**Comment by tophf** [comment]
You can try the fix in a temporary-installed extension ([instruction](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)):
[**vmfix.zip**](https://github.com/violentmonkey/violentmonkey/files/5758984/vmfix.zip)

**Comment by rezad1393** [comment]
> I see a lot of comments with a lot of problems here but I don't see a definitive sequence of actions to reproduce neither one. So, I can only hope the fix I wrote will help.

I understand.
that is what I said at the start of issue at top that after some use these issues happens and reloading (disabling and re-enabling) the addon fixes it for sometime.
so I will revert to 2.12.7 version of this addon to see if the issue exist with new firefox and old addon or not.
this is the easiest route right now to check.

**Comment by rezad1393** [comment]
I reverted back to old version of addon (from feb 20) and I dont see the bugs anymore.
although I cant be 100% sure that is the case but could this be the violentmonkey regression or it combined with some other addon?
though if it is some other addon why disabling and re-enabling this addon fixes the issue temporarily.

**Comment by tophf** [comment]
Try the fixed version in the comment above please.

**Comment by rezad1393** [comment]
> Try the fixed version in the comment above please.

you said that was the beta version that just fixed the save edit issue. so other issues are not fixed by that right? (at least intentionally) 
I need to be sure that I do not get the error ever with this version first.
this way we both know whether the regression happened because of this addon or because of something else.

if I don't see those 2 errors (the third one we are sure we dont see because you yourself saw it and fixed it in the beta).
then I would know it was not a firefox regression or another addon conflicting with this addon.
though to be honest this kind of behavior (addon clash) have become less of an issue after firefox migrated to webextentions.
mostly network connection related addon can clash right now.

and if I see the bug even with older addon then ...... I am f...d and need to check all my addon one by one.
hopefully it is your fault only ;)

**Comment by tophf** [comment]
Just try it please.

**Comment by rezad1393** [comment]
> Just try it please.

no means no.

jokes aside if you thinks that you new beta just fixes the save issue and is not designed to fix other issue, then please have some patience and wait a week or so for me to be sure.

**Comment by tophf** [comment]
This is just the most recent version, which should fix for everything.

**Comment by rezad1393** [comment]
> This is just the most recent version, which should fix everything.

I dont seem to be able to make my point clear.
you said that you just fixed the save issue.
then you said that I should install the beta to test that.
"The Save button problem was fixed recently in v2.12.9.2 which you can install manually. A simple workaround is to add a space in the code of the script."
I need to see if the other issues are regression introduced by the last stable version (before that beta) or my other addons fault or firefox issue.
so I need to test with the last version before the newest stable version.
this is the semi-scientific way.

please wait for my own testing and don't put replies here before I have tested that at least for a week.
this is my last answer before next week.

**Comment by tophf** [comment]
There's no point in testing anything except the version in the comment above. It contains all the fixes.

**Comment by rezad1393** [comment]
> There's no point in testing anything except the version in the comment above. It contains all the fixes.

so you are telling me that you saw no regression in code from last stable but you manage to fix it? without knowing what to fix?
this is getting ridiculous.
this is that last reply till next week.
have a nice weekend.

**Comment by tophf** [comment]
> without knowing what to fix?

The description of the bug was sufficient to know what to fix, moreover I've seen the bug previously myself. Anyway, currently you're the only one affected by this bug so I guess we can wait any amount of time until you condescend to test the fix.

**Comment by rezad1393** [comment]
I used firefox for a week (as I said I would) with older version of addon (2.12.7).
I dont get any one the bugs (the save issue was fixed by your update but I was testing for other issues I encountered with new firefox AMO update).
I am now more certain that the bugs where VM(violentmonkey) caused ( regressions).
so now I will test this new version that you recommend (that is not available in AMO) to see if in daily usage of firefox I encounter the bugs again.

**Comment by rezad1393** [comment]
that didnt take long.
at least the disble bug (disabling all script from switch in VM menu) is present in the newest beta.
" also disable and re-enabling scripts dont work until (again) disable re-enable of addon."

**Comment by rezad1393** [comment]
going back to AMO version for now to see and wait if any new update fixes this.

**Comment by tophf** [comment]
> is present in the newest beta.

The newest beta doesn't have the fix. The fix is present in my [comment above](https://github.com/violentmonkey/violentmonkey/issues/1159#issuecomment-753317914).

**Comment by rezad1393** [comment]
> > is present in the newest beta.
> 
> The newest beta doesn't have the fix. The fix is present in my [comment above](https://github.com/violentmonkey/violentmonkey/issues/1159#issuecomment-753317914).


Version
2.12.9.2

???  is this different from beta .xpi this is in the release page on github?
if not then the bugs are still there because I tested with that xpi.

**Comment by tophf** [comment]
Yes and yes.

**Comment by rezad1393** [comment]
right now I see that some scripts fail to work but when I disable all scripts at least that disabling works.
for the those failing scripts to work I need to disbale and re-enable the addon.
I need to use it more to get a feel of how much goes wrong and how much of the last bug are not present anymore.

**Comment by rezad1393** [comment]
update: some thing weird that happened with last bug happens now that I can replicate for me.
it is for a p0rn torrent private tracker so I dont know if you can replicate it but I try to explain it.
it is for this script"
https://github.com/ehfraim/emporniumuserscripts/blob/master/empornium_add_preview_thumbnail.user.js
when I open the site other scripts work but this one doesnt work (doesnt load thumbnails) but when I disable the addon and reenable it then the same page loads thumbnails even without me refreshing it. I mean just as I reenable the addon the page page changed and gets the thumbnail.
dont I need to refresh a page for addon to work?
weird?

**Comment by tophf** [comment]
I can't test that script because I don't have access to the private site where it runs.

**Comment by rezad1393** [comment]
i know.
I think I just wait for newer update of addon to see if others report other bug that may fix mine too.

**Comment by tophf** [comment]
I've just analyzed the code of that script: it's incorrect. It worked only because we didn't support `document-body` properly, which is now implemented in new beta. To circumvent the problem you can set the script's `Run-at` to `document-end` in the script editor and inform the author of the script that they should either remove `@run-at document-body` or use MutationObserver.

![image](https://user-images.githubusercontent.com/1310400/104201631-01818080-543b-11eb-984f-65eb9edcb0c4.png)

**Comment by rezad1393** [comment]
can you make a new beta instead of the temporary addon?
having to reinstall it is very annoying.

**Comment by rezad1393** [comment]
new update:
latest beta from github solves most of bugs but I see another bug.
I edited a script that runs on imdb (the one from first post but not important) ,
I saved it then I refreshed the imdb page but it the script is not changed.
the change are saved in editor and if I open the script in editor I see the change is saved but it seem that violent monkey still loads the older non-edited script.

**Comment by rezad1393** [comment]
update:
I spoke too soon.
I now get the bug for imdb script. the one that didnt save setting of script for "imdb scout mod" script.
