### ISSUE TITLE
Twitter detects injection in the background and reports it along with the GUID of tampermonkey back to them...

### ISSUE THREAD

**Issue by ilikenwf** [violentmonkey/violentmonkey#1164]
So a really nasty fingerprint...

See https://github.com/easylist/easylist/issues/6921

This is doable by any other given site too. I realize this is more a firefox issue, but I wonder if there's a way around this.

More or less an FYI as I'm not sure it can be helped.

**Comment by tophf** [comment]
This is how CSP works so I don't see what we can do here. The only workaround is to remove the `CSP` header via browser.webRequest API (we can do it but it's really outside of the scope of the extension) or the users can disable something in `about:config` about `reporting` themselves like maybe set `security.csp.reporting.script-sample.max-length` to 1 or 0. Anyway, those who are concerned with the potential for fingerprinting should be already blocking **all** kinds of reporting in their browsers.

**Comment by AlttiRi** [comment]
uBlock Origin
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports

**Comment by ilikenwf** [comment]
I am using uBlock Origin, and I have no-csp-reports set in the settings...this still happens unless I block it explicitly. Go try it.

**Comment by ilikenwf** [comment]
Ok so now it's working properly...weird. Please close.
