### ISSUE TITLE
How can I know GM_xmlhttpRequest redirected request?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1165]
How can I know `GM_xmlhttpRequest` actually redirected request? And what is new address?

**Comment by tophf** [comment]
It's `finalUrl` property in the `onload` callback, see https://stackoverflow.com/questions/51960139/how-to-see-the-link-of-the-website-it-redirects-to-while-using-gm-xmlhttprequest. You can find more info in userscript documentation and by searching for the keywords yourself.

**Comment by soviet-man** [comment]
I thought I can inspect response object and find `response.status === 302` and `Location` header among `response.responseHeaders`, BUT I don't see any of this.
