### ISSUE TITLE
Everything was lost after Windows' blue screen while reading/writing to storage

### ISSUE THREAD

**Issue by pintassilgo** [violentmonkey/violentmonkey#1168]
#599 and #1048 are also about data loss, but they lack details to know if it's about the same thing, so I'm opening a new ticket.

Firefox 85. Now I'm not sure if I was using Violenymonket 2.12.8 or BETA 2.12.9.3, as I tried installing both after the issue as last hope.

One of the UserScripts I use is to mark already seen items in Reddit. While I was loading Reddit homepage, what I do ~4 times per day, got blue screen on Win10. I never shutdown my PC, it was on for weeks, so these crashes eventually happen, probably something about memory. I'm sure the crash happened exactly at the same time that Violentmonkey was processing GM.getValue/GM.listValues/GM.setValue on Reddit's UserScript.

After rebooting, everything about Violentmonkey was lost, not only the scripts, general settings too. Just Violentmonkey was affected, I use other dozens of other addons and they are all fine, my browser history is OK etc.

This data corruption broke Violentmonkey completely. I'm not able to install any script, create new script... I can only open dashboard, but even after clicking a checkbox the change doesn't save.

Violentmonkey data wasn't deleted, it's still accessible on [profile]\storage\default\moz-extension+++{guuid}. But Violentmonkey apparently doesn't store simple data, it does some kind of compression so that I can't read data even using DB Browser (.sqlite viewer).

How to debug if there's something corrupted in .sqlite files and how to repair it? I understand if I have to lose script data of the Reddit UserScript, but I expect that other UserScripts and its files and also Violentmonkey settings should be intact so there must be a way to restore them.

P.S.: I know that if I uninstall Violentmonkey, then reinstall, generating a new guuid, it will work, but with default settings and with no scripts.

**Comment by gera2ld** [comment]
Violentmonkey does not do any kind of compression, it just utilizes [the storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) to read and write plain text data, and it depends on the browser to store the data and keep it safe.

I have no idea how the data is handled by Firefox under the hood. Maybe you should ask for help in Firefox community.

**Comment by tophf** [comment]
There are certainly some tutorials about extracting data from Firefox files so try searching. Also consider setting up a daily backup of your entire user data drive/directory because computer software isn't reliable, which is something we only learn after painful encounters like this one.
