### ISSUE TITLE
Script is not being injected in page with CSP [BETA v2.12.9.3 regression]

### ISSUE THREAD

**Issue by pintassilgo** [violentmonkey/violentmonkey#1171]
Tested on Twitter with Firefox 84, 85 and 86, with my main profile and also with fresh new profile.

With v2.12.9.2 it's OK, but with v2.12.9.3 the script is not injected.

This, of course, is with CSP enabled in the browser (default). If I set `security.csp.enable = false`, then v2.12.9.3 works too.

**Comment by tophf** [comment]
Luckily it works in `master` so the next beta should be fine.
