### ISSUE TITLE
"Check for updates" button fails for userscript installed by GitHub raw URL (option to disable cache?)

### ISSUE THREAD

**Issue by karlhorky** [violentmonkey/violentmonkey#1172]
First of all, thanks so much for your continued effort creating and maintaining this extension, really amazing! 💯

### What is the problem?

I have a userscript at [this GitHub URL](https://github.com/karlhorky/dotfiles/blob/main/userscripts/add-tmdb-links-to-imdb.user.js) (and [this raw URL](https://raw.githubusercontent.com/karlhorky/dotfiles/main/userscripts/add-tmdb-links-to-imdb.user.js)).

I bumped the version to `1.0.1` to test that the updates were working, and clicked on the "Check for updates" button. It could not find the new version, although `curl` was showing the new version.

### How to reproduce it?

1. Install a userscript by GitHub raw URL
2. Make a change to the userscript and push it (the GitHub raw URL shows the update)
3. Click the "Check for updates" button. Violentmonkey reports that there are no updates.

### What is the expected result?

The "Check for updates" button works instantly.

If it's not possible to enable by default, offer an option to enable instant updates (eg. an option to disable whatever cache is reporting stale results?)

### What is the actual result?

I need to wait some time before the update shows up.

Workaround: Install the new version with a cache-busting URL parameter such as `?v=1.0.1`

### Environment

- Browser: Chrome macOS
- Browser version: 88.0.4324.96 (latest)
- Violentmonkey version: v2.12.9
- OS: macOS Big Sur 11.1

**Comment by tophf** [comment]
This is a bug in GitHub's server, not ours, as it ignores `Cache-Control` header. We can use a workaround of course but I wonder if we should...

**Comment by karlhorky** [comment]
Ah ok, thanks for the response! Maybe I should be using something like [raw.githack.com](https://raw.githack.com/) - maybe they have a better way of caching.

What would be the workaround?

**Comment by tophf** [comment]
GitHub serves the exact same content for 5 minutes after it was actually modified. The only workaround is to add `?` and a random thing in the URL, which is why I don't think we should be doing it. For rapid development you should be using a local file directly, right from the disk as described in https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/

**Comment by tophf** [comment]
Although we can probably use the `?` workaround when the update icon is clicked in the dashboard, @gera2ld ?

**Comment by karlhorky** [comment]
Ah yeah, understood. Maybe `?updateTime=<timestamp>` or something...

---

If this feature is deemed generally useful, maybe making this apply to more URLs would be desirable (eg. not just for GitHub raw links), maybe allow for a special "variable" in the URL strings?

I'm not sure about what would be a good idea for variable delimiters, but after scanning a bit through RFC 2396 and RFC 6570, maybe something like this would be low risk of collision with real URLs:

```
https://example.com/?anyParamName=${__timestamp__}
````

This would replace the `${__timestamp__}` bit with the current timestamp.

**Comment by gera2ld** [comment]
Generally userscripts don't need to be updated very frequently, and we can wait until the server is ready to provide the updated data.

So I think we should respect the server's cache policy, rather than add a hacky workround to bypass this limitation and possibly increase the server's costs.

**Comment by tophf** [comment]
@karlhorky try asking github support if they can reduce the caching interval for their "raw" links.

**Comment by karlhorky** [comment]
Ok, thanks for the consideration anyway!
