### ISSUE TITLE
503 Error: Backend is unhealthy

### ISSUE THREAD

**Issue by karlhorky** [violentmonkey/violentmonkey#1173]
### What is the problem?

As described also in #1172:

I have a userscript at [this GitHub URL](https://github.com/karlhorky/dotfiles/blob/main/userscripts/add-tmdb-links-to-imdb.user.js) (and [this raw URL](https://raw.githubusercontent.com/karlhorky/dotfiles/main/userscripts/add-tmdb-links-to-imdb.user.js)).

I bumped the version to `1.0.1` to test that the updates were working. Since the "Check for updates" button was not working, I reverted to `1.0.0` and pushed again.

Then when I tried adding that URL after waiting for the Violentmonkey cache to update, it gave me this `503: Backend is unhealthy` error:

```json
{
  "url": "https://raw.githubusercontent.com/karlhorky/dotfiles/main/userscripts/add-tmdb-links-to-imdb.user.js",
  "status": 503,
  "headers": {},
  "data": "\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html>\n  <head>\n    <title>503 Backend is unhealthy</title>\n  </head>\n  <body>\n    <h1>Error 503 Backend is unhealthy</h1>\n    <p>Backend is unhealthy</p>\n    <h3>Guru Mediation:</h3>\n    <p>Details: cache-vie21645-VIE 1611403193 1997251410</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n"
}
```

I suspect this could be because of the move from version `1.0.1` to `1.0.0`.

### How to reproduce it?

1. Install a userscript from a URL
2. Revert to a previous version at that URL
3. Install / upgrade from that same URL

### What is the expected result?

It installs the `1.0.0` version

### What is the actual result?

It fails with a cryptic error message

### Environment

- Browser: Chrome macOS
- Browser version: 88.0.4324.96 (latest)
- Violentmonkey version: v2.12.9
- OS: macOS Big Sur 11.1

**Comment by tophf** [comment]
The error is returned by the github site, it's not Violentmonkey's cryptic message.

**Comment by karlhorky** [comment]
Ok, I wasn't able to see this in my testing anywhere else. Thanks!
