### ISSUE TITLE
Chinese characters were suddenly inserted in my code!

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1179]
WHAT THE HELL IS THIS?

![изображение](https://user-images.githubusercontent.com/33825590/106354672-940f9400-6304-11eb-901f-13784e4cdaaa.png)

**Comment by tophf** [comment]
You need to post a link to the userscript or attach it in a txt file here.

**Comment by soviet-man** [comment]
I just deleted this mess. I have no idea why this bunch hieroglyphs were inserted in my code. It's all happened after I press Ctrl+V having simple single line in clipboard.
