### ISSUE TITLE
Support changing parameters of menu commands without re-registering them?

### ISSUE THREAD

**Issue by aminomancer** [violentmonkey/violentmonkey#1182]
I've been working on a script that registers a menu command and wants to change the menu command and its label dynamically. Specifically, my script runs a callback at a user-defined interval, and the menu command pauses or unpauses that interval. So the menu command alternates between "pause" and "resume" behavior, and the label alternates accordingly. Actually, the behavior itself simply calls a toggle function inside the script, which handles whether it's a pause or a resume call. So for this particular case I don't actually need to change the callback dynamically. I just need to change the label/caption dynamically. But I figure if the label can be changed dynamically it shouldn't be much harder to change the callback.

What I've been doing so far is just to store the menu command's current label, and when I receive the callback to "change" the menu command, I call `GM_unregisterMenuCommand(currentLabel)` and then `GM_registerMenuCommand(newLabel, callback)` if that makes sense. Which is perfectly functional so this is a pretty minor complaint.

The trouble is that when I do it in this order, the menu command disappears for a moment before being replaced with the new menu command. The size of the violentmonkey popup jitters wildly for a moment. If I do it in the reverse order, the same thing happens except instead of shrinking briefly, the popup expands briefly as there are 2 menu commands for a moment instead of 0.

As you can see, this is obviously a really insignificant issue, like literally a fraction of a second's worth of an issue. Tiny as it is, it just seems like it should be pretty easy to add support for a new API method that changes the label and callback in one swoop without clearing the actual DOM nodes. Or one might not even need to add a new method. For instance, what if GM_registerMenuCommand returned an object with a setter for the label and a setter for the callback? Although I guess that wouldn't be desirable since it might break a huge number of existing scripts. Maybe a more robust version of the method could just be added in parallel to the current one, or maybe it really is better to just have a GM_changeMenuCommand function.

In any case, thanks for your work on this extension 🤗

**Comment by tophf** [comment]
I don't think a new API command should be added just for this moreover there's apparently a simpler solution: persist the old items visually for like 100ms so that if another item is added during that time the height won't change.
