### ISSUE TITLE
Wow, wtf?

### ISSUE THREAD

**Issue by idgas01** [violentmonkey/violentmonkey#1185]
@tophf 

I was going to respond with the test results of Violetmonkey BETA and I wasn't able to because:

 @violentmonkey violentmonkey locked and limited conversation to collaborators 33 minutes ago 

Unbelievable.  Just for asking for MutationObserver examples?  Excuse me for being an opportunist and trying to learn something from someone that I couldn't learn by myself.  I mean if you gave me a GM_addStyle example, how is that any different from giving me a MutationObserver example?

I'm so sick of GitHubs with crappy arse moderators.

**Comment by tophf** [comment]
The conversation was simply moved to discussions:
https://github.com/violentmonkey/violentmonkey/discussions/1184

I don't know where you learnt to behave like that but here you should be a little more patient, otherwise no one will pay attention to you.
