### ISSUE TITLE
Badge count does match matched count.

### ISSUE THREAD

**Issue by cmacfarl** [violentmonkey/violentmonkey#1186]
### What is the problem?

I have a trivial script that I'm using to figure out how to get the scripts to execute properly.

Here is the entirety of my script
```
// ==UserScript==
// @name        WaniKani ViolentMonkey Unit Test
// @namespace   WaniKaniScripts
// @match       https://www.wanikani.com/review/session
// @grant       none
// @version     1.0
// @author      Craig MacFarlane
// @description Violent Monkey Test
// @run-at      document-end
// ==/UserScript==

console.log("Hello ViolentMonkey Unit Test")
```

When I navigate to the matching url, The badge will indicate that there's a match, but on the dropdown list, the new Unit Test script is not listed, and I can find no evidence in the console that it ever executed.

![image](https://user-images.githubusercontent.com/1435639/107133410-a2c5f000-689c-11eb-8343-f62bfabbdff7.png)

The badge count say 9, but there are only 8 active userscripts listed and my new script is not among the active or inactive scripts in the dropdown.

One presumes that the 9th script being recognized on the badge is this unit test, but why is it not in the list, and why is it not getting executed?

Note that the Unit Test script does appear at the bottom of the ViolentMonkey dashboard.  Where I can select the edit icon and modify it.  And I've confirmed that it is not disabled.

### How to reproduce it?
1.  Install the script above.
2.  Navigate to https://www.wanikani.com/review/session

### What is the expected result?

Expect to see the script matched, in the dropdown list as enabled.  And expect to see the console message in the console.

### What is the actual result?

None of the above.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

![image](https://user-images.githubusercontent.com/1435639/107133491-98582600-689d-11eb-97f2-d7450b15ea0f.png)

### Environment
- Browser: Firefox
- Browser version: 84.0.2
- Violentmonkey version: 2.12.8
- OS: Windows 10

**Comment by cmacfarl** [comment]
Updated, does what I described I expect it to do above in v2.12.9.4.

![image](https://user-images.githubusercontent.com/1435639/107133590-b1ada200-689e-11eb-9550-6edf548917a4.png)

**Comment by tophf** [comment]
Apparently fixed, yay!
