### ISSUE TITLE
No output for console.log

### ISSUE THREAD

**Issue by ellipticview** [violentmonkey/violentmonkey#1187]
### What is the problem?
When running this script it displays the alert, but shows no log output in the Firefox console. Running exactly the same script in tampermonkey _does_ show the log entry.

### How to reproduce it?
Create a script with this content:

```
(function() {
    'use strict';
    console.log('xx');
    alert('Hello World !');
})();
```

This is probably related to the site on which I am running the script. Sorry; cannot provide a reproducible testcase because this site requires credentials.
Possible causes are warnings from the target website that are displayed in the log, such as:
Loading failed for the <script> with source “https://www.linnworks.net/Modules/OrderBook/OpenOrders/localization/en.js”.

### Environment
- Browser: Firefox
- Browser version: 78.7.1esr (32-bit)
- Violentmonkey version: v2.12.8
- OS: Windows 10

**Comment by tophf** [comment]
Violentmonkey doesn't change console.log so indeed it must be related to the site, assuming you see the output on other sites. Nothing we can do without a way to reproduce the problem. You can try debugging Violentmonkey yourself. I can upload a development build if you don't want to build it from source.

**Comment by tophf** [comment]
FWIW, you can use `GM_log`.

**Comment by tophf** [comment]
Another workaround is to [use `@inject-into content` mode](https://violentmonkey.github.io/api/metadata-block/#inject-into).
