### ISSUE TITLE
Clicking save does not change cached version of script

### ISSUE THREAD

**Issue by cmacfarl** [violentmonkey/violentmonkey#1188]
### What is the problem?

I've made changes to my script, saved them but they don't show up when actually running the script.

Old script.

![image](https://user-images.githubusercontent.com/1435639/107154858-ffbbb780-6929-11eb-958f-6b672c5bce2a.png)

New script, which replaced getNewSentence()

![image](https://user-images.githubusercontent.com/1435639/107154890-27ab1b00-692a-11eb-80f5-3ca314db2ebd.png)

I have changed and saved that script a dozen times.  I've refreshed the page, cleared the cache.  Nothing makes the old version of the script unstick.

### How to reproduce it?
1.  Write a script
2.  Test it.
3.  Change something
4.  See changes don't appear

### What is the expected result?

Save causes the new script to get put wherever it needs to be to run properly.

### What is the actual result?

See above.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

I'm running latest beta.  

### Environment
- Browser: Firefox
- Browser version: 84.0.2
- Violentmonkey version: bleeding edge latest
- OS: Windows 10

**Comment by tophf** [comment]
I can't reproduce the problem. What is the exact version of Violentmonkey you're running?

**Comment by tophf** [comment]
Also try closing and reopening the script tab in devtools or even devtools itself because it may be a bug in Firefox.

**Comment by cmacfarl** [comment]
I'm running 2.12.9.4

Away from my desk right now. I'll try the devtools suggestions when I get
back.

**Comment by cmacfarl** [comment]
Restarting firefox completely alone did not fix the problem.  But I was two versions behind firefox latest and updating to latest and see the script changing in devtools as I modify it.
