### ISSUE TITLE
Feature or bug? GM_openInTab in foreground only work for the last one

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#1194]
Environment
- Browser: Firefox 
- Browser version: 85.0.2
- Violentmonkey version: 2.12.8
- OS: Win10

I'd like to open first tab in foreground, the open second tab in foreground, then the third.
However, only the last one open in foreground, others opened in background.
I'm not sure what should I do.

```
// ==UserScript==
// @name        ! openInTab test
// @namespace   Violentmonkey Scripts
// @match       https://cn.bing.com/
// @grant       GM_openInTab
// @version     1.0
// @author      -
// ==/UserScript==

let links = document.querySelectorAll('a');
console.log(links);
let i = 0;
for (const l of links) {
  if (i > 3) return;
  setTimeout(GM_openInTab(l.href, false), 1000);

  i++;
  console.log(l);
}
```

**Comment by tophf** [comment]
This is a standard mistake with loops and asynchronous code: all calls to `setTimeout` were performed in one internal "task" of the *JS event loop* and all of them were scheduled at the exact same time.

The correct code would be like this:

```js
(async () => {
  for (const l of links) {
    if (i > 3) return;
    await new Promise(r => setTimeout(r, 1000));
    GM_openInTab(l.href, false);
    i++;
    console.log(l);
  }
})();
```
