### ISSUE TITLE
[firefox]通过"Track local file"同步本地js文件内容，不工作

### ISSUE THREAD

**Issue by liuxb** [violentmonkey/violentmonkey#120]
拖放一个外部.user.js脚本文件到violentmonkey，载入成功。
提示：Script data loaded.
然后选择“track local file before window closed”，然后点击 confirm installation。
提示：Script installed. ，然后马上变成：**Error loading script data.**
这时在外部编辑js文件，保存，violentmonkey中js内容没有跟随着变化。

firefox 55a1， violentmonkey 2.6.4.

**Comment by gera2ld** [comment]
似乎又是权限问题，firefox不让页面读文件。。。

**Comment by gera2ld** [comment]
Firefox issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1266960>

**Comment by goozak** [comment]
Might be a good idea to add this info to your "How to edit scripts with your favorite editor?" page.  Was coming here to report the same issue.
