### ISSUE TITLE
About the color of the switch

### ISSUE THREAD

**Issue by naskater** [violentmonkey/violentmonkey#1203]
Is it possible to change the color of the switch enabled and disabled by the script to more vivid and conspicuous colors?  such as green。The black doesn't look so obvious

**Comment by tophf** [comment]
You can change the entire UI of Violentmonkey using `Custom CSS` option in advanced settings.

```css
use[*|href="#toggle-on"] {
  fill: red;
}
```

Use any other [CSS color](https://www.google.com/search?q=color+picker) instead of `red`, like `#10a0e8`.
