### ISSUE TITLE
Can't save settings script in any way

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#1209]
### What is the problem?

Try to add a site in @include rules and receive message "Changes not saved!
Click OK to discard them or cancel to stay."

I tried in Firefox 86 and Vivaldi 3.6.2165.36 (windows 10)
violentmonkey 2.12.8
also tried with new profile on Firefox, new (clean) violentmonkey

**Comment by tophf** [comment]
This was fixed some time ago via 5ae8ea26, currently available in [beta releases](https://github.com/violentmonkey/violentmonkey/releases).
Meanwhile, you can change the code, too, like add and remove a space, then save.

**Comment by gabri25ele** [comment]
I didn't understand (apart from that the fix is ​​in beta release)

**Comment by tophf** [comment]
There's a tab in the editor named `Code` so click it, type a space there, remove it.
