### ISSUE TITLE
Not working with "netdna-storage bypass clicker"

### ISSUE THREAD

**Issue by mickcarterus** [violentmonkey/violentmonkey#121]
Could you try to see why Violentmonkey is not working with this script?
https://greasyfork.org/en/scripts/29692-netdna-storage-bypass-clicker

It's a script for autoclicking a download website from (NSFW) gaybeeg.info

**Comment by gera2ld** [comment]
It seems to have nothing to do with Violentmonkey. Can you provide a full reproduction?

**Comment by mickcarterus** [comment]
So i'm using chrome + tampermonkey. The script is supposed to auto click
the Download button on netdna-storage. That works fine with Tampermonkey.
However, if I switch to using ViolentMonkey, the page will keeps reloading.

Sincerely,

M. Carter

**Comment by gera2ld** [comment]
Cannot reproduce it. No download button is seen and no page is reloading.

**Comment by mickcarterus** [comment]
Here's a few examples (NSFW):
http://netdna-storage.com/f/bUZUm8nr/RD-SpitRoasted.mp4.html
http://netdna-storage.com/f/bUZUm8nr/MMB-ElderXanders-Initiation.mp4.html
http://netdna-storage.com/f/bUZUm8nr/BLM-Rapper-Chelo.mp4.html

Sincerely,

M. Carter

**Comment by gera2ld** [comment]
I have tested links above, by checking the source code, it is normal to keep reloading. I got the same result in Tampermonkey.

Since there is nothing to do with Violentmonkey, I'll keep this issue closed.
