### ISSUE TITLE
[feature request] Table view in Installed Scripts

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1210]
My suggestion is to be able to view the installed scripts as a *table* .

&nbsp;
Indeed, VM, compared to TM, currently displays more scripts in a screenful at max *(see screens)* :
VM --> 36 scripts (3 columns x 12 rows)
TM --> 29 scripts (as table list),
but, I find that: 
- VM's view is not compact enough , as each entry box still has some margin from its next, and 
- most importantly, if you sort the scripts alphabetically,
with TM the resulted list can be read as any table, i.e. each script entry after another, 
A
B
C
while with VM each displayed row has 3 sorted script entries, e.g.
A B C (1st row)
D E F (2st row)
etc.
thus making it not very easy to read.

To clarify, making VM display the entries sorted vertically, e.g.
A D
B D
C F
wouldn't help anything, because if you have a lot of scripts, the sorted "column" A>B>C would continue below the viewport.

I personally prefer table view in general, because I find it more compact, and easier to read.

&nbsp;
Here is a screenshot comparison: 
<sup>*(using Chrome 88 and latest VM/TM betas)*</sup>

<details>
<summary>VM (alphabet. sort)</summary>

![](https://user-images.githubusercontent.com/723651/109031504-76e4a000-76cd-11eb-9e85-c587399f44bd.jpg)
</details>

<details>
<summary>TM (alphabet. sort)</summary>

![](https://user-images.githubusercontent.com/723651/109031904-d3e05600-76cd-11eb-9a6b-8a58a2d24fa1.jpg)
</details>

<details>
<summary>TM (default sort)</summary>

![1](https://user-images.githubusercontent.com/723651/109032167-130ea700-76ce-11eb-8988-2acc6986709a.jpg)
</details>

Thank you

**Comment by tophf** [comment]
We will rethink the UI and ways to organize scripts in #287. Until then you can write your own CSS and put it in Violentmonkey's advanced settings in "Custom CSS" section, you can also publish it as a repo or a gist on github. If there will be many such themes we may even compile a list of them in Wiki here and link to it in VM settings.

**Comment by darkred** [comment]
Thanks for your response.

**Comment by darkred** [comment]
Thank you for implementing this, @tophf !
