### ISSUE TITLE
TypeError: <iterable>.entries() is not iterable, only in VM

### ISSUE THREAD

**Issue by szc126** [violentmonkey/violentmonkey#1213]
### What is the problem?

The following script fails within Violentmonkey (`TypeError: temp.entries() is not iterable`), but succeeds in a browser console:
```js
// ==UserScript==
// @name        TESTING 3 iterable 
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

let temp;

temp = new URLSearchParams(window.location.search);
console.log(1, window.location.search, temp, temp.toString());
for (let pair of temp.entries()) {
	console.log(pair);
}
```

### How to reproduce it?
1. Create a new script with the above contents.
3. Navigate to https://en.wikipedia.org/w/index.php?title=Main_Page&action=history.
2. View the browser console.

### What is the expected result?
```
1 ?title=Main_Page&action=historyURLSearchParams {  }title=Main_Page&action=history
Array [ "title", "Main_Page" ]
Array [ "action", "history" ]
```

### What is the actual result?
```
1 ?title=Main_Page&action=historyURLSearchParams {  }title=Main_Page&action=history
TypeError: temp.entries() is not iterable
```

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

```
1 ?title=Main_Page&action=historyURLSearchParams {  }title=Main_Page&action=history
TypeError: temp.entries() is not iterable
```

### Environment
- Browser: Firefox
- Browser version: 86.0
- Violentmonkey version: Firefox latest version→BETA v2.12.9.8
- OS: Arch Linux

**Comment by gera2ld** [comment]
Cannot reproduce, works for me on Firefox 86 / 87 with latest Violentmonkey.
Can you confirm if `temp` or `URLSearchParams` is modified by other scripts or extensions? Maybe log it to console and see if it's natively implemented.

**Comment by szc126** [comment]
Hm, I really should have tried that. 😳
The culprit seems to be uBlock Origin's "Disable JavaScript" option, if/when JS is disabled for the current domain.
But that still leaves the question of why only the iterable breaks, while the remainder of the script and Violentmonkey's script execution is otherwise unbothered.

**Comment by gera2ld** [comment]
Maybe the website has provided an incomplete polyfill.
I guess this issue can be closed now since it's not a problem of Violentmonkey.

**Comment by szc126** [comment]
It can't be related to polyfills; the same problem happens at https://example.com/test?key1=one&key2=two, which is JavaScript-free. I'll file a bug report with uBlock Origin then.

**Comment by tophf** [comment]
FWIW, `.entries()` is not necessary, removing it makes the code work, which is pretty weird as I thought it's just an alias.

**Comment by tophf** [comment]
Turns out this is not related to uBlock. When JS is disabled, Violentmonkey runs the scripts in the isolated world of a WebExtension content script so this is a bug in Firefox, which can be reproduced by loading an extension with this content script:

```js
console.log([
  new URLSearchParams()[Symbol.iterator],
  new URLSearchParams().entries()[Symbol.iterator],
]);
```

In Chrome it'll print two functions, in FF it'll print just the first one.

**Comment by tophf** [comment]
Found it: https://bugzil.la/1414602
