### ISSUE TITLE
Is GM_addValueChangeListener broken for remote Tabs?

### ISSUE THREAD

**Issue by Brandhand** [violentmonkey/violentmonkey#1214]
When I try the following script on a tab and then open other tabs, the GM_addValueChangeListener should fire, right?

```js
// ==UserScript==
// @name        New script - addValueChangeListener
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_addValueChangeListener
// @version     1.0
// @author      -
// @description 2/26/2021, 5:02:32 PM
// ==/UserScript==

const ss = GM_getValue('Bsp', 0);
GM_addValueChangeListener('Bsp', function (a,b,c,d) { console.log(`Value changed: ${a} ${b} ${c} ${d}`)});
GM_setValue('Bsp', ss + 1);
```

In my Firefox '87.0b3' with Violentmonkey v2.12.8 it only fires on the tab itself (also when reloaded).

I tried this on Tampermonkey and it works as expected.

**Comment by tophf** [comment]
It was fixed some time ago but not published in AMO yet.
You can install the [latest beta](https://github.com/violentmonkey/violentmonkey/releases).
