### ISSUE TITLE
[Feature Request]Tamper Verification Bypass

### ISSUE THREAD

**Issue by Lucas559-noob** [violentmonkey/violentmonkey#1218]
Some websites can check if user use a tamper(have installed) and don't allow user to continue browsing on their website.

### How to reproduce it?
1. go to here https://cdn.krnl.gg/getkey.php
2. it should show something like this 
"Detected possible tampers, try using a different browser!
Mozilla Firefox is mostly the best solution to try."
3.Can't do nothing there

### What is the expected result? 
A Bypass, maybe make it looks like is not a tamper
### What is the actual result?
Blocked for being a tamper

### Environment
- Browser: Microsoft Edge
- Browser version: 88.0.705.81 64 bits
- Violentmonkey version: v2.12.9
- OS: Windows 8.1

**Comment by tophf** [comment]
Doesn't seem related to Violentmonkey and the site shows the same message regardless of whether the extension is enabled or not.
