### ISSUE TITLE
Scripts do not save

### ISSUE THREAD

**Issue by Conzar** [violentmonkey/violentmonkey#122]
Any scripts added to violentmonkey do not persist.  For instance, [this](https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtector.user.js) script.  I add it to violentmonkey and click 'confirm installation'.  The message says 'script installed'.  However, when I navigate back to the violentmonkey dashboard, no script has been installed.

* **Chrome Version**: 58.0.3029.110 (64-bit)
* **OS**: Ubuntu 16.04
* **Violentmonkey**: v2.6.4

**Comment by gera2ld** [comment]
Cannot reproduce. Did you try reinstalling the extension? It is better if you can provide some error logs from background page or options page.

**Comment by anotherusername77** [comment]
Violentmonkey seems to be not working if Firefox is set on Private Mode (at least, with OSX).
Seems to be working if Private Mode is disabled, and scripts are correctly loaded... but, turning back on Private Mode, they disappear.

**Comment by gera2ld** [comment]
@anotherusername77 yeah, this is a known issue, see #169

**Comment by gera2ld** [comment]
Does the issue still occur? More info needed.

**Comment by gera2ld** [comment]
closed since no response for a long time
