### ISSUE TITLE
feature request：active iframe's tab by window.focus

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#1225]
The last release support window.focus, however, I can't active iframe's tab by it.

For example:
forground tab: A
background tab: B
iframe: C (in B)

How can I active B while C changing?

**Comment by tophf** [comment]
Tampermonkey grants this feature to framed scripts but we grant it only to the main page scripts, same as we always did with `window.close`. I guess this is intentional, @gera2ld ?

**Comment by gera2ld** [comment]
Rethinking about this, I think it may be unnecessary to limit the API in top window, because if a script wants to do it from an iframe, it actually can (via `postMessage`). Maybe it's better to let the script decide whether to do it in iframes?

**Comment by tophf** [comment]
Yeah, why not. I thought you tried to prevent some known abuse vector.

**Comment by tophf** [comment]
@ivysrono the next version will be able to do it, meanwhile you can send a message to the instance of your script in the main page via `top.postMessage` in the frame script.
