### ISSUE TITLE
[UX/UI] Too many notifications when there are a lot of errors updating scripts

### ISSUE THREAD

**Issue by T1mL3arn** [violentmonkey/violentmonkey#1228]
### What is the problem?

Sometimes (I have no idea why and when, probably my ISP is the reason) VM fails to update all the installed script. And with this it shows a lot of notifications like this:

![image](https://user-images.githubusercontent.com/9349164/111251840-bc0c4a00-865b-11eb-8370-eb13946cf33c.png)

These notifications occupy the whole vertical space (cause there are many of them), and if some links to the script are long - they occupy a lot of horizontal space too, making around of 40% browser window hidden.

### How to reproduce it?

I guess you need to call a lot of notifications https://github.com/violentmonkey/violentmonkey/blob/e8177755f1af05a2d47ac5e1eb8a51f6c66be0ad/src/background/utils/message.js#L5 at once (let's say 30) 

### What is the expected result?

The notifications are shown with delay, one by one (or small groups 2-3 message each), not blowing the screen. Or maybe VM should not update (when it does it automatically) all the scripts at once.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

Didn't test

### Environment
- Browser: Firefox 86.0.1 (64-bit)
- Violentmonkey version: v2.12.11
- OS: Win 8.1 x64

**Comment by tophf** [comment]
Indeed we can display just one notification with a list of problems if there is more than one error. Meanwhile you can uncheck the `Notify script updates` checkbox in Violentmonkey's settings.
