### ISSUE TITLE
脚本名称显示问题

### ISSUE THREAD

**Issue by lycleg** [violentmonkey/violentmonkey#1236]
大佬大佬，脚本名称显示上，应该显示@name的内容
但是如果脚本内，@name下，有@name：en时
插件的名称就显示@name：en的名称，而不显示默认的中文名称

例如https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97

**Comment by gera2ld** [comment]
这和你电脑配置的语言有关，比如我的是 `['zh-CN', 'en-US', 'en']`，就会去查找 `@name:zh-CN`、`@name:en-US`、`@name:en`，最后只匹配到了 `@name:en`，所以就显示成英文了。
可以在控制台输入 `navigator.languages` 查看你的电脑上配置的语言。

解决方案：在系统里改一下语言配置，在 `en-XX` 前面加上 `zh`，如 `['zh-CN', 'zh', 'en-US', 'en']`。

**Comment by tophf** [comment]
@gera2ld what about a selector in VM settings to choose the metadata language?

**Comment by gera2ld** [comment]
> @gera2ld what about a selector in VM settings to choose the metadata language?

I think it should be a list to choose since not all scripts use exact locale codes. Then it makes no difference to the browser preferences.

**Comment by tophf** [comment]
My primary language in the browser is English but if I add any _secondary_ language to Chrome's languages e.g. Russian it will be used to display script names with `@name:ru` key because this is how VM's `getLocaleString` works and I don't like it...

**Comment by gera2ld** [comment]
So we can add a different locale list? That makes sense to me.

**Comment by tophf** [comment]
If you don't want a VM setting, maybe we should restrict `getLocaleString` to use the first language in navigator.languages? It can be controlled via an option like "Display script metadata only in browser's primary language".

**Comment by gera2ld** [comment]
> Maybe we should restrict `getLocaleString` to use the first language in navigator.languages?

I think it is not friendly to multilingual users, or users who accept languages with different locale codes, like `zh`, `zh-CN`, `zh-TW`.

I prefer a list in advanced options, under the hood just a textarea with the value of locales each in a line, and falls back to `navigator.languages`.

**Comment by gera2ld** [comment]
It's a problem when only `@name` and `@name:ru` are provided and you prefer `@name`. I guess this is something the script author has to take into account since the locale suffix is designed to work this way -- the most specific one will be chosen. Maybe another `@name:en` should be added.

Or add a not-so-useful option to *disable the locale suffix*.

**Comment by tophf** [comment]
At first I thought about a list... and textarea is similar in complexity. Now I want to try to simplify it by exposing a simple checkbox to stick to the primary language: my hope/idea is that even multilingual users would still prefer uniformity of the script list. Currently the list looks less readable when it uses different languages because most scripts don't provide localized names.

**Comment by gera2ld** [comment]
> my hope/idea is that even multilingual users would still prefer uniformity of the script list

The fact is, while users prefer `zh-CN`, the script authors may only specify `zh` or `zh-TW`, so they have to include them all to avoid falling back to the default language. Another way is to match only the language part (`zh`) but there seems to be quite different locales sharing same language IDs so it may not be a good idea.

**Comment by tophf** [comment]
Well, I use only English language in the browser so I don't know what would be better. Maybe it's better to wait for someone affected by the problem to open an issue :-)

**Comment by kkocdko** [comment]
> > my hope/idea is that even multilingual users would still prefer uniformity of the script list
> 
> The fact is, while users prefer `zh-CN`, the script authors may only specify `zh` or `zh-TW`, so they have to include them all to avoid falling back to the default language. Another way is to match only the language part (`zh`) but there seems to be quite different locales sharing same language IDs so it may not be a good idea.

I agree with you, we shouldn't make it failback. If there haven't a `@name` matches `navigator.languages[0]`, the default name should be displayed.

Now I delete other language from browser setting to avoid this problem :(

**Comment by tophf** [comment]
@kkocdko, why don't you ask the authors of those userscripts to add the correct name e.g. `@name:en`?

**Comment by kkocdko** [comment]
> @kkocdko, why don't you ask the authors of those userscripts to add the correct name e.g. `@name:en`?

It's duplicate, both `@name` and `@name:en` have the same content.

**Comment by tophf** [comment]
I suggested to ask about using the **correct** name...
