### ISSUE TITLE
[Feature] Keyboard navigation for Popup menu

### ISSUE THREAD

**Issue by myfonj** [violentmonkey/violentmonkey#1238]
### What is the problem?
It is possible to assign keyboard shortcut for opening the popup menu, but there is no way to further interact with elements in there.

### How to reproduce it?
0. (Assumed browser: Firefox, used in Dev edition.)
1. Visit `about:extensions` > ⚙ Manage Extensions Shortcuts > Violentmonkey > Activate toolbar button: (set shortcut).
2. Invoke shortcut set in step 1.
3. Try to navigate trough popup's elements using keyboard (intuitively <kbd>Tab</kbd>, <kbd>Shift</kbd><kbd>Tab</kbd> or alternatively arrow keys) and trigger primary action of any element in there, e.g. Disable Scripts toggle that seem to be the first in assumed tab order.

### What is the expected result?
Disable Scripts toggle is highlighted after pressing <kbd>Tab</kbd> and invoked with <kbd>Enter</kbd> or <kbd>Spacebar</kbd>, like native checkbox.

### What is the actual result?
Neither <kbd>Tab</kbd>/ arrow keys, <kbd>Enter</kbd> nor <kbd>Spacebar</kbd> keys do anything.  It is only possible to close the popup with <kbd>Escape</kbd> and with the assigned shortcut.

### Environment
- Browser: Firefox
- Browser version: 88.0b3 20210325185929
- Violentmonkey version: 2.12.12
- OS: Windows 10

### Notes
(I'm not fluent in Vue, so apologies for potential misinterpretation. Plus I'm quite sure this insight will be unnecessary for most devs in here, but I feel it should be told:) Looking into https://github.com/violentmonkey/violentmonkey/blob/master/src/popup/views/app.vue it seems most interactive elements seemingly functioning like button or checkbox are actually implemented as `<div>`s or `<tooltip>`s (from "vueleton") with attached `@click` handlers.  Using "divs instead of buttons" is commonly considered a very bad approach by those with at least marginal interest in accessibility and good coding practices in general.  I don't know whether used libraries or Vue itself does a bad job in re-using listeners for keyboard-initiated events or does not even try (I'd not be surprised; recreating accessible interactive element from scratch is usually lots of work).
Normally using native HTML `<button>` or `<input type="checkbox">`  produces focusable elements that fires click handlers on spacebar or enter key press.  Such approach is AFAIK generally accepted as a best practice.

Looking at Stylus extension, it uses this approach (https://github.com/openstyles/stylus/blob/master/popup.html), so the effect is you don't necessarily need a mouse for using it at all; I'd be happy to see same approach in Violentmonkey. In fact I'm quite surprised to see such differences considering both extensions share core dev(s) (?))

BTW Dashboard page could use some focus styles for those elements that are already "native HTML", and minor accessibility overhaul, but at least one can navigate among installed scripts with arrow keys in there, but it's probably topic for other issue.

**Comment by tophf** [comment]
Yes, keyboard accessibility was something on my mind for quite a long time.

**Comment by gera2ld** [comment]
> Using "divs instead of buttons" is commonly considered a very bad approach

That is true, but it's simpler in this situation. I did this long time ago because I was using SVG icons as buttons and I didn't want to wrap every SVG in a `<button>` and deal with style issues among different browsers.
Even if they are all built with `<button>`s, I don't think it's keyboard friendly because there are so many of them.

I guess we can make the script items tabbable (it's focusable by arrow keys by now), and then provide some single key shortcuts to operate them. For example, <kbd>Space</kbd> to enable / disable a script, <kbd>e</kbd> to edit it, etc. What do you think about it?

**Comment by tophf** [comment]
In Stylus we're using `<a>` not `<button>` so we don't have to reset the appearance and deal with various ensuing browser bugs. We don't set `href` attribute so there's no useless built-in tooltip display by the browser for links. It's inherently tabbable via keyboard. The only thing it needs is a global listener for <kbd>Enter</kbd> key that re-dispatches a `click` event on such elements.
