### ISSUE TITLE
Page glitch when clicked New in v2.6.4

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#124]
Steps to Reproduce

Install VM or remove all scripts
Click on New
See this  - https://i.gyazo.com/874d887920964461ee86ba22e28df535.png

**Comment by uBlock-user** [comment]
Thanks for the prompt fix, looks like a regression bug.

**Comment by gera2ld** [comment]
It should have been there for some time, but it's hard to find it out.
