### ISSUE TITLE
有一个脚本大佬们看看我们的暴力猴能不能兼容下!!谢谢!!

### ISSUE THREAD

**Issue by Asteroids89** [violentmonkey/violentmonkey#1240]
### How to reproduce it?
1.
2.
3.

### Environment
- Browser:
- Browser version:
- Violentmonkey version:
- OS:
脚本地址:https://greasyfork.org/zh-CN/scripts/418182-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%AE%80%E6%98%93%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B-%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%A4%8D%E6%B4%BB%E7%89%88
![图片](https://user-images.githubusercontent.com/19388220/112847066-44b5cc00-90d9-11eb-8b13-12c3d658f01a.png)

**Comment by tophf** [comment]
If the script isn't compatible then describe the exact sequence of actions to reproduce the problem because we won't be doing it for you.

**Comment by Asteroids89** [comment]
感谢!!!
