### ISSUE TITLE
Bug：GUI for Fennec

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#1249]
[Fennec F-Droid | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/packages/org.mozilla.fennec_fdroid/)

![Screenshot_20210411-182644_Fennec_1](https://user-images.githubusercontent.com/2649544/114300699-319cf600-9af4-11eb-8df5-214d0d788b3c.png)

![Screenshot_20210411-182835_Trebuchet](https://user-images.githubusercontent.com/2649544/114300711-382b6d80-9af4-11eb-86f9-58cef7367500.png)

**Comment by tophf** [comment]
Looks like a bug in Fennec as its support of extensions is still in development. I've tried debugging it in an emulator but it doesn't work for me at all (pages are blank) so I won't be looking into this further. If @gera2ld won't look into it either, the issue may be closed.

**Comment by tophf** [comment]
I guess the first problem is that Fennec can't resolve `__MSG_extName__` in manifest.json. We could fix it by writing the real value in our build script.

**Comment by ivysrono** [comment]
> I don't understand the second arrow though.

Could not show the last.

**Comment by tophf** [comment]
> Could not show the last.

This is handled by the browser automatically (it should show a scrollbar) so I guess it's a bug in Fennec.

**Comment by ivysrono** [comment]
> This is handled by the browser automatically (it should show a scrollbar) so I guess it's a bug in Fennec.
> 
> Maybe the scrollbar is shown when you scroll the view by touching it and dragging?

Yes, the scrollbar is shown, I have scroll to bottom and the last can't show.

**Comment by tophf** [comment]
Yeah, sounds like a bug in Fennec then.

**Comment by tophf** [comment]
I've fixed the only bug that we could fix (the config UI position). As for the name in the menu, we could fix it by writing the real value in our build script but it won't support multiple languages so the name will be wrong in Chinese which is currently 暴力猴 not Violentmonkey.

**Comment by gera2ld** [comment]
> Could not show the last.

I think this is because Fennec does not work well with `100vh` height. The address bar in the bottom works like a float panel and hides only when the page scrolls up.
So if the page has a height of exactly `100vh` and cannot scroll up, the address bar floats for ever and we have no way to see the bottom part of the page. I've encountered this problem in other web pages too.

**Comment by ivysrono** [comment]
![Screenshot_20210411-201815_Fennec](https://user-images.githubusercontent.com/2649544/114304046-b0e5f600-9b03-11eb-802a-4e00dcbc9b42.png)
@tophf @gera2ld I re-screenshot the scrollbar. The address bar always show in VM and other extensions'( like ublockO ) pages, auto hide in web pages.
