### ISSUE TITLE
无法正确识别中文名称

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#125]
[购物党比价工具](https://greasyfork.org/zh-CN/scripts/14466-%E8%B4%AD%E7%89%A9%E5%85%9A%E6%AF%94%E4%BB%B7%E5%B7%A5%E5%85%B7)

GM 没问题。

**Comment by gera2ld** [comment]
有问题请描述具体细节，并提供重现方法。

**Comment by ivysrono** [comment]
点击安装即可复现。
VM和TM都识别成了英文名称：gwdang ，只有GM能正确识别该脚本的中文名称：购物党比价工具。

**Comment by gera2ld** [comment]
哦，我理解错误了 :dizzy_face:
