### ISSUE TITLE
Import / Export does not work (v2.12.13)

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#1253]
Firefox ESR, VM v2.12.13
Import / Export does not work. I also checked on a clean profile.

**Comment by gera2ld** [comment]
zip.js web worker seems to be blocked by Firefox.

**Comment by tophf** [comment]
The new zip.js creates workers from Blob, apparently. We should use a separate file like we did in the old version. I see such files in [dist](https://github.com/gildas-lormeau/zip.js/tree/master/dist) so we can either to get them from node_modules or build the same ourselves. Will you look into this, @gera2ld?

**Comment by gera2ld** [comment]
I will look into this later.



Sent from my Mi phone
Apr 12, 2021 18:48 wrote on tophf ***@***.***>:

The new zip.js creates workers from Blob, apparently. We should use a separate file like we did in the old version. I see such files in dist<https://github.com/gildas-lormeau/zip.js/tree/master/dist> so we can either to get them from node_modules or build the same ourselves. Will you look into this, @gera2ld<https://github.com/gera2ld>?
