### ISSUE TITLE
[Feature Request] Auto-update only upgrade scripts when browser version match specification

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#1258]
I'm not sure if this feature is very useful to others. But it seems to be useful to me.

When monkey detected a newer version of user script, it will upgrade it. But what if newer version of user script only runs on more recent browsers? User may get their functional broken after the script got upgraded. So I would suggest add some meta header to user scripts. So monkey may know the minimal version of environment to run the script. And give up upgrade if the required version is newer than the running version.

I'm still not quite sure how the structure may be applied. A possible idea is define some version numbers per browsers. And maybe use an regex to match UA is another option.

Monkey user may still install / upgrade by ignoring the version requirement manually. (may opt-out this feature)

**Comment by tophf** [comment]
The idea makes sense but it seems like an edge case because 1) only a small amount of people still use outdated browsers and 2) only a few scripts actually specify the version in `@compatible`.

**Comment by gera2ld** [comment]
Also it breaks the idea to sync between different browsers.
