### ISSUE TITLE
ViolentMonkey is freezing and not working from time to time in Chrome

### ISSUE THREAD

**Issue by gitti0** [violentmonkey/violentmonkey#1268]
### What is the problem?

ViolentMonkey is freezing and not working from time to time in Chrome. When that happened, the scripts and the ViolentMonkey extension option page are not loading.

If I'm able to clearly reproduce it I will report it here.

Did anyone has similar problem?

I notice this behavior in the last few builds of Chrome.

### How to reproduce it?

1. I don't know how to reproduce it but ViolentMonkey is freezing from time to time in Chrome.
2. I have this problem randomly on different pages.

### What is the expected result?

ViolentMonkey shouldn't freeze.

### What is the actual result?

ViolentMonkey is freezing.

### Environment
- Browser: Chrome
- Browser version: 88.0.4324.190
- Violentmonkey version: 2.12.14
- OS: Windows 10

**Comment by tophf** [comment]
Unfortunately there's nothing we can do without a sequence to reproduce the problem. Try creating a new browser profile and see if the issue happens there.
