### ISSUE TITLE
support for firefox android

### ISSUE THREAD

**Issue by ghajini** [violentmonkey/violentmonkey#127]
I installed violentmonkey from mozilla add-in page on firefox android, but it doesn't seem  to detect any script installation ......I am trying install script,but it won't install......
On firefox for android 53.0.2

Also it doesn't run actually.....Loaded extensions show up in firefox but vm not shown.....Eg iam using ublock origin and violentmonkey....But violentmonkey is not shown
![img_20170610_212302](https://user-images.githubusercontent.com/20338483/27004206-0df6cc5c-4e23-11e7-9977-bf90737d68e0.JPG)
@gera2ld

**Comment by ghajini** [comment]
Also for firefox nightly android, on when trying to install vm ,it says `corrupt`

**Comment by ghajini** [comment]
@gera2ld,
So with ver 2.6.4 iam able to install script successfully.....but iam not able to see interactive ui of violent monkey(where I can see which scripts were installed) or options/submenus of violent monkey....its not listed in currently loaded addons on Firefox android

**Comment by ghajini** [comment]
Any inputs @gera2ld

**Comment by hiltonjanfield** [comment]
This seems to be a widespread issue relating to how FF Android handles displaying of options. There is a thread about this on Bugzilla which indicates issue fixed for FF52/53/54, but requires addon developers do specific things for Android.

USI (the only other option, in alpha) has this figured out, showing general options in its Addons page as well as a menu item which opens their version of a dashboard. Unfortunately their script support seems lacking.

**Comment by ghajini** [comment]
Relevant bugzilla issues fixed@gera2ld and landed in Firefox nightly 57.01(28/8/17) but still issues lie on violent monkey side

1.
https://bugzilla.mozilla.org/show_bug.cgi?id=1364945

2.
https://bugzilla.mozilla.org/show_bug.cgi?id=1302504

**Comment by gera2ld** [comment]
@ghajini Please use Violentmonkey 2.8.9 in [releases](https://github.com/violentmonkey/violentmonkey/releases)
