### ISSUE TITLE
连接VPN扩展的时候同步失败的问题

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1278]
当我在使用某个VPN扩展时，当连接VPN后，无任何脚本的violentmonkey扩展，在进行同步webDAV时,会同步失败。而在同步过脚本后，进行删减脚本后的自动webDAV同步时，却同步成功了。请问这是否与网络有关？

**Comment by gera2ld** [comment]
网络问题请自行排查。信息不够我们也没啥可做的。

**Comment by violenttamper** [comment]
哦哦，感谢解答
