### ISSUE TITLE
扩展进行脚本编写时的设置功能的相关建议以及扩展的目标人群的提问

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1279]
我想建议的是：在新建脚本进行脚本编写的时候，能有一个设置选项可以进行"撤销"的操作，类似这个![118152275-17359f80-b447-11eb-8dd5-63b57754750b.png](https://user-images.githubusercontent.com/75355896/118404844-434f5b80-b6a7-11eb-8270-9ce4ed94c6fd.png)，以及增添其他便于编写脚本的功能。
    这对使用violentmonkey扩展编写或修改脚本有些帮助，因为可能violentmonkey扩展是个对用户方便使用，而对编写者可能有些不便，加了也许会变得方便，不加依然简洁。我更希望作者大大能考虑下。也许因此能有更多新用户，新编写者的使用。 
    如果是因为轻量化的原因不去添加上述功能 ，我也表示理解。
    我想知道violentmonkey扩展的目标人群是普通的使用者，是脚本编写者，还是二者都有?
    因为对普通用户来说，多余的脚本编写功能，其实并无大用，而对脚本编写者来说，可能更加方便，而值得加入新功能。所以我想了解扩展的目标人群，希望作者能说下。
    最后感谢作者大大能看到这里。

**Comment by tophf** [comment]
We won't be substantially enhance the editor. The idea is that authors should use their favorite editor or IDE, see
https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/

**Comment by violenttamper** [comment]
谢谢，我曾看过这个文章，理解这个决定。最后感谢回复。
