### ISSUE TITLE
possible to convert between tampermonkey and violent monkey?

### ISSUE THREAD

**Issue by Zhangsun321** [violentmonkey/violentmonkey#128]
https://github.com/whawker/TweetDeck-Chrome-Trends

doesn't work with violent monkey
says the script has no @gran tlines

can i run both tamper and violent...  if i disable the violent to install the script on tamper... then reactivate violent....??

**Comment by gera2ld** [comment]
`no @grant` is just a warning, you can suppress it in settings.

Violentmonkey and Tampermonkey can certainly run at the same time. But scripts installed on both of them will be run twice.
