### ISSUE TITLE
添加同步源的建议

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1280]
是否有计划加入对浏览器同步的功能，加入对yandex云的支持?

**Comment by gera2ld** [comment]
> 浏览器同步

No. See [FAQ](https://violentmonkey.github.io/faq/#why-are-third-party-sync-services-used-instead-of-native-ones).

> 加入对yandex云的支持?

PRs are welcome.

**Comment by violenttamper** [comment]
请问"PRs"是什么(ﾟoﾟ;?
