### ISSUE TITLE
请问能否增加一个快捷跳转到greasyfork安装地址的按钮

### ISSUE THREAD

**Issue by KKFantasy** [violentmonkey/violentmonkey#1282]
类似于tampermonkey一样，有些脚本没有配主页地址，可以显示安装地址
![image](https://user-images.githubusercontent.com/15992381/119105991-72bbea80-ba50-11eb-879f-146f63258ef1.png)

**Comment by violenttamper** [comment]
![IMG_20210521_165809.jpg](https://user-images.githubusercontent.com/75355896/119111666-dac0ff80-ba55-11eb-829c-da34e31e0d45.jpg)这个就是主页按钮

**Comment by gera2ld** [comment]
Seems to be answered.

**Comment by KKFantasy** [comment]
@violenttamper 我这边主页按钮是灰的，我是通过tampermonkey的备份导入的，试了下重新使用violentmonkey安装之后主页就恢复正常了。谢谢。
