### ISSUE TITLE
某个脚本安装时，显示脚本加载依赖失败。

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1283]
这个脚本自动加载了三四次后才显示可以安装了。不知道什么问题，之后重新安装后就没问题了。不过在清除cookie后，再重新安装脚本时，又会显示"加载脚本依赖失败"的情况。

脚本链接如下:https://greasyfork.org/zh-CN/scripts/329484-%E8%B1%86%E7%93%A3%E8%B5%84%E6%BA%90%E4%B8%8B%E8%BD%BD%E5%A4%A7%E5%B8%88-1%E7%A7%92%E6%90%9E%E5%AE%9A%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1-%E9%9F%B3%E4%B9%90-%E5%9B%BE%E4%B9%A6%E4%B8%8B%E8%BD%BD

**Comment by tophf** [comment]
Dependency means `@require` or `@resource` in the script. Apparently there's a network problem or a server problem. Retry later.

**Comment by violenttamper** [comment]
嗯嗯，我排查了一下，确实是网络问题，不过在同样网络下，tampermonkey扩展却很快加载出来了，这是什么原因?，最后感谢，解答

**Comment by tophf** [comment]
Network problems occur randomly.

**Comment by violenttamper** [comment]
嗯，确实和网络有关，感谢回答。

**Comment by mohalikeyou** [comment]
还真是网有问题.............
