### ISSUE TITLE
Could't use @require resource when @grant is't none

### ISSUE THREAD

**Issue by yola-0316** [violentmonkey/violentmonkey#1284]
```js
// @name        Test
// @namespace   test
// @match       *://*/*
// @grant       GM_addStyle
// @require     https://cdn.jsdelivr.net/npm/eruda
// @require     https://unpkg.com/jquery
// @run-at      document-start
// @version     1.0
// @author      -
```
when set `@grant GM_addStyle`, jQuery couldn't use in the script. it works while @grant is none.
### How to reproduce it?
1.
2.
3.

### What is the expected result?
Could use jquery in the script.

### What is the actual result?
jQuery is not defined.

### Environment
- Browser:
- Browser version:
- Violentmonkey version:
- OS:

**Comment by tophf** [comment]
Works for me. Can't help without seeing actual code that uses jQuery.

**Comment by yola-0316** [comment]
@tophf Sorry, the previous description isn't correct, It can not use in devtool for debugging propose when the grant is not none.

**Comment by tophf** [comment]
Works for me in Chrome so I guess you're using Firefox. Its debugger doesn't handle such scripts correctly. You can add `debugger` statement in your code.

**Comment by yola-0316** [comment]
@tophf I'm testing in chrome, it not works. Maybe many sites have been used jQuery. I am used d3 do testing replace jQuery to avoid confusion.
> Chrome version 90.0.4430.212 on windows 10.
![image](https://user-images.githubusercontent.com/4338052/119236384-b0606680-bb69-11eb-87aa-917f1fffe172.png)
![image](https://user-images.githubusercontent.com/4338052/119236391-ba826500-bb69-11eb-94cf-4a017e2eba7a.png)
It works when change GM_addStyle to none.

**Comment by tophf** [comment]
This is how userscripts work. Their `window` and global variables are sandboxed when `@grant` is not `none`.
