### ISSUE TITLE
[Feature Request] Provide API to notify update while in local file track develop

### ISSUE THREAD

**Issue by yola-0316** [violentmonkey/violentmonkey#1286]
### What is the problem?
Track local file is a great feature, If can provide a notify API, then could implement Hot Reload in development.

### How to reproduce it?
1.
2.
3.

### Environment
- Browser:
- Browser version:
- Violentmonkey version:
- OS:

**Comment by gera2ld** [comment]
Please clarify what it is supposed to do, step by step.
Maybe you are expecting a page reload when the script gets updated?
