### ISSUE TITLE
增加一个检查网站脚本被删除后不更新的功能的建议

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1289]
某些脚本被脚本网删除了，violentmonkey扩展更新后就成了空脚本无效了，如果只是禁用更新。就不清楚哪个脚本被脚本网站删除了，无法判断脚本是否可用。

**Comment by tophf** [comment]
This will be fixed when we implement #1023.

**Comment by violenttamper** [comment]
请问，这个意思是下个版本更新？

**Comment by tophf** [comment]
No.

**Comment by violenttamper** [comment]
请问，下个版本会改善那个情况吗？

**Comment by tophf** [comment]
No one knows when it'll be fixed.

**Comment by violenttamper** [comment]
OK，thank you very much😏
