### ISSUE TITLE
Script Does Not Work With Firefox Violentmonkey

### ISSUE THREAD

**Issue by kah0922** [violentmonkey/violentmonkey#129]
This issue is specific to the Firefox version of Violoentmokey only. This scripts works on the Chrome version of Violentmonkey and the Firefox version of Tampermonkey.

To reproduce:
Install Manga OnlineViewer: https://openuserjs.org/scripts/TagoDR/Manga_OnlineViewer.
Visit any supported site (Dynasty Scans for this example).
Pick any manga (This one for example: https://dynasty-scans.com/chapters/family_1)
Wait for the viewer to load after the popup.
The UI will load but no images will be loaded.

**Comment by ivysrono** [comment]
#107
