### ISSUE TITLE
对脚本的兼容性反馈

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1291]
(https://www.baiduyun.wiki/tool/install-darkmode.html ）这个脚本在 " https://violentmonkey.github.io/ "这个页面有时可能会不生效。这是一个适用于所有站点的脚本。

**Comment by tophf** [comment]
We don't debug userscripts.

**Comment by violenttamper** [comment]
好的，希望能加强兼容性。
