### ISSUE TITLE
script with `@run-at document-start` does not always run before other scripts

### ISSUE THREAD

**Issue by biuuu** [violentmonkey/violentmonkey#1293]
### What is the problem?
A user script I maintain needs to be executed as early as possible to work properly.
But I found that as the script size increases, @run-at document-start cannot take effect stably.
### How to reproduce it?
I made a test page and userscript to show the problem.

__The Page:__ https://mio.danmu9.com/test.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>test user script</title>
  </head>
  <body>
    <div id="app"></div>
    <script>console.log('script in html')</script>
  </body>
</html>
```

__The userscript:__ https://mio.danmu9.com/test1.user.js
```
// ==UserScript==
// @name        New script - mio.danmu9.com/test.html
// @namespace   Violentmonkey Scripts
// @match       https://mio.danmu9.com/test.html
// @run-at      document-start
// @version     1.0
// @author      -
// @description 2021/6/23上午9:41:53
// ==/UserScript==
console.log('user script')

// (function () {
//   'use strict';

//   const ENVIRONMENT = "development";
//       const DEV = true;
...
Behind is more than 10,000 lines of commented code, the script size is about 500KB.
```

### What is the expected result?
The console should display `user script` first and then `script in html`.
### What is the actual result?
![image](https://user-images.githubusercontent.com/10892119/123025040-9afe8680-d40c-11eb-87f9-de9a0cc384af.png)
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
v2.13.0

### Environment
- Browser: Google Chrome
- Browser version: 91.0.4472.114 (64bit)
- Violentmonkey version: v2.13.0
- OS: Windows 10

**Comment by gera2ld** [comment]
This is actually a known issue, as documented [here](https://violentmonkey.github.io/api/metadata-block/#run-at):

> The script executes as soon as possible. There is no guarantee for the script to execute before other scripts in the page.

**Comment by tophf** [comment]
The only way to guarantee it in Chrome would be for us to implement a hack via synchronous XHR (#1100) like instant inject in Tampermonkey. On the other hand, soon we will have to rewrite large parts of the extension for ManifestV3 where the API is completely different and will guarantee proper timing...

**Comment by biuuu** [comment]
Thanks for the answer, I think I should find a way to reduce the size of the script to avoid this problem and wait for the release of ManifestV3.
