### ISSUE TITLE
Could not export the Script to zip file to local

### ISSUE THREAD

**Issue by pbnlw123** [violentmonkey/violentmonkey#1294]
### What is the problem?
When i try to backup the script to zip file to local PC. it could not pop-up windows to let me save the script.
### How to reproduce it?
1.The new version could not allow to export script to zip file
2.Try many times all failure
3.Only the sync way to find my script from the cloud

### What is the expected result?
Fix this issue that let the user export the zip file
### Environment
- Browser:
- Browser version:
- Violentmonkey version:
- OS:

**Comment by tophf** [comment]
It works for me. 

1. Fill the info in the template as required:

> Browser:
Browser version:
Violentmonkey version:
OS:

2.  Describe the exact actions you perform like which button you click and so on.

**Comment by GavinBrelstaff** [comment]
I get the same bug: nothing happens when I click [Export to Zip] within Settings.

Browser: FireFox 91.0 (64-bit) Windows
OS Window 10 64
Violentmonkey: v2.13.0

**Comment by tophf** [comment]
Still can't reproduce the problem. 

1. Try copypasting the debug log: open `about:debugging`, click `inspect` in Violentmonkey's entry, a new tab will open, switch to `Console` there, select all, copypaste here.
2. Try creating a new browser profile with just one Violentmonkey extension and try there.
