### ISSUE TITLE
Changes for the currently opened key in storage editor are lost if GM_setValue is used for an unrelated key

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1299]
### What is the problem?
Unable to append to JSON values through editor normal fashion. Also if you press save when you additions are present and invalid,  the value itself gets deleted completely. 

### How to reproduce it?
1. Create a JSON value like below
![Snap45](https://user-images.githubusercontent.com/8114076/123630714-bc48e380-d80d-11eb-82c2-ea57bbf4ba82.jpg)

2. try to insert the number 3 between 2 and 4 
3. Then while number is present press save. If you are too slow the edits gets removed, if you manage to press save while edits are present and there is a small error the stored value is deleted.

### What is the expected result?
Ability to amend and append to the JSON value in a normal fashion without timeout.

### What is the actual result?
It just resets value unless you press save quickly and then if there is an error it removes stored value and everything is lost.

### Environment
- Browser: Firefox
- Browser version: 89.0.2 64bit
- Violentmonkey version: 2.13.0
- OS: Windows 10

**Comment by tophf** [comment]
I can't reproduce the problem. Do you have a script that writes the value while you edit it? A screen recording might help.

**Comment by TimidScript** [comment]
> I can't reproduce the problem. Do you have a script that writes the value while you edit it? A screen recording might help.

Hi, I just updated the content. It seems having carriage return casues errors. But the timeout issue is still present. There is no script that writes into the value. I created a value called "AAA" and then tried to edit it.

So take these steps:

1) Create value "AAA" with content [1,2,3,5,6] and then save.
2) Then slowly edit it and watch it reset value

OR
1) Create value "AAA" with content [1,2,3,5,6] and then save.
2) Then edit it and make a mistake like adding two commas and save and it will delete JSON value


Here is a gif with steps taken: https://imgur.com/a/I8HkFlJ

**Comment by tophf** [comment]
I still can't reproduce the problem. I also can't save an invalid value with two commas. Do you have a script that writes the value while you edit it?

**Comment by TimidScript** [comment]
> I still can't reproduce the problem. I also can't save an invalid value with two commas. Do you have a script that writes the value while you edit it?

I get it now. The script does not write to the value "AAA" but writes to other values. It seems if script is running and writing to other values, it still affects the one you are trying to edit.
