### ISSUE TITLE
夜间护眼或者黑暗护眼的功能建议

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1308]
请问，是否可以加入给扩展一键开启夜间护眼的功能，这对浏览器上使用了夜间模式的扩展的人，在设置violentmonkey扩展时，会很有帮助。希望可以采纳，谢谢！

**Comment by tophf** [comment]
Violentmonkey switches to the dark mode automatically when the system and the browser are running in dark mode.

**Comment by violenttamper** [comment]
了解，感谢回复
