### ISSUE TITLE
疑似对 run-at document-start 支持不足

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#131]
[浦发银行个人网银动态密码版 Windows 登录免安全控件](https://greasyfork.org/zh-CN/scripts/7537)
安装后进入 https://ebank.spdb.com.cn/nbper/prelogin.do#

> 尊敬的客户，您当前使用的系统暂不支持浦发网银安全控件，建议您通过其他支持浦发网银安全控件的系统访问。如您继续访问，可能导致您的密码等隐私信息的泄漏，您在此系统上的操作将无法得到有效保护。是否继续访问？

在如上提示后应可无需插件输入密码。

GM 支持, TM 4.3.5447+ 支持。

记得原来在 Chrome 版 VM 是支持的，但现在 2.6.4 和 2.6.3 无论 Chrome/Firefox 都不支持。
Chrome 2.6.4 是有提示要插件，Firefox 2.6.3 是无提示，要插件。
是否是 run-at document-start 具体执行的时间点有问题？

**Comment by gera2ld** [comment]
我测试正常，无法重现

**Comment by ivysrono** [comment]
额，我已经几乎排查成玄学问题了。
这个脚本的支持 GM>TM>VM
但如何稳定重现bug……
继续试验ε=ε=ε=┏(゜ロ゜;)┛

**Comment by gera2ld** [comment]
`document-start`只能尽量靠前，没办法保证一定在最前面的，毕竟扩展的初始化也需要时间。GM好像有特殊的API可以阻塞页面所以有可能支持。。。

**Comment by ivysrono** [comment]
多次排查下来，不能稳定的重现问题，但部分可确认信息如下：
1、VM仅此一个脚本时，有较低概率出现失效的情形，随着脚本安装数量的增多而增多，甚至不在本页面生效的脚本也有可能增加该脚本失效的可能。
2、GM 失效的可能极低，可以忽略不计。TM 4.3.5447 以前版本失效概率与 VM 相当，TM 4.3.5447+ 失效概率已经很低了，接近GM。原因不明。

不负责任瞎扯淡的缓解方案：
1、增加脚本间生效排序手动处理，保证该脚本第一个生效。
2、增加特殊语法，可以指定在特定页面仅该脚本生效。
如果能实现，这规则不知能否在脚本内部声明。
3、研究下TM新版的黑魔法？

**Comment by ccd0** [comment]
Related (for the case of Firefox):
https://bugzilla.mozilla.org/show_bug.cgi?id=1332273

**Comment by jspenguin2017** [comment]
如果 `document.write` 一个 `<script>` 然后用背景页面重新定向到一个 `data:` 链接的话貌似可以阻塞页面加载直到猴子脚本加载运行完。
或者试试用同步的 `XMLHttpRequest` ？

**Comment by gera2ld** [comment]
synchronous XMLHttpRequest 已经被新版Chrome和Firefox抛弃了，已经不支持了。
`document.write`本身也是JS，也是需要扩展来在合适的时机注入的，这就回到了最初的问题。
而且任何阻塞页面影响性能的行为都是不提倡的。

以后考虑改变数据存储方式（#152），优化初始化过程，也许会有改善。

**Comment by jspenguin2017** [comment]
虽然说不提倡，但是有时猴子脚本必须在真正的 `document-start` 运行才能生效，其他插件不应该阻塞页面，但是猴子脚本管理器是例外……

**Comment by gera2ld** [comment]
Chrome是没有阻塞的方法的，以前有的也去掉了，所以这是不能实现的。这跟`document.write`根本没有关系。。

**Comment by gera2ld** [comment]
现在有没有快一点？如果再不行只能won't fix了。。。

**Comment by ivysrono** [comment]
用Chrome测了下最新版，正常运行。
谢谢。
至于Firefox，什么时候新版能过审啊

**Comment by gera2ld** [comment]
@ivysrono 正在审核中，不知道能不能过。。。orz

**Comment by ivysrono** [comment]
@gera2ld 最新的 2.8.18 在
Chrome 稳定版 62 上又不行了。禁掉所有其他扩展和脚本也不行。
Firefox beta 58 上登录页面可以，后面交易不行。同时安装了 GM4 就专门对付这个脚本。

**Comment by gera2ld** [comment]
嗯，就是那个用blob注入导致的问题，下个版本改回去

**Comment by ivysrono** [comment]
就是支持 GM_openInTab 造成的？改回去了又不支持 GM_openInTab 了？

**Comment by gera2ld** [comment]
@ivysrono 为了支持Firefox下面的有CSP限制的页面啊

**Comment by ivysrono** [comment]
都是刚需啊
