### ISSUE TITLE
Support multiple profiles in one sync service

### ISSUE THREAD

**Issue by allblue** [violentmonkey/violentmonkey#1315]
### What is the problem?
目前采用onedrive同步时，只能同步到默认的violentmonkey目录。同于该应用名称无法更改。因此1个onedrive帐户只能同步1套设置。

像我这种工作电脑、家用电脑采用不同配置的，只能选用多个onedrive帐号或webdav方式同步，是否能在onedrive同步时增加应用名称自定义设置功能，以区分不同脚本配置，实现1个onedrive帐户同步多套配置效果。

### How to reproduce it?
无

### What is the expected result?
1个onedrive帐户同步多套配置。

### What is the actual result?
无
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
无

### Environment
- Browser: firefox 
- Browser version: 90
- Violentmonkey version: 2.13.0
- OS: Windows 10 X64

**Comment by gera2ld** [comment]
Closing in favor of #1306

**Comment by tophf** [comment]
Sounds like #1273.
