### ISSUE TITLE
Kiwi Browser Chromium 93

### ISSUE THREAD

**Issue by liquidmetalrob** [violentmonkey/violentmonkey#1318]
Violentmonkey was working on Kiwi Browser up until it got updated to Chromium 93, now my previously working scripts don't run anymore.

**Comment by liquidmetalrob** [comment]
I've managed to fix it now. I think the problem is that specifying run-at document-start causes a script to fail now.

**Comment by tophf** [comment]
A self-resolved issue is the best issue! BTW [this info](https://github.com/violentmonkey/violentmonkey/issues/1292#issuecomment-860143458) may be helpful for you.
