### ISSUE TITLE
GM_setClipboard Conflict with TitleUrlCopy

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#1319]
### How to reproduce it?
1.Install [TitleUrlCopy](https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/)
2.use GM_setClipboard or GM.setClipboard in script.
3.get page's `Title & URL`

### Environment
- Browser: Firefox
- Browser version:90
- Violentmonkey version:2.13.0
- OS:Win10

**Comment by tophf** [comment]
The description of that extension says it works only when Ctrl-C/Cmd-C is pressed but that is not true: that extension intercepts all `copy` events and overwrites the copied data so there's nothing Violentmonkey can do. This is something only TitleUrlCopy's author can fix.

P.S. GM_setClipboard doesn't work in Firefox for me at all if used directly, which actually matches the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_execcommand()):
> The document.execCommand() method's "cut" and "copy" commands [...] can be used [...] in a short-lived **event handler for a user action (for example, a click handler)**.
