### ISSUE TITLE
为何已同步时间提醒，Chrome是24小时制，Firefox是12小时制？

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#132]
![default](https://user-images.githubusercontent.com/2649544/27040774-9971aee4-4fc4-11e7-9d24-60819cb69fa1.png)

![default](https://user-images.githubusercontent.com/2649544/27040781-9e7573d0-4fc4-11e7-8014-18a895a7bfb5.png)

**Comment by gera2ld** [comment]
直接用的浏览器在当前语言环境下的时间格式，跟浏览器的语言设置有关。
