### ISSUE TITLE
Script not run

### ISSUE THREAD

**Issue by bokunodev** [violentmonkey/violentmonkey#1322]
### What is the problem?
my script does not run and it give me this message **"Sub-frames only scripts: 1"**

### How to reproduce it?
1. create a new script
2. paste this
```JavaScript
// ==UserScript==
// @name        Google Tweak
// @namespace   local.google
// @match       *://*google.com/*
// @grant       none
// @version     1.0
// @run-at      document-idle
// @author      bokunocode
// ==/UserScript==
;
(function() {
  'use strict';
  document.querySelectorAll("a").forEach(function(a) {
    a.onmousedown = null;
    a.onclick = null;
    console.log(a)
  });
});
```
3. toggle script on and off, refresh the page.

### What is the expected result?
event on all `a` elements, removed.

### What is the actual result?
nothing happen, 
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
i've tried both stable and beta from chrome web store

### Environment
- Browser: Opera
- Browser version: Opera 77.0.4054.277
- Violentmonkey version: Version 2.12.14.1
- OS: Linux Arch

**Comment by AlttiRi** [comment]
> `// @match       *://*google.com/*`

> Browser: Opera

Did you have enabled `Allow access to search page results` for this extension?

**Comment by AlttiRi** [comment]
You just have wrong written IIFE.

**Comment by AlttiRi** [comment]
BTW, I use it:
```js
function clearLinks() {
    const links = document.querySelectorAll("a");
    for (const link of links) {
        if (link.hasAttribute("onmousedown")) { 
            link.removeAttribute("onmousedown");
        }
    }
}
const searchDiv = document.querySelector("#search");
if (searchDiv) {
    clearLinks();
    searchDiv.addEventListener("DOMNodeInserted", clearLinks);
}
```

**Comment by bokunodev** [comment]
> Did you have enabled `Allow access to search page results` for this extension?

thanks, it works now.

**Comment by tophf** [comment]
@gera2ld, I wonder if we should show a special message in popup for Opera + google/bing/duckduckgo like `You may need to enable "Allow access to search page results" in Opera browser settings and reload this tab`.

**Comment by bokunodev** [comment]
something logged to the console also very helpful.

**Comment by gera2ld** [comment]
> @gera2ld, I wonder if we should show a special message in popup for Opera + google/bing/duckduckgo like `You may need to enable "Allow access to search page results" in Opera browser settings and reload this tab`.

It is reasonable, just a little annoying that we have to code for another specific browser.

> something logged to the console also very helpful.

I guess we are not able to log anything to the console if we don't have access to the page at all.

**Comment by AlttiRi** [comment]
+yandex

**Comment by bokunodev** [comment]
@gera2ld by logging to console i mean, firefox and opera (i never use chrome) has ability to debug extensions.
currently it does not log anything about unable to inject script etc.

**Comment by tophf** [comment]
Violentmonkey can't write to the console of such tabs.

**Comment by bokunodev** [comment]
> Violentmonkey can't write to the console of such tabs.

not in console of current tab. in debug console.
open this in firefox `about:debugging#/runtime/this-firefox`

**Comment by tophf** [comment]
We don't write anything to that console normally because most users have no idea how to access it. You can compile a debug build from source and there will be many messages there. However, Violentmonkey doesn't inject its scripts explicitly when using the default (page) mode ([more info](https://violentmonkey.github.io/api/metadata-block/#inject-into)), it's only for the `content` mode that you will see an error there when injection fails.

Anyway, the next version tests injectability in the popup and displays the message accordingly.
