### ISSUE TITLE
Native `fetch` does not work (sometimes) in the latest Firefox

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1325]
### What is the problem?

I have [userscript for Twitter](https://github.com/AlttiRi/twitter-click-and-save).
It works fine everywhere. Even if I just paste it to the console.

Except Violentmonkey + Firefox (90).

While it works OK in Firefox ESR (78). TM + FF90 also works OK.

### How to reproduce it?
1. Install https://github.com/AlttiRi/twitter-click-and-save/raw/master/twitter-click-and-save.user.js
2. Try to download an image or a video. By click on the button over the image. For example from: https://twitter.com/SpaceX/status/1418667693016711170

### What is the expected result?
The image is downloaded.

### What is the actual result?
`fetch` fails to download `https://pbs.twimg.com/media/E7AdwdkUYAAqxy3?format=jpg&name=orig`:
```
TypeError: NetworkError when attempting to fetch resource.
```
![2](https://user-images.githubusercontent.com/16310547/127583679-30744f14-b645-40f1-9c67-9dbd55f000c5.png)

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
The same.

### Environment
- Browser: Firefox
- Browser version: 90
- Violentmonkey version: The latest from AMO
- OS: Win 10

**Comment by AlttiRi** [comment]
While POST `fetch` to API work OK:

![image](https://user-images.githubusercontent.com/16310547/127583952-6563fda8-e947-4885-8a41-2f2264174fa6.png)

But GET to `pbs.twimg.com` fails:
 ![1](https://user-images.githubusercontent.com/16310547/127583984-bac9615f-2f9a-4592-b0e7-b2fe4d5cfa7f.png)

**Comment by AlttiRi** [comment]
The most simplified demo:
```js
// ==UserScript==
// @name        Twitter fetch demo
// @version     0.1
// @namespace   gh.alttiri.fetch
// @match       https://twitter.com/*
// @description https://github.com/violentmonkey/violentmonkey/issues/1325
// ==/UserScript==

(async function() {
  console.log("xxx-1");
  const url = "https://pbs.twimg.com/media/E7AdwdkUYAAqxy3?format=jpg&name=orig";
  try {
    const res = await fetch(url);
    console.log("xxx-2", res, url);
  } catch(e) {
    console.error("xxx-e", e, url);
  }
})();
```

**Comment by AlttiRi** [comment]
Very interesting moment is that if I enable the script in Tampermonkey then Violenmokey starts to work:

![3](https://user-images.githubusercontent.com/16310547/127584404-8add1f55-382f-4f68-9d2f-add0b070f385.png)

**Comment by tophf** [comment]
I can't reproduce the problem neither with twitter-click-and-save.user.js nor with the simplified demo. I've tried like 20 times each time reloading the page.

The fact that enabling Tampermonkey makes it work for you indicates a bug in Firefox (`fetch` is failing in content script context but works in page context) because when Violentmonkey is alone it runs userscripts in `content` mode due to twitter's CSP forbidding DOM `script` elements (which we use to inject userscripts in page context), whereas Tampermonkey disables CSP header of the site so the userscripts may run in page context freely.

**Comment by tophf** [comment]
Please also try your script in a new browser profile without any other userscripts or extensions except Violentmonkey.

**Comment by AlttiRi** [comment]
The reason is `Browser Privacy` -> `Enhanced Tracking Protection` -> `Strict`
![image](https://user-images.githubusercontent.com/16310547/127656940-1572b952-5c26-44bd-9902-511f3b835c63.png)

**Comment by tophf** [comment]
In that case I don't see what we can do here. We decided not to include a CSP-patch option because there are several other extensions that can do it.

**Comment by AlttiRi** [comment]
Note: however in Firefox ESR even with `Strict` it works.

**Comment by tophf** [comment]
Which kinda confirms to me that it's a browser thing, either a bug or intentional change in the newer version.

**Comment by tophf** [comment]
`await wrappedJSObject.fetch(url)` works (it uses the function from page context), which means that it's a problem in Firefox's implementation of CSP in content scripts.

**Comment by AlttiRi** [comment]
The interested moment with
```js
const fetch = (wrappedJSObject && typeof wrappedJSObject.fetch === "function") ? wrappedJSObject.fetch : fetch;
```
is that `fetch` with `{cache: "force-cache"}` fails with:
```
Error: Permission denied to access property "body"
```

**Comment by tophf** [comment]
That's because you must export the non-literal value (the config object) to the page context:
```js
await (wrappedJSObject || window).fetch(url, cloneInto({cache: "force-cache"}, document))
```
More info: [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts).

**Comment by AlttiRi** [comment]
Looks working.
```js
const fetch = (globalThis.wrappedJSObject && typeof globalThis.wrappedJSObject.fetch === "function") ? function(resource, init) {
    return globalThis.wrappedJSObject.fetch(resource, cloneInto(init, document));
} : globalThis.fetch;
```

**Comment by AlttiRi** [comment]
It was good until I checked [a video](https://twitter.com/elonmusk/status/1413598670331711493).

`wrappedJSObject.fetch` fails when you pass a Headers object to `cloneInto`.

```
Error: Encountered unsupported value type writing stack-scoped structured clone
```

With [the updated userscript](https://github.com/AlttiRi/twitter-click-and-save/raw/master/twitter-click-and-save.user.js):

![vm3](https://user-images.githubusercontent.com/16310547/127716234-67e441f9-973a-4525-8b88-b4a356daea77.png)
![vm2](https://user-images.githubusercontent.com/16310547/127716240-d6e65b7a-ad0b-4b2b-9621-cb8ad06068fb.png)
![vm1](https://user-images.githubusercontent.com/16310547/127716243-be96c191-106c-4c9f-86c9-11b0d28a5182.png)

---

While it works in TM. But it replaces `cloneInto` with some other function:

![tm](https://user-images.githubusercontent.com/16310547/127716360-6121960a-2d1e-474e-bcdc-e85f142bc67c.png)

**Comment by AlttiRi** [comment]
Okay, `Headers` are not [structured cloneable](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm):

```js
function structuralClone(obj) {
  return new Promise(resolve => {
    const {port1, port2} = new MessageChannel();
    port2.onmessage = m => resolve(m.data);
    port1.postMessage(obj);
  });
}
const obj = new Headers();
const clone = await structuralClone(obj);
// Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': Headers object could not be cloned.

```

 But I can pass `headers` as a usual JavaScript object, so the additional code:
```js
/** @param {Headers} headers */
function headersToSimpleObject(headers) {
    const temp = {};
    for (const [key, value] of headers.entries()) {
        temp[key] = value;
    }
    return temp;
}
if (init.headers instanceof Headers) {
    init.headers = headersToSimpleObject(init.headers);
}
```

**Comment by tophf** [comment]
FWIW, there's no need to use `Headers`. Just use a simple object.

**Comment by AlttiRi** [comment]
As I understand, `window.wrappedJSObject` is used only when required? (Only on pages with CSP.)

I noted that on https://example.com `window.wrappedJSObject` in `undefined` and `fetch` from the web page context works without any problems.
