### ISSUE TITLE
Violentmonkey beta in Chrome Web Store is still 2.12.14.1

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1326]
I see in the Violentmonkey beta [CWS page](https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg) that the latest version is still 2.12.14.1, dated April 22.
But, there have been two betas since then, 2.13.0.1 and 2.13.0.2 (see [Releases](https://github.com/violentmonkey/violentmonkey/releases)).

In the `Release` action workflow ([release.yml](https://github.com/violentmonkey/violentmonkey/blob/master/.github/workflows/release.yml)) there's currently no entries to automatically publish each release to neither CWS nor AMO, so it has to be done manually by you every time.

Maybe you would like to consider adding the relevant entries to automate the process for each new release?

PS. For reference, here are the relevant entries for the 'Refined GitHub' extension's [release.yml](https://github.com/sindresorhus/refined-github/blob/4af1669e2dba94a1d170dfe563b88416582be716/.github/workflows/release.yml#L61-L77)

**Comment by gera2ld** [comment]
Beta versions for Firefox are created automatically with the official tool [sign-addon](https://github.com/mozilla/sign-addon) in `release.yml` workflow.

The latest beta version was rejected on CWS (some time ago) so I'll have to make an update before it can be published.

By now the releases are submitted manually indeed. 😅 

> PS. For reference, here are the relevant entries for the 'Refined GitHub' extension's [release.yml](https://github.com/sindresorhus/refined-github/blob/4af1669e2dba94a1d170dfe563b88416582be716/.github/workflows/release.yml#L61-L77)

Thanks for the great suggestion, I'll look into it later.

**Comment by darkred** [comment]
I'm glad that after commit https://github.com/violentmonkey/violentmonkey/commit/3766b7600f133ce9c96f0d50927200016677c715 , VM beta in CWS has been updated today to v2.13.0.5 . 
Thank you.

**Comment by darkred** [comment]
The issue has occurred again: 
in CWS the the latest VM beta version is still 2.13.10.2 dated Feb.18, but there has been a new beta, 2.14.1, dated 3 days ago.

Seeing the [relevant workflow](https://github.com/violentmonkey/violentmonkey/actions/runs/4422227476/jobs/7753830678#step:8:58) it can be seen that "Publish to CWS" failed because:

```
Error Code: PKG_MANIFEST_PARSE_ERROR
Details: The manifest has an invalid version: 2.14.1b. Please format the version as defined 
      <a href="https://developer.chrome.com/extensions/manifest/version" target="_blank"> here</a>.
Error: Process completed with exit code 1.
```

<details><summary>Screenshot of the above error:</summary>
<p>

![](https://user-images.githubusercontent.com/723651/226121867-ca964554-3888-45a8-af72-a5f73597e61f.jpg)
</p>
</details>

**Comment by tophf** [comment]
We've fixed it in c18b2df4.

**Comment by darkred** [comment]
I noticed that the action [v2.15.3](https://github.com/violentmonkey/violentmonkey/actions/runs/5917827787) of 5 days ago for publishing v2.15.3 to AMO and CWS failed with 2 errors. 
I quote:
<details>
<summary>Error in <code>Publish to AMO</code>:</summary>

[relevant workflow step](https://github.com/violentmonkey/violentmonkey/actions/runs/5917827787/job/16046551929#step:6:50)

```
Run mkdir -p $TEMP_DIR/updates
Publish unlisted version
Error: Not processed yet
    at file:///home/runner/work/violentmonkey/violentmonkey/node_modules/amo-upload/dist/index.mjs:87:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async poll (file:///home/runner/work/violentmonkey/violentmonkey/node_modules/amo-upload/dist/index.mjs:17:14)
    at async AMOClient.uploadFile (file:///home/runner/work/violentmonkey/violentmonkey/node_modules/amo-upload/dist/index.mjs:85:5)
    at async AMOClient.createVersion (file:///home/runner/work/violentmonkey/violentmonkey/node_modules/amo-upload/dist/index.mjs:94:24)
    at async signAddon (file:///home/runner/work/violentmonkey/violentmonkey/node_modules/amo-upload/dist/index.mjs:265:19)
    at async main (file:///home/runner/work/violentmonkey/violentmonkey/scripts/amo-upload.mjs:32:3)
Error: Process completed with exit code 1.
```
</details>

<details>
<summary>Error in <code>Publish to CWS</code>:</summary>

[relevant workflow step](https://github.com/violentmonkey/violentmonkey/actions/runs/5917827787/job/16046551929#step:8:49)

```
Run set -x
+ '[' true '!=' true ']'
Publish prerelease
+ echo Publish prerelease
+ npx chrome-webstore-upload-cli@1 upload --extension-id opokoaglpekkimldnlggpoagmjegichg --source tmp/Violentmonkey-beta-webext-beta-v2.15.3.zip --auto-publish
npm WARN exec The following package was not found and will be installed: chrome-webstore-upload-cli@1.2.2
Response code 400 (Bad Request)
"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy practices tab.\",\n    \"errors\": [\n      {\n        \"message\": \"Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy practices tab.\",\n        \"domain\": \"chromewebstore.access\",\n        \"reason\": \"badRequest\"\n      }\n    ]\n  }\n}\n"
Error: Process completed with exit code 1.
```
</details>

**Comment by tophf** [comment]
@gera2ld, ping!

**Comment by tophf** [comment]
Also, what about running AMO/CWS jobs from release-helper.js and adding the error to the text of the release?

**Comment by gera2ld** [comment]
Sorry for the late response. I've added the information required in the CWS dashboard (permission justification of the newly added `contextMenus`).

> what about running AMO/CWS jobs from release-helper.js and adding the error to the text of the release?

They were designed to be able to retry even after the release is created. The error message might change on each retry so I don't think it's a good idea to include it in the release notes.
However we can send the error message to our Discord channel or other tools. WDYT? @tophf

**Comment by tophf** [comment]
Any method of indication is good.

**Comment by tophf** [comment]
So, what about beta 3, do I just re-run the job?

**Comment by gera2ld** [comment]
> So, what about beta 3, do I just re-run the job?

Just wait for review

**Comment by tophf** [comment]
And what about AMO beta 3? I don't see it in the dashboard.

**Comment by gera2ld** [comment]
It doesn't look right, let me check.

**Comment by gera2ld** [comment]
The reason why AMO beta 3 was not published is because the AMO validation took more time than expected. A simple retry fixed the issue.
I'll extend the polling time, add more logs, and send release errors to a dedicated Discord channel.
