### ISSUE TITLE
`responseHeaders` are not `ByteString`

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1329]
VM returns headers as `String` while it should be [`ByteString`](https://developer.mozilla.org/en-US/docs/Web/API/ByteString).
In most cases it works transparent, but not for some "Content-Disposition" header (when `filename` has non-ASCII character).

Native `XMLHttpRequest`, `fetch` and `GM.xmlhttpRequest` of TM return the related header string as `ByteString`.

That enchantment (?) may break a code that expect _only_ `ByteString`.

My current workaround (specially only for VM) is to check is it really a `ByteString` object:
```js
function byteStringToString(byteString) {
  const chars = [...byteString];
  const isBinaryString = chars.every(ch => ch.charCodeAt(0) < 256);  
  if (isBinaryString) {
    console.log("isBinaryString", isBinaryString);
    const isASCII = chars.every(ch => ch.charCodeAt(0) < 128);
    if (isASCII) { // not required
      console.log("isASCII", isBinaryString);
      return byteString;
    }
    const bytes = new Uint8Array(chars.map(ch => ch.charCodeAt(0)));
    return new TextDecoder().decode(bytes);
  }
  return byteString;
}
```

I tested it 1-2 months ago, but I don't think that something changed now.

**Comment by tophf** [comment]
Quoting https://developer.mozilla.org/en-US/docs/Web/API/ByteString

>ByteString maps to a String when returned in JavaScript

**Comment by tophf** [comment]
Ah, apparently, the problem is not about the name of the type, for which `String` is the correct representation per the specification, but rather the fact that Violentmonkey doesn't decode headers, which we may consider a bug.

**Comment by AlttiRi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary

**Comment by tophf** [comment]
Yes, we also use binary strings internally.

**Comment by tophf** [comment]
Turns out I misunderstood it yet again.

The actual problem is that Violentmonkey already decodes responseHeaders but it shouldn't.

Since we don't decode headers anywhere I guess the problem is caused by our [code that extracts "forbidden" headers](https://github.com/violentmonkey/violentmonkey/blob/718bafc7fbaa55f15d80135a2d175da182d085b2/src/background/utils/requests.js#L167) so the correct solution is to encode the result to UTF8.

**Comment by AlttiRi** [comment]
I have written the demo site that returns  "Content-Disposition" header via Service Worker, but requests from the background script are not intercepted by Service Worker, so this demo is useless for this issue testing.
https://alttiri.github.io/content-disposition-by-sw/

Also in Chromium it's not possible to set Binary string as a header value due to a bug. So it works correctly only in Frefox.

But it can be used for testing of the native `fetch` and `XMLHttpRequest`.
