### ISSUE TITLE
同步能否增加高级选项

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#133]
现在默认应该是merge，但有时需要覆盖，本地覆盖云端或云端覆盖本地，尤其是第一次同步的时候。

**Comment by ivysrono** [comment]
zip导入的时候跟需要覆盖选项。

**Comment by gera2ld** [comment]
zip导入本来就是覆盖吧？

**Comment by ivysrono** [comment]
zip导入模式可能我弄错了，不好意思。

**Comment by up24** [comment]
如果可以自动同步就更好了，现在还要绑定dropbox。

**Comment by gera2ld** [comment]
@up24 不能直接用chrome同步，因为数据量太大了。
