### ISSUE TITLE
IPADos safari extensions - violentmonkey

### ISSUE THREAD

**Issue by stillhope** [violentmonkey/violentmonkey#1331]
### Environment
- Browser: Safari ipadios 15
- Browser version: 15 public beta 4
- Violentmonkey version:
- OS:
Hello: Are there plans to release violentmonkey safari extension for IPAD os 15?  The new os has support for safari extensions.

**Comment by tophf** [comment]
Even if we convert the extension, there's $99 to pay each year to Apple so I don't think we will bother unless @gera2ld already has an Apple dev account...
