### ISSUE TITLE
`GM_addElement` missing

### ISSUE THREAD

**Issue by SNDST00M** [violentmonkey/violentmonkey#1335]
### What is the problem?

Scripts that use `GM_addElement` are completely broken :(

### How to reproduce it?
1. Install https://raw.githubusercontent.com/SNDST00M/material-dynmap/main/src/user.js
2. Open https://mc.westeroscraft.com
3. Watch the console get lit like a Christmas tree

### What is the expected result?

https://www.tampermonkey.net/documentation.php#GM_addElement

### What is the actual result?

Doesn't work and borks the whole script.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

Identical result, there's been no work in this avenue.

### Environment
- Browser: Edge.
- Browser version: 92.0
- Violentmonkey version: 2.13.0
- OS: Windows 10 Home 20H2

**Comment by tophf** [comment]
I see approximately 20 scripts that use GM_element out of thousands so I'm not convinced we should implement it. Just because Tampermonkey implemented something, doesn't mean it's a good thing. Why don't you use the standard document.createElement + appendChild in your script?

**Comment by SNDST00M** [comment]
Because that requires unsafeWindow which isn't the best idea to me to promote

**Comment by tophf** [comment]
Why exactly do you need unsafeWindow here? Normally it's not needed.

**Comment by SNDST00M** [comment]
That's good, although I still think I should be using \@\grant GM_addElement and that function, so that users know I am injecting elements into the DOM

**Comment by tophf** [comment]
Adding elements to DOM is something scripts are supposed to do and they were doing it for decades. There's no need for a special grant. The only purpose of GM_addElement is to add `script` element on a page with a strict CSP. Until such case is presented to us by an author we won't implement GM_addElement.

**Comment by tophf** [comment]
Ah, actually it makes sense for `style` elements too because some sites forbid them via CSP. However, this is a very bad practice what you're doing. The proper solution is to use `@resource` and then GM_addStyle. I'll keep this issue open for @gera2ld to chime in though.

**Comment by SNDST00M** [comment]
I recently stumbled across https://github.com/Tampermonkey/tampermonkey/issues/881 for the CSP issue.
It's probably why modifying GitHub locally necessitates a custom extension.

**Comment by SNDST00M** [comment]
Btw I confirmed with a dev that the CORS bypass I was doing wasn't necessary.
Thanks for pointing this out!

**Comment by tophf** [comment]
Done.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/4206569336/artifacts/108643418) (don't forget to do an export in Violentmonkey settings).
It properly circumvents CSP on npmjs.com and other such sites.

**Comment by KaKi87** [comment]
Will try ! For now the hack works, although I had to [switch from `https://www.youtube.com/embed/mKMaG0cixXw*` to `https://js.stripe.com/*`](https://git.kaki87.net/KaKi87/userscripts/commit/cda2236f098ad6ec871fb39d90e2963d8daba90e), because the first one has been removed from npmjs.com, I wonder if it's related and how they found out if it was, since I didn't published the userscript anywhere else than my own git repo yet.
