### ISSUE TITLE
点击“安装链接”安装该脚本，无法跳出violentmonkey的安装界面

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1337]
不清楚是否是violentmonkey扩展的bug，网址如下https://timer.palerock.cn，点击
![]I9@1_Z6W7EEFAY89C`P`BX.png](https://user-images.githubusercontent.com/75355896/129195068-dd446138-3992-49a1-b5cf-2855af4a2724.png)
圈出的链接，会显示如图下载的弹窗
![PTHQ~JUDVJ~(5KS6{`QX~XH.png](https://user-images.githubusercontent.com/75355896/129194779-6dac5eb6-8066-4089-a23c-37090497d59e.png)。使用的是vivaldi浏览器（4.1.2369.16 (Stable channel) （64 位），violentmonkey v2.13.0。其他浏览器如edge浏览器没有出现这个问题。

**Comment by tophf** [comment]
I can't reproduce the problem in Vivaldi stable but my version ends on `.10` in Windows, not `.16`. It can be a bug in Vivaldi or a temporary network problem or another installed extension in your browser is interfering.

**Comment by violenttamper** [comment]
> 不清楚是否是violentmonkey扩展的bug，网址如下https://timer.palerock.cn，点击
> ![]I9@1_Z6W7EEFAY89C`P`BX.png](https://user-images.githubusercontent.com/75355896/129194718-9cbf765f-94fc-440a-9992-90b11c75a3d4.png)圈出的链接，会显示如图下载的弹窗
> ![PTHQ~JUDVJ~(5KS6{`QX~XH.png](https://user-images.githubusercontent.com/75355896/129194779-6dac5eb6-8066-4089-a23c-37090497d59e.png)。使用的是vivaldi浏览器（4.1.2369.16 (Stable channel) （64 位），violentmonkey v2.13.0。其他浏览器如edge浏览器没有出现这个问题。

    好的，我去排查下，think you
