### ISSUE TITLE
对 css 的 @-moz-document regexp 生效范围判断不准

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#135]
https://userstyles.org/styles/78857/

@-moz-document regexp("https?://www\\.google\\.(?:com|(?:com?\\.)?[a-z][a-z])/(?!maps(?:$|.*)).*")

以 js 模式安装后，变成全局生效了。

**Comment by gera2ld** [comment]
那个脚本就是这么写的，全局都会加一段注释，只有在特定页面上会加入CSS，没有问题。
