### ISSUE TITLE
Add option to set Icon badge color

### ISSUE THREAD

**Issue by RezqZiyad** [violentmonkey/violentmonkey#1350]
As in TM.
![image](https://user-images.githubusercontent.com/29045522/130675068-48954d5e-8a77-4d4a-a787-cf02c67c09c9.png)
![image](https://user-images.githubusercontent.com/29045522/130675209-e2276954-c579-424b-97d3-a203793f8174.png)

**Comment by tophf** [comment]
We already have such an option, currently in beta.
