### ISSUE TITLE
Cannot sync with Onedrive

### ISSUE THREAD

**Issue by peasoft** [violentmonkey/violentmonkey#1360]
### What is the problem?
I cannot sync with Onedrive.
### How to reproduce it?
1. Open settings page.
2. Choose "Onedrive" at "Sync to"
3. Sync
4. Sync failed

### What is the expected result?
I want to sync with Onedrive.
### What is the actual result?
Sync failed.

### Environment
- Browser: Microsoft Edge
- Browser version: 92.0.902.84
- Violentmonkey version: v2.13.0
- OS: Windows 10

**Comment by tophf** [comment]
1. Try clicking `Revoke` and authorize again.
2. Try opening the [background devtools](https://stackoverflow.com/a/10258029) and see what happens in the network request to onedrive.

**Comment by qwazx** [comment]
![QQ截图20210916025337](https://user-images.githubusercontent.com/45809751/133492624-c16d4fdc-25ce-484e-9abc-95ce2ad31c1d.png)
我看到提示了这个，但我不知道说的是哪个脚本

**Comment by tophf** [comment]
I meant the Network panel:

![image](https://user-images.githubusercontent.com/1310400/133497448-b598d03d-3d99-416e-95b7-71136b28fe60.png)

Open it, then try to sync with OneDrive again, then check the requests in this panel, please.

**Comment by qwazx** [comment]
抱歉我不是很懂需要怎么弄，是需要这个吗？Sorry I don’t know how to do it,is this it?
![QQ截图20210916211007](https://user-images.githubusercontent.com/45809751/133618101-1029d90c-5b76-4fe5-af84-ec9926c4bb29.png)

**Comment by peasoft** [comment]
OK. Now it can sync well.
