### ISSUE TITLE
Faster `buf2binstr`

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1366]
VM uses it:
https://github.com/violentmonkey/violentmonkey/blob/62b3259f266032cb1ebb3e66c3c700ae228aaeea/src/common/util.js#L82-L92

---

I was looking through Pako repo's issues and found this one: https://github.com/nodeca/pako/issues/229

After checking I found that Pako's [`buf2binstring`](https://github.com/nodeca/pako/blob/26dff4fb3472c5532b3bd8856421146d35ab7592/dist/pako.es5.js#L4027-L4044) works notable faster (by 30-40 %) than VM's function.

Checked here https://jsben.ch/ and here https://jsbench.me/.

Use that code:
```js
let STR_APPLY_UIA_OK = true;
try { String.fromCharCode.apply(null, new Uint8Array(1)); } catch (__) { STR_APPLY_UIA_OK = false; }
let buf2binstring = (buf, len) => {
  // On Chrome, the arguments in a function call that are allowed is `65534`.
  // If the length of the buffer is smaller than that, we can use this optimization,
  // otherwise we will take a slower path.
  if (len < 65534) {
    if (buf.subarray && STR_APPLY_UIA_OK) {
      return String.fromCharCode.apply(null, buf.length === len ? buf : buf.subarray(0, len));
    }
  }

  let result = '';
  for (let i = 0; i < len; i++) {
    result += String.fromCharCode(buf[i]);
  }
  return result;
};


function buffer2string(buf, offset = 0, length = 1e99) {
    // The max number of arguments varies between JS engines but it's >32k so we're safe
    const sliceSize = 8192;
    const slices = [];
    const end = Math.min(buf.byteLength, offset + length);
    for (; offset < end; offset += sliceSize) {
        slices.push(String.fromCharCode.apply(null,
            new Uint8Array(buf, offset, Math.min(sliceSize, end - offset))));
    }
    return slices.join('');
}

function arrayBufferToBinaryString(arrayBuffer) {
    return arrayBuffer.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
} 

let ui8a = new Uint8Array(96*1024); // try different sizes
for (let i = 0; i < ui8a.length; i++) {
    ui8a[i] = Math.trunc(Math.random()*256);
}

```

```js
buf2binstring(ui8a, ui8a.length); // Pako
```
```js
buffer2string(ui8a); // VM
```
```js
arrayBufferToBinaryString(ui8a); // My one, works even with 50 MB (50*1024*1024)
```

----

```js
arrayBufferToBinaryString(ui8a) === buffer2string(ui8a) && 
arrayBufferToBinaryString(ui8a) === buf2binstring(ui8a, ui8a.length)
// true
```

**Comment by tophf** [comment]
1. Pako's code assumes that JavaScript engine's stack is capable to pass 65534 elements, which is an unsafe assumption.
2. Pako's code concatenates the string in a loop, which stresses the Garbage Collector, AFAIK.
3. VM uses this function only to encode webRequest headers which are very short by definition so the difference would be microseconds, which is totally negligible.

**Comment by AlttiRi** [comment]
Wait, your code is fine, but only if you pass `ArrayBuffer`, not `Uint8Array` as `buf` argument.

The third parameter of `Uint8Array`  constructor must be exactrly `ArrayBuffer`, not `Uint8Array`, in other case it will be ignored. 

And, as GitHub shows me, you always pass to `buffer2string` `Uint8Array` from `TextEncore.encode`. 
That's bad. It works 10 times slower!

```js
function buffer2string(buf, offset = 0, length = 1e99) {
    const sliceSize = 8192;
    const slices = [];
    const end = Math.min(buf.byteLength, offset + length);
    for (; offset < end; offset += sliceSize) {
        slices.push(String.fromCharCode.apply(null,
            new Uint8Array(buf, offset, Math.min(sliceSize, end - offset))));
    }
    return slices.join("");
}

let ui8a = new Uint8Array(50 * 1024);
for (let i = 0; i < ui8a.length; i++) {
    ui8a[i] = Math.trunc(Math.random() * 256);
}

console.time("Uint8Array");
buffer2string(ui8a);
console.timeEnd("Uint8Array");

console.time("ArrayBuffer");
buffer2string(ui8a.buffer);
console.timeEnd("ArrayBuffer");
```

- Uint8Array: 4.15625 ms
- ArrayBuffer: 0.434814453125 ms

Also it will work with the large data due to the correct slicing.

**Comment by tophf** [comment]
That's because your output string is 10 times longer for uint8array. Anyway, I'm not interested in optimizing this because as I already explained we only encode headers in this function, so the data is very short, which means that invocation of the function might constitute the bulk of the time spent on encoding and not the encoding itself.

**Comment by tophf** [comment]
I've added native toBase64() in modern browsers a61ebdc804d4a0568933c4d6ace1412fe67603ee and fixed the buffer/array bug which we didn't actually hit because this function is only used on short strings.
