### ISSUE TITLE
[Google's Problem]谷歌商店地址的中文出问题

### ISSUE THREAD

**Issue by SekiBetu** [violentmonkey/violentmonkey#1368]
![image](https://user-images.githubusercontent.com/38283893/133404851-ba02385f-d13d-4afe-9d4b-2da03a638133.png)
![image](https://user-images.githubusercontent.com/38283893/133404976-68067b21-6d19-425b-bd67-fdc63af1262c.png)
![image](https://user-images.githubusercontent.com/38283893/133404990-f423c0cd-eb94-4542-8946-0dc89223836b.png)
![image](https://user-images.githubusercontent.com/38283893/133405003-fe47fb95-bb1a-4f74-a1ad-f696c3e75352.png)
![image](https://user-images.githubusercontent.com/38283893/133405017-ea35fd83-33cf-47d5-8496-eec212102bb6.png)

**Comment by SekiBetu** [comment]
violent-monkey字段会被转成暴力猴，然后就炸了，改成了empty-title才能进去

**Comment by SekiBetu** [comment]
就先开个issue在这，静观其变，似乎受影响的是全体的带中文标题的插件

**Comment by tophf** [comment]
Looks like a problem in the web store or in Chrome, not related to Violentmonkey's code.
