### ISSUE TITLE
同步到OneDrive提示同步出错

### ISSUE THREAD

**Issue by qwazx** [violentmonkey/violentmonkey#1369]
### What is the problem?
OneDrive同步报错，每次都同步到最后一个提示出错，尝试过重装插件，授权OneDrive等等，依旧无法解决。

但是增加了脚本之后，可以在OneDrive同步到的新脚本。

### How to reproduce it?
1.尝试同步百分百报错

### Environment
- Browser:Vivaldi
- Browser version:4.2.2406.40
- Violentmonkey version:暴力猴v2.13.0
- OS:win10

**Comment by tophf** [comment]
Sounds like #1360.

1. Try clicking `Revoke` and authorize again.
2. Try opening the [background devtools](https://stackoverflow.com/a/10258029) and see what happens in the network request to onedrive.

**Comment by boehs** [comment]
Can this be safely closed as @qwazx hasn't responded for well over a year?
