### ISSUE TITLE
replacing Function.prototype.call can break violentmonkey

### ISSUE THREAD

**Issue by xBZZZZ** [violentmonkey/violentmonkey#1373]
### What is the problem?
replacing `Function.prototype.call` can break violentmonkey if there is `// @run-at document-end` or `// @run-at document-idle` userscript that runs on the webpage

### How to reproduce it?
1. install userscript like:
```javascript
// ==UserScript==
// @name        useless script
// @namespace   http://bzzzzdzzzz.blogspot.com/
// @description does nothing
// @author      BZZZZ
// @include     *
// @version     0.1
// @grant       none
// @run-at      document-end
// ==/UserScript==

undefined;
```
2. save this as html file:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>violentmonkey bug demo</title>
  <script type="text/javascript">
    Function.prototype.call=function(cthis,...cargs){
      console.log('Function.prototype.call:\n\tfunction:%O\n\tthis:%O\n\targuments:%O\n\t%O',this,cthis,cargs,Error('dummy error to show call stack'));
      document.write('<h1>open javascript console</h1>');
      return Reflect.apply(this,cthis,cargs);
    };
  </script>
</head>
<body>
</body>
</html>
```
and open with browser with violentmonkey (works on firefox and brave)
3. if webpage shows "**open javascript console**" you reproduced the bug
4. open javascript console
you will see `Function.prototype.call` logs but nothing in webpage and userscript calls ` Function.prototype.call`

for developer: to fix this do
```javascript
const fcall=Function.prototype.call.bind(Function.prototype.call);
```
before webpage script can replace any native functions and use
```javascript
fcall(func,thisArg,...args);
```
instead of
```javascript
func.call(thisArg,...args);
```
in `injected-web.js`

### Environment
- Violentmonkey version: Violentmonkey v2.13.0

**Comment by tophf** [comment]
Yes, I know it is possible, but I don't see any valid purpose for a site to do it other than a pointless exercise.

**Comment by tophf** [comment]
OTOH, it'd be nice to fix to make Violentmonkey more secure...

**Comment by xBZZZZ** [comment]
webpage can also leak userscript source code

**Comment by xBZZZZ** [comment]
also `injected-web.js` uses [`Object()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object) a lot (sometimes for no reason) and webpage can replace `window.Object`

**Comment by tophf** [comment]
`Object` is used by webpack. It'll be also fixed by the linked PR.

**Comment by tophf** [comment]
Would you test the PR before I merge it? Here it is: [dist.zip](https://github.com/violentmonkey/violentmonkey/files/7230221/dist.zip)

**Comment by xBZZZZ** [comment]
> Would you test the PR before I merge it? Here it is: [dist.zip](https://github.com/violentmonkey/violentmonkey/files/7230221/dist.zip)

fixed (scripts work and no `Object` and `Function.prototype.call` calls)
