### ISSUE TITLE
Aborting xmlhttpRequest does nothing

### ISSUE THREAD

**Issue by melusc** [violentmonkey/violentmonkey#1375]
### What is the problem?

`GM_xmlhttpRequest(...).abort()` / `GM.xmlHttpRequest(...).abort()` does nothing

### How to reproduce it?
1. Run either script below on any page
1. Check console to see which function was called

```js
// ==UserScript==
// @name        GM_xmlhttpRequest abort
// @match       *://*/*
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
	url: location.href,
	onabort: console.log.bind(console, 'onabort'),
	onload: console.log.bind(console, 'onload'),
}).abort();
```

```js
// ==UserScript==
// @name        GM.xmlHttpRequest abort
// @match       *://*/*
// @grant       GM.xmlHttpRequest
// ==/UserScript==

GM.xmlHttpRequest({
	url: location.href,
	onabort: console.log.bind(console, 'onabort'),
	onload: console.log.bind(console, 'onload'),
}).abort();
```

### What is the expected result?

It should log onabort and the responseObject.

### What is the actual result?

It logs onload and the responseObject.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

The same result.

### Environment
- Browser: Firefox
- Browser version: 93.0b9
- Violentmonkey version: 2.13.0
- OS: W10

**Comment by tophf** [comment]
Until the new fixed version is released you'll have to delay aborting the request:
```js
let aborted;
const req = GM_xmlhttpRequest({
  onabort: () => { aborted = true; },
});
let timer = setInterval(() => aborted ? clearInterval(timer) : req.abort(), 1);
```

**Comment by AlttiRi** [comment]
It looks to be working:
```js
if (signal.aborted) {
    gmAbort();
    setTimeout(gmAbort, 0); // VM fix.
    return;
}
```
Or I should use `setInterval` approach?
