### ISSUE TITLE
Scripts not working on PWAs

### ISSUE THREAD

**Issue by aayushbhatia06** [violentmonkey/violentmonkey#1377]
### What is the problem?
I am currently running a script to make the titlebars of all PWAs black - https://greasyfork.org/en/scripts/390566-pwa-dark-titlebar
This script works in both Greasemonkey and MeddleMonkey perfectly but does not do anything in ViolentMonkey

### How to reproduce it?
1. Installed the said script
2. ......
3. Does nothing!

### What is the expected result?
Should turn the titlebars black

### What is the actual result?
Nothing happens

### Environment
- Browser: Edge Chromium 
- Browser version: 94.0.992.3
- Violentmonkey version: 2.13.0
- OS: Windows 11

**Comment by tophf** [comment]
Your script incorrectly assumes that `head` element is present at `document-start`. There's no such guarantee per the specification. Here's the correct code:
```js
(document.head || document.documentElement).prepend(meta);
```

Your script works in Greasemonkey and MeddleMonkey because their implementation of `document-start` is much slower than Violentmonkey's.
