### ISSUE TITLE
`GM_openInTab` cannot open non-http pages or URI

### ISSUE THREAD

**Issue by dnknn** [violentmonkey/violentmonkey#1382]
```js
	// E.g 
GM_openInTab(`chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options/index.html` ,false);
```

- Current behavior (or bug?):
	It open as: `http://jinjaccalgkegednnccohejagnlnfdag/options/index.html`

- Expected behavior: Just like Tampermonkey
	Tampermonkey can normally open the expected non-http protocol `URI` .
	That is: the extension does not actively `.replace(... ,'http')` the user's protocol header

---------------------------------------------------------------------

<details><summary> code </summary>

```js
// ==UserScript==
// @name		GMopen_non-http
// @match		*://*/*
// @grant		GM_openInTab
// ==/UserScript==
'use strict';
addEventListener(`keydown`,e=>	{
	const key=e.key.length===1?e.key.toLowerCase():e.key;

	let URL = `chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options/index.html`;
		URL = `or other`

	key===`F2` && GM_openInTab(URL ,false);

});
```

</details>

**Comment by tophf** [comment]
We can allow opening any protocol except own pages of Violentmonkey.
