### ISSUE TITLE
Scrolling in the Violentmonkey editor is very slow

### ISSUE THREAD

**Issue by akiirui** [violentmonkey/violentmonkey#1383]
### What is the problem?

Scrolling in the Violentmonkey editor is very slow.

### How to reproduce it?
1. Open the violentmonkey options, add a new script
2. Press ENTER in the editor until the scroll bar is displayed
3. Use the mouse to scroll in the editor

### What is the expected result?

Scrolling speed is the same as everywhere else.

### What is the actual result?

Scrolling speed is very slow.

https://user-images.githubusercontent.com/3736910/135746752-3650cf60-1f01-462d-a1ad-e88c22659c82.mp4

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

The BETA v2.13.0.6 result is same as v2.13.0

### Environment
- Browser: Google Chrome
- Browser version: 94.0.4606.61
- Violentmonkey version: v2.13.0
- OS: Windows 10 21H1

**Comment by tophf** [comment]
This is a bug in Chrome 94. Try the [new beta v2.13.0.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.7), it should fix the bug.

@gera2ld, AMO timed out again so apparently it's because they don't work on weekends 😭 please copy the xpi manually when it appears tomorrow(?).

**Comment by tophf** [comment]
Chrome has fixed their bug in 94.0.4606.71. You can force an update by opening `chrome://settings/help`.

**Comment by akiirui** [comment]
> Chrome has fixed their bug in 94.0.4606.71. You can force an update by opening `chrome://settings/help`.

Oh, thanks for reminding, I will try to upgrade chrome to the latest version.
