### ISSUE TITLE
容易点错的设置

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#139]
![snipaste_20170615_155658](https://user-images.githubusercontent.com/2649544/27171196-4ef68bd4-51e3-11e7-8e0f-80b676e315c6.png)

一下拉就会出现如图的问题，全局设置和单个脚本设置合在一起，很容易误操作。
不如把全局的三个选项按钮移到右边，和“获取更多脚本”对调。

**Comment by ivysrono** [comment]
才发现 2.7.1 已经没有这个问题了，全怪 AMO 审核太慢。

**Comment by gera2ld** [comment]
其实没有完全解决，后面我准备把顶上的按钮再调大一点

**Comment by ivysrono** [comment]
现在已经可以了，不急的。
急的是CSP不解决，还得装TM
没有WebDav，同步总是大麻烦——TM的同步就是坨翔，同步党全指望VM了。
