### ISSUE TITLE
All scripts deleted after testing beta 2.13.0.7

### ISSUE THREAD

**Issue by Luke-Baker** [violentmonkey/violentmonkey#1391]
### What is the problem?
Tried to report a bug. The form asks to test the upcoming release. Now all my scripts are gone. The recycle bin is empty. The relevant _%AppData%\Mozilla\Firefox\Profiles\<profile follder>\browser-extension-data_ folder is empty. A deep scan with Recuva yielded nothing. I had a million other things to worry about, so I didn't have a backup. Is there any way to get my scripts back?

### How to reproduce it?
1. Disable Violentmonkey 2.13.0 in about:addons
2. Install Violentmonkey 2.13.0.7 in about:debugging. It's an unsigned ZIP, so it's only possible to install it temporarily this way.
3. All my scripts were fine at this stage, but the bug I wanted to report was still reproducible, so I removed Violentmonkey 2.13.0.7 from about:debugging.
4. Re-enable Violentmonkey 2.13.0 in about:addons.

### What is the expected result?
My entire scripts database isn't wiped.

### What is the actual result?
My entire scripts database was wiped.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
There are still no scripts if I retrace my steps above to install the latest beta.

Browser Console output:
`10:26:41.874 sendRemoveListener on closed conduit {aecec67f-0d10-4fa7-b7c7-609a2db280cf}.274877907376 ConduitsChild.jsm:108
10:26:43.123 1633764403123	addons.webextension.{aecec67f-0d10-4fa7-b7c7-609a2db280cf}	WARN	Loading extension '{aecec67f-0d10-4fa7-b7c7-609a2db280cf}': Reading manifest: Warning processing permissions: Error processing permissions.9: Value "declarativeContent" must either: must either [must either [must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["geckoProfiler"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["networkStatus"], be one of ["telemetry"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
10:26:43.124 1633764403124	addons.webextension.{aecec67f-0d10-4fa7-b7c7-609a2db280cf}	WARN	Loading extension '{aecec67f-0d10-4fa7-b7c7-609a2db280cf}': Reading manifest: Warning processing options_page: An unexpected property was found in the WebExtension manifest.
10:26:43.139 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:5003
10:26:44.540 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. popup-fenix.html
10:26:44.843 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. index.html
10:26:45.272 browser.ui.interaction.pinned_overflow-menu - Unknown scalar.
`

### Environment
- Browser: Firefox
- Browser version: 93.0
- Violentmonkey version: 2.13.0
- OS: Windows 10 64-bit

**Comment by tophf** [comment]
This is a bug in Firefox or rather a bad implementation of the temporary extension installation. I'm not aware of a way to restore the database. FWIW I've learnt this lesson ~20 years ago and since then I use a daily automatic backup of my entire system partition.

**Comment by tophf** [comment]
Maybe [this](https://github.com/openstyles/stylus/issues/1094) investigation can help you.

**Comment by Luke-Baker** [comment]
Thank you, but that's beyond my comprehension level. I'd looked under `<Firefox profile folder>\storage\default` prior to your reply and I couldn't find the relevant extension folder in there.
