### ISSUE TITLE
GM_download cannot generate folder

### ISSUE THREAD

**Issue by qinxs** [violentmonkey/violentmonkey#1393]
### What is the problem?
GM_download cannot generate folder

It should be a mistake to replace the `/` symbol with `_`
In the browser API `chrome.downloads.download`, when the parameter file is `AA/abc.jpg`, an `AA` folder will be generated 

### How to reproduce it?
```js
// ==UserScript==
// @name          GM_download Test
// @namespace     https://github.com/qinxs
// @author        qinxs
// @version       1.0.0
// @description   GM_download cannot generate folder
// @include       http*
// @run-at        document-start
// @grant         GM_download
// ==/UserScript==

'use strict';

GM_download({
  url: 'https://cdn.jsdelivr.net/gh/qinxs/cdn-assets@master/img/md/b04c6f46/workmodel.png',
  name: 'md/workmodel.png',
  saveAs: false,
});
```

### What is the expected result?
Generate the folder `md`, and the picture 'workmodel.png' is stored in the `md` folder 

### What is the actual result?
The file `md_workmodel.png` is generated 

### Environment
- Browser: Firefox & Chrome
- Browser version: 78.15esr & 90.0.4430.93（正式版本） （64 位）
- Violentmonkey version: 暴力猴 v2.13.0
- OS: Win 7（x64）

**Comment by tophf** [comment]
Currently Violentmonkey uses the standard browser functionality for downloads that doesn't support paths.
There's an existing issue #1349 about this, which will be implemented someday in the future.

**Comment by milkliker** [comment]
@tophf I could help to implement this by using native chrome.downloads, and I'm wondering where (the file, I mean) to put this code in, in order to not break your architecture design.

To make a quick patch, I would put the code in src/background/utils/request.js
In the func named HttpRequest,
```javascript
if (chrome && isDownloadReq(opts)) {
  return chrome.downloads.download({
    url: opts.url,
    filename: opts.fileName,
  }, downloadId => {
    requests[id] = { id, downloadId, tabId, eventsToNotify, xhr: null };
    downloads[downloadId] = { req: requests[id], opts, src };
    if (eventsToNotify?.includes('progress')) {
      sendTabCmd(tabId, 'HttpRequested', { type: 'progress', id, downloadId }, { frameId });
    }
  });
}
```
and also in abort:
```javascript
AbortRequest(id) {
  const req = requests[id];
  if (req) {
    // eslint-disable-next-line no-undef
    if (chrome) {
      // eslint-disable-next-line no-undef
      chrome.downloads.cancel(req.id);
      delete requests[req.id];
    } else {
      req.xhr.abort();
      clearRequest(req);
    }
  }
},
```
add update listener
```javascript
if (chrome) {
  chrome.downloads.onChanged.addListener(evt => {
    console.info('onChanged', evt);
    if (!downloads[evt.id]) return;
    const { req, src } = downloads[evt.id];
    const { tab: { id: tabId }, frameId } = src;

    if (evt.state?.current === 'complete') {
      sendTabCmd(tabId, 'HttpRequested', {
        type: 'load', id: req.id, downloadId: evt.id,
      }, { frameId });
    } else if (evt.state?.current === 'interrupted') {
      sendTabCmd(tabId, 'HttpRequested', {
        type: 'error', id: req.id, downloadId: evt.id,
      }, { frameId });
    } else {
      return;
    }
    delete downloads[evt.id];
    delete requests[req.id];
  });
}
```

But I feel not good to do like this, it's kind of very dirty code implement.
Pls let me know, if you have any advise.

**Comment by tophf** [comment]
This feature should be surfaced as an option in our settings page.

It should use [optional permission](https://developer.chrome.com/extensions/permissions) to enable the downloads API and if the permission is not granted then the option should change back to the default.

The onChanged listener should be added dynamically, when needed, and removed when done.

**Comment by milkliker** [comment]
Yes, and any advise where to put the code in ?
Or do you have any spec plan to add this? 

Thanks @tophf ! 
> This feature should be surfaced as an option in our settings page.
> 
> It should use [optional permission](https://developer.chrome.com/extensions/permissions) to enable the downloads API and if the permission is not granted then the option should change back to the default.
> 
> The onChanged listener should be added dynamically, when needed, and removed when done.

**Comment by tophf** [comment]
The code that deals with requests should be in the `request.js`. The code that shows the option should be in the file that contains the options, probably inside `Advanced`.

**Comment by milkliker** [comment]
got~ thanks!
I will add these and create pull request later..
