### ISSUE TITLE
Sync doesn't sync with script data

### ISSUE THREAD

**Issue by Cyberavater** [violentmonkey/violentmonkey#1397]
So, I had a huge collection of blocked sites for [Google Hit Hider](https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites) with sync I expected that the data would be on all of my browsers but it isn't.

Only if I use export and import (with data) I can have the data in the new browser. Please add include data for sync as well. Thanks!

**Comment by tophf** [comment]
Sounds like #48.
