### ISSUE TITLE
Scripts are not loaded for new tab images

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1402]
### What is the problem?

"Open Image in New Tab"  in FireFox does not load any scripts

### How to reproduce it?
1. For test purposes create a script that just says alert("Testing") and it runs on any jpg images
2. From a site right click on an image and then select ""Open Image in new Tab"
3. Tab is then loaded in the background without any scripts running

If you refresh the page the scripts listings are loaded and the script is run.

### What is the expected result?

To get an alert message

### What is the actual result?

The script does not run

### Environment
- Browser: FireFox
- Browser version: 93
- Violentmonkey version: 2.13.0
- OS: Windows 10

**Comment by TimidScript** [comment]
You are right. I just tried it on a different profile and it worked. Something must be broken on my main profile.

**Comment by tophf** [comment]
See if the [most recent VM beta](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.9) works in the main profile. Don't forget to perform an export in VM settings.
