### ISSUE TITLE
[BUG] `GM.getResourceURL` should be `GM.getResourceUrl`

### ISSUE THREAD

**Issue by Yash-Singh1** [violentmonkey/violentmonkey#1403]
GreaseMonkey internally uses `GM.getResourceUrl` not `GM.getResourceURL`, but ViolentMonkey expects `getResourceURL` with the `r` and the `l` is capitalized.

**Comment by tophf** [comment]
Test build: https://github.com/violentmonkey/violentmonkey/suites/4092754685/artifacts/104293469
Don't forget to click `Export to zip` in Violentmonkey settings.

**Comment by Yash-Singh1** [comment]
For compatability with older ViolentMonkey userscripts, should `GM.getResourceUrl` **AND** `GM.getResourceURL` be supported?
