### ISSUE TITLE
 脚本命名空间冲突，请修改@name和@namespace！（Script namespace conflict, please modify @ name and @ namespace）

### ISSUE THREAD

**Issue by af199901** [violentmonkey/violentmonkey#1408]
在 百度 添加脚本的时候，会提示这错误，请问怎么解决呢？（This error will be prompted when adding a script at www.baidu.com. How can I solve it？）

**Comment by tophf** [comment]
It means you already have a script in Violentmonkey that has the same `@name` and `@namespace`. If you're trying to update an existing script, then open it in the list of scripts and overwrite with the new code. Otherwise, change `@name` or `@namespace` to something unique.

**Comment by tophf** [comment]
That script may also be inside the Recycle Bin so you can restore it, then edit it and overwrite with the new code.
