### ISSUE TITLE
Export/Import selected script data and nothing else

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1413]
Ability to export/import selected script saved data (values). Just the saved values and not the script itself.

**Comment by tophf** [comment]
The feature is now easier to discover:

![image](https://user-images.githubusercontent.com/1310400/139945355-968b6713-3af9-497f-bf23-1abace2c2696.png)
And the contents of the storage is shown automatically when opening Values for the first time in this editor.

If you meant the import/export in VM settings, then I don't see it in Tampermonkey, which implements lots options that I deem meaningless but some people may use them, so the absence of a feature there is a strong indication that it's not generally useful. You can just delete all .js files in the zip either manually or write an external script to do it.
