### ISSUE TITLE
脚本数据无法导出

### ISSUE THREAD

**Issue by LvjiangKYI** [violentmonkey/violentmonkey#1416]
在设置里点击"导出为zip文件"无反应。已使用火狐，谷歌浏览器测试，均无法解决。目前使用Google Drive云备份

**Comment by tophf** [comment]
What is the version of Violentmonkey? Browser version? Does it work in a new browser profile or in another user profile?

**Comment by LvjiangKYI** [comment]
> What is the version of Violentmonkey? Browser version? Does it work in a new browser profile or in another user profile?

The version of Violentmonkey should be the latest, because I installed it directly from the extension store. The version of Firefox browser is Version 93.0, and the version of Google Chrome is 95.0.4638.54. What do you mean by "Does it work in a new browser profile or in another user profile?"

**Comment by LvjiangKYI** [comment]
> What is the version of Violentmonkey? Browser version? Does it work in a new browser profile or in another user profile?

**Comment by LvjiangKYI** [comment]
> What is the version of Violentmonkey? Browser version? Does it work in a new browser profile or in another user profile?


https://user-images.githubusercontent.com/57767487/139529789-8d3e23b3-298f-487c-96be-3c6851a5ed64.mp4

**Comment by LvjiangKYI** [comment]
> What is the version of Violentmonkey? Browser version? Does it work in a new browser profile or in another user profile?


https://user-images.githubusercontent.com/57767487/139529898-6dde5b70-3a05-4be4-bbc9-241db655dfc2.mp4

**Comment by tophf** [comment]
Since the export works for me and other people, let's try to guess what might be wrong.

1. Maybe you don't have any scripts so there's nothing to export?
2. Open devtools console by pressing Ctrl-Shift-J or F12 key after pressing the export button and see if there are any messages/errors.
3. Check your default directory for downloads - maybe the file is created there silently.
4. Try the [beta version](https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg) - add a new script there and try to export.

**Comment by LvjiangKYI** [comment]
> Since the export works for me and other people, let's try to guess what might be wrong.
> 
> 1. Maybe you don't have any scripts so there's nothing to export?
> 2. Open devtools console by pressing Ctrl-Shift-J or F12 key after pressing the export button and see if there are any messages/errors.
> 3. Check your default directory for downloads - maybe the file is created there silently.
> 4. Try the [beta version](https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg) - add a new script there and try to export.
> 
> Here's the profile thing: ![profile](https://camo.githubusercontent.com/3134514fa90d2c648dcf4357f032f178a531449031b8ba539b13d2bdf9d64afd/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f4950385a716d666b5f2d4c68314277596338616876497265515a41516757564573627930595164616a42434b50676e426331313452455737544a39532d5f6c5845504d3d77373230)

I have installed about 60 scripts, and I will take out 4 as a demonstration below. It can be found that after deleting this script, the rest can be exported smoothly.

https://user-images.githubusercontent.com/57767487/139556121-5ad451f3-a83b-4efb-9d60-85dd238fd6f0.mp4

After installing the beta version, I tried to sync with Google Drive, but the following 401 error occurred.
![2021](https://user-images.githubusercontent.com/57767487/139556153-587cccd5-12c0-4f68-932a-d32a0d30a5ad.png)

**Comment by tophf** [comment]
1. The export problem is already fixed in beta.
2. The above sync problem in beta is something @gera2ld knows - can you register its id? If not, we should probably add a note somewhere on the site about beta not supporting cloud sync.
