### ISSUE TITLE
adding from URL not working in FF 54 on Linux

### ISSUE THREAD

**Issue by leedoyle** [violentmonkey/violentmonkey#142]
The only way I can add a script on Firefox 54 is to create a new empty script and then copy paste the code. URL importing doesn't work, gives this error
>Oops, you haven't got any script yet.
>{ "url": "https://greasyfork.org/scripts/1317-download-youtube-videos-as-mp4/code/Download%20YouTube%20Videos%20as%20MP4.user.js", "data": "" }

**Comment by gera2ld** [comment]
Which version of Violentmonkey are you using? Where did you get the error? Can you provide a reproduction?

**Comment by leedoyle** [comment]
@gera2ld 2.6.3 Firefox 54 Linux build.

Okay. Open dashboard. Click on "get more scripts button". Select any script and copy it's URL like the one I quoted above. Navigate to dashboard. Click on "install from URL". Paste the link and click OK.

**Comment by gera2ld** [comment]
should have been fixed in [v2.6.4](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.6.4)

**Comment by gera2ld** [comment]
v2.6.4 is released as [self-signed](https://developer.mozilla.org/en-US/Add-ons/Distribution#Self-distributed_(unlisted)_versions), so it will not be listed on AMO.
The review can take relatively long time, so it's likely that the self-signed version to be released more often.
