### ISSUE TITLE
In script installation page, the code area is unthemed (dark theme)

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1420]
In script installation page, the code area is unthemed when dark theme is enabled on Windows OS. 
Here are screenshots:

<details>
<summary>VM 2.13.0.10/11</summary>

![2021-11-07_133929](https://user-images.githubusercontent.com/723651/140643363-04bd40f1-23c2-43fa-a830-5aba0c704e71.jpg)
</details>

<details>
<summary>VM 2.13.0.9</summary>

![2021-11-07_132105](https://user-images.githubusercontent.com/723651/140643335-f73d3d6f-c0c6-4462-bf4c-253e11b19115.jpg)
</details>

Violentmonkey is in its default settings (and, Settings | Advanced | UI theme | `automatic` )

Tested VM 2.13.0.9/10/11 beta in Chrome 95 fresh profile, win11.

*There's no latest Firefox beta version to test, the last self-signed beta release in the repo is [2.13.0.6](https://github.com/violentmonkey/violentmonkey/releases/download/v2.13.0.6/violentmonkey-2.13.0.6-an+fx.xpi), which is themed ok (tested in Firefox 95 beta3).*

Thank you

**Comment by tophf** [comment]
Until a fixed version is released you can set the dark theme explicitly:
![](https://user-images.githubusercontent.com/1310400/137583578-1c190317-2796-4f2a-9c1e-8449bacd1f65.png)

**Comment by darkred** [comment]
Thank you for the super quick response.
I tried setting dark theme explicitly, but it doesn't fix the issue:
<details>
<summary>screen capture:</summary>

![Animation99~~](https://user-images.githubusercontent.com/723651/140648092-1ae21e42-d671-4c92-9f7e-2884f47a6041.gif)
</details>

**Comment by tophf** [comment]
Indeed.
