### ISSUE TITLE
potential bugs in `/src/injected/web/util-web.js`

### ISSUE THREAD

**Issue by xBZZZZ** [violentmonkey/violentmonkey#1421]
- [`Number.prototype.toString` and `window.isFinite` can be replaced](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L5)
- [`isArray` is broken](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L11) (`isArray({splice:()=>{},length:0})` returns `true`, web page can `delete Array.prototype.splice`)
- [`escMap` inherits from `Object.prototype`](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L15) (web page can `Object.prototype['\u0000']='fake escape'`)
- [web page can `open('/').Object.prototype.__defineGetter__('defineAs',()=>alert('???'));`](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L113) (maybe that's intended)
---
fix (doesn't fix [`isArray`](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L11) and [`defineAs`](https://github.com/violentmonkey/violentmonkey/blob/e278cfc7c130d63e3b7325d4f3bb78dc30016277/src/injected/web/util-web.js#L113)):
<ul><li>replace

```javascript
const { isFinite } = global; // eslint-disable-line no-restricted-properties
const { toString: numberToString } = 0;
```
with
```javascript
const isFinite=(()=>{
  'use strict';//need to be strict mode because (function(){isFinite({toString:function(){alert(arguments.callee.caller)}})})() alerts null
  var inf=1/0,ninf=-inf;
  return x=>(x=+x)==x&&inf!=x&&ninf!=x;
})();
```
</li><li>replace

```javascript
const escMap = {
  '"': '\\"',
  '\\': '\\\\',
  '\b': '\\b',
  '\f': '\\f',
  '\n': '\\n',
  '\r': '\\r',
  '\t': '\\t',
};
const escRE = /[\\"\u0000-\u001F\u2028\u2029]/g; // eslint-disable-line no-control-regex
const escFunc = m => escMap[m] || `\\u${(m::charCodeAt(0) + 0x10000)::numberToString(16)::slice(1)}`;
```
with
```javascript
const jsStrEsc=s=>{
  var c,l=s.length,i=0,hex='0123456789ABCDEF',out='"';
  while(l>i)switch(c=s[i++]){
    case '"':out+='\\"';continue;
    case '\\':out+='\\\\';continue;
    case '\b':out+='\\b';continue;
    case '\f':out+='\\f';continue;
    case '\n':out+='\\n';continue;
    case '\r':out+='\\r';continue;
    case '\t':out+='\\t';continue;
    case '\u2028':out+='\\u2028';continue;
    case '\u2029':out+='\\u2029';continue;
    default:
      if('\u001F'<c){
        out+=c;
        continue;
      }
      c=c::charCodeAt(0);//String.prototype.charCodeAt can be replaced
      out+='\\u00'+
        hex[c>>4]+
        hex[15&c];
  }
  return out+'"';
};
```
</li><li>replace

```javascript
    res = `"${value::replace(escRE, escFunc)}"`;
```
with
```javascript
    res = jsStrEsc(value);
```
</li></ul>

**Comment by tophf** [comment]
> Number.prototype.toString and window.isFinite can be replaced

I thought about reimplementing many of the built-in functions but then decided against it because it didn't provide any benefits.

> isArray

Yeah, just like Array.isArray was broken on other pages, but it's hard to improve detection because JavaScript doesn't expose its [internal flag](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#array-exotic-object) for arrays. I guess we can check `length` for being **own** property and add a few more checks for Array-specific functions like `concat`, `shift`.

> escMap inherits from Object.prototype

Eek!

> web page can open('/').Object.prototype.__defineGetter__('defineAs',()=>alert('???'));

Yeah I forgot about it.

> out+='\\u00'+

Why did you remove support for unicode? Also, I don't optimize code unless the tests show significant performance improvements or better GC behavior, otherwise we will bury ourselves in unnecessary micro-optimizations that hinder readability and maintainability of the code. This function is only used for GM_setData so the input is a simple string/object/array in almost 100% of cases.

**Comment by tophf** [comment]
Ah, Array.isArray [wasn't broken](https://github.com/violentmonkey/violentmonkey/commit/5f81a447a56145935597bcf82d9caa1db288fd0a), so I'll try to use it instead of ours.

**Comment by xBZZZZ** [comment]
> Why did you remove support for unicode?

I didn't.

`\u2028` and `\u2029` are special `case`s in `switch`

`out+='\\u00'+` part is only for `\u0000-\u001F` and all characters in that range are 8 bit (2 hex characters) so escape always starts with `\u00`

**Comment by tophf** [comment]
Thanks, I misinterpreted this code.

**Comment by xBZZZZ** [comment]
`Number.prototype.toString` can still be replaced
```javascript
var w=open('/');
Object.defineProperty(w.Number.prototype,'toString',{
  'get':()=>{
    if(Error().stack.indexOf('/sandbox/injected-web.js')>=0)w.alert('violentmonkey?');
    return (0).toString;
  }
});
```

**Comment by tophf** [comment]
Now I understand! I forgot to use the vault for these methods.

**Comment by xBZZZZ** [comment]
also web page can break
```javascript
    res = `"${value::replace(escRE, escFunc)}"`;
```
by doing
```javascript
RegExp.prototype[Symbol.replace]=()=>console.log(Error("replace"));
```
(also breaks everything that uses `.replace` with `RegExp`)

[other stuff that can be broken using symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#static_properties)

**Comment by tophf** [comment]
It will break all scripts in `page` mode too so even if we fix it for us, what good will that be?

**Comment by tophf** [comment]
Like I already said, if people report to us such a page we will add it to an internal list that forces `content` mode automatically. If there will be many such reports we will add an option to customize this list.

**Comment by tophf** [comment]
I've changed my mind because there were just a few places where those symbols needed guarding: f5239b4e.

**Comment by xBZZZZ** [comment]
web page can do
```javascript
RegExp.prototype.exec=console.trace;
```
and this beaks most of regexp stuff

**Comment by tophf** [comment]
No, Violentmonkey doesn't use `exec`.

**Comment by xBZZZZ** [comment]
> No, Violentmonkey doesn't use `exec`.

but native regexp functions do!

try running this:
```javascript
RegExp.prototype.exec=console.trace;
"aaabaaabaa".replace(/b/g,"!");
```

**Comment by tophf** [comment]
Like I said, Violentmonkey is not affected.

**Comment by xBZZZZ** [comment]
> Like I said, Violentmonkey is not affected.

what about this line? https://github.com/violentmonkey/violentmonkey/blob/54f78130379a00afa4419bad0723a8b1363b0cf6/src/injected/web/requests.js#L39

`exec` is used by `RegExp.prototype[Symbol.replace]`:
```javascript
//similar thing happens in violenmonkey
var rsr=open().RegExp.prototype[Symbol.replace];


rsr.call(/aa/g,"aaaabaa","e");//this will work

RegExp.prototype.exec=()=>{throw Error("asd")};

rsr.call(/aa/g,"aaaabaa","e");//this will not work because `exec` is now broken
```

**Comment by tophf** [comment]
regexpReplace is taken from the vault so like I said, Violentmonkey is not affected.

**Comment by xBZZZZ** [comment]
> regexpReplace is taken from the vault so like I said, Violentmonkey is not affected.

It doesn't matter from which context `regexpReplace` is from.
```javascript
//the vault iframe contentWindow
var w=document.body.appendChild(document.createElement("iframe")).contentWindow;

//these are native functions from vault (not spoofed)
var regexpReplaceFromVault=w.RegExp.prototype[w.Symbol.replace];
var safeCallFromVault=w.Object.call.bind(w.Object.call);

//web page does this (didn't change vault stuff)
RegExp.prototype.exec=()=>{throw Error("asd")};

//error becauce regexpReplaceFromVault GETS `exec` OF REGEXP OBJECT internally
safeCallFromVault(regexpReplaceFromVault,/aa/g,"aabaa","x");
```

see https://262.ecma-international.org/12.0/#sec-regexpexec

**Comment by tophf** [comment]
Geez, what a retarded language design.

**Comment by xBZZZZ** [comment]
`RegExp.prototype.global` (and other stuff) can also be replaced and is used by `exec`

here is fix: https://github.com/violentmonkey/violentmonkey/pull/1431
