### ISSUE TITLE
Opening raw text files from raw.githubusercontent.com doesn't give proper display

### ISSUE THREAD

**Issue by win98se** [violentmonkey/violentmonkey#1424]
### What is the problem?
As in title

### How to reproduce it?
1. Disable all extensions and install Violentmonkey Beta from scratch
2. Open a raw text file from raw.githubusercontent.com
3. Result bug (see below)

### What is the expected result?
The raw text file displays correctly.

### What is the actual result?
The raw text file doesn't display, and only shows a small iframe at the top left side of the page.

![image](https://user-images.githubusercontent.com/11819816/141650387-c27827e4-568e-4277-82a9-6ae1f1421b67.png)

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?<br>WARNING! Do an export in settings before testing!
Same as above (as I am using beta version)

The JavaScript console logs are as below -
```
about:blank:1 
        
Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

-------------

chrome-extension://o…gichg/injected.js:1 
        
Uncaught (in promise) TypeError: Illegal invocation
    at at (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1)
    at tt (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1)
    at $t (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1)
    at Module.<anonymous> (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1)
    at n (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1)
    at chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1
    at chrome-extension://opokoaglpekkimldnlggpoagmjegichg/injected.js:1

Promise.catch (async)
(anonymous) @ chrome-extension://o…gichg/injected.js:1
n @ chrome-extension://o…gichg/injected.js:1
(anonymous) @ chrome-extension://o…gichg/injected.js:1
(anonymous) @ chrome-extension://o…gichg/injected.js:1
```
### Environment
- Browser: Microsoft Edge
- Browser version: 95.0.1020.53
- Violentmonkey version: BETA v2.13.0.12
- OS: Windows 10 Version 21H2 (Build 19044.1348)

**Comment by tophf** [comment]
Fixed it half an hour ago via b9e6e015, test build is in CI workflows.
