### ISSUE TITLE
web page can see violentmonkey cookie inside <code>unload</code> event if <code>Synchronous <code>page</code> mode</code> is enabled

### ISSUE THREAD

**Issue by xBZZZZ** [violentmonkey/violentmonkey#1425]
<ol><li>enable <code>Synchronous <code>page</code> mode</code> in violentmonkey  settings</li><li>open http web page</li><li>run this in javascript console:<pre lang="javascript">window.addEventListener("unload",()=>{
  sessionStorage.setItem("cookie",document.cookie);
});</pre></li><li>reload web page</li><li>check <code>Session Storage</code> in devtools <code>Application</code> tab, you will see stuff similar to this:<table><thead><tr><td>Key</td><td>Value</td></tr></thead><tbody><tr><td>cookie</td><td>"Violentmonkey:B703g3fL5ec="=82e02995-cec6-47d4-a9b6-0b15b3a604d9</td></tr></tbody></table></li></ol>violentmonkey build: <a href="https://github.com/violentmonkey/violentmonkey/actions/runs/1456812878">
Violentmonkey-test-webext-v2.13.0.12-21-gb9e6e01</a><br>web browser: chromium

**Comment by tophf** [comment]
The page can see it but seeing won't help it.
