### ISSUE TITLE
`Script installed` message text color should not be red/orange, because it refers to a successful operation

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1430]
In script installation page, after you click the "Confirm installation(Ctrl+Enter)" button, 
the displayed `Script installed` message text has red/orange color. Here are screenshots with the dark/theme theme respectively:
![2021-11-25_165631](https://user-images.githubusercontent.com/723651/143464129-5c7e0fcf-6e0b-4a99-888e-54e04e5370e4.jpg) ![2021-11-25_170416](https://user-images.githubusercontent.com/723651/143464501-3717d6bf-e462-445d-92d6-a2ea95cbe1a4.jpg)

I believe it shouldn't be red/orange, because it refers to a successful operation, not an error. Instead, it should be in a "positive" color (green/blue) or neutral.

- Browser: Chrome 96, Firefox 94
- Violentmonkey version: 2.13.0 stable, 2.13.0.14 beta
- OS: Windows 11 x64

**Comment by tophf** [comment]
Orange is an attention color here, it's also close to the logo color. That said, it should be adjusted in the dark scheme, which I forgot since I don't use it.

**Comment by darkred** [comment]
Thanks for responding. You are right, it should only refer to the dark theme, so I edited it according.
I see you closed it. Maybe it should remain open?

**Comment by darkred** [comment]
Thank you for handling this.
