### ISSUE TITLE
Change default `run-as`

### ISSUE THREAD

**Issue by DUOLabs333** [violentmonkey/violentmonkey#1434]
### What is the problem?
There's no way to change the default `run-as` behavior -- I moved from Tampermonkey, so a lot of `run-as` needs to be specified as `document-idle` manually.

### How to reproduce it?
1.
2.
3.

### What is the expected result?
Option to change default `run-as`

### Environment
- Browser: Firefox
- Browser version: 88
- Violentmonkey version: v2.13.0
- OS: Arch Linux

**Comment by tophf** [comment]
While such an option would make sense by itself, I'd like to clarify why you want to specify document-idle manually? The default injection timing is document-end both in Tampermonkey and Violentmonkey so there should be no need for you to change anything.

**Comment by DUOLabs333** [comment]
For some reason, `document-end` doesn't work with my scripts.

**Comment by tophf** [comment]
You should investigate the problem separately then. We probably won't implement this option because even Tampermonkey doesn't have it, which means that it's not necessary.
