### ISSUE TITLE
The network requests log in the extension's popup

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1435]
The requests made with `GM.xmlhttpRequest` are not possible to watch in DevTools log of the site where the script runs.

I think it would be useful if were a window with the last network requests in the extension's pop up.
It should contain size, speed, and show the URL of the request (as a title, or as a details elem, for example).

It makes to easier control the extension's requests, also to make easier debugging.

Also it would be useful for people with low speed connections if an userscript has not UI in web page that shows the downloading progress.

**Comment by AlttiRi** [comment]
The request entry should looks like this:
The left colored border (one color for the requests of the same script), hostname, size and speed, the progress bar as bottom border, or colored background.
On click it shows the details with URL (It would be nice to show both the requested URL and the final URL after redirects) and HTTP headers.

**Comment by AlttiRi** [comment]
The ability to cancel the request also would be nice. Currently it requires to reload the web page.

**Comment by AlttiRi** [comment]
I know about it.

The issue is more for common users, than for devs. But for devs it makes writing the scripts much easier.

It's notable unconvenient to inspect the extension, also DevTools does not displays the requests performed and started before opening.

**Comment by tophf** [comment]
Violentmonkey is a lightweight extension by design so we won't replicate such advanced functionality that is already available in built-in devtools.

**Comment by WhatIsACore** [comment]
@tophf This functionality does **not** seem to be available in any built-in devtools as they are currently unable to record requests made in violentmonkey.

Is there another way for users or script authors alike to know what requests a violentmonkey script is making? A malicious script that has already been granted `GM_xmlhttpRequest` for seemingly good reasons could steal information and send it on the side (completely bypassing cross-origin protections), and there's currently no easy way to monitor the behavior of these scripts.

**Comment by tophf** [comment]
Sounds like you're opening the wrong devtools, please use the links in my first comment.
