### ISSUE TITLE
Can violentmonkey run on edge:// URLs  when experimental feature is enabled

### ISSUE THREAD

**Issue by YexuanXiao** [violentmonkey/violentmonkey#1445]
Can  violentmonkey run on edge:// URLs or chrome:// URLs when experimental feature is enabled?
![image](https://user-images.githubusercontent.com/20025591/147875567-81965985-e6a8-4a47-9c5f-8b6d19f2edf0.png)
I want to make some little changes to edge://newtab using volentmonkey, but its doesn't work.
edge://newtab actually accesses https://ntp.msn.cn (in China), but if I access https://ntp.msn.cn directly, violentmonkey is disabled as well.

**Comment by tophf** [comment]
No. You'll have to make a copy of Violentmonkey extension, edit its manifest.json and add `,"chrome://*/*"` after `"<all_urls>"`. We can't submit such extension into the web store, AFAIK.

>but if I access https://ntp.msn.cn directly, violentmonkey is disabled as well.

Edge may have an option that protects the search engine just like Opera. If not, see if `chrome://policy` has ExtensionSettings with runtime_blocked_hosts.

**Comment by YexuanXiao** [comment]
> No. You'll have to make a copy of Violentmonkey extension, edit its manifest.json and add `,"chrome://*/*"` after `"<all_urls>"`. We can't submit such extension into the web store, AFAIK.
> 
> > but if I access https://ntp.msn.cn directly, violentmonkey is disabled as well.
> 
> Edge may have an option that protects the search engine just like Opera. If not, see if `chrome://policy` has ExtensionSettings with runtime_blocked_hosts.

Thank you very much for your reply!🥰
