### ISSUE TITLE
Some scripts do not work under Fennec F-Droid (a build of Firefox) with ViolentMonkey

### ISSUE THREAD

**Issue by Iey4iej3** [violentmonkey/violentmonkey#1447]
### What is the problem?

The script https://greasyfork.org/zh-CN/scripts/396171-%E7%9F%A5%E4%B9%8E%E5%85%8D%E7%99%BB%E5%BD%95 does not work under Fennec F-Droid with ViolentMonkey

### How to reproduce it?
1. Install the script;
2. Visit www.zhihu.com

### What is the expected result?
No prompt for login.

### What is the actual result?
The script does not seem to work.
It works under KiwiBrowser with ViolentMonkey, or under Fennec F-Droid with TamperMonkey.

### Environment
- Browser: Fennec F-Droid
- Browser version: 95.2.0
- Violentmonkey version: 2.13.0
- OS: LineageOS 18.1 (Android 11)

**Comment by tophf** [comment]
We can't investigate it because Fennec doesn't allow installing a development extension directly as an xpi/zip. Fennec is still in the process of implementing WebExtensions support so such bugs are expected.

**Comment by tophf** [comment]
It's also possible our beta already works with this script so please retest it when it's published.

**Comment by Iey4iej3** [comment]
Neither does it work under Firefox 78 ESR on Debian Linux, with User Agent being Chrome on Android (it works under Chromium with the same UA). It might be an issue about Firefox. I don't find VM Beta on AMO.

**Comment by tophf** [comment]
> Neither does it work under Firefox 78 ESR on Debian Linux, with User Agent being Chrome on Android (it works under Chromium with the same UA).

If you can reproduce it in a desktop Firefox, please provide an exact sequence of steps and settings. I've tried reproducing it in Tampermonkey and I don't see any login prompts either.

> I don't find VM Beta on AMO.

AMO no longer allows beta in their listing so you can install it as a zip from this repo's releases.

**Comment by Iey4iej3** [comment]
> I've tried reproducing it in Tampermonkey and I don't see any login prompts either.

Did you mean that you tried ViolentMonkey on Firefox? Are you testing the beta version? I will try to test the same version as yours later.

**Comment by tophf** [comment]
Never mind.

This script has a mistake: it runs at `document-start` and expects `document.head` to exist at that time, which is wrong. It should use `document.documentElement` instead.

**Comment by tophf** [comment]
Thanks, but it doesn't matter anymore, see my comment above.

**Comment by Iey4iej3** [comment]
I understand a bit, but does that explain why it does not work under Firefox but it does under Chromium? Do they have different behaviors?

**Comment by tophf** [comment]
Violentmonkey uses a special fast API in Firefox to inject scripts at the real document start. In Chrome there's no such thing so injection usually occurs slightly later. Violentmonkey beta has a special synchronous mode of injection which ensures with 100% reliability a real document start also in Chromium. Tampermonkey also has such a mode in its advanced settings, it's called "instant".

**Comment by Iey4iej3** [comment]
I am not sure whether this is the real reason. I tried "instant" mode of TamperMonkey, and the script still works. I look at the console under "instant" with TamperMonkey, and it indeed contains an error

> Uncaught (in promise) TypeError: document.head is null

But this seems to be benign (and this error message does *not* appear with ViolentMonkey). The App avoidance works without that CSS injection. When I compare the error messages of TamperMonkey and ViolentMonkey, I find the following error messages which appear with ViolentMonkey but not TamperMonkey:

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). sandbox eval code:21:35
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

I don't know whether this is related?

**Comment by tophf** [comment]
> it starts to work when I set security.csp.enable to be false.

It means the real cause is a bug in Firefox: https://bugzil.la/1267027. On such sites Violentmonkey (as well as Firemonkey) injects in the "isolated world" that's not affected by CSP. Userscripts have to use `unsafeWindow.wrappedJSObject.navigator` + `cloneInto` when they want to override page properties on such sites.

> I don't know how TM solved this issue.

It removes the site's CSP, which effectively is the same as disabling it in about:config.
