### ISSUE TITLE
同一个脚本，暴力猴无法运行，但是tampermonkey可以

### ISSUE THREAD

**Issue by JamYiz** [violentmonkey/violentmonkey#1451]
### What is the problem?
同一个脚本，暴力猴无法运行，但是tampermonkey可以
### How to reproduce it?
1.安装链接的115转存脚本https://gist.github.com/Nerver4Ever/953447c9ecd330ffc0861d4cbb839369
2.暴力猴运行该脚本，在转存时会出现“上传失败！！！可能参数不正确 (?)：request invalid”错误
3.排查后使用油猴运行该脚本正常

### What is the expected result?
转存成功
### What is the actual result?
可能参数不正确 (?)：request invalid”错误
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
仍然错误
<br>WARNING! Do an export in settings before testing!

### Environment
- Browser:vivaldi
- Browser version:5.0.2497.38
- Violentmonkey version:2.13.0.16
- OS:windows

**Comment by gera2ld** [comment]
没有环境无法调试，请联系作者或者自行定位原因。
如果是API的问题我们这边可以修复。

**Comment by tophf** [comment]
See also if any older version of Violentmonkey worked, it may help us locate the reason.

**Comment by JamYiz** [comment]
> See also if any older version of Violentmonkey worked, it may help us locate the reason.

旧版本仍然不行，但Firefox上暴力猴可以正常运行，Vivaldi则报错。

**Comment by tophf** [comment]
Vivaldi is known to have multiple bugs in chrome.webRequest. Apparently Tampermonkey found a workaround but we don't know what it is. I don't have an account on 115.com so I can't debug it either.

**Comment by JamYiz** [comment]
> Vivaldi is known to have multiple bugs in chrome.webRequest. Apparently Tampermonkey found a workaround but we don't know what it is. I don't have an account on 115.com so I can't debug it either.

Thanks.
