### ISSUE TITLE
Unable to authorize with dropbox

### ISSUE THREAD

**Issue by newadventure079** [violentmonkey/violentmonkey#1454]
### What is the problem?
Unable to authorize with dropbox

### How to reproduce it?
1. Click settings
2. Choose Dropbox for sync
3. Click Authorize

### What is the expected result?
I'm taken to dropbox and can authorize

### What is the actual result?
I'm taken to `https://violentmonkey.github.io/auth_dropbox.html#access_token=REDACTED`

Page says
```
Not Found
You just hit a route that doesn't exist... the sadness.
```
![Screen Shot 2022-01-27 at 5 29 03 PM](https://user-images.githubusercontent.com/84156407/151465883-57ac60d9-a4e9-4020-809d-a49958261a5a.jpg)

### Environment
- Browser: Microsoft Edge
- Browser version: Version 99.0.1141.0 (Official build) Dev (arm64)
- Violentmonkey version:  Version2.13.0
- OS: macOS

**Comment by tophf** [comment]
The issue template asks to try out the [beta](https://github.com/violentmonkey/violentmonkey/releases). Please do. Don't forget to export the data first.

**Comment by newadventure079** [comment]
That fixed it.  Thanks!
