### ISSUE TITLE
GM_XMLHttprequest, HTTP 302 and MEGA.NZ

### ISSUE THREAD

**Issue by MikeZeDev** [violentmonkey/violentmonkey#1456]
### What is the problem?

I am trying to perform a XMLHttpRequest to get the real url behind a redirector using the following script.

https://pastebin.com/dBTc28dy

response.finalUrl (which i guess is a hack) does actually gives the redirected url but it doesnt work for MEGA.NZ links.

I just got the folder url : https://mega.nz/file/XXXX without the #xxxxxxxxxxxxxxxxxxx part (the decryption key)

Of course, its normal. Because VM got the link from (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL) which strips url artifacts. Or maybe i am wrong.

Do you know of a way i could get the Location header of the 302 response ? Of at least the final complete url? 

### Environment
- Browser: Firefox 96.0.3
- Violentmonkey version: latest
- OS: Windows 10

**Comment by tophf** [comment]
I don't see what Violentmonkey can do here. You need to write code to process the URLs for that site in a special fashion, maybe use an API or find an external service or something.

**Comment by tophf** [comment]
Yes, it's possible and Tampermonkey already exposes full URL.
