### ISSUE TITLE
坚果云webdav同步报错

### ISSUE THREAD

**Issue by redleafnew** [violentmonkey/violentmonkey#1457]
### What is the problem?
坚果云webdav同步报错，但不知道只是提示报错，实际已经同步完成还是真的是同步错误。因为原来没有脚本，通过这种方法同步出现了脚本。
### How to reproduce it?
1.输入坚果云webdav信息
2.保存
3.同步报错：同步出错！

### What is the expected result?
同步正常，不报错
### What is the actual result?
提示：同步出错！
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?<br>WARNING! Do an export in settings before testing!
结果一样。提示同步出错！

### Environment
- Browser:EDGE
- Browser version: 98.0.1108.43
- Violentmonkey version:v2.13.0
- OS:win 10 64

![录制_2022_02_09_14_48_20_71](https://user-images.githubusercontent.com/22135631/153140163-b547808e-8409-4c06-be18-07ce43021cf4.gif)

**Comment by gera2ld** [comment]
我这边测试是成功的，能不能看下具体的失败日志？

在扩展管理页面，开启“开发者模式”，然后查看“Background page”的控制台。
<img width="1225" alt="Screen Shot 2022-02-09 at 16 02 49" src="https://user-images.githubusercontent.com/3139113/153149646-c3023df5-9054-4bb6-8043-ac8dc6dc7a58.png">

然后看一下 Console 下面的错误日志

**Comment by redleafnew** [comment]
index.js:1 Ready to sync: WebDAV
index.js:1 First sync: true
index.js:1 Outdated: true ( local: undefined remote: 1644191445968 )
index.js:1 Download script: lanhaha-0a懒人专用，全网VIP视频免费破解去广告、全网音乐直接下载、百度网盘直接下载等多合一版。长期更新，放心使用。-0a
index.js:1 Download script: https-3a-2f-2fgitee.com-2fHGJing-2feverthing-2dhook-2f-0a计时器掌控者-7c视频广告跳过-7c视频广告加速器-0a
index.js:1 Download script: http-3a-2f-2flctnq.yhzu.cn-0a全网VIP视频免费破解去广告，百度文库下载,一键领取淘宝、天猫、京东、唯品会、拼多多、抖音隐藏优惠券！全网查券！【免费领取外卖红包、公交地铁红包】-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fadlered-0a🔥持续更新🔥-20CSDN广告完全过滤、人性化脚本优化：🆕-20不用再登录了！让你体验令人惊喜的崭新CSDN。-0a
index.js:1 Download script: http-3a-2f-2ftampermonkey.net-2f-0a自动展开豆瓣、站长之家、米坛、cnbeta、知乎、慕课网、Awesomes、喜马拉雅、CSDN博客、CSDN下载、道客88、百度文库、百度知道、回形针、人民日报客户端、凤凰网页面的隐藏内容-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fusers-2f7036-0aHTML5视频播放工具-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fusers-2f694396-0a【电脑-20&&-20手机-20全网唯一全自动脚本】VIP会员视频自动解析-0a
index.js:1 Download script: congcongguoke_baiduwenku_script-0a全网VIP视频免费破解去广告、【百度文库】破解-7c可复制下载、全网音乐直接下载、短视频去水印下载-3a支持抖音、快手等、知乎使用增强、CSDN使用增强等多功能脚本-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fzh-2dCN-2fusers-2f106222-2dqxin-2di-0a网页限制解除(改)-0a
index.js:1 Download script: baiduwangpan.taozhiyu.gitee.io-0a百度云去广告，快捷键倍速，免VIP解锁倍速、画质！全网独家！-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fzh-2dCN-2fusers-2f3128-0a网盘自动填写访问码【威力加强版】-0a
index.js:1 Download script: wenku.taozhiyu.gitee.io-0a百度文库-2d精简&优化-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fsyhyz1990-2fpanAI-0a网盘智能识别助手-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fsyhyz1990-2fbaiduyun-0a百度网盘直链下载助手（极速版）-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fsyhyz1990-2fbaiduyun-0a网盘直链下载助手-0a
index.js:1 Download script: lalala-0a懒人专用，全网VIP视频免费破解去广告、全网音乐直接下载、百度网盘直接下载、知乎视频下载等多合一版，长期更新。-0a
index.js:1 Download script: http-3a-2f-2fbd.softxm.cn-2fbd-2f-0a百度网盘简易下载助手（直链下载复活版）-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fsupernovaZhangJiaXing-2fTampermonkey-2f-0a知网PDF下载助手-0a
index.js:1 Download script: TyCloud_Tools-0a天翼云盘助手-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2fAruelius-2fCloud189_Greasyfork-2f-0a免登录下载天翼云盘分享文件-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fzh-2dCN-2fusers-2f4330-0a天翼云盘大文件直接下载，启用分享功能-0a
index.js:1 Download script: https-3a-2f-2fgithub.com-2foneNorth7-2fCloud189_popper-0a雷利子-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fscripts-2f412680-0a吾爱破解论坛增强-20-2d-20自动签到、翻页-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fscripts-2f412681-0a吾爱破解论坛美化-0a
index.js:1 Download script: https-3a-2f-2fgreasyfork.org-2fusers-2f244539-0a中国知网CNKI硕博论文PDF下载-0a
index.js:1 Download script: http-3a-2f-2ftampermonkey.net-2f-0a大学生网络党校学习助手-0a
index.js:1 Download script: coolhii_vip-0a[新]全网VIP视频免费破解去广告,支持电视剧免跳出选集、知乎使用增强、B站哔哩哔哩使用增强、全网音乐直接下载、百度文库下载等多合一纯净脚本-0a
www.youxiaohou.com/panai.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
www.youxiaohou.com/panai.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
www.youxiaohou.com/48x48.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
www.youxiaohou.com/48x48.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
dav.jianguoyun.com/dav/Violentmonkey/vm@2-coolhii_vip-0a[%E6%96%B0]%E5%85%A8%E7%BD%91VIP%E8%A7%86%E9%A2%91%E5%85%8D%E8%B4%B9%E7%A0%B4%E8%A7%A3%E5%8E%BB%E5%B9%BF%E5%91%8A,%E6%94%AF%E6%8C%81%E7%94%B5%E8%A7%86%E5%89%A7%E5%85%8D%E8%B7%B3%E5%87%BA%E9%80%89%E9%9B%86%E3%80%81%E7%9F%A5%E4%B9%8E%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA%E3%80%81B%E7%AB%99%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA%E3%80%81%E5%85%A8%E7%BD%91%E9%9F%B3%E4%B9%90%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E3%80%81%E7%99%BE%E5%BA%A6%E6%96%87%E5%BA%93%E4%B8%8B%E8%BD%BD%E7%AD%89%E5%A4%9A%E5%90%88%E4%B8%80%E7%BA%AF%E5%87%80%E8%84%9A%E6%9C%AC-0a:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 400 ()
index.js:1 Failed syncing: WebDAV
index.js:1 Array(3)

**Comment by gera2ld** [comment]
看上去是坚果云报错了，可能是文件名字过长了😅

这个 issue 暂时无法修复，需要一个新的同步方案，所以先关闭了。如果有兴趣可以到[这里](https://gitter.im/violentmonkey/sync-jianguoyun?utm_source=share-link&utm_medium=link&utm_campaign=share-link)讨论细节。

后续可以关注 #1306
