### ISSUE TITLE
User Interface for user scripts

### ISSUE THREAD

**Issue by cheater** [violentmonkey/violentmonkey#1458]
My scripts are very large and complex. I would like to make a user interface accessible via the Violentmonkey menu bar button. When the script is loaded, right next to the name of the script, currently there are the code button and the ellipsis (menu). I would like there to be additionally a cog which leads to a local `file://` resource which I define in my user script. This will be a html file with my own javascript code. I do not want to make this user script a FireFox addon or anything to that effect. I would like this functionality to be supported by Violentmonkey.

Currently what I have to do is somehow hack the user interface for my script somewhere into the page that the script is running on. I do not like that and I think it's a messy way of doing things.

I agree that in many situations there are ways to do things like that - to seamlessly integrate your own UI into the website being modified - but sometimes it just doesn't really work.

It seems that #430 is in a way an intermediate step towards achieving the functionality I'm looking for. For disambiguation, 430 does not realize the "cog button" function I describe above, so those two are not duplicates; it also talks about loading an arbitrary file off disk, not a html page that is distributed together with the user script.

**Comment by tophf** [comment]
It's already implemented in major engines: use [GM_registerMenuCommand](https://violentmonkey.github.io/api/gm/#gm_registermenucommand) and then show the UI either in the current page or in a new window.

**Comment by cheater** [comment]
@tophf while this allows you to run a function based upon some UI interaction, it does not allow opening a new window or tab that contains only the html I would like. So GM_registerMenuCommand does not seem to be a solution to what I am talking about. Can you advise how you would do that?

**Comment by tophf** [comment]
GM_registerMenuCommand('foo', showUI) then in your showUI function use window.open + document.write or set innerHTML.

**Comment by cheater** [comment]
Thank you!
