### ISSUE TITLE
Feature request: add option to GM_openInTab to create new tab group or create new option GM_openInTabWithGroup

### ISSUE THREAD

**Issue by zx6000** [violentmonkey/violentmonkey#1462]
Hello all,

I searched the issues but couldn't find anything related.

"add option to GM_openInTab to create new tab group or create new option GM_openInTabWithGroup"

The use case is that one might need to open 2-3 tabs from the original page and then work on the pages in the tabs and open more tabs.
The grouping will assist in showing which tabs belong together.
It's easier if we can do that from the script instead of the user clicking the tabs and creating groups every time.

Maybe the user could specify the color for different category of pages in their use case or leave it blank to be a random one.

My use case is about creating new groups and not messing with any existing grouping the user has.
No adding new tabs to existing groups by "accident" and no overwriting/closing existing groups (if this can happen).

What do you think?

https://developer.chrome.com/docs/extensions/reference/tabGroups/

Thank you!!!

**Comment by tophf** [comment]
This API is only for ManifestV3, which doesn't support userscripts yet. Additionally, this API is not supported by Firefox so I don't think we should add it. Try finding an extension that can automatically group tabs based on a pattern that you specify in its settings.
