### ISSUE TITLE
External JS framework load error using @require

### ISSUE THREAD

**Issue by krepe90** [violentmonkey/violentmonkey#1466]
### What is the problem?

**[Same issue on Tampermonkey [fixed]](https://github.com/Tampermonkey/tampermonkey/issues/1176)**
Excpetion occured when import external js framework. I could fix temporarily by using that issue's solution.

### How to reproduce it?
1. Just import `popper.js` and `tippy.js`
```js
// ==UserScript==
...
// @require      https://unpkg.com/@popperjs/core@2.11.2/dist/umd/popper.js
// @require      https://unpkg.com/tippy.js@6.3.7/dist/tippy-bundle.umd.js
...
// ==/UserScript==
```

### What is the expected result?

`TypeError: Cannot read properties of undefined (reading 'applyStyles')` printed on console and script stopped.
![image](https://user-images.githubusercontent.com/31591528/157322397-69f017ac-8121-4477-a370-c76b5b733914.png)

### What is the actual result?
Running script without error.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

Same error

### Environment
- Browser: Google Chrome
- Browser version:  99.0.4844.51
- Violentmonkey version: v2.13.0
- OS: Windows 10 21H1 (x86-64)

**Comment by tophf** [comment]
Fixed in a9c40558.
