### ISSUE TITLE
Fail to send request when adding a FormData  obejct to options.data of GM_xmlhttpRequest

### ISSUE THREAD

**Issue by techmovie** [violentmonkey/violentmonkey#1470]
### What is the problem?
Fail to send request when adding a FormData  obejct to `options.data` of GM_xmlhttpRequest

`index.js:formatted:3075 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

this error message is from 

https://github.com/violentmonkey/violentmonkey/blob/74716b32096bc19d89f8bca9014152dee0fcb005/src/background/utils/requests.js#L390

### How to reproduce it? 
send a http request like this: 
```
GM_xmlhttpRequest({ 
       method: 'POST',
      url: 'xxx',
      responseType: 'json',
      data: new FormData()
})
```

### What is the expected result?

should  send http request with data properly

### What is the actual result?
can't send http request with data properly
### Environment
- Browser: Chrome
- Browser version:  99.0.4844.51 (Official Build) (x86_64)
- Violentmonkey version: Violentmonkey BETA 2.13.0.17
- OS: MacOS 12.2.1

**Comment by tophf** [comment]
Fixed in 25ee40e3.
