### ISSUE TITLE
Add a dark mode to preferences

### ISSUE THREAD

**Issue by ghtesting2020** [violentmonkey/violentmonkey#1475]
I checked open and closed with none mentioning this request yet.

### What is the problem?
Please add a dark mode to the settings page. Currently out of 8 add-ons I use in Firefox this is the only one that does not have a dark mode.

### How to reproduce it?
1. Go to add-ons and themes
2. Click the ... menu beside Violentmonkey
3. Click preferneces

### What is the expected result?
not being temporarily blinded

### What is the actual result?
being temporarily blinded

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?<br>WARNING! Do an export in settings before testing!
No mention of a dark mode.

**Comment by tophf** [comment]
It's already implemented in beta.
![image](https://user-images.githubusercontent.com/1310400/159146068-d8a75631-e8e2-4e37-9545-c32f68e5fe95.png)
