### ISSUE TITLE
[BUG] custom elements aren't created properly with @inject-into content

### ISSUE THREAD

**Issue by bipface** [violentmonkey/violentmonkey#1479]
with `@inject-into content`, creating custom elements (aka *web components*) does instantiate the element class, yet still results in a plain `HTMLElement` instance,.

- install the below script
- visit <https://violentmonkey.github.io/>
- open the web console
- expect: `instanceof TestElem: true` should be logged (actual: `instanceof TestElem: false`)

tested with violentmonkey v2.13.0.17 in firefox v99.0b7 and v91.4.1 ESR

test script:

```js
// ==UserScript==
// @name        customelements-test
// @namespace   Violentmonkey Scripts
// @match       https://violentmonkey.github.io/*
// @grant       none
// @inject-into content
// ==/UserScript==

'use strict';

let w = window; // or unsafeWindow

class TestElem extends HTMLElement {
	constructor() {
		super();
		console.log('invoked constructor()');
	}
    
    testMethod() {
		console.log('invoked testMethod()');
	}
}

w.customElements.define('test-elem', TestElem);
let el = w.document.createElement('test-elem');
el.testMethod?.();
console.log('instanceof TestElem:', el instanceof TestElem);
```

various scenarios tested:

| `w` | `@inject-into` | `@unwrap` | output |
| --- | --- | --- | --- |
| `window` | `page` | - |  invoked constructor() , invoked testMethod() , instanceof TestElem: true |
| `unsafeWindow` | `page` | - |  invoked constructor() , invoked testMethod() , instanceof TestElem: true |
| `window` | `page` | `@unwrap` |  invoked constructor() , invoked testMethod() , instanceof TestElem: true |
| `window` | `content` | - |  invoked constructor() , instanceof TestElem: false |
| `unsafeWindow` | `content` | - |  invoked constructor() , instanceof TestElem: false |
| `window` | `content` | `@unwrap` |  invoked constructor() , instanceof TestElem: false |

**Comment by tophf** [comment]
This is an architectural necessity, see https://crbug.com/390807, because JavaScript is isolated in content mode. The solution is to use [GM_addElement](https://violentmonkey.github.io/api/gm/#gm_addelement) to add the component code into the page as `script` element.
