### ISSUE TITLE
Issues with AdBypasser in CocCoc

### ISSUE THREAD

**Issue by mickcarterus** [violentmonkey/violentmonkey#148]
### What's the problem?
AdsBypasser is not working with Violentmonkey in Coc Coc. 

### How to reproduce it ?
1. I'm using Violentmonkey + AdsBypasser (https://adsbypasser.github.io/) + CocCoc (a chromium-based browser, can be downloaded here: http://coccoc.com/en/). 
2. The problem I have is Adsbypassers seems to not be working at all. So, if I visit a adf,ly kind of page, a message would appear saying it detects adblocker or redirects to a captcha page.
3. This issue is not present when using Chrome v 59. (still with Violentmoney and Adsbypasser.

### Environment
- Browser: COC COC broweser (http://coccoc.com/en/)
- Browser version: 64.4.126 (latest)
- Violentmonkey version: 2.7.0
- OS: Windows 7

**Comment by legnaleurc** [comment]
I *think* I'll need `cloneInto` and `exportFunction` for AdsBypasser.

**Comment by gera2ld** [comment]
closed in favor of #168
