### ISSUE TITLE
[BUG] 暴力猴无法在此页面执行用户脚本

### ISSUE THREAD

**Issue by tafeilgh** [violentmonkey/violentmonkey#1485]
使用chrome,暴力猴的图标是灰色的,提示"暴力猴无法在此页面执行用户脚本",部分脚本可以正常使用部分不可以

**Comment by tophf** [comment]
The message you see already explains the reason. If you need further assistance show a screenshot and describe what you do, so we can investigate it ourselves.

**Comment by tophf** [comment]
Your screenshot doesn't show the page and its address. If you click the icon you will see an explanation:

>暴力猴无法在当前页面执行用户脚本
    （常见原因：浏览器/扩展内置页面、被策略屏蔽、Opera 下的搜索页面需要特殊设置）

**Comment by rdsylsq** [comment]
暴力猴无法在当前页面执行用户脚本 （常见原因：浏览器/扩展内置页面、被策略屏蔽、Opera 下的搜索页面需要特殊设置）
