### ISSUE TITLE
[BUG] GM_DOWNLOAD not working on mobile android fenix 

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#1487]
I'm totally aware that android fenix is not even official supported but since violentmonkey works almost perfectly and let me say among the userscrip managers is the most compatible with mobile (for example TM is not able to export UserScript zip backup while VM do it perfectly ) i really wish that GM_DOWNLOAD api will also work with mobile in future .
for example this UserScript downloading images in contextual menu works perfectly on desktop but not on mobile (long tap is correctly recognized as contextual menu) ,but download fails

**Comment by tophf** [comment]
Seems to be fixed in 84373a9f, however the current 2.13.3 won't run in Android due to #1612. Please wait for 2.13.4.
