### ISSUE TITLE
VM cannot connect to the background page.

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1492]
In console I have this

`Error: Violentmonkey cannot connect to the background page.`

I have this message when I start my browser (Manjaro Linux, Firefox)

**Comment by tophf** [comment]
Unfortunately it's impossible to tell what's wrong based on this info.
Try debugging the extension yourself: https://extensionworkshop.com/documentation/develop/debugging/

**Comment by soviet-man** [comment]
In Firefox I have two profiles.
When I open Firefox with one profile I have this issue.
When I open Firefox with another profile everything is OK.

![изображение](https://user-images.githubusercontent.com/33825590/163668019-04dc6487-53f7-476a-9583-c69fc209f632.png)

**Comment by tophf** [comment]
Sounds like there's a problem in your other profile.
Unfortunately it's impossible to tell what's wrong based on this info.
Try debugging the extension yourself: https://extensionworkshop.com/documentation/develop/debugging/

**Comment by soviet-man** [comment]
> Sounds like there's a problem in your other profile.

No idea what can happen? Yesterday everything was OK.
I already cleared cache in my browser but it doesn't help, my userscripts don't work.

**Comment by tophf** [comment]
Sorry, no idea.
