### ISSUE TITLE
[Feature] add easy way to exclude sub-frame only script

### ISSUE THREAD

**Issue by jacob755** [violentmonkey/violentmonkey#1494]
**Motivation**

in matched script i will exclude an script with url suggested by extension 
now i will to try to exclude sub-frame  script and extension  suggest me same url in first step but sub-frame  script running on another domain

**Proposed Solution**
on sub-frame  script extension offer excluding url that running on it

**Use Cases**

excluding

**Comment by tophf** [comment]
Fixed in 8959db82.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/6150553455/artifacts/214932321)

**Comment by jacob755** [comment]
> Fixed in [8959db8](https://github.com/violentmonkey/violentmonkey/commit/8959db82c5f908fcf1420720fef1a46fc24587bf). Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/6150553455/artifacts/214932321)
thank you for fast fix.but can not get to work extension


Warning details

Reading manifest: Warning processing permissions: Error processing permissions.9: Value "declarativeContent" must either: must either [must either [must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking", "webRequestFilterResponse.serviceWorkerScript"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["geckoProfiler"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["networkStatus"], be one of ["telemetry"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking", "webRequestFilterResponse.serviceWorkerScript"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
Warning details

Reading manifest: Warning processing options_page: An unexpected property was found in the WebExtension manifest.

**Comment by tophf** [comment]
These warnings can be ignored.

**Comment by jacob755** [comment]
> These warnings can be ignored.
installed in fresh profile setting page visible
on not fresh profile blank page

and again thank you so much for great fast fix its working.test page
first exclude match script
then refresh page subscript appear exclude it
then refresh,another subscript appear exclude it
no more sub-script done!

https://www.udemy.com/course/curso-de-programacao-em-linguagem-c-para-iniciantes/?couponCode=REALDISCOUNT5

when chrome version? i use most that

**Comment by tophf** [comment]
Sorry, I didn't understand your post. If there's a problem, maybe you can show a screen recording gif?

**Comment by jacob755** [comment]
> Sorry, I didn't understand your post. If there's a problem, maybe you can show a screen recording gif?

its might my profile have problem
error in console
Uncaught 
Exception { name: "NS_ERROR_FILE_CORRUPTED", message: "", result: 2152857611, filename: "moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/common-ui.js", lineNumber: 1, columnNumber: 0, data: null, stack: "@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/[common-ui.js:1](moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/common-ui.js):102924\nl@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:722\n@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:28578\nl@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:722\nn@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:591\n@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:1537\n@moz-extension://eff7c3f4-ed40-4238-bf0f-36ff932e78ac/options/index.js:1:1542\n" }
common-ui.js:1

​


![violet](https://user-images.githubusercontent.com/65178892/163715373-cab94fbc-7b1c-4390-aa8b-f5a2e38a6b07.png)

**Comment by jacob755** [comment]
:its working very well as supposed too above is just error in old Firefox profile
which seems maybe my profile corrupted so ignore it
just please build chromium build

best regards

**Comment by jacob755** [comment]
so sorry its working on chrome too!
thanks
