### ISSUE TITLE
Multiple call of `GM_registerMenuCommand`

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1495]
### Script
```js
// ==UserScript==
// @name        Pixiv Triple GM_registerMenuCommand
// @namespace   Pixiv
// @match       https://www.pixiv.net/en/users/*
// @match       https://www.pixiv.net/users/*
// @description 2022.04.19 Pixiv Triple GM_registerMenuCommand
// @grant       GM_registerMenuCommand
// ==/UserScript==

GM_registerMenuCommand("Menu Item (click me)", () => {
  console.log("[MenuCommand], GM_registerMenuCommand");
});
```

### URL
https://www.pixiv.net/en/users/42083333

### What to do
- Click on the menu item.

### Result
The callback of `GM_registerMenuCommand` is called **three** times.

---

The bug appears only in Firefox. (And on this site)

**Comment by AlttiRi** [comment]
There is the bug in TM too.

Although the menu command is called once, but the script is registered 3 times:
![image](https://user-images.githubusercontent.com/16310547/164063536-6bb7855a-9ed6-4064-b9bf-709a27004b1b.png)

@derjanb

**Comment by tophf** [comment]
This is working correctly: there are three pixiv iframes where you script runs. You can disable it by adding `@noframes` in the metablock.

**Comment by AlttiRi** [comment]
Okay, thanks, it works now.

But in Chromium it works different.
(Chromium, as I know, also supports running script in `iframe`.)

**Comment by tophf** [comment]
It's a bug in Firefox, apparently. It runs our scripts in so-called anonymous iframes that don't have any `src` and that weren't navigated inside, so their effective URL is `about:blank`. Our extension (and Tampermonkey) doesn't want to run in such iframes, which is why we don't specify `"match_about_blank": true` in manifest.
