### ISSUE TITLE
"Invalid script" when pasting text from another script

### ISSUE THREAD

**Issue by Tamarindo94** [violentmonkey/violentmonkey#1496]
I'm trying to migrate from Tampermonkey to Violentmonkey. Importing Tampermonkey scripts failed, so I tried to copypaste the text in a new userscript, but I keep getting "Invalid script" when trying to save it. I cannot figure out what is causing the problem

**Comment by Tamarindo94** [comment]
Just figured it out - it seems that the metadata block requires a whitespace after the double slash. It doesn't happen on Tampermonkey, so it kinda puzzled me

**Comment by tophf** [comment]
This is because Violentmonkey intentionally matches the original requirement, see #610 for more context.
