### ISSUE TITLE
[BUG] Installed scripts are not visible till restart of Firefox

### ISSUE THREAD

**Issue by kiulifa76** [violentmonkey/violentmonkey#1499]
**Describe the bug**

If we disable the option "allow update" in any VM script setting, all installed scrips are disappearing and not working till restart of the browser.

**To Reproduce**
1. Install any script.
2. Go in VM installed scripts.
3. Disable the option "allow update" of the script and click on "save and close".
4. When you`re in VM options, click on "check all for updates" icon. VM is ignoring to update the script, something which we did in the previous step.
5. Close the VM option tab but the browser should be running.
6. Open the VM options again. There is no script loaded in VM.
7. If we close the browser and opened it again, the script is showing and working in the VM options.
8. I reproduce this behavior with any installed script.

**Environment:**
- OS: Windows 10
- Browser: Firefox
- Browser Version: 95.0.2
- Violentmonkey Version: 2.13.0.18

**Comment by tophf** [comment]
Fixed in b1aaadad.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/6456842477/artifacts/236819512)
