### ISSUE TITLE
GM_download: Add saveAs attribute

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1501]
**Motivation**

On a website with an list of sounds, I would like to be able to bulk download a list of files.
I was able to guess/build all the URL of my list, but when I call `GM_download` on them in my `for` loop, I end up having a "Save as…" browser window (Vivaldi) popping up, in which I have to browse to the folder I want to save the file to (and strangely, I only have the possibility to save the last iteration of my loop).

**Proposed Solution**

I guess that if we had the possibility to have the same `saveAs: false` attribute as in Tampermonkey, I could have my script running good?

```js
GM_download({
	url: "/audio/audio_file_2016/" + audio.getAttribute("data-id") + "/" + audio.getAttribute("data-title"),
	name: app + " - " + lang + " - " + audio.getAttribute("data-title"),
	saveAs: false // this is not supported by VM yet
});
```

`saveAs` is the only attribute that [TM has](https://www.tampermonkey.net/documentation.php?ext=dhdg#GM_download) but [VM has not](https://violentmonkey.github.io/api/gm/#gm_download) yet.

**Comment by tophf** [comment]
Yeah, it's #1349.

**Comment by tophf** [comment]
I mean we will add `saveAs` when/if we implement an alternative GM_download backend in that issue.
