### ISSUE TITLE
[BUG] BETA v2.13.0.11 and above break compatibility with maxurl

### ISSUE THREAD

**Issue by brian6932** [violentmonkey/violentmonkey#1502]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Versions of Violentmonkey >= BETA v2.13.0.11, [break this UserScript](https://github.com/qsniyg/maxurl/)

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Install BETA v2.13.0.11 or later
2. Install Image Max URL https://github.com/qsniyg/maxurl/blob/master/userscript.user.js?raw=true
3. Go to options page: https://qsniyg.github.io/maxurl/options.html

**Expected behavior**
![image_239](https://user-images.githubusercontent.com/18603393/168669072-e2784e4a-ce81-46b9-bd4d-774dfb01a587.png)

**Actual behavior**
![image_238](https://user-images.githubusercontent.com/18603393/168668569-7e59eb55-2ee8-4eb3-ad82-f3ae96acece3.png)

**Console Error**
![image_240](https://user-images.githubusercontent.com/18603393/168669389-d9864bbc-9031-4fbc-9106-9f5887a39c89.png)

**Environment:**
- OS: Windows 10
- Browser: Tested on LibreWolf , Firefox Dev 
- Browser Version: 100.0-3, 101.0b2
- Violentmonkey Version: Title

**Comment by tophf** [comment]
It's a mistake in the script's code which was exposed when we added a 4th number to our version string. Please suggest the author to fix the script by converting `var _version_compare_pad_0 = function(array, amount) {` to `function _version_compare_pad_0(array, amount) {`
