### ISSUE TITLE
Don't send `origin` header

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1504]
VM has the default browser behaviour, it sends `origin: chrome-extension://opokoaglpekkimldnlggpoagmjegichg` with each request (since they are "cross-origin").

TM does not do it. More correct — TM removes this header.

- It would useful to simulate real browser requests.
- Also it will not not expose, that requests are made from the extension.

I can only modify a header value, but not remove the header entirely.

---

It's only Chromium related issue.
Firefox does not add `origin` header for requests sent from bg script.

**Comment by tophf** [comment]
Chrome doesn't add this header to normal requests with method `GET`, but it indeed adds them to the other methods. I agree we should remove it because there's no useful purpose in adding this header automatically.

**Comment by tophf** [comment]
Fixed in 530cc4c4.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/6618797888/artifacts/249240778)
