### ISSUE TITLE
[BUG] "Something went wrong" while authorizing google drive sync

### ISSUE THREAD

**Issue by Willy-JL** [violentmonkey/violentmonkey#1507]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Attempting to authorize google drive sync results in a "Something went wrong" google auth loop.

**To Reproduce**
1. Select sync to google drive
2. Click authorize
3. Select google account and click allow
4. Now stuck in "Something went wrong" loop

**Expected behavior**
Violentmonkey is granted access to my google drive and it starts syncing my userscripts.

**Actual behavior**
When attempting to authorize google drive sync I am able to select my google account, I am able to click on the allow access button, but after that I get stuck in a "Something went wrong" loop. Clicking next just takes me back to this page.
![image](https://user-images.githubusercontent.com/49810075/170122024-84200df1-2d43-4ae5-8d11-5f5c07bf212b.png)

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Same behavior.

**Environment:**
- OS: Garuda Linux (Arch based)
- Browser: Firefox and Waterfox
- Browser Version: Firefox 100.0.1 and Waterfox G4.1.2
- Violentmonkey Version: 2.13.0 from addons.mozilla.org

**Additional context**
The console of the Violentmonkey settings tab shows no output. The google auth page shows this instead while failing:
![image](https://user-images.githubusercontent.com/49810075/170123413-8f4a1238-80f1-406d-b7c9-dccac6d40550.png)
My best guess is that XHR 401 unauthorized is the issue. Unfortunately it doesn't seem to provide that much useful information as far as i can tell... this is the raw response content for it:
![image](https://user-images.githubusercontent.com/49810075/170123677-4b592562-02f4-47ab-93e1-5d1d7c7185fa.png)
I tried logging out and in again of my account, nothing changed.

**Comment by tophf** [comment]
The stable version 2.13.0 is quite ancient. There's a high probability it was fixed in the beta version. Try installing it as a temporary extension via `about:debugging` page after exporting your current data.

**Comment by Willy-JL** [comment]
Already tried the latest build from the pre-releases here on github, same behavior...

**Comment by tophf** [comment]
It works for me in my main profile where I have an active goggle account. The error in your screenshot says "Unauthorized" so I guess it may be a problem logging in. Things to try: 1) sign in your google account separately, 2) make a new firefox profile on `about:profiles` with just Violentmonkey extension.

**Comment by Willy-JL** [comment]
So after manually disabling all extensions one by one it worked fine, still no clue which one was the issue... sorry for wasting your time :/
