### ISSUE TITLE
[BUG] Sync XHR during script execution breaks page loads

### ISSUE THREAD

**Issue by ppixiv** [violentmonkey/violentmonkey#1508]
If a script runs a sync XHR during its initial execution, the XHR completes normally and the script continues running, but the page doesn't load.  This only happens in Firefox.

For context, in development I'm using a small script stub that loads the script from a server on localhost. It was originally due to #430, but it also lets me handle SCSS parsing on the devel server, so I can make changes to SCSS without having to do a separate rebuild.

However, it needs to load the script synchronously, otherwise the page will get a chance to run before the script is fetched.  In a regular build of the script this doesn't happen (all of the code is packaged in the script), and of course it's important for the devel environment to behave as closely as possible to a regular build.

This only happens in Firefox.  For reference, it doesn't happen in TamperMonkey.

A simple example is attached.  Running it against https://ahcohhievaokoon.s3.amazonaws.com/testing.html logs "Loading" and "Loaded" (and the usual Firefox screaming about sync XHR), but the page never actually appears.  The tab keeps showing the loading icon.  This only happens with ViolentMonkey in Firefox, it doesn't affect TamperMonkey, or with VM in Chrome.

It's not critical for me for this to work since I do most of my development in Chrome, and I can test Firefox with TM, but it'd be nice to be able to quickly test all environments the same way.

This is with FF release 100, VM 2.13.0 in Windows 10.

[sync-xhr.user.js](https://github.com/violentmonkey/violentmonkey/files/8777539/sync-xhr.user.js.txt)

**Comment by tophf** [comment]
Assuming all your userscripts on this page are document-start, this is an old bug already fixed in beta. Try adding a dummy userscript for this page without `document-start`.

**Comment by tophf** [comment]
I confirm this is fixed in beta.
