### ISSUE TITLE
Script cannot run due to loss of native properties

### ISSUE THREAD

**Issue by rEnr3n** [violentmonkey/violentmonkey#151]
### What's the problem?
I can't run this script https://greasyfork.org/en/scripts/4369-ikariam-enhanced-ui/

### How to reproduce it?
1. Install the script
2. Reload the ikariam game page (need an account)

### Environment
- Browser: Inox (https://github.com/gcarq/inox-patchset/)
- Browser version: 59.0.3071.115
- Violentmonkey version: 2.7.1
- OS: Archlinux

**Comment by gera2ld** [comment]
The page has overridden some native functions, which breaks Violentmonkey.
