### ISSUE TITLE
[BUG] Violent monkey appearance in UI is a bit broken on android version of firefox

### ISSUE THREAD

**Issue by openwick** [violentmonkey/violentmonkey#1510]
Not really breaking bugs but visual ones. There are 2 visual bugs.

First one is when violentmonkey is added to a firefox collection and viewed in the browser section, the description is broken as shown in image below.
![Screenshot_2022-06-10-04-34-58-329_org mozilla fenix_1](https://user-images.githubusercontent.com/78715124/172960387-bc8c51db-d4dd-4732-bd09-960285eb7a05.jpg)
As you can see from image rest of the extensions descriptions are fine except for violent monkey one.

2nd bug is when extensions tab is selected for some reason tamper monkey name is not visible and extensions tab gets bigger as show in images below
![Screenshot_2022-06-10-04-35-56-328_org mozilla fenix_1](https://user-images.githubusercontent.com/78715124/172960553-89db366e-c521-4028-972f-17af22cb56c3.jpg)
![Screenshot_2022-06-10-04-38-39-845_us spotco fennec_dos_1](https://user-images.githubusercontent.com/78715124/172960567-11568a06-e6ea-4ad6-9f49-4d65ee9cdcd1.jpg)

As you can see from the images violent monkey has no name where as extensions like tamper monkey can even show which scripts are being used on that page which would be great.

These issues are found when extension is being used in nightly and fdroid fennec. Though functionally its not an issue visually its looks not ok hence this bug report.

**Comment by tophf** [comment]
As we investigated in #1249, it's a bug in Firefox: a translated name of the extension isn't shown.

**Comment by openwick** [comment]
I see it's a firefox bug but many other extensions I use don't seem to have the problem like tampermonkey alteast the display name. So does that mean if changing something in violent monkey code makes the name appear in second image @tophf ? 

I am sorry if this is a silly question to ask but please if u have time answer.

**Comment by tophf** [comment]
Adding a workaround for this bug in Firefox breaks our support for multiple languages in the name so it'll be wrong in Chinese which is currently 暴力猴 not Violentmonkey.
