### ISSUE TITLE
[BUG] GM.xmlHttpRequest hangs if started before window loaded complete (2.13.0.12+, FF)

### ISSUE THREAD

**Issue by ROpdebee** [violentmonkey/violentmonkey#1511]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Requests made through `GM.xmlHttpRequest` before the page is fully loaded can hang indefinitely with no callback being fired. `TypeError: can't access dead object` appears in the page console.

**To Reproduce**
```js
// ==UserScript==
// @name        Test script. 
// @namespace   Violentmonkey Scripts
// @match       https://musicbrainz.org/*
// @grant       none
// @version     1.0
// @author      -
// @description 12/06/2022, 12:27:47
// @grant       GM.xmlHttpRequest
// @run-at document-start
// ==/UserScript==


function reqLoop(times) {
  if (!times) {
    console.warn('done');
    return;
  }
  
  console.warn(`Requesting ${times}`);
  GM.xmlHttpRequest({
    url: `http://httpbin.org/200`,
    onload: (res) => {
      setTimeout((() => reqLoop(times - 1)), 100);
    },
    onerror: (res) => {
      console.error('ERROR');
      console.error(res);
    },
    ontimeout: (res) => {
      console.error('TIMEOUT');
      console.error(res);
    },
    onabort: (res) => {
      console.error('ABORT');
      console.error(res);
    },
  });
}

reqLoop(25);
```
Navigate to https://musicbrainz.org/ (or perhaps any other page that loads slowly and adjust the include pattern), check the console.

**Expected behavior**
For the repro above, it should print 25 times and then print "done", consistently; or at least print an error from one of the other callbacks.

**Actual behavior**
Inconsistent hanging, seemingly dependent on page load time. Oftentimes only the first warning is printed and no callbacks are invoked, sometimes it gets to the second iteration, very rarely it completes the full loop. One some Violentmonkey versions there's also a `TypeError` thrown: `TypeError: can't access dead object` ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object)), pointing to somewhere in the injected code.

This happens both for `@run-at document-start` and `@run-at document-end`, although for the former it happens more consistently, the latter succeeds more often. I've even seen it happen for `@run-at document-idle`, although more rarely. ~Doesn't seem to happen if the `reqLoop` call is placed in a `window` `load` event handler.~ Even waiting until the window is loaded is not enough, it can still hang after the `load` event has occurred.

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
This affects beta versions 2.13.0.12 – 2.13.0.19.
2.13.0.12 – 2.13.0.17: Type error is shown in the console.
2.13.0.18 – 2.13.0.19: No type error is shown in the console, but the requests still hang.

**Environment:**
- OS: macOS
- Browser: Firefox. Chrome does not seem to be affected.
- Browser Version: Nightly 103.0a1 (2022-06-10) (but also happened on older builds)
- Violentmonkey Version: BETA 2.13.0.12 – 2.13.0.19

**Additional context**
- The repro site is using React, so that might have something to do with it?
- I've verified that this still occurs when all other userscripts are disabled, but full disclosure, I didn't disable all other add-ons.
- #1255 seems related but that was already fixed well before 2.13.0.12. This could perhaps be a regression, but their repro case works fine for me.
- Originally discovered in https://github.com/ROpdebee/mb-userscripts/issues/465 on a script that runs at `document-end` and in a scenario wherein the script performs a bunch of requests near-immediately.
- For the record: Adding a timeout doesn't help either.

**Comment by tophf** [comment]
Should be fixed now.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/6897763571/artifacts/267604738)

**Comment by ROpdebee** [comment]
Can confirm that it seems to have been fixed, thanks!
