### ISSUE TITLE
[BUG] Can't play video from menu command click

### ISSUE THREAD

**Issue by Zipdox** [violentmonkey/violentmonkey#1513]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
When autoplay is blocked in the browser, a user interaction is required for the play() method to work on videos. But a callback specified in registerMenuCommand doesn't satisfy this requirement, resulting in this error:
```
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

**To Reproduce**
1. Disable autoplay in the browser settings
2. Install [this script](https://github.com/violentmonkey/violentmonkey/files/8934479/userscript.video.play.txt) or another script that tries to play a video.
3. Visit a web page that allows loading media from another domain (https://example.com/ works)
4. Click the Play command from the Violentmonkey menu

**Expected behavior**
The video gets added to the page and starts playing

**Actual behavior**
The video gets added to the page and doesn't start playing

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
I haven't tried but I'm pretty sure it's the same.

**Environment:**
- OS: Debian GNU/Linux bookworm/sid x86_64
- Browser: Firefox
- Browser Version: 100.0.2 (64-bit)
- Violentmonkey Version: 2.13.0

**Comment by tophf** [comment]
Unfortunately this is not implemented in the extensions platform. It doesn't carry the activation flag from the popup to the content script. Try opening a feature request on https://bugzil.la for Firefox and maybe also in https://crbug.com for Chrome.
