### ISSUE TITLE
[BUG] Violentmonkey doesn't update scripts from "auth" URLs

### ISSUE THREAD

**Issue by dumpsters** [violentmonkey/violentmonkey#1514]
Best way I know how to describe such URLs.

Take a script with the following, hosted on a private repository on bitbucket:
```
// @updateURL https://user:app_token@bitbucket.org/user/repo/raw/master/script.meta.js
// @downloadURL https://user:app_token@bitbucket.org/user/repo/raw/master/script.user.js
```
If you bump the version up on script.meta.js and click update in Greasemonkey, it will update. If you do the same in Violentmonkey it won't

**Expected behavior**
Update the script

**Actual behavior**
"Failed fetching update information."

**Environment:**
- OS: W10
- Browser: Firefox
- Browser Version: 91
- Violentmonkey Version: 2.13.0

**Comment by tophf** [comment]
Fixed in 6f7ef3c8.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/7055293772/artifacts/278074905).
