### ISSUE TITLE
[Feature] Add a switch to manually change between dark mode and light mode

### ISSUE THREAD

**Issue by youssef20031** [violentmonkey/violentmonkey#1515]
**Motivation**

Violent monkey is always set to light mode when i use resist fingerprinting in Firefox.

**Proposed Solution**

 Add a switch to manually change between dark mode and light mode.

**Comment by tophf** [comment]
This option is already implemented in [beta](https://github.com/violentmonkey/violentmonkey/releases):

![image](https://user-images.githubusercontent.com/1310400/175525891-3c432540-77ac-4c30-b98a-ee6b2312bf21.png)
