### ISSUE TITLE
[Feature] Request to add TypeScript definition files to provide better code assistance

### ISSUE THREAD

**Issue by viocha** [violentmonkey/violentmonkey#1516]
**Motivation**

 by introducing TypeScript definition files,the IDE can improve code completion, resolve symbols for an external library.

**Proposed Solution**

a simple example:
![image](https://user-images.githubusercontent.com/66580331/175755354-97ed18ad-705d-4741-99eb-e4cbd5b6a1a4.png)

reference:
https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute
https://www.jetbrains.com/help/webstorm/2022.1/configuring-javascript-libraries.html#ws_js_configure_libraries_ts_definition_files

**Use Cases**

usage in webstorm:
![image](https://user-images.githubusercontent.com/66580331/175754526-80be6afe-2eeb-4226-9486-507ab4c467c0.png)
![image](https://user-images.githubusercontent.com/66580331/175754532-1ba8ea5d-7a79-409a-8aff-b496ac11f697.png)
![image](https://user-images.githubusercontent.com/66580331/175754533-b3a7c7b5-0b23-4051-993f-9b445a316f0d.png)

**Comment by gera2ld** [comment]
Is this feature for userscript development only? Will [@types/tampermonkey](https://www.npmjs.com/package/@types/tampermonkey) help?

**Comment by viocha** [comment]
most of the popular libs have offered the ***@***.***/tampermonkey&nbsp; isn't a good solution,they don't have the completely same api




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月25日(星期六) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [violentmonkey/violentmonkey] [Feature] Request to add TypeScript definition files to provide better code assistance (Issue #1516)





 
Is this feature for userscript development only? Will @types/tampermonkey help?

**Comment by mataha** [comment]
I'm interested in making this work; how can I help?

**Comment by gera2ld** [comment]
Added in [@violentmonkey/types](https://github.com/violentmonkey/types).
Also updated in [generator-userscript](https://github.com/violentmonkey/generator-userscript).
