### ISSUE TITLE
[BUG] When browser language is Spanish, ViolentMonkey is still in English

### ISSUE THREAD

**Issue by Elaborendum** [violentmonkey/violentmonkey#1518]
- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
When selecting either European Spanish or Latin American Spanish, ViolentMonkey shows its interface in English, even when there is a complete Latin American Spanish translation available.

**To Reproduce**
1. Select either European Spanish (Spanish (ES)) or Latin American Spanish (in this case Spanish (MX)) as the main languages for Firefox
2. Install ViolentMonkey
3. See that its interface is in English

**Expected behavior**
The addon should show its interface in Spanish when either Spanish is selected as the main language in Firefox

**Actual behavior**
ViolentMonkey's interface is entirely in English

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Exactly the same happens

**Environment:**
- OS: Windows 10
- Browser: Firefox
- Browser Version: 101.0.1
- Violentmonkey Version: v2.13.0

**Additional context**
I'm not a dev, but from what I understood from #1389 is that this is somewhat of a Firefox issue. However, since the European Spanish translation is empty and the Latin American Spanish translation is 100% complete, maybe replacing the former with the latter could fix it on this side?

**Comment by tophf** [comment]
Weirdly, no one translated Violentmonkey into `es` Spanish yet, but we have `es_419` (Latin America).
Maybe you could help: https://www.transifex.com/violentmonkey/violentmonkey-nex/

**Comment by tophf** [comment]
Chrome correctly displays Violentmonkey in Spanish when I choose `español (México)` here so I don't understand how exactly to reproduce the problem. As for the translation I doubt we should combine anything because the proper solution is that someone who knows Spanish does it manually and having two separate similar languages isn't a problem in other projects.
