### ISSUE TITLE
Please consider moving IndexedDB to firefoxprofile/storage/permanent

### ISSUE THREAD

**Issue by curiosity-seeker** [violentmonkey/violentmonkey#152]
### What is the problem?
Violentmonkey is obviously using IndexedDB and is storing this data in `firefox-profile/storage/default`. Other add-ons that I'm aware of and Firefox itself are using the `.../storage/permanent` folder.

IndexedDB is used by many websites to track/fingerprint your browser. A [trick](https://github.com/mrdokenny/Cookie-AutoDelete/issues/44#issuecomment-312300461) to prevent this and, hence, to increase your privacy is to make the `default` and the `temporary` sub-folders read-only and leave the `permanent` subfolder read-write. Since Violentmonkey is using `default` this is no longer possible.

### How to reproduce it?
1. Make the `storage/default` subfolder read-only.
2. Start Firefox
3. Try to change settings and load scripts in Violentmonkey

### What is the expected result?
Settings should be saved and scripts loaded.

### What is the actual result?
Violentmonkey is unusable.

### Environment
- Browser: Firefox
- Browser version: 54
- Violentmonkey version: 2.6.3
- OS: Fedora 25

Please consider to use the `permanent` subfolder like other add-ons do.

**Comment by mrdokenny** [comment]
@gera2ld Ideally VM should use the [actual storage API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage) rather than using Web APIs
