### ISSUE TITLE
How can I use local (from my computer) images in my userscripts?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1533]
Because protocol `file://` is prohibited.

**Comment by tophf** [comment]
It's best to run any localhost web server and use an `http://localhost/foo/bar.jpg` URL.
A less secure alternative (not recommended) is to enable file access on `chrome://extensions` page in details of Violentmonkey.

**Comment by soviet-man** [comment]
I cant open `chrome://extensions` page

**Comment by tophf** [comment]
You probably have a malware extension that blocks opening this page. Try right-clicking Violentmonkey icon in the toolbar and choose "Manage extension".

**Comment by soviet-man** [comment]
Are you sure I can open `chrome://extensions page` in Firefox?

**Comment by tophf** [comment]
In Firefox extensions can't open file://

**Comment by soviet-man** [comment]
OK. How can I make `blob:` from local image to insert as `src`?
