### ISSUE TITLE
[BUG] GM.xmlhttpRequest finalUrl and statusText occasionally undefined

### ISSUE THREAD

**Issue by ROpdebee** [violentmonkey/violentmonkey#1536]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
This was reported by a user of one of my scripts, I cannot reproduce it myself but I managed to get some logs that show the problem. Sporadically, `GM.xmlhttpRequest`'s `onload` will be called with a response that has a `readyState: 4, status: 200`, but `finalUrl` is omitted entirely and `statusText` is an empty string. I haven't been able to determine a pattern or find out under which circumstances it occurs, and it occurs quite rarely.

**To Reproduce**
Here's a couple of confirmed URLs on which it has happened:
* https://f4.bcbits.com/img/a3563316698_0.jpg
* https://music.apple.com/gb/album/1582667542

However, it might not happen on these for everyone. It's very random: It just appears to happen on any URL, without any pattern.

**Expected behavior**
Since the request has completed and the status code is 200, I'd expect `finalUrl` to be defined and `statusText` to have a value.

**Actual behavior**
`finalUrl` is sometimes undefined, the property doesn't exist on the response. When that happens, it seems that `statusText` is also an empty string.

Some logs from my script to illustrate. Note that the logged response object is a copy of the original with `response`, `responseText`, and `responseHeaders` set to `null` to strip away any potentially sensitive information:

* First request made on a page, to https://music.apple.com/gb/album/1582667542. The TypeError is the result of the script constructing a `URL` from the `finalUrl`, which is undefined. The request had the `onload`, `onerror`, `onabort` and `ontimeout` handlers, but no timeout was set and no abort was triggered.
```
instrument.js:102 [mb_enhanced_cover_art_uploads] Searching for images in Apple Music release…
instrument.js:102 Response finalUrl is undefined
instrument.js:102 Response is {"responseHeaders":null,"readyState":4,"status":200,"statusText":"","lengthComputable":false,"loaded":413040,"total":0,"response":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Failed to fetch or enqueue images TypeError: Failed to construct 'URL': Invalid URL
    at MB： Enhanced Cover Art Uploads.user.js:106220:72
(anonymous) @ instrument.js:102
```

* A bunch of prior requests went fine, then one to https://f4.bcbits.com/img/a3563316698_0.jpg did not have the `finalUrl` and a later request also went fine. The setup of the request was more or less identical to the above, but this one also has an `onprogress` listener.
```
instrument.js:102 [mb_enhanced_cover_art_uploads] Fetching https://mikehuguenor.bandcamp.com/album/the-gateless-gate
instrument.js:102 [mb_enhanced_cover_art_uploads] Searching for images in Bandcamp release…
instrument.js:102 Response finalUrl is https://mikehuguenor.bandcamp.com/album/the-gateless-gate
instrument.js:102 Response is {"finalUrl":"https://mikehuguenor.bandcamp.com/album/the-gateless-gate","responseHeaders":null,"readyState":4,"status":200,"statusText":"OK","lengthComputable":false,"loaded":177341,"total":0,"response":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Checking for Bandcamp track images, this may take a few seconds…
instrument.js:102 Response finalUrl is https://mikehuguenor.bandcamp.com/track/the-gateless-gate
instrument.js:102 Response is {"finalUrl":"https://mikehuguenor.bandcamp.com/track/the-gateless-gate","responseHeaders":null,"readyState":4,"status":200,"statusText":"OK","lengthComputable":false,"loaded":144784,"total":0,"response":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Checking for Bandcamp track images, this may take a few seconds… (1/2)
instrument.js:102 Response finalUrl is https://mikehuguenor.bandcamp.com/track/mumons-commentary
instrument.js:102 Response is {"finalUrl":"https://mikehuguenor.bandcamp.com/track/mumons-commentary","responseHeaders":null,"readyState":4,"status":200,"statusText":"OK","lengthComputable":false,"loaded":144847,"total":0,"response":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Checking for Bandcamp track images, this may take a few seconds… (2/2)
instrument.js:102 [mb_enhanced_cover_art_uploads] Found no unique track images this time
instrument.js:102 [mb_enhanced_cover_art_uploads] Getting image dimensions for https://f4.bcbits.com/img/a3563316698_0.jpg
instrument.js:102 [mb_enhanced_cover_art_uploads] Found 1 image(s) in Bandcamp release
instrument.js:102 [mb_enhanced_cover_art_uploads] Fetching https://f4.bcbits.com/img/a3563316698_10.jpg (1/1)
instrument.js:102 Response finalUrl is undefined
instrument.js:102 Response is {"readyState":4,"status":200,"statusText":"","lengthComputable":true,"loaded":8958943,"total":8958943,"response":null,"responseHeaders":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Skipping maximised candidate https://f4.bcbits.com/img/a3563316698_0.jpg TypeError: Failed to construct 'URL': Invalid URL
    at MB： Enhanced Cover Art Uploads.user.js:110528:30
(anonymous) @ instrument.js:102
instrument.js:102 Response finalUrl is https://f4.bcbits.com/img/a3563316698_10.jpg
instrument.js:102 Response is {"finalUrl":"https://f4.bcbits.com/img/a3563316698_10.jpg","readyState":4,"status":200,"statusText":"","lengthComputable":true,"loaded":335879,"total":335879,"response":null,"responseHeaders":null,"responseText":null}
instrument.js:102 [mb_enhanced_cover_art_uploads] Successfully added 1 image(s)
```

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
This occurred in the current Beta release on Chrome, I'm not sure whether it happens on older versions.

**Environment:**
- OS: Unknown at this time, but I can try to find out if it could make a difference.
- Browser: Chrome
- Browser Version: 103.0.5060.132
- Violentmonkey Version: BETA 2.13.0.22

**Additional context**
I'll note again that I wasn't able to reproduce this myself, neither on Firefox with BETA 2.13.0.19 (a test build, I think), nor on the same Chrome version with the same VM version.

In lieu of reproduction code, here's [the implementation](https://github.com/ROpdebee/mb-userscripts/blob/c8d33a912a37f71bd094fbaba99ec3afed343a2b/src/lib/util/xhr.ts#L68) of the request function that's being used. In the first log, the affected request comes from [here](https://github.com/ROpdebee/mb-userscripts/blob/c8d33a912a37f71bd094fbaba99ec3afed343a2b/src/mb_enhanced_cover_art_uploads/providers/base.ts#L105), in the second, the affected request originates from [here](https://github.com/ROpdebee/mb-userscripts/blob/c8d33a912a37f71bd094fbaba99ec3afed343a2b/src/mb_enhanced_cover_art_uploads/fetch.ts#L207). The first request doesn't really do anything special, so I assume this behaviour can be triggered by any request.

I should note that although there's an additional layer of asynchronicity in that implementation, the logging of the response object in the logs above occurred directly in the `onload` listener as the very first statement. Here's the [transpiled implementation](https://gist.github.com/ROpdebee/a616e640abf270e7268f96dc7216ed43/0701096d70b0babb8be8b4f5e0e27bc17894e20a#file-mb_enhanced_cover_art_uploads-user-js-L1753) from which the log was generated.

I hope this is enough context to identify the problem. but I'll try to find out some more information as well.

**Comment by tophf** [comment]
finalUrl uses the url provided by webRequest API onBeforeSendHeaders event, so I guess there's a bug (possibly triggered by a presence of another extension) in Chrome that prevented Violentmonkey from seeing this event.

We can provide the original url in such cases.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/7578340741/artifacts/313521613).

I don't think we can do anything about statusText being empty though. It may be even the correct behavior in case the server is HTTP/2 because this protocol [does not support](https://fetch.spec.whatwg.org/#concept-response-status-message) status messages.

**Comment by ROpdebee** [comment]
Ah, I hadn't thought of potential conflicts with other extensions. That seems to be a plausible cause. Perhaps some other extension is sometimes stripping away the VM-Verify header, or maybe Chrome is reusing the details object and some other extension is erronously deleting the url property from it.

Personally though, I'd prefer finalUrl to be undefined if it cannot be correctly determined. I'm using finalUrl to reject responses that follow certain redirects. So at least in my case, it'd be better if I could emit a warning that a redirect may or may not have occurred. That could be a false positive, but I'd prefer that over a false negative. If someone else wanted finalUrl to be defined at all times, even if it can't be determined, they can just fall back on the original URL in their own code.

About statusText: I'm not using it, I just noticed it was empty when finalUrl is absent, but non-empty is finalUrl is present, and thought it was related.

**Comment by tophf** [comment]
I've switched to xhr's responseURL as a fallback now. Its only problem is that it doesn't preserve the #hash part.
