### ISSUE TITLE
[BUG] No support for non-Latin letters in userscript's name in debugger view

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1538]
This is how name of userscript looks like with cyrillic letters added to a name

![изображение](https://user-images.githubusercontent.com/33825590/181861626-dd9e9b7f-b99d-4999-8a49-6e58c4046337.png)

But it's only in debugger view.
In code window name displayed correctly.

**Comment by tophf** [comment]
It's a bug in Firefox.

Chrome shows them:

![image](https://user-images.githubusercontent.com/1310400/181876231-bced4ecd-2ccb-45fc-90fd-77cc62b21656.png)

**Comment by soviet-man** [comment]
It's not even wrong enconding, because semicolon and colon (which are part of standart ASCII) are displayed as doodles. The only symbols displayed correctly are latin letters, digits, dot and space.

**Comment by tophf** [comment]
https://bugzil.la/1782364

**Comment by tophf** [comment]
Fixed in FF 105.

**Comment by soviet-man** [comment]
> Fixed in FF 105.

Now it works fine 👍
