### ISSUE TITLE
[BUG] Cannot edit local http server script when Firefox HTTPS-Only Mode is enabled

### ISSUE THREAD

**Issue by kachelaqa** [violentmonkey/violentmonkey#1542]
This is using Firefox-103.0 and VM-2.13.0

When Firefox HTTPS-Only Mode is enabled, I cannot open a script in VM via a local http web-server ***even if an exception is added for the relevant domain***.

So, from the VM dashboard, I open the homepage for an installed script (e.g. `http://mydomain.org/scripts`). With HTTPS-Only Mode _disabled_ in Firefox, this will allow loading `user.js` files with the VM extension and I can confirm installation. But if I enable HTTPS-Only, the files will just load as an ordinary read-only page in Firefox. I have tried adding an exception in various ways (all of which show up correctly in the Firefox settings), but this makes no difference. Somehow, with HTTPS-Only Mode enabled, VM just won't recognise my scripts anymore. Oddly, when I had the old HTTPS-Only add-on installed, I never had this issue. It's only the new Firefox feature that seems to cause the problem.

I assume something must be fixed in VM to avoid this issue, but if anyone knows of a work-around, that would also be helpful. I don't really want to go to all the hassle of enabling https, as I only need this for local development at the moment. Of course, I can just temporarily switch off HTTPS-Only Mode whenever I need to confirm installation, but it would be nice not to have to do this all the time.

**Comment by tophf** [comment]
Please try Violentmonkey [beta](https://github.com/violentmonkey/violentmonkey/releases). I think this was fixed some time ago.

**Comment by tophf** [comment]
It's a bug in Firefox: the customized exceptions are not applied to requests made by extensions.

**Comment by kachelaqa** [comment]
@tophf Thanks for the confirmation and info. Now that I know the cause, I will just wait for the fix in Firefox.

Regarding the workaround: do you mean that it literally has to be exactly `localhost`? (I'm already using a local server).

**Comment by tophf** [comment]
Yes, literal `localhost` works.
