### ISSUE TITLE
[BUG] Missing extension name in Add-ons popup

### ISSUE THREAD

**Issue by cunlem** [violentmonkey/violentmonkey#1545]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

![vmonkey2](https://user-images.githubusercontent.com/87859114/183284552-ffb76db2-c823-4f3c-8d3c-056b7ce6ce29.jpg)

**To Reproduce**

1. Open ⋮> Add-ons

**Expected behavior**

Extension name is displayed

**Actual behavior**

Extension name is not displayed

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**

Not tested

**Environment:**
- OS: Android
- Browser: Fennec F-Droid
- Browser Version: 103.1
- Violentmonkey Version: 2.13

**Comment by tophf** [comment]
As we investigated in https://github.com/violentmonkey/violentmonkey/issues/1249, it's a bug in Firefox: a translated name of the extension isn't shown. Adding a workaround for this bug in Firefox breaks our support for multiple languages in the name so it'll be wrong in Chinese which is currently 暴力猴 not Violentmonkey.
