### ISSUE TITLE
I need to launch function on webpage close. Can I register such handler/listener?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1549]
...

**Comment by tophf** [comment]
No. When the page closes, everything is destroyed, nothing can run there. You can run something just before closing: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by soviet-man** [comment]
When browser closes `beforeunload` event doesn not work! It works only when tab is closed.

**Comment by tophf** [comment]
That's how browsers behave, nothing we can do about it.

**Comment by soviet-man** [comment]
I want to handle moment when userscript doesnt work anymore so I can note it in storage with `GM_setValue`

**Comment by tophf** [comment]
Well, it depends on what the "work" exactly is. You can try opening a new discussion or ask for advice on a forum.
