### ISSUE TITLE
Broken since 2017-07-10 FF nightly.

### ISSUE THREAD

**Issue by Betsy25** [violentmonkey/violentmonkey#155]
### What is the problem?
Violentmonkey is no longer working since 2017-10-07 Firefox nightly.
The toolbar icon is there but just flash instead of opening upon clicking & the scripts seems to be non-working. To be specific, they don't work upon loading the page it should target, but only kick in after refreshing the page after loading.

Multiprocess = Enabled.
dom.ipc.processCount = 2
dom.ipc.processCount.extension = 1

- Browser: FF x86 nightly 20170711
- Browser version: 56a1
- Violentmonkey version: 2.6.3
- OS: Win7 x64

**Comment by mrdokenny** [comment]
@Betsy25 I'm pretty sure this is a FF bug ever since OOP extensions has been enabled a few days ago.

https://bugzilla.mozilla.org/show_bug.cgi?id=1190679

>The toolbar icon is there but just flash instead of opening upon clicking

I do experience this with my own extension but it's unpredictable for me so I can't file a bug on bugzilla yet.

> they don't work upon loading the page it should target, but only kick in after refreshing the page after loading.

If it works after setting `extensions.webextensions.remote` to false, then I recommend filing a bug on bugzilla and blocking 1190679.

**Comment by Betsy25** [comment]
> If it works after setting extensions.webextensions.remote to false, then I recommend filing a bug on bugzilla and blocking 1190679.
Thanks for chiming in mrdokenny,

I've tried setting `extensions.webextensions.remote` to false & browser restart, problem continues. The toolbar icon appears to work correctly, however the scripts only fire random, like once every 2 times they should have fired.
Tried changing values for `dom.ipc.processCount.extension` & browser restart, still the same problem as above.

**Comment by gera2ld** [comment]
Does this still happen in Firefox v57 with Violentmonkey [v2.8.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.8.7)?

**Comment by Betsy25** [comment]
Hi gera2ld, I'm sorry to say but with the latest v2.8.7 on the latest Firefox nightly, the script still doesn't work, and now doesn't even work anymore after manually refreshing the page either.

**Comment by gera2ld** [comment]
Some scripts do not work on certain sites due to CSP issue on Firefox, which is a known issue.
So I want to make sure whether the extension itself is working. I guess it worked since the badge number was shown. Did the popup menu show when clicked on the icon?

**Comment by Betsy25** [comment]
Yes, the icon popup menu came up just fine. And showed that the script was running when on the tab where a script should run.

**Comment by gera2ld** [comment]
OK, then it may be related with #173
