### ISSUE TITLE
[Feature] Add local naming to scripts

### ISSUE THREAD

**Issue by xushet** [violentmonkey/violentmonkey#1550]
**Motivation**

No
**Proposed Solution**

Display custom naming in the script management interface and web page pop-ups
**Use Cases**

Add custom names to scripts for identification, such as script names in other national languages

**Comment by tophf** [comment]
It's already implemented in editor for a script:

![image](https://user-images.githubusercontent.com/1310400/184875133-6e0a5f44-c955-44af-a19b-01f81eac1b7b.png)
