### ISSUE TITLE
[BUG] GM_setValue not working

### ISSUE THREAD

**Issue by peasoft** [violentmonkey/violentmonkey#1551]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
1. ~I can edit but **cannot** save any data of the scripts by `Settings -> Edit script -> Data`. I lost all changes when I reload the page.~
2. `GM_setValue` does not work.
3. Sometimes it works, but very few times.

**To Reproduce**
1. The script runs `GM_setValue`.
2. Nothing happened, the data didn't change.

**Expected behavior**
The data should be changed.

**Actual behavior**
The data didn't change.

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
This is the newest release now.

**Environment:**
- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: 104.0.1293.7
- Violentmonkey Version: BETA v2.13.0.25

**Additional context**
This problem was found in stable v2.13.0 too.

**Comment by tophf** [comment]
Works for me. Please open devtools (F12 key) and check `console`. Also go to `edge://extensions`, enable "Developer mode" switch on the left, click "Background page" in Violentmonkey entry and check console there as well.

**Comment by peasoft** [comment]
It works today, but yesterday it didn't work. Maybe it is a random problem.

**Comment by MarvNC** [comment]
Having the same issue here, `GM_setValue` and `GM_getValue` are very inconsistent, often the value fetched by the userscript does not match with what can be seen in the `Data` panel and `GM_setValue` often does not seem to actually save anything.

I didn't see any errors in console of the extension page or in `background/index.html`.

**Comment by MarvNC** [comment]
Here is a video demonstrating such, the data does not remain after refresh. 

https://user-images.githubusercontent.com/17340496/186522224-f4c595ba-9876-49cc-8133-0307a2657f1b.mp4

But then a few minutes later, it might show up. Changes in the userscript seem to work similarly unpredictably; if I try to save some settings using `GM_setValue` they will not be reflected until some time later.

**Comment by tophf** [comment]
Unfortunately, the video doesn't help. I guess there's a bug in the old Violentmonkey you're using. Try using the new [beta](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by peasoft** [comment]
This bug still exists in the latest beta.

**Comment by tophf** [comment]
> Also go to `edge://extensions`, enable "Developer mode" switch on the left, click "Background page" in Violentmonkey entry and check console there as well.

**Comment by peasoft** [comment]
Nothing in the console.

**Comment by tophf** [comment]
Please show your userscript.

**Comment by peasoft** [comment]
1. https://github.com/XIU2/UserScript/blob/master/52pojie-Enhanced.user.js
2. https://www.baiduyun.wiki/instantpage.user.js
3. https://www.baiduyun.wiki/panlinker.user.js
4. Other scripts with `GM_setValue`

The scripts are written in Chinese.

**Comment by tophf** [comment]
Works for me. What exactly should I do or click to replicate the problem?

**Comment by tophf** [comment]
Please also try in a different browser, maybe Chrome or Chrome Canary. You can use a portable app installer.

**Comment by peasoft** [comment]
It works on Chrome, but not Edge.

**Comment by tophf** [comment]
Aha! Sounds like a bug in Edge then...

**Comment by peasoft** [comment]
> Is it a bug only in Edge?

Today I found my test on Chrome may be wrong. `GM_setValue` only failed after you run your browser for a long time, but I only test it for a few minutes on Chrome. So we need more information from Chrome.
Reproducing it is very hard. I think it is a bug in the code, but we didn't noticed it.

**Comment by tophf** [comment]
Sorry, nothing we can do without an exact sequence of actions that replicates the problem.
