### ISSUE TITLE
[BUG] Sync to Dropbox: Initializing error!

### ISSUE THREAD

**Issue by cunlem** [violentmonkey/violentmonkey#1552]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Some time successful authorization Violentmonkey loses access to Dropbox and requires reauthorization. The error displayed is `Initializing error!`. After clicking Authorize and logging into Dropbox the access is restored (until the error reoccurs).

![sync](https://user-images.githubusercontent.com/87859114/185455826-71d24512-5d9f-46a3-a5dd-23bf5aa0cc6c.png)

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Configure Sync to Dropbox, sync data
2. Wait...
3. `Initializing error!`

**Expected behavior**
Once configured sync to Dropbox continues to work

**Actual behavior**
Reauthorization is required

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Not tested

**Environment:**
- OS: Ubuntu 20.04
- Browser: Firefox
- Browser Version: 103
- Violentmonkey Version: 2.13

**Additional context**
No errors in console

**Comment by cunlem** [comment]
Thanks I've installed beta on desktop and will test it. Unfortunately I can't do this on the phone because AFAIK Firefox doesn't support loading extensions from file on Android (it would be great to have beta published on AMO)

**Comment by tophf** [comment]
AMO doesn't support beta extensions anymore.

**Comment by cunlem** [comment]
Ok same thing happened with v2.13.0.24. Had to reauthorize after some time:
![signin-dropbox](https://user-images.githubusercontent.com/87859114/185513042-c33c5d73-301d-48dc-af26-bbfc203e2302.png)

**Comment by tophf** [comment]
It means login wasn't successful.

1. Maybe you have another extension that manages privacy or cookies? 
2. Alternatively, if your global cookie preference is to block cookies, you need to add an exception for dropbox.
3. Try clearing site data: go to dropbox.com, open devtools (F12 key), go to Application, then Storage, then "Clear site data".

**Comment by cunlem** [comment]
> 1. Maybe you have another extension that manages privacy or cookies?

UBlock Origin maybe. I also have "Delete cookies and site data when Firefox is closed" preference enabled. But the error happens without closing the browser. I also have `privacy.resistFingerprinting` config option enabled.

> 2\. Alternatively, if your global cookie preference is to block cookies, you need to add an exception for dropbox.

Firefox blocks some tracking cookies (Enhanced Tracking Protection: Strict) otherwise cookies are enabled and I'm able to login and maintain sessions on all sites.

> 3\. Try clearing site data: go to dropbox.com, open devtools (F12 key), go to Application, then Storage, then "Clear site data".

I've cleared dropbox.com cookies from Settings > Cookies and Site Data > Manage Data. But they are cleared regularly when browser closes with few exceptions. I can add Allow exception for dropbox.com if this is needed

**Comment by tophf** [comment]
I can't reproduce the problem with this config.

**Comment by tophf** [comment]
Check the [background console](https://extensionworkshop.com/documentation/develop/debugging/) please.

**Comment by cunlem** [comment]
There is an `401 Unauthorized` error in console from endpoint

https://api.dropboxapi.com/2/users/get_current_account

```json
{"error_summary": "expired_access_token/", "error": {".tag": "expired_access_token"}}
```
How long is the dropbox OAuth token valid for? Should it be refreshed?

**Comment by gera2ld** [comment]
This is the expected behavior for now. It seems that Dropbox has updated their OAuth2 support, and we need to make some changes accordingly.

**Comment by tophf** [comment]
We also should probably display the error json in UI...

**Comment by gera2ld** [comment]
> We also should probably display the error json in UI...

Right, we should at least distinguish between network errors and login errors.
