### ISSUE TITLE
[Feature] Manifest V3

### ISSUE THREAD

**Issue by FlowerForWar** [violentmonkey/violentmonkey#1555]
Is there a plan to update the extension to support Manifest V3?

And more importantly, will the extension be affected by the changes made by Manifest V3?

Edit: Almost all my extensions are Manifest V2, and yet to be updated. Doesn't everyone realize that if they are not updated in few months, we will not be using extensions?!

**Comment by tophf** [comment]
ManifestV3 doesn't yet allow userscripts, so we can't even start migrating. No one knows when it'll be allowed. Anyway, ManifestV3 is a complete disaster, so expect the worst.

**Comment by FlowerForWar** [comment]
At least now I know, thank you.
