### ISSUE TITLE
[BUG] HTTP 400 error when using Dropbox sync on Beta 

### ISSUE THREAD

**Issue by fireattack** [violentmonkey/violentmonkey#1556]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

I just switched from stable to beta. When I click authorize for Dropbox sync, it shows 

```
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.


More details for developers
Invalid client_id: "undefined".
```

![image](https://user-images.githubusercontent.com/4130991/187342898-ba0e79b2-2fdb-418e-bab8-69019030c061.png)

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Go to settings.
2. Click "authorize" here: 
![image](https://user-images.githubusercontent.com/4130991/187342940-9a307fb6-979a-4104-97e0-299fa5fd297c.png)

**Environment:**
- OS: [e.g. macOS] Windows
- Browser: [e.g. chrome, safari] Chrome 
- Browser Version: [e.g. 22] 104.0.5112.102
- Violentmonkey Version: 2.13.0.25, Updated August 24, 2022

**Additional context**
I see the old issue #1552, but I assume the current version is after #1553 fix is applied.

**Comment by tophf** [comment]
Fixed in 9966f314, will be released in new beta soon.
