### ISSUE TITLE
[BUG] The "require" storage is missing .. no way to find the culprit 

### ISSUE THREAD

**Issue by fireattack** [violentmonkey/violentmonkey#1557]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
After installing the beta version and importing all my old scripts, I constantly get this error message:

![VM](https://user-images.githubusercontent.com/4130991/187398132-8cb4b877-1f48-47a8-a5ee-6d88dbe42b9a.png)

I don't know what it means, but more importantly, I don't know which script is causing this, clicking the notification does nothing. (I can't even see the full js URL in the notification, as you can see).

**Environment:**
- OS: [e.g. macOS] Windows
- Browser: [e.g. chrome, safari] Chrome
- Browser Version: [e.g. 22] 104.0.5112.102
- Violentmonkey Version: 2.13.0.25, Updated August 24, 2022

**Comment by tophf** [comment]
Yeah, we should show the names of the affected scripts.

Meanwhile, you can probably hover the notification to see the full https:// URL, then paste it in the search field in Violentmonkey dashboard:
![image](https://user-images.githubusercontent.com/1310400/187408442-3c20e7f6-85e9-4018-989e-10b594d555c0.png)

**Comment by tophf** [comment]
Ah, you can see the full URL in the [background console](https://stackoverflow.com/a/10258029).

**Comment by fireattack** [comment]
Thanks. Probably can make clicking it to jump to the script like #1175?

**Comment by tophf** [comment]
fixed in 01541c12

**Comment by heywolf15** [comment]
I'm using Firefox and clicking the notif didn't do anything
