### ISSUE TITLE
[Feature] Autocomplete for VM editor

### ISSUE THREAD

**Issue by byzod** [violentmonkey/violentmonkey#1559]
**Motivation**

[Firefox dose not support local URI yet,](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/#known-issues) using local editor is not so easy. 
Default editor of VM is good, but it lack one thing: autocomplete

**Default Editor Now**
![An1](https://user-images.githubusercontent.com/848607/188260443-481d8901-8f41-442a-b06a-04a5bbf1aca7.gif)

**Default Editor After (hopefully)**
(Actually a demo of firefox console)

![An2](https://user-images.githubusercontent.com/848607/188260446-a461ea16-1cc2-45f5-87af-90a14ff6c9f1.gif)

**Use Cases**

It will be very convenient and useful for user like me who is not native english speaker and not very good at high-tech things like deploy local http server and connect it to VM

I found [something available](https://github.com/codemirror/autocomplete) btw  (not sure if it's suitable)

**Comment by tophf** [comment]
1. We implemented a workaround for local file:// URLs in [beta](https://github.com/violentmonkey/violentmonkey/releases) so using an external editor is easy.
2. We have autocomplete but it works only for JavaScript methods like forEach and words that are already present in the script. I guess we should add the most popular DOM globals like `document` or `querySelector` manually as I don't see such plugin for CodeMirror5.

**Comment by tophf** [comment]
Actually, we already have autocomplete for DOM in beta, but it doesn't work on-the-fly, you need to press Ctrl-Space.

**Comment by byzod** [comment]
> 1. We implemented a workaround for local file:// URLs in [beta](https://github.com/violentmonkey/violentmonkey/releases) so using an external editor is easy.

Cool, but I installed the latest beta version but didn't found any new feature related to local file, is there any detailed instruction?

> Actually, we already have autocomplete for everything including DOM, but it doesn't work on-the-fly, you need to press Ctrl-Space.

That's nice, but press a combination of keys for every word to open autocomplete is hard to use tbh...I think that's called `word suggestion` or something since it's not auto at all :D. Mabye there will be an option for this editor like `autocompleteOnTheFly: true`?

Another thing, `ctrl+space` is conflict with the default hotkey for switching input method (basically only a thing for CJK user but that's essential), so I need to press like 10 keys combination in total to trigger auto...suggestion for a word and repeat again for the next word....in conclusion, it's not usable for CJK user :(

**Comment by tophf** [comment]
> is there any detailed instruction

It just works as usual. Simply drag'n'drop the local file with `.user.js` extension in the file name onto the browser tab strip and enable "Track local file before this window is closed" option.

> autocompleteOnTheFly

Yeah, I've already started working on it.

> Ctrl-Space conflict

You can fix it like this: open Violentmonkey editor, open devtools console (F12 key or Ctrl-Shift-I), paste `delete (keys=$('.CodeMirror').CodeMirror.options.extraKeys)['Ctrl-Space']; keys['Insert']='autocomplete'` and press the Enter key. This example assign the `Insert` key.

**Comment by byzod** [comment]
> It just works as usual. Simply drag'n'drop the local file with `.user.js` extension in the file name onto the browser tab strip and enable "Track local file before this window is closed" option.

Uhh if it's that one, I tested it. If I read it correctly, you can edit local file while the install page is open and that's the first and last window to edit it, any future development after you (on purpose or by accident) close that page is only available in default editor, the local .user.js has nothing to do with script with the same name in firefox anymore? 


That sounds very limited for me :/

I hope [bug1266960](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960) got a decent fix soon

btw that `Track local file before this window is closed` thing also not working when I tested with [BETA v2.13.0.26](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.26)

> Yeah, I've already started working on it.

Bravo! 👍 


> You can fix it like this: open Violentmonkey editor, open devtools console (F12 key or Ctrl-Shift-I), paste `delete (keys=$('.CodeMirror').CodeMirror.options.extraKeys)['Ctrl-Space']; keys['Insert']='autocomplete'` and press the Enter key. This example assign the `Insert` key.

Cool, is there any way to automated this?

**Comment by tophf** [comment]
> That sounds very limited for me :/

I don't understand. As long as your script has the `@name` and `@namespace` you can open the local installer as many times as you want. This is how local editing was always implemented. The only difference in beta is that it opens the second tab with the source file to circumvent the restriction in Firefox. 

> any way to automated

No.

**Comment by byzod** [comment]
> > That sounds very limited for me :/
> 
> I don't understand. As long as your script has the `@name` and `@namespace` you can open the local installer as many times as you want. This is how local editing was always implemented. The only difference in beta is that it opens the second tab with the source file to circumvent the restriction in Firefox.

So the correctly progress is
1. Create local `demo.user.js` file
2. Drag it into firefox and check the track setting
3. Do not close the install tab until finished editing
4. Drag it in again when you need to edit it, by overwritting installed one and open track mode again while install page opened

Like this?

Then that's much more practical :D

**Comment by tophf** [comment]
Yes.

**Comment by byzod** [comment]
Thanks for the autocomplete on the fly :D
