### ISSUE TITLE
[Feature] Ability to exclude all subframes on specified URLs

### ISSUE THREAD

**Issue by pointydev** [violentmonkey/violentmonkey#1561]
**Motivation**
I am attempting to use the [DAA's WebChoices](https://optout.aboutads.info/) tool to opt-out of targeted advertising in the event that disabling 3p cookies doesn't work. Due to the amount of requests being made (500+), Violentmonkey is being killed on my machine with [`SIGILL`](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGILL) for some reason, likely due to the fact one of my scripts is set to run on all URLs.

**Proposed Solution**
The ability to exclude scripts from running in subframes of documents on specified URLs.

**Use Cases**
I would use this feature to block scripts from running in subframes on the above listed site, therefore (most likely) preventing the extension from crashing and having to be reloaded for the entire browser.

Thanks,
Elliott

**Comment by tophf** [comment]
There are two related exclusion mechanisms: `@noframes` and `@exclude`/`@exclude-match`, which can be specified in metadata or in the editor's settings for the script.

We won't add a third nonstandard mechanism unless it's also implemented in Tampermonkey or a few other popular engines.

You can try to exclude these iframes by URLs if they contain a telltale part.

What we can do is help with investigating the cause of the crash though. First, try using [beta](https://github.com/violentmonkey/violentmonkey/releases). Then try [enabling verbose logging](https://www.chromium.org/for-testers/enable-logging/). Then try building a DEBUG build of Violentmonkey or we'll build one for you.

**Comment by pointydev** [comment]
> First, try using [beta](https://github.com/violentmonkey/violentmonkey/releases).

I was already using beta 2.13.0.26 from the Chrome Web Store, which is what I was using when the crashes occured.

> Then try [enabling verbose logging](https://www.chromium.org/for-testers/enable-logging/).

This issue isn't very reproducable and I couldn't get it to occur while logging, but here're [some logs](https://violentmonkey.is-serious.business/85MmMP5.txt) regardless.

**Comment by tophf** [comment]
Nothing stands out in the log to me. Maybe some of your scripts is causing the crash?

**Comment by pointydev** [comment]
I'm thinking it's probably [Image Max URL](https://github.com/qsniyg/maxurl) as that was the script running in the subframes I made the issue about. It's possible I may need to test in a clean browser to ensure the opt-out site is making *all* possible requests instead of ones that are left over after previous runs.

On an unrelated note, I also tried building the extension myself (CI artifacts work fine) but ran into this:
```js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/pointy/tools/chromeunpacked/violentmonkey/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/pointy/tools/chromeunpacked/violentmonkey/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/pointy/tools/chromeunpacked/violentmonkey/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/pointy/tools/chromeunpacked/violentmonkey/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/pointy/tools/chromeunpacked/violentmonkey/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/pointy/tools/chromeunpacked/violentmonkey/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by tophf** [comment]
IIRC that error means you need to set NODE_OPTIONS=--openssl-legacy-provider.
Here's my debug build: 
[Violentmonkey-debug.zip](https://github.com/violentmonkey/violentmonkey/files/9491556/Violentmonkey-debug.zip)
