### ISSUE TITLE
Data vacuumed error if "// @require" empty

### ISSUE THREAD

**Issue by raingart** [violentmonkey/violentmonkey#1568]
error massage:
![Screenshot_4](https://user-images.githubusercontent.com/13064767/190915468-b8487cb9-5dd2-4c92-8690-464a4123ce42.png)

![Screenshot_1](https://user-images.githubusercontent.com/13064767/190915663-12f22b09-9011-49bf-bfcb-39ac3c4fa099.png)

script:
https://greasyfork.org/en/scripts/375216-block-opensearch-descriptions/code

error reason incorrect declaration // @require
Possibly related to sync.

**Comment by gera2ld** [comment]
I think the error message is clear enough. The script has defined an empty `@require`. Maybe you should report the issue to the script author.

**Comment by raingart** [comment]
I agree that this is a mistake of the author. But imagine that I am a dumb user. 

Why does ViolentMonkey periodically notify about this?
And without specifying which script it refers to. 
It was my desire and time to figure it out and find the reason and let you know. But that doesn't mean others can.

There were no such messages in the previous version of ViolentMonkey.

I would hide such messages. And ignored empty declaration `@someting`

**Comment by tophf** [comment]
You see this message because vacuuming runs automatically now. We probably never encountered such a script ourselves, which is why our code didn't handle it well. Since it's certainly a rare situation, an edge case, and Tampermonkey doesn't care about empty deps, I guess we can ignore it too: ec46b111.

**Comment by raingart** [comment]
@tophf  Thanks for listening to me.
Just a notification in the corner of the screen is not informative enough (capacious).

Making changes in the script is not the prerogative of the user. And if the error is not significant, then it should be ignored. 
I think it's important to report it to the editor. And not the user who installed the script.

I absolutely agree that the scenario is atypical. But he is existing. There and other items are empty. For example:
```
// @author
// @downloadURL
// @grant
// @icon
```
I think they are worth checking out too.

**Comment by raingart** [comment]
also I'm not sure if it's worth checking the possibility for example `@icon` to insert a js file or gif. Or a malicious request
```
// ==UserScript==
// @name          New script
// @icon            https://c.tenor.com/4ceD4nmGZsgAAAAM/you-can-do-it-school.gif
// @namespace     Violentmonkey Scripts
// @version       0.1
// @description   9/18/2022, 9:04:39 PM
// @author        raingart <test@test.com>
// @include       *://*/*
// @run-at        document-end
// @noframes

// ==/UserScript==
/*jshint esversion: 6 */
alert(1)
```
it is clear that these are strange options. But for example, an unnecessarily large gif file is read. Perhaps you should introduce a limit on the file size, and resolution.

**Comment by raingart** [comment]
I'm unsure of the need for one more feature. But maybe it's worth adding the ability and the author's nickname to add not only email but like url.
```
// @author        violentmonkey <https://github.com/violentmonkey/>
```

**Comment by tophf** [comment]
> other items are empty

Doesn't seem to cause any problems.

> I'm not sure if it's worth checking the possibility for example @icon to insert a js file 

No such possibility.

> unnecessarily large gif file

I don't think we should limit it, but we can scale it down to 128x128px and use just one frame before caching. I don't want to implement it  though without seeing a popular script that uses such an icon.

> Or a malicious request

The browser already detects it and cancels.

> add not only email but like url.

This is what `@homepage` or `@homepageURL` does already. We can't just invent things in the established userscript syntax. What we can do, is to use `@namespace` with a URL as homepage when no `@homepageURL` is specified. There's also `@website` supported by Tampermonkey and used by 115 scripts on GreasyFork, so we'll handle it too.
