### ISSUE TITLE
Whitelist support missing

### ISSUE THREAD

**Issue by therealmarv** [violentmonkey/violentmonkey#157]
### What is the problem?
We have a blacklist but no whitelist. I tried to simulate a whitelist but it seems it's not possible right now.

For me a missing whitelist is a security risk. I don't want my auto updated JS lists to inject JS on sites I don't allow it explicitly.

Whitelisting certain domains was for me essential on Tampermonkey.

What would also work for me:
Blacklist all except certain domains (I thought `@except` is doing that but it's not). So maybe add `@include` ?

**Comment by gera2ld** [comment]
It is confusing to have both blacklist and whitelist, because we cannot tell which list to trust if both matched.

We can add `@include` and `@match` for your cases.

**Comment by therealmarv** [comment]
A simple switch between a whitelist and blacklist could work?

I agree that to have both (white and black-)lists enabled is bad design and confusing (Tampermonkey allows that but I don't like Tampermonkey on that specific thing).

**Comment by therealmarv** [comment]
big thanks to this @gera2ld . I get a whitelist working now with adding whitelist items first with `@match` and/or `@include` and adding a general blacklist at the end:

```
*://*/*
```

Screenshot instructions:
![image](https://user-images.githubusercontent.com/1050582/29451548-5b3550f4-8403-11e7-8a9f-c48332c7d6c0.png)

Very happy and thanks again! Now I can use Violentmonkey :)
