### ISSUE TITLE
[BUG] bump minimum_chrome_version

### ISSUE THREAD

**Issue by Arnie97** [violentmonkey/violentmonkey#1579]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Albeit `manifest.yml` declares `minimum_chrome_version: '55.0'`, the latest release `2.13.1` no longer works in Chrome 70.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Install / upgrade to the latest Violentmonkey version from the Chrome Web Store.

**Expected behavior**
Legacy browsers should be blocked from incompatible new versions.

**Actual behavior**
Chrome 70 silently upgraded Violentmonkey from 2.13.0 to 2.13.1 five days ago.
After the upgrade, all user scripts no longer run on any site, just like if the site domain did not match the script header.

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
WARNING! Do an export in settings before testing!

**Environment:**
- OS: macOS
- Browser: chrome
- Browser Version: 70.0.3538.77
- Violentmonkey Version: 2.13.1

**Comment by tophf** [comment]
It's already fixed in Violentmonkey beta, now it works again in Chrome 55, I've just verified it.
One problem though: import/export doesn't work due to the use of globalThis in zipjs library, gonna fix it now.
