### ISSUE TITLE
Dropbox/OneDrive Sync Error..

### ISSUE THREAD

**Issue by JourneyOver** [violentmonkey/violentmonkey#158]
### What is the problem?

Any time I try to sync to either dropbox or onedrive I get a sync error.

### How to reproduce it?
1. Open up violentmonkey
2. go to settings
3. choose one of the sync options
4. watch it fail to sync correctly

### What is the expected result?

For it to sync to either dropbox or onedrive correctly.

### What is the actual result?

When it goes to sync it always ends up producing a failed sync. 

These are the console outputs for both Dropbox and OneDrive 

http://i.imgur.com/KIxCzZC.png

### Environment
- Browser: Chrome 64-bit
- Browser version: Doesn't seem to make a difference as all versions of chrome are failing this.
- Violentmonkey version: 2.7.1
- OS: Windows 10 x64 bit

**Comment by ygfly** [comment]
我的也是同步失败，看来是共性问题了。

**Comment by gera2ld** [comment]
The dropbox issue seems to be with [babili](https://github.com/babel/babili). I've just compressed the code with the latest version and it seems correct now.
