### ISSUE TITLE
Some run-at make require loading crash

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1581]
Following ***Uncaught (in promise) ReferenceError: <function_from_@require_directive> is not defined*** #1580

---

Is it a new bug that some values of `@run-at` will cause the script to not load `@require` library at run time?

```js
// ==UserScript==
// @name         New NG script
// @require      https://github.com/jesus2099/konami-command/raw/de88f870c0e6c633e02f32695e32c4f50329fc3e/lib/SUPER.js?version=2022.3.24.224
// ==/UserScript==
"use strict";
console.log("NEW NG SCRIPT");
createTag("span", {}, "test");
```
![image](https://user-images.githubusercontent.com/1401086/191765853-25b1a458-cb0d-4536-bc79-9afb86612d11.png)

**This does not work**, the SUPER.js code is not append.
I also tried `// @run-at       document-ready` and `// @run-at       document-idle` both no good (NG), as well.

```js
// ==UserScript==
// @name         New OK script
// @require      https://github.com/jesus2099/konami-command/raw/de88f870c0e6c633e02f32695e32c4f50329fc3e/lib/SUPER.js?version=2022.3.24.224
// @run-at       document-start
// ==/UserScript==
"use strict";
console.log("NEW OK SCRIPT");
createTag("span", {}, "test");
```

![image](https://user-images.githubusercontent.com/1401086/191765802-6ce8e944-af49-4f17-b5f0-8f372823fbf9.png)

**This works** with `// @run-at       document-start` !?

Other values than `document-start` are blocking the `@require` loading.

**Comment by jesus2099** [comment]
For the moment I just used the internal user script editor to reproduce successfully (`// @ run-at document-start` OK / anything else NG, KO).

But I will make a zip file with test cases in order to test more easily in many browsers.

Please cope with my lowliness doing so, I have just had my laptop reset and you can imagine I encounter many other issues for many other things.

**Comment by jesus2099** [comment]
As soon as I have interesting new from [my own ticket](https://github.com/jesus2099/konami-command/issues/708), I will come back here and say.

**Comment by tophf** [comment]
Works for me. I even installed Vivaldi to verify. I'm out of ideas, so if Violentmonkey beta doesn't help you, I'll just consider it a weird hardware bug and you'll have to debug Violentmonkey yourself :-)

**Comment by jesus2099** [comment]
You're so kind to test that much!
I hope I have time soon to test clean profile and other browsers.
In the meantime, I copy paste manually the library content in the main script codes.

Why do you mention Violentmonkey beta?

**Comment by tophf** [comment]
Beta is where all the development goes so it may have fixed whatever bug there was.

**Comment by jesus2099** [comment]
I didn't have much time but I'm in the metro now and I could reproduce the problem on another browser too, with my same 2 simple OK and NG scripts: [Android 9 Kiwi Browser 105](https://github.com/jesus2099/konami-command/issues/708#issuecomment-1256364790).

**Comment by tophf** [comment]
Well I don't have an Android so I can't test it.

**Comment by jesus2099** [comment]
No but it's starting to be more than a series glitch an a random installation. 😉

I see several changes around `run-at`, `document-start` and `document-end` in [Violentmonkey V2.13.1 release notes](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.1)… 🤔

**Comment by tophf** [comment]
Well, to me it doesn't look like that as it still may be two bugged browsers, both Vivaldi and Kiwi are known to have inexplicable bugs just like this one :-)

**Comment by jesus2099** [comment]
Now also confirmed in **Chrome** 105.0.5195.127 (Build officiel) (64 bits).
**OK script must be first in the list and NG script must be second in the list, to reproduce the bug.**

**Comment by tophf** [comment]
Still works for me.
Can you give me an exported zip from Violentmonkey with just these two scripts that fails for you in Chrome?

**Comment by jesus2099** [comment]
Yes, so I ran Chrome for the very first time in my session on this new laptop install.
There is no settings, no extensions, nothing.

1. I go to https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag and install latest ViolentMonkey.
2. I go to https://github.com/jesus2099/konami-command/issues/708 and copy the OK script code
3. I click Violentmonkey + button
4. Ctrl+A, Ctrl+V, Ctrl+S, Ctrl+W
5. I copy the NG script code
6. Ctrl+A, Ctrl+V, Ctrl+S, Ctrl+W
7. I press F12 and display DevTools console tab
8. I press F5 to reload page with my 2 new OK and NG script (and no others)

And then I see that **ReferenceError**.

Here is the zip: [violentmonkey_2022-09-24_17.59.38.zip](https://github.com/violentmonkey/violentmonkey/files/9639080/violentmonkey_2022-09-24_17.59.38.zip)

**Comment by tophf** [comment]
I see it now. Evidently I've copypasted the code incorrectly.

**Comment by tophf** [comment]
Fixed in 070eca76

**Comment by tophf** [comment]
The workaround until the new release might be to add something meaningless to the URL e.g. `#bugfix`

**Comment by jesus2099** [comment]
Subsequent https://github.com/violentmonkey/violentmonkey/issues/1581 got fixed!
Just waiting for the new release, using the work-around.

**Comment by jesus2099** [comment]
Hello @tophf,
I checked the changelog but it's not clear to me if this fix is included in latest version 3.13.3.
Is it fixed?
Can I remove the work around from my scripts?

**Comment by tophf** [comment]
> Fixed in https://github.com/violentmonkey/violentmonkey/commit/070eca76c6c41cd8b5b97a2b0b9293946bbedc07.

If you click the link you'll see the versions that include the fix.

**Comment by jesus2099** [comment]
Oh, super!
I do see **v2.13.3**, indeed:

> master
> v2.13.3.2 v2.13.3.1 **v2.13.3** v2.13.2.5 v2.13.2.4 v2.13.2.3 v2.13.2.2 v2.13.2.1 v2.13.2 v2.13.1.5 v2.13.1.4
