### ISSUE TITLE
[BUG] Some scripts don't work

### ISSUE THREAD

**Issue by Gersonzao** [violentmonkey/violentmonkey#1593]
- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Some userscripts like https://greasyfork.org/en/scripts/449705-yuhan-user-script-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E-%E7%99%BE%E5%BA%A6%E5%BF%85%E5%BA%94%E8%B0%B7%E6%AD%8Cf%E6%90%9C-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-csdn-github-%E5%BC%80%E5%8F%91-%E6%9B%B4%E5%A4%9A-%E4%BC%98%E5%8C%96-%E7%BE%8E%E5%8C%96-%E5%87%80%E5%8C%96-%E5%A2%9E%E5%BC%BA just don't work

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Go to a userscript website
2. Install an userscript like the mentioned above
3. Test the script

**Expected behavior**
The script worked perfectly

**Actual behavior**
The script doesn't work at all

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
The same
Logs: INS: content-ads.js loaded:  https://www.ecosia.org/search?q=IRC+web+client content-scripts.js:1:107966
TSS: content-tss.js loaded:  https://www.ecosia.org/search?q=IRC+web+client content-scripts.js:1:117760
INS: content-blocked-items.js loaded:  https://www.ecosia.org/search?q=IRC+web+client content-scripts.js:1:137798
Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “ECRQ” has been rejected because it is already expired. search
Cookie “ECFG” has been rejected because it is already expired. search
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). moz-extension:97:25
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). moz-extension:1:322
CONTENT_SHELL: Page allowed. Skipping shell injection blocks content-scripts.js:1:137460
GET TAB ID RESPONSE:  
Object { tabId: 11 }
content-scripts.js:1:119296
TSS: excluded result:  
Object { excluded: true }
content-scripts.js:1:128481
TSS: Excluding content tss (trigger: send-mesage) content-scripts.js:1:119833
[OptiSearch] Hello ! utils.js:4:31
The resource at “https://cdn-static.ecosia.org/static/fonts/inter/static/Inter-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. search
The resource at “https://cdn-static.ecosia.org/static/fonts/inter/static/Inter-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. search
The resource at “https://cdn-static.ecosia.org/static/fonts/inter/static/Inter-Bold.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. search
[OptiSearch] Ecosia — "IRC web client" utils.js:4:31

oooooooooooo                               o8o
`888'     `8                               `"'
 888          .ooooo.   .ooooo.   .oooo.o oooo   .oooo.
 888oooo8    d88' `"Y8 d88' `88b d88(  "8 `888  `P  )88b
 888    "    888       888   888 `"Y88b.   888   .oP"888
 888       o 888   .o8 888   888 o.  )88b  888  d8(  888
o888ooooood8 `Y8bod8P' `Y8bod8P' 8""888P' o888o `Y888""8o

We love JavaScript too - why not code and plant trees? Check out https://explore.ecosia.org/jobs

hiring-easteregg.js:5:10
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://www.bingapis.com/api/ping/pageload?IG=13D18E16398E4411B7EC877306D0C5EE&CID=1D09248CD8056BB2338936BDD9026A78&Type=Event.CPT&DATA=0 cjs-ponyfill.js:436:11
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://www.bing.com/th?id=AMMS_c1e03e416d9cfcfed330e80ddef622e4&w=110&h=110&c=7&rs=1&qlt=80&cdv=1&pid=16.1 82c71ce.js:1:8703
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://www.bingapis.com/api/ping/pageload?IG=13D18E16398E4411B7EC877306D0C5EE&CID=1D09248CD8056BB2338936BDD9026A78&Type=Event.CPT&DATA=0 2 cjs-ponyfill.js:436:11
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://www.bingapis.com/api/ping/pageload?IG=13D18E16398E4411B7EC877306D0C5EE&CID=1D09248CD8056BB2338936BDD9026A78&Type=Event.CPT&DATA=0 cjs-ponyfill.js:436:11
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://www.bingapis.com/api/ping/pageload?IG=13D18E16398E4411B7EC877306D0C5EE&CID=1D09248CD8056BB2338936BDD9026A78&Type=Event.CPT&DATA=0 cjs-ponyfill.js:436:11

**Environment:**
- OS: Windows 7 SP1 Build 7601
- Browser: Firefox ESR
- Browser Version: 103.2
- Violentmonkey Version: 2.13.1

**Additional context**
Tampermonkey and Tampermonkey Beta are the only ones that work perfectly with this script

**Comment by tophf** [comment]
The author uses invalid `@match` values like `*.bing.com/*`.
You can suggest the author to fix it per the specification: `*://*.bing.com/*`

I don't think we should support invalid syntax because other engines don't support it as well. The fact that Tampermonkey allows invalid syntax is what encourages the authors to write broken scripts and this is just wrong. Greasemonkey and Firemonkey don't support this broken syntax either, but they're better than us as they show an error about it. We will do it too in #1312.
