### ISSUE TITLE
[BUG] `Object.defineProperty(window, ...)` on `document-start` does not work on Firefox

### ISSUE THREAD

**Issue by Cynosphere** [violentmonkey/violentmonkey#1595]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Using `Object.defineProperty` to overwrite a property on `window` via `document-start` does not work on Firefox.

**To Reproduce**
Example userscript:
```js
// ==UserScript==
// @name        Twitter Feature Switches Menu Option
// @namespace   Violentmonkey Scripts
// @author      Cynosphere
// @match       https://twitter.com/*
// @match       https://mobile.twitter.com/*
// @grant       none
// @run-at      document-start
// ==/UserScript==

(()=>{
  let origState;
  Object.defineProperty(window, "__INITIAL_STATE__", {
    set(s) {
      s.featureSwitch.debug = s.featureSwitch.user.config

      origState = s;
      window.__ORIGINAL_INITIAL_STATE__ = s;
    },
    get() {
      return origState;
    },
    configurable: true,
  });
})();
```

**Expected behavior**
The defined property for window is defined

**Actual behavior**
Nothing

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Nothing

**Environment:**
- OS: Windows 10 21H2
- Browser: Firefox
- Browser Version: Developer 106.0b7
- Violentmonkey Version: 2.13.1

**Comment by tophf** [comment]
This is a Firefox limitation, see #997 for workarounds.
