### ISSUE TITLE
[BUG] 2.13.2 upgrade caused issue with default icon, script size calculation, and seeing any script code at all in the editor, downgrade to 2.13.1 resolves issue

### ISSUE THREAD

**Issue by LabMember-001** [violentmonkey/violentmonkey#1599]
Upgrade from 2.13.1 to 2.13.2 caused:
- No default icons to show, only custom icons show.
```22:02:53.859 Uncaught (in promise) 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 2227, … }
10 common-ui.js:1:97837
```
One for each script with default/no icon. The default icon shows as blank.
- Script size only shows stored settings/values/require, does not include userscript size.
- Opening script editor in violentmonkey shows blank page 

macOS Big Sur v11.6
Firefox 105.0.3 64bit

Downgrading to [2.13.1](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.1) has restored normal activity. I will keep using that one for now.

Minor irrelevant bugs that have persisted for a while now, I can open new issues for if interested:
- I have a script that's over 14mb (ik) and it also shows blank in the old version. When it was under 10mb it loaded fine. 
- Opening script editor throws ```Error: Unknown modifier key: Cmd```, but loads fine.
These two also happened on my Linux desktop, also firefox.

Interestingly while I couldn't read the scripts in the editor, I could export them just fine so I backed them up before touching anything.

**Comment by tophf** [comment]
> No default icons to show
> Unknown modifier key: Cmd

I wonder if this is specific to Mac, because it works in PC for me. @gera2ld, do you have a Mac?

> Script size only shows stored settings/values/require, does not include userscript size

Yeah, fixed already, I noticed just today.

> I have a script that's over 14mb (ik) and it also shows blank in the old version.

I've just made a 15MB script and it opens fine here. 
Are there any errors in devtools console?
Maybe you could share the script or describe a way to generate it?

**Comment by tophf** [comment]
Oh, maybe you can install the [beta versions](https://github.com/violentmonkey/violentmonkey/releases) released since 2.13.1 and find the last one working for you, so that we can narrow the regression range.

**Comment by LabMember-001** [comment]
>Maybe you could share the script or describe a way to generate it?

I am hesitant to share the script itself on here since it was previously taken down from github.

Probably should have mentioned, it has a massive oneliner in base64 for a binary file that is like 99% of the script. Should probably be reproducible like that. To reproduce the bug I tried to put a 5mb image in one variable and the script editor fails to load anything at all so that must be the issue. When saving it, just says line too long. When reopened, even meta is not there anymore. Not exactly normal use for such large lines, but not always suitable to fetch external files.

I'll go try the beta versions and see where the original issue in the OP started.

**Comment by LabMember-001** [comment]
Issue in subject about icons and script size and text editor blank starts here https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.1.4

https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.1.3 is fine.

**Comment by tophf** [comment]
This range switched to `data:` icons, so I guess you've disabled Canvas in Firefox either via `about:config` or you might have enabled some super secure mode in preferences. It'd be helpful if you confirm, but I'll add a workaround for that anyway.

**Comment by LabMember-001** [comment]
No major changes.

The scripts I have use a base64'd data: icon and they load fine, though not sure if that's what you mean or if it's something else.
The blank ones show empty <img> tags, and console log shows ```originalTarget: <img src="moz-extension://accd9fcb…lic/images/icontrue.png">```;
Looking at moz-extension:// /public/images/ shows me there is no "icontrue.png", but many other images sizes in there. If I manually set the src to those image urls the image loads fine.
I'm guessing for some reason it returns true instead of the intended size and doesn't know what data to fetch.

**Comment by tophf** [comment]
Thanks, now I see where I made a stupid mistake.

> Opening script editor in violentmonkey shows blank page

Which beta breaks this?

**Comment by tophf** [comment]
Could you maybe find the latest working [test build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml?query=branch%3Amaster)? Starting with "feat: expose pattern errors in installer" 5 days ago back to "fix: read envStart from storage first" 14 days ago. There's like 15 of them so you can test the middle one, then if it fails test the middle one in the older half of the range, so you'll only have to test 3 or 4 builds overall.

**Comment by LabMember-001** [comment]
Had to download some nightly/enterprise version to run unsigned xpi.
Picked librewolf.
I installed one small script and one huge script.
Unreadable, incorrect size: https://github.com/violentmonkey/violentmonkey/actions/runs/3170184057
Unreadable, correct size: https://github.com/violentmonkey/violentmonkey/actions/runs/3210322356
Readable, correct size: https://github.com/violentmonkey/violentmonkey/actions/runs/3162514846
With librewolf 105.0.1-1 default config on mac big sur, all images showed data: tags as intended on all dev versions I tried.

None of them could read to edit the script with the huge payload.
All scripts ran even when unreadable in all of these versions on librewolf, even the latest dev version.

**Comment by tophf** [comment]
Fixed everything except "Unknown modifier key: Cmd", @gera2ld.
Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/8682266589/artifacts/391330684).

**Comment by LabMember-001** [comment]
Script size shows correct, script readable, also the big ass line script readable. Cheers.

**Comment by gera2ld** [comment]
"Unknown modifier key: Cmd" has been there for a long time and I've fixed it after migrating to Vue 3. Anyway it's just a warning so not a big deal.

**Comment by loskael** [comment]
> Unknown modifier key: Cmd

it's makes editor broken on this exception, and seems cause by this commit

https://github.com/violentmonkey/violentmonkey/blob/888631cf14f50a2ad48a1120f201cc16b907ccf1/src/options/views/edit/index.vue#L275
