### ISSUE TITLE
Change deprecated manifest.json values

### ISSUE THREAD

**Issue by Sn0wCrack** [violentmonkey/violentmonkey#160]
### What is the problem?

The manifest.json is using old fields, namely "options_page"
This will cause certain browsers to not display the options item in the add-ons menu

You can see more about implementing this here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/options_ui and here: https://developer.chrome.com/extensions/optionsV2#migration

**Comment by bershan2** [comment]
@gera2ld Please don't forget `"open_in_tab": true`, so that options open up in a full new tab as they do now.

Thus the new values would look like:
```
  "options_ui": {
    "page": "options/index.html",
    "open_in_tab": true
  },
```

**Comment by gera2ld** [comment]
Thanks! @Sn0wCrack @bershan2

**Comment by bershan2** [comment]
@gera2ld Also I noticed that `manifest.json` does not have `"minimum_chrome_version"`. I just would like to confirm that this is intentional. Thanks.
