### ISSUE TITLE
Nothing works in incognito window (Firefox, Linux)

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1600]
**Usual window**

![изображение](https://user-images.githubusercontent.com/33825590/194731859-085c77dd-4819-4908-a855-3db115656063.png)

**Incognito window**

![изображение](https://user-images.githubusercontent.com/33825590/194731866-be0b61a9-24a3-4429-b319-a75584eac329.png)

**Console in incognito window**

![изображение](https://user-images.githubusercontent.com/33825590/194731883-24110ce8-c866-4ba8-b175-4da9cd12b135.png)

**Comment by gera2ld** [comment]
I guess it's related to #1599 . It's working now in the latest master. Please expect the fix in the next release.

**Comment by tophf** [comment]
> In the pop up:

What?

**Comment by AlttiRi** [comment]
The same bug.
The userscripts are not listed in the popup, but they work.

Windows, Firefox.

If https://github.com/violentmonkey/violentmonkey/commit/3fa47f66f780233d0f2a4b8441b65fcdad454c7e fixes it too, it is fine.

**Comment by tophf** [comment]
Your screenshot is from an old version. The issue is fixed in the new version.

**Comment by gitdine** [comment]
Just updated and can confirm it's fixed.

**Comment by soviet-man** [comment]
I my Firefox is old version (Manjaro Linux, XFCE, Firefox). Version 2.13.2.
In private windows userscripts are not shown but work.

**Comment by soviet-man** [comment]
Yes, it's fixed now.
