### ISSUE TITLE
[BUG] Cannot enable/disable script from toolbar menu

### ISSUE THREAD

**Issue by cox34** [violentmonkey/violentmonkey#1602]
- [x] I have searched for existing issues that already reported this problem and found none

Since 2.13.2, cannot enable/disable script from toolbar menu (where it shows matched scripts for a page). 
(tested for issue in beta versions and is actually present since 2.13.1.4)
Clicking the slider button does not toggle the script. 
Violentmonkey itself can be toggled. 
Scripts can be toggled from the Violentmonkey dashboard page (moz-extension://xxx/options/index.html#scripts)

**Environment:**
- OS: Linux
- Browser: Firefox
- Browser Version: 105.0
- Violentmonkey Version: 2.13.2

**Comment by tophf** [comment]
Thanks, this is already fixed in the development version. It'll be released soon.
