### ISSUE TITLE
[BUG] can't enable/disable script via popup menu

### ISSUE THREAD

**Issue by Landius** [violentmonkey/violentmonkey#1603]
- [x] I have searched for existing issues that already reported this problem and found none

**To Reproduce**
1. click toolbar icon to open the popup menu
2. click the left switch of a script

**Expected behavior**
enable/disable script

**Actual behavior**
console prints an error msg:
`Uncaught (in promise) Error: Command is only allowed in extension context: UpdateScriptInfo`

**Environment:**
- Browser: firefox v106
- Violentmonkey Version: 2.13.2

**Comment by tophf** [comment]
Thanks, this is already fixed in the development version. It'll be released soon.
