### ISSUE TITLE
[BUG] Not recognizing user defined std. classes prototype

### ISSUE THREAD

**Issue by trumpeta** [violentmonkey/violentmonkey#1605]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Defining custom prototype to existing class is ignored later.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. define custom object prototype within test script (eg. `String.prototype.double = function() { return this + this }`)
2. call the prototype later (eg. `'hello'.double()`)
3. you get a type error
4. executing the sequence in browser console works as expected

**Expected behavior**
custom prototype visible within the scope (as in console, as in Tampermonkey)

**Actual behavior**
custom prototype invisible as in Violentmonkey

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Idk how to install upcoming release

**Environment:**
- OS: Ubuntu
- Browser: Chromium
- Browser Version: 106.0.5249.91
- Violentmonkey Version: 2.13.1

**Additional context**

**Comment by tophf** [comment]
Works for me.

> Idk how to install upcoming release

There's a link to the web store.

**Comment by trumpeta** [comment]
Violentmonkey BETA:
it's the same
> TypeError: str.double is not a function

**Comment by tophf** [comment]
Well, since it works me, I can't investigate it. I guess the problem is triggered by something else.
