### ISSUE TITLE
[BUG] VM script editor doesn't load scripts

### ISSUE THREAD

**Issue by XiaoHippo** [violentmonkey/violentmonkey#1607]
**Describe the bug**
Scripts editor doesn't load scripts. The editor pane is empty even though scripts are being executed at runtime. Tried creating new scripts in addition to trying to edit existing scripts, also tried new Browser profile. VM 2.13.1 works for me.

**To Reproduce**
1. Go to VM Installed Scripts tab
2. Add "+" -> New
3. Type something
4. Save & Close
5. Click the </> icon to load the script just created

**Expected behavior**
Seeing what's just been save.

**Actual behavior**
Seeing empty editor pane.

**Environment:**
- OS: 12.6
- Browser: Firefox
- Browser Version: 105.0.3
- Violentmonkey Version: 2.13.2

**Additional context**
Originally after upgrading to 105.0.3, the "Installed Scripts" panel was completely empty for me, mentioning GetAllOptions error, and showing no installed scripts but in fact there were. After reinstalling VM it did show the scripts but script content is empty.

**Comment by tophf** [comment]
Thanks, this should be already [fixed in beta](https://github.com/violentmonkey/violentmonkey/releases).
