### ISSUE TITLE
[BUG] Enter doesn't work on "Find scripts for this site" via popup menu

### ISSUE THREAD

**Issue by polt515** [violentmonkey/violentmonkey#1608]
**Describe the bug**
When I highlight "Find scripts for this site" and then press enter nothing happens.

**To Reproduce**
1. Open the popup menu
2. Highlight "Find scripts for this site"
3. Press enter

**Expected behavior**
When I press enter on "Find scripts for this site" it takes me to the Greasyfork page for that site.

**Environment:**
- Browser: Firefox v105.0.3
- Violentmonkey Version: 2.13.2

**Comment by polt515** [comment]
> Thanks, this should be already [fixed in beta](https://github.com/violentmonkey/violentmonkey/releases).

Just checked and it's still not fixed in beta

**Comment by gera2ld** [comment]
This is a UI issue, also exists in Chrome.

**Comment by polt515** [comment]
This issue still persists in firefox but not in chrome in BETA v2.13.2.5

**Comment by gera2ld** [comment]
Fixed in d05cb34bc4b7fd770bf0a9201fe865da7d1ba73a
