### ISSUE TITLE
[BUG] GM_setValue blocks other tabs on v2.13.2 with uBlock on Firefox

### ISSUE THREAD

**Issue by nuiva** [violentmonkey/violentmonkey#1609]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
I have an userscript whose GM_storage takes 2.4MB memory (i.e. going to Violentmonkey dashboard -> Edit userscript -> values tab says "Values (2.4 M)") with 15902 distinct keys.
Since v2.13.2, calling GM_setValue on 100 existing keys hangs other tabs for about a minute.
"Hangs" here means that the browser is responsive and I can open new tabs, but trying to load other webpages doesn't work. The other tabs behave as if they're connecting for a really long time.

While investigating, I found that the issue occurs only when uBlock Origin is enabled.

**To Reproduce**
1. Install uBlock Origin 1.44.4.
2. Install Violentmonkey 2.13.2.
3. Create the following userscript:
```
// ==UserScript==
// @name        Test script
// @match       *://blank.org/
// @grant       GM_setValue
// ==/UserScript==

let x = Date.now();
for (let i = 0; i < 2000; ++i) GM_setValue(i, x);
```
4. Load https://blank.org.
5. Immediately try to open https://google.com in another Firefox tab.
6. Observe that the Google tab is stuck for 20ish seconds.
7. Disable uBlock Origin and repeat steps 4-5. Observe that the Google tab loads immediately.
8. Enable uBlock Origin again and downgrade to Violentmonkey 2.13.1. Repeat steps 4-5. Observe that the Google tab loads immediately.

**Expected behavior**
Other tabs should load immediately, as they did in version 2.13.1.

**Actual behavior**
Other tabs get stuck at connecting while Violentmonkey is saving storage values or something.

**Environment:**
Test 1:
- OS: Windows 10.0.19042
- Browser: Firefox 105.0.3 64b with a bunch of other extensions and scripts
- Violentmonkey Version: 2.13.2

Test 2:
- OS: Windows 10.0.19042
- Browser: Fresh install of Firefox developer edition 106.0b9 64b. Only extensions were freshly installed Violentmonkey and uBlock Origin 1.44.4.
- Violentmonkey Version: 2.13.2

Test 3:
- Same as test 2 but with Violentmonkey beta 2.13.2.3

**Comment by tophf** [comment]
I've fixed the problem but there seems to be an underlying bug in Firefox: when one extension is doing something CPU-expensive it blocks the entire browser even though it's not inside a blocking listener. It may be an architectural deficiency i.e. it's still not fully-multiprocess. Another problem in Firefox seems to be the unexpected slowness of its implementation of array.includes which takes 20 seconds to make 2000 checks inside an array of 2000 elements. I've removed the check altogether, just in case.

**Comment by tophf** [comment]
On the other hand, all of this happens when uBlock is installed, so my deductions may be totally off the mark.

**Comment by nuiva** [comment]
I changed the test userscript loop to have 14000 iterations instead of 2000.
With this change, the new Violentmonkey test build (with uBlock, of course) blocks other tabs for around 20 seconds.
On the other hand, version 2.13.1 made the entire browser stutter for 1ish second, after which the Google tab loaded immediately. So older version was still 10-20x faster but had a bigger performance impact in that short timespan.

The profiler says both cases spent 90% sleeping. I might be using it incorrectly.

Anyhow, the new test build is sufficiently fast for my application, so I'm content with this fix.

**Comment by tophf** [comment]
The profiler has several modes. In `Firefox` mode, with the new build, it shows that 100% of those 27 seconds is spent inside Firefox internal MessagePump: https://profiler.firefox.com/public/y085wwcmpzagfbadxtc4keasdhtpd25m6azezb8/calltree/?globalTrackOrder=0w3&thread=2&v=7

Coupled with the fact that the problem is triggered by installing a second extension, it almost definitely looks like a bug in Firefox. I don't know what exactly triggers it, unfortunately.
