### ISSUE TITLE
[BUG][Firefox/Chrome] Turning on "Sync page mode" in the settings will invalidate GM_setValue `v2.13.2`

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1610]
**Describe the bug**
Turning on "Sync page mode" in the settings will invalidate GM_setValue.

**To Reproduce**
As above.

**Expected behavior**
fixed it.

**Actual behavior**
The console does not have any error messages.

**Environment:**
- OS: [e.g. macOS] win10
- Browser: [e.g. chrome, safari]  Firefox/Chrome
- Browser Version: [e.g. 22] v105.0.3/v106.0.5249.119
- Violentmonkey Version: v2.13.2

**Additional context**
none.

**Comment by tophf** [comment]
Please provide more info and a script that demonstrates the problem, otherwise there's nothing we can do...

**Comment by F9y4ng** [comment]
It fixes the problem for regular sites, but sites with Content-Security-Policy applied, such as github.com, will not execute the script and report an error.

```
Uncaught (in promise) TypeError: Error in invocation of tabs.executeScript(optional integer tabId, extensionTypes.InjectDetails details, optional function callback): Error at parameter 'details': Error at property 'runAt': Value must be one of document_end, document_idle, document_start.
```
![err1](https://user-images.githubusercontent.com/15855068/195379288-bcf4a832-46fc-4c73-b343-557a8194c535.png)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
```
![err2](https://user-images.githubusercontent.com/15855068/195379650-1b004513-eadb-4f9a-b7ec-b3b1c30cf9ab.png)

**Comment by tophf** [comment]
This executeScript error is a separate thing, thanks for reporting, I'll look into it.

**Comment by tophf** [comment]
I can't reproduce executeScript error, but I've fixed some other bugs, here's the new test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/8742319260/artifacts/395761883).
If it still has the error, please describe how I can reproduce it.

**Comment by tophf** [comment]
I finally found and fixed the executeScript bug.
