### ISSUE TITLE
[Feature] Manifest v3

### ISSUE THREAD

**Issue by jez9999** [violentmonkey/violentmonkey#1613]
I just watched this video: https://www.youtube.com/watch?v=18VM1xZQdXc

Seems Chrome, and pretty much all Chrome-based browsers, will disable manifest v2 soon.  It looks like Violentmonkey uses manifest v2.  Is it possible for it to work with v3?  If not, that really rather sucks, userscript managers are going to be relegated to Firefox.

**Comment by tophf** [comment]
Chrome hasn't yet implemented an API for userscripts, so there's nothing we can do.

**Comment by jez9999** [comment]
@tophf Isn't Brave going to continue supporting it?  Maybe we could keep using it in that.

**Comment by tophf** [comment]
You can keep using ManifestV2 extensions in a browser that still supports ManifestV2. There's nothing we need to do about that.

**Comment by AlttiRi** [comment]
> all Chrome-based browsers, will disable manifest v2 soon

They recently delayed it to 2024.

**Comment by tophf** [comment]
MV2 will be randomly disabled in Chrome's main release channel [since June 2023](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/), and since Januray 2023 in beta/dev/canary. Most users won't bother re-enabling it forcefully via policies/flags.
