### ISSUE TITLE
[BUG] 2.13.3 still  not work on Firefox Nightly any version test on Firefox Nightly106.0a1

### ISSUE THREAD

**Issue by klcb2010** [violentmonkey/violentmonkey#1615]
For details, see #1612

**Comment by tophf** [comment]
No need to open a new issue.

**Comment by klcb2010** [comment]
> No need to open a new issue.

you said “AFAIK this is fixed in the latest beta.” but this is latest [Releases](https://github.com/violentmonkey/violentmonkey/releases) now

**Comment by tophf** [comment]
Just add a comment in the original issue. No need to open a new issue. It's the same issue.
