### ISSUE TITLE
Don't minify for FF 

### ISSUE THREAD

**Issue by mrdokenny** [violentmonkey/violentmonkey#162]
@gera2ld The Firefox version is stuck on 2.6.3 (since May 4) while the Chrome version is on 2.7.2. I think this extension is stuck in the slower admin queue.

Looking at the downloaded xpi from AMO, it looks like the code is minified. This makes it harder for reviewers to review and will usually go in the slower admin queue (once it's placed there, all new versions will go in that queue from now on).

To have a faster review, it is better to upload a new version without minification (since it's open source anyways). After uploading a new version, email AMO to get your extension out of the admin queue.

**Comment by gera2ld** [comment]
I can't find anything introduction to the admin queue. 😞 What do you think about self-distributed version?

**Comment by mrdokenny** [comment]
@gera2ld https://discourse.mozilla-community.org/t/optimize-addon-for-faster-review/17176

> I can't find anything introduction to the admin queue

From what I gather, your extension gets placed in the admin queue IF you provided original source code.

> What do you think about self-distributed version?

That could work while the old version is still on AMO, but people usually trust extensions from AMO. So I would upload a unminified 2.7.2 to AMO. Then request via email or IRC #addon-reviewers to get your extension out of admin queue. 

After that, in any future updates, the review will be faster since a volunteer reviewer (not just an admin) can review your extension and they can just check the diff between versions. For me, addon updates are really quick like 2-3 days.

**Comment by jspenguin2017** [comment]
> For me, addon updates are really quick like 2-3 days.

Chrome store review takes precisely 3 seconds. I can pretty much pull my extension from the store as soon as CI finish building it. Mozilla needs to automate the process.

**Comment by gera2ld** [comment]
Some code has different behaviors in development and production mode, e.g. debugging code.
Without minification in production mode, there will be useless and dead code everywhere.
I think it is not a good idea to submit a version with code in development mode.

**Comment by mrdokenny** [comment]
>Chrome store review takes precisely 3 seconds. I can pretty much pull my extension from the store as soon as CI finish building it. 

The review has it's pros and cons
https://www.ghacks.net/2017/08/02/google-pulls-chrome-web-developer-extension-over-ad-injecting/
https://www.ghacks.net/2017/07/31/chrome-extension-copyfish-hijacked-remove-now/

>Mozilla needs to automate the process.

There's going to be some form of some slight automation but it will still be primary human reviews.

@gera2ld 

I assume that this [line of code](
https://github.com/violentmonkey/violentmonkey/blob/master/gulpfile.js#L84) is the one for minification. 

Couldn't you make another version in automation for FF without minification? [uBlock WebExt versions do not have minification](https://github.com/gorhill/uBlock/releases) and it manages to have good review times.

>Some code has different behaviors in development and production mode, e.g. debugging code.
Without minification in production mode, there will be useless and dead code everywhere.

Depending on your build process, you can have a production version without minification that has no debugging code. And the useless and dead code wouldn't matter too much if you cleaned that code beforehand.

Updates for AMO should be really quick since it just checks the line diff between versions and it's hard to do that when it's minified.

**Comment by jspenguin2017** [comment]
> The review has it's pros and cons

I publish from 1 to 10 versions a day, form CI server. That review process is not going to work for rolling release extensions. 

>  uBlock WebExt versions do not have minification

That is uBlock Origin, not uBlock. 

> Depending on your build process, you can have a production version without minification that has no debugging code. 

Are you sure Uglify has an option to remove dead code without minifying? 
https://stackoverflow.com/questions/34361272/uglifyjs-options-to-only-remove-dead-code

**Comment by mrdokenny** [comment]
>I publish from 1 to 10 versions a day, form CI server. That review process is not going to work for rolling release extensions.

Not sure if you know these options but there are signed unlisted versions (where you can set your own update channel) and the dev channel

>Are you sure Uglify has an option to remove dead code without minifying?

Even if there isn't, there's probably other npm modules you could use.

**Comment by gera2ld** [comment]
Just updated the build script, supporting an uncompressed version without debugging code.
