### ISSUE TITLE
[BUG] Raw file view in Gitea doesn't offer installation

### ISSUE THREAD

**Issue by KucharczykL** [violentmonkey/violentmonkey#1620]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
When I open userscript hosted in Gitea in raw mode (same as on GitHub), installation is not offered automatically.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Open https://git.kucharczyk.xyz/lukas/userscripts/raw/branch/main/animebytes_display_anime_names/display_anime_names.js in the browser with the extension installed (or go to https://git.kucharczyk.xyz/lukas/userscripts/src/branch/main/animebytes_display_anime_names/display_anime_names.js and click on "Raw").
2. Plain text is displayed but installation is not offered.

**Expected behavior**
Installation is offered.

**Actual behavior**
Installation is not offered.

**Environment:**
- OS: Arch Linux
- Browser: Firefox
- Browser Version: 105.0.3
- Violentmonkey Version: 2.13.3

**Additional context**
It could be Gitea bug but I don't know how to investigate further.

**Comment by tophf** [comment]
Userscript managers recognize `.user.js` file extension, so you need to rename your file accordingly.

**Comment by KucharczykL** [comment]
:man_facepalming: Thank you, I can't believe I missed something like that.
