### ISSUE TITLE
[Feature] API Access to `browser.pageAction` (or `browser` in general)

### ISSUE THREAD

**Issue by nitz** [violentmonkey/violentmonkey#1621]
**Motivation**
I've been making use of a small userscript I've written that has performs actions when manually triggered through menu commands registered via the `GM_registerMenuCommand()` API. This works perfectly fine, but I've just begun to find it cumbersome to click the browser button, find my script in the popup, and then click the menu command I want to execute. I began looking into the [pageAction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction) Extension API as a method for providing a page-dependent action that I could invoke with a single click, while being a UI element that is in a consistent location. 

**Proposed Solution**
There could be many ways to accomplish exposing this API to userscripts.

- The easiest would to be able to just expose the `browser` object to userscripts as a whole. This is something that would obviously have security implications, and as such would almost definitely need to at minimum be protected via requiring a `@grant`. The object returned could also be a stripped down version of the `browser` object, but I'll stay out of those weeds for now.
- The second easiest method would to expose _just_ the `pageAction` object to userscripts, likely as well behind a `@grant`.
- A more verbose method would to expose `pageAction`'s functionality by means of a proxy API similar to how the `vm-shortcut` library wraps keyboard shortcut functionality. (Though it wouldn't be loadable via `@require`, as it'd need to be on the extension side of the sandbox.)
- Similar to above, but exposing a subset of functionality through methods similar to `GM_registerMenuCommand` to get a "does enough" implementation so that a userscript would be able to set/clear the `pageAction` and perhaps icon. If done in this way, violentmonkey could maintain it's own list of actions, and optionally use the popup feature of `pageAction` to display the choices if more than one is registered.

**Use Cases**
The primary use case is incredibly similar to that of `GM_registerMenuCommand`, with the added benefits of appearing in a consistent browser location, requiring only a single click to activate, and optionally displaying a custom icon to indicate the action it performs.

**Potential Roadblocks**
Because extensions get only the single page action (AFAICT), multiple userscripts that would like to use this feature could potentially fight over the UI element. Potential workarounds would include options like the aforementioned 'popup', something more akin to a priority system, or simply letting the last userscript that sets it to "win".

Cheers, and thanks for all the hard work you put in!

**Comment by tophf** [comment]
Unfortunately, extensions can't use both `browser_action` and `page_action` because Chrome disallows it, and we can't switch from browser_action to page_action for our main UI, obviously. Firefox allows both but we don't want to make two vastly different versions of extension UI because we want visual continuity and cross-browser uniformity.

There are other extension(s) that expose `browser` object, I forgot the name though.

**Comment by nitz** [comment]
Somehow I imagine this won't even be the last time this week that Chrome ends up being the rain on my parade. Appreciate the quick feedback!

**Comment by tophf** [comment]
We could probably expose several dummy slots for `browser.command` (this is for browser-wide or system-wide hotkeys) and let the user configure which script's action to use in our settings.

**Comment by nitz** [comment]
That sounds pretty nice too, being able to assign a keypress to command at the extension level would definitely help with visibility/potential clashing between scripts. I will say I've had a just fine time with https://github.com/violentmonkey/vm-shortcut, it's done the job nicely for my small cases.
