### ISSUE TITLE
[BUG] Unable to sync to WebDav on Firefox

### ISSUE THREAD

**Issue by wordpure** [violentmonkey/violentmonkey#1625]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Violentmonkey cannot sync to WebDav on Firefox.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Create a new firefox profile
2. Install Violentmonkey 2.13.3 on AMO
3. Open extension settings page and  switch sync type to WebDav
4. Enter relevant information
5. Click Save or Sync button
6. The interface is not responding

**Expected behavior**
WebDav sync works fine after clicking save or Sync button.

**Actual behavior**
The interface is not responding after clicking save or Sync button. And the console doesn't output any logs.

**Environment:**
- OS: Windows 21H2
- Browser: Firefox
- Browser Version: 106.0
- Violentmonkey Version: 2.13.3

**Comment by tophf** [comment]
The next version will be fixed.
