### ISSUE TITLE
[BUG] GM_notification can't process SVG image without width and height

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1626]
`GM_notification( { text : '...', title : '...', image : '...', } )`

If I pass link to SVG image as image parameter, then it won't be displayed if there are no width and height attributes in `svg` tag.

It is nonsense since SVG image has no dimensions. It's scalable and fits to any dimensions required.

For example, I downloaded one simple SVG file and it wasn't displayed in GM_notification, because `svg` tag has no `width` and `height` attributes.

Example
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     x="0px" y="0px" viewBox="0 0 64 64"
     enable-background="new 0 0 64 64"
     xml:space="preserve">
...
</svg>
```

Meanwhile, `notify-send` command works fine and SVG as icon is displayed
```
$ notify-send -i 'path_to_svg' 'title' 'text'
```

In order to view SVG image in GM_notification, I have to manually edit SVG file in text editor then add width and height attributes, i.e. `width="256px" height="256px"`.

**Comment by tophf** [comment]
We don't process the image in any way, so it's a bug in the browser, meaning you'll have to edit your svg accordingly.
