### ISSUE TITLE
[BUG] What's wrong with highlight of template strings?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#1627]
Template strings (enclosed in backticks) are highlighted wrong.
Spaces after closing curvy brackets are not highlighted.

![изображение](https://user-images.githubusercontent.com/33825590/196640045-24139c86-03e6-46ad-a92a-d4557d5aa989.png)

**Comment by tophf** [comment]
I don't see anything like that here. Post your full code please.

**Comment by soviet-man** [comment]
If you highlight not foreground, but background of numbers/strings/functions..., you will clearly see it.

**Comment by tophf** [comment]
I don't understand.

**Comment by soviet-man** [comment]
It's either your problem or CodeMirror's one. Wrong highligting of components of code.

**Comment by tophf** [comment]
Well, we can't do anything about a problem we can't replicate :-)

**Comment by soviet-man** [comment]
I don't understand you. I told you what to do to see this bug.

**Comment by tophf** [comment]
We're going in circles. If you can't find another way to demonstrate the problem, there's nothing I can do about it.

**Comment by soviet-man** [comment]
Here is my style
```
.cm-s-eclipse span.cm-meta { color: #FF1717; }
.cm-s-eclipse span.cm-keyword { font-weight: bold; color: #7F0055; }
.cm-s-eclipse span.cm-atom { color: #219; }
.cm-s-eclipse span.cm-number { color: black; background-color: rgba( 0, 255, 0, 0.2 ); }
.cm-s-eclipse span.cm-def { color: #00f; }
.cm-s-eclipse span.cm-variable { color: black; }
.cm-s-eclipse span.cm-variable-2 { color: #0000C0; }
.cm-s-eclipse span.cm-variable-3, .cm-s-eclipse span.cm-type { color: #0000C0; }
.cm-s-eclipse span.cm-property { color: black; }
.cm-s-eclipse span.cm-operator { color: black; }
.cm-s-eclipse span.cm-comment { color: #8C8C8C; }
.cm-s-eclipse span.cm-string { color: black; background-color: rgba( 255, 0, 0, 0.2 ); }
.cm-s-eclipse span.cm-string-2 { color: black; background-color: rgba( 255, 165, 0, 0.3 ); }
.cm-s-eclipse span.cm-qualifier { color: #555; }
.cm-s-eclipse span.cm-builtin { color: #30a; }
.cm-s-eclipse span.cm-bracket { color: #cc7; }
.cm-s-eclipse span.cm-tag { color: #170; }
.cm-s-eclipse span.cm-attribute { color: #00c; }
.cm-s-eclipse span.cm-link { color: #219; }
.cm-s-eclipse span.cm-error { color: #f00; }

.cm-s-eclipse .CodeMirror-activeline-background { background: #e8f2ff; }
.cm-s-eclipse .CodeMirror-matchingbracket { color: white !important; background-color: black !important; }
```

Apply it and then type simple code above
```
let variable = 'abc'
`text before ${ variable }     text after`
```

**Comment by tophf** [comment]
Yes, now I see the same, but why is this a problem in CodeMirror or Violentmonkey? It is the direct result of your CSS.

As for spaces, why do you think it's a bug? We only highlight trailing spaces.

**Comment by soviet-man** [comment]
OK. Why spaces after closing bracket is not highlighted if it's continuation of string and therefroe must be highlighted correspondingly.

**Comment by tophf** [comment]
Ah, I understand now. This is how CodeMirror5 renders spaces, they're plain text outside of spans. It's fixed in CodeMirror6, but we won't switch to it in the foreseeable future, because it's much slower inside chrome extensions in the initial stages of showing the code (extensions don't have code compilation cache).

**Comment by soviet-man** [comment]
Yes, as I thought it's CodeMirror's bug. It's not so irritating but I regularly pay attention why whitespaces after closing brackets are not highlighted as part of string.

**Comment by tophf** [comment]
I found a way. The next version will be fixed.
