### ISSUE TITLE
[BUG]  Myanimelist - Userscript does not work in Firefox but does in Edge

### ISSUE THREAD

**Issue by cospking** [violentmonkey/violentmonkey#1629]
- [X] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
On Myanimelist.net I use the following script:
[Series Highlighter](https://greasyfork.org/en/scripts/424774-series-highlighter-mal)

**This is a relatively simple script that colorizes Anime or Manga that you have:**
- Completed (Blue)
- Currently watching (Green)
- Plan to watch (Gray)
- Dropped (Red)
- Not on your list (White)

With Violentmonkey installed in Firefox **it does not show the colors** depicting the status on your list, it does however work in **Microsoft Edge with Violentmonkey**. Firemonkey does not work either in Firefox **but it works with Tampermonkey in Firefox**.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Install Firefox 101/102/103/104/105/106/108(Nightly) with new clean profile
2. Install Violentmonkey
3. Install Userscript https://greasyfork.org/en/scripts/424774-series-highlighter-mal
4. Login to Myanimelist.net
5. Add the top 1-5 on https://myanimelist.net/topanime.php to your list and change their status to Watching/Dropped/Plan to watch or other status.
6. Check page https://myanimelist.net/topanime.php

**Expected behavior**
The colors to reflect like what is seen in the following screenshot:
![msedge_AEVjHgkz2J](https://user-images.githubusercontent.com/108274310/197388466-cc56ef6a-5a65-4f56-9530-39f40e7abb74.png)

**Actual behavior**
I tried it in Firefox 101/104/106/108(Nightly) with new profiles and no addons besides Violentmonkey but I assume the other versions in between would be having the same issue.

**Firefox 106.1:**
![firefox_ngJq6u7Bxh](https://user-images.githubusercontent.com/108274310/197388487-1f2901f7-faf0-4f45-b7ba-0efb27c9dd0a.png)

**Microsoft Edge 106.0.1370.52 (Official build) (64-bit):**
![msedge_AEVjHgkz2J](https://user-images.githubusercontent.com/108274310/197388466-cc56ef6a-5a65-4f56-9530-39f40e7abb74.png)

![firefox_5GLrZaRNT5](https://user-images.githubusercontent.com/108274310/197388500-c053fe19-85f4-413d-aef4-3de1ae032bb5.png)

**The only noteworthy mention in the log would be:**
_"This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”."_
But it shows the same warnings and information without Tampermonkey/Violentmonkey activated.

I tried to look for any differences between the console logs with Tampermonkey vs Violentmonkey but they're practically the same.

**Environment:**
- OS: Windows 11H2
- Browser: Mozilla Firefox
- Browser Version: 106.1 but same issue in 101/102/103/104/105/106/108(Nightly
- Violentmonkey Version: 2.13.3.2 (BETA) and 2.13.3 from (Store)

I have tried to contact the developer of the userscript but he basically says _"I just installed firefox and tampermonkey and the script, and the script is working, so please use tampermonkey instead."_

Which I'm obviously not happy to oblige with.

I have no clue if the issue is caused by Violentmonkey, the browser or the script. I mean it works on Firefox with Tampermonkey but also works with Violentmonkey in Edge.

**Comment by tophf** [comment]
Next release will be fixed.

**Comment by tophf** [comment]
BTW since it was broken only in 2.13.1 you can install 2.13.0 from AMO:
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

**Comment by cospking** [comment]
> BTW since it was broken only in 2.13.1 you can install 2.13.0 from AMO (and disable auto-update for Violentmonkey): https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

Thanks, that version does seem to work. As I didn't know exactly when it stopped working, I couldn't figure where the issue was coming from since Firefox updates it's browser almost monthly.
