### ISSUE TITLE
[Feature] ability to disable code completion

### ISSUE THREAD

**Issue by cheater** [violentmonkey/violentmonkey#1630]
**Motivation**

the code completion popup gets in the way when i'm typing which is very annoying and i would like to turn it off, but code mirror doesn't seem to have an option and there's no option in VM either.

**Proposed Solution**

**Use Cases**

it would be less annoying like this :)

**Comment by tophf** [comment]
It can be configured in editor options as usual, which is admittedly inconvenient, so something to address in the future.

1. click `Show editor state` in advanced settings
2. find "complete", it'll be `"autocompleteOnTyping": 100`
3. copy the line into the input box and change the number to `0` (zero).
4. click `Save`

**Comment by cheater** [comment]
@tophf thanks, where is "autocompleteOnTyping" documented? I haven't been able to find anything about that variable on google. Is it a VM setting or a CodeMirror setting?

**Comment by tophf** [comment]
It's our custom option, the number is the delay in milliseconds.

**Comment by cheater** [comment]
Thanks, appreciated. Does 0 turn it off?

**Comment by cheater** [comment]
Thanks! :)
