### ISSUE TITLE
Multiple columns aren't enabled in Centbrowser

### ISSUE THREAD

**Issue by k650dg4d2** [violentmonkey/violentmonkey#1632]
in catxp browser，it shows two in one line。but in cent browser，it shows one in one line。and i did not find options in setting。how i became two in one line
![QQ截图20221024131538](https://user-images.githubusercontent.com/32454224/197453124-7fb4069f-3c2f-4d0d-bb7f-8d328f1aa76d.png)
![QQ截图20221024131603](https://user-images.githubusercontent.com/32454224/197453133-ad62d135-ae09-46fb-aa64-0acf3f3d89f9.png)

**Comment by gera2ld** [comment]
![image](https://user-images.githubusercontent.com/3139113/197455496-fbd2f6ff-4df2-496e-ad98-f128c6a31930.png)

**Comment by k650dg4d2** [comment]
> ![image](https://user-images.githubusercontent.com/3139113/197455496-fbd2f6ff-4df2-496e-ad98-f128c6a31930.png)

![QQ截图20221024134132](https://user-images.githubusercontent.com/32454224/197455768-6bd0eae7-114f-4452-896f-478c1c5a27d4.png)
![VeryCapture_20221024134448](https://user-images.githubusercontent.com/32454224/197456177-9cab9ad9-c6c2-4df4-840a-4fcd84cda61f.gif)
maybe it is my problem?

**Comment by k650dg4d2** [comment]
> > ![image](https://user-images.githubusercontent.com/3139113/197455496-fbd2f6ff-4df2-496e-ad98-f128c6a31930.png)
> 
> ![QQ截图20221024134132](https://user-images.githubusercontent.com/32454224/197455768-6bd0eae7-114f-4452-896f-478c1c5a27d4.png) ![VeryCapture_20221024134448](https://user-images.githubusercontent.com/32454224/197456177-9cab9ad9-c6c2-4df4-840a-4fcd84cda61f.gif) [ ![VeryCapture_20221024134448](https://user-images.githubusercontent.com/32454224/197456177-9cab9ad9-c6c2-4df4-840a-4fcd84cda61f.gif) ](https://user-images.githubusercontent.com/32454224/197456177-9cab9ad9-c6c2-4df4-840a-4fcd84cda61f.gif) [ ](https://user-images.githubusercontent.com/32454224/197456177-9cab9ad9-c6c2-4df4-840a-4fcd84cda61f.gif) maybe it is my problem?

it take effect in catxp browser, but invalid in cent browser

**Comment by gera2ld** [comment]
Possibly because cent browser is using a relatively old Chromium (86.0.4240.198) while the latest version is 106.0.5249.119.

**Comment by k650dg4d2** [comment]
> 



![QQ截图20221024140359](https://user-images.githubusercontent.com/32454224/197458299-7861b375-5937-4a30-92ca-b36d5560e132.png)
Otherwise, forget it，It's not unavailable

**Comment by tophf** [comment]
Number of columns depends on the width of the screen and it works in any supported browser i.e. Chrome>=55, Firefox>=52. Could you debug the problem yourself in devtools because we can't replicate it?

**Comment by tophf** [comment]
Ah, I found CentBrowser beta and I can see this problem. I'll try to investigate it.

**Comment by tophf** [comment]
Looks like a bug in Centbrowser: `document.documentElement.getComputedStyle` doesn't use the CSS file that was just loaded. Looks like a serious violation of the page loading process, but now that we know since this functionality can be broken we can add a hardcoded fallback.

**Comment by tophf** [comment]
So yeah, it's serious: Centbrowser incorrectly handles `defer` attribute of the script.
Luckily we don't need this attribute so the fix is simply to remove it.

**Comment by k650dg4d2** [comment]
> So yeah, it's serious: Centbrowser incorrectly handles `defer` attribute of the script. Luckily we don't need this attribute so the fix is simply to remove it.

oh，Now working normally。It's too awesome
