### ISSUE TITLE
[BUG] Unable to communicate installed version of GreeasyFork on Firefox

### ISSUE THREAD

**Issue by wordpure** [violentmonkey/violentmonkey#1634]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
On Firefox, GreasyFork can't get  script versions.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Allow GreasyFork to get script version in extension settings 
	![图片](https://user-images.githubusercontent.com/68013962/197573793-0ffaa713-e3e4-40e3-928d-b196d02f7835.png)
2. Open an installed script on GreasyFork's homepage.

**Expected behavior**
GreasyFork can get the version of the installed script.

**Actual behavior**
GreasyFork can not get the version of the installed script.
![图片](https://user-images.githubusercontent.com/68013962/197572568-d082a318-a4bc-493e-a533-dbcf73b07fa8.png)

**Environment:**
- OS: Win11 21H1
- Browser: Firefox
- Browser Version: 106.0.1
- Violentmonkey Version: 2.13.3

**Comment by tophf** [comment]
Next release/beta will be fixed.
