### ISSUE TITLE
[Feature] Add a script support button in the extension's popup

### ISSUE THREAD

**Issue by wordpure** [violentmonkey/violentmonkey#1635]
When @supportURL is present in the script, can the extension add a support button to make it easier for users to give feedback to the script author.

![图片](https://user-images.githubusercontent.com/68013962/197576021-ffb41cfb-189c-436a-b9c7-1336cd16e68d.png)

![图片](https://user-images.githubusercontent.com/68013962/197577595-8389a14e-73ee-490b-b475-28bc06c641a1.png)

**Comment by tophf** [comment]
Yeah I agree, we even have an icon for that in dashboard list.

**Comment by wordpure** [comment]
Some scripts don't explicitly specify @supportURL, in which case, if they are installed from GitHub or GreasyFork, can the extension use GitHub's Issue page or GreasyFork's feedback page as the @supportURL for the script, just like extension does with @homepageURL?

![图片](https://user-images.githubusercontent.com/68013962/197673071-d57ca627-2ce0-4bcb-9be9-21968a66a7ee.png)

**Comment by tophf** [comment]
I don't think it makes sense in this case - we already show the homepage and the feedback link is just one click away.

**Comment by tophf** [comment]
BTW, github repository can disable the issues in settings.

**Comment by tophf** [comment]
On the other hand Tampermonkey does it, and people don't seem to dislike it, so I guess we may do the same.

**Comment by wordpure** [comment]
> On the other hand Tampermonkey does it, and people don't seem to dislike it, so I guess we may do the same.

This feature was added in 2.13.3, thanks🌹

But there seems to be some problems with its implementation.

I installed [Bilibili Evolved Preview](https://github.com/the1812/Bilibili-Evolved#安装) in Github. The script itself did not set @homepageURL and @supportURL, but after installation Violentmonkey did not infer its @supportURL and set its @homepageURL to `about:blank.`

![图片](https://user-images.githubusercontent.com/68013962/199026137-ada6ef8b-24fa-4590-a134-11acee5c44ee.png)

![图片](https://user-images.githubusercontent.com/68013962/199025948-84291ab2-fa30-41f7-8b61-4d565c478879.png)

![图片](https://user-images.githubusercontent.com/68013962/199025920-cc8c4b6e-db1c-4852-a755-ea69704684ba.png)

![图片](https://user-images.githubusercontent.com/68013962/199025821-ad46d101-4255-4434-b552-abd975e2781a.png)

**Comment by tophf** [comment]
When you report bugs please specify your browser and its version. Apparently this is Firefox because I can't replicate the problem in Chrome, but it indeed is present in Firefox.

**Comment by tophf** [comment]
Fixed in 5da4c563.

**Comment by wordpure** [comment]
> When you report bugs please specify your browser and its version. Apparently this is Firefox because I can't replicate the problem in Chrome, but it indeed is present in Firefox.

Thanks for the reminder, I'll avoid making that mistake again.
