### ISSUE TITLE
[Feature] Allow custom metadata in script installation window

### ISSUE THREAD

**Issue by TFWol** [violentmonkey/violentmonkey#1637]
When installing a script for the first time from a website, I would like to edit (rather than only being able to view) prior to it being added.

It's already right there in front of you and saves needing to reopen the script to change it.

**Comment by tophf** [comment]
No, I don't think we should encourage editing remotely installed scripts.
@gera2ld?

**Comment by TFWol** [comment]
I typically remove things like icon URLs if they're pointing to a weird website I don't want to touch.
Especially since the connection happens right away whether or not the script is activated.

To alleviate concerns, maybe a setting in Options with it turned off by default?

**Comment by tophf** [comment]
I guess we can add an option to ignore script `@icon`

**Comment by gera2ld** [comment]
Maybe we can allow changes to custom metadata before confirming installation?

**Comment by TFWol** [comment]
That'd be useful. 99% of the changes deal mostly with those.

**Comment by tophf** [comment]
The next version will have an Edit button when installing the script to open the editor in the same tab after installing:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/3bb0f7a3-782f-4ca4-aad1-7027a679769f)
