### ISSUE TITLE
This extension is causing google search issues

### ISSUE THREAD

**Issue by diomed** [violentmonkey/violentmonkey#164]
### What is the problem?/ 

google search and images returns 404
like this:
`https://www.google.hr/^(/d+/d+/d+).*/`

instead of actual results.

This happens on Chrome as well.

I went through disabling/enabling extension by extensiont, and only with ViolentMonkey enabled this happens,
so it must be bug somewhere

### Environment
- Browser: Vivaldi 
- Browser version:.1.11.904.3.
- Violentmonkey version:  2.7.2
- OS: Windows 10

**Comment by gera2ld** [comment]
Works for me. Please provide a full reproduction.

**Comment by diomed** [comment]
how would I do that?

**Comment by gera2ld** [comment]
1. Which scripts should be installed?
1. Which URL should be open?
1. What is the expected behavior and what is the actual behavior?

**Comment by diomed** [comment]
All my scripts are disabled, I tell you. 
when I enable this one, it breaks; see gif:
![myscreen](https://user-images.githubusercontent.com/72777/28621660-f984b992-7211-11e7-83ca-db619964f262.gif)

**Comment by diomed** [comment]
oh, I see what u mean. so you think, a script might be causing it:
I use W.A.R. Links Checker Premium script

**Comment by diomed** [comment]
yup, it's the f* script that's causing this. my bad.
