### ISSUE TITLE
[BUG] GM_DL & GM_XHR does not work for resources > 1MB in incognito (Chrome)

### ISSUE THREAD

**Issue by alphabug** [violentmonkey/violentmonkey#1640]
- [X] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).

- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Downloading a large (> 1MB) resource via GM_xmlhttpRequest or GM_download in incognito mode does not work. On 2.13.3, GM_download completes but the file only has about 1MB of real data. In beta 2.13.3.3, the onload event never fires even when the loaded and total bytes reported in readyState changes are equal and thus no file is downloaded.

**To Reproduce**
Install script and visit any page in incognito mode.
```JS
// ==UserScript==
// @name        GM_DL/XHR Test
// @match       *://*/*
// @grant       GM_download
// @grant       GM_xmlhttpRequest
// @noframes
// ==/UserScript==

GM_download({
  url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Programming_code.jpg", // 2MB image
  name: "big.jpg",
  onload: r => console.log("GM_DL load", r),
  onerror: e => console.log("GM_DL error", e),
  onprogress: p => console.log("GM_DL progress", p)
});

GM_xmlhttpRequest({
  url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Programming_code.jpg", // 2MB image
  responseType: "blob",
  onload: r => {
    console.log("GM_XHR load", r);
    const i = document.createElement("img");
    i.style = "position: absolute; top: 0; left: 0; z-index: 999999999";
    i.src = URL.createObjectURL(r.response);
    document.documentElement.append(i);
  },
  onerror: e => console.log("GM_XHR error", e),
  onprogress: p => console.log("GM_XHR progress", p)
});
```

**Expected behavior**
GM_download triggers a download of a complete image.
GM_xmlhttpRequest onload event (crudely) overlays the page with a complete image.

**Actual behavior**
Downloaded image is either mangled beyond the 1MB threshold of data (release version) or does not download at all (beta).
Similarly, GM_XHR either produces an incomplete image or does not yield a usable blob to display on the page.

The page as well as the extension console/network info does not show any irregularities.

**Environment:**
- OS: Windows
- Browser: Chrome
- Browser Version: 107.0.5304.88
- Violentmonkey Version: 2.13.3 (Also tested beta 2.13.3.3)

**Additional context**
My actual use case is in gathering certain images on a page and generating an archive via JSZip. GM_XHR is not completing for larger images.

I have also tested Tampermonkey and it does not have this problem.

**Comment by tophf** [comment]
Fixed in 0e73b2b5
