### ISSUE TITLE
tell me which script update is wrong[Feature] 

### ISSUE THREAD

**Issue by izsiyy** [violentmonkey/violentmonkey#1641]
Every time a certain script error pops up in the lower right corner, I can only click, but I can't quickly locate that script. Can you tell me which script is wrong when prompted for an update error?

**Comment by tophf** [comment]
AFAIK it was fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by izsiyy** [comment]
Thanks
