### ISSUE TITLE
[BUG] Incorrect script editor width.

### ISSUE THREAD

**Issue by cesaryuan** [violentmonkey/violentmonkey#1642]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Script editor page style is strange.

https://user-images.githubusercontent.com/35998162/199985806-f7238c81-2d54-44eb-9154-565e24da57b6.mp4

**To Reproduce**
1. Open [script](https://greasyfork.org/zh-CN/scripts/27752-searchenginejump-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC) editor page.

**Environment:**
- OS: Windows 10
- Browser: cent browser (Chromium 102.0.5005.167)
- Browser Version: (Chromium 102.0.5005.167)
- Violentmonkey Version: 2.13.3

**Additional context**
Script url in the video: [searchEngineJump](https://greasyfork.org/zh-CN/scripts/27752-searchenginejump-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC)

**Comment by tophf** [comment]
The bug is not present in beta so it's already fixed.
