### ISSUE TITLE
[BUG] 为此站点查找脚本 不见了

### ISSUE THREAD

**Issue by 1990chs** [violentmonkey/violentmonkey#1643]
**Describe the bug**
暴力猴插件界面“为此站点查找脚本”这个选项不见了

**Environment:**
- OS:  win 10
- Browser: chrome
- Browser Version: 86.0.4240.198
- Violentmonkey Version: v2.13.3

![image](https://user-images.githubusercontent.com/27892759/199999967-e961b69d-12e8-4956-b90d-ef3a2b97e59d.png)

**Comment by tophf** [comment]
The bug is not present in beta so it's already fixed.

**Comment by klcb2010** [comment]
> The bug is not present in beta so it's already fixed.

我想知道 什么时候发布1.13.4？

**Comment by 1990chs** [comment]
> The bug is not present in beta so it's already fixed.

You mean this bug will be fixed in the future version ?

**Comment by klcb2010** [comment]
> > The bug is not present in beta so it's already fixed.
> 
> You mean this bug will be fixed in the future version ? And also when the next version will be released ?

测试版是12天以前就已经修复了，但是手机上没办法安装测试版。作业看得懂中文的。

**Comment by 1990chs** [comment]
> > > The bug is not present in beta so it's already fixed.
> > 
> > 
> > You mean this bug will be fixed in the future version ? And also when the next version will be released ?
> 
> 测试版是12天以前就已经修复了，但是手机上没办法安装测试版。作者看得懂中文的，你的语法有问题 😂😂😂

不是写作文，语法不重要，意思到就行

**Comment by tophf** [comment]
https://github.com/violentmonkey/violentmonkey/releases

**Comment by klcb2010** [comment]
> https://github.com/violentmonkey/violentmonkey/releases

 As far as I can tel ，beta release can not  install  to Firefox Android

**Comment by tophf** [comment]
There is one method, but setting it up for the first time is somewhat complicated:
https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/

**Comment by klcb2010** [comment]
> There is one method, but setting it up for the first time is somewhat complicated: https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/

太复杂 我决定放弃  安心等待正式版本
