### ISSUE TITLE
[Feature] 添加脚本设置功能

### ISSUE THREAD

**Issue by 1990chs** [violentmonkey/violentmonkey#1644]
https://greasyfork.org/zh-CN/scripts/391688-%E6%B0%B4%E6%B0%B4-qbittorrent-%E7%AE%A1%E7%90%86%E8%84%9A%E6%9C%AC-qq-%E7%BE%A4-189574683
如上的一个脚本安装完成后需要进行对其设置，但是在暴力猴中设置中没有其选项。
在tampermonkey中却可以进行设置，所有暴力猴能不能添加类似如tampermonkey设置功能？

![image](https://user-images.githubusercontent.com/27892759/200005329-97383052-8436-4fe2-9387-e9e2e3f975b9.png)

**Comment by tophf** [comment]
![image](https://user-images.githubusercontent.com/1310400/200038042-4bf80a36-9fcc-40e8-a988-7dd39cbbe07f.png)

**Comment by 1990chs** [comment]
设置界面和您的不一样，您的是什么版本？
![image](https://user-images.githubusercontent.com/27892759/200097529-2d48afab-4532-40a5-9134-d77de75fd20f.png)

**Comment by 1990chs** [comment]
> ![image](https://user-images.githubusercontent.com/1310400/200038042-4bf80a36-9fcc-40e8-a988-7dd39cbbe07f.png)

**Comment by 1990chs** [comment]
@tophf

**Comment by tophf** [comment]
The settings on my screenshot were added many years ago and should be present in all versions. Scroll the page down maybe.

**Comment by 1990chs** [comment]
> The settings on my screenshot were added many years ago and should be present in all versions. Scroll the page down maybe.
我的页面设置缩放设为120%导致的，没有问题了。
Sorry, my mistake due to I set zoom 120% to the website. No problem.
