### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by 3kh0** [violentmonkey/violentmonkey#1648]
**Motivation**

Add https://www.userscript.zone/ to the find scripts dialog. (USZ)

**Proposed Solution**

![image](https://user-images.githubusercontent.com/58097612/200201582-7aa81bc4-e91b-4dbd-8f0c-48ff3243bd28.png)

it would be added right after OUJS

**Use Cases**

Just yet another site to find user scripts, (why are there so many lol, just make one jeez)

**Comment by tophf** [comment]
We already offer two prominent repositories and that's enough. If this site ever becomes more prominent then we'll add it. You can write a userscript (or ask someone to do it) that would open a search on any site(s) and place it at the top of the list.
