### ISSUE TITLE
[Feature] Need to show Not Installed and Installed

### ISSUE THREAD

**Issue by razilong** [violentmonkey/violentmonkey#1652]
**like the Tampermonkey on Greasy Fork**

![](https://user-images.githubusercontent.com/97635957/200780983-26149c04-b2d8-4b83-8bfe-fb23fe341007.png)

![](https://user-images.githubusercontent.com/97635957/200780670-cd2b1a37-1a72-49e7-8755-dae2775e71bf.png)

**Comment by tophf** [comment]
This is already implemented, but broken in the current version. The next release will be fixed or you can use [beta](https://github.com/violentmonkey/violentmonkey/releases).
