### ISSUE TITLE
[Feature] manifest_version 2 is Closing soon

### ISSUE THREAD

**Issue by kumv-net** [violentmonkey/violentmonkey#1657]
manifest_version 2 is Closing soon

**Comment by tophf** [comment]
There's nothing we can do about it.

**Comment by tophf** [comment]
Currently ManifestV3 doesn't support userscripts, so it's impossible to migrate. When the necessary API is added to ManifestV3 the minimum supported version of Chrome will be the one that implements this API, probably 111. At this point it's pointless to discuss what we will do, so let's wait for the API first.

**Comment by Vangelis66** [comment]
> When the necessary API is added to ManifestV3, 
> the minimum supported version of Chrome will be the one 
> that implements this API, probably 111

... Thanks for your reply 👍 ; while, as you say, it's still premature "to discuss what you will do", from the above it appears that chances of maintaining (if **only** on GitHub) a parallel **MV2**-based VM (LTS) branch (for the sake of Ch55-110) look pretty grim... I'll be certainly keeping an eye on how "things" develop... 
Thanks again 😃 .
