### ISSUE TITLE
Settings button in Firefox

### ISSUE THREAD

**Issue by nazar-pc** [violentmonkey/violentmonkey#166]
### What is the problem?
There is no way to open Dashboard other than using toolbar icon, while the icon itself is typically useless otherwise.
Firefox extensions support having additional buttons in addons list, would be nice to be able to get into dashboard from there.

### Environment
- Browser: Firefox Nightly
- Browser version: 57
- Violentmonkey version: 2.6.3
- OS: Linux

**Comment by gera2ld** [comment]
Should have been fixed in #160
