### ISSUE TITLE
how to copy image?

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey#1662]
<div type='discussions-op-text'>

<sup>Originally posted by @green1052 November 21, 2022</sup>
i tried this code

```js
const rawData = await fetch("some url").then((response) => response.blob());

// mime is image/jpeg
GM_setClipboard(rawData, rawData.type);
```
i follwed https://violentmonkey.github.io/api/gm/#gm_setclipboard

but not working

how to do?
</div>

**Comment by tophf** [comment]
Currently we don't support complex data types in Chrome because we use JSON-based messaging. I'll investigate if we can fix it. Meanwhile try the new `navigator.clipboard` API: https://blog.saeloun.com/2022/06/09/copying-texts-to-clipboard-using-javascript

**Comment by green1052** [comment]
thx

**Comment by tophf** [comment]
Unfortunately, we can't fix it in GM_setClipboard as this type is [not supported](https://stackoverflow.com/questions/45017037/how-to-set-image-to-clipboarddata-in-oncopy-event), so you'll have to use `navigator.clipboard` API linked above.
