### ISSUE TITLE
[Feature] 文字说明挡住最后面一个脚本...

### ISSUE THREAD

**Issue by Noah1995** [violentmonkey/violentmonkey#1663]
![image](https://user-images.githubusercontent.com/25548230/203758081-6f9f4896-696c-420a-94c6-388291d4f6a0.png)
文字说明挡住最后面一个脚本...
有时候开关都点不了...
请不要重叠...

**Comment by tophf** [comment]
I can't reproduce this problem. It's also weird that you have two scrollbars.

To help us investigate please do the following:
1. right-click `2.13.3`
2. click "Inspect"
3. right-click `<html>`
4. click "Copy"
5. click "Copy outerHTML"

![image](https://user-images.githubusercontent.com/1310400/203772205-52a4de60-204a-4077-9cdc-7583f4684503.png)

**Comment by Noah1995** [comment]
Many scripts appear double rolling bar
[Copy outerHTML.txt](https://github.com/violentmonkey/violentmonkey/files/10088142/Copy.outerHTML.txt)

**Comment by Noah1995** [comment]
![录制_2022_11_25_10_32_09_453](https://user-images.githubusercontent.com/25548230/203888700-7a0adf2e-03c0-439f-9aae-88eeb2cddf51.gif)

**Comment by tophf** [comment]
I still can't reproduce these problem even when using your html.

What is your browser?
Did you change the scale setting in OS to 125% or more?

**Comment by Noah1995** [comment]
Can you remove the text prompt...
![录制_2022_11_26_00_17_53_923](https://user-images.githubusercontent.com/25548230/204024627-0ac7d259-58b6-4664-bf1f-85a3ad278188.gif)

**Comment by tophf** [comment]
We can't remove something unless we can understand what causes the problem.
You can remove it yourself by adding the following code to "Custom CSS" in Violentmonkey settings:

```css
.page-popup .message {
  display: none;
}
```

**Comment by tophf** [comment]
> My question is not about double scrollbars...

It's the source of the problem.

**Comment by Noah1995** [comment]
It is indeed related to the scale setting
100% no problem
![image](https://user-images.githubusercontent.com/25548230/204079914-c854c447-af14-49e3-b7ac-0b48aaedf116.png)

**Comment by tophf** [comment]
I can reproduce it now if I reduce the screen resolution and increase OS zoom, so that the popup becomes less than 600px.
