### ISSUE TITLE
[BUG] [Firefox] `GM_xmlhttpRequest` sends an empty response for readystate 4 before sending actual data

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1665]
**Describe the bug**
Violentmonkey 2.13.3 on Firefox, `GM_xmlhttpRequest` does not pass data correctly during async processing.

**To Reproduce**
F9y4ng/GreasyFork-Scripts/issues [#148](https://github.com/F9y4ng/GreasyFork-Scripts/issues/148)

**Expected behavior**
fixed it.

**Actual behavior**
nope.

**Environment:**
- OS: [e.g. macOS] win10
- Browser: [e.g. chrome, safari] Firefox
- Browser Version: [e.g. 22] 107.0
- Violentmonkey Version: 2.13.3

**Additional context**

Please try the follow code, in the URL: https://cn.bing.com/search?ensearch=1&q=yahoo
```js
// ==UserScript==
// @name        New test script
// @namespace   Violentmonkey Scripts
// @match       *://*.bing.com/*
// @grant       GM_xmlhttpRequest
// @version     1.0
// @author      -
// @description 2022/11/29 23:04:55
// @run-at      document-start
// ==/UserScript==

(function(){
  setTimeout(()=>{
    const requestNodes = document.querySelectorAll("#b_results a[href*='.bing.com/ck/a?']");
    requestNodes.forEach(node => {
      const url = node.href;
      return new Promise((resolve, reject) => {
        GM_xmlhttpRequest({
          url: url,
          headers: { Accept: "*/*", Referer: location.href },
          method: "GET",
          timeout: 8e3,
          onreadystatechange: response => {
            if (response.status === 200 && response.readyState === 4) {
              const resText = response.responseText || response.response || "";
              // console.log(resText); // Here can get the value of resText
              resolve(resText);
            }
          },
        });
      })
        .then(res => {
         console.log(res); // But no value is received here!!
        })
        .catch(e => {
         console.error(e);
        });
    });
  },1000)
})()
```

**Comment by tophf** [comment]
Until the bug is fixed the workaround is to use `onload` or `onloadend` events.

**Comment by tophf** [comment]
Actually, it's a bug in Firefox (it sends two `onreadystatechange` events when readyState is 4 and the first event has an empty response), so I'm not sure we should work around it.

A second workaround for a userscript (in addition to using `onload` event) is to check `response.response` before calling `resolve`.

@gera2ld, WDYT?

**Comment by F9y4ng** [comment]
But, applying the above code under Tampermonkey & Greasemonkey can correctly obtain the return value on FF, has Tampermonkey & Greasemonkey done some necessary processing?

**Comment by tophf** [comment]
Hmm, they don't, so it means this is our bug.
Apparently it's caused by our check for readyState added in 9903ca9e, I'll investigate.

**Comment by F9y4ng** [comment]
> Hmm, they don't, so it means this is our bug.
> Apparently it's caused by our check for readyState added in 9903ca9e, I'll investigate.

thanks.
