### ISSUE TITLE
[BUG] GM_getResourceURL fetch refused by Content Security Policy

### ISSUE THREAD

**Issue by polyproline** [violentmonkey/violentmonkey#1666]
- [ ] The bug is also present in the latest releases.
violentmonkey 2.13.3
edge 107.0.1418.52

- [ ] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
When I fetch GM_getResourceURL ,it crash
Refused by Content Security Policy

**To Reproduce**
use this code
```javascript
// @grant	GM_getResourceURL
// @resource opencc_wasm https://cdn.jsdelivr.net/gh/polyproline/opencc-wasm@main/opencc_gc.wasm
// ==/UserScript==

"use strict";
let ret = (()=>{
		const url = GM_getResourceURL("opencc_wasm", true);
		let arr;
		if (url.startsWith('data:')) {
      const detail = {
        "url":url,
        "method":"GET",
        "responseType":"arraybuffer",
      };
      let control = GM_xmlhttpRequest(detail);
      arr = control.response;
      console.log(arr);
      arr = new Uint8Array(arr);
      console.log(arr);
		} else {
      const req = fetch(url);
      const buf = req.arrayBuffer();
      arr = new Uint8Array(buf);
    }
  return arr;
})();
console.log(arr);
````
open https://developer.mozilla.org/zh-CN/docs/WebAssembly/JavaScript_interface/instantiate
see error msg in devtool console.

**Expected behavior**
get opencc_wasm data

**Actual behavior**
Refused to connect to 'blob:https://developer.mozilla.org/c8140c87-e92c-4026-b937-def3cdb5efd3' because it violates the following Content Security Policy directive: "connect-src 'self' updates.developer.allizom.org updates.developer.mozilla.org www.google-analytics.com stats.g.doubleclick.net".
 Refused to connect to 'blob:https://developer.mozilla.org/c8140c87-e92c-4026-b937-def3cdb5efd3' because it violates the document's Content Security Policy.

**Environment:**
- OS: [e.g. macOS]
- Browser: edge 
- Browser Version: 107.0.1418.52
- Violentmonkey Version: 2.13.3

**Comment by tophf** [comment]
Violentmonkey doesn't change the site's CSP, so it's beyond our control.
You can either disable CSP of the site using another extension like modheader or try using `false` in [GM_getResourceURL](https://violentmonkey.github.io/api/gm/#gm_getresourceurl).
