### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by joshtheworst** [violentmonkey/violentmonkey#1667]
Where do I put the userscript file in the source code so that when I load the extension, the userscript is already there?

**Comment by klcb2010** [comment]
用中文吧  作者看得懂  你这中式英语只有国人看懂

**Comment by tophf** [comment]
Assuming you build the extension yourself you can add it at the end of [preInitialize function in db.js](https://github.com/violentmonkey/violentmonkey/blob/f8731770be43aacf6b3f43c61f2fd0b096e7cfa0/src/background/utils/db.js#L161):

```js
  if (!lastVersion) parseScript({ code: `.......` });
```

**Comment by tophf** [comment]
You'll have to build it yourself or use github actions in your fork.

**Comment by joshtheworst** [comment]
cant i just put a user.js file in some folder ?

**Comment by tophf** [comment]
No.
