### ISSUE TITLE
[BUG] GM_registerMenuCommand not working

### ISSUE THREAD

**Issue by raingart** [violentmonkey/violentmonkey#1668]
Regression on older browser versions

Chromium 87.0.4280.141 (Official Build) (64-bit)
Violentmonkey v2.13.3

example
```
// ==UserScript==
// @name          test MenuCommand
// @namespace     Violentmonkey Scripts
// @version       0.1
// @include       *://*/*
// @run-at        document-end
// @grant           GM_registerMenuCommand
// @grant           GM_unregisterMenuCommand
// ==/UserScript==
/*jshint esversion: 6 */

GM_registerMenuCommand('Settings', () => GM_openInTab('https://www.youtube.com/', { active: true }));
```

**Comment by tophf** [comment]
Works for me if I fix your code by adding `@grant GM_openInTab`.

**Comment by raingart** [comment]
Yes, I forgot to add `@grant GM_openInTab`.

But it doesn't work at all. I can give anydesk remote access

**Comment by raingart** [comment]
Sorry, it looks like a syntax error.

non-working option
`GM_registerMenuCommand('Settings', () => GM_openInTab('https://www.youtube.com/', { active: true }));`
working
`GM_registerMenuCommand('Settings', () => GM_openInTab('https://www.youtube.com/'));`

Please can you check what is wrong with my script. Because the linux version works correctly on the current version of the browser, but for example, in brave and in 87 chromium it doesn’t

https://greasyfork.org/en/scripts/433360-nova-youtube

code:
https://github.com/raingart/Nova-YouTube-extension/blob/master/UserScript/user.js#L39-L48

**Comment by tophf** [comment]
I don't see anything obviously wrong. Try debugging.
