### ISSUE TITLE
Scripts may not close windows that were not opened by script.

### ISSUE THREAD

**Issue by zmni** [violentmonkey/violentmonkey#167]
### What is the problem?
#105, #117 still happened. The window doesn't close.

### How to reproduce it?
1. Choose script to install on greasyfork
2. Click `confirm install` or `close`

### What is the expected result?
Close the window after install script or when the close button clicked.

### What is the actual result?
Window doesn't close, devtool console show error: `Scripts may not close windows that were not opened by script.` `app.js:1:172750`

### Environment
- Browser: Firefox Beta
- Browser version: 55.0
- Violentmonkey version: 2.6.3
- OS: Windows 64bit

**Comment by gera2ld** [comment]
They are fixed in later versions, which has not been published to Firefox because of review problems.
