### ISSUE TITLE
[BUG] quirks with @noframes

### ISSUE THREAD

**Issue by Purfview** [violentmonkey/violentmonkey#1671]
- [ x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
- [x ] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Script sometimes randomly doesn't load and doesn't appear in Violentmonkey's menu of matched scripts.
I refined it down to @noframes, it's like Violentmonkey thinks that the site is iFrame and prevent it from running.

"A" case can be fixed by removing `@noframes` , but then it would need an unclean fix like `window.top === window.self` check.
"B" case I can fix by changing `location.reload()` to `window.location.reload()`. [shouldn't it be same effect?]

**To Reproduce A:**
1. Install the script: https://greasyfork.org/en/scripts/407284
2. Got to https://www.imdb.com/title/tt13678040/reference/
3. If the script loaded: in the same tab go to this url: https://www.imdb.com/title/tt0088247/reference
4. If the script loaded: use Go back/Go forward buttons to switch between both URLs till the script doesn't load.

**To Reproduce B:**
1. Install the script: https://greasyfork.org/en/scripts/407284
2. Got to https://www.imdb.com/title/tt13678040/reference/
3. If the script loaded: open the script's settings then close them [page is reloaded on close - the script doesn't load].

**Environment:**
- OS: Windows7 x64
- Browser: Firefox 
- Browser Version: 107.0.1 (x64)
- Violentmonkey Version: 2.13.3

**Additional context**
No issue with Tampermonkey.
No issue with Waterfox Classic + Violentmonkey.

**Comment by tophf** [comment]
It's probably caused by Chrome's new pre-render, which activates only in certain conditions, which is what makes this behavior seem random. The pre-rendered page uses a non-zero frame id, so our code mistakenly recognizes it as a subframe.

**Comment by Purfview** [comment]
It's so random that it can work/not-work dozens times in a row, first I thought it has something to do uBlock, then that "B" case is 100% reproducible, but those where wrong assumptions.
Maybe it has something to do with random kind of ads IMDb serves.
