### ISSUE TITLE
[BUG] Unable to update userscripts from GitHub release assets

### ISSUE THREAD

**Issue by pointydev** [violentmonkey/violentmonkey#1673]
- [X] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.
- [X] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
I am unable to update a userscript from GitHub release assets as a HTTP 401 is returned. I am able to access the same asset via cURL using `curl -Lv {url}`.

**To Reproduce**
1. Add the following userscript: https://github.com/Vendicated/Vencord/releases/download/devbuild/Vencord.user.js
2. Either attempt to force update the script from the options menu or wait for an auto-update to run

**Expected behavior**
The update check to complete successfully.

**Actual behavior**
Encounter a `Failed fetching update information.` error, accompanied by a notification stating that a 401 was returned:
![401 notification](https://user-images.githubusercontent.com/22241432/206297267-15168d1f-4630-42d5-b147-d7359295b5b9.png)
No errors are visible in the console of the extension background page, however here are the network logs:
![Network logs](https://user-images.githubusercontent.com/22241432/206297831-d4f0f705-e3c7-4555-89ed-6ed0e7563ddf.png)

**Environment:**
- OS: Fedora Linux
- Browser: Google Chrome
- Browser Version: 109.0.5396.2 (Official Build) dev (64-bit)
- Violentmonkey Version: Beta v2.13.3.8 from [CWS](https://chrome.google.com/webstore/detail/opokoaglpekkimldnlggpoagmjegichg)

**Additional context**
The URL being used as the `@updateURL` redirects with a 302 to a location at `https://objects.githubusercontent.com/github-production-release-asset-`, and the query string used between cURL and Violentmonkey differs, specifically `&actor_id=0` being `&actor_id=22241432` (my GH user id) instead.

Thanks,
Elliott

**Comment by tophf** [comment]
Works for me. It's a known problem with github artifacts: the link works only when the user is signed in to github. I don't remember the solution though, maybe you'll have to manually upload the files.

**Comment by tophf** [comment]
Correction: it works for me even if I'm not signed in to github, so apparently it's a different problem.

**Comment by tophf** [comment]
Try reproducing the problem in a different version of Chrome e.g. in the stable 108, maybe it's a bug in the browser.

**Comment by pointydev** [comment]
Just tested using Chrome Stable and Dev on Win 11 22H2 using [BrowserStack](https://live.browserstack.com) with the same VM version from CWS, and curiously userscript updates to the same script above succeed on both versions *until* I log in to GitHub, implying being logged in is the issue for me.

**Comment by tophf** [comment]
> Would it be possible to create an "anonymous mode" setting for script updates, preferably per script?

Only if this is not an external bug in browser or github.

**Comment by pointydev** [comment]
This does appear to be an issue with GitHub's authentication, and weirdly only appears to be affecting my account with the people I've tested with. While this is an external bug (or at least unwanted behaviour) on GitHub's part, it may still be useful to have an anon mode for updating scripts even for sites that aren't GitHub.

**Comment by JAK0723** [comment]
I'm receiving a similar "Failed fetching update information" error for [re621](https://github.com/re621/re621.Legacy), though I'm not getting a 401 notification and nothing's showing in the network log. I have no idea why it isn't working properly, all the URLs appear to be correct.
![image](https://user-images.githubusercontent.com/29014804/229264630-e81b9659-ea90-41a0-9416-70f211f40079.png)

**Comment by tophf** [comment]
@JAK0723, I don't see an error with this script. Try inspecting the network requests in the [background devtools](https://stackoverflow.com/q/38913799).

**Comment by JAK0723** [comment]
@tophf Thank you for telling me about how to access the correct devtools. It does appear to be getting a 401 error after a 302 redirect when attempting to retrieve the script.meta.js of re621.

There's also an error message in the console regarding CSP, though I'm not sure if that's related to the update issue.
![image](https://user-images.githubusercontent.com/29014804/229279926-5d2f9db4-e06e-4855-8ca3-4c579a237eaa.png)

**Comment by tophf** [comment]
The CSP error is not related.

**Comment by alexiayaa** [comment]
I started getting the same error recently? Is there a fix?

The URL in question is https://github.com/solymosi/npu/releases/latest/download/npu.user.js, which is accessible without login normally.
