### ISSUE TITLE
[Feature] use GM_xmlhttpRequest to get GM_getResourceURL data for avoiding CSP

### ISSUE THREAD

**Issue by polyproline** [violentmonkey/violentmonkey#1676]
**Motivation**
https://github.com/violentmonkey/violentmonkey/issues/1666
Violentmonkey doesn't change the site's Content Security Policy
Can we use GM_xmlhttpRequest get the GM_getResourceURL data?

**Proposed Solution**

use GM_xmlhttpRequest get the GM_getResourceURL data
violentmonkey give the GM_getResourceURL data get through Content Security Policy
connect keyword
- self-domain : violentmonkey domain
- main-domain : page url domain
**Use Cases**

```javascript
// @grant	GM_getResourceURL
// @grant	GM_xmlhttpRequest
// @connect self-domain
// violentmonkey domain, such as moz-extension://55062a2b-39b7-4121-afec-90d0bea7968e/
// @connect main-domain
// page url domain, such as https://developer.mozilla.org/
// @resource opencc_wasm https://cdn.jsdelivr.net/gh/polyproline/opencc-wasm@main/opencc_gc.wasm
// ==/UserScript==

"use strict";
let ret = (()=>{
	const url = GM_getResourceURL("opencc_wasm", true);
	const detail = {
		"url":url,
		"method":"GET",
		"responseType":"arraybuffer",
	};
	let control = GM_xmlhttpRequest(detail);
	arr = control.response;
	console.log(arr);
	arr = new Uint8Array(arr);
	console.log(arr);
	return arr;
})();
````

**Comment by tophf** [comment]
No, this won't work, but you can use GM_xmlhttpRequest with the remote resource URL yourself, which would rely on browser caching.

Why don't you just use false in [GM_getResourceURL](https://violentmonkey.github.io/api/gm/#gm_getresourceurl) and then build the Blob? It's what I suggested and is what everyone does, AFAIK.
