### ISSUE TITLE
ViolentMonkey Electron support

### ISSUE THREAD

**Issue by deliciouslytyped** [violentmonkey/violentmonkey#1679]
Can / would / does / could ViolentMonkey work with Electron?
Some supported extensions API information is listed here: https://www.electronjs.org/docs/latest/api/extensions .

(I'm specifically interested in using it with archived pages in the https://github.com/webrecorder/replayweb.page Electron app.)

**Comment by tophf** [comment]
I don't know. Try loading it and tell us if it doesn't work. If there's an error and the fix is simple we can add it, otherwise no.
