### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by rayman89** [violentmonkey/violentmonkey#168]
Violentmonkey seems to be lacking exportFunction and cloneInto and some really useful scripts need that to work are you planing to implement them in the near feature?

**Comment by gera2ld** [comment]
Aren't they Firefox specific features and deprecated in WebExtensions?

**Comment by rayman89** [comment]
>For AdsBypasser to work for all sites, Violentmonkey lacks two key functions: cloneInto and exportFunction. There is no workaround for that. Unless Violentmonkey provides those functions (or any alternative method to deal with X-Ray vision), it is not possible to use AdsBypasser with Violentmonkey.

**Comment by jspenguin2017** [comment]
What? That's nonsense. Which site does not work? I bet I can fix it.

**Comment by jspenguin2017** [comment]
If they don't want to add script host detection, you can just polyfill them: 

```js
const exportFunction = (func, scope, options) => {
    if (options && options.defineAs) {
        scope[options.defineAs] = func;
    }
    return func;
};
const cloneInto = obj => obj;
```

**Comment by gera2ld** [comment]
@jspenguin2017 Wow, is it that simple?

**Comment by jspenguin2017** [comment]
You don't have the security restriction since you are emulating `unsafeWindow` already.

**Comment by quilloss** [comment]
>Aren't they Firefox specific features and deprecated in WebExtensions?

They are Firefox specific but I don't think they are deprecated. It's documented in their WebExtension page.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#exportFunction
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#cloneInto
Using ```window.wrappedJSObject.foo = cloneInto("bar", window);``` in a content script, I managed to inject the object even in a CSP protected page.

>You don't have the security restriction since you are emulating unsafeWindow already.

Does this mean that all scripts including privileged GM_* api run in the page's scope?

**Comment by jspenguin2017** [comment]
@quilloss Yes.

**Comment by gera2ld** [comment]
Closing since this issue does not block adsbypasser any more.
