### ISSUE TITLE
[BUG] script updating quirks

### ISSUE THREAD

**Issue by Purfview** [violentmonkey/violentmonkey#1680]
I got this vague complain from a user:
>If I try to update it via Violentmonkey, it consistently fails. It throws up a prompt that I then have to click to close. Strangely, it then sometimes (but not always) launches the Discogs Scout code in a separate browser tab.
I can manually update from Greasy Fork, though it can take repeated attempts before it does install. This has been going on for the last few versions, dating back at least until the early part of this year.

I tried to repeat what he mentioned, usually it updates normally, sometimes it says that there is no update, few times I got "Fetch Error" [in red], dunno what to make out of this as I never update scripts this way.

Usually I update by opening scripts from my HDD in a browser, and lately few times randomly I get this error: "TypeError: t.then is not a function.".
That error I get after pressing the Confirm button, then pressing it again script updates normally [there is no "t.then" in the actual script].

![alt text](https://i.imgur.com/TIOiYTl.png)

[Script on Github (has @updateURL)](https://github.com/Purfview/Discogs-Scout/blob/main/Discogs_Scout.user.js)
[Script on GF (without @updateURL)](https://greasyfork.org/en/scripts/439452-discogs-scout)

**Environment:**
- OS: Windows 7  (64-bit)
- Browser: Firefox
- Browser Version: 108.0 (64-bit)
- Violentmonkey Version: v2.13.3.9

**Comment by Purfview** [comment]
Btw, reinstall is of the same script without any changes in it.

**Comment by tophf** [comment]
I tried reproducing both problems but couldn't. 

The first error sounds like the user has a network problem or an old version of Violentmonkey. In the new version the notification should show the error that occurred while updating. Clicking the notification indeed opens the editor, it's the intended behavior. Try asking the user to copypaste the contents of [background console](https://stackoverflow.com/a/10258029).

The second error may have a different cause.
Please show an exact sequence of actions or show a screenshot of devtools after doing this:
1. open devtools, switch to `Sources` tab, click the `||` pause button in the toolbar and enable "Pause on caught exceptions"
   ![image](https://user-images.githubusercontent.com/1310400/207638048-9a8ef5c3-f3d7-4bb4-b605-480e7dd9eda3.png)
2. when the error occurs you'll see `t.then` text in the `Scope` panel, otherwise it's a different error
3. click the `{}` to reformat the code

**Comment by tophf** [comment]
I fixed the second error in 9584e1c3, but I don't think it's the reason of the first problem.

**Comment by Purfview** [comment]
> The first error sounds like the user has a network problem or an old version of Violentmonkey. In the new version the notification should show the error that occurred while updating. Clicking the notification indeed opens the editor, it's the intended behavior. Try asking the user to copypaste the contents of [background console](https://stackoverflow.com/a/10258029).

Is there similar guide for Firefox?

Here is what he did answer:

>I'm sending more information, in the hope that it helps. If you need any further information, then let me know.

>The sequence is as follows:

>When checking for updates, via Violentmonkey, to either Discogs Scout alone or when doing a "Check all for updates" (that is, all installed scripts), the error prompt comes up. Immediately thereafter, the script's code opens in another tab. It all happens in the blink of an eye.

>I can suppress both actions with scripts that I have written, though I do still see the briefest of flashes from the error prompt.

>I've indeed been using an old version of Violentmonkey – 2.13.1, to be precise. The reason is that both 2.13.2 and 2.13.3 caused my list of scripts to appear blank.

>I've since installed the latest beta release from Github – 2.13.3.9. This update corrects the blank script issue, but it doesn't solve the Discogs Scout update issue.

>The environment in which I use Discogs Scout:
OS: Windows 7 Ultimate (x64)
Browser: Firefox
Browser versions tested: 98.0 (x64) and 107.0.1 (x64)
Violentmonkey versions tested: 2.13.1, 2.13.2, 2.13.3, 2.13.3.9 (Beta)

>I have 25 scripts installed, and this is the only one that causes this error in Violentmonkey. I'll confirm again that everything runs perfectly with IMDb Scout Mod. This fact, along with investigations on my end, makes me doubt that I have a network problem.

>I'll be very thankful if you could post all, or part of the above for me on GitHub.

**Comment by tophf** [comment]
> Is there similar guide for Firefox?

https://extensionworkshop.com/documentation/develop/debugging/

* enter about:debugging in the URL bar.
* in the left-hand menu, click This Firefox (or This Nightly).
* click Inspect next to your extension.

**Comment by Purfview** [comment]
The user found the cause, here is his msg: 

>Here's something I've discovered:

>Going to IMDB Scout Mod in Violentmonkey, clicking on Edit, and then on the Settings tab, I see this:

>![alt text](https://i.postimg.cc/D0CFjPHd/1.png)

>In Discogs Scout, it looked like this, on initial view:

>![alt text](https://i.postimg.cc/br5WSC4M/2.png)

>As you can see, the Download URL is blank and the Homepage URL doesn't correspond to the pattern of IMDb Scout Mod's. With everything having these values, the update fails.

>I changed the values manually to this:

>![alt text](https://i.postimg.cc/HkXRjtzZ/3.png)

>Now the update works, regardless of Discogs Scout version or Violentmonkey version.

**Comment by tophf** [comment]
It doesn't help me understand what happened. I've checked recent versions of Violentmonkey and it doesn't show `none` in that field. I guess the problem was caused by some old version of Violentmonkey which broke the internal storage for this script. The solution would be to remove the script and reinstall it. The storage of the script can be copypasted in `Values` tab inside the editor.

**Comment by Purfview** [comment]
I think there are some logic quirk in that custom metadata.

1) Start fresh Win7 +fresh Firefox +fresh Violentmonkey in VM.
2) Install v2.4 [Discogs_Scout](https://github.com/Purfview/Discogs-Scout/raw/1855e7d8b1843ddeaeb265eb0434a31a3bde738a/Discogs_Scout.user.js)
3) Press "Check for updates"  button in Violentmonkey. Successfully updated to v2.5.
4) Reinstall v2.5 from GF: https://greasyfork.org/en/scripts/439452-discogs-scout
5) Downgrade to v2.4 [Discogs_Scout](https://github.com/Purfview/Discogs-Scout/raw/1855e7d8b1843ddeaeb265eb0434a31a3bde738a/Discogs_Scout.user.js) from GitHub

**Comment by Purfview** [comment]
I miss-clicked to close it. :)

I've managed to reproduce that "none" issue on  VM.
I did lots of various updates/downgrades mixed from GitHub/GF, not sure what caused it, later I'll try again...
Some logic quirk in that custom metadata.

**Comment by Purfview** [comment]
Refined it to:

1) Install: https://greasyfork.org/en/scripts/439452-discogs-scout
2) Downgrade: https://greasyfork.org/en/scripts/439452-discogs-scout?version=1108564

Now there is "none", and when trying to update it gives "Failed fetching update information." error.

**Comment by tophf** [comment]
greasyfork adds `// @downloadURL none` at the end of the metablock and I'd say it's their bug, but anyway I'll add a test for valid URL in our parser for known xxxURL keys.

**Comment by tophf** [comment]
On the other hand it may be intentional to prevent auto-updates.
