### ISSUE TITLE
[BUG] js is not work!

### ISSUE THREAD

**Issue by xinggsf** [violentmonkey/violentmonkey#1685]
Script:
https://github.com/xinggsf/gm/raw/master/cntv.user.js

the console:
`Uncaught (in promise) TypeError: 0 is not a valid property name
    at Function.getOwnPropertyNames (<anonymous>)`

**Environment:**
- OS: win8.1 x64
- Browser: Chromium 108.0.5359.150
- violentmonkey 2.13.3
- add ad's filter rule: `||player.cntv.cn/h5vod/$script`
- test URL: http://tv.cctv.com/2021/09/29/VIDErf36NcgeWYnGqDUJFn7O210929.shtml

**Comment by klcb2010** [comment]
试一下 BETA v2.13.3.10， 13.3.14还在审核之中

**Comment by tophf** [comment]
Already fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases) and the upcoming 2.13.4.

**Comment by klcb2010** [comment]
> Already fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases) and the upcoming 2.13.4.

新版本violentmonkeyv2.13.4还没发布在火狐插件市场 ，因此这个项目没有完成
