### ISSUE TITLE
[Feature] Infer @supportURL from @homepageURL if @supportURL is missed

### ISSUE THREAD

**Issue by T1mL3arn** [violentmonkey/violentmonkey#1686]
**Motivation**

Too lazy to write `@supportURL` each time I publish my scripts on greasyfork. Since I cannot predict the final link of the published script, I have to go through cycle copy-paste-updatescript to set `@supportURL` to greasyfork feedback page.

**Proposed Solution**

As it is done for `@homepageURL`, infer `@supportURL`.

**Use Cases**

- I make a script with no `@supportURL` 
- user installs/updates the script from greasyfork/github (there might be a lot of other providers though)
- Violentmonkey infer `@supportURL` and sets it to feedback/issues etc
- now the user can jump instantly to support page from dashboard

**Comment by tophf** [comment]
This is already implemented.
