### ISSUE TITLE
[BUG] Missing slash when slash is not required

### ISSUE THREAD

**Issue by garfieldbanks** [violentmonkey/violentmonkey#1689]
`// @match        *://*www.isfdb.org*`

Violentmonkey reports this as a bad match:
`Bad pattern: missing "/" for path in *://*www.isfdb.org*`

A slash is not required to match here.

**Comment by tophf** [comment]
Your pattern is incorrect. The correct one is `*://*www.isfdb.org/*`, see the [documentation](https://developer.chrome.com/extensions/match_patterns).

**Comment by garfieldbanks** [comment]
What if the url was www.somesite.com?some_query

Would violentmonkey still match that? Requiring a slash doesn't seem right..

**Comment by tophf** [comment]
URL internally always has a slash, so it's not a problem. Note that this is how match patterns have worked for 10+ years. The reason why a match pattern should always have a slash is to indicate the end of the host portion explicitly. When each URL is checked against the pattern it is compared separately.
