### ISSUE TITLE
[BUG] `Blob` is `null` of `GM_XHR`

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1691]
My download scripts do not work now because of `Blob` is `null` (the response of `GM_XHR`) after the update to the latest version. (_Sometimes_ they work)

I use the latest v2.13.4.1 built from the sources.

Chromium.

---

Non BETA (Violentmonkey 2.13.4) also have the same bug. `e392724`

---

Violentmonkey BETA 2.13.3.7 works fine.

**Comment by tophf** [comment]
Works for me. Can't do anything without a test script.

**Comment by AlttiRi** [comment]
Okay:
https://github.com/mikf/gallery-dl/issues/2495#issuecomment-1102505269

If it will work (`✅` in the title), disable the cache in the bg script. Also you will see `❌` in the title.

Just checked with the latest chrome with BETA version from the store.

**Comment by tophf** [comment]
Your code is wrong: **a Promise can be resolved just once** and you do it too early (HEADERS_RECEIVED) when the response is not yet received, so when you call `resolve(response.response)` it is ignored.

**Comment by tophf** [comment]
Oops, sorry, you have nested Promises. Gonna investigate further...

**Comment by tophf** [comment]
The bug had two roots, one was simple (dca9578), the other one was an asynchronous race condition, which caused the randomness of behavior.

The only workaround is to remove onreadystatechange/onprogress listeners, unfortunately, so I guess we'll release a new stable version sooner this time, maybe in a week after testing the beta.

**Comment by AlttiRi** [comment]
BTW, to handle the results of async tasks one by one (with the call order) you can use a mutex (semaphore) like this:

```js
class Semaphore {
    constructor(max = 1) {
        if (max < 1) { max = 1; }
        this.max = max;
        this.count = 0;
        this.queue = [];
    }
    acquire() {
        let promise;
        if (this.count < this.max) {
            promise = Promise.resolve();
        } else {
            promise = new Promise(resolve => {
                this.queue.push(resolve);
            });
        }
        this.count++;
        return promise;
    }
    release() {
        if (this.queue.length > 0) {
            const resolve = this.queue.shift();
            resolve();
        }
        this.count--;
    }
}
```

The full demo with multiple requests here: https://github.com/Tampermonkey/tampermonkey/issues/1113#issuecomment-754427095

**Comment by tophf** [comment]
Yeah, it's essentially the same thing I did.

**Comment by AlttiRi** [comment]
Will be a release soon in the Chrome Store?

I think this bug is critical — the scripts do not work, or even worse they may loose some data (the script can show that something was downloaded, but due to the bug it was not downloaded.)

And that bug is notable https://github.com/violentmonkey/violentmonkey/issues/1697
