### ISSUE TITLE
[BUG] [Firefox] `GMxmlhttpRequest` API, when set `onerror:` or `ontimeout:`, can not return correct value. `BETA 2.13.4.1`

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1692]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
I reported issue #1665 three weeks ago, but I installed beta 2.13.4.1 today and found a new issue where adding "onerror" or "ontimeout" when using the "GMxmlhttpRequest" API will return an error value instead of the correct value, regardless of whether GMxmlhttpRequest returns the correct value.

**Expected behavior**
Please fix it.

**Actual behavior**
Please try the follow code, in the URL: https://cn.bing.com/search?ensearch=1&q=yahoo
```js
// ==UserScript==
// @name        New test script
// @namespace   Violentmonkey Scripts
// @match       *://*.bing.com/*
// @grant       GM_xmlhttpRequest
// @version     1.0
// @author      -
// @description Thu Dec 22 2022 22:00:46
// @run-at      document-start
// ==/UserScript==

(function(){
  setTimeout(()=>{
    const requestNodes = document.querySelectorAll("#b_results a[href*='.bing.com/ck/a?']");
    requestNodes.forEach(node => {
      const url = node.href;
      return new Promise((resolve, reject) => {
        GM_xmlhttpRequest({
          url: url,
          headers: { Accept: "*/*", Referer: location.href },
          method: "GET",
          timeout: 8e3,
          onreadystatechange: response => {
            if (response.status === 200 && response.readyState === 4) {
              const resText = response.responseText || response.response || "";
              resolve(resText);
            }
          },
          onerror: reject(new Error(`ON ERROR`)),
          ontimeout: reject(new Error(`ON TIMEOUT`)),
        });
      })
        .then(res => {
         console.log(res);  // Only receive error feedback unless 'onerror:' or 'ontimeout:' is removed
        })
        .catch(e => {
         console.error(e);
        });
    });
  },1000)
})()
```

**Environment:**
- OS: [e.g. macOS] win10
- Browser: [e.g. chrome, safari] Firefox
- Browser Version: [e.g. 22] 108.0.1
- Violentmonkey Version: BETA 2.13.4.1 

**Additional context**
nope.

**Comment by tophf** [comment]
Your code is incorrect: `reject(` should be `() => reject(`

**Comment by F9y4ng** [comment]
> Your code is incorrect: `reject(` should be `() => reject(`

... it's my fault. 😂
