### ISSUE TITLE
[Feature] Site-specific storage sandboxing

### ISSUE THREAD

**Issue by steponmepls** [violentmonkey/violentmonkey#1695]
**Motivation**

I would like to be able to contain the settings stored by an userscript within a domain. Currently the storage is shared between websites meaning that if an userscript is compatible with more than one website, it's going to use the same storage (and in my case the same settings) with all the websites listed in the `@include` rules possibly applying settings/custom styling that would make no sense normally.

**Proposed Solution**

A checkbox in the `Settings` tab that will force Violentmonkey to generate new sandboxed settings for each website in the `@include` list when you visit them for the first time.

**Use Cases**

Every cross-site userscripts would benefit. No code rewrite required. For example I would be able to set site-specific styling without risking to break anything in other supported websites. Or maybe having site-specific keyword filter rules that would not affect other supported websites. Naturally one could code the logic himself making these distinctions but what if you are working with different userscripts made by different people? I believe sandboxing would be the quickest workaround.

**Comment by tophf** [comment]
Generally we don't implement non-standard behavior or new API. Only sometimes we make an exception for something really popular or trivial to implement or for a feature present in other userscript managers, but this is not such a case.

You can implement this behavior yourself by using `location.hostname` as a key in storage. The only disadvantage compared to your suggestion is that the entire script storage is sent currently into the tab, although that would be a problem only if the data is particularly big, in which case you should probably convert your userscript into a separate extension as it'll be much more performant.
