### ISSUE TITLE
[BUG] Changes to script won't be effective until Chrome restart

### ISSUE THREAD

**Issue by mon-jai** [violentmonkey/violentmonkey#1697]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

Starting from about a month ago, changes to scripts, including script body and match rules, won't be effective immediately.

I had to manually restart current Chrome profile to make the change to take effect.

**To Reproduce**

1. Edit a script

**Expected behavior**

The change is effective immediately after saving.

**Actual behavior**

The change is not effective until Chrome is restarted manually.

**Environment:**
- OS: Windows
- Browser: Chrome
- Browser Version: 108.0.5359.125
- Violentmonkey Version: 2.13.4.2

**Comment by tophf** [comment]
Works for me. Please 1) verify the problem exists in a new browser profile without other extensions and 2) provide a more detailed instruction.

**Comment by mon-jai** [comment]
1. Yes.
2. Maybe I record a video for you?

**Comment by tophf** [comment]
It's best to describe it as text and provide an example userscript.

**Comment by tophf** [comment]
Also note that saving never applied the change immediately: you need to [re]load the website tab. Assuming you know and do that, try finding the last beta that works for you.

**Comment by mon-jai** [comment]
Violentmonkey should output "foo" in the following example, but nothing happened.

https://user-images.githubusercontent.com/91261297/209558104-d34217ef-1425-4451-956f-63917a806b0a.mp4

**Comment by mon-jai** [comment]
> Also note that saving never applied the change immediately: you need to [re]load the website tab. Assuming you know and do that, try finding the last beta that works for you.

I did.

**Comment by tophf** [comment]
Maybe the URL is incorrect: Chrome hides `www.` by default. Right-click the address bar and enable "Always show full URLs", then adjust your `@match` accordingly.

**Comment by mon-jai** [comment]
The script was created by pressing the "+" button in Violentmonkey popup, so the match rule should be correct.

**Comment by mon-jai** [comment]
Another example.

After editing the script, Violentmonkey didn't print "bar", throw an error instead.

https://user-images.githubusercontent.com/91261297/209560652-3a5626c7-71db-49b2-9d02-cb5b755feaa9.mp4

**Comment by AlttiRi** [comment]
Set `Site access: On all sites`.

![image](https://user-images.githubusercontent.com/16310547/209560627-c6ced990-022d-4d72-ade2-5ab175ff0531.png)

**Comment by mon-jai** [comment]
That is the default I think.

![image](https://user-images.githubusercontent.com/91261297/209560753-4c528b1f-a1d6-4ce0-8d63-e4f74982c1af.png)

**Comment by tophf** [comment]
I can reproduce the problem now. Weirdly it only happens with an extension installed from the web store. Gonna investigate...

**Comment by AlttiRi** [comment]
![image](https://user-images.githubusercontent.com/16310547/209561226-05c90236-f186-4b42-86d8-4862741c34b2.png)

**Comment by tophf** [comment]
Until a new version is released, the workaround is to have at least one other script that matches the site like a dummy global script that applies to all sites.

**Comment by F9y4ng** [comment]
> Until a new version is released, the workaround is to have at least one other script that matches the site like a dummy global script that applies to all sites (warning: you'll need to disable and enable the extension once to clear the bugged state).
> 
> Another workaround is to temporarily use the [fixed build](https://github.com/violentmonkey/violentmonkey/suites/10060530034/artifacts/489715226) as an unpacked extension.
 
(Chrome108 & VM2.13.5)

I've had the same problem, but I can't figure out what cause that. I'm not sure if it happened by accident after manually modifying the code.

**Comment by tophf** [comment]
I've just encountered this too and hopefully fixed in the new beta v2.13.5.1.

**Comment by F9y4ng** [comment]
> I've just encountered this too and hopefully fixed in the new beta v2.13.5.1.

Just now I reproduced the problem, and I got this error when I refreshed the page after modifying the code, but not every time I modified it. I'm not sure if I found the real cause.

![error](https://user-images.githubusercontent.com/15855068/210707769-07b580c1-3d7f-4c5a-bacc-f60f5f4a242a.png)

**Comment by tophf** [comment]
Yes, it's the same symptom.

**Comment by tophf** [comment]
Did you see it in v2.13.5.1?

**Comment by F9y4ng** [comment]
> Did you see it in v2.13.5.1?

v2.13.5 in Chrome 108.0.5359.125

**Comment by F9y4ng** [comment]
> Did you see it in v2.13.5.1?

Yes, I found it in v2.13.5.1, still the error of refreshing the page after editing the code, but not every time, randomly.

![2023-01-06 121249](https://user-images.githubusercontent.com/15855068/210929035-1fc5937b-18ca-465b-83d1-c7f2c4d872bf.png)

**Comment by tophf** [comment]
I've added a tentative fix in v2.13.5.2.
