### ISSUE TITLE
[BUG]Why my webdav can't be used in Firefox 108.0.1?

### ISSUE THREAD

**Issue by mind-dance** [violentmonkey/violentmonkey#1698]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [ ] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Environment:**
- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]
- Violentmonkey Version:

**Additional context**

**Comment by tophf** [comment]
Check if this is fixed in beta.
