### ISSUE TITLE
Iridium (YouTube layout script) not working in FF Violentmonkey

### ISSUE THREAD

**Issue by eberhardweber** [violentmonkey/violentmonkey#170]
### What is the problem?

The YouTube new layout script [Iridium](https://github.com/ParticleCore/Iridium) does not currently work in Firefox (55.0) using Violentmonkey (2.6.3).

The problem seems to stem from an incompatibility, as Tampermonkey apparently loads the script fine. I tried opening an issue on Iridium's github page, but the script author does not currently support anything other than Tampermonkey at this juncture.

Perhaps there's something that could be done in Violentmonkey to support the script? :) I see it being very popular like [YouTube+ (Particle)](https://github.com/ParticleCore/Particle) used to be, and would love to use Violentmonkey instead of Tampermonkey in the future because it is open source, and frankly awesome.

### How to reproduce it?
1. Create new Firefox profile
2. Go to http://www.youtube.com/new to turn on new Youtube layout
2. Install Violentmonkey
3. Install [Iridium](https://github.com/ParticleCore/Iridium)

### What is the expected result?

Iridium icon should show up and the website https://www.youtube.com/iridium-settings should load Iridium settings.

### What is the actual result?

Iridium icon does not show up and https://www.youtube.com/iridium-settings gives a 404.

Web Console gives the following error on the above website:

> Use of Mutation Events is deprecated. Use MutationObserver instead.  iridium-settings:31:1

### Environment
- Browser: Firefox
- Browser version: 55.0
- Violentmonkey version: 2.6.3
- OS: Win 7 64-bit

**Comment by SW1FT** [comment]
Not just that script, [this](https://greasyfork.org/en/scripts/13169-firefox-for-desktop-list-fixed-bugs-in-mercurial-as-sortable-table) also doesn't work, but works on Tampermonkey just like Iridium.

**Comment by d4k0** [comment]
Same problem here.

**Comment by seiterseiter** [comment]
Same here.

**Comment by CorePoint** [comment]
The cause of this already has a bug report here.
https://github.com/violentmonkey/violentmonkey/issues/173

Mentioned here.
https://github.com/ParticleCore/Iridium/issues/101

**Comment by d4k0** [comment]
I just tested it with Firefox 55.0.3, Violentmonkey 2.8.8 and Iridium 0.2.4b and it seems to work again.

**Comment by NudeSpoons** [comment]
@gera2ld Label? Assign? Respond? Close?

**Comment by tophf** [comment]
Seems to be working fine now.
