### ISSUE TITLE
[Feature] Online full backup (not sync)

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1702]
**Motivation**

I lost everything after a crash. I have scripts that collect data.  Days of collected data and some scripts are lost forever. I have a zip fle but it is a few days old, which is painful to say the least.

**Proposed Solution**

Daily automatic time stamped online zip backup (not sync). So you have a collection of backups. Currently, total backup is done manually. It should auto-delete backup older than x-time (my prefrence is a month). Also backup on press of a button,

**Comment by tophf** [comment]
You can configure Sync to use WebDAV and install some local WebDAV server, then you can back up this local data any way you like.

**Comment by tophf** [comment]
Sync actually is a full backup.

You can configure Sync to use WebDAV and install some local WebDAV server, then you can back up this local data any way you like.

You can also configure a daily backup of your entire disk or just the data directories. I do it for the past ~20 years and indeed losing important data is a necessary step before people actually get to configure it.
