### ISSUE TITLE
[BUG] scripts disappeared

### ISSUE THREAD

**Issue by privacyguy123** [violentmonkey/violentmonkey#1706]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
After update all scripts missing in UI - they still seem to be working in the background.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Open FireFox
2. Open VM UI
3. ???

**Expected behavior**
I expect to see all the scripts I have installed listed there.

**Actual behavior**

**Environment:**
- OS: Windows 10 
- Browser: FireFox
- Browser Version: 108.01
- Violentmonkey Version: 2.13.5

**Additional context**

**Comment by tophf** [comment]
I can't guess what's wrong from this description. Maybe you can show a video or describe the exact steps. Do you see scripts when you open a site where userscript should run and then click Violentmonkey icon? Do you use Custom CSS in settings?

**Comment by tophf** [comment]
Try also this:
1. Check the devtools console of the script manager tab.
2. Open `about:debugging`, click `Inspect` in the card for Violentmonkey, check the devtools console there.

**Comment by privacyguy123** [comment]
> Try also this:
> 
>     1. Check the devtools console of the script manager tab.
> 
>     2. Open `about:debugging`, click `Inspect` in the card for Violentmonkey, check the devtools console there.

Some weird stuff in here I don't understand.

![image](https://user-images.githubusercontent.com/50337995/210786481-5f0ec892-8db5-4bf7-b454-c20fc437a3a9.png)

**Comment by privacyguy123** [comment]
> I can't guess what's wrong from this description. Maybe you can show a video or describe the exact steps. Do you see scripts when you open a site where userscript should run and then click Violentmonkey icon? Do you use Custom CSS in settings?

I don't know how else to explain - all scripts are missing from the UI but seem to be working in the background.

**Comment by tophf** [comment]
The warnings in the screenshot aren't related, they're not a problem. I still can't guess what's wrong, so you'll need to open devtools and follow my instructions above, it's not hard: just right-click the page and click "inspect", then switch to "console", copy the output here if it's there. Then open `about:debugging` in the address bar, click `Inspect` in the card for Violentmonkey, check the devtools console there too.

**Comment by privacyguy123** [comment]
UI with all scripts "invisible"
![image](https://user-images.githubusercontent.com/50337995/210790619-5e11221a-6a1f-4db0-b4be-a039f390dc9b.png)

**Comment by privacyguy123** [comment]
resintalled and fixed, no idea wtf is going on

**Comment by tophf** [comment]
> resintalled and fixed

That's great.

Unfortunately there were no relevant errors in the screenshots so I guess it might have been a bug in Firefox itself while updating the extension.

**Comment by monarchwadia** [comment]
I'm also experiencing exactly this issue. There is a script in my ViolentMonkey that I really need to retrieve, otherwise I'll lose work... so I cannot reinstall. Weird thing is, the script works just fine on the target URLs.

**Comment by monarchwadia** [comment]
Maybe these repro steps will work. I'm not really sure, but it's close to what I did right before the scripts disappeared.....

1. Create a script
2. Test it thoroughly
3. Restart firefox
5. Go to edit the script. Make some changes but dont save.
6. Restart firefox. Scripts should (?) be gone.

**Comment by tophf** [comment]
Also, try exporting the file backup in Settings, then if it contains the script you can reinstall.

**Comment by tophf** [comment]
You can also copy the content of the script from devtools of the tab where it runs.

**Comment by monarchwadia** [comment]
@tophf thank you for the quick turnaround! I was able to export the file from Violentmonkey's settings tab. Instructions for posterity:

1. Click Violentmonkey extension icon -> Gear icon (looks like this emoji: ⚙️)
2. Click "Settings" in the left panel
4. Under the "Backup" section, click "Export to zip"
![image](https://user-images.githubusercontent.com/4856944/210821336-0c703dcb-ff5c-4149-ad47-68497990b4ac.png)
6. The script will be included as a *.js file in the zip
![image](https://user-images.githubusercontent.com/4856944/210821802-6bacdf8c-2133-4cba-95c5-d9c32f31b52e.png)

**Comment by monarchwadia** [comment]
@tophf apologies, I have lost access to the error now. If it appears again, I will drop a screenshot.

**Comment by tophf** [comment]
Since the error contains `img` it must be from an icon.

**Comment by monarchwadia** [comment]
Given that the list of scripts disappears, perhaps its one of these icons in this component.

![image](https://user-images.githubusercontent.com/4856944/210838464-90ecb012-4653-4b72-b00a-035da28156d7.png)

**Comment by tophf** [comment]
Hmm... Maybe you have some option enabled that breaks `Canvas` API used by our UI to speed up icons. I'll add a check for this, which will fix the problem in the future.

**Comment by LummoxJR** [comment]
This same bug also prevents accessing the list of scripts in use and/or available on any given site when clicking the Violentmonkey icon. This makes it impossible to turn scripts on and off. We need a new release ASAP.

**Comment by tophf** [comment]
Can someone install the [new beta](https://github.com/violentmonkey/violentmonkey/releases) and verify it fixes the bug?
You can also go back to an [old working version on AMO](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/).

**Comment by piquark6046** [comment]
It seems that the new beta version works correctly.

**Comment by Lhorzz** [comment]
I'm having the same problem since yesterday, but some scripts stopped working. 
I've also tried reinstalling, but it stays the same, and it shows nothing when I look at the the scripts page.

**Comment by titoCA321** [comment]
Having the same issue as described above.
