### ISSUE TITLE
[BUG] Firefox Android doesn't show `Sync` section in settings

### ISSUE THREAD

**Issue by klcb2010** [violentmonkey/violentmonkey#1707]
系统：安卓10
浏览器：火狐测试版和每夜版

Firefox Beta108.0b5上测试 能看到暴力猴名称，但看不到“同步”相关内容（图一）；在Firefox Nightly110.0a1 上 可以正常使用同步，但是看不到暴力猴名称名称，只能看到当前生效脚本数量（图二）
![微信截图_20230105214430](https://user-images.githubusercontent.com/32628414/210794890-f4dab4bc-5544-4a22-a731-df6a5a439085.png)
![微信截图_20230105214415](https://user-images.githubusercontent.com/32628414/210795282-23a03ffe-f7c1-46f7-8fe9-dbe0accfba4e.png)

**Comment by tophf** [comment]
This is a known bug in Firefox: it can't resolve __MSG_extName__ in our manifest.json. We could fix it by writing the real value in our build script but it won't support multiple languages so the name will be wrong in Chinese which is currently `暴力猴` not `Violentmonkey`.

**Comment by tophf** [comment]
BTW I can't reproduce the first problem, so maybe you could perform remote USB debugging yourself?

![image](https://user-images.githubusercontent.com/1310400/210798038-efbf048f-cdf3-44e0-8ebb-1c783d83adf2.png)

**Comment by klcb2010** [comment]
> 顺便说一句，我不能重现第一个问题，所以也许你可以执行远程USB调试自己？
> 
> ![image](https://user-images.githubusercontent.com/1310400/210798038-efbf048f-cdf3-44e0-8ebb-1c783d83adf2.png)

再次测试 仍然看不到“同步”下的内容，你可以试一下 https://firefoxci.taskcluster-artifacts.net/ILyUK6PpQcGGwhr_zi13ug/0/public/build/arm64-v8a/target.apk

**Comment by tophf** [comment]
It crashes for me in the emulator immediately, I can't debug.

**Comment by klcb2010** [comment]
> It crashes for me in the emulator immediately, I can't debug.

**测试一下更早的版本看看？mobile.v2.fenix.beta.2022.10.31.latest.armeabi-v7a（107B5）  https://firefoxci.taskcluster-artifacts.net/PXUZIR-NQNaQCwjoSg9yrQ/0/public/build/arm64-v8a/target.apk

**Comment by tophf** [comment]
I didn't configure sync though, it was just None.
@gera2ld, maybe you could debug this?

**Comment by gera2ld** [comment]
Sure, I'll take a look this weekend.

**Comment by klcb2010** [comment]
> It runs, but I can't reproduce the problem because Violentmonkey still shows itself in English even though I configured Firefox to use Chinese. I guess this is yet another bug in Firefox Android, so I won't be debugging further.
暴力猴显示英文这个bug来自火狐，我猜你的模拟器只适合使用32位apk，测试这个应该可以复现我的问题，https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.beta.2023.01.04.latest/armeabi-v7a ，辛苦 @gera2ld兄弟测试一下，很抱歉在推特打扰你了

**Comment by klcb2010** [comment]
新问题，他不会显示已经生效的脚本 
![Screenshot_2023-01-07-00-54-26-891_org mozilla firefox_beta](https://user-images.githubusercontent.com/32628414/211060333-07c74ca6-9c7c-47c8-9437-460aab378b05.jpg)

![Screenshot_2023-01-07-00-54-33-268_org mozilla firefox_beta](https://user-images.githubusercontent.com/32628414/211060278-f444fba8-27f3-4883-8ce5-a9d938fa4912.jpg)

**Comment by gera2ld** [comment]
Tested on latest Firefox Beta and Nightly, both issue cannot be reproduced (stably).

I encountered the empty name issue for a while, and then it suddenly worked with perfect locale support. So it's more like a Firefox bug and nothing much we can do.

As for the sync issue, there might be a chance that the data is not properly loaded (possibly corrupted?). But I cannot debug it since I cannot reproduce it. @klcb2010 could you try backing up your data and restoring into a freshly installed Firefox?

**Comment by klcb2010** [comment]
> Tested on latest Firefox Beta and Nightly, both issue cannot be reproduced (stably).
> 
> I encountered the empty name issue for a while, and then it suddenly worked with perfect locale support. So it's more like a Firefox bug and nothing much we can do.
> 
> As for the sync issue, there might be a chance that the data is not properly loaded (possibly corrupted?). But I cannot debug it since I cannot reproduce it. @klcb2010 could you try backing up your data and restoring into a freshly installed Firefox?

可能是测试环境的区别？我手机安卓10系统，浏览器是mobile.v2.fenix.beta.2023.01.06.latest.arm64-v8a,我提供官方软件链接(https://firefoxci.taskcluster-artifacts.net/aXl9hqhPRjGNMUZiC_vZyg/0/public/build/arm64-v8a/target.apk)你再试试一下？或者用我的钛备份导入程序和数据，测试链接是 https://www.52pojie.cn/forum-65-1.html

**Comment by gera2ld** [comment]
Can you reproduce the issue with a **fresh installation** of the latest official version (either Beta or Nightly, installed from Google Play or the offical website)? If the issue persists, it is likely a bug, otherwise it's external and we cannot help.

BTW please add English description when possible so that it can help other people with similar problems.

**Comment by klcb2010** [comment]
> Can you reproduce the issue with a **fresh installation** of the latest official version (either Beta or Nightly, installed from Google Play or the offical website)? If the issue persists, it is likely a bug, otherwise it's external and we cannot help.
> 
> BTW please add English description when possible so that it can help other people with similar problems.

The version I installed(either Beta or Nightly) is the latest version of the official website(https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix). the  release version in Firefox Android doesn't  support violentmonkey.did you test the titanium backup I provided without finding any problems?

**Comment by gera2ld** [comment]
OK, I suppose we are using the same version of Firefox Beta (109.0b6). But I still cannot reproduce the issue.
Sorry I'm not able to use Titanium backup.

**Comment by klcb2010** [comment]
It's strange. When I clear the data of beta , reinstall the ViolentMonkey, and the Sync section  comes back, I think it will happen with a certain probability.now it's working  well ,i'm sorry to have taken up your weekend.

**Comment by tophf** [comment]
Ah, so it may be caused by an incompatible value in the storage.
We should check it probably or at least guard via try/catch.

**Comment by gera2ld** [comment]
Maybe we should implement a way to export `browser.storage` directly for debugging such issues.
