### ISSUE TITLE
[BUG] `page` injection mode stopped working after updating to v2.13.5

### ISSUE THREAD

**Issue by mikelei8291** [violentmonkey/violentmonkey#1708]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Scripts cannot be injected with the `page` injection mode after updating to v2.13.5. All scripts were being injected using the `content` mode, while setting the mode to `page` manually would make all scripts fail to inject to the webpage, even when the CSP of the page allowed such injection.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Update the extension to v2.13.5
2. Set the injection mode to `page`
3. Scripts failed to be injected

**Expected behavior**
Scripts being injected in the `page` mode.

**Actual behavior**
Scripts didn't inject into the page at all.

**Environment:**
- OS: Windows 10
- Browser: Firefox
- Browser Version: 109.0b6
- Violentmonkey Version: v2.13.5

**Comment by tophf** [comment]
@gera2ld, this is pretty bad because it breaks scripts that override various stuff in page context so I'd say we should make a new release sooner this time, the sooner the better...

**Comment by mikelei8291** [comment]
Just curious, is there any active beta testers? I think it should be quite obvious for people to spot the issue but it still got into a stable release.

**Comment by tophf** [comment]
Apparently there aren't.

**Comment by tophf** [comment]
I've added a link to beta in our listing on AMO, hopefully it'll attract more testers.

**Comment by mikelei8291** [comment]
That's nice. I'll also switch to the beta version to see if I could prevent bugs like this getting into the stable release in the future.

**Comment by purple512** [comment]
Whew, okay good to see this was reported and fixed. I thought I was going insane, I was bashing my head against the wall wondering why properties of window/unsafeWindow were not set and I couldn't see any in the debugger.

I reverted back to the previous stable and disabled automatic updates, will check back again later after the fix has made its way to AMO.

**Comment by tophf** [comment]
FWIW you can also install the newest beta instead of reverting.

**Comment by kellnerd** [comment]
The new beta version (2.13.5.2) has resolved all the issues I had with my own userscripts and many others which access properties of `window`.

**Comment by makyen** [comment]
In addition to page mode injection not working, I also found with 2.13.5 that userscripts with an `@require` were injected using "content" mode when "auto" was selected for "Default injection mode". This, of course, resulted in a number of them not working.

A workaround for that was to check "Synchronous page mode". With "Synchronous page mode" checked, it appeared both that userscripts with an `@require` used page mode for injection and that page mode injection worked.

Brief testing with the current beta version, indicated that *both* userscripts with `@require` were identified to use page mode when "auto" was selected for "Default injection mode" *and* that page mode did inject userscripts. It was no longer necessary to have "Synchronous page mode" checked. Given that the current beta appears to resolve this associated issue, I'm not creating a separate issue for it.

**Comment by mikelei8291** [comment]
It seems that in the latest beta v2.13.5.2 when the default injection mode was set to `auto` in the settings, some scripts were still being injected with `content` mode, even if they could be injected with `page` mode when the default mode was set to `page`. The issue described by @makyen may still exist.

**Comment by tophf** [comment]
Indeed, there was a bug when every script for this page ran at document-start or document-body.

**Comment by mikelei8291** [comment]
Thanks for the quick fix. However the version available on AMO is still 2.13.5. Since you didn't release a beta version this time, it was quite hard to update the beta version to test the fix. It's also not possible to install the latest stable version through GitHub release as it's not signed.

**Comment by tophf** [comment]
You can still load it as an unpacked extension. Don't forget to export a backup though.

**Comment by mikelei8291** [comment]
Yeah that's doable but it makes the testing process unnecessarily complicated, and makes it not possible for beta testers to run the beta version as their daily-driver to catch any bug in advance. I think we could have a signed beta version which is a bit ahead of the stable version just for our beta testers to catch bugs in advance, and release stable versions after several days of testing. Also, for this issue I think it's better to just publish the latest stable version on AMO asap.

**Comment by Sollace** [comment]
Do we have an update one when this fix will be in production?

I'm still stuck with none of my scripts running since two weeks ago.

**Comment by Sollace** [comment]
Actually nevermind. Looks like I'm having a separate issue. I'll open a new bug report.

**Comment by tophf** [comment]
It's already released in Chrome. If you use Firefox you can switch to [beta](https://github.com/violentmonkey/violentmonkey/releases). The main release is still in review by Mozilla and their last reviewer didn't approve it because they misunderstood what the code does.
