### ISSUE TITLE
不支持特定的 @-moz-document regexp()

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#171]
https://userstyles.org/styles/138388/discuz-phpwind
`@-moz-document regexp("^https?://[^\/]+/.*((thread-)|(viewthread)).*")`
用 VM 安装，无法自动生成 @include 或 @match

**Comment by gera2ld** [comment]
本来就不会生成`@include`或`@match`啊，这跟暴力猴没啥关系吧。。。
