### ISSUE TITLE
[BUG] injected.js: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ids') `v2.13.5.1 BETA` `2.13.6`

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1711]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
I mentioned this error in this ISSUE :[#1697#issuecomment-1373127570](https://github.com/violentmonkey/violentmonkey/issues/1697#issuecomment-1373127570)

console Error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ids')

I found a way to reproduce this problem in its entirety: 

Env: Brave 1.46.153 Chromium: 108.0.5359.128 - violentmonkey BETA 2.13.5.1 - violentmonkey 2.13.6

**I'm not sure if it's Brave's problem?**

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. switch from Violentmonkey BETA to the release version in the browser extension management
2. then open the Voilentmonkey settings, update the script, prompt no update (in fact, there is an update, but no update is successful)
3. then open any website, and the console reports an error: `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ids')`

**Expected behavior**
Find the real cause and fix it.

**Actual behavior**
### ViolentmonBETA 2.13.5.1:
![ViolentmonBETA 2 13 5 1](https://user-images.githubusercontent.com/15855068/211143989-fcc4dd45-e511-4f38-9796-f0c0235307b4.png)

### Violentmon 2.13.6
![Violentmon 2 13 6](https://user-images.githubusercontent.com/15855068/211143985-e8923180-328b-4d25-8a21-cc3a4045f103.png)

**Environment:**
- OS: [e.g. macOS] Win10 
- Browser: [e.g. chrome, safari] Brave
- Browser Version: [e.g. 22] 108.0.5359.128
- Violentmonkey Version:BETA 2.13.5.1 & 2.13.6

**Additional context**
#1697

**Comment by F9y4ng** [comment]
One more thing, under Brave virentmonkey 2.13.6 will not update the script, even if you update it manually, it keeps prompting that no new version is found, but the new version exists.

**Comment by tophf** [comment]
I can't reproduce the problem. What exactly should I click and do? Does the problem exist on all sites or just a few?

**Comment by tophf** [comment]
Could you find the last beta that works for you and the first that fails?

**Comment by F9y4ng** [comment]
![2023_01_07_18_28_00_658](https://user-images.githubusercontent.com/15855068/211145852-8a8321b2-db9d-4c6e-81fc-1fb1c047c412.gif)

**Comment by gera2ld** [comment]
I can reproduce this issue with the latest master (v2.13.6) in Brave/Vivaldi, but not Chrome/Edge:

- First open Violentmonkey dashboard and leave it there (not sure why this matters)
- Then open https://www.google.com or whatever

![image](https://user-images.githubusercontent.com/3139113/211146745-0eba6069-7990-4180-bd1d-7a00199d8191.png)

**Comment by tophf** [comment]
I still can't reproduce it. In Chrome the bug was probably triggered by e5f85bde or c381e02d but it doesn't make any sense as there's no change in functionality. The fix 2afbd217 that disables declarativeContent also doesn't make any sense but it seems to work.

**Comment by tophf** [comment]
@F9y4ng, try removing the old extension 2.13.5.1 because it still uses declarativeContent, which probably triggers the bug.

**Comment by F9y4ng** [comment]
> @F9y4ng, try removing the old extension 2.13.5.1 because it still uses declarativeContent, which probably triggers the bug.

I also reproduced this error in Chrome, where the script manager only has TM and VM, but the result is the same.

I found that I need to open VM to refresh the page once to close VM (very important). then open TM to refresh the page to close TM. then open VM again, go to the VM settings screen, then go to the page to refresh it will report error 100%.

![2023_01_07_19_54_45_130](https://user-images.githubusercontent.com/15855068/211149629-fe005061-7bd3-4876-b40d-a5f0a52bb7bc.gif)

**Comment by tophf** [comment]
Sorry, I still can't reproduce. Try removing the extension and install it again - maybe the bug is "remembered" by the browser.

**Comment by F9y4ng** [comment]
> Sorry, I still can't reproduce. Try removing the extension and install it again - maybe the bug is "remembered" by the browser.

I removed BETA 2.13.5.1 and 2.13.6 version of VM, Clear browser cache, then reinstall 2.13.6, but error still can reproduce.

![2023_01_07_21_49_30_231](https://user-images.githubusercontent.com/15855068/211154198-f129de51-4e53-49fc-994f-40ad2555f856.gif)

**Comment by tophf** [comment]
Still nothing. Can you reproduce it in a new profile without any other extensions? Can you reproduce it in Chrome in a new profile without other extensions?

**Comment by tophf** [comment]
Oh, I finally managed to do it.

**Comment by tophf** [comment]
I only see it in Brave though, not in Chrome, and it doesn't happen every time.

**Comment by tophf** [comment]
Hmm, I can't really debug it because it happens 1 time out of 100...

**Comment by tophf** [comment]
Can you reproduce it in Chrome in a new profile without other extensions?

**Comment by tophf** [comment]
Hey, I'm dumb. It was indeed caused by e5f85bde. It simplified onMessage listener to be always async regardless of the returned value so now the dashboard's onMessage in handlers.js responded with `undefined` before GetInjected created the real response.

**Comment by tophf** [comment]
Please test the [fixed build](https://github.com/violentmonkey/violentmonkey/suites/10237690502/artifacts/501985885).
The workaround for the bugged versions is to close the dashboard/editor before loading a web page.

**Comment by F9y4ng** [comment]
OK, it works fine now, no TypeError report.

Another question, if I only changed the version number (to a lower version than the current version), why can't I update the code? Not even if  manually click the update button. Does v2.13.6 check for code changes instead of just version numbers?

**Comment by tophf** [comment]
I don't know, it works for me. What are the exact steps?

**Comment by tophf** [comment]
I guess you've edited the script locally. Indeed we only compare the version if the remote file is changed. It's because we don't even fetch the file in such cases: we use the server's HTTP header.

**Comment by tophf** [comment]
This is an edge case though but we can fix it by clearing the remembered value of the remote header when the user edits an updatable script locally. I'll add a fix.

**Comment by F9y4ng** [comment]
It may be due to cache, you need to wait 30 seconds or more after modifying the version number before you can update manually, otherwise it will prompt update not found.

Thank you very much.
