### ISSUE TITLE
[BUG] Wrong order of scripts in pop-up

### ISSUE THREAD

**Issue by jojoPL1987** [violentmonkey/violentmonkey#1712]
**Describe the bug**
The scripts in the pop-up are in the wrong order

**To Reproduce**
1. Violentmonkey >> Settings
2. Select: "execution order" & "Show disabled scripts"
3. Unselect: "Enabled first"

**Expected behavior**
Different order of scripts in the script management window and in the pop-up

**Environment:**
- OS: Windows 10
- Browser: Opera 94.0.4606.54 & Vivaldi 5.6.2867.50
- Violentmonkey Version: 2.13.6

**Comment by tophf** [comment]
These are two different options. The one you describe is for the popup as indicated by the name of the section.

There's another option inside the script list:

![image](https://user-images.githubusercontent.com/1310400/211148448-80f922d9-c7f5-4a49-9d2b-43a4c6ff706f.png)

**Comment by jojoPL1987** [comment]
In this list, I have selected the option: "Sort by: execution order". I also have the execution order set in the pop-up. But ultimately in the pop-up the order of the scripts is different, unknown to me.
https://drive.google.com/file/d/1llCLkx4onADkfnitWkkYat8W0Y-iCbLj/view?usp=sharing

**Comment by tophf** [comment]
I see. The popup displays the final execution order, which means it's grouped by `@run-at`. A script that runs at document-start will always run before scripts at document-body, document-end (the default mode), or document-idle.

I guess we can add another option in the settings: `[x] group by `@run-at`.
