### ISSUE TITLE
[BUG] Firefox doesn't support submit event listeners

### ISSUE THREAD

**Issue by notetiene** [violentmonkey/violentmonkey#1713]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
In Firefox, using ViolentMonkey to attach "submit" events doesn't work (while other events do work).  Chrome isn't affected by this behaviour.

Furthermore, events are not always listed in the inspector depending on the website.  I'm not sure if this is an expected behaviour.

**To Reproduce**
1. Using this userscript:
```js
// ==UserScript==
// @name        Google Test
// @namespace   notetiene
// @match       https://*.google.com/*
// @version     0.0.0
// @grant       none
// ==/UserScript==

document
  .querySelector('form[action="/search"]')
  .addEventListener('submit', (event) => {
    alert('submit event');
    debugger;
  });

document
  .querySelector('form[action="/search"]')
  .addEventListener('click', (event) => {
    console.log('click event');
    debugger;
  });
```
3. Go to https://www.google.com
4. In the console, we can see events by typing the following:
> inspect(document.querySelector('form[action="/search"]'))#
6. Type something in the search bar
7. Press enter to submit

**Expected behavior**
1. Clicking on the input (since it's part of the form) should log a message and pause the debugger
2. Submitting the form should issue an alert dialog and pause the debugger after that

**Actual behavior**
1. Clicking on the input logs a message and pauses the debugger
2. Submitting the form **does not** issue an alert dialog

<details>
<summary>Console logs</summary>

```
Navigated to https://www.google.com/webhp?hl=en&sa=X&ved=0ahUKEwjD0rGW57X8AhWxkmoFHVebCvsQPAgI
Cookie “AEC” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. si
click event Google Test.user.js:19:13
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. webhp:18:174
Navigated to https://www.google.com/search?q=Test&hl=en&source=hp&ei=bpW5Y6YTuKSm1A_96pnACA&iflsig=AK50M_UAAAAAY7mjfqyrue2pNLSLQ6Il4LGwCzYjEuCz&ved=0ahUKEwimgvfC6LX8AhU4kokEHX11BogQ4dUDCAk&uact=5&oq=Test&gs_lcp=Cgdnd3Mtd2l6EAMyCggAELEDEIMBEEMyBAgAEEMyCggAELEDEIMBEEMyCwgAEIAEELEDEIMBMgUIABCABDIICAAQgAQQsQMyBQgAEIAEMgUIABCABDIFCAAQgAQyCwgAEIAEELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoICC4QsQMQgwE6CwguEIAEELEDEIMBUKQGWPMLYOYUaAFwAHgAgAFQiAGjApIBATSYAQCgAQGwAQA&sclient=gws-wiz
```
</details>

**Environment:**
- OS: Ubuntu 20.04
- Browser: Firefox. Chromium works as expected
- Browser Version: 108.0.1, Firefox Nightly 109.0b9, Chromium 108.0.5359.124
- Violentmonkey Version: v2.13.6

**Additional context**
I discovered this bug while make a userscript for disnat.com. I made an other userscript for github, but since it uses suggestion links, I tried to use a simpler example.

**Comment by tophf** [comment]
It's probably a bug in Firefox because `submit` won't work even if I paste this code manually in devtools console.

**Comment by notetiene** [comment]
@tophf thanks for responding.

Given it would be a Firefox bug, any idea how I should report this bug?  It seems to be related to a specific execution mode.  It's been many years since I've touched extensions.

**Comment by tophf** [comment]
There are two things here. The first one doesn't depend on execution mode and happens regardless of the extension. The second one is about "DOM listeners in a content script" of any extension, it's not specific to Violentmonkey and I would expect them to be aware of this missing functionality. Chrome also doesn't show them.
