### ISSUE TITLE
Scripts not loading: "Error: Injection data expired, please reload the tab!"

### ISSUE THREAD

**Issue by GiftWolf** [violentmonkey/violentmonkey#1715]
My scripts only load occasionally. If not, I get the message: "Error: Injection data expired, please reload the tab!" in the console.
The violentmonkey badge then shows no number but the violentmonkey popup lists the scripts under "Matched scripts". However the scripts names are grayed out.

I am using Violentmonkey v2.13.5 and Firfeox 108.0.2

**Comment by tophf** [comment]
You can load this [test build](https://github.com/violentmonkey/violentmonkey/suites/10256835680/artifacts/503298300): open `about:debugging` in address bar, then click "This Firefox" and then "Load Temporay addon". **Export your scripts in Violentmonkey settings beforehand!**

Until a new version is released the workaround for you would be to change some script on this page e.g. edit it or disable and then enable it in Violentmonkey popup, then reload the tab.
