### ISSUE TITLE
[BUG] Doesn't work with overleaf vimrc script (but tampermonkey does)

### ISSUE THREAD

**Issue by eavesjump** [violentmonkey/violentmonkey#1717]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
The semi-official overleaf vimrc script [here](https://www.overleaf.com/learn/how-to/How_can_I_define_custom_Vim_macros_in_a_vimrc_file_on_Overleaf%3F) only works with tampermonkey, not violentmonkey.

**To Reproduce**
1. Install that script
2. Open a document on overleaf in vim mode
3. Press the "h" key and see that the cursor moves left like normal, not down as expected

**Expected behavior**
The script's remapping from "h" to "j" in normal mode succeeds. Pressing "h" moves the cursor down.

**Actual behavior**
The mapping doesn't appear to change anything. "h" moves the cursor left.

&nbsp;

> If this is a bug report, please also provide logs in the console.

What console? I don't see anything that looks relevant in the Browser Console if that's it.

&nbsp;

**Environment:**
- OS: macOS
- Browser: Firefox
- Browser Version: 107.0.1
- Violentmonkey Version: 2.13.5

**Comment by tophf** [comment]
I don't have an overleaf project but it must be the same bug as #1708, [fixed in beta](https://github.com/violentmonkey/violentmonkey/releases). The next release is already submitted and hopefully will be reviewed by AMO soon.
