### ISSUE TITLE
[bug][Android] cannot open dashboard from popup

### ISSUE THREAD

**Issue by klcb2010** [violentmonkey/violentmonkey#1719]
This seems to be an unnecessary step,setting violencemonkey through the menu of Add-on , these steps must be carried out ,It seems that the previous version has no such problem. Is it a new function or a bug?
![IMG_20230112_005755](https://user-images.githubusercontent.com/32628414/211871957-4763bf2b-92ca-4cb1-987a-5100dc872401.jpg)

**Comment by tophf** [comment]
Nothing's changed in that regard but I didn't really understand what you were doing. Maybe you can record a video or gif?

**Comment by klcb2010** [comment]
> Nothing's changed in that regard but I didn't really understand what you were doing. Maybe you can record a video or gif?

Manage all scripts or set violence monkey，through the menu of Add-on.

**Comment by tophf** [comment]
Like I said, nothing's changed, which is why I think I don't understand the problem, so I'm asking to show a screen recording (video or gif).

**Comment by klcb2010** [comment]
> Like I said, nothing's changed, which is why I think I don't understand the problem, so I'm asking to show a screen recording (video or gif).
ah  my  poor  english，i mean  that manage all scripts or set violencemonkey，must use  the Add-on Manager，can't go through the menu of Add-on.

**Comment by tophf** [comment]
Then maybe you can show me how you want it to open? Do you have another extension that provides such method?

**Comment by gera2ld** [comment]
It seems to be a bug, I can reproduce it, let me fix it.

**Comment by tophf** [comment]
Ah, clicking the button doesn't open the dashboard.

**Comment by klcb2010** [comment]
还好他看懂我的中式英语了 😂 期待修复版到来

**Comment by gera2ld** [comment]
Actually it's opened in the background and the popup is not closed.

**Comment by Qussayyon** [comment]
Hi @klcb2010,
Which Firefox accept to run viloentmoneky on android?
