### ISSUE TITLE
At every script update, a tab with violentmonkey dashboard is opened

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#1721]
After the last update 2.13.7, at **every script update**, a tab with violentmonkey dashboard is opened (in addition to the notification below).
I find this slightly annoying behavior in both Firefox and Vivaldi.

**Comment by tophf** [comment]
It's a bug, which I can't reproduce. Normally a notification is displayed that shows which scripts failed to update, and only if you click this notification the dashboard will be opened. Did you see it? Did you click it?

**Comment by tophf** [comment]
You can also disable the `Notify script updates` option in Violentmonkey settings.
