### ISSUE TITLE
Some scripts stop working after a while, entries in the doorhanger mysteriously grayed out

### ISSUE THREAD

**Issue by Atario** [violentmonkey/violentmonkey#1722]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Some scripts stop working after a while, with their entries in the doorhanger mysteriously grayed out.

**To Reproduce**
1.  Have some scripts ready for a page
2.  Verify they're working and displaying normally in the doorhanger
3.  Wait for some time (Hours?  Probably less than a day)

**Expected behavior**
Everything continues normally.

**Actual behavior**
Some scripts stop functioning and the doorhanger shows them grayed out without explanation.

![Screenshot](https://i.imgur.com/OIK7ho6.png)

Reloading the page puts things back to normal again — for a while.

![Screenshot](https://i.imgur.com/ZYTCeVJ.png)

**Environment:**
- OS: Windows 7
- Browser: Firefox
- Browser Version: 108.0.2
- Violentmonkey Version: 2.13.7

**Additional context**
This started within the last few months; before that I never saw this happen.

**Comment by klcb2010** [comment]
你是卡饭的网友？尝试禁用其他扩展 只留下这个试试 我怀疑是你那个S扩展导致问题

**Comment by Atario** [comment]
Pardon?

**Comment by tophf** [comment]
Looks like as #1715, which is already [fixed in beta](https://github.com/violentmonkey/violentmonkey/releases).
