### ISSUE TITLE
Missing XPI builds?

### ISSUE THREAD

**Issue by chocolateboy** [violentmonkey/violentmonkey#1725]
Trying to resolve a startup issue in Firefox which appears to have been [fixed in v2.13.8](), but v2.13.8 isn't available yet on AMO (any idea why?), and the XPIs aren't available to download here for this release or several others, e.g.:

- [v2.13.8](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.8)
- [v2.13.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.7)
- [v2.13.6](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.6)

**Comment by tophf** [comment]
There's no XPI because AMO didn't approve them in time. When we uploaded a new version we or AMO disabled the old one. You can debug the startup using zip builds + webext as explained [here](https://stackoverflow.com/questions/41867515/open-firefox-with-a-temporary-add-on-on-startup).

**Comment by klcb2010** [comment]
It's easy, only needs change *.zip to *·xpi

**Comment by tophf** [comment]
No, renaming won't help because XPI is securely signed by AMO site.

**Comment by klcb2010** [comment]
The premise is to use the userChromeJS modified by xiaoxiaoflood，but this method is not applicable to Android system.
