### ISSUE TITLE
[Feature] Can you add a script dependency?

### ISSUE THREAD

**Issue by klcb2010** [violentmonkey/violentmonkey#1726]
Some scripts need it  (https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js), such as https://greasyfork.org/zh-CN/scripts/370556-%E4%B8%80%E4%B8%AA%E8%BF%94%E5%9B%9E%E9%A1%B6%E9%83%A8%E5%92%8C%E5%88%B0%E8%BE%BE%E5%BA%95%E9%83%A8%E7%9A%84%E6%8C%89%E9%92%AE/code

**Comment by tophf** [comment]
Yes, use `@require`: https://violentmonkey.github.io/api/metadata-block/#require
