### ISSUE TITLE
[BUG] Scripts not loading: "can't convert symbol to number"

### ISSUE THREAD

**Issue by Sollace** [violentmonkey/violentmonkey#1728]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Starting from an update a few weeks ago none of the scripts I have installed have been working. When looking at the pages, I see an error logged (image below) on every site for which I have a userscript installed. For some of them I also have them crossed out with the message "could not inject some scripts" in Violent Monkey's dropdown, but have been able to confirm the console error is printed, and none of them run regardless of this.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. Be on firefox 88.0.1
2. Have Violentmonkey 2.13.7 installed
3. Install the below test script
4. Load any website

```
// ==UserScript==
// @name        Test Script
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description 2023/01/19, 00:04:52
// ==/UserScript==


alert('Test Passed');
```

**Expected behaviour**
You should see an alert saying "Test passed" if the script was applied.

**Actual behaviour**
I do not see any toast and the error "TypeError: can't convert symbol to number" is printed to the developer console.

**Environment:**
- OS: Windows 10
- Browser: FIrefox
- Browser Version: 88.0.1
- Violentmonkey Version: 2.13.7

**Additional context**

![image](https://user-images.githubusercontent.com/6429283/213323656-946bb258-7a24-43ad-9dda-81f4329bf57c.png)

**Comment by Sollace** [comment]
I tested this with injection mode set to `auto`, `page`, `content`, and with `synchronous page mode` on and off just to rule out a possible overlap with #1708 but I've found it has no effect.

**Comment by tophf** [comment]
Our code triggers a bug in this old version of Firefox. This bug is already fixed in the current version of Firefox. I've added a workaround, it'll be in our [next beta](https://github.com/violentmonkey/violentmonkey/releases) soon.

**Comment by Sollace** [comment]
Excellent! Thank you for the hasty fix.
