### ISSUE TITLE
Firefox installed script interface on Android side shows exception[BUG] 

### ISSUE THREAD

**Issue by MrzeroY** [violentmonkey/violentmonkey#1729]
The last script in the single column view is not displayed fully when the script reaches a certain amount, because Firefox does not automatically hide the address bar in this interface

**Comment by MrzeroY** [comment]
![Uploading Screenshot_2023-01-20-04-15-53-50_ffb2f5e1b976ff98cfc94f359fbce8de.jpg…]()

**Comment by MrzeroY** [comment]
![Screenshot_2023-01-20-04-15-53-50_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/90129383/213551282-dda6bd13-aa44-4ad5-9733-d1aef45994cc.jpg)

**Comment by tophf** [comment]
I guess it's because we use absolute positioning. I'll see if we can switch to a standard page + sticky header, so that Firefox handles the bottom part automatically.

**Comment by MrzeroY** [comment]
Thanks for your reply, very strange, I still have this problem when I switch the address bar to the top

**Comment by tophf** [comment]
Position doesn't matter.

**Comment by gera2ld** [comment]
It seems the toolbar will only hide when a body scroll event is triggered. I'll check later.
