### ISSUE TITLE
Only the last modified script visible after closing the editor

### ISSUE THREAD

**Issue by Epyxoid** [violentmonkey/violentmonkey#1731]
I'm using latest Firefox, latest Violentmonkey.

If I modify an installed script, which I always do, and exit from the editor back to the Installed scripts page, then I only saw the script I just closed. It shows that I only have 1 installed script, until I refresh the page, whereupon I can see all my scripts again. I recently noticed that they might show up on their own after a couple of seconds, but not always, most of the time I have to refresh the page.

**Comment by tophf** [comment]
I can't reproduce it. What is the exact version of Violentmonkey and what is the exact sequence of actions?

**Comment by Epyxoid** [comment]
Okay. So Violentmonkey is v2.13.7. And the actions are... Hmm, I'm not sure. It doesn't always happen. (In fact, just recently I did a little edit, saved it and closed it, opened another script (everything was normal), just read it a few seconds, no modification and when I closed it I only saw that one script which I left.) But if I just add a character, save (Ctrl+S), then click on the close button I don't always get it. I guess you have to spend a short time in the editor, maybe do a more extensive edit, couple lines or something, then, for me for sure, if I save (Ctrl+S), then click on the close button then I'll most definitely see only one script in the list.

**Comment by tophf** [comment]
Without a reliable sequence I couldn't find the mistake in our path router code, so I can't fix it without rewriting entirely, but I don't want that as it may introduce new bugs. It'd be helpful if you can find the last [beta](https://github.com/violentmonkey/violentmonkey/releases) that doesn't have this problem (don't forget to export the backup first just in case).

**Comment by tophf** [comment]
You can also test the latest [dev builds](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml?query=branch%3Amaster) by loading them as a temporary extension on `about:debugging` page.

**Comment by Epyxoid** [comment]
I don't know, it's really easy to reproduce to me. Been running into it all the time. I just open a script and edit and save it a couple of times. Spending time in there. And the moment I close it. Boom. One script. And I can even reopen it then close it and it still remains on its own. Only reloading helps.

I hope you found it and that last commit of yours solves the problem! I'm looking forward to it!

**Comment by F9y4ng** [comment]
> I can't reproduce it. What is the exact version of Violentmonkey and what is the exact sequence of actions?

It occasionally happens when editing locally, randomly.

**Comment by klcb2010** [comment]
> > I can't reproduce it. What is the exact version of Violentmonkey and what is the exact sequence of actions?
> 
> It occasionally happens when editing locally, randomly.

it seems  fixed  in  12.3.9,you should check the version of browser
