### ISSUE TITLE
[BUG] Vue3 use of dotAll regexp flag breaks old browsers 

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey#1732]
Vue3 uses regexp `s` flag in many of its files, which is only implemented in Chrome 62 and FF78.
```js
const styleCommentRE = /\/\*.*?\*\//gs;
```

Adding `['@babel/plugin-transform-dotall-regex']` to our babel.config.js only applies it to our code not to vue...

**Comment by tophf** [comment]
Great! One minor problem remains though: apparently babel isn't applied in dev build.

**Comment by gera2ld** [comment]
It actually is applied as per my experiment in old Firefox. Did you still get the same error?

**Comment by tophf** [comment]
The **dev** build still fails in old FF and `common-ui.js` still has `s` flag unchanged.

**Comment by gera2ld** [comment]
Hmm strange, I checked my build and the `s` flag was compiled. Maybe it's because you are using Windows and the slash should be changed to a backslash?

**Comment by tophf** [comment]
The OS shouldn't matter, and it's not our code, this is inside various js files in Vue3 packages.

**Comment by gera2ld** [comment]
Could you try debugging `scripts/webpack.conf.js`? It's us to decide whether a file is going to be transpiled by Babel, including those from Vue.

```js
rule.exclude = file => {
  const result = /node_modules/.test(file) && !/vueleton|@vue\/shared/.test(file);
  console.log(file, result);
  return result;
};
```

**Comment by tophf** [comment]
Ah, you meant the path separator in this condition! Indeed, `\/` should be changed to `[/\\]` to support Windows.

**Comment by tophf** [comment]
So I'll add the commit I guess.

**Comment by liu01983zm** [comment]
> Vue3 uses regexp `s` flag in many of its files, which is only implemented in Chrome 62 and FF78.
> 
> ```js
> const styleCommentRE = /\/\*.*?\*\//gs;
> ```
> 
> Adding `['@babel/plugin-transform-dotall-regex']` to our babel.config.js only applies it to our code not to vue...

downgrade vue version to 3.2.39, version 3.2.47 has the error

**Comment by tophf** [comment]
> downgrade vue version to 3.2.39, version 3.2.47 has the error

We've already fixed the problem, so I don't see the need to downgrade.
