### ISSUE TITLE
[BUG] Error updating scripts

### ISSUE THREAD

**Issue by atyuiloaaga** [violentmonkey/violentmonkey#1741]
### Sequence of actions: 
1. Check the option in VM "notify script updates".
2. Every time when the script is updated, VM is showing the message "error updating scripts" but the script is updated properly.

#### Environment:
- OS: Windows
- Browser: Chrome 109, Firefox 109
- Violentmonkey Version: 2.13.9.1

**Comment by tophf** [comment]
1. Is there any additional text in the message?
2. What happens if you click the message?

**Comment by atyuiloaaga** [comment]
If I clicked in the message, the script code is opening.

![VM Error](https://user-images.githubusercontent.com/124350915/216634907-8fb0320a-551e-4eaf-94db-638668fda477.jpg)

**Comment by tophf** [comment]
I see. So the bug is that we show an incorrect title.
