### ISSUE TITLE
[BUG] On Chrome does not sync scripts from Dropbox

### ISSUE THREAD

**Issue by Cigaras** [violentmonkey/violentmonkey#1746]
**Sequence of actions:**
1. Add Violentmonkey to Chrome
2. Go to Violentmonkey seetings,
3. Set Sync to Dropbox
4. Click Authorize

**Problem:** Dropbox website pops up briefly and closes (I am already logged in there), Violentmonkey button "Authorizing" is grayed out, scripts do not sync

**Devtools console contents:** empty

**Environment:**
- OS: Windows 11
- Browser: Chrome 111.0.5563.8
- Violentmonkey Version: 2.13.9 and 2.13.9.1

**Comment by tophf** [comment]
Try clearing site data/cookies for dropbox.

**Comment by Cigaras** [comment]
I cleared everything, not just Dropbox, and reinstalled Violentmonkey because it was still stuck on "Authorizing", still get same problem – button caption changes to "Authorizing" and nothing happens. Would love to see an error or something.

**Comment by gera2ld** [comment]
It seems their API has changed. I'll fix it soon.
