### ISSUE TITLE
[BUG] Firefox nightly, some scripts dont get injected/are enabled but greyed out.

### ISSUE THREAD

**Issue by SleepDaemon** [violentmonkey/violentmonkey#1761]
### Sequence of actions: 
1. Open Firefox
2. open youtube
3. Shows only # scripts of are running/injected while # are enabled but are greyed out

### Problem: 
![image](https://user-images.githubusercontent.com/88533953/219963413-5f432eba-06dd-4e41-a65b-c64d8caf5dff.png)

#### Devtools console contents:
![image](https://user-images.githubusercontent.com/88533953/219963416-147070d4-e842-436c-b2c2-0a2260b77f79.png)

#### Further Explanation:
Reinstalling the extension and importing my scripts from zip fixes the issues temporarily, but then returns back. The scripts that don't seem to inject are shown in the image below. I apologize if this is not enough information, as I only encountering this issue with YT, and it cannot be scripts need to be updated as I mention if I reinstall the extension itself then everything works fine for little while. It might be firefox made some changes but again it works if I reinstall the extension so I doubt it is a browser issue, and since I reinstalled the extension and it work it seems the issue persists with the extension. I am not saying I am mad, but this issue simply occur only just recently. As it was working fine yesterday, I assume the recent update cause this but I am unsure. If you need more feedback to further diagnose the problem let me know and I can try provide more information.
![Uploading image.png…]()

#### Environment:
- OS: Windows 11 Pro 22H2
- Browser: Firefox nightly 112.0.0.8450
- Violentmonkey Version: v2.13.10

**Comment by tophf** [comment]
It's hard to understand what happens from these screenshots. I guess it's a bug fixed in 2.13.11 via 4ccc1d80. You can verify it's fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases). The bug template should have suggested it, I think.
