### ISSUE TITLE
Can't see errors. I moved from TM to the better VM.

### ISSUE THREAD

**Issue by Coding-Sn4ke** [violentmonkey/violentmonkey#1764]
How can I enable error checking like TM?

I tried searching online and saw that there should be a checkbox similar to TM to enable error checking.

**Comment by tophf** [comment]
There's no such checkbox, we don't have this feature.

**Comment by tophf** [comment]
It's not planned currently either, except for #1312. You can use an [external editor or IDE](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/).

**Comment by Coding-Sn4ke** [comment]
Thanks much appreciated.
