### ISSUE TITLE
[BUG] Large size userscript not loading most of the times

### ISSUE THREAD

**Issue by steponmepls** [violentmonkey/violentmonkey#1765]
### Problem: 
The userscript in question is hosted on github and it's ~11mb in size due to built-in assets encoded in base64 + @requiring an external ~3mb script from a CDN. The problem is that the script doesn't load most of the times (greyed in the list while being toggled on). It works perfectly when it does but the fact that loading is unreliable is what made me open this issue. Is this some browser policy preventing loading of big files?

#### Environment:
- OS: Windows 10
- Browser: Firefox 110.0 (64-bit)
- Violentmonkey Version: 2.13.10

**Comment by tophf** [comment]
Did you try it in beta as suggested by the bug report template? It should be already fixed there.
