### ISSUE TITLE
[BUG] 坚果云webdev同步失败，应该是脚本名称中含有特殊字符问题，删除就成功了，希望改一下同步规则，还有样式问题，见下文

### ISSUE THREAD

**Issue by tianlongJ** [violentmonkey/violentmonkey#1771]
![image](https://user-images.githubusercontent.com/50390874/221073649-0caa1e88-fa5c-4b5e-8c90-2916ef955285.png)
![image](https://user-images.githubusercontent.com/50390874/221073657-d88ef5c0-9872-47f7-bca1-a269e0f70e0f.png)

**Comment by tianlongJ** [comment]
被遮挡了，没有其他东西干扰

**Comment by tophf** [comment]
Same as #1756, fixed in the latest version.

**Comment by tophf** [comment]
As for the problems with synchronization, please describe it in more detail in a new issue.
