### ISSUE TITLE
[BUG] 脚本标题中包含部分特殊字符，用坚果云的webdev同步失败

### ISSUE THREAD

**Issue by tianlongJ** [violentmonkey/violentmonkey#1772]
例如脚本
https://greasyfork.org/scripts/418355-%E8%B6%85%E7%AE%80%E6%B4%81%E7%9A%84%E7%BD%91%E8%B4%AD%E7%9C%81%E9%92%B1%E5%B0%8F%E5%8A%A9%E6%89%8B-%E8%87%AA%E5%8A%A8%E6%98%BE%E7%A4%BA%E4%BA%AC%E4%B8%9C-%E6%B7%98%E5%AE%9D-%E8%81%9A%E5%88%92%E7%AE%97-%E5%A4%A9%E7%8C%AB%E9%9A%90%E8%97%8F%E4%BC%98%E6%83%A0%E5%88%B8%E4%B8%8E%E5%8E%86%E5%8F%B2%E4%BB%B7%E6%A0%BC-%E7%AE%80%E6%B4%81%E6%97%A0%E5%B9%BF%E5%91%8A-%E4%B8%80%E7%9B%AE%E4%BA%86%E7%84%B6-%E8%AE%A9%E6%82%A8%E5%91%8A%E5%88%AB%E8%99%9A%E5%81%87%E9%99%8D%E4%BB%B7-%E6%8C%81%E7%BB%AD%E7%BB%B4%E6%8A%A4%E4%B8%AD/code/!%11%20%E8%B6%85%E7%AE%80%E6%B4%81%E7%9A%84%E7%BD%91%E8%B4%AD%E7%9C%81%E9%92%B1%E5%B0%8F%E5%8A%A9%E6%89%8B%EF%BC%8C%E8%87%AA%E5%8A%A8%E6%98%BE%E7%A4%BA%E4%BA%AC%E4%B8%9C%E3%80%81%E6%B7%98%E5%AE%9D%E3%80%81%E8%81%9A%E5%88%92%E7%AE%97%E3%80%81%E5%A4%A9%E7%8C%AB%E9%9A%90%E8%97%8F%E4%BC%98%E6%83%A0%E5%88%B8%E4%B8%8E%E5%8E%86%E5%8F%B2%E4%BB%B7%E6%A0%BC%E3%80%82%E7%AE%80%E6%B4%81%E6%97%A0%E5%B9%BF%E5%91%8A%EF%BC%8C%E4%B8%80%E7%9B%AE%E4%BA%86%E7%84%B6%EF%BC%8C%E8%AE%A9%E6%82%A8%E5%91%8A%E5%88%AB%E8%99%9A%E5%81%87%E9%99%8D%E4%BB%B7%E3%80%82%E6%8C%81%E7%BB%AD%E7%BB%B4%E6%8A%A4%E4%B8%AD.user.js

包含的特殊字符如图
![图片](https://user-images.githubusercontent.com/50390874/221166467-6d4b3a4d-53de-4ae4-9e28-e50e9d9a8bc0.png)

**Comment by tophf** [comment]
Until we fix the problem, try opening this script in Violentmonkey editor and specify a custom name:

![image](https://user-images.githubusercontent.com/1310400/221169020-2b5a75d1-654c-4bd2-b9ca-9d1a98516aac.png)

**Comment by tianlongJ** [comment]
> Until we fix the problem, try opening this script in Violentmonkey editor and specify a custom name:
> 
> ![image](https://user-images.githubusercontent.com/1310400/221169020-2b5a75d1-654c-4bd2-b9ca-9d1a98516aac.png)

我直接改了代码里name的三个部分才解决，只改settings的name没有用，不过还是非常感谢您，期待修复😁

**Comment by klcb2010** [comment]
> > Until we fix the problem, try opening this script in Violentmonkey editor and specify a custom name:
> 
> 我直接改了代码里name的三个部分才解决，只改settings的name没有用，非常感谢您，期待修复😁

建议修改成英文，在线翻译那种也行，方便有同样问题的人看到解决方案。

**Comment by tianlongJ** [comment]
> > > Until we fix the problem, try opening this script in Violentmonkey editor and specify a custom name:
> > 
> > 
> > 我直接改了代码里name的三个部分才解决，只改settings的name没有用，非常感谢您，期待修复😁
> 
> 建议修改成英文，在线翻译那种也行，方便有同样问题的人看到解决方案。

okok

**Comment by tianlongJ** [comment]
I deleted the special characters after @name, @name: zh, @name: zh-TW in the code, and it is useless for me to modify only the name in the settings

**Comment by gera2ld** [comment]
will be fixed in #1306

**Comment by peasoft** [comment]
Long script name will cause the problem too. My solution is: Copy original `@name` to custom `@name` in settings, and change original `@name` to a short name. Violentmonkey always use `@name` in the code as the name to sync.
