### ISSUE TITLE
[BUG] `Find script for site(GF)` does not work

### ISSUE THREAD

**Issue by alice0775** [violentmonkey/violentmonkey#1773]
Regression window:
Bad: Version 2.13.10
Good: Version 2.13.9

Steps to reproduce;
1. Start Firefox110.0 with new profile
2. Install the addon from https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
3. Open Web site(e,g www.google.com) 
4. Click `Unified extension button` and `Violentmonkey`
5. `Find script for site(GF)`

Actual results:
Nothing happens

Expected results:
`greasyfork.org` should open in new tab.

**Comment by alice0775** [comment]
wfm on version 2.13.12b

**Comment by tophf** [comment]
It's already fixed, please update.
