### ISSUE TITLE
[BUG] `openInTab()` with data URL or blob URL does not work in Firefox

### ISSUE THREAD

**Issue by chipzhang** [violentmonkey/violentmonkey#1778]
## Behavior

When calling `openInTab()` with a data URL or blob URL using Firefox, there should be a corresponding new tab open, but actually nothing happens.
Also, it works fine in Chrome.

## Specifications

- Firefox: 102.8.0esr (64-bit)
- VM: v2.13.11
- OS: Linux

## Example Script

```js
// ==UserScript==
// @name              Example
// @namespace         https://github.com/chipzhang
// @author            ChipZhang
// @match             *://*/*
// @version           0.0.1
// @run-at            document-end
// @grant             GM_openInTab
// ==/UserScript==

function openDataInTab(text) {
	const blob = new Blob([text], {type: 'text/plain'})
	const url = URL.createObjectURL(blob)
	GM_openInTab(url)
}

openDataInTab('abcdefg')

```

This example only demonstrates the blob URL, but data URLs do not work either.

**Comment by tophf** [comment]
Firefox developers think you don't have the right to open it https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#:~:text=For%20security%20reasons
