### ISSUE TITLE
Align "Keep original" text to the left

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1779]
Currently it looks so:
![Screenshot_1](https://user-images.githubusercontent.com/16310547/222886829-45eb8623-fb3e-47bf-812e-175e51810b15.png)

I think, I would a bit more correct:
![Screenshot_2](https://user-images.githubusercontent.com/16310547/222886920-01a44d50-3067-41fa-a365-243d62aeeec0.png)

Just a suggestion.

**Comment by tophf** [comment]
It is intentional to make it stand out. Ideally it should be in a second column but some languages like German have ridiculously long translations.
