### ISSUE TITLE
[Feature] Is it possible for `GM_info.platform` to output JSON in the same format as `navigator.userAgentData`?

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1785]
Similar to the following format:
```JSON
{
    "architecture": "x86",
    "bitness": "64",
    "brands": [
        {
            "brand": "Chromium",
            "version": "110"
        },
        {
            "brand": "Not A(Brand",
            "version": "24"
        },
        {
            "brand": "Google Chrome",
            "version": "110"
        }
    ],
    "mobile": false,
    "model": "",
    "platform": "Windows",
    "platformVersion": "10.0.0",
    "uaFullVersion": "110.0.5481.178"
}
```

**Comment by tophf** [comment]
Why? This format is the most retarded thing I've ever seen in the web platform.

**Comment by tophf** [comment]
I mean specifically navigator.userAgentData and its brands.

**Comment by F9y4ng** [comment]
I think whether the format is ugly or not is secondary, but if the output JSON format is all similar, can judge with minimal code to obtain the real client information. Each manager has a different format, which invariably adds a lot of unnecessary work.

I asked @derjanb the same question yesterday and he thought it was acceptable. 

what do you think?   :-)

**Comment by tophf** [comment]
1. I disagree you need "a lot of unnecessary work" to process different userscript managers. It's just a few statements.
2. Even if Tampermonkey and Violentmonkey implement it there will be other userscript managers that do it differently.
3. The userAgentData API is just objectively bad.

I don't mind if a good universal format is agreed upon.

**Comment by F9y4ng** [comment]
> I don't mind if a good universal format is agreed upon.

Um. . .well, I think I can only propose some primary ideas (such as a ready-made reference), each author has their own code aesthetics, whether it can be unified understanding I think it requires the participation of all, I hope it can be achieved. 

So be it.

**Comment by tophf** [comment]
It's not about esthetics but about objective ergonomics. For example, userAgentData contains nonsensical trash like `Not A(Brand`, there's also no meaning in multiple `brands`.

**Comment by F9y4ng** [comment]
You may have misunderstood my point, it's not about using the userAgentData data, but its structure, and optimizing it by removing the useless data and keeping only what's needed. So that even under FF, you can read the real client-side parameters in a fixed format via VM, TM or other managers, which will reduce a lot of code to determine the different formats, whether the information has been falsified on the client side, etc. 

If it works well, I think the script authors will ask other manager authors to standardize the format.

Everything is difficult at the beginning.

**Comment by tophf** [comment]
No, it's not about difficulty, my point was that userAgentData is trash and should not be reused. I agree that a universal format would be helpful.

**Comment by tophf** [comment]
Actually Violentmonkey already uses an existing format based on browser.runtime.getPlatformInfo and browser.runtime.getBrowserInfo. We only renamed `name` to `browserName` and `version` to `browserVersion` in order to place everything in one object.

We can rename some properties inside or move them, but this is a sensible base that can be used by other userscript managers. Definitely not userAgentData.

**Comment by F9y4ng** [comment]
Well, I think you should understand what I mean. it doesn't matter whether the structure of userAgentData is used or not, the important thing is to be able to contribute to the uniform format of most managers. then how to contribute to the uniform format may require further communication between you and derjanb, or other manager authors. 

That's all I can do for now. 😃

**Comment by tophf** [comment]
I fully understand and support the idea, but not this specific proposal.
