### ISSUE TITLE
New option: Disable auto-update as soon as the script is edited

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1787]
**Motivation**

I was working on a script but forgot to disable auto-update or to set a future version number, like I usually do.

Then I published a new version of this script and lost my work in progress because of the auto-update.

I followed a way to [dump Violentmonkey leveldb files](https://github.com/violentmonkey/violentmonkey/discussions/1674) but VM does not seem to store older versions.

**Proposed Solution**

~~I would like the recycle bin to contain old versions of scripts that have been auto-updated.~~
~~The same period as deleted script, 7 days, would be enough.~~

Add **an option** to Disable auto-update as soon as the script is edited.

**Use Cases**

Would avoid loosing work in progress in case we forget to change auto-update settings.

**Comment by tophf** [comment]
I like it, but maybe we should add some indication it was due to auto-update.
@gera2ld?

**Comment by gera2ld** [comment]
> just automatically uncheck auto-update as soon as the script is edited

I agree with this.

I think adding old versions to the recycle bin is not a good idea because it would increase the logic and UI complexity dramatically. Maybe it's easier to just keep a few old versions of each script but I don't like it personally.

**Comment by jesus2099** [comment]
I changed the ticket in this direction. 😉

**Comment by tophf** [comment]
I've implemented a different solution in d366d020: updatable scripts aren't editable as long as "Allow update" is checked. Attempting to edit it will show a warning `To enable editing, disallow updates in the Settings tab and click "Save"`.

**Comment by jesus2099** [comment]
Wow, this sounds great!
