### ISSUE TITLE
Settings always reset with every new update

### ISSUE THREAD

**Issue by AL3x3y0** [violentmonkey/violentmonkey#179]
### How to reproduce it?
1. Change some settings in Violentmonkey
2. Wait new update
3. Update the extension
4. Settings was reseted to default

### Environment
- Browser: Google Chrome
- Browser version: 60.0.3112.101 64-bit
- Violentmonkey version: 2.8.1
- OS: Windows 10 64-bit Enterprise LTSB

**Comment by gera2ld** [comment]
What do you mean by "update the extension"?

**Comment by AL3x3y0** [comment]
@gera2ld just get the new version of extension by clicking "Update extensions" in Google Chrome settings.

**Comment by gera2ld** [comment]
Nothing happens if it is already the latest version. The settings are still there.
Oh, do you mean that settings are lost when upgrade to the latest version? So it only happens once?

**Comment by AL3x3y0** [comment]
> Oh, do you mean that settings are lost when upgrade to the latest version?

Yes.

**Comment by gera2ld** [comment]
It happens only when the add-on is upgraded from an older version to v2.8.x?

**Comment by AL3x3y0** [comment]
I noticed that a long time ago, before 2.8.x.

**Comment by gera2ld** [comment]
The bug in v2.8.x is fixed. I will reopen this if reproduced in other versions.

**Comment by AL3x3y0** [comment]
> The bug in v2.8.x is fixed.

I doubt. Today I update monkey to 2.8.1 from 2.8.0 and settings is reset anyway.

**Comment by gera2ld** [comment]
I don't think it is related to updates because most of the times the updates have nothing to do with data.
I have tested upgrading from older versions and it works well. Hope there is a reproduction.
Anyway there is a bug in v2.8.x.

**Comment by AL3x3y0** [comment]
It's reseted again in 2.8.2. 

![image](https://user-images.githubusercontent.com/29476322/29374047-270efe8a-82c1-11e7-8d54-b06bd46f0d9d.png)

**Comment by gera2ld** [comment]
Still cannot reproduce. Can we discuss about it more on [gitter](https://gitter.im/violentmonkey/violentmonkey)?

**Comment by AL3x3y0** [comment]
I'm answer to you on gitter.

**Comment by AL3x3y0** [comment]
Seems like fixed, from 2.8.3 to 2.8.6 settings is fine.
