### ISSUE TITLE
[Question] Need help switching from TamperMonkey to ViolentMonkey

### ISSUE THREAD

**Issue by c0wg0d** [violentmonkey/violentmonkey#1791]
Hello,

I just learned about the existence of ViolentMonkey.  I am trying to switch from Chrome to Firefox and from TamperMonkey to ViolentMonkey.

There are two scripts I use often that I can't get working after the switch to ViolentMonkey.  Both scripts have `require` in them, and when I try to update the scripts, I get the error "Error fetching resource!"  I am not sure if this is a problem with my ViolentMonkey config, with my Firefox setup, or with the scripts themselves.  Can someone please help?  The two scripts are from here:

https://github.com/murdos/musicbrainz-userscripts

Specifically:

https://github.com/murdos/musicbrainz-userscripts/blob/master/bandcamp_importer.user.js

https://github.com/murdos/musicbrainz-userscripts/blob/master/discogs_importer.user.js

**Comment by tophf** [comment]
Both scripts are installed successfully here, so it must be something external like a network connectivity problem, or a broken browser cache or another extension somehow redirected/blocked the URL.

Make sure you're using the latest Violentmonkey, try restarting the browser, clear the cache, disable other extensions.

![image](https://user-images.githubusercontent.com/1310400/227789985-4e4be645-cfd3-4071-ba12-b909591011d3.png)

**Comment by c0wg0d** [comment]
I forgot there was an install process.  Instead of clicking the + and then Import from URL, I went to New and just copy/pasted the script from TamperMonkey.  Thanks.
