### ISSUE TITLE
[Feature] A Filter Script Values

### ISSUE THREAD

**Issue by JingJang** [violentmonkey/violentmonkey#1792]
**Motivation**

The script stored values can be quite large. It's paniful to parse through pages of values. 

**Proposed Solution**

A way to filter saved data by name(id) and value. So just to search boxes. 

**Use Cases**

**Comment by tophf** [comment]
You can simply look at the entire storage for the script, which is the default mode, and then search inside by pressing Ctrl-F key.

**Comment by JingJang** [comment]
Currently that's what I do, but not very easy or friendly when you have pages of values to go through.

**Comment by tophf** [comment]
There's no need to go through pages. All values are shown at once and you can easily find/filter them using the method I described.

**Comment by JingJang** [comment]
I mean pages of stored information and searching through it in one go. Lots of hts if the names are numbers and the values contain numbers. It is what it is. Thank you.

**Comment by tophf** [comment]
You can copypaste to some external json viewer that supports filtering by keys.
You can use regexp button `.*` in Ctrl-F with an expression to find just keys `^\s*"[^"]*foo` or just values `": "[^"]*foo`.
