### ISSUE TITLE
Cannot build/run

### ISSUE THREAD

**Issue by arantius** [violentmonkey/violentmonkey#180]
Checked out head ( 6881ca70bea74737d828afbf5b801fd028f2b638 ) today.  Tried to run/build, get e.g.:

```
$ npm run dev

> violentmonkey@2.8.1 dev .../violentmonkey
> gulp watch

.../violentmonkey/scripts/i18n.js:8
const readFile = util.promisify(fs.readFile);
                      ^

TypeError: util.promisify is not a function
    at Object.<anonymous> (.../violentmonkey/scripts/i18n.js:8:23)
```

Bisecting shows that 30e7d3bb7d9de2da3903c045b132dd7ba580f1ff introduced this failure.  (And indeed, it introduces exactly this line.)  If I check out the previous commit, run and build work as expected.

**Comment by gera2ld** [comment]
Node.js v8+ is required since `util.promisify` is added in Node.js v8.

**Comment by gera2ld** [comment]
If you want a quick start with earlier versions, you can replace `util.promisify` with `require('es6-promisify')`.
