### ISSUE TITLE
event doesn't bubble up

### ISSUE THREAD

**Issue by adipiciu** [violentmonkey/violentmonkey#1801]
I have a script which dispatches an event (for example a change event). The event is triggered but does not bubble up.

The script works ok on Firefox + Greasemonkey, or if you load the script in developer mode in Chrome. 

What Violentmonkey does different from Greasemonkey, or Chrome developer mode?

Thanks

#### Environment:
- OS: Windows 10
- Browser: Firefox 112/Chrome 112
- Violentmonkey version: v2.14.0

**Comment by tophf** [comment]
Violentmonkey doesn't do anything specific about event dispatch. Can you show the script and tell us the site where we can replicate the problem?

**Comment by adipiciu** [comment]
The script is here: https://github.com/adipiciu/Travian-scripts , but it's a little complex, because you need an account and there is only a specific function. You can contact me on telegram to explain better https://t.me/adipiciu

**Comment by tophf** [comment]
I don't use telegram so maybe someone else will debug it or provide a simplified example.

**Comment by adipiciu** [comment]
I found a workaround which works here:
https://github.com/facebook/react/issues/11488

But still don't know why in greasemonkey it works without the hack/workaround.

**Comment by 7nik** [comment]
@tophf simple test case and some thoughts: https://github.com/Tampermonkey/tampermonkey/issues/1758#issuecomment-1510428644
