### ISSUE TITLE
[BUG] GM_download loads response into memory

### ISSUE THREAD

**Issue by cunlem** [violentmonkey/violentmonkey#1803]
### Sequence of actions: 
1. `GM_download('https://example.com/superbig10gig.dat', 'mydata.dat')`
2. Download starts
3. ...
4. After file is downloaded (to memory) the dialog appears for choosing folder to save to (if the browser is configured to do so)

### Problem:
File is downloaded to memory instead of being saved to disk directly. It's inefficient and potentially causes a risk of running OOM. It's also not possible to monitor download progress in builtin browser's panel.

### Expected result:
File is downloaded to disk directly. If the browser is configured to ask each time for destination folder the dialog appears immediately after call.

#### Environment:
- OS: Ubuntu 22.04
- Browser: Firefox 112.0.1
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
The only way to fix it is to use browser.downloads API, which is #1349.
