### ISSUE TITLE
[Feature] Disable caching of require

### ISSUE THREAD

**Issue by Kein** [violentmonkey/violentmonkey#1807]
I use this [workflow]()https://stackoverflow.com/questions/41212558/develop-tampermonkey-scripts-in-a-real-ide-with-automatic-deployment-to-openuser to quickly compile TS into JS and iterate on changes, however, `@require` seems to be caching the local js file for the first time and never re-reads again, which makes it impossible to use the said workflow.

**Comment by tophf** [comment]
We won't do it because file:// URLs cannot be directly accessed in modern Firefox and we don't add significant features if it's browser-specific. You can use a different method: https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/
user.js

**Comment by Kein** [comment]
Hmm, I see.

> file:// URLs cannot be directly accessed from the background script in modern Firefox
That 7 years old bug, though, haha. Typical, for a well-deserved 1.2% market share I suppose.
