### ISSUE TITLE
可以不自动更新吗

### ISSUE THREAD

**Issue by bingyii** [violentmonkey/violentmonkey#181]
暴力猴这几天不能用。
下载旧版本还自动更新头疼。

**Comment by gera2ld** [comment]
不能。有问题直接说问题

**Comment by bingyii** [comment]
脚本已禁用，控制台打不开。

**Comment by gera2ld** [comment]
请提供一下background页面下的错误信息（Chrome更多工具 > 扩展管理 > 找到暴力猴 > 检查视图background/index.html > 看下有没有红色的错误信息）。
最好提供一下环境、浏览器版本、重现步骤（就是你创建issue时删掉的那些东西）。。

**Comment by gera2ld** [comment]
@bingyii 你是不是用的旧版Chrome，提供一下版本号？

**Comment by bingyii** [comment]
http://down.360safe.com/cse/360cse_8.7.0.306.exe
360极速浏览器（内核50.0.2661.102），具体的自己测试吧..

**Comment by gera2ld** [comment]
好了，更新到v2.8.3，兼容Chrome v45+
