### ISSUE TITLE
[Feature] Configurable Match/Include

### ISSUE THREAD

**Issue by AntoineTurmel** [violentmonkey/violentmonkey#1816]
**Motivation**
Instead of
// @include http://*/*
// @include https://*/*
I want an "include/match" configurable dynamically to avoid loading the userscript in each web page. (if you have @require tag you don't want to load on each website)

**Proposed Solution**
- With the GM API, allow include/match.
GM_include("https://mywebsite.com/*");

**Use Cases**
The user of userscript wants the userscript to work on X site without modifying manually the userscript.

**Comment by tophf** [comment]
Userscript extensions provide built-in customization of a script's matches/includes/excludes, which is a known and established method that existed for years, so I don't think GM_include will be useful, so we will implement it only if it's supported by Tampermonkey or several other extensions.

**Comment by AntoineTurmel** [comment]
So the only solution is to use:
// @include http:///
// @include https:///

and if (window.location.host.includes("https://mywebsite.com"))  ?

**Comment by tophf** [comment]
The solution is to customize the sites in the extension's UI.

**Comment by tophf** [comment]
In Violentmonkey it's inside the editor, in the second tab called `Settings`.
