### ISSUE TITLE
[Feature] Install an userscript from an URL (using protocol) or by detecting userscript metadata

### ISSUE THREAD

**Issue by AntoineTurmel** [violentmonkey/violentmonkey#1817]
**Motivation**
I want to install an userscript from web browser without having it to end by ".user.js"

**Proposed Solution**
- Protocol with an url parameter like vm_install://http://mywebsite.com/pathToMyUserScript
OR/AND
- Detecting when the tab opened is a text file containing a valid userscript metadata

**Use Cases**
If you want to install an userscript generated by client js (blob file doesn't allow filename in url)

**Comment by tophf** [comment]
You can add `?foo=.user.js` to the URL. Will this work for you?

**Comment by AntoineTurmel** [comment]
?foo=.user.js is working if the file is already present on server or generated by server-side
I doesn't work when generating a script using javascript from browser (with blob file generation).

I guess delivering my .user.js from a server-side php script is a workaround.

**Comment by tophf** [comment]
> I doesn't work when generating a script using javascript from browser (with blob file generation).

Maybe we can fix something to support this. How do you do it?

**Comment by AntoineTurmel** [comment]
Example:
https://jsfiddle.net/4x0nzbwo/

I want to be able to install this userscript (generated from browser client js) from browser (without server counterpart).

**Comment by tophf** [comment]
I see. It has `blob:` protocol which we can't observe anyway.

**Comment by AntoineTurmel** [comment]
So I guess it's impossible to trigger a "file.user.js" installation from a js text generated in the browser ? (without server side)

**Comment by tophf** [comment]
You can add `download` attribute that's equal to `filename`. The user will then drag'n'drop the file into the browser. It's pretty inconvenient though as it requires confirming the safety of the download and enabling file access checkbox in the properties of the extension in Chrome.
