### ISSUE TITLE
[BUG] Strange Settings 'Vacuum Database' Tooltip Behavior

### ISSUE THREAD

**Issue by Raymond-Adams** [violentmonkey/violentmonkey#1819]
### Sequence of actions: 
![strange_tooltip_behavior](https://user-images.githubusercontent.com/102918860/236541067-ffeeef6b-61a7-4bca-a093-d9b9659fc043.gif)
1. Scroll Down.
2. Hover over the 'Vacuum Database' button.

### Problem: 
The tooltip does not remain below the button.

### Expected result:  
The tooltip remains under the button, as it does prior to scrolling.

#### Devtools console contents:
N/A

#### Environment:
- OS: MacOS Big Sur 11.7.6 
- Browser: Firefox 112.0.2
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
@gerald, I thought you've fixed it in vm-tooltip?

**Comment by gera2ld** [comment]
Yes, it's fixed in `vueleton@2.0.2`
