### ISSUE TITLE
[Feature] While in Help, press F1 to go back to code

### ISSUE THREAD

**Issue by TFWol** [violentmonkey/violentmonkey#1822]
**Motivation**
To be able to keep hands on keyboard instead of needing to use mouse to click Code tab.

**Proposed Solution**
While in Help, press F1 to go back to code

**Use Cases**
If I needed a quick reminder in help, I would press F1 to see help and then press F1 to go right back to code view.

**Comment by tophf** [comment]
No, F1 is not an Esc.

**Comment by tophf** [comment]
However we should probably suppress F1 to avoid the default browser help page when we show our Help, @gera2ld?

**Comment by TFWol** [comment]
> No, F1 is not an Esc.

Once you mentioned Esc, I pressed Esc... and it did exactly that this time.
It definitely wasn't bringing me back before. I started thinking 'Cancel' under Esc in the help page meant something else.

i guess this Issue is null and void 😃
