### ISSUE TITLE
GM_setValue slow with many data/keys

### ISSUE THREAD

**Issue by Joe136** [violentmonkey/violentmonkey#183]
I stored 9000+ entries with GM_setValue; this results in 700KB in the database as one long string. Storing or changing an entry takes around 100ms, which is slow when changing multiple entries at once.

A look into the source code shows that GM_setValue is implemented in that fashion: parse, change, stringify. this takes long on big content.

Using localStorage is unreliable as the Browser (or the OS) can delete the data at will. Secondly storing data permanent is not possible in private mode.

The solution in GreaseMonkey is to store each entry independently in the database table. I would recommend to take advantage of sqlite by using three keys in the 'values'-table: script-ID | key | value.

GM_getValue is fast.

### Environment
- Browser: Maxthon
- Browser version: 5.x
- Violentmonkey version: 2.7.3

**Comment by gera2ld** [comment]
Does this happen with Chrome or just Maxthon?

**Comment by gera2ld** [comment]
This is not the perfect solution but can improve the performance significantly.
For browser to transport data between background, content page and web page, the data has to be serialized (e.g. `JSON.stringify`), so if data is too large, the browser gets blocked for a while. I don't see a perfect solution to this if we have millions of bytes of data to transport.
