### ISSUE TITLE
[BUG] Editor Font Size, Sorting Scripts, Copy-Pasting, Keybindings.

### ISSUE THREAD

**Issue by SedapnyaTidur** [violentmonkey/violentmonkey#1830]
### Sequence of actions: 
1.
2.
3.

### Problem: 
- **Editor font size**
The editor font is way too huge for me. It makes it hard to view/edit codes when you have a small view frame. Most of the time, I have to open dev-tool and modify the `<meta name="viewport" content="width=device-width, initial-scale=0.7">`.
- **Sorting**
Unable to sort the most bottom script to top when you have more than lets say 20/30 scripts. It gets stuck somewhere in the middle and won't scroll to the top. One way to do it is search the scripts by name and sort them there.
- **Copy-Pasting**
Copy-pasting in the editor sucks. Just look at this code block:
```javascript
function copyPaste() {
  console.log('firstLine');
  console.log('Eeckk!!!');
  console.log('lastLine');
}
function copyPaste() {
32
  console.log('firstLine');
33
  console.log('Eeckk!!!');
34
  console.log('lastLine');
35
}
```

Editing the setting "lineWiseCopyCut" to true or false does not do anything different either.
- **Keybindings**
None of the keybindings works either. I'd like to have "nano" keybindings though.
- **Syntax Error Highlighting**
It would make the editing easier.
![img](https://github.com/violentmonkey/violentmonkey/assets/76834441/eef5fa78-e8d0-412b-9291-f8a616c2e4b6)
[### Expected result:  

#### Environment:
- OS: Android 13
- Browser: [Kiwi-Next](https://github.com/kiwibrowser/src.next/releases) 
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
> The editor font is way too huge for me

You can customize it in the advanced settings via `Custom CSS` like `.CodeMirror { font-size: 8px }`

> Sorting

A screenshot or gif would be helpful as I don't have a way to test Kiwi.

> Copy-pasting in the editor sucks

I guess it's a bug in the browser or in CodeMirror. Try adding `"inputStyle": "textarea",` to the editor config in the advanced settings.

> Keybindings

Sounds like a bug in the browser or it depends on the keyboard app you're using.

> Syntax Error Highlighting

As noted in #836 we won't add it. In the future we may add a method of using a powerful online editor like VSCode, see [this](https://github.com/violentmonkey/violentmonkey/discussions/1753).

**Comment by SedapnyaTidur** [comment]
Nah, using "usingStyle": "textarea", I can't even copy the selected text. Tested about 10x, open and closed the browser but it didn't help. Here the screenshot:
![az_recorder_20230602_163559](https://github.com/violentmonkey/violentmonkey/assets/76834441/08360bc4-5e5e-485d-a42d-43a8feea156f)
![az_recorder_20230602_163636](https://github.com/violentmonkey/violentmonkey/assets/76834441/e39770ca-be8a-4fa9-9953-4f5ce9de9a05)

**Comment by tophf** [comment]
To use `textarea` you probably need to find a different keyboard app that properly implements `Ctrl-C` hotkey.

Anyway, as far as I know there's nothing we can do about it other than adding an editing toolbar with the formatting buttons and actions, but I don't suppose we should do it as our purpose is a small extension that runs userscripts and a simple editor.

@gerald, could you test it in Kiwi or mobile Firefox and see if there's anything we can fix?

**Comment by SedapnyaTidur** [comment]
I can use my keyboard with Termux just fine. nano, vim, etc.. but not in ViolentMonkey. Well, I think it is in browser side. Only `Ctrl-J` and `Ctrl-M` seem to work. Well, whatever. I'm closing this issue now.
