### ISSUE TITLE
[Feature] Option to disable Icons in extension's Drop-Down menu

### ISSUE THREAD

**Issue by cvladan** [violentmonkey/violentmonkey#1831]
I have a suggestion for the authors.

Now that I have activated a bunch of ChatGPT scripts, they all use different icons for scripts. This poses a problem for me because those who don't use them appear as "disabled".

In fact, all that is needed is an option to disable the display of icons in the extension's drop-down menu.

This didn't bother me before because I didn't have many userscripts on the same website. But now I have accumulated quite a few for ChatGPT, and I also have a lot of disabled userscripts that I only activate occasionally.

**Comment by tophf** [comment]
You can use `Custom CSS` in the advanced settings with the following code:

```css
.script-icon { display: none }
```

**Comment by cvladan** [comment]
> ```css
> .script-icon { display: none }
> ```

Yes! Thank you!

**Comment by cvladan** [comment]
Should I close this ticket? Or... I don't know.
It makes sense for beginners, but on the other hand, who cares?
... kidding 😉

**Comment by cvladan** [comment]
Closing. 
There aren't many userscript users who don't understand CSS.

Maybe to write this somewhere in instructions.
