### ISSUE TITLE
GM_xmlHttpRequest default mode should be anonymous?

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey#1835]
Allegedly it's anonymous in Tampermonkey, which enables scripts like https://greasyfork.org/en/scripts/407957 to work without affecting the main cookies. We need to investigate whether many of the existing scripts use this assumption and act accordingly: either change our default or report a compatibility issue in Tampermonkey.

Repro: install the script linked above and open https://myanimelist.net/profile/zTimez - you will be logged out of your account because the script calls GMxhr and the browser uses the cookies in its response instead of the current cookies, i.e. the standard browser behavior.

**Comment by tophf** [comment]
Another solution may be indeed customizing `firstPartyDomain` as described in #1467 because the myanimelist cookies are overwritten in GMxhr for anime.jhiday.net and not for myanimelist URL. Switching the latter to `fetch` with `credentials: 'omit'` didn't help (I thought it did but turns out I made a mistake).

**Comment by cyber-sec0** [comment]
Thanks for opening this!

I thought a fetch with credentials: 'omit' would work since you recommended it, but seems like it didn't work for you, so I won't even waste time testing again.

Ping me if you find a solution I can add to the script code

**Comment by tophf** [comment]
Judging by devtools, Tampermonkey sends the request with browser cookies, then removes `set-cookie` from the response and puts them into GMxhr's `responseHeaders`. It actually makes more sense than our behavior, so we should do the same and remove our complicated `setCookieInStore`.

**Comment by cyber-sec0** [comment]
Your fix
https://github.com/violentmonkey/violentmonkey/suites/14263589826/artifacts/801443076

Says that "can't be installed because it is corrupted"

**Comment by cyber-sec0** [comment]
@tophf
Your fix
https://github.com/violentmonkey/violentmonkey/suites/14263589826/artifacts/801443076

Says that it "can't be installed because it is corrupted"

**Comment by tophf** [comment]
It's not corrupted. I've just installed it in Chrome or Firefox successfully the same way as usual.

**Comment by cyber-sec0** [comment]
@tophf

Actually, the message I get on firefox is
"can't be installed because it has not been verified"

**Comment by tophf** [comment]
That's because you're not installing it correctly. To install a zipped extension in Firefox you need to use Temporary installation mode.

BTW the fix for this issue is already included with the [latest beta 3](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.14.3), so the new build shouldn't be any different in this regard.

**Comment by cyber-sec0** [comment]
@tophf

Ok I see that it worked with https://github.com/violentmonkey/violentmonkey/suites/14263589826/artifacts/801443076 but when is it actually going to be released on the firefox extensions website?
I installed and tested it a few hours ago, and the bug was still there...

**Comment by tophf** [comment]
> when 

In a few days I guess as I want to wait for other possible reports in the last beta.

> I installed and tested it a few hours ago, and the bug was still there...

Was it really beta 3?

**Comment by cyber-sec0** [comment]
@tophf

ok thank you, would you be able to write here to let me know when it is actually released?

Nope, that was from here https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/

**Comment by tophf** [comment]
You can subscribe to releases using the `Watch` button menu and get a notification automatically.
