### ISSUE TITLE
[Feature] Add support Sleazyfork

### ISSUE THREAD

**Issue by KonoromiHimaries** [violentmonkey/violentmonkey#1838]
**Motivation**

In current time, i must install this script 
```
https://greasyfork.org/en/scripts/23840-greasyfork-search-with-sleazyfork-results-include
```

**Proposed Solution**

Add Sleazyfork link to search button in popup panel
Add Sleazyfork link to `add new script` button in script management panel

**Use Cases**

To unblock more scripts

**Comment by tophf** [comment]
We can't add links to NSFW sites in a published extension.
