### ISSUE TITLE
[Question] Is `'X-Requested-With': 'XMLHttpRequest'` required in VM's GM.xmlHttpRequest?

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1840]
Hi,

Recently we are facing difficulties that the response of `GM.xmlHttpRequest` is occasionally incorrect. (response become HTTP body text instead of JSON format) (https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/issues/22)

We are still looking for the root clause. However, I noticed that `'X-Requested-With': 'XMLHttpRequest'` is added to the header in our script, while there is no document for Userscript that whether it should be specified or not.

Whether the following is correct in using `GM.xmlHttpRequest`?

```
GM.xmlHttpRequest({
    "url": "https://genius.com/api/search/song?page=1&q=MAN%20WITH%20A%20MISSION%2C%20milet%20Kizuna%20No%20Kiseki",
    "method": "GET",
    "headers": {
        "Referer": "https://genius.com/api/search/song?page=1&q=MAN%20WITH%20A%20MISSION%2C%20milet%20Kizuna%20No%20Kiseki",
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "Host": "genius.com",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
        "X-Requested-With": "XMLHttpRequest"
    }
})
```

1. Should we specify `"X-Requested-With": "XMLHttpRequest"` in the request headers? Any negative impact?
2. Should we specify `Referer`, `Host`, `User-Agent` in the request headers? Any negative impact?
3. As the api link is not associated to any logging status, will adding `anonymous: true` can help?
4. Should we add `overrideMimeType` and `responseType` in the request?

**Comment by tophf** [comment]
The code looks correct. As for the numbered questions, it depends on the server and (AFAIK) doesn't change how gmxhr works in Violentmonkey. 

Judging by the contents of the wrong response, it's a CloudFlare error page displayed when the hosted server is unavailable. There are two things to try I can suggest: 1) add `Accept: application/json` header to forbid an html response, 2) check `response.status` as it should be above 300, 3) ignore the response if it starts with `<`.
