### ISSUE TITLE
[Feature] Add support to upload scripts to virustotal.com

### ISSUE THREAD

**Issue by andreldmonteiro** [violentmonkey/violentmonkey#1841]
**Motivation**
This would provide extra security assurances and assure that scripts are run on a sandbox.

**Proposed Solution**
Add support to upload scripts to virustotal.com

**Use Cases**
Automatic or manual upload, based on preferences.

**Comment by tophf** [comment]
The free public API is limited to 500 requests per day and a rate of 4 requests per minute, which means we can't use it directly in our extension. We definitely won't use the commercial API.

The only convenient alternative is to hijack their web page by embedding it inside our background page in an iframe and then issue the requests on behalf of it, but this would be a violation of their terms of service.

We could allow the user to paste their own API key but that means most of the users won't do it and it'll be a deadweight feature, which we earnestly try to avoid. Such integration would make more sense in the galleries like greasyfork.org, openuserjs.org.

@gera2ld?

**Comment by gera2ld** [comment]
I think it's out of the scope of this extension.
