### ISSUE TITLE
[Feature] `GM.addEventListener` for `activate` and `deactivate`

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1843]
**Motivation**

<img width="321" alt="Screen Shot 2023-06-30 at 10 36 41" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/7acc2b54-f386-4caa-adc2-1379351d6c97">

* The userscript on/off shall be dynamic such that the users can turn on/off anytime in the userscript manager instead of making a separate on/off button with their own javascript coding + css styling on page.
* It shall be done with Event Mechanism. Developers can easily attach or detach the event listeners to monitor the triggering or do something when events fire.

**Proposed Solution**
There shall be an event mechanism. 
* GM.addEventListener(type: string, callback: function, options: Object?)
The 3rd parameter options shall be reserved for future use.

Then GM can have two events `activate` and `deactivate`.
_(`valuechange` might be also implemented in respect of  `addValueChangeListener` and `removeValueChangeListener`)_

* Permission requires `@grant GM.events.activate`,  `@grant GM.events.deactivate`
* _(`@grant GM.events.valuechange`)_
* `@grant GM.events.*` can grant all events

For simplicity, all these events are not cancellable.

The event in callback just looks like Event but not Event. There is no target, bubble/capture, defaultPrevented, etc. It does not require to extend from Event.

**Use Cases**
Example:
```css
.my-userscript-style span.f-word {
  color: transparent !important;
  background: #777;
}
```
```js

// Event `deactivate` will be dispatched just before the script is off
GM.addEventListener('deactivate', () => {
  document.body.classList.remove('userjs-for-kids');
});
// Event `activate` will be dispatched just after the script is on
GM.addEventListener('activate', () => {
  if (!noStyleTextAdded()) styleElementCreate(); // add css rules to the document.head
  document.body.classList.addClass('userjs-for-kids');

  const search = document.evaluate("//*[name()='span'][contains(text(),'fuck')]",
    document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);

  for (let i = 0; i < search.snapshotLength; i++) {
    const node = search.snapshotItem(i);
    console.log(node, node.classList)
    node.classList.add('f-word')
  }

});
```

### Implementation
```js

// native event mechanism; internal use
const GMEventTarget = document.createAttribute("GM");
// function mapping; internal use
const store = new WeakMap();

const handleGMEvents = (evt) => {

  const { type, timeStamp } = evt;
  if (type === 'valuechange') {
    const { key, oldValue, newValue, remote } = evt.detail;
    return { type, timeStamp, key, oldValue, newValue, remote };
  } else {
    return { type, timeStamp };
  }

}

function fnHelper(evt) {
  evt = handleGMEvents(evt);
  this.callback.call(null, evt);
};

GM.addEventListener = (type, callback, opts) => {
  console.assert(typeof type === 'string');
  console.assert(typeof callback === 'function');
  let handler = store.get(callback);
  if (!handler) {
    handler = fnHelper.bind({ callback });
    store.set(callback, handler);
  }
  GMEventTarget.addEventListener(type, callback, false);
}
GM.removeEventListener = (type, callback, opts) => {
  console.assert(typeof type === 'string');
  console.assert(typeof callback === 'function');
  const handler = store.get(callback);
  if (handler) {
    GMEventTarget.removeEventListener(type, handler, false);
  }
}

// GM_dispatchEvent for internal use
const GM_dispatchEvent = (type, data) => {
  GMEventTarget.dispatchEvent(new CustomEvent(type, { detail: data }));
};
```

**Comment by tophf** [comment]
The On/off toggle has a different meaning e.g. to deactivate [temporarily] unused scripts, so I don't agree that we can overload its behavior. We would have to add a new UI element instead and since the functionality is the same as GM_registerMenuCommand we would add a menu item named "Toggle" or "Activate" (and "Deactivate"). This can be fully replicated by a userscript library added via `@require`. @gera2ld?

**Comment by gera2ld** [comment]
Yeah I agree, it makes no difference from a menu item, but completely different from a toggle to prevent the script from loading.
The idea is interesting, but it may not be easy to spread because it requires changes to all userscripts.
