### ISSUE TITLE
[Feature] Add to the dasboard favicons for the sites the script works on, icons for info regarding permissions, requirements, and access and an icon linking to the site the script was installed from

### ISSUE THREAD

**Issue by TSnatch72** [violentmonkey/violentmonkey#1845]
**Motivation**

A little but meaningful aspect of tampermonkey i thank a lot is how it has columns in the dashboard displaying these things at a glance with corresponding links (see picture below). I think this would be a nice QoL addition to Violentmonkey.

![23 07 03-brave-13 47-18](https://github.com/violentmonkey/violentmonkey/assets/88058182/b58daded-2d53-428f-bd00-27d3c53c2311)

**Proposed Solution**

Violentmonkey doesn't use a column-based ui for its dashboard. However, rows (or cards) are currently mostly empty in the dashboard, with only info and functions at each border. Maybe could keep up with the vertical-bar-separated layout each row or card currently has and take advantage of the empty space this way.

Violent monkey already has buttons for accessing the script's homepage and support page as parsed from the script. Maybe a button next to them containing a link to the site the script was installed from, like the greasyfork post or the github repo.

I think the favicons part is the easiest to implement since they could be scraped from the sites manifested in the script. Tampermonkey only presents the first 7 followed by 3 dots.

the "feature" part seems to be what would require most work.
This column shows some icons (with links to further details if aplicable) reporting wether or not the script has full internet access, access to https sites, if it stores data in the userscript manager, if it uses external resources like pictures or css files, if it requires and pulls scripts from external sites or if it doesn't require any special power.

This is the page showed by tampermonkey after clicking the requirement or resource icons (the purple ones):

![23 07 03-brave-14 09-22](https://github.com/violentmonkey/violentmonkey/assets/88058182/4486d9bd-10f8-43ef-aded-e40036a6b2c7)

**Comment by tophf** [comment]
Our dashboard is already quite complicated internally, and it takes half a second to paint my ~50 scripts on a moderately fast desktop computer. This is the price we have to pay for using a convenient UI framework. The only way to make it fast is to hardcode the UI (this is what Stylus extension does, which is why it shows its dashboard so fast even with site favicons). Moreover, I've never paid attention to any of these icons when I've been using Tampermonkey for several years.

I don't think we should add them as our goal is to keep Violentmonkey UI simple and fast.
@gera2ld?

**Comment by gera2ld** [comment]
Yeah let's keep the UI simple and fast. Maybe we can migrate the script list to plain HTML + event delegation for better performance.

We may provide those features but it's unlikely to put so many icons in the dashboard. TBH those icons were the first reason why I didn't like Tampermonkey and created this extension.

**Comment by TSnatch72** [comment]
Interesting, maybe there's a way to provide some of that information, primarily the access and permission one, through other means

**Comment by tophf** [comment]
We couldn't see any use for this information. What's the use case? How it can be helpful to our users? Why would they look at it and what would they use it for?

**Comment by TSnatch72** [comment]
For privacy and security. Quickly assessing if the script is pulling external resources and scripts and which, what does it have access to or if it stores data

**Comment by tophf** [comment]
Privacy and security are vague words without much inherent meaning. Quickly assessing should be performed before you install the script.

**Comment by erosman** [comment]
If I may, I would like to mention few additional considerations....

### Practicality and Usefulness

- Userscript may have 100s of specific matches in `@match`
- Userscript may have endless number of non-specific matches e.g. `*://*/*`
- Storing all the favicons is impractical

### Privacy and Security

- External favicons (e.g from Google API) can be used by the image provider to track users, thus eroding users' "privacy and security"

**Comment by tophf** [comment]
One thing we could do, theoretically, is showing the first meaningful match pattern's favicon as the main icon of the script in case the script doesn't have its own `@icon`, however it's blocked on https://crbug.com/1431958 for the browser's built-in favicon service.

**Comment by TSnatch72** [comment]
> Privacy and security are vague words without much inherent meaning. Quickly assessing should be performed before you install the script.

That's true, but that's assuming you understand the scripting language. Giving this information at a glance would make the scripts more transparent for everyone independently of their coding knowledge

**Comment by tophf** [comment]
I don't see any meaningful info in these icons that can help users. If you want to convince us you need to describe a specific "user journey". Depending on how popular/useful that will be, we may reconsider.

**Comment by erosman** [comment]
> That's true, but that's assuming you understand the scripting language. Giving this information at a glance would make the scripts more transparent for everyone independently of their coding knowledge

False perception of security, IMHO.

Consider the following (I have actually seen such a userscript)

```
// @match     https://www.google.com/*
// @include   *
```

The display cant show a catch-all result and shows ![image](https://github.com/violentmonkey/violentmonkey/assets/6458876/2e328f52-00f6-4d50-b85b-f3e7196cc72e) which would then create a false perception of security.
