### ISSUE TITLE
2.8.4更新后造成脚本跟网站各种冲突

### ISSUE THREAD

**Issue by rcyggdra** [violentmonkey/violentmonkey#185]
- Browser:cent browser 64bit
- Browser version:Chromium 59
- Violentmonkey version:2.8.4
- OS:windows 10 64bit

同脚本在Tampermonkey运行无问题。
![snipaste20170822_005650](https://user-images.githubusercontent.com/8652464/29530208-3aca94bc-86d5-11e7-8d60-0f5ee5ac88f8.jpg)
![snipaste20170822_005845](https://user-images.githubusercontent.com/8652464/29530211-3d5d05de-86d5-11e7-8404-1248258f2c5f.jpg)
在别的网站不同的脚本有不同的问题。

**Comment by gera2ld** [comment]
无法重现，请提供完整的复现步骤。
