### ISSUE TITLE
Injection wont work at all

### ISSUE THREAD

**Issue by Civ01** [violentmonkey/violentmonkey#1850]
```
// ==UserScript==
// @name        TK
// @namespace   Violentmonkey Scripts
// @match       https://www.turkishairlines.com/*
// @grant       none
// @version     1.0
// @author      -
// @run-at      document-end
// @description 7/16/2023, 10:49:03 AM
// ==/UserScript==

console.log('Injected!');
(function () { 'use strict'; console.log('Injected1!'); })();
```

Absolutely nothing happens, no errors, nothing. I see script is activated in the pop-up.

**Comment by tophf** [comment]
It works. The site simple clears the console.

**Comment by Civ01** [comment]
> It works. The site simply clears the console.

It isnt:
```
(function () {
    'use strict';
    window.test = 'Test!';
})();
```

Later `window.test` is undefined.

**Comment by tophf** [comment]
This code also works for me.

**Comment by Civ01** [comment]
> This code also works for me.

I dont understand. Literally nothing works for me, `Crhome  114.0.5735.199`, VM is `2.14.0`.
Iis there a way for me to debug it?

**Comment by tophf** [comment]
Set a breakpoint in devtools inside your script and reload the page. Devtools should pause when your code runs.

**Comment by Civ01** [comment]
> Set a breakpoint in devtools inside your script and reload the page. Devtools should pause when your code runs.

This actually works? I never could get it to do so for me, I always assumed it is because VM instance of the script is being recreated on each reload so it can't possible break when code no longer exist.

**Comment by tophf** [comment]
Yes, it works and has been working for many many years, I wouldn't advise it otherwise.  I guess devtools is smart.

**Comment by tophf** [comment]
Ah, it works because we are adding a sourceURL comment to let devtools keep track of the script. We started to add it in 2019. I don't know when Tampermonkey or other userscript managers started to do it.
