### ISSUE TITLE
Enable Shadow DOM manipulation

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1852]
There are websites that rely on stuff called [Shadow DOM](https://developer.mozilla.org/docs/Web/API/Web_components/Using_shadow_DOM).

There are seen as `#shadow-root (open)` in the element inspector:

![image](https://github.com/violentmonkey/violentmonkey/assets/1401086/bd5d0442-11a5-4ce6-8421-4cb7a09b41da)
If it would have been `#shadow-root (closed)` then I guess nothing would be possible about them.

From this example, if you want to pick the `<main class="preset-right">` element with `document.querySelector("main.preset-right")` then it doesn't work.

You can get any elements inside the `shadow-root` by using the `shadowRoot` property of the shadow root `host`:

```js
document.querySelector("span.easepick-wrapper").shadowRoot.querySelector("main.preset-right")
```

So I can get any elements from the shadow root, and see everything about them.

But it is **impossible to change existing elements** (`setAttribute`, `style.setProperty`, `addEventListener`, `dataset.property` assign), and **impossible to add new elements** inside the shadow root (`insertBefore`, `appendChild`, `innerHTML`).

**Do you think something can be done by Violentmonkey, to enable that?**

---

PS. In this example here, I queried `main.preset-right` because it appears in the small screenshot, but in fact in my script I access some more regular `div#this.that` in the `shadowRoot` (but cannot write anything).

**Comment by tophf** [comment]
For `open` shadowRoot there's nothing Violentmonkey can or should do. It's up to you to write the correct code.

For `closed` shadowRoot there is chrome.dom.openOrClosedShadowRoot in Chrome 88+ and a similar thing in Firefox 60+, so we may add GM_getShadowRoot once our minimum supported browser is above these versions, which will definitely happen after we migrate to ManifestV3. However you can already access it by overriding attachShadow at `document-start`:

```js
// @run-at         document-start

const closedRoots = new WeakMap();
const attachShadow = Function.prototype.call.bind(Element.prototype.attachShadow);
Element.prototype.attachShadow = function (opts) {
  const root = attachShadow(this, opts);
  if (opts?.mode === 'closed') closedRoots.set(this, root); 
  return root;
};

// Then use it like `let root = someElement.shadowRoot || closedRoots.get(someElement)`
```

**Comment by jesus2099** [comment]
> For `open` shadowRoot there's nothing Violentmonkey can or should do. It's up to you to write the correct code.

What do you think about the fact that a userscript can read everything inside an open shadow root but cannot write anything?

Or maybe it can, you mean?
I didn't find any examples, yet.

**Comment by tophf** [comment]
You can write anything both inside an open root and closed root (requires overriding attachShadow as shown in my example), so I guess your code was incorrect.

**Comment by tophf** [comment]
My example is only about intercepting a closed shadowRoot. It doesn't show how to use ShadowDOM. Your code is correct, so if it doesn't work there's something else interfering, which I can't say without seeing the site myself.

**Comment by jesus2099** [comment]
OK you're right @tophf!
It is possible to manipulate shadow DOM, it's just that the website I am working on has some additional funny stuff going on!

I found a random page with `#shadow-root (open)`: https://apearce.github.io/react-shadow-root/

And both those two following lines of code, read and write, did work in console (F12) and in a userscript!

```js
alert('document.querySelector("basic-demo").shadowRoot.querySelector("span").innerText: ' + document.querySelector("basic-demo").shadowRoot.querySelector("span").innerText);
document.querySelector("basic-demo").shadowRoot.querySelector("span").appendChild(document.createTextNode(" toto"));
```
