### ISSUE TITLE
[BUG] webdav同步失败后丢失全部脚本

### ISSUE THREAD

**Issue by arix00** [violentmonkey/violentmonkey#1854]
Windows 10 + Chrome 114.0 
同步到webdav

开始肯定是成功的，webdav能看到备份
然后过段时间，webdav目录清空，只有一个violentmonkey文件，比如
`{"info":{},"timestamp":1689738546818}`
本地脚本全部丢失。

没法直接复现问题，但是搜索了下源码，如果理解没错，
获取远程失败则新内容为空，然后继续同步？？？相当于用空内容覆盖？？？
这种时候不是应该中断同步么。。。

https://github.com/violentmonkey/violentmonkey/blob/c5911c0a5fa7d8592e3cc0831b06b406f8bf7786/src/background/sync/base.js#L394-L400

**Comment by gera2ld** [comment]
你理解错了。

**Comment by gera2ld** [comment]
Anyway, the current logic cannot handle conflicts properly and will be rewritten.

Closing as a duplicate of #1306
