### ISSUE TITLE
[BUG] `Check all for updates` is buggy

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1855]
## Screenshot:

<img width="1257" alt="Screen Shot 2023-07-22 at 19 23 20" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/38c093be-dd4c-4a93-8b87-f559c83f5e77">

## Reproduction:
<<< NOT ALWAYS REPRODUCIBLE >>>
- Open Violentmonkey options page,
- click "Check all for updates" on the top left.
- some scripts will show the red text message "Failed fetching update information"
- Same result if click it again.

However, if I click the individual update button, it can update as normal.

<img width="1256" alt="Screen Shot 2023-07-22 at 19 26 01" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/25e47031-f29b-42d3-a84f-42ad50624441">

#### Environment:
- OS: Apple Macbook Pro M2
- Browser: Brave | 1.56.11 Chromium: 115.0.5790.102 (Official Build) (arm64)
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
Sounds like your network may be limiting network connections issued in quick succession, which happens when updating all scripts, which will be eventually fixed in #1809.

**Comment by cyfung1031** [comment]
I have checked the background page that there are some 503 ERROR

200
<img width="1119" alt="Screen Shot 2023-07-22 at 19 33 51" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/005283eb-5a4c-4e40-8a8e-1c9e3f7a1e6a">



503
<img width="1181" alt="Screen Shot 2023-07-22 at 19 33 27" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/6f462a45-76f4-408b-8dde-894ebc8cf826">


I guess it is due to all network requests were made at the same time, thus the server will abort some requests and return 503.



## Suggested Solution

DO NOT simultaneously send the network request.
store them in a queue; fetch one by one after the previous fetch request completed (response recevied).
