### ISSUE TITLE
[Feature] Please add Violentmonkey to new Firefox mobile 

### ISSUE THREAD

**Issue by ChowMein47** [violentmonkey/violentmonkey#1860]
**Motivation**
Please add this extension to Firefox android

**Proposed Solution**

**Use Cases**

**Comment by tophf** [comment]
It's up to Mozilla, not us, we can't do it. You can already add custom extensions in mobile Firefox via collections, see [this article](https://www.androidpolice.com/install-add-on-extension-mozilla-firefox-android/).
