### ISSUE TITLE
[BUG] GM_xmlhttpRequest onreadystatechange callback with readyState=4 and status=200 more than once

### ISSUE THREAD

**Issue by Ocrosoft** [violentmonkey/violentmonkey#1862]
### Sequence of actions: 
1.Try download a file with GM_xmlhttpRequest.
```
GM_xmlhttpRequest({
    method: 'GET',
    url: 'https://github.com/neon-nyan/Collapse/releases/download/CL-v1.70.12/CL-1.70.12_Installer.exe',
    onreadystatechange: function(res) {
        if (res.readyState === 4 && res.status === 200) {
            console.log(200);
        }
    }
});
```
2.The console print the follow log:
![image](https://github.com/violentmonkey/violentmonkey/assets/25629637/d54cafc0-98c1-447b-8557-b4f49b897214)

### Expected result:  
I'm not sure if this is the expected behavior, but I think it should be callback only once with readyState=4 and status=200.
Is it possible that it is related to this? https://github.com/violentmonkey/violentmonkey/issues/1665

#### Environment:
- OS: Windows
- Browser: Firefox 116
- Violentmonkey Version: 2.15

**Comment by tophf** [comment]
It works correctly for me, so I guess your script runs in many iframes.

**Comment by Ocrosoft** [comment]
This is the full script, it also can be reproduced in edge.
```
// ==UserScript==
// @name        New script - github.com
// @namespace   Violentmonkey Scripts
// @match       https://github.com/violentmonkey/violentmonkey/issues
// @grant       none
// @version     1.0
// @author      -
// @description 8/2/2023, 10:58:13 AM
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
    method: 'GET',
    url: 'https://www.google.com/',
    onreadystatechange: function(res) {
        if (res.readyState === 4 && res.status === 200) {
            console.log(200);
        }
        console.log(res.readyState + ',' + res.status);
    }
});
```
![image](https://github.com/violentmonkey/violentmonkey/assets/25629637/0f5e7cb1-5e89-44a7-854d-e37c6b4de192)

**Comment by tophf** [comment]
I can't reproduce it neither in Chrome nor in Firefox.

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/20495161-bb27-46e1-8471-815a8e14833a)

**Comment by Ocrosoft** [comment]
But the console's output is not stable,
![image](https://github.com/violentmonkey/violentmonkey/assets/25629637/9e753267-03c9-41ca-9b85-bc5ceef2cb85)
![image](https://github.com/violentmonkey/violentmonkey/assets/25629637/a011e630-183c-476d-b06f-f854676b49da)
I guess there maybe a timing synchronization problem...

**Comment by tophf** [comment]
I can see it now in Firefox but not in Chrome....
