### ISSUE TITLE
[Feature] Bypass CSP without injecting as content script

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1863]
It would be nice if ViolentMonkey, by default, will bypass CSP as TamperMonkey does.

Currently, it runs scripts on sites like Twitter as [a content scripts](https://violentmonkey.github.io/api/metadata-block/#inject-into). In this case I can't interact with `unsafeWindow` of the web page.

Also, scripts can work different in ViolentMonkey / TamperMonkey because of it. I always need to test scripts twice in in both userscript managers, and both browsers (it seems on Chromium it works as TamperMonkey, but not on FF). And, there are extra bugs in the content script's context, like this https://bugzilla.mozilla.org/show_bug.cgi?id=1757836.

**Comment by tophf** [comment]
It's the same as #1001.
