### ISSUE TITLE
更新脚本时机导致问题

### ISSUE THREAD

**Issue by xcffl** [violentmonkey/violentmonkey#187]
### What is the problem?
每天第一次开启火狐，或禁用后再启用暴力猴，看起来都会触发它更新脚本。然而这个更新过程由于某种网络原因往往需要若干分钟才能完成。这段时间暴力猴自身将处于失效状态（脚本无法触发），且卡死（关闭火狐时有一个进程延迟若干秒才会关闭）。

### What is the expected result?
将更新脚本与执行脚本改成可以并行的，而且不必在启动暴力猴的一瞬间就开始更新（这段时间火狐需要完成的工作很多）。

### Environment
- Browser: Firefox
- Browser version: 57.0a1(2017-08-21)
- Violentmonkey version: 2.6.4
- OS: Ubuntu 17.04

**Comment by gera2ld** [comment]
1. 本来就延迟了20s才更新。
1. 更新并不影响其他流程。暴力猴自身将处于失效状态是个什么状态？列表打不开还是脚本看上去正常但是不会运行？
1. 卡死又是什么情况？关闭时继续处理任务不叫卡死，浏览器关闭的时候自己也会有一些清理操作。。。

从你的描述来看，只有“失效状态”可能是个bug，请提供完整的重现。

**Comment by xcffl** [comment]
1. 那就不知道为什么一开就卡死了……
2. 脚本确实没运行，我记得“打开控制台”的按钮也是灰色的。直到过了好久突然弹出xxx脚本更新成功才能用。具体的我也有点记不清，明天触发了我再继续反馈。
3. 也确实……这个以前没怎么注意，不确定是不是暴力猴的问题。

**Comment by xcffl** [comment]
很幸运，重启计算机后第一次打开火狐就能遇到。

现象是，火狐一打开的时候会卡在显示about:home（出现这个很正常，异常的是卡了好几秒，浏览器放大缩小也不会重绘界面，而只打开了8个标签页）。标签页总算打开了，想打开github报错误，地址栏输入网址回车后，转圈圈很多秒，此时暴力猴面板（由于开启了扩展放在新进程中，截图时无法截下这个面板）：





打开暴力猴控制台，点“设置”，地址栏里的地址确实变了，但界面无改变：

过了十几秒，github的标签页开始显示画面了，设置也随之打开。

然而直到我写这帖的现在，暴力猴的控制台仍显示“加载中...”，脚本也无效。

**Comment by gera2ld** [comment]
你确定这和暴力猴有关系？禁用暴力猴就不卡了吗？

**Comment by xcffl** [comment]
是的。而且暴力猴自己也同时卡在那里……

卡完，暴力猴工作得很棒。

**Comment by gera2ld** [comment]
最新的[v2.8.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.8.7)还有这个问题吗？

**Comment by xcffl** [comment]
尚未发现此问题重现

**Comment by gera2ld** [comment]
那先关掉了，有问题再打开
