### ISSUE TITLE
[BUG] greasyfork.org cannot detect my Script Installation since v2.13.2.2 (include v2.13.2.2) v2.13.2.2版本开始Greasy Fork无法检测我安装过的脚本

### ISSUE THREAD

**Issue by Axotot1** [violentmonkey/violentmonkey#1872]
### Sequence of actions: 
1.Modify settings to enable related options(已修改设置)
![image](https://github.com/violentmonkey/violentmonkey/assets/99773418/78b2372a-9e68-4a41-9584-3b79c641df55)

2.Install any script from greasyfork.org（在greasyfork.org上安装任意脚本）
3.reload the Installation page.（刷新）

### Problem: 
and the script is not detected as 'Installed'.（无法检测到已安装脚本）
![image](https://github.com/violentmonkey/violentmonkey/assets/99773418/9d2d2f4f-b51e-41b7-81d2-cdb1442f96ff)

### Expected result:  

The 'Install' button should be replaced with 'ReInstall x.x.x version'.
（“安装此脚本”按钮应当变成“重新安装 xxx版本”）
like this (Using ViolentMonkey Beta v2.13.2.1): 
![image](https://github.com/violentmonkey/violentmonkey/assets/99773418/1c17c158-fed0-44dc-b399-299f4e196cf9)

#### Devtools console contents:

![image](https://github.com/violentmonkey/violentmonkey/assets/99773418/dfbe9859-9542-4ce1-9f40-a9be2c0b4be0)

#### Environment:
- OS: Windows 10 (10.0.19045.3086)
- Browser: Ungoogled Chromium 115.0.5790.99 from GitHub
- Violentmonkey Version: BETAv2.15.2 (also can be triggered since Beta v2.13.2.2)

ps: I am a Chinese. My English is very poor.

**Comment by Axotot1** [comment]
maybe caused by [this commit](https://github.com/violentmonkey/violentmonkey/commit/af17e83219ea895ac5bff356a8aa09cb94bf399e)?

**Comment by tophf** [comment]
The workaround for you until the fix is published in a new release is to create an empty script for greasyfork.org:

```js
// ==UserScript==
// @name        Fix Violentmonkey GetScriptVer
// @namespace   Violentmonkey Scripts
// @match       https://greasyfork.org/*scripts/*
// @grant       none
// @run-at      document-start
// ==/UserScript==
```

The script may be disabled after saving, it doesn't have to be active.
