### ISSUE TITLE
Circumvent TrustedHTML errors

### ISSUE THREAD

**Issue by psultan** [violentmonkey/violentmonkey#1873]
### Sequence of actions: 

1. Install Userscript
```
// ==UserScript==
// @name        Hello
// @namespace   Violentmonkey Scripts
// @match       https://calendar.google.com/calendar/*
// @require     http://code.jquery.com/jquery-latest.min.js
// @icon        https://www.google.com/s2/favicons?domain=google.com
// @grant       none
// @version     1.0
// ==/UserScript==
(function() {
    'use strict';
    console.log("Hello")
})();
```
2. Goto https://calendar.google.com/calendar/

### Problem:  
In Chrome Beta some sites are throwing a 'This document requires 'TrustedHTML' assignment.' error when the script sources a require file.  This is only happening in Chrome Beta now, but will likely be an issue in standard Chrome in the future.

This tampermonkey ticket seems related:  https://github.com/Tampermonkey/tampermonkey/issues/1334.  Using the linked 'Trusted-Types Helper' with violentmonkey fixes the issue for toplevel matches, but does not fix it for sub-frames (goto gmail and open calander sidepanel).  If I use the latest tampermonkey the require works on both toplevel and sub-frames (without the helper).

#### Devtools console contents:
```
This document requires 'TrustedHTML' assignment.
    (anonymous)	@	Hello.user.js:2
    ib	@	Hello.user.js:2
    fb.setDocument	@	Hello.user.js:2
    (anonymous)	@	Hello.user.js:2
    (anonymous)	@	Hello.user.js:2
    (anonymous)	@	Hello.user.js:2
    (anonymous)	@	Hello.user.js:2
    VMl5m11cb4xv	@	Hello.user.js:20
    Ut	@	injected-web.js:1
    (anonymous)	@	Hello.user.js:1
    Et	@	injected.js:1
    Dt	@	injected.js:1
    await in Dt (async)		
    St	@	injected.js:1
    $t	@	injected.js:1
    await in $t (async)		
    (anonymous)	@	injected.js:1
    await in (anonymous) (async)		
    (anonymous)	@	injected.js:1
    (anonymous)	@	injected.js:1
```

#### Environment:
- OS: Windows
- Browser: Chrome Version 117.0.5938.11 (Official Build) beta (64-bit)
- Violentmonkey Version: 2.15.0

**Comment by tophf** [comment]
We don't change CSP of the page currently, but seeing how more and more sites get hostile to userscripts I guess we'll have to do it.

**Comment by tophf** [comment]
After thinking this over, we can't remove the CSP of sites by default because it reduces security of sites, so having your script depend on removal of this header is not a good idea. More and more sites will use trustedTypes, so the most universal solution  is to reuse the policy of the site without removing it.

@gera2ld, maybe it can be implemented as a separate library similarly to vm-url?

**Comment by gera2ld** [comment]
> maybe it can be implemented as a separate library similarly to vm-url?

Sounds a good idea.

To make it clear, this issue is actually caused by `jQuery` trying to inject unsafe code, instead of sourcing a `@require`d file.
So it is not something we should fix in the extension.

**Comment by cyfung1031** [comment]
Just don't use jQuery. 
Here is a excellent alternative https://github.com/fabiospampinato/cash

**Comment by juliancastroorozco** [comment]
any script now is not working on youtube, please fix

**Comment by tophf** [comment]
Not any script, but only those that use the outdated method of manipulating html directly. The problem doesn't affect scripts that use the modern method of directly modifying DOM. Hence, Violentmonkey shouldn't "fix" it. The workaround for html-based scripts is mentioned in my comment above: https://github.com/tophf/trust-any-html

**Comment by cyfung1031** [comment]
> any script now is not working on youtube, please fix

https://greasyfork.org/en/scripts/433051-trusted-types-helper

Work with VM as well

**Comment by MaxikTheBest** [comment]
just use:  if (window.trustedTypes && window.trustedTypes.createPolicy && !window.trustedTypes.defaultPolicy) {
        window.trustedTypes.createPolicy('default', {
            createHTML: string => string,
            createScriptURL: string => string,
            createScript: string => string
        });
    }
