### ISSUE TITLE
[BUG] description doesn't looks good on Firefox Mobile 

### ISSUE THREAD

**Issue by ChowMein47** [violentmonkey/violentmonkey#1876]
Sorry if my report looks weird. I just want to report that the description of violentmonkey for Firefox mobile looks very disturbing as u can see from this screenshot. Is this violentmonkey's bug or Firefox? 
![Screenshot_2023-08-24-08-13-17-35_9c7ad408470e52983cc8816adf9ff347](https://github.com/violentmonkey/violentmonkey/assets/98148960/89418fa0-879f-4c8c-b0e7-61f86acc9ba8)

#### Environment:
- OS: Android 13
- Browser: Iceraven browser 2.8.5  
- Violentmonkey Version: 2.15.0

**Comment by tophf** [comment]
It's a bug in mobile Firefox, but to circumvent it we'll remove the link because it's not really necessary in the short summary.
