### ISSUE TITLE
[Feature] Retain user changes to code upon script update

### ISSUE THREAD

**Issue by ShintoPlasm** [violentmonkey/violentmonkey#1878]
**Motivation**
When scripts are updated, they get overwritten entirely by the new version. This resets any tweaks or configuration changes which have been made by the user directly in the code. The issue relates to scripts which DO NOT have a visible UI inside the browser, and where the user has to edit the code from within VM.

**Proposed Solution**
A function that parses the script's code for any sections titled 'config' or similar. The outcome could be either of the following:
1. VM automatically copies the relevant config changes in the old version of the script code, and tides them over to the equivalent 'config' section in the new script version.
2. VM presents the user with a question whether to copy over the existing config changes into the new version.
3. VM presents the user with a diff view of the old version vs the new version, highlighting any user changes made previously, and allowing the user to select what they'd like to retain in the new version's code.

Essentially, this could be implemented as a toggle in the VM settings, enabling or disabling the parsing function. Additionally (and optionally), this could also be implemented on a per-script basis: allowing the user to select which script(s) they'd like to keep track of where the new version overwrites user changes to the code.

**Use Cases**
A good example of a UI-less script is 'Control Panel for Twitter' (https://github.com/insin/control-panel-for-twitter).

Script: https://greasyfork.org/en/scripts/387773-control-panel-for-twitter

Whereas the standalone browser extension has a UI for the various options/tweaks, the script doesn't have any such UI and has to be tweaked directly in the 'config' section. Every time the script is updated to a new version, the new code overwrites the old version entirely, and any user-made tweaks in the code are lost.

**Comment by tophf** [comment]
We won't do it because it's too complicated for such a rare use case, which already has an established solution: Git with its pull and auto-rebase, which you can do either locally or in github.com. We will simply disable auto-updates for edited scripts in #1787.
