### ISSUE TITLE
Signed XPI Release on GitHub

### ISSUE THREAD

**Issue by Rictusempra** [violentmonkey/violentmonkey#188]
Could you add XPI to GitHub release?

**Comment by gera2ld** [comment]
Why not just install from AMO?

**Comment by anotherusername77** [comment]
I guess the reason of EMLVIRUS' asking is that on AMO the last release actually available is still (since May) v2.6.3 ( and the reason, I think, is more or less here: https://github.com/violentmonkey/violentmonkey/issues/165 ).

**Comment by EMLVIRUS** [comment]
Yes. @anotherusername77 is not missing anything. Getting a sign can be much easier than being hosted on AMO

**Comment by mrdokenny** [comment]
@gera2ld There's also the dev channel on AMO; it's basically an instant review.

https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance#How_do_I_submit_a_Beta_add-on

**Comment by gera2ld** [comment]
close via [v2.8.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.8.7)
