### ISSUE TITLE
[BUG] Reason why userscript is disabled it not fully visible in UI

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/violentmonkey#1885]
### Sequence of actions: 
1.  Make typo in userscript (in my case, I wrote `if (false} {}`
2. Reload page and notice VM icon does not list a script
3. Open VM ui and see script has a red line through it and some unreadable text below it 

### Problem: 
![Screen Shot 2023-09-05 at 09 20 33](https://github.com/violentmonkey/violentmonkey/assets/6006766/173cb112-00de-4652-81ff-88228e387388)

### Expected result:  
To read why it was disabled.  

#### Environment:
- OS: Linux
- Browser: Firefox 117 and Firefox Dev Edition 1.118.0b4
- Violentmonkey Version: 2.15 and 2.15.3 beta

I created a blank FF profile just in case I'd tweaked fonts or something, but I didn't see anything different.  But if it matters, they were all 16pt fonts.

I exported the HTML of the drop down menu and loaded it by itself and can see the problem that way as well.

If I disable the `.submenu {overflow-y: auto}` in FF's inspector menu, a scrollbar shows up alongside both the **Matched Scripts** and **LinkedIn Tool** rows and can scroll down and now see the message reads *Syntax error?*.

I see that the HTML reads `<sup class="syntax">Syntax error?</sup>` and that the class `syntax` includes `position: absolute`.  I am still new to HTML/CSS/JS, but my understanding is that `absolute` takes the element out of the flow and no space is allocated for it.  That that then confused me on why tweaking overflow-y allows the scrollbar to work.  WTFDIK?

**Comment by tophf** [comment]
Ah, geez, I'm so bad at reading. The problem is not the error per se, but styling of it.

**Comment by nexushoratio** [comment]
:->  My report was a bit rambling.  Sorry about that!

Thanks for fixing.
