### ISSUE TITLE
[Feature] sync rules and VM settings to iclouddrive (ventura 13.5 on M2 mac)

### ISSUE THREAD

**Issue by stillhope** [violentmonkey/violentmonkey#1886]
**Motivation**
I use CloudDrive not dropbox or google drive. The sync options currently do not include iclouddrive.
The sync options appear to be at rule level only. Could we please include userscripts (rule) and settings.

**Proposed Solution**
Add support for iclouddrive. Ventura 13.5 on M2 mac.

**Use Cases**
Set sync up so any changes on my macbook air are automatically updated in the sync file. a live backup so to speak. And when I use my second mac, when home, the rules and settings are there.

**Comment by gera2ld** [comment]
I don't think iCloud has open APIs for that, because Apple doesn't want that. So it's unlikely for us to support it as a web extension.

As a workaround, you may create a local folder and serve it with a WebDAV server, and sync that folder to your iCloud:

```mermaid
flowchart LR
    A[iCloud Drive] --- B(Local folder on macOS)
    B --- |WebDAV| C[Violentmonkey]
```
