### ISSUE TITLE
Request of Disallowing / Warning the installation of userscripts from Scam Site "Monkey Fork"

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1889]
https://www.monkeyfork.com/

This site pretends to be Greasy Fork, and creates fake users with the same names as script authors in Greasy Fork to clone the userscripts.

If users wrongly install the malware codes from Monkey Fork, the original owner might be blamed and taken of the responsibility.

I urge Violentmonkey to disallow or to warn the users who are going to install the scripts on Monkey Fork.

**Comment by tophf** [comment]
We can't list all such clones as there may be thousands. Such sites must be reported to authorities e.g. https://safebrowsing.google.com/safebrowsing/report_badware/
