### ISSUE TITLE
Post to Windows Store｜Migrate to Microsoft Edge

### ISSUE THREAD

**Issue by EMLVIRUS** [violentmonkey/violentmonkey#189]

**Comment by tiansh** [comment]
Maybe dupe of #79 ?

**Comment by EMLVIRUS** [comment]
indeed. Sorry that I missed it.

**Comment by jspenguin2017** [comment]
AFAIK the Edge extension store is full, Microsoft put a limit of 70. 
(Not sure why I can't comment on #79 )

**Comment by jspenguin2017** [comment]
AFAIK the Edge extension store is full, Microsoft put a limit of 70 so they can test the extension system in a controlled manner. 
(Not sure why I can't comment on #79 )

**Comment by franklinyu** [comment]
@jspenguin2017 We can still [sideload the extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions) ourselves, just not through Windows Store.

**Comment by jspenguin2017** [comment]
Yea but Edge will disable the extension on every start.
