### ISSUE TITLE
[BUG] Unable to Install Userscripts in Sleazy Fork

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1891]
### Sequence of actions: 
1. Go to Sleazy Fork and find a script, e.g. https://sleazyfork.org/en/scripts/375992-nhentai-helper
2. Click Install

### Problem: 

A dialog is shown that Userscript manager is not available.

### Expected result:  

Script can be installed via install button like Tampermonkey without any dialog.

#### Devtools console contents:

Nothing

#### Environment:
- OS: MacOS
- Browser: Chrome 116 
- Violentmonkey Version: 2.15.0

<img width="1298" alt="Screen Shot 2023-09-11 at 5 26 51" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/022f6d4a-01ec-4543-b2dc-0cd550124ae6">

Same for Chrome & Brave, Firefox

Unlike Firemonkey, Violentmonkey should behavior nearly the same way that Tampermonkey does. 
So it should work in both Greasy Fork and Sleazy Fork.

**Comment by tophf** [comment]
Until the fix is released you can click `I already have a script manager` and it'll enable installation for all scripts.

**Comment by cyfung1031** [comment]
@tophf 

in BETA v2.15.4,  `window.external.Violentmonkey` exists in sleazyfork.org, but the `isInstalled` always return `undefined`.
<img width="1236" alt="Screen Shot 2023-09-23 at 16 29 17" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/7cd58a18-2c50-4223-82cc-639242dbdc89">

**Comment by tophf** [comment]
It is controlled by an option in Violentmonkey, which is disabled by default:
![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/6831fb9e-029b-4cc7-837c-b11f4277b06a)
