### ISSUE TITLE
[Feature] Select Mutiple Script

### ISSUE THREAD

**Issue by HDark15** [violentmonkey/violentmonkey#1892]
**Motivation**
I want to delete all the script (100+)

**Proposed Solution**
Can select multiple script and delete all

**Comment by tophf** [comment]
We can add a button `Delete all scripts` next to `Vacuum database`, with two consequtive confirmations, @gera2ld?

**Comment by gera2ld** [comment]
No, this is a rare case, not worth a button in my opinion.

A workaround is to press arrow down, then keep pressing <kbd>x</kbd>.
