### ISSUE TITLE
[BUG] GM_info.isIncognito/isPrivate is not returning value

### ISSUE THREAD

**Issue by Knud3** [violentmonkey/violentmonkey#1893]
Not sure if this a bug or feature request. Greasemonkey and Tampermonkey has this feature.

### Problem:
```
console.log(GM_info.isIncognito)
console.log(GM_info.isPrivate)
```

Returns:
```
undefined
undefined
```

### Expected result

isIncognito/isPrivate should give status of private browsing.

#### Environment:
- OS: Windows
- Browser: Firefox 117.0
- Violentmonkey Version: v2.15.0

**Comment by tophf** [comment]
We can add it since Tampermonkey adds it. Note that Greasemonkey doesn't have this feature.

**Comment by Knud3** [comment]
Greasemonkey at least have had that: https://github.com/greasemonkey/greasemonkey/pull/2386/files
And feature is mentioned in here about Tampermonkey: https://github.com/Tampermonkey/tampermonkey/issues/943

**Comment by tophf** [comment]
Ah, the classic addon version. So I guess they may have forgotten to add it in the webext version.
