### ISSUE TITLE
[Feature] Add a `tag` option for GM_notification

### ISSUE THREAD

**Issue by helloworldSB** [violentmonkey/violentmonkey#1894]
**Motivation**

```javascript
// ==UserScript==
// @name        New script - github.com
// @namespace   Violentmonkey Scripts
// @match       https://github.com/*
// @grant       GM_notification
// @grant       GM_openInTab
// ==/UserScript==
'use strict';

(() => {
    // codes...
    const result = { // Simulate the result.
        id: 255,
        text: "New release has been found!",
        ver: "2.5.4",
        title: "Electronic-RRMusic",
        uri: "https://example.org/electronic-rrmusic/releases/v2.5.4"
    }
    GM_notification({
        onclick: () => GM_openInTab(result.uri),
        tag: result.id, // want this
        ...result
    });
})();
```
I want to use the `tag` option, [just like the legacy API](https://developer.mozilla.org/docs/Web/API/Notification/Notification#tag)

**Proposed Solution**

I don't want to use the Legacy API, because the Notification will turn into a "ghost" notification after user close the tab. (`onclick` function was destroyed, so nothing will happen when you click it)

**Use Cases**

To update the notification content.

**Comment by tophf** [comment]
Indeed, it looks like a useful feature. The documentation doesn't seem to elaborate but we'll treat `tag` to be unique within notifications of the calling script in any tab.

That said, next versions of Violentmonkey will remove ghost notifications by default, see #1888, so your old code will correctly work even without this new tag.

**Comment by helloworldSB** [comment]
> Indeed, it looks like a useful feature. The documentation doesn't seem to elaborate but we'll treat `tag` to be unique within notifications of the calling script in any tab.
> 
> That said, next versions of Violentmonkey will remove ghost notifications by default, see #1888, so your old code will correctly work even without this new tag.

That's good, however I still need the `tag` option.
I don't want to push a Notification twice just because of the release's comment changed
