### ISSUE TITLE
[BUG] searchParams.keys() is not iterable

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1895]
In Firefox 117.0.1 with Violentmonkey 2.15.0 the follow code does not work, while it worked earlier:

```js
// ==UserScript==
// @name        Twitter test demo
// @version     0.1
// @namespace   gh.alttiri.fetch
// @match       https://twitter.com/*
// ==/UserScript==

try {
  let posterUrl = "https://pbs.twimg.com/tweet_video_thumb/FedW-7_WIAExgJ3.jpg?test1=123&test2=456";
  let posterUrlObj = new URL(posterUrl);
  console.log("xxx", posterUrlObj);
  for (const key of [...posterUrlObj.searchParams.keys()]) {
    posterUrlObj.searchParams.delete(key);
  }
  console.log("xxx", posterUrlObj.toString);
  posterUrl = posterUrlObj.toString();
  console.log("xxx", posterUrl);
} catch (e) {
  console.log("xxx", e);
}
```

It throws `TypeError: posterUrlObj.searchParams.keys() is not iterable`.

**Comment by AlttiRi** [comment]
It works in Chrome:
![image](https://github.com/violentmonkey/violentmonkey/assets/16310547/af2ed75c-d420-487e-ac48-cd8d40e31757)

However, I see the grey icon, with an empty script list:
![image](https://github.com/violentmonkey/violentmonkey/assets/16310547/10fa3764-0991-4aa5-8ceb-eb862d67d817)



Chrome 109, Violentmonkey BETA 2.15.3.

**Comment by tophf** [comment]
It's a bug in Firefox that you encounter because the userscript is automatically injected in `content` mode due to twitter's CSP.

**Comment by tophf** [comment]
There are some workarounds listed in https://bugzil.la/1023984, so I'll see if we can apply one automatically...

**Comment by tophf** [comment]
BTW until then you can either try unchecking `Alternative page mode in Firefox` optionin Violentmonkey settings or use that `forEach` workaround in your script.

**Comment by AlttiRi** [comment]
> use that `forEach` workaround in your script

Yeah, already, thanks.

**Comment by tophf** [comment]
@gera2ld, do you think we should automatically apply a workaround for this bug if the scripts are injected in content mode and the code has words like FormData, URLSearchParams, searchParams, adoptedStyleSheets? It's not exactly trivial though:

<details><summary>Code</summary>

```js
function patchIteratorBugFF() {
  const iterSym = Symbol.iterator;
  const pushEntry = function (val, key) {
    safePush(this, [key, val]);
  };
  const pushKey = function (val, key) {
    safePush(this, key);
  };
  const pushValue = function (val) {
    safePush(this, val);
  };
  const collect = (src, fn) => {
    const res = [];
    src.forEach(fn, res);
    return res;
  };
  const iterEntries = function* () {
    for (const e of collect(this, pushEntry)) yield e;
  };
  const iterKeys = function* () {
    for (const e of collect(this, pushKey)) yield e;
  };
  const iterValues = function* () {
    for (const e of collect(this, pushValue)) yield e;
  };
  const patchObj = obj => {
    obj.entries = obj[iterSym] = iterEntries;
    obj.keys = iterKeys;
    obj.values = iterValues;
    return obj;
  };
  const assKey = 'adoptedStyleSheets';
  const assDesc = describeProperty(Document[PROTO], assKey);
  const assGet = assDesc?.get;
  if (assGet) {
    assDesc.get = () => patchObj(document::assGet());
    defineProperty(Document[PROTO], assKey, assDesc); // eslint-disable-line no-restricted-syntax
  }
  for (const obj of [SafeFormData, URLSearchParams]) patchObj(obj[PROTO]);
}
```

</details>

**Comment by cyfung1031** [comment]
Issue remains in Firefox Stable 118 + Violentmonkey 2.15.0
Issue disappears in FireFox Developer Edition 118.0b9 + Violentmonkey BETA 2.15.5
