### ISSUE TITLE
[Feature] Add a icon button to copy the script name

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1897]
**Motivation**

I want to copy the script name, but the script name is just clickable not selectable

**Proposed Solution**

Add a button after the script name for copying.

<img width="649" alt="Screen Shot 2023-09-19 at 17 14 57" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/bb01983a-5d77-4edc-b392-49dfcc635551">

**Use Cases**

**Comment by tophf** [comment]
It's easily selectable when it looks like your screenshot.

The problem is in the table view, but it's a bug which we'll fix, so you'll be able to select the name by click-dragging around it.

We defintely won't add a button because it's a rare task that's not related to the main purpose of the extension and even now you can copy it from inside the editor.

**Comment by cyfung1031** [comment]
@tophf  it is still not selectable in v2.15.4 (macOS)

**Comment by tophf** [comment]
Simply click around the name, not in the name.

**Comment by tophf** [comment]
Anyway, I don't have a Mac, so maybe it's something specific to the platform?

**Comment by cyfung1031** [comment]
> Simply click around the name, not in the name.

cannot.

**Comment by cyfung1031** [comment]
> Anyway, I don't have a Mac, so maybe it's something specific to the platform?

IDK

**Comment by cyfung1031** [comment]
How did you disable the drag & drop effect? by CSS? by event.preventDefault() ?

For me, the entire cell is still draggable except the script logo.

**Comment by tophf** [comment]
Sorry, it just occurred to me, it happens in the default execution order. I'll try to come up with a solution.

**Comment by tophf** [comment]
> How did you disable the drag & drop effect

I don't use the default sorting order inside the options button, I use "by update time" usually. BTW I think we should extract the order dropdown outside of the options so that it's always visible.
