### ISSUE TITLE
[BUG] Disabling redirects doesn't work

### ISSUE THREAD

**Issue by oifj34f34f** [violentmonkey/violentmonkey#1907]
### Goal

I want to make the browser ignore the `meta[http-equiv="refresh"]` redirect tag (in my example it is in the `<noscript>` tag)

### Sequence of actions:

1. Disable JavaScript (`about:config` -> `javascript.enabled`).
2. Install [this](https://greasyfork.org/en/scripts/16079-disable-autorefresh/code) userscript ("disables" `meta[http-equiv="refresh"]` redirect).
3. Open https://vk.com
4. See redirect (it shouldn't be):

![Screenshot](https://github.com/violentmonkey/violentmonkey/assets/128177553/7606478f-ffa3-4935-9876-871982347df4)

### Workaround:

Use this filter in uBlock Origin:

```
vk.com##^meta[http-equiv="refresh"]
```

#### Environment:
- OS: Linux
- Browser: Firefox 117.0
- Violentmonkey Version: 2.15.0

**Comment by tophf** [comment]
The fact that userscript's waiting for DOMContentLoaded behaves differently in Chrome and Firefox may mean there's a bug in one of the browsers with applying the refresh tag.

The userscript works if you enable `[x] Synchronous page mode` in Violentmonkey, which means the problem will be fixed when we use a dedicated browser API for userscripts, but it's not yet implemented in Chrome. There is a Firefox-only API but it currently doesn't allow running scripts in the main JS context of the page, so I don't want to use it now, as it's incompatible with a lot of scripts.

Here's a fixed version of the userscript that works in Firefox even without synchronous page mode. You may need to disable and then re-enable the extension as there was a bug in internal caching fixed only in beta 2.15.4.

```js
run();
addEventListener("DOMContentLoaded", run, {once: true});

function run(evt) {
  var allMetas,
  thisMeta,
  content,
  timeout,
  timeout_ms,
  rules;

  rules = [{
      host : 'moviesvids.blogspot.co.uk',
      timeout : .5
    }
  ];

  allMetas = document.getElementsByTagName('meta');
  for (var i = 0; i < allMetas.length; i++) {
    thisMeta = allMetas[i];

    if (thisMeta.httpEquiv.match(/refresh/i)) {
      if (thisMeta.content.match(/[\D]/)) {
        content = thisMeta.content.split(';');
        timeout = content[0] - 1;
        rules.forEach(function (rule) {
          if (location.host.indexOf(rule.host) > -1) {
            timeout = rule.timeout;
            return false;
          }
        })
        timeout_ms = (timeout > 0) ? (timeout * 1e3) : 0;
        setTimeout(function () {
          console.log('Redirection stopped after ' + timeout_ms + ' ms');
          window.stop();
        }, timeout_ms);
      }
    }
  }
}
```
