### ISSUE TITLE
I have successfully used Violentmonkey on my iPhone!

### ISSUE THREAD

**Issue by Wei-Winter** [violentmonkey/violentmonkey#1908]
There is a browser on iOS that can install third-party extensions called Orion. I installed the latest version of Violentmonkey for it, but the script did not take effect. After testing, only versions below v2.13 can successfully inject scripts into web pages and take effect, as mentioned in the post below. I installed Violentmonkey BETAv2.13.0.8 version and it successfully used the script in my mobile browser! But unfortunately, there are always some small bugs. For example, v2.13 cannot display the script menu. The older versions v2.12 and v2.10 can display the script menu, but the script runs unstable and so on. Can it be optimized according to this browser? It would be really cool if ios could run Violentmonkey perfectly. After all, Safari has too many restrictions.[](https://orionfeedback.org/d/547-tampermonkey-violentmonkey-do-not-work-properly/14) 
![IMG_0188](https://github.com/violentmonkey/violentmonkey/assets/134502767/d0430e03-f83b-4651-99e0-638515565e61)

**Comment by cyfung1031** [comment]
I don't think violentmonkey can work well on iPhone Safari.
You might consider to use https://github.com/shenruisi/Stay although it is developed by China developer.

**Comment by tophf** [comment]
If anyone wants to help, they woul dhave to either debug the code (ideally) or at least find the smallest range of versions where Violentmonkey stopped working (the one mentioned in the linked thread is 2.13.0.8 - 2.13.0.22 and that is too wide to be helpful).

**Comment by tophf** [comment]
Unfortunately this didn't help as there's nothing obvious in the log.

**Comment by cyfung1031** [comment]
@xiaoyuhaoge Just to tell you that, there are several fixs in both Violentmonkey and Orion. You can try again with Violentmonkey BETA and Orion's latest version.
