### ISSUE TITLE
[BUG] Settings Page becomes Two Columns when window maximizes

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1909]
In 2.15.0, BETA 2.15.4, BETA 2.15.5

Normal Window:
<img width="1322" alt="Screen Shot 2023-09-26 at 21 40 33" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/b3cd2559-dce1-48d1-91d5-9f14239378f4">

Max. Window:
<img width="1512" alt="Screen Shot 2023-09-26 at 21 40 45" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/e33cc674-e4ed-44b9-a266-374c13776b4a">

[screen-capture(9)-reformatted-00.00.02.539-00.00.14.482.webm](https://github.com/violentmonkey/violentmonkey/assets/44498510/b31d6001-8852-40be-8659-d9c3afa79cc7)

I believe there should be options to let users to disable two column mode.

### Related Issue

https://github.com/violentmonkey/violentmonkey/issues/1617

**Comment by cyfung1031** [comment]
I don't think "column-count" shall be applied.
That shall be `display: flex` with wrapping like script list.

and 

```css
    flex-basis: 534px;
    flex-grow: 1;
```
where 534px can be adjustable by user.

**Comment by tophf** [comment]
Nothing's changed since the last beta in this regard. The two-column mode was added in 2.13.0.14 in e916ffa4. It depends on the width of the browser (1440px).

I don't understand why you think this behavior is bad and why your idea is better.

**Comment by cyfung1031** [comment]
> Nothing's changed since the last beta in this regard. The two-column mode was added in 2.13.0.14 in [e916ffa](https://github.com/violentmonkey/violentmonkey/commit/e916ffa42da66a5d2cf5366b05f3ecaab8034b69). It depends on the width of the browser (1440px).
> 
> I don't understand why you think this behavior is bad and why your idea is better.

Yes. This is not added in latest beta.
There should be option to use two column or not.

**Comment by tophf** [comment]
> There should be option to use two column or not.

Like I said, why? I don't understand why you think this behavior is bad and why your idea is better.

**Comment by tophf** [comment]
Note that if you personally dislike it you can write your own Custom CSS.

**Comment by cyfung1031** [comment]
> > There should be option to use two column or not.
> 
> Like I said, why? I don't understand why you think this behavior is bad and why your idea is better.

I am not saying it is bad, but just like theme selection, people can have a choice.

**Comment by cyfung1031** [comment]
> Note that if you personally dislike it you can write your own Custom CSS.

I see.

**Comment by tophf** [comment]
We only add options if we think it'd be useful to many people, not because everything should have an option. So far you're the only one who objects this behavior and you didn't convince me it's bad, so until that happens we won't add an option. Please use Custom CSS, which was created intentionally to allow any customizations.
