### ISSUE TITLE
JAV老司机脚本使用115离线功能不正常

### ISSUE THREAD

**Issue by liangxyz** [violentmonkey/violentmonkey#191]
### What is the problem?
JAV老司机脚本使用115离线功能不正常，使用暴力猴加载脚本，点击115离线，会提示不是vip会员，没有离线额度了。使用tampermonkey，就可以正常离线
### How to reproduce it?
1.打开http://www.javlibrary.com/cn/?v=javlilq2qe
2.点击页面右侧115离线
3.屏幕右下角弹出离线失败提示名额不足

### What is the expected result?
屏幕右下角弹出离线成功提示，115离线列表增加影片链接
### What is the actual result?
屏幕右下角弹出离线失败提示名额不足
### Environment
- Browser:centbroswer
- Browser version:2.8.3.58
- Violentmonkey version:2.8.6
- OS:win10 15063

**Comment by Mattwmaster58** [comment]
Google translate of this.
## JAV old driver script uses 115 Offline is not functioning properly ##
### What is the problem? ###
JAV old driver script offline using 115 does not function properly, the use of violent monkey load scripts, click 115 offline, you will be prompted not vip members, no amount of off-line. Use tampermonkey, you can normally offline
### How to reproduce ###
1. Open http://www.javlibrary.com/cn/?v=javlilq2qe
2. Click on the right side of the page 115 offline
3. The lower right corner of the screen pops up offline failed to indicate a shortage of places
### What is the expected result? ###
The bottom right corner of the screen pops up offline successful tips, 115 offline list increases the video link
### What is the actual result? ###
The lower right corner of the screen pops up offline failed to indicate a shortage of places
 ### Environment ###

 -  Browser:centbroswer
 -  Browser version:2.8.3.58
 -  Violentmonkey version:2.8.6
 -  OS:win10 15063

**Comment by Mattwmaster58** [comment]
Note: Cent browser is based on chromium, user is not on latest VM build

**Comment by NudeSpoons** [comment]
@Mattwmaster58 Thanks for posting Google's translation; though it doesn't quite make sense.
@gera2ld Can you provide a clearer English translation?  Or, at least, provide a Label for this issue?

**Comment by tophf** [comment]
Probably works fine by now.
