### ISSUE TITLE
[BUG] v2.15.5 dark theme breaks default editor theme

### ISSUE THREAD

**Issue by Rikk** [violentmonkey/violentmonkey#1910]
When `UI theme: dark` / `Editor Theme: default`, script editor opens with a light theme (instead of dark) and with wrong colors (some parts are white on white).

![2023-09-28 17 46 56](https://github.com/violentmonkey/violentmonkey/assets/2916485/bc8ebff1-fac4-4013-9b5e-dfad4db8fed4)

This makes editor pretty unusable and requires changing themes for using.
Versions v2.15.4 and earlier are not affected.

**Comment by tophf** [comment]
It's already fixed in dev version 2939499b and [newer](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml), but not yet released.

**Comment by Rikk** [comment]
Nice, thank you.
