### ISSUE TITLE
Default edit panel are too dazzled.

### ISSUE THREAD

**Issue by helloworldSB** [violentmonkey/violentmonkey#1911]
Open a script's edit panel.
Normal look will like this:
![](https://z1.ax1x.com/2023/09/30/pPq6Jrq.png)

But in ViolentMonkey 2.15.5 BETA, it's look is:
![](https://z1.ax1x.com/2023/09/30/pPq6NZV.png)

#### Environment:
- OS: Windows 10
- Browser: Firefox/117.0.1
- Violentmonkey Version: 2.15.5 BETA

**Comment by tophf** [comment]
Please see #1910.
