### ISSUE TITLE
[Feature] `GMinfo.platform` cannot recognize more browsers well. Can the recognition be increased?

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1913]
`GMinfo.platform` doesn't recognize more browsers well, 

- such as Edge, Brave, Opera, Chromuim, etc., they are all recognized as Chrome; 
- such as Waterfox, SeaMonkey, Iceweasel， etc.,they are all recognized as Firefox;

which doesn't match the facts. Although similar are using the same kernel, they parse styles very differently, and many times it is necessary to differentiate between browsers.

So please add recognition of more browser brands, thanks.

**Comment by tophf** [comment]
There's no way to recognize it reliably.

**Comment by F9y4ng** [comment]
> There's no way to recognize it reliably.

TM can do it. 

At least in the BLINK kernel, the exact brand name can be obtained via `navigator.userAgentData`.

**Comment by tophf** [comment]
Yeah, and that's not reliable, but we can add it as `browserBrand`.

**Comment by F9y4ng** [comment]
yes, Vivaldi only has chromium brand in the `navigator.userAgentData`, just identify it as `chromium`, is that ok? Although the Vivaldi brand name can be obtained through `navigator.userAgent`, it is more unreliable, isn't it?😅

The current identification method is more like giving the name of the browser kernel. BLINK is called CHROME, and GECKO is called FIREFOX. The more detailed browser brand is not actually given. I think that **add it as browserBrand** would be a good idea.

As shown in common/ua.js:

https://github.com/violentmonkey/violentmonkey/blob/00d86603bacb3667d2e23272e9d7be27349c36a0/src/common/ua.js#L5-L46

**Comment by tophf** [comment]
> Vivaldi brand name can be obtained through navigator.userAgent

No, this browser intentionally doesn't expose its name anywhere.

**Comment by F9y4ng** [comment]
> > Vivaldi brand name can be obtained through navigator.userAgent
> 
> No, this browser intentionally doesn't expose its name anywhere.

It uses the chrome brand name, that's tooooooo bad. 😱
```JSON
[
    {
        "brand": "Chromium",
        "version": "116"
    },
    {
        "brand": "Not)A;Brand",
        "version": "24"
    },
    {
        "brand": "Google Chrome",
        "version": "116"
    }
]
```

Thanks for adding the brand name.
