### ISSUE TITLE
[BUG] GM setValue getValue not working in latest beta

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1915]
[screen-capture(11)-reformatted-00.00.02.202-00.00.38.950.webm](https://github.com/violentmonkey/violentmonkey/assets/44498510/ce022c30-39d0-411a-b22f-807fde35cb20)

### Sequence of actions: 
1. create userscript to setValue and getValue
```js
// ==UserScript==
// @name            NS037
// @namespace       https://greasyfork.org/
// @description     Make NS037
// @author          Me
// @version         0.1.0
// @grant           GM.setValue
// @grant           GM.getValue
// @match           https://www.youtube.com/*
// @exclude         https://www.youtube.com/embed/*
// @exclude         https://www.youtube-nocookie.com/embed/*
// @exclude         https://www.youtube.com/live_chat*
// @exclude         https://www.youtube.com/live_chat_replay*
// @exclude         /^https?://\S+\.(png|jpg|jpeg|gif|xml|svg|manifest|log|ini)[^\/]*$/
// ==/UserScript==

'use strict';
  (() => {

    'use strict';

    let mw = false;

    GM.getValue('annotationsenabled').then((r) => {
      mw = !r;
      console.log(999, r)
    }).then(() => {


      console.log(101, 'annotationsenabled', mw)
      GM.setValue('annotationsenabled', mw).then(()=>{


         console.log(102, 'annotationsenabled', mw)
        GM.getValue('annotationsenabled').then((r) => console.log(103, r))

      });


    });

  })();

```
3. run in a page in youtube.com (e.g. https://www.youtube.com/watch?v=M2cckDmNLMI )
4. reload the page

### Problem: 

GM value get reset
(i.e. `999, undefined` is always printed in console)

### Expected result:  

GM value shall be persistent
(i.e. `999, true` OR `999, false` shall be printed in console)

#### Environment:
- OS: MacOS
- Browser: Firefox Developer Edition 119.0b2  
- Violentmonkey Version: 2.15.6 BETA (latest CI)

#### Remarks:
1. I am not sure this bug appears from which BETA version.
2. Not only Firefox but also Chrome (e.g. Brave)
3. Tried restart the browser but in vain.

**Comment by cyfung1031** [comment]
Same code but with "async"

Same result.

```js
// ==UserScript==
// @name            NS037
// @namespace       https://greasyfork.org/
// @description     Make NS037
// @author          Me
// @version         0.1.0
// @grant           GM.setValue
// @grant           GM.getValue
// @match           https://www.youtube.com/*
// @exclude         https://www.youtube.com/embed/*
// @exclude         https://www.youtube-nocookie.com/embed/*
// @exclude         https://www.youtube.com/live_chat*
// @exclude         https://www.youtube.com/live_chat_replay*
// @exclude         /^https?://\S+\.(png|jpg|jpeg|gif|xml|svg|manifest|log|ini)[^\/]*$/
// ==/UserScript==

'use strict';
(async () => {

    'use strict';

    let mw = false;


    let r1 = await GM.getValue('annotationsenabled');

    mw = !r1;
    console.log(999, r1);

    console.log(101, 'annotationsenabled', mw)
    await GM.setValue('annotationsenabled', mw);


    console.log(102, 'annotationsenabled', mw)
    let r2 = await GM.getValue('annotationsenabled');
    console.log(103, r2)


})();
```

**Comment by cyfung1031** [comment]
Toggle the ON/OFF button (video time: 0:18) can make the result a bit different, but as `mw = !r1`, it will set it to `false` then the value is "removed"

[screen-capture(12)-reformatted-00.00.00.957-00.00.33.782.webm](https://github.com/violentmonkey/violentmonkey/assets/44498510/be4827b7-7b19-44d3-8f1c-f6524a1e2c54)

**Comment by tophf** [comment]
Yeah I already found the problem and fixed it, thanks, I'll upload the fix soon.
