### ISSUE TITLE
[Feature] Customizable size of popup menu

### ISSUE THREAD

**Issue by xushet** [violentmonkey/violentmonkey#1919]
There are so many scripts installed that you need to see more when managing scripts enabled and disabled, and the popup menu experience is terrible on small monitors.

**Comment by gera2ld** [comment]
I don't think it's worth an option.
But indeed, the current popup size is too small on a retina display.

Can you provide more information for what you expect?

**Comment by tophf** [comment]
The height of the popup is limited by the browser, so there's nothing we can do about it, AFAICT.

>  the popup menu experience is terrible on small monitors.

You really need to elaborate and show screenshots when you make emotionally charged claims like this.

**Comment by tophf** [comment]
Realistically we can add two options:
1. `[x] Compact mode` to hide the footer, reduce the height of items, move the "Find" commands into the ⋮ menu
2. `[x] Two columns` when `Group disabled scripts` option is selected, so the disabled scripts will be shown in a separate column to the right, the popup will be 2x wider.

**Comment by tophf** [comment]
This is already possible via `Custom CSS` in the advanced options, here's an example:

```css
body {
  width: 800px;
}
.menu.expand>.submenu {
  display: flex;
  flex-wrap: wrap;
}
.script {
  width: 33%;
}
.menu-item {
  min-height: 1rem;
}
```

**Comment by Tback1** [comment]
> This is already possible via `Custom CSS` in the advanced options, here's an example:
> 
> ```css
> body:has(.page-popup) {
>   width: 800px;
> }
> .page-popup .menu.expand>.submenu {
>   display: flex;
>   flex-wrap: wrap;
> }
> .page-popup .script {
>   width: 33%;
> }
> .page-popup .menu-item {
>   min-height: 1rem;
> }
> ```

but can't change the height of popup. but at last give me a 800*600, now just 400*X

**Comment by tophf** [comment]
> but can't change the height of popup. but at last give me a 800600, now just 400X

Works for me. Please show a screenshot and your code.

**Comment by Tback1** [comment]
> > but can't change the height of popup. but at last give me a 800600, now just 400X但无法更改弹出窗口的高度。但最后给了我一个 800600，现在只有 400X
> 
> Works for me. Please show a screenshot and your code.对我有用。请出示屏幕截图和您的代码。

I don't meaning it not work,and it show multi-line for the item. but the whole pop-menu height less 400 ( I know the Chrome limits it is 800*600 ), this is ridicules and ugly, I tried use devtool to solve this,but not work.  finally I have to give up .

![image](https://github.com/violentmonkey/violentmonkey/assets/8872546/2774af43-ac1d-4be4-8c5e-3ea7044e0add)

**Comment by tophf** [comment]
I don't understand what you want to achieve. Maybe you can demonstrate a sketch?

**Comment by Tback1** [comment]
> I don't understand what you want to achieve. Maybe you can demonstrate a sketch?

I just want the pop-menu had enough height ( at last fit the limits by Chrome）

**Comment by tophf** [comment]
I didn't see your edited comment at first, now I see it, and I don't understand why the popup is so short in your case, I can't replicate this behavior here, i.e. it's 600px by default.

**Comment by tophf** [comment]
I guess you're using 200% page zoom in Chrome? In that case it's a bug in the browser.

**Comment by Tback1** [comment]
> I didn't see your edited comment at first, now I see it, and I don't understand why the popup is so short in your case, I can't replicate this behavior here, i.e. it's 600px by default.

I don't know why it too! I use the default setting and just add the css

```css
body:has(.page-popup) {
  height: 600px;
}
```

**Comment by tophf** [comment]
Your screenshot shows you have zoom. It's either in Chrome's settings or in the OS.

**Comment by tophf** [comment]
There's no need to add 600px, it's the internal limit in Chrome anyway.

**Comment by Tback1** [comment]
> Your screenshot shows you have zoom. It's either in Chrome's settings or in the OS.

I tested this is the reason. I zoom the `chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options/index.html#settings` 

So I thinks this is a error.
We should separate the zoom rendering of the settings page and the pop-up page.

**Comment by tophf** [comment]
We can't separate zoom, the browser applies it automatically to all pages of the extension.

**Comment by Tback1** [comment]
> There's no need to add 600px, it's the internal limit in Chrome anyway.

I know so that's why I tried to use  css to fix the height to 600, because after the zoom it's just give me a so less height 😢

**Comment by tophf** [comment]
> high dpi is also a trouble

It's not a problem if you set scaling in the OS settings. This is what I thought everyone was doing.

**Comment by Tback1** [comment]
> We can't separate zoom, the browser applies it automatically to all pages of the extension.

I'm confused about this, because I used Tampermonkey before, and I can test it and show you now, zooming its settings page, but its popup rendering does not follow the scaling.

Of course, his settings page and pop-up window use two different html files for rendering

![image](https://github.com/violentmonkey/violentmonkey/assets/8872546/60fc6305-a980-4873-975f-1ac47b389fe5)

![image](https://github.com/violentmonkey/violentmonkey/assets/8872546/87ffb0dd-210e-4b63-ac25-32d56c13784f)

**Comment by tophf** [comment]
Ah, now I understand the problem and I can replicate it here, so indeed there's a bug in our handling of zoom.

**Comment by Tback1** [comment]
Okay, it seems that I can continue to evaluate and migrate my script manager. Thank you for your patience and carefulness (I did not expect that zooming will cause the pop-up window height to be reduced such a bug)
