### ISSUE TITLE
[BUG] Error would show if the script uses broken url for `@icon`

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1920]
### Sequence of actions: 
1. install https://greasyfork.org/en/scripts/439699
2. its `@icon` is `// @icon               https://api.iowen.cn/favicon/get.php?url=greasyfork.org`
3. https://api.iowen.cn/favicon/get.php?url=greasyfork.org is 404

### Problem: 

As `@icon` is linking to a non-image response, error is shown in violentmonkey.

### Expected result:  

broken icon shall be treated as no `@icon`. No error shall show.

#### Devtools console contents:

I get it in Chrome's load unpacked extension.
<img width="666" alt="Screen Shot 2023-10-06 at 13 20 39" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/945e8ff4-6ef3-411f-9b14-f25f5261998d">

#### Environment:
- OS: MacOS
- Browser: Brave Version 1.58.137 Chromium: 117.0.5938.153 (Official Build) (arm64) 
- Violentmonkey Version: BETA

**Comment by F9y4ng** [comment]
This function should be inherited from greasymonkey. If the links of `@require` and `@icon` cannot be accessed, an error will be reported.

**Comment by tophf** [comment]
It's a debugging message for the db health check. If you don't want to see it you can disable `[ ] Collect errors` in the details of the extension in chrome://extensions page.
