### ISSUE TITLE
[Feature] Add option to export GM values as well

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1921]
**Motivation**

I want to move all my settings from old version to new version of violentmonkey via export zip
most are exported and able to re-import, except those values set by `GM.setValue(...)`

**Proposed Solution**

There shall be a checker option in the export setting page to allow people export zip including GM values

**Use Cases**

https://greasyfork.org/en/scripts/473830-greasy-fork
* This script use `const isScriptFirstUse = await GM.getValue('firstUse', true);` to detect the first time of using the script, and show the setting dialog in the first usage in https://greasyfork.org/en/
* Then `GM.setValue('firstUse', false);`

So, the zip export shall include `GM value firstUse = false` as well.

<img width="420" alt="Screen Shot 2023-10-06 at 13 42 05" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/a404822a-59af-41bd-ba34-955f594b1396">

I am not sure it is a feature or a bug.
I tested in the latest CI build (2.15.7 BETA)

**Comment by gera2ld** [comment]
We already have "Export script data" option. It is a bug if it does not work.

**Comment by tophf** [comment]
I've tested 2.15.7 and it properly exports the values, but there's a bug in import. Until it's fixed please do the import twice: the second one will import the values successfully.

**Comment by cyfung1031** [comment]
Confirm Issue Resolved
