### ISSUE TITLE
[BUG] `Import from zip` cannot restore backup. `v2.15.7 BETA CI`

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1922]
I download new BETA version `Violentmonkey-test-webext-v2.15.7-19-gbfc1902` from [CI](https://github.com/violentmonkey/violentmonkey/suites/16937316586/artifacts/967596892)

When I restored the backup through `Import from zip` on the settings page, the scripts and settings in the original backup were not restored.

![cannt restore](https://github.com/violentmonkey/violentmonkey/assets/15855068/46f9bab2-26bf-49bb-a17f-ceed22b30009)

#### Environment:
- OS: Windows10
- Browser: Chrome 117
- Violentmonkey Version:v2.15.7 BETA CI

**Comment by tophf** [comment]
Works for me.

**Comment by F9y4ng** [comment]
It's so weird.

I kept getting `0 item(s) are imported` no matter how I restored this afternoon and couldn't restore the backup correctly.

I've forgotten what I set up this afternoon, and now reinstalled `2.15.7BETA CI` and it was able to restore!!

But there is a new problem: restoring the same backup, the scripts keep growing instead of overriding the `NAME + NAMESPACE` same scripts, As shown:

![cam](https://github.com/violentmonkey/violentmonkey/assets/15855068/6603b060-cb42-4735-ab1b-f5834da2975e)

**Comment by tophf** [comment]
I can't reproduce. Works correctly for me in the latest CI.

**Comment by tophf** [comment]
I guess your backup is broken because it was made in an earlier build that was affected by the bug I fixed today.

**Comment by F9y4ng** [comment]
I just installed the latest version of `Violentmonkey-test-webext-v2.15.7-22-g08e7f1c`, all the problems in the previous `Violentmonkey-test-webext-v2.15.7-19-gbfc1902` have been fixed. Thanks.

**Comment by cyfung1031** [comment]
Try 2.15.8.
I believe most issues have been gone in 2.15.8
