### ISSUE TITLE
[BUG] Cannot import local userscript in brave browser

### ISSUE THREAD

**Issue by skrabadiloseidon** [violentmonkey/violentmonkey#1923]
### Sequence of actions: 
1. created a local userscript with userscript generator named "index.user.js"
2. drag & drop "index.user.js" to violentmonkey dashboard -> browser shows a save file dialog to store the "index.user.js" in downloads. No dialog from violentmonkey to import
3. used the local http server method, same result, when opening the url, just get a download dialog

### Problem:
I cannot install a userscript from local file, browser is always open a safe file dialog. No dialog from violentmonkey.
File url access was enabled on the plugins page.

### Expected result:
File should be installed in Violentmonkey insteal of opening browser safe dialog.

#### Devtools console contents:
nothing

#### Environment:
- OS: Windows
- Browser: Brave 1.58.137
- Violentmonkey Version: v2.15.0

**Comment by tophf** [comment]
To drag'n'drop a local file directly you need to enable `Allow access to file URLs` in the details of an extension inside chrome://extensions page.

As for the local http server, I guess the one you've used adds a download header on files that aren't html. Try using a different server.

**Comment by skrabadiloseidon** [comment]
I enabled "Allow access to file URLs" on the chrome://extensions and used the server mentioned on this page: https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/.

**Comment by tophf** [comment]
It works for me in Brave, so I guess your file is either in a weird text encoding or it lacks the correct metadata block comment.

**Comment by skrabadiloseidon** [comment]
No, i used the file generated by the user script generator https://violentmonkey.github.io/guide/using-modern-syntax/. I also copied the content of a new, empty userscript created via violentmonkey dashboard, stored as a file, renamed to "test.user.js", dragged to the browser, same behaviour. File Encoding is UTF-8.

File content:
```
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description 7.10.2023, 15:03:39
// ==/UserScript==
```

**Comment by skrabadiloseidon** [comment]
I found the reason, when the "Website Access" in the extension settings is set to "On Click" or limited to specific domains, it does not work. It needs to be set to allow all webpages.

**Comment by tophf** [comment]
You can add `file://*/*` to the allowed domain, I suppose.

**Comment by skrabadiloseidon** [comment]
> You can add `file://*/*` to the allowed domain, I suppose.

unfortunately no, it shows that it is an invalid one, even when you type only "file://*". it looks like only http/s is allowed

**Comment by tophf** [comment]
Maybe add the localhost domain for the server?
