### ISSUE TITLE
[BUG] Native Class Inheritance (Firefox, @inject-into content)

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1924]
## Problem

```js
// ==UserScript==
// @name          Native Class Inheritance
// @description   Testing
// @match         *://*/*
// @version       1.0
// @run-at        document-start
// @inject-into   content
// ==/UserScript==

const BaseClass = MutationObserver;

class ExtendedClass extends BaseClass {

  constructor() {
    super(...arguments);
  }

  myFunc() {
  }
}

const newObject = new ExtendedClass(() => {});
const res = 'myFunc' in newObject;

console.log(GM.info.scriptHandler, `result is '${res}' (correct result is 'true')`);
```

## Details

see https://github.com/erosman/support/issues/526

For violentmonkey, this bug is only found in `content` mode.

## Bugzilla

> Subsequent to a chat with Mozilla engineers, a bug was filed.
> [Instantiated subclass of Xray-wrapped DOM constructor is not an instance of the subclass, but the superclass](https://bugzilla.mozilla.org/show_bug.cgi?id=1820521)
> Also:
> [Can't define new custom element after a previous one was created, in Add-On Content Scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1771291)

_Originally posted by @erosman in https://github.com/erosman/support/issues/526#issuecomment-1456451561_
            

## Remarks

I am not sure whether violentmonkey can resolve this or not. Just FYI.
I tested in Waterfox Classic + Violentmonkey as well, also failed.

**Comment by tophf** [comment]
Violentmonkey can't do anything about Xrays bugs.
