### ISSUE TITLE
[BUG] Cannot perform further update action as the result in last update "no update found" is cached.

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1926]
### Sequence of actions: 
1. Create a script and host it in Greasy Fork, say v1.0.0
2. Install the script (v1.0.0)
3. Update the script in Greasy Fork, to v1.0.1
4. Click "Update" in violentmonkey => The script is updated from 1.0.0 to 1.0.1
5. Click "Update" in violentmonkey => "No update found." 
6. Update the script in Greasy Fork, to v1.0.2
7. Click "Update" in violentmonkey

### Problem: 

In Step 7, result: "No update found." 

### Expected result:  

(the update button shall invalidate the cache)
the script shall be updated to v1.0.2.

#### Devtools console contents:

N/A

#### Environment:
- OS: MacOS
- Browser: Brave Version 1.58.137 Chromium: 117.0.5938.153 (Official Build) (arm64) 
- Violentmonkey Version: BETA v2.15.8

## Remarks

This bug long exists since earlier versions.
If the version does NOT change for the first update action, seems like there is a cache, so the script is believed as latest, and do not accept any more update request.

~If the browser extension is re-enabled, then the cache will be gone and the update button will work again.~

--------------

click update -> update found -> OK -> click update -> update found -> OK -> click update -> update found -> OK -> ...

click update -> update found -> OK -> click update -> update NOT found -> <<<< cached >>>>
-> click update -> update NOT found (due to cache) -> click update -> update NOT found (due to cache) -> ...

**Comment by tophf** [comment]
Could you check the [background console](https://stackoverflow.com/a/10258029) and see if the response from greasyfork has the same `E-Tag` header or is it different?

**Comment by cyfung1031** [comment]
Cannot find a reliable way to reproduce the issue.

There were some error messages before but I did not capture. something like iframe removed.
Might not might not related.

<img width="1511" alt="Screen Shot 2023-10-11 at 2 33 32" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/1293d536-07fd-4f25-ab71-d659c2400fe9">

**Comment by cyfung1031** [comment]
With toggling the entire extension. still unable to update


https://github.com/violentmonkey/violentmonkey/assets/44498510/b1d9f70e-57c1-4b12-9440-df64ff52aaf1

**Comment by tophf** [comment]
I see that all responses have the same `Etag` and `Last-Modified`, which means it's a bug in greasyfork. Please open this URL in a new tab right after Violentmonkey doesn't find the update and see if it's new or old.

**Comment by cyfung1031** [comment]
> Please open this URL in a new tab right after Violentmonkey doesn't find the update and see if it's new or old.

OK.. might be few more days later.

But just want to say that, I think "no-cache" is not really injected into the fetch requests (HEAD).
(not shown in console)
> https://github.com/violentmonkey/violentmonkey/blob/fa1433445038b564492a045be8ed3e4c25ba4dbf/src/background/utils/storage-fetch.js#L62C29-L62C29
<img width="973" alt="Screen Shot 2023-10-11 at 9 11 53" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/2cac745c-1a4a-4f98-93d2-79d285816298">
<img width="977" alt="Screen Shot 2023-10-11 at 9 12 04" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/eb59c8cc-1413-4b91-9b0a-a4c69edb184a">

<img width="980" alt="Screen Shot 2023-10-11 at 9 12 12" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/07f2ba6c-3caf-4f4c-b034-0352e1351a83">


Is this a bug?

**Comment by tophf** [comment]
Wee use [cache: 'no-cache'](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) in `fetch`, which means that greasyfork is either bugged (as I suggested) or it intentionally lies in order to throttle the update requests.

**Comment by cyfung1031** [comment]
I tried to use fetch API with GET request of the same url in background console in violentmonkey and console in Greasyfork webpage.
```
fetch('https://greasyfork.org/scripts/xxxxxxxx/code/xxxxxxxxxxx.user.js', {cache: "no-cache"})
```
The response is different.

Anyway, just keep this issue open and I will post more if I can get more evidence on this topic.

**Comment by tophf** [comment]
Try the [new CI build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml), which always makes a full GET request on manual update check.

**Comment by cyfung1031** [comment]
right now not reproducible. reopen if issue appears again.
