### ISSUE TITLE
[BUG] GM.getResourceUrl returns an empty string in Chrome but not in Firefox

### ISSUE THREAD

**Issue by Sv443** [violentmonkey/violentmonkey#1930]
I found this while testing for #1927

### Sequence of actions: 
1. Install example userscript
2. Go to https://example.org using Google Chrome
3. Open console to see that the `test` resource returns an empty string
  
**Example userscript:**  
  
```js
// ==UserScript==
// @name        getResourceUrl test
// @namespace   https://github.com/Sv443
// @match       https://*.example.org/*
// @version     1.0
// @grant       GM.getResourceUrl
// @resource    test https://raw.githubusercontent.com/Sv443/BetterYTM/develop/assets/icons/close.png
// ==/UserScript==

(async () => {
  console.log("function", GM.getResourceUrl);

  const prom1 = GM.getResourceUrl("test");
  console.log("promise 1", prom1);
  const url1 = await prom1;
  console.log(`url 1 '${url1}'`);

  const prom2 = GM.getResourceUrl("test123");
  console.log("promise 2", prom2);
  const url2 = await prom2;
  console.log(`url 2 '${url2}'`);
})();
```

### Problem: 
On Chrome, the function `GM.getResourceUrl()` returns an empty string for a resource that is defined and available:  
  
<img width="522" alt="image" src="https://github.com/violentmonkey/violentmonkey/assets/38158426/1a78bc9c-e6c3-4dc2-aa55-a3a398835e85">
  
On Firefox meanwhile the exact same script works as expected:  
  
<img width="921" alt="image" src="https://github.com/violentmonkey/violentmonkey/assets/38158426/c94bd5f9-4258-4094-802d-f966cace2c73">
  
### Expected result:  
A `blob:` URL should be returned, like it is on Firefox

#### Devtools console contents:
see above

#### Environment:
- OS: MacOS 14.0
- Browser: Chrome 118.0.5993.70 and Firefox Developer Edition 119.0b7
- Violentmonkey Version: [v2.15.8-16-g1cc84e5 (from CI)](https://github.com/violentmonkey/violentmonkey/actions/runs/6485345332)

**Comment by tophf** [comment]
Chrome 109 has nuked URL.createObjectURL via a detached iframe that we used for security, just like it did for console.log. I don't like the idea of switching to an unsafe method, so I guess we'll provide the result as a base64 data URI by default, same as Tampermonkey, and maybe even remove the isBlobUrl parameter completely.

**Comment by tophf** [comment]
Meanwhile the workaround is to use `GM.getResourceUrl("test", false)`

**Comment by Sv443** [comment]
I see. Though I think polluting the DOM with gigantic base64 data URIs is also kind of a bad thing, I guess there's no other choice.

**Comment by tophf** [comment]
There might be a way to keep the current behavior, I'm testing it now.

**Comment by tophf** [comment]
Yeah it worked. My initial implementation erred too much on the side of caution.

**Comment by Sv443** [comment]
Can confirm this is now working again, thanks again!
