### ISSUE TITLE
Does not work with Citrus GFork

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#194]
### What is the problem?

It fails to work with <a href="https://greasyfork.org/en/scripts/4336-ts-citrus-gfork">Citrus GFork</a> on both FireFox 55.0.3 and latest Chrome. 

### How to reproduce it?
1. Install the script 
2. Go to: https://greasyfork.org/users/1455-timidscript
3. Look at the console

### What is the expected result?

Suppose to change the layout of the site. 

FYI. The script works fine with TamperMonkey and GreaseMonkey

### What is the actual result?

On Chrome it does not know the TSL library. The library is in the @require.
--> // @require             https://greasyfork.org/scripts/19968/code/TSLibrary - Generic.js

On Firefox it says that the r is not defined. It is near impossible to debug as it condenses all the code, making console output with error line pretty useless. 

Maybe you should consider not minimising (condensing) the scripts.

### Environment
- FireFox 55.0.3
- Chrome  60.0.3112.113 
- Violentmonkey version: 2.8.6
- OS: Windows 10

**Comment by gera2ld** [comment]
The reason is, `https://greasyfork.org/scripts/19968/code/TSLibrary - Generic.js` is actually not a valid URL. But I will handle this.
