### ISSUE TITLE
[BUG] New version of userscript will not become active for quite a while

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/violentmonkey#1940]
This may be a duplicate of #1926, but I did not want to clutter that if it turns out to be different.

### Sequence of actions:
0.  As developing on FF, I am running a mini webserver to serve up the script: `python -m http.server -d src/userscripts/`.  It has been working for me for months.
1. Change anything in my userscript, like a log message.
2. See VM's tracking tab noticed the change and loaded it.
3. Reload the page, see old string logged.
4. Wait a few minutes (I did not time, but 10 minutes sounds about right), and see the new string logged.

Restarting the browser seems to fix immediately.

It does not always get stuck.  Sometimes it will unstick and work as expected for a while.

I am experimenting with FF Dev Edition and latest VM build and so far it seems to be working.  However, since it does not always get stuck, I am not fully convinced yet.

### Problem:
Old string logged.

### Expected result:
New string logged.

#### Environment:
Not working:
Userscript manager: Violentmonkey 2.15.0
  injected into "content"
Platform: firefox 118.0.2 linux x86-64

Working so far:
Userscript manager: Violentmonkey 2.15.9
  injected into "content"
Platform: firefox 119.0 linux x86-64 (really, Developer Edition 119.0b, 20231013091412)

### Remarks

I have only started noticing this happening recently (last couple of weeks?), around the same time I started using *GM.{get,set}Value()*.  My initial thought that having multiple VM tabs open was causing the problem.  One for watching/editing script values, and one for watching for source changes.  But I think my solution of *closing the script values tab* really just resulted in me wasting time and for things to unstick.

My userscript has been growing, not sure if causing any issues.  Neither the main script nor the local version of lib/base will load.  When process unsticks, they both load fine.
```
Code    [↗](http://localhost:8000/linkedin-tool.user.js)http://localhost:8000/linkedin-tool.user.js    164 k
@require    [↗](https://cdn.jsdelivr.net/npm/@violentmonkey/shortcut@1)https://cdn.jsdelivr.net/npm/@violentmonkey/shortcut@1    6 k
@require    [↗](https://greasyfork.org/scripts/477290-nh-base/code/NH_base.js?version=1266925)https://greasyfork.org/scripts/477290-nh-base/code/NH_base.js?version=1266925    36 k
@require    [↗](http://localhost:8000/lib/base.js?1864366778)http://localhost:8000/lib/base.js?1864366778    40 k
```

After finding #1926, I tried the suggestions listed there.  None seemed to work except for (maybe) upgrading.

I am going to downgrade VM in the dev browser to see if it reproduces there.  If I can reproduce, I'll figure how to view VM's logs and see if there is anything interested in there.

**Comment by tophf** [comment]
If I understand correctly, there's no bug in 2.15.9, in which case the bug is fixed.

**Comment by nexushoratio** [comment]
I'm not *certain* there is no bug in 2.15.9.

There still might be, and that I simply have not yet used it long enough to verify one way or the other.

Yes, I am hoping it it fixed.  But as they used to say at work, "Hope is not a strategy."

Also, note that I changed two things at the same time:  Browser version and VM version.  Either could have it.

And, FTR, I did just have this happen in the FF 119.0 + VM 2.15.0.  It was working for a while, then just stopped.

I'll collect more data after we visit the dog park and have dinner.

**Comment by nexushoratio** [comment]
Once it gets stuck updating, I can reliably unstick it by doing the following in FF:
1. Open the debug console for the extension (about:addons -> settings gear -> Debug Add-ons -> find VM in the list, click the `Inspect` button).
2. In the debug console, click the `Reload` button to effectively restart the add-on without restarting the browser (this technique works whereas others I've tried, like toggling VM off/on, has not)
3. Reload website
4. Success!   (well, until the next edit)

I can update the script, click on page my local webserver hosts to load the new version of the userscript then tell VM to update it and close.  Returning to the real website, I reload that web page, and see it is still using the old code.

I kill my webserver so I know VM can NOT load it again  Goint into the extension debugger and poking around in the Storage tab -> Extension Storage -> key code:1, I can see my change.  So it appears VM fetched it and stored it locally.

Reload the website again, still old version.

Use the debug to restart VM.

Reload the website, now see the update.  And my server hosting the userscript was not running.  VM successfully injected the correct version into the website after pulling it from its own storage.

Now, if only I could figure how to make it start happening on demand!

**Comment by nexushoratio** [comment]
I finally managed to make it work *almost on demand* just by constantly incrementing the version number in the userscript and reloading.  I could get two or three reloads before it would get stuck again.

I went through the following process, starting with VM 2.15.0:
1. Install VM
2. Restart browser
3. Load website and verify userscript version (my script shows it in a popup).
4. Edit script, bumping version number
5. Have VM install new version
6. Reload website and verify userscript version -- if it updates, go back to step 4.
7. If it did not update, try a couple more times to verify not a user problem.
8. Select the next version of VM and go back to step 1.

If I manage to keep bumping the version number and it keeps loading, eventually I'll go back to the previous version of VM and verify it has the problem.

Eventually I got to where it seems VM 2.15.4 fixed the problem.

I looked at the release notes and found bug #1793 . 

So yeah, this IS a duplicate, just of a different one.  And I suppose you can add FF/Linux to the list of platforms affected by that bug.
