### ISSUE TITLE
[Feature]  Add `url` property for `GM_notification` to open a new tab on click and make it more persistant.

### ISSUE THREAD

**Issue by helloworldSB** [violentmonkey/violentmonkey#1943]
**Motivation**

```javascript
// ==UserScript==
// @name        New script - github.com
// @namespace   Violentmonkey Scripts
// @match       https://github.com/*
// @grant        GM_notification
// @author      x
// @description 2023/10/28 09:25:14
// ==/UserScript==
'use strict';
let API_URL = "https://example.org/api234";
const cache = {};
setInterval(async () => {
    const item = await fetch(API_URL);
    if (!(item.name in cache) || item.version > cache[item.name]) {
        cache[item.name] = item.version;
        // Hope --> GM_notification(item.name, {url: item.url});
       const ct = GM_notification(item.name, {onclick: () => {window.open(item.url); ct.remove();}}) // Actually
    }
}, 5000);
```
It just push an notification that refer to an URL, it shouldn't be destroyed after the tab close (if using `onclick` event, it will do so).
Using `zombieTimeout` cannot solve this problem, because the function onclick refers to has been destroyed.

**Proposed Solution**

Hope to suppport `url` property. Just like Tampermonkey 5.0.6189 does: https://www.tampermonkey.net/documentation.php#api:GM_notification

**Use Cases**

push news.

我不太会说英语，但是十分感谢开发者们！

**Comment by tophf** [comment]
This is already implemented via `zombieTimeout`, see the [documentation](https://violentmonkey.github.io/api/gm/#gm_notification).

**Comment by tophf** [comment]
Sorry, I have trouble reading.

**Comment by helloworldSB** [comment]
![图片](https://github.com/violentmonkey/violentmonkey/assets/65109494/8f0e0094-cacf-48cf-a7d6-316e6d14b4be)
like this

**Comment by tophf** [comment]
There's no need to repeat.

**Comment by tophf** [comment]
I don't like `event.preventDefault()` mechanism in Tapermonkey. I think we will add `zombieUrl` which will open the URL when clicked after the script is dead, otherwise the `onclick` function will be called, without the need for event.preventDefault().

@gera2ld ?

**Comment by tophf** [comment]
Our implementation is different: you can specify `zombieUrl`, which will be opened only when a "zombie" notification is clicked. If your script is running then you can do whatever you want in `onclick` without the need to call preventDefault. You will also need to specify `zombieTimeout` to force the notification to stay after the script's death.

**Comment by helloworldSB** [comment]
> Our implementation is different: you can specify `zombieUrl`, which will be opened only when a "zombie" notification is clicked. If your script is running then you can do whatever you want in `onclick` without the need to call preventDefault. You will also need to specify `zombieTimeout` to force the notification to stay after the script's death.

Are there any way to stick (make it never be removed) the notification?

**Comment by tophf** [comment]
The maximum is `2 ** 31 - 1` which corresponds to 24 days.

**Comment by helloworldSB** [comment]
> The maximum is `2 ** 31 - 1` which corresponds to 24 days.

That's enough, thanks!!!!!!
