### ISSUE TITLE
[Feature] option to choose if ext icon in toolbar takes to the popup or straight to the dashboard

### ISSUE THREAD

**Issue by G-D-B-9-9** [violentmonkey/violentmonkey#1944]
Straight to dashboard would be great.

Been using Violentmonkey both in a desktop Windows browser and Android mobile browser - prefer that it would go straight to dashboard.

Combine the two views?

These extension managers have many features and options than just on/off toggle. Especially simpleextmanager it can do almost everything from the popup.

https://chrome.google.com/webstore/detail/simpleextmanager/kniehgiejgnnpgojkdhhjbgbllnfkfdk

https://chrome.google.com/webstore/detail/extmanager/bgejgfcdaicmfbfphchgcdgnpnbcondb

https://chrome.google.com/webstore/detail/extentie-extension-manage/bhjkadebkpcekfbjkkmcjhhlfidajfmi

Violentmonkey popup seems like an extra step - many times more than currently running scripts view is needed: 

- access script options (or code)
- turn scripts off
- turn scripts on
- have an overview of all scripts
- test what scripts works and/or gives most desired result
- turn on/off
- uninstall
- get more scripts

At least the popup could be useful - but dashboard gives best result for userscript users - who usually are power users

**Comment by tophf** [comment]
Out of 10+ millions of users of Tampermonkey+Violentmonkey this feature would be helpful only to a small percentage of users, AFAICT, however we can add such an option because it's easy to implement.

**Comment by tophf** [comment]
On the other hand, even thuogh implementation is trivial, I'm not sure this is a good idea because it'd be impossible to show script's menu created via GM_registerMenuCommand. We'll also have to find a good UI method of showing just the matching scripts for this tab, otherwise this would be a niche feature for people with just a couple of scripts, which isn't exactly the power user scenario.

@gera2ld?

**Comment by tophf** [comment]
> turn scripts off
> turn scripts on
> turn on/off
> uninstall

These are already possible from the popup.

> test what scripts works and/or gives most desired result

This is only possible inside the web page and doesn't depend on whether the popup or dashboard is used.

> access script options (or code)

This opens an editor anyway. I'm using the option to open a simple popup editor, so I don't need dashboard for this.

> have an overview of all scripts

And why would I want to see hundreds of scripts every time I open the popup? It's a rare need.

**Comment by gera2ld** [comment]
I think the popup is important for users and we have provided enough features there.
Also you can open the code editor directly from the popup so there is no additional click compared to the dashboard. I don't see any benefit from opening the dashboard directly.
Besides, I personally don't like unexpected new pages from an extension which would break my flow. So I suggest not to change the existing behavior.

**Comment by G-D-B-9-9** [comment]
The popup is informal of course.

Maybe the issue is more that clicks and links opens a new tab.

From the popup it's understandable but from dashboard onwards not so much.

Let user decide. 

And maybe clean those links? "Get more scripts" to a page that's hardly working, some of the userjs sites not updated "in years" - to use search engine(s) that shows ~ google site results 10 per page with bad to nonexistent results arranging. Now you have 7 new tabs open - from the dashboard - and your still not at git/github searching or greasyfork searching. Prune it.

Anyhow - I like Violentmonkey a lot. It's the best browser addon for userscripts.

Is it MV3 already? Great time to do enhancements here and there.

**Comment by G-D-B-9-9** [comment]
@tophf @gera2ld 

Check this guy's popup extension and userscript manager.
https://chrome.google.com/webstore/detail/nooboss/aajodjghehmlpahhboidcpfjcncmcklf

- full text title doesn't have to show in the popup, just the name
- arrange the popup in list or grid

Websites aren't that static anymore. There's almost a constant upkeep on changes. Most scripts are give and take. Turning on off and finding best combination. Leave as off or uninstall? People have all kinds of adblockers and privacy addons and what not addons and userscripts on top plus 50 tabs open to same or different sites. It's handy to turn extensions on and off group them by sites depending on the workspace and same with userscripts. So that the addons don't bloat resources cost effectively.

But to tell the truth extensions community is better arranged and organized. Yet sites are becoming evermore complex there's more and more demand for userscripts.

Maybe there should be semi centralized distribution "store" site that's clean, modern, easy and engages users but creators too 🤔👏

**Comment by tophf** [comment]
I don't understand what you are talking about, it doesn't seem related to Violentmonkey and the way it's used. The screenshot in the link seems to exhibit the same functions we already provide in the popup.
