### ISSUE TITLE
[Feature] Grouped ON/OFF for userscripts

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1951]
**Motivation**

* I have many scripts used in a website. I want to enable & disable some scripts to test my script. but i have to on/off them one by one
* Want to disable most scripts but not all in visiting banking sites.

**Proposed Solution**

Add grouping so that scripts can be assigned to different groups. I can on/off the groups to enable/disable multiple scripts without clicking one by one

for example, i have three groups, "always on", "sometimes off", and "experimental"
so i can on/off the experimental group to test something new.
when i go to banking site, i can off sometimes off and experimental, or even with always on. So that I can just off three stuff to get a clean browser to use my banking service. (might be i keep some important scripts to be ON, which is the difference with totally OFF violentmonkey)

**Use Cases**

* Developers' testing
* General users who are interested in script testing / compatibility checking
* General users who want to disable most scripts but not all in visiting banking sites.

**Comment by tophf** [comment]
#287
