### ISSUE TITLE
[Feature] Enable/Disable button is missing inside code editor

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1953]
**Motivation**

When I use code editor to make the script, i would like to have a button / checkbox in the code editor to enable it or disable it for testing.
currently I have to go back to the main setting page or other way to find the enable/disable button.

**Proposed Solution**

add a button / checkbox inside code editor

**Use Cases**

**Comment by tophf** [comment]
We can add `[x] Enabled` in the Settings tab.
