### ISSUE TITLE
[BUG] Unable install userscript due to loading icon resource (very slow server)

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1956]
https://update.greasyfork.org/scripts/469522/%F0%9F%8F%86%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E4%B9%9D%E4%B9%9D%E5%8A%A9%E6%89%8B%7C%E7%BB%A7%E7%BB%AD%E6%95%99%E8%82%B2%7C%E5%AD%A6%E9%93%B6%E5%9C%A8%E7%BA%BF%7C%E5%9B%BE%E7%89%87%E9%A2%98%7C%E8%80%83%E8%AF%95%7C%E5%90%8E%E5%8F%B0%E8%87%AA%E5%8A%A8%E6%8C%82%E6%9C%BA%7C%E8%A7%86%E9%A2%91%E6%96%87%E6%A1%A3%7C%E7%AB%A0%E8%8A%82%E6%B5%8B%E9%AA%8C%7C%E4%B8%8D%E5%8D%A0%E7%BD%91%E9%80%9F%F0%9F%8F%86.user.js

Tampermonkey can install it.

Violentmonkey can see the content. But after installation, cannot enter its code editor UI.
(including the case that Install + Edit option. just no response)
it will show the loading symbol.
close the tab and reopen the extension setting page, the script will disappear.

**Comment by tophf** [comment]
Works for me.

**Comment by cyfung1031** [comment]
v2.16.0

tested on Chrome, Brave, and Firefox. Same issue.

**Comment by tophf** [comment]
Must be a network issue on  your side. Try pasting the code of the script in a new editor and save it and you'll see its code is actually parsed correctly.

**Comment by cyfung1031** [comment]
> Must be a network issue on your side. Try pasting the code of the script in a new editor and save it and you'll see its code is actually parsed correctly.

Yes. It resolved. Now the icon url is working so it can install normally.

But the network loading of the icon resource should not affect the installation and editing.

**Comment by tophf** [comment]
I can install the script regardless of the icon's availability. I can't reproduce the problem.

**Comment by tophf** [comment]
The closest I can get to the problem is by using `https://hub.dummyapis.com/delay?seconds=10`, so I can fix the issues caused by a super slow server.
