### ISSUE TITLE
All user scripts disappeared (Firefox + ViolentMonkey)

### ISSUE THREAD

**Issue by AleksG3** [violentmonkey/violentmonkey#1957]
Today, when I launched the Firefox browser and went into ViolentMonkey, I was just killed, there is not a single script, everything is just clean there. I'm asking for help on how to get my custom scripts back

**Comment by AleksG3** [comment]
I use Firefox Portable

**Comment by tophf** [comment]
If you have a backup then you can restore it, otherwise there's no magic solution, but you can try finding some tutorials on restoring lost files in Firefox profile.

**Comment by AleksG3** [comment]
Which is not even interesting as such or because of what it could happen, I understand that obviously this is an ordinary thing when scripts simply dissolve from Violentmonkey in Firefox Portable

**Comment by tophf** [comment]
No, it doesn't happen normally, so I guess it's caused by a crash or a bug in the browser.
