### ISSUE TITLE
[BUG] script disabled due to syntax error on very specific pages, but editor finds not syntax error

### ISSUE THREAD

**Issue by yamada321** [violentmonkey/violentmonkey#1958]
### Sequence of actions: 
1. install script ([own script](https://greasyfork.org/en/scripts/475538-imm-trans)). 
2. open new tab, goes to the webpage in question (see below)

### Problem: 

After the two steps, script is marked as disabled due to "syntax error?". 

However, there is no error in violentmonkey's editor view, and doing 2 on the same domain but a different url suffix will work without issues. 

If I land on the url that does not trigger the syntax error, and go the url by clicking on a hyperlink or `window.location.replace()` in console, the script will run normally on the problematic page. But, if I add another userscript in violentmonkey to automate this workaround, the workaround fails (i.e. disabled-by-syntax error appears again).

The site is a fediverse instance (pleroma) with pleroma-fe as front end. The problematic page is my home timeline, or any user profile page that exists. The page that works is a non-existent user profile page. I note that I can't reproduce this on another pleroma instance that runs the same front end (albeit probably different versions and setups).

### Expected result:  

Works on both pages.

#### Devtools console contents:

Here is console output when I land directly on the problematic page ([for example this url](https://vnil.de/users/pi)):

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:42:9

Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:401

Cyclic depenency in topoSort, ignoring 2 theme_data.service.js:120:14

Both sources have valid data, figuring things out... serverSideStorage.js:94:12

Same version/timestamp on both source, source of truth irrelevant serverSideStorage.js:96:14

Checking if data needs merging... serverSideStorage.js:310:14

Data doesn't need merging serverSideStorage.js:315:14

false serverSideStorage.js:422:14

Cookie “userLanguage” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite js.cookie.mjs:75:48

Can't load stickers after_store.js:222:12

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data after_store.js:223:12
​
```

And here is console output when I land directly on the page where my userscript works (for example [this url](https://vnil.de/users/xxxxxxxx)):

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:42:9

Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:401

Cyclic depenency in topoSort, ignoring 2 theme_data.service.js:120:14

Both sources have valid data, figuring things out... serverSideStorage.js:94:12

Same version/timestamp on both source, source of truth irrelevant serverSideStorage.js:96:14

Checking if data needs merging... serverSideStorage.js:310:14

Data doesn't need merging serverSideStorage.js:315:14

false serverSideStorage.js:422:14

Cookie “userLanguage” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite js.cookie.mjs:75:48

XHRGET https://vnil.de/api/v1/accounts/lookup?acct=xxxxxxxx [HTTP/2 404  528ms]

Can't load stickers after_store.js:222:12

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data after_store.js:223:12

XHRGET https://vnil.de/api/v1/accounts/xxxxxxxx [HTTP/2 404  413ms]
```

#### Environment:
- OS: arch linux
- Browser: firefox 120.0b8 (64-bit) developer edition
- Violentmonkey Version: 2.16.0

Thank you for your time.

**Comment by tophf** [comment]
> script is marked as disabled due to "syntax error?"

Can't see it here, your script always works on both pages for me.
The errors in console.log aren't related.

**Comment by yamada321** [comment]
> Reloading the extension in the extension dev tools fixes the issue for some reason, but sometimes then other pages break. (#1949)

This suggestion accidentally worked for me too, but not via dev tools reload. 

I was testing in private window (somehow forgot to do so yesterday). I set violentmonkey to be allowed in private window, and opened a problematic page. It worked. And when I go back to the regular environment thinking to disable other plugins one by one, the problem reported in this issue of mine is gone.
