### ISSUE TITLE
[Feature] New *Reload tab* feature be local to script being tracked

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/violentmonkey#1959]
Userscript manager: Violentmonkey 2.16.0
  injected into "content"
Platform: firefox 119.0.1 linux x86-64

**Motivation**
I was surprised when I turned on automatic tab reloading on one page, and a different page (that was also tracking), reloaded as well.

**Proposed Solution**
Enabling *Reload tab* should be local to the script being tracked, not all scripts being tracked.

**Use Cases**
I was working on a library shared by two userscripts.  One for a real website, and another for a dummy site served up from localhost.  The local site has a nearly instant reload time as it is just a static page used for testing stuff; the real site takes several seconds to reload, and I have received requests from them to not reload quite so often.

Saving the library results in both userscripts being rebuilt.

What I want to have happen is the local site page reload automatically, then when I am satisfied with my change, try it on real site with a manual load.

Right now I have to remember to close the tab with VM tracking the script for the real site, then reopen it when I'm ready to test there.

**Comment by tophf** [comment]
All options are global. Changing this behavior may be an enhancement for your scenario, but on the other hand it means the option won't be auto-saved and everyone will need to re-enable it every time. A possible solution might be to add yet another option below like `[ ] only for this script`.

**Comment by tophf** [comment]
BTW you can stop tracking instead of closing the tab.

**Comment by nexushoratio** [comment]
> BTW you can stop tracking instead of closing the tab.

I discovered that shortly after posting my FR.  :->
