### ISSUE TITLE
Malwarebytes is blocking violentmonkey.top

### ISSUE THREAD

**Issue by SW1FT** [violentmonkey/violentmonkey#196]
### What is the problem?
Malwarebytes is blocking violentmonkey.top

### How to reproduce it?
1. Download [Malwarebytes](malwarebytes.com)
2. Enable Web Protection in Malwarebytes
3. Check for updates in Firefox's add-on manager
4. Notice that violentmonkey.top gets blocked

### What is the expected result?
violentmonkey.top should not be blocked by Malwarebytes and any future update should be downloaded.

### What is the actual result?
violentmonkey.top gets blocked by Malwarebytes and any future update won't be downloaded.

### Environment
- Browser: Firefox (Nightly)
- Browser version: 57.0a1
- Violentmonkey version: 2.8.7
- OS: Windows 10

**Comment by gera2ld** [comment]
Is there a reason?

**Comment by SW1FT** [comment]
No idea, here's some more details:
IP: 138.128.208.212
Type: Outbound

Maybe they already had this IP blocked for some other reason?

**Comment by ghajini** [comment]
Nothing but a false positive (a feature of malwarebytes),their real time protection just bad.....

Report here

https://forums.malwarebytes.com/forum/123-website-blocking/

**Comment by gera2ld** [comment]
It's funny, [all `.top` domains are blocked](https://forums.malwarebytes.com/topic/209943-top-domain-blocked/).

**Comment by gera2ld** [comment]
Closing since you don't need to visit `violentmonkey.top` any more.
