### ISSUE TITLE
[BUG] "Syntax error?" - userscript disabled - enabled after restarting browser

### ISSUE THREAD

**Issue by zbluebugz** [violentmonkey/violentmonkey#1960]
### Sequence of actions: 
1. Install userscript (https://greasyfork.org/en/scripts/431970-fb-clean-my-feeds)
2. Visit Facebook - script runs Ok
3. Introduce an error in userscript (e.g. "nnnn;")
4. Reload FB - userscript is not running
5. Remove the error from the userscript
6. Reload FB - userscript is not running

To resolve: restart browser

### Problem: 
Userscript is not running after fix is applied to code
Deleting and installing another copy of the userscript does not fix the issue
No error is listed in devtools console

### Expected result:  
Expected userscript to be enabled after fix is applied
Expected userscript to be running after being deleted and reinstalled

#### Devtools console contents:
n/a

#### Environment:
- OS: Windows
- Browser: Firefox 115.4.0esr (64-bit)
- Violentmonkey Version: 2.16.0

Resolution found: Restart the browser (a bit kludgy when trying to debug the code)

**Comment by tophf** [comment]
Until the bug is fixed the workaround is to disable `Alternative page mode` in Violentmonkey settings, then disable and enable Violentmonkey.
