### ISSUE TITLE
[BUG] Script options looping 

### ISSUE THREAD

**Issue by joshgrosz** [violentmonkey/violentmonkey#1963]
### Sequence of actions: 
1. Install userscript from https://github.com/LibreScore/dl-librescore/releases/latest/download/dl-librescore.user.js 
2. Open Musescore score to download pdf/midi/mp3 of score
3. Click on Violentmonkey menu to select download

### Problem: 
On both Chrome and Firefox, using ViolentMonkey results in a list of the same options several scrolls in length as opposed to Tampermonkey. Despite this the options retain their function (downloading the assets) contrary to the mountain of errors in the devtool panel related to them.
![tampermonkey_bug](https://github.com/violentmonkey/violentmonkey/assets/133725829/fe74ee46-ba45-4ba1-b72c-961dffa7226a)

### Expected result (Using Tampermonkey 4.19.0):  
![Screenshot 2023-11-24 204425](https://github.com/violentmonkey/violentmonkey/assets/133725829/ee75ca9e-6b8e-4e8c-bcab-804a74c2302b)

#### Devtools console contents:
![userscriptdevtools](https://github.com/violentmonkey/violentmonkey/assets/133725829/6409777d-8486-4ecb-9e65-63c6d701ce01)

I'm not super well-versed in web scraping nor JS in general, so please let me know if any additional information would help.

#### Environment:
- OS: Windows
- Browser: Firefox 120.0, Chrome 119.0.6045.160
- Violentmonkey Version: 2.16.0

**Comment by tophf** [comment]
I can't reproduce the problem. It may be specific to the URL which you didn't provide or there may be some other pre-condition.

**Comment by tophf** [comment]
Ah, I needed to visit two different pages in that site.
