### ISSUE TITLE
[Request]  Please if the developer can. Support mv2 until the summer of 2025 [2025H2]

### ISSUE THREAD

**Issue by rtx2080tix** [violentmonkey/violentmonkey#1965]
Just like what the title says
And in the extension is removed from Chrome Web Store
You can just publish the release on **GitHub** so that users who want powerful and reliable can use powerful and reliable extension 

mv2 is **always more useful and powerful and reliable** than mv3
you can enable mv2 in 2024 using [ExtensionManifestV2Availability](https://chromeenterprise.google/policies/#ExtensionManifestV2Availability)
windows registry example

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave]
"ExtensionManifestV2Availability"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium]
"ExtensionManifestV2Availability"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExtensionManifestV2Availability"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ExtensionManifestV2Availability"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Vivaldi]
"ExtensionManifestV2Availability"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\YandexBrowser]
"ExtensionManifestV2Availability"=dword:00000002


```
and linux user are nerd enough to apply the policy to any chromium based browser

And yes I know the policy is just a one-year delay
but I refused to use mv3 with useful and powerful extensions

and the developer can follow the lead of uBlock Origin
where there is a **weak mv3 version** ublock origin lite but **there is still the powerful mv2 version**
and it will be supported until **mv2 code is 100% removed from chromium source code**

**Comment by tophf** [comment]
Yeah, that's the plan, at least until MV3 becomes less broken.

**Comment by rtx2080tix** [comment]
@tophf 

Wait so **IF** mv3 become less broken by 2024 you will stop supporting mv2

**Comment by tophf** [comment]
Well, personally, I doubt that happens before 2200...

**Comment by rtx2080tix** [comment]
Good to know thank for your fast response
