### ISSUE TITLE
[Feature] Open extensions on Firefox for Android debut December 14

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#1966]
**Motivation**

Apparently extensions (add-ons) are back on **Firefox for Android** this December.

**Proposed Solution**

https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/ contains links to informations on how to be part of the Android supported extensions.

**Comment by tophf** [comment]
It's already compatible.

**Comment by jesus2099** [comment]
I didn't see it in [AMO’s Android page](https://addons.mozilla.org/android/). Did you? 🤔

**Comment by tophf** [comment]
They pick extensions based on undisclosed decisions. Compatibility doesn't equate inclusion.

**Comment by jesus2099** [comment]
But maybe this post includes how to be included.
Maybe you need to connect them as a step to be included? 🤔
I didn't read all the links.

**Comment by tophf** [comment]
No, there's no such method. The article only says how to ensure the extension is compatible and offers help to do so.

**Comment by jesus2099** [comment]
OK, strange ...

**Comment by tophf** [comment]
As suggested elsewhere, I've marked it compatible in AMO:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/e9879678-ecd7-4161-9020-9cea09153b8e)

@gera2ld, can you add it to amo-upload?

**Comment by gera2ld** [comment]
@tophf sorry, add what to amo-upload?
