### ISSUE TITLE
[Feature] Access to local port

### ISSUE THREAD

**Issue by atbsi** [violentmonkey/violentmonkey#1972]
I have a script to access the local port (127.0.0.1:xxxx), and at https://www.flickr.com/explore the page is restricted from accessing it properly, even if tampermonkey is turned on with the CSP option for tampering with the page. But in Greasemonkey-4, it can be accessed normally without any settings.

May I ask how violentmonkey has to be modified to achieve the same effect as Greasemonkey?

**Comment by tophf** [comment]
Try adding `@inject-into content` to your script, see https://violentmonkey.github.io/posts/inject-into-context/

**Comment by atbsi** [comment]
Thank you, very useful, scripts are not limited anymore, the
