### ISSUE TITLE
[BUG] [Orion] No UserScript Execution inside iframe under YouTube domain

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1975]
### Reproduction Steps
1. Create the script for testing

```js
// ==UserScript==
// @name            Script-VM300
// @namespace       Test.org
// @description     A test
// @author          tester
// @version         0.0.1
// @grant           none
// @match           https://*/*
// ==/UserScript==


const tag = `vm300${(Math.floor(Math.random()*300+110)+ (window.top !== window ? 500 : 0))}`;
console.log(tag, location.href)

if(window.top === window){
  setTimeout(()=>{
    console.log(`${tag}-iframe`);
    document.body.appendChild(document.createElement('iframe')).src=`https://google.com/robots.txt`;
  },800)
}
```

2. Go to any page of https://example.com, https://google.com, https://www.youtube.com, https://duckduckgo.com, https://kahoot.it

3. Expected Result
<img width="1171" alt="Screen Shot 2023-12-04 at 20 09 59" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/31f21918-fc02-416e-9d54-f76f55c2f1d9">

4. Go to any page of https://www.youtube.com, https://m.youtube.com

5. Incorrect Console Log - Indicating no execution inside iframe

<img width="1171" alt="Screen Shot 2023-12-04 at 20 10 54" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/88dde22e-bdf1-4b95-b3a5-2288cdace02b">

#### Environment:
- OS: macOS M1 Pro
- Browser: Orion Version 0.99.126.3-beta (WebKit 618.1.2)
- Violentmonkey Version: latest CI build

## Remarks

* Same result for `@inject-into content` and `@inject-into page`
* Same result for `@sandbox raw` and `@sandbox JavaScript`

## Orion

https://orionfeedback.org/d/6749-orion-violentmonkey-userscript-execution-failure-inside-iframe-under-youtube-domain

**Comment by tophf** [comment]
It's unclear why you think it's an issue with Violentmonkey and not Orion. Anyway, we can't test it, so I don't think it makes sense to report these problems here.

**Comment by cyfung1031** [comment]
Confirmed the same bug exists in MeddleMonkey. 
Reported in Orion: https://orionfeedback.org/d/6749-orion-violentmonkey-userscript-execution-failure-inside-iframe-under-youtube-domain

**Comment by cyfung1031** [comment]
The bug is fixed by Orion. Confirm the issue is gone with latest Orion and Violentmonkey BETA.
