### ISSUE TITLE
[BUG] @require relative paths seem to be broken

### ISSUE THREAD

**Issue by riley-martine** [violentmonkey/violentmonkey#1979]
### Sequence of actions: 
1. Install this userscript: https://raw.github.com/murdos/musicbrainz-userscripts/master/bandcamp_importer.user.js
2. View require tab in violentmonkey settings for the script, check on any `lib/` files
3. See that it's a JSON response from GitHub and not the actual file
4. Replace relative import with full path (prepend `https://raw.github.com/murdos/musicbrainz-userscripts/master/`)
5. See that the import works now

I've seen this before where an `accept` header was accidentally set to (or defaulted to) `application/json`, but I'm not confident that this is the issue.

### Problem: 

`[Violentmonkey][Import Bandcamp releases to MusicBrainz] SyntaxError: unexpected token: ':'`

### Expected result:  

Loading the lib file successfully.

#### Devtools console contents:

Should not be needed, I think I figured out the error.

#### Environment:
- OS: macOS
- Browser: Firefox 120.0.1
- Violentmonkey Version: v2.16.0

See also: https://github.com/murdos/musicbrainz-userscripts/issues/524

**Comment by tophf** [comment]
> See that it's a JSON response from GitHub and not the actual file

I see the actual file...

**Comment by StaticRocket** [comment]
I was able to reproduce this. Not sure if its a combination of extensions causing the issue here or what. Further debug required.

**Comment by tophf** [comment]
Well, someone else will have to debug it because I can't reproduce the problem. Reading the source code I see no way it can happen, although I may have mistaken of course, but so far my guess is a corruption of the internal database. Try removing the script and install it again.

**Comment by StaticRocket** [comment]
I tried that first, no dice. Let me setup a simpler test today and see if I can narrow it down.

**Comment by StaticRocket** [comment]
Well, I created a new blank profile and only installed ViolentMonkey and the Bandcamp importer script and it was able to reproduce the issue. This was on Firefox 120.0.1 (64-bit) as well.

The injector script is minified, is there any slick tricks I can use for debug that can make it easier to track down this error? (I'm no web dev unfortunately.)

**Comment by StaticRocket** [comment]
It may be worth noting that when attempting to use the update command in the ViolentMonkey interface for the userscript the following error is reported:

`Error fetching resource!` 
```
TypeError: a.depsMap is undefined
TypeError: a.depsMap is undefined
TypeError: a.depsMap is undefined
TypeError: a.depsMap is undefined
```

**Comment by tophf** [comment]
I can't reproduce the problem using the sequence in the description, so maybe there's an additional step missing? I also can't reproduce the `depsMap` error, but judging by the source code it's unrelated to installation/update.

**Comment by tophf** [comment]
To debug the problem you'll need `about:debugging` -> `This Firefox` -> `Inspect` for Violentmonkey.

**Comment by tophf** [comment]
Here's a non-minified dev build of 2.16.2: [zip](https://github.com/violentmonkey/violentmonkey/files/13693385/dev.zip)

**Comment by StaticRocket** [comment]
Alright, scanning through the logs it seems that the script itself is being pulled from raw.github.com but the relative imports are using github.com directly and receiving a different response with a json payload...

**Comment by tophf** [comment]
Here all requests are raw.github.com.

**Comment by StaticRocket** [comment]
Well that seems to be the issue then. It's passing the raw JSON payload and dying because it really is a syntax error:

![image](https://github.com/violentmonkey/violentmonkey/assets/35777938/7aad5108-6855-4340-acdd-4717187e1434)
![image](https://github.com/violentmonkey/violentmonkey/assets/35777938/3b4e7670-b9b7-404a-9528-80d49ff89f99)

**Comment by tophf** [comment]
Yeah, that much I knew all along, but I don't know is how that is even possible as I don't see any way that can happen in the source code.

**Comment by tophf** [comment]
For all I know it may be a bug in github or in Firefox, which depends on some unknown condition...

**Comment by StaticRocket** [comment]
It's weird that it's changing so much of the URL. It's not just dropping the subdomain or anything simple like that, it's completely changing it:

expected:
```
https://raw.github.com/murdos/musicbrainz-userscripts/master/lib/mbimport.js
```

logs:
```
https://github.com/murdos/musicbrainz-userscripts/blob/master/lib/mbimport.js
```

And no 302 or anything so it's not Github redirecting traffic...

**Comment by tophf** [comment]
Violentmonkey doesn't do such things.

**Comment by StaticRocket** [comment]
Forgive my ignorance but how does Violentmonkey handle relative imports? Is it relying on some external library or is it some built in function of the browsers JS interpreter?

**Comment by tophf** [comment]
We use the standard `URL` constructor with the last installation URL as the base.

**Comment by StaticRocket** [comment]
Oh, well that explains it. The actual install url is this:

```
https://github.com/murdos/musicbrainz-userscripts/blob/master/bandcamp_importer.user.js?raw=1
```

**Comment by tophf** [comment]
Where/how do you get this link?

**Comment by StaticRocket** [comment]
From the MusicBrainz wiki

https://wiki.musicbrainz.org/Guides/Userscripts

**Comment by tophf** [comment]
I see. So it looks like the fix in Violentmonkey would be to preserve the original `?` parameters.

**Comment by StaticRocket** [comment]
For Github at least.

I suppose this is a classic case of User Error ™ sorry for the wild goose chase

**Comment by StaticRocket** [comment]
I updated their wiki so nobody else will fall into that trap in the meantime.

**Comment by tophf** [comment]
Tampermonkey uses XMLHttpRequest, we use `fetch`. The only difference per devtools network monitor is that the former is an unconditional request without If-None-Match header, but the presence of this header in our request changes the type of response from the actual contents to json, which is a violation of the specification, so apparently it's a github bug...

**Comment by tophf** [comment]
Ah, no, Tampermonkey uses a different URL with `raw` instead of `blob` so maybe it explicitly patches this bug in github...

**Comment by tophf** [comment]
Damn, it was a bug in Violentmonkey introduced in v2.13.1.4 via a6f8e61c where I incorrectly converted one regexp.
