### ISSUE TITLE
Is there any official store link for Firefox's Violentmonkey BETA?

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1986]
#### Chrome
* Violentmonkey (Stable): https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag
* Violentmonkey BETA: https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg

#### Firefox
* Violentmonkey (Stable): https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
* Violentmonkey BETA: ??????????????????????????????

**Comment by tophf** [comment]
AMO doesn't allow beta versions in the list anymore, so the only place is our [releases](https://github.com/violentmonkey/violentmonkey/releases).
