### ISSUE TITLE
[BUG] Cannot close tabs

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [violentmonkey/violentmonkey#1987]
### Sequence of actions: 
1. Make userscript that invokes `closeTab();` or `window.close();` on some event
2. Do the event action; registered in console
3. Tab doesn't close; security blocks it.

### Problem: 

I can't seem to find a way to let a userscript close the current tab. I want the tab to close on a simple keypress. This action is registered, but the Console output as shown below suggests it can't due to security. I was hoping there is something like the `@grant GM_OpenInTab` argument but for closing a tab, but as far as I can tell in the Violentmonkey documentation, there isn't. 

Am I missing something? Is there no way to grant permission to the script manager to close the current tab? 

Various Chrome extensions can do this, so I presume it must be possible somehow. Thank you. 

### Expected result:  

Expect tab to close

#### Devtools console contents:

> CloseTab-testuserscript (except in inputs).user.js:16 Scripts may close only the windows that were opened by them.

#### Environment:
- OS: macOS
- Browser: Brave 1.6 
- Violentmonkey Version: 2.16

**Comment by tophf** [comment]
You need to add `// @grant window.close`

**Comment by TS6ix2GaH3q679h5** [comment]
Ah my apologies. That was it. Thank you.
