### ISSUE TITLE
[BUG] Very High CPU Usage

### ISSUE THREAD

**Issue by AlifianK** [violentmonkey/violentmonkey#1989]
I'm using [this script](https://github.com/TuxedoTako/4chan-xt) on Edge with the JSON Index feature.
![image](https://github.com/violentmonkey/violentmonkey/assets/50392169/fa1a4ada-26db-4fd0-9f3d-c3319d8c17ec)
Most boards are fine, but some boards are affected. For example, from what I tested, on /vg/ it's 30 seconds, but the worst affected board is /vt/ with up to 2 minutes of high CPU usage, rendering the tab hanging until the CPU usage settles down.

Firefox works fine. Also tested on Tampermonkey on both browser, works fine too.
### Sequence of actions: 
1. Open [this link](https://github.com/TuxedoTako/4chan-xt/releases/download/XT2.3.2/4chan-XT.user.js) to install the script.
2. Use the Index JSON feature.
3. Open the affected boards, /vg/ or /vt/.
4. Use the catalog (The XT catalog, not the native one)

#### Devtools console contents:
```
vt/:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
4chan XT.user.js:21252 [Violation] 'loadend' handler took 863ms
[Violation] Forced reflow while executing JavaScript took 162ms

```

#### Environment:
- OS: Windows 11
- Browser: Edge 120.0.2210.91
- Violentmonkey Version: 2.16.0

**Comment by tophf** [comment]
I can't reproduce the problem.

Assuming you can reproduce it using this exact sequence of steps in a new browser profile with default settings and only Violentmonkey installed, the only way forward here is for you to debug it in devtools -> Performance panel.

**Comment by AlifianK** [comment]
[Here's the recorded profile](https://github.com/violentmonkey/violentmonkey/files/13779040/trace.json.zip)
Will update if I can reproduce this on a new browser profile.

**Comment by AlifianK** [comment]
[Here's the trace](https://gofile.io/d/HS9JJS) with a new browser profile, touched nothing but installed violentmonkey and the script.

**Comment by tophf** [comment]
The trace shows ~4 seconds of CPU activity during which the script creates a lot of elements in the page. I see the same here. Afterwards the tab constantly consumes 5% CPU to draw the snowflakes.

**Comment by AlifianK** [comment]
Hmmm, I will try with a fresh Chrome install.

**Comment by tophf** [comment]
I see that Violentmonkey extension process is spiking over 100% CPU for a few seconds.
You can try the fix in [CI builds](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml).

**Comment by AlifianK** [comment]
That fixed the problem, thank you!
