### ISSUE TITLE
[Feature] Shortcut Key for Close button in editor

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1990]
**Motivation**

I want to close the editor using keyboard to go back to the main setting/option page

**Proposed Solution**

use VM.shortcut to register a shortcut key like ctrl-W to close the editor and back to the main setting page

**Use Cases**

code editing

**Comment by gera2ld** [comment]
Did you try <kbd>Esc</kbd>?

**Comment by cyfung1031** [comment]
> Did you try Esc?

Can we have some hints for the button like "Close (Esc)"
I don't know Esc can exit the editor.

**Comment by tophf** [comment]
We can add a hover tooltip.

**Comment by tophf** [comment]
Or maybe add it to the list of hotkeys shown in `?` tab in the editor. Currently it says `Esc: cancel`, which is too vague. We can show something like this at the beginning of the list:

<table><tr><td><b>Esc</b></td><td>

Cancel or go back:
* go back to code from other tabs or the find panel
* go back to script list if code is already active
* close the value data editor
* cancel multiple selections

</td></tr></table>
