### ISSUE TITLE
[BUG] Ui width

### ISSUE THREAD

**Issue by raingart** [violentmonkey/violentmonkey#1997]
incorrect text formating for scripts with large authors names 

![Screenshot_3](https://github.com/violentmonkey/violentmonkey/assets/13064767/5152e745-7c52-489a-8cd7-3547b2ff9ced)

![Screenshot_4](https://github.com/violentmonkey/violentmonkey/assets/13064767/e86b8050-15a0-4ade-8c2d-193a75a12297)

**Comment by tophf** [comment]
Fixed it yesterday in 2f07c1c3. 

Until a new version is published you can add the following code to `Custom CSS` in settings -> advanced:

```css
.script-info { overflow: hidden; }
```
