### ISSUE TITLE
[Feature] Subresource Integrity (SRI)

### ISSUE THREAD

**Issue by andrewsuzuki** [violentmonkey/violentmonkey#1998]
**Motivation**
From MDN:
> Subresource Integrity (SRI) is a security feature that enables browsers to verify that resources they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched resource must match.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Proposed Solution**
Allow supplying a similar `integrity` string to `@require`/`@resource`.

Tampermonkey uses a URL fragment (e.g. `jquery-2.1.1.min.js#sha-512=23fd34...`). I don't particularly like this solution because some resources might need the fragment themselves. Something like this might be cleaner: `jquery-2.1.1.min.js integrity:sha512-23fd34...` (`integrity:` followed by the same format that `<script />` uses).

Can use SubtleCrypto [digest()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) to generate hashes (supports `SHA-1`, `SHA-256`, `SHA-384`, `SHA-512`).

**Comment by tophf** [comment]
#1558
