### ISSUE TITLE
[BUG] Homepage is shown using namespace value

### ISSUE THREAD

**Issue by mperry2** [violentmonkey/violentmonkey#2001]
### Sequence of actions: 
1. Create a userscript with the following content

```
// ==UserScript==
// @name        New script
// @namespace   https://www.example.org
// @match       *://example.org/*
// @grant       none
// @version     1.0
// @author      -
// @description 1/9/2024, 11:03:20 PM
// ==/UserScript==
```

2. Go to the script index page.
3. Check homepage button for the userscript created above.

### Problem: 
The home page button is active and links to `https://www.example.org`

### Expected result:  
The homepage icon should be inactive and greyed out because there isn't an `@homepageURL` field in the userscript. `@namespace` should never be used as the homepage value regardless of its contents. If a home page must be specified then it should be done so using `@homepageURL`.

#### Environment:
- OS: Windows 10
- Browser: Firefox 121.0.1 (64-bit)
- Violentmonkey Version: BETA v2.17.1

**Comment by tophf** [comment]
It's the intended behavior, we infer the homepage URL from the installation URL and `@namespace` which may be used to identify the author, so I don't agree with your opinion unless you can convincingly substantiate it.
