### ISSUE TITLE
[BUG] Styles in ShadowDOM can be wiped by CSP

### ISSUE THREAD

**Issue by 7nik** [violentmonkey/violentmonkey#2002]
In Firefox, CSP can completely wipe all styles in ShadowDOM. In Chromium, the `style` attribute and `<style>` seem to be ignored.

### Sequence of actions: 
1. Install the following userscript:
```js
// ==UserScript==
// @name        Test adoptedStyleSheets
// @match       https://pawoo.net/about
// @grant       GM_addElement
// ==/UserScript==

const container = document.createElement("div");
container.style.position = "fixed";
container.style.top = 0;
container.style.zIndex = 1000;
document.body.append(container);
const shadow = container.attachShadow({ mode: "open" });

shadow.innerHTML = "<div style='min-width: 50px; min-height: 50px; border: 5px solid blue;'>text</div>";

const sheet = new CSSStyleSheet();
sheet.replaceSync("*{ width: 100px; height: 100px; background: red; }");
shadow.adoptedStyleSheets = [sheet];

const style = GM_addElement(shadow, "style");
style.textContent = "*{ opacity: 0.5; background: green; }";
```
2. open https://pawoo.net/about

### Problem:
In Firefox, no styles are applied at all; in Chromium, only `adoptedStyleSheets` is applied.

### Expected result: 
A consistent way to add styles to ShadowDOM in all browsers.
In TM, only `adoptedStyleSheets` works, but in both browsers.

#### Environment:
- OS: Manjaro 
- Browser: Chromium 120.0.6099.199 (Official Build) Arch Linux (64-bit), Firefox 121.0
- Violentmonkey Version: v2.17.0

**Comment by tophf** [comment]
To use GM_addElement correctly you need to pass `textContent` and the attributes:

```js
GM_addElement(shadow,  "div", {
  style: 'min-width: 50px; min-height: 50px; border: 5px solid blue;',
  textContent: "text",
});

const style = GM_addElement(shadow, "style", {
  textContent: "*{ opacity: 0.5; background: green; }",
});
```
