### ISSUE TITLE
[BUG] Issues with Violentmonkey on Firefox Post v2.15.6: Unresponsive UI and Script Management Problems

### ISSUE THREAD

**Issue by RedRain77** [violentmonkey/violentmonkey#2005]
Description:
After updating to any version past v2.15.6, Violentmonkey has become largely unusable on Firefox. The extension's popup opens, but interactions within it do not function as expected. For example, clicking to open the settings page does not work; I have to enter the address manually in the address bar. Additionally, creating a new script is not possible.

Each time I update Violentmonkey, it indicates that I have 0 scripts installed. This is a recurring issue as every time I restart Firefox, I need to re-import all my scripts.

When accessing the settings page directly, I can navigate through the options, but cannot perform actions like importing script backups. Attempting to import scripts results in the file name being displayed without any further action.

Sequence of actions:
Update to any version of Violentmonkey past v2.15.6.
Attempt to interact with the extension's UI elements, such as opening the settings page or creating a new script.
Try to import script backups from the settings page.
Problem:
Unresponsive UI elements within the extension's popup.
Inability to create new scripts.
Failure to import script backups; the interface only displays the file name without further action.
Expected result:
Functional UI interactions within the extension's popup.
Ability to create new scripts and manage existing ones.
Successful import of script backups.
Devtools console contents:
[Insert any relevant console logs or error messages here, if available]

Environment:
OS: Windows 10
Browser: Firefox (latest version)
Violentmonkey Version: >v2.15.6

**Comment by tophf** [comment]
Sounds like a broken profile or a bug in Firefox e.g. it doesn't support ImDisk RAM drives and maybe also fails on any NTFS junctions/symlinks.
