### ISSUE TITLE
[Feature] Added a feature/option to disable/enable all installed scripts

### ISSUE THREAD

**Issue by Rusenche** [violentmonkey/violentmonkey#2006]
Guys, thanks for adding the feature I had requested re: https://github.com/violentmonkey/violentmonkey/issues/1995/

Guys I would like you to add one more feature.

It's about adding a `function/option` to `disable/enable` **all installed scripts**. Some extensions have this feature/option which can enable/disable extensions - this is an example of installed browser extensions.

Why am I suggesting the introduction of this feature? A while ago I had to disable all the scripts one by one because I can't disable all the scripts with one click. The goal was to find out which of the installed scripts gave me a defect.

Please consider adding a feature/option to disable/enable all installed scripts.

**Comment by tophf** [comment]
It's already present in the popup:
![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/f1ed3dcc-0393-483f-a911-844d95c55a97)

**Comment by tophf** [comment]
There's also a command to reload the tab without scripts in the `...` menu.

**Comment by tophf** [comment]
Well, now with more info added I see what the actual goal you had in mind, but I don't think we should add a feature for such a rare use case. WDYT, @gera2ld?

**Comment by tophf** [comment]
Since our express goal is to keep the UI simple, what about implementing this feature implicitly: click one toggle then drag over the rest of them vertically without releasing the button to set the new state in one fell swoop? This is how standard apps behave, AFAIK.

**Comment by gera2ld** [comment]
Maybe we should support repeated shortcuts, or a sequence of shortcuts from a string, which seems to be much more flexible.

**Comment by tophf** [comment]
You don't have to convince me, I already understood. I'll try to implement click-n-drag solution and we'll see if it's viable.

**Comment by tophf** [comment]
Actually, a more useful solution is called "bisecting" when you disable just the half of the items, which lets you find the answer in `log2(totalNumberOfScripts)` steps i.e. for 16 enabled scripts it's 4 steps. I wonder if this is possible to implement in a user-friendly fashion? We could add this command to the `...` menu then.

**Comment by gera2ld** [comment]
How about adding a "Batch Action" dropdown button to apply actions to all filtered scripts? So we can support batch toggle on/off, remove, update, etc. We can also add a custom field "tags" to enhance the searching feature, and also partially resolve the grouping feature requested a few times.

TBH I don't like the click-n-drag UX personally.

**Comment by tophf** [comment]
Yeah I thought about adding a `...` menu to the group entry "Matched scripts", but we don't always show it...

**Comment by gera2ld** [comment]
IMHO `bisecting` is too hard to understand and use in a graphic UI. If we have to provide such a geek way, I suggest syncing all the script metadata with a textarea and let the user modify it.

- Show a popup with content like this:
  ```
  # id    enabled     autoupdate     script name
  1        true           false         My awesome script 1
  2        true           false         My awesome script 2
  ```
- user can modify it in any way
- click "Apply" to sync it back

**Comment by gera2ld** [comment]
I see, you are talking about the popup window.

I think we should only implement such advanced features in the dashboard? BTW we could add a filter to filter scripts by whether it matches a URL, so we can easily get "Matched Scripts" in the dashboard.

**Comment by tophf** [comment]
The popup already lists the matching scripts, which is why it makes sense to add this feature to the popup. Filtering by URL in the dashboard is something I added in another extension, so I agree it's occasionally convenient.

**Comment by gera2ld** [comment]
Yeah it doesn't hurt to add such a button to the popup. I'm not against adding this one.
But the problem is, after adding this one, another one may be requested too. :joy: 

Besides, I think this is a rare case which doesn't have to complicate the popup window.

**Comment by gera2ld** [comment]
I'll work on tags + searching enhancement + batch actions.
