### ISSUE TITLE
[Feature] Can we also synchronize the settings in each script

### ISSUE THREAD

**Issue by freedomspiritJohn** [violentmonkey/violentmonkey#2008]
example：
![image](https://github.com/violentmonkey/violentmonkey/assets/129288685/9b403c03-1cb5-4437-8571-8aa29722952a)
Otherwise, I need to set the same script settings on each browser separately。

**Comment by tophf** [comment]
#48

**Comment by freedomspiritJohn** [comment]
> #48

But it seems like it hasn't been resolved yet
