### ISSUE TITLE
HELP me get old version of Violentmonkey CRX file !

### ISSUE THREAD

**Issue by krimnassim** [violentmonkey/violentmonkey#2011]
Hi, i'm trying to find Violentmonkey version v2.13.0 CRX file i found it in releases but there is only zip/xpi files if someone can help me get CRX file i really appreciated.

**Comment by tophf** [comment]
2.13.0 wasn't approved due to timeout, here's 2.13.0.1.
You'll need to rename it manually from zip to xpi as github didn't allow the upload otherwise.
[violentmonkey-2.13.0.1.zip](https://github.com/violentmonkey/violentmonkey/files/13961082/violentmonkey-2.13.0.1.zip)

**Comment by tophf** [comment]
Sorry, there's no crx though, because the web store doesn't maintain history.

**Comment by tophf** [comment]
Why do you need it? Maybe @gera2ld could build 2.13.0 and sign it manually...

**Comment by krimnassim** [comment]
i liked that version of Violentmonkey i need CRX if he can build it,i really appreciate ur help:)

**Comment by krimnassim** [comment]
i liked that version because i used it for long time until i had an issue with my pc i liked the older UI and i can disable script updates,the latest version won't let me the option is grayed out.

**Comment by tophf** [comment]
You can disable updates in the new version just as well and the UI hasn't changed. Could you clarify the problem?

**Comment by tophf** [comment]
> the option is grayed out

If you mean the option inside script editor it is grayed out when the script isn't updatable, so there's no need to disable the option anyway.

**Comment by tophf** [comment]
Anyway, you can unpack zpi/xpi and load it as unpacked extension if you like it.

@gera2ld, there's no need to build 2.13, sorry for the noise.

**Comment by krimnassim** [comment]
thanks for the help i will just use the latest version
