### ISSUE TITLE
[Feature] Throttling when updating scripts

### ISSUE THREAD

**Issue by msva** [violentmonkey/violentmonkey#2017]
**Motivation**

Hi there! I've a bunch of scripts stored on github.
And when they going to update, after N successfull requests, there appears 429 errors (too many requests).

And I can't see any setting to add some throttling between requests

**Proposed Solution**

I guess, it would be nice to add some option to settings page to allow settng throttling timeout between requests (checking for new version, downloading update, whatever) for each next script

**Comment by tophf** [comment]
We already throttle updates. I've never seen this error in my life though even when we didn't. What's your version of Violentmonkey and the number of scripts?

**Comment by tophf** [comment]
We throttle for 250ms currently. Please try this version with 1000ms that you can load as an unpacked extension:
[Violentmonkey-v2.18.0-1000ms.zip](https://github.com/violentmonkey/violentmonkey/files/14063495/Violentmonkey-v2.18.0-1000ms.zip)

**Comment by msva** [comment]
> We already throttle updates

I meant adding the way to assign throttle value manually from settings page

> What's your version of Violentmonkey

2.18.0

> the number of scripts

35 installed, 24 of them enabled

Most of time, I catch 429 on last or pre-last script in the list.

**Comment by tophf** [comment]
I want to fix it without adding a new option. Did you try the build above?

**Comment by msva** [comment]
> Did you try the build above?

Yup. Just finished.

And it din't triggered 429

**Comment by ABC000sk** [comment]
Solved comment

**Comment by tophf** [comment]
I think we can try keeping the current 250ms initially and when 429 status occurs we just increase it progressively and retry 10 times.

**Comment by tophf** [comment]
Also, maybe automatic update shouldn't check all scripts in one go, but instead randomize the delay...

**Comment by msva** [comment]
> Also, maybe automatic update shouldn't check all scripts in one go, but instead randomize the delay...

It is nice idea (and I voting on it, if any), but I don't think it is mutually exclusive with changing throttling delay.
I also getting 429 on manual trigger of the "check updates" :shrug:

**Comment by ABC000sk** [comment]
It is Nice but issue intox.

**Comment by simonrob** [comment]
I'm also seeing similar issues when editing scripts – #93 added a local cache, but I'm getting the `Error fetching resource!` popup when using the inbuilt editor with a script that has a OpenUserJS dependency.

**Comment by tophf** [comment]
Doesn't sounds like the same issue to me. Please open a new issue and describe how we can reproduce it.
