### ISSUE TITLE
[BUG] Error loading OpenUserJS dependencies

### ISSUE THREAD

**Issue by simonrob** [violentmonkey/violentmonkey#2019]
### Sequence of actions: 
1. Create a new script (the default template is fine for this, but the following one can be pasted if needed)
2. Add an OpenUserJS dependency
3. Using Violentmonkey's inbuilt editor, make changes to the script, saving regularly

```javascript
// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @grant       none
// @version     1.0
// @author      -
// @require     https://openuserjs.org/src/libs/sizzle/GM_config.min.js
// @description 29/01/2024, 14:46:29
// ==/UserScript==
```

### Problem: 
After saving a few times, the following error popup appears:
```
Error fetching resource!
HTTP429 https://openuserjs.org/src/libs/sizzle/GM_config.min.js
```

### Expected result:  
The dependency is loaded once and then cached.

#### Devtools console contents:
Empty

#### Environment:
- OS: macOS
- Browser: Firefox 115.7.0esr
- Violentmonkey Version: v2.18.0

**Comment by tophf** [comment]
I see, we currently don't differentiate editing from auto-update which is why we don't reuse the local copy.
