### ISSUE TITLE
希望增加1个脚本安装网页的按钮

### ISSUE THREAD

**Issue by etjim** [violentmonkey/violentmonkey#202]
有时候脚本的主页并不是脚本的安装网页，比如这个脚本：[Picviewer CE+](https://greasyfork.org/zh-CN/scripts/24204-picviewer-ce)
它的主页是http://www.hoothin.com/
但它的安装网页是https://greasyfork.org/zh-CN/scripts/24204-picviewer-ce
在VM的控制台上，该脚本只有主页这个按钮，而在该主页上是无法安装该脚本的。希望VM也像TM一样添加1个脚本安装网页的按钮，方便查看脚本详细信息！

**Comment by gera2ld** [comment]
我觉得各种链接太多了，反而会让用户很迷茫，需要去了解很多概念，这一点我不太喜欢。而且我觉得脚本的主页应该提供去安装页面的信息，不然要它何用？如果想自己覆盖脚本主页，可以通过脚本`编辑`->`设置`来配置，如图：
![image](https://user-images.githubusercontent.com/3139113/30974978-a5c03dac-a436-11e7-813a-6a2315c752a5.png)

这个issue先关闭了，如果其他用户也有此需求再考虑。
