### ISSUE TITLE
[Feature] Folder Support

### ISSUE THREAD

**Issue by Eikosa** [violentmonkey/violentmonkey#2021]
I think it would be much nicer to use folder like in file explorer rather than script group

https://github.com/violentmonkey/violentmonkey/issues/1705
https://github.com/violentmonkey/violentmonkey/issues/287

**Comment by gera2ld** [comment]
Sorry but I don't like this idea.

If you don't have many scripts, there is no need to organize them in such a complicated way.
Conversely, it is much easier to search for your scripts by tags or content.

Scripts are independent from each other, so maintaining a hierarchical structure does not make much sense. So this feature will not be implemented.

**Comment by tophf** [comment]
One case where it might make sense is when most scripts are for individual sites e.g. 10 for youtube, 10 for twitter/X, 10 for reddit.

A possible solution is to add "Group by first tag" option in the gear menu.

**Comment by tophf** [comment]
Another potentially helpful idea might be to allow the users to customize the tag colors via CustomCSS - for this we can add the tag text as a `data-tag` attribute.
