### ISSUE TITLE
[BUG] Clicking the update button fetches script content that is cached and outdated

### ISSUE THREAD

**Issue by niceqc** [violentmonkey/violentmonkey#2022]
### Sequence of actions: 
1. click on the Update Script button on the Greasyfork platform

### Problem: 
the code captured by ViolentMonkey is still the old version

### Expected result:  
get the latest version of the code

The actual function of the update button is to open a new window with the specified URL, the content of which may have been cached by the browser. the URL format is as follows

```
https://update.greasyfork.org/scripts/<id>/<name>.user.js
```

ViolentMonkey should capture the content bypassing the cache

#### Environment:
- Browser: Firefox/122.0
- Violentmonkey Version: 2.18.0

![](https://github.com/violentmonkey/violentmonkey/assets/93897839/f3b27cc4-7d36-4025-bc46-2a4bac8ac782)

**Comment by tophf** [comment]
I can't reproduce the problem, but I know that greasyfork has CDN which takes a minute or several minutes to push the update, during which time it may serve the old version and I don't know what we can do about it.

Please describe the exact sequence and timing of actions.
