### ISSUE TITLE
[BUG] Turn off a script in the script-menu on Edge will make the script disappear from the menu.

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#2025]
### Problem: 
Turn off a script in the script-menu on Edge will make the script disappear from the menu.

![PIC_2024-02-06_17-56-49](https://github.com/violentmonkey/violentmonkey/assets/15855068/1413346a-ae63-4f16-94ac-fd0192ebec14)

This problem only occurs in the system environment of Edge, Voilentmonkey 2.18.0 (installed from the Microsoft Edge Addons), other browsers or extension installation sources are normal.

#### Environment:
- OS: Win10
- Browser: Edge 121.0.2277.106 (64 bit)
- Violentmonkey Version: 2.18.0 (Installed from [Microsoft Edge Addons](https://microsoftedge.microsoft.com/addons/detail/%E6%9A%B4%E5%8A%9B%E7%8C%B4/eeagobfjdenkkddmbclomhiblgggliao) )

**Comment by tophf** [comment]
It works correctly according to your preference:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/a5c22bbd-6de9-48ea-8425-a74b66d548ec)

**Comment by F9y4ng** [comment]
It seems that this is a new setting item, why not make "Show disabled scripts" the default, hidden by default may confuse users.

**Comment by tophf** [comment]
It's an old setting. The default is to show the scripts.

**Comment by tophf** [comment]
What was the previous version?

**Comment by F9y4ng** [comment]
> What was the previous version? 

v2.16.0
