### ISSUE TITLE
[BUG] Bypasses Firefox's Resist Fingerprinting

### ISSUE THREAD

**Issue by MrQubo** [violentmonkey/violentmonkey#2026]
Firefox has a feature called RFP (Resist Fingerprinting). It does a few things, one of them is spoofing User-Agent to Windows 10. Requests sent from Violentmonkey are sent with a different User-Agent than what browser sends on normal requests. This is a problem for me, because I'm hitting Cloudflare bot detection when doing requests from Violentmonkey. Also, I've enabled RFP for a reason and I don't want to leak unnecessary data.

### Sequence of actions: 
1. Enable `privacy.resistFingerprinting` in `about:config`.
2. Enable `XHR` and `Requests` in browser console (not dev console). Alternatively, use a proxy, like Burp Suite.
3. Open some URL.
4. Send a request with GM.xmlHttpRequest to the same URL.

### Problem: 

The request from browser is sent with header `User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0`. The request from Violentmonkey is sent with header `User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0`.

### Expected result:  

Both requests should be sent with header `User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0`.

#### Environment:
- OS: Linux
- Browser: Firefox 122.0 (64-bit)
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
We're not setting this header i.e. it's whatever the browser decided, so I guess it should be reported in bugzilla.mozilla.org.

**Comment by tophf** [comment]
We could explicitly set it to the current tab's value obtained by our content script... but I wonder if it breaks something? @gera2ld, WDYT?

**Comment by gera2ld** [comment]
I don't know, that sounds dangerous. 😅

**Comment by tophf** [comment]
Shouldn't be dangerous per se because we'll do it in the content script, so my concern is rather theoretical. Like, is there a popular/important case that can be broken? I couldn't think of one, but I may be wrong, which is why adding an option might be reasonable.

**Comment by gera2ld** [comment]
Sorry I might have misunderstood the question. I think it makes sense to pass the current user-agent as the default value since it might be different in the page and background script.
