### ISSUE TITLE
[BUG] GM_addValueChangeListener of "sleeping" tab blocks GM.setValue of current tab

### ISSUE THREAD

**Issue by tobbexiv** [violentmonkey/violentmonkey#2028]
If a script uses GM_addValueChangeListener in a tab which is sleeping/inactive [1], then this will defer/block all updates of another instance of the script using GM.setValue until the tab is active again.

### Sequence of actions:
1. Set up your browser to use a very short inactive time (see for example [1] for Edge).
2. Install the example script in Violentmonkey. [2]
3. Load the script in one browser tab.
4. Go to a second browser tab and wait for the first tab to get inactive.
5. Reload the second tab and check the console output. --> after GM.setValue is missing
6. Switch to the first tab to end its sleeping/inactivity (or close it).
7. Check the console on the second tab again. --> after GM.setValue is there

### Problem:

It seems that the promise of the GM.setValue only returns once all tabs have reacted to the GM_addValueChangeListener (or were closed). However, due to the execution stop in sleeping/inactive tabs, this is not returning. As a result, the script execution in the active tab is stalled.

### Expected result:

GM_addValueChangeListener of a sleeping tab should not prevent the update of values from an active tab. Instead, GM.setValue should return immediately (or at least once all active tabs have returned). The value change information for the sleeping/inactive tab would optimally be collected until the tab is active again and then sent as bulk.

#### Devtools console contents:

n/a as no error coming from console.

#### Environment:
- OS: Windows
- Browser: Chrome 121.0.2277.112
- Violentmonkey Version: 2.18.0

[1] https://support.microsoft.com/en-us/topic/learn-about-performance-features-in-microsoft-edge-7b36f363-2119-448a-8de6-375cfd88ab25
[2]
```
// ==UserScript==
// @name        GM_addValueChangeListener of Fading Tab Blocks Other Tab
// @namespace   Example
// @match       *://*/*
// @grant       GM_addValueChangeListener
// @grant       GM.setValue
// @version     1.0
// @author      -
// @description Example script to show that GM_addValueChangeListener set in fading tabs block the return of GM.setValue in an active tab.
// ==/UserScript==

(async () => {
  console.log('add value change listener');
  GM_addValueChangeListener('test', (...parameters) => console.log('GM_addValueChangeListener', parameters));
  console.log('before GM.setValue');
  await GM.setValue('test', Date.now());
  console.log('after GM.setValue');
})();
```

**Comment by tophf** [comment]
AFAICT this is a bug in Edge because it neither wakes the tab when we send a message nor reports the failure in chrome.tabs.sendMessage. I guess we can use a timeout, but it's a bad solution generally because the tab may be legitimately busy for that duration.

@gera2ld?

**Comment by tophf** [comment]
Although we can probably remove `await` from sendMessage tasks in https://github.com/violentmonkey/violentmonkey/blob/ace56de4c59ff8deb72c53879902c9553c08d792/src/background/utils/values.js#L107 without negative consequences. IIRC I added it in an attempt to solve concurrency problems, which turned out to have a different cause.
