### ISSUE TITLE
[BUG] UserScripts localization for zh-* broken on Firefox Android

### ISSUE THREAD

**Issue by JasonHK** [violentmonkey/violentmonkey#2031]
### Sequence of actions: 
1. 
2.
3.

### Problem: 

Firefox for Android, weirdly, uses "zh-Hant-TW" instead of "zh-TW" as the language code for Traditional Chinese (Taiwan), which breaks the function (see below) used to get localized metadata since most (if not all) of the scripts use the code "zh-TW". Same should happen on Simplified Chinese (zh-CN, zh-Hans-CN).

https://github.com/violentmonkey/violentmonkey/blob/5eb2c5ad8de7ad5df6ac081e4167e715f02c6056/src/common/index.js#L159

### Expected result:  

Language code should be minimized first using function like `new Intl.Locale("zh-Hant-TW").minimize().baseName // -> "zh-TW"`.

#### Devtools console contents:

N/A

#### Environment:
- OS: Android 14
- Browser: Firefox Nightly for Android 124.0a1 
- Violentmonkey Version: 2.18.0

**Comment by Gloryandel** [comment]
Currently, this problem can be alleviated by manually copying the corresponding metadata and modifying it in custom metadata. At least be able to display the appropriate script name.

**Comment by tophf** [comment]
@gera2ld ?
