### ISSUE TITLE
[Feature] Shortcut key (`Esc`)  for closing the script installation tab

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#2032]
**Motivation**

My suggestion is to add the functionality the <kbd>Esc</kbd> key to quickly close the script install window via keyboard, instead of having to move the mouse to the 'Close' button to click it. This is how Tampermonkey works and I find it very convenient.

**Proposed Solution**

Pressing `Esc` key to close the script install window. Additionally, the `Close` button label could be renamed to `Close (Esc)` to give a visual hint. I attach a screenshot and a mockup:

![2024-02-17_205812](https://github.com/violentmonkey/violentmonkey/assets/723651/c198dcce-cd60-4a5b-9d27-5cb590b894b5)
![2024-02-17_205836](https://github.com/violentmonkey/violentmonkey/assets/723651/d32dae8f-9ae6-400e-bd05-15ad4d2ef57d)

**Use Cases**

[Test URL](https://update.greasyfork.org/scripts/377327/Kitsu%20MALonnaised.user.js)  

&nbsp;
Using Violentmonkey beta 2.17.1 with Chrome 121 on win11 x64

**Comment by tophf** [comment]
What's wrong with the standard browser shortcut Ctrl-W? The only reason we have Esc in the editor is because its action is to go back to the script list in the same tab, so Ctrl-W won't work.

**Comment by darkred** [comment]
The main reason for me is that, since I also have Tampermonkey always enabled, when I click on a URL to install a script, two script install dialogs open, one by VM and another by TM. So, being able to close both dialogs with the same key,<kbd>Esc</kbd>, would make it easier. 
And, frankly, using the Ctrl+W in the script install dialog doesn't seem like the obvious thing for me to do - it's a dialog that draws my attention every time I see it. So, pressing <kbd>Esc</kbd> seems the quickest way to dismiss it.

**Comment by tophf** [comment]
While I don't necessarily disagree to add Esc key, but it's not a dialog, it's a tab, so Ctrl-W is the natural and obvious hotkey to close it. WDYT, @gera2ld?

**Comment by gera2ld** [comment]
I'm not against it but I also think it is more natural to close a tab using <kbd>ctrl</kbd>+<kbd>w</kbd>.

**Comment by darkred** [comment]
What I meant is that the script installation tab is not like the other, normal tabs, but it's a significant one: it contains important information about the script (e.g. `@grant`, `@match`, `@connect`, `@require`, `@resource`), that helps you decide whether to install it. When you see it, you either want to inspect it carefully or quickly dismiss it (if it's by mistake).
<details>
<summary>Two examples:</summary>

![2024-02-18_140314](https://github.com/violentmonkey/violentmonkey/assets/723651/d8dffafc-2a83-4831-8af8-bb3b8fbeb193)

![2024-02-18_135546](https://github.com/violentmonkey/violentmonkey/assets/723651/90aaad6d-843e-4245-94c1-1f6cca97dd0f)
</details>

And if the script is already installed, and so you get a "Re-installing script" tab, you want to dismiss the tab in the easiest way possible. 

That's why I find that pressing <kbd>Esc</kbd> is the most straightforward shortcut for me.

**Comment by tophf** [comment]
I don't agree with this logic. It's still a tab, so Ctrl-W is the most natural way to dismiss it.

**Comment by darkred** [comment]
To clarify, I don't propose to disable <kbd>Ctrl</kbd>+<kbd>W</kbd> of course. I'm just suggesting to add an additional shortcut, <kbd>Esc</kbd>.

**Comment by tophf** [comment]
I understand. It just seems superfluous, unnecessary, and actually incorrect because it's weird to close tabs via Esc.

**Comment by tophf** [comment]
I just disagree with your reasoning and consider the entire idea inapplicable. It doesn't mean I'm against adding the hotkey, but I don't think I'll do it myself.

**Comment by darkred** [comment]
I've tried a lot to make a PR for this but I've found it to be very difficult, so I think it's best to close this.

**Comment by tophf** [comment]
You can use an external utility like AutoHotkey in Windows:

```ahk
setTitleMatchMode 2

#ifWinActive - Installing script - Violentmonkey
  Esc::send ^w
#ifWinActive
```

**Comment by darkred** [comment]
Thanks for the script!
