### ISSUE TITLE
[BUG] can not scroll script settings page

### ISSUE THREAD

**Issue by quroe** [violentmonkey/violentmonkey#2036]
### Sequence of actions: 
1.Create a new script
2.Click Settings
3.Input strings to `@include rules` or expand input area

### Problem: 
Overflowed elements (`@match rules`,`@exclude rules`,`@exclude-match rules`) are not visible and cannot be scrolled "Settings" page.

### Expected result:  
Overflowed elements are not visible, but they can be scrolled "Settings" page.

#### Environment:
- OS: Windows
- Browser: Firefox 115.8.0esr
- Violentmonkey Version: v2.18.0 (BETA v2.15.9 and later)

**Comment by tophf** [comment]
@gera2ld, look like this is because of c1bf0ce9 where you removed overflow:auto on edit-body. Could you look into this (assuming you remember how it should have worked)?

**Comment by gera2ld** [comment]
Noted, I'll check it later.

**Comment by gera2ld** [comment]
It seems removing dbc0a7977a99969cb7ba3789432f98060b3aff19 also fixes the issue. Any idea why we need it? @tophf

**Comment by tophf** [comment]
Yeah, this is what happens without it:
![2024-02-21_14-55-26](https://github.com/violentmonkey/violentmonkey/assets/1310400/61989f6f-9cb1-46c4-a55b-9fab36e518fb)

**Comment by quroe** [comment]
> It seems removing [dbc0a79](https://github.com/violentmonkey/violentmonkey/commit/dbc0a7977a99969cb7ba3789432f98060b3aff19) also fixes the issue.
I noticed `Values` page also affected.
If removing it, `Values` page can scroll too.
