### ISSUE TITLE
[BUG] Various breakages observed in latest development snapshots (v2.18.0-26-git-20240226-g9310864 and later)

### ISSUE THREAD

**Issue by Vangelis66** [violentmonkey/violentmonkey#2041]
Many thanks for maintaining `Violentmonkey`; it's the default userscript manager I install on **all** my browsers :smile: !
I often engage in retrocomputing :wink: , my "legacy"-type browser (**Serpent 52**, has WE APIs of the **Fx52-53** era, but much more recent JS+CSS APIs) is [no longer supported](https://github.com/violentmonkey/violentmonkey/pull/1759#issuecomment-1436021866), but I still use **VM** on **Chromium**-based browsers _able to run_ in my retro-WinOSes...

These Chromium forks can span from Chromium **86-based** (360 Extreme Explorer v13.x), **87-based** (Kafan MiniBrowser), to even Chromium **121-based** ([Supermium](https://github.com/win32ss/supermium) v121-hotfix) ; `Violentmonkey`, according to its `manifest.json` file, currently has **Chromium 61** as minimum version requirement:
```json
  "minimum_chrome_version": "61.0",
```
Well, I routinely check the latest **VM dev snapshots** offered as artifacts inside the [GH Actions tab](https://github.com/violentmonkey/violentmonkey/actions), with the aim of discovering possible bugs (and alerting the devs about them :stuck_out_tongue_winking_eye:) , with a side focus on sustained compatibility with "older" browser engines; I understand these builds are **not production-ready**, as such I always use them inside "test" browser profiles...

The browsers I used in my below reports were a) a **Chromium 87** based 32-bit fork & b) a **Chromium 121** based 32-bit fork, **the results have been identical and reproducible on BOTH (old and current) platforms!**

The breakages first started with artifact (renamed) `ViolentmonkeyDEV-2.18.0+26-git-20240226-g9310864` obtained from [here](https://github.com/violentmonkey/violentmonkey/actions/runs/8049453620); FYI, the `last GOOD` artifact is (renamed) `ViolentmonkeyDEV-2.18.0+24-git-20240226-g2b1b735`, downloaded from [here](https://github.com/violentmonkey/violentmonkey/actions/runs/8044274238); both, code snapshots from **VM**'s `master` branch.

### Sequence of actions: 
1. Invoke VM's toolbar button on a loaded browser tab; the enabled userscripts for the tab's site display correctly; when I try to selective disable just one userscript for the site (and expext the tab to be auto-reloaded, as per my custom preference inside VM's settings), I'm greeted with an error in red at the bottom of the popup (which overlaps other userscripts, BTW :disappointed: ) and no tab reload: 

![Bug](https://github.com/violentmonkey/violentmonkey/assets/9669492/ed975f23-c69d-4021-a91a-b579870c3550)

2. Inside the main dashboard, click the trash can icon (inside a script's entry) to send a no-longer-wanted userscript to the `Recycle Bin`; an error footer in red is displayed, overlapping the bottom script entry(-ies); no visible transfer to the RB is being observed: 

![SendindtoBIN](https://github.com/violentmonkey/violentmonkey/assets/9669492/e3453f42-9b6b-4976-9efe-13b4881f9df1)

3. Userscripts already transferred to the RB can't be permanently deleted, at least not within the same browser session; 

![InsideBIN](https://github.com/violentmonkey/violentmonkey/assets/9669492/0d95737c-f7cd-49e0-9dd2-879aec4ccb7e)

If **I click the `Empty the RB now!` button (string in blue), the userscript initially appears as deleted/gone, but if I reload that same VM tab, back it comes:**

![ReloadingBIN](https://github.com/violentmonkey/violentmonkey/assets/9669492/cbb030c1-f6c4-45e4-b654-50603ce079d6)

In addition, userscripts I have previously (same browser session) force-removed from the RB, continue to appear as striken-out when VM's toolbar button is invoked: 

![VMbug2](https://github.com/violentmonkey/violentmonkey/assets/9669492/c951674d-2239-4c0f-a7fd-aa5574bd2fa4)

(This screenshot is from **Chromium 121**, those "polyfiil-as-userscripts" are not needed _there_)

I haven't exhausted every other scenario, it's still possible other usage aspects are also affected by the "bug" ...

**Troubleshooting** (?)

[2b1b735...9310864](https://github.com/violentmonkey/violentmonkey/compare/2b1b7351c78d3f1ac83f16aafa2028c1c337eb44...9310864d32f39076d52da8552664861f62a80956), as I see it (could be wrong, of course :stuck_out_tongue_winking_eye: ), points to 26e941463f6207a7bfadbd4c8a4df28386c4eb16 ; FWIW, and according to [this article](https://web.dev/articles/bfcache), `bfcache` was first implemented, in a partial iteration, in **Ch86**, perfected later in **Ch96**; does VM still target **Ch61** at minimum (or does that commit not affect Ch61-85) ?

Many thanks for your coding efforts :+1: and for reading my report :wink: ; slight apology for not sticking fully to the issue template...

**Comment by tophf** [comment]
I can't reproduce any of these problems in Chrome 87. Can you do it in a new profile? If you do I need an exact instruction. The bfcache error is not related and cannot cause this behavior.

**Comment by Vangelis66** [comment]
> Indeed **that commit** is the cause of the problem.

Thanks a bunch for your attention to my ticket :+1: and your swift actions :heart: ...
Indeed, I downloaded the **most current artifact** from [here](https://github.com/violentmonkey/violentmonkey/actions/runs/8101198189) and it appears to have remedied **all issues** I reported :tada: ; much obliged :smile_cat: ...
