### ISSUE TITLE
[BUG] "document-start" and "document-body" are broken

### ISSUE THREAD

**Issue by sn-o-w** [violentmonkey/violentmonkey#2042]
### Sequence of actions: 
1. Install this script: https://greasyfork.org/en/scripts/404535-ig-helper
2. Modify script's @run-at to "document-start" or "document-body".
3. Go to Instagram website and log in if you are not logged in.
4. Access Instagram home page.

### Problem:
IG-Helper will behave weirdly and sometimes not download the selected media properly. Plus, it will spawn multiple times the same message:

https://github.com/violentmonkey/violentmonkey/assets/2406819/5faf5c41-8998-45cc-90ab-a2298a6f8bce

^ For privacy reasons, I chose not to share content from the Instagram website. It doesn't even matter, anyway.

### Expected result:
IG-Helper working OK while using "document-start" or "document-body".

---

Looks like the timings are messed up with "document-start" or "document-body" while using Violentmonkey.

Given that IG-Helper works without any problem in Tampermonkey with "document-start" or "document-body", this seems like a Violentmonkey bug. 🤔

#### Environment:
- OS: Windows 11 23H2 (build 22641.3227)
- Browser: Chrome Beta - 123.0.6312.22
- Violentmonkey Version: 2.17.1 (BETA)

**Comment by tophf** [comment]
I can't reproduce the problem, the output in console is the same. Try updating to the current version 2.18.

**Comment by tophf** [comment]
Yeah, try the latest stable.

**Comment by tophf** [comment]
Of course. You can use export/import buttons.

**Comment by tophf** [comment]
Yes, I followed all the steps except I used Canary and stable instead of beta. I don't think there's any difference.

**Comment by tophf** [comment]
Sounds like you may have another script that interferes with this one when it runs early. Try disabling all scripts except this one.

**Comment by tophf** [comment]
Yeah that's exactly what I did here, nothing fancy, and I only see 3 messages for 3 articles shown in my home feed.

**Comment by tophf** [comment]
Thing is, there's nothing to improve or change because it just runs early. I don't know why it fails in your case, but I won't investigate it further unless someone comes up with a report that I can reproduce locally or someone debugs what happens in devtools debugger...

**Comment by tophf** [comment]
Maybe you have customized options for that script? Upload the backup from Violentmonkey with this script and settings here.

**Comment by tophf** [comment]
I mean these options:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/0bdf90f6-e2a8-4295-a0fa-9e93b4149ade)

**Comment by tophf** [comment]
Okay, let's try that. My email is tophf at gmx.com

**Comment by tophf** [comment]
Got it, I can see the problem here, gonna debug it...

**Comment by tophf** [comment]
The problem is that the site redefines standard timer functions like clearInterval which Violentmonkey calls directly, whereas Tampermonkey saves the initial unaltered function. We did that too for a long time, but then I optimized initialization time too much I guess so now I'll restore the old behavior for at least the most common functions such as this one.

**Comment by cyfung1031** [comment]
> The problem is that the site redefines standard timer functions like clearInterval which Violentmonkey calls directly, 

Does the script is executed in an isolated content? The standard timer functions should be not modified by the page content?

**Comment by tophf** [comment]
By default scripts run in the `page` context i.e. the MAIN world.
