### ISSUE TITLE
Document how to customize editor settings like autocompletion

### ISSUE THREAD

**Issue by cheater** [violentmonkey/violentmonkey#2043]
### Problem: 

Since some time there is autocompletion in the editor and it's extremely annoying. There is no way to turn it off. I tried figuring out the option in the codemirror settings, but I haven't been able to after googling for a long time. Please make it possible to turn it off, or add a hint to the codemirror options about how to turn it off.

**Comment by tophf** [comment]
1. In Violentmonkey's settings click `Show editor state` button
2. You'll see "autocompleteOnTyping"
3. Add `"autocompleteOnTyping": 0,` to the config

**Comment by tophf** [comment]
I guess I'll add it to the default config for easier discover.

**Comment by cheater** [comment]
thanks a lot. I've noticed autocompleteOnTyping, but by default it is set
to 100, so it didn't look like an option that could turn something off. The
codemirror manual you link to doesn't mention this option at all. Could you
please add info to that config area about setting it to 0 to turn off
autocomplete?

**Comment by tophf** [comment]
These settings can't have a comment. Using 0 or false or null is a common way to disable features in CodeMirror.

**Comment by cheater** [comment]
right but most people won't know what's common or not common in
CodeMirror... because they don't use CodeMirror...

you could add a hint below the text area that holds the settings :)

**Comment by tophf** [comment]
Well, the default config contains a few options with `false` so I'd say it's a good hint.

**Comment by cheater** [comment]
no dude that's like a riddle. come on, there's really no reason to hate
other programmers. make things easy.

**Comment by tophf** [comment]
So far I see only one complaint, which means that other people either aren't annoyed or they guessed it quickly :-)

**Comment by cheater** [comment]
or they didn't bother asking. survivor bias. the fact that it took me ages
to search this out and i still didn't find it should be enough reason for
you to make this easier, it's not like anyone else had better chances.
playing guessing games is bullshit.

**Comment by tophf** [comment]
Sounds like non-survivor bias :-)

**Comment by cheater** [comment]
riiiiight, funny, so can you add the hint to the thing? it seriously isn't
good to make this obscure on purpose.

**Comment by tophf** [comment]
There are many settings, so I don't think we should describe this one in particular.

**Comment by tophf** [comment]
Riddles notwithstanding, it makes sense to add a description for the most popular settings, at least for the nonstandard ones that we implemented ourselves like autocompleteOnTyping.

**Comment by cheater** [comment]
thank you, appreciated

**Comment by cheater** [comment]
thank you very much!
