### ISSUE TITLE
[BUG] Editor Irresponsible -> Entire Extension Malfunction

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2046]
### Sequence of actions: 
1. Download / View the content of [a.user.js.txt](https://github.com/violentmonkey/violentmonkey/files/14546657/a.user.js.txt)

2. Copy the content of that file
3. Create a new script in violentmonkey. The editor page will be shown
4. Paste the content to the editor textarea.
5. click the line "▼" to collapse `var e, t, n = ` (L17)
6. click the line "▼" to collapse `!function () {` (L16)
7. click the line "▶" to expand `!function () {` (L16)

### Problem: 

No Response. Entire Extension Hangs. (including violentmonkey's other functions/features)

### Expected result:  

The code can be expanded without issue.

#### Environment:
- OS: MacOS
- Browser: Brave (Chrome 122)
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
I can't reproduce it. Anyway, if there's a bug in CodeMirror which causes an infinite loop, it will naturally hang the entire extension process, there's nothing we can do about it. Use an external editor for large scripts.
