### ISSUE TITLE
Annoying script update notification

### ISSUE THREAD

**Issue by SeriousHoax** [violentmonkey/violentmonkey#205]
### What is the problem?
I have AAK Cont script installed in my Firefox 57 Nightly. Since Violentmonkey 2.8.7 every time the AAK Cont script gets updated Violentmonkey notifies me. It's cute but I don't wanna be notified every time. Let everything happen in the background. 

### Environment
- Browser: Firefox 57 Nightly
- Browser version: Latest
- Violentmonkey version: 2.8.7
- OS: Windows 10

**Comment by gera2ld** [comment]
This is a feature requested by other users, you can disable it in options. I think I will make it disabled by default.

**Comment by SeriousHoax** [comment]
Oops sorry. How did I miss that! 😑 Sorry. Yes I mean it's better if it's disabled by default. Ok thanks 🙂
