### ISSUE TITLE
the line numbers in the editor began to be copied

### ISSUE THREAD

**Issue by AleksG3** [violentmonkey/violentmonkey#2050]
when copying the script from the editor, the line numbering began to be copied, how can I fix it?

**Comment by tophf** [comment]
You must have clicked outside the code area and then you selected everything in the window. Click in the code area first.

**Comment by AleksG3** [comment]
Thanks for the answer, but following your instructions, I get the same result as it was copied with line numbering, so it is copied with it. What is the reason for this defect in the editor's work? This was not the case in December

**Comment by tophf** [comment]
It works correctly for me. What is your browser and its version? What is Violentmonkey version?

**Comment by AleksG3** [comment]
Portable Firefox 123.0.1 (64)
Violentmonkey 2.18.0
it makes no difference to me, no matter how you select and click copy anywhere, it is still copied with line numbering

**Comment by tophf** [comment]
Works for me in Firefox 123. I have no idea how such bug can occur.

**Comment by AleksG3** [comment]
except if you copy one line, then everything is ok

**Comment by tophf** [comment]
Multiple lines are okay here.

**Comment by tophf** [comment]
I guess it's caused by some `about:config` setting or a bug in Firefox.

**Comment by AleksG3** [comment]
Thanks for the prompt answers, I will demolish everything and install it in a new way, maybe it will help

**Comment by tophf** [comment]
BTW if it looks like this then you didn't select the code area:

```
CodeSettingsValues?
Backspace goes back
SaveSave & CloseClose
1
// ==UserScript==
2
// @name          Backspace goes back
3
// @include       *
4
​```
