### ISSUE TITLE
[BUG] console.log not working on some sites

### ISSUE THREAD

**Issue by fwonce** [violentmonkey/violentmonkey#2051]
### Sequence of actions: 
1. use `console.log("something")` in a script
2. make sure this script get executed on the target site, by any means like firing an alert
3. make sure console log is not filtered out by my browser's setting itself
4. open console and see no result of the above statement
*NOTE* I cannot provide the URL because it's an intranet one.

### Problem: 
`console.log("something")` cannot produce any result. 

### Expected result:  
`console.log("something")` can produce the expected result.

#### Devtools console contents:
Not relevant. But the useful information I can give is that I believe this bug is triggered by the replaced implementation of `console.log` by the website's developer.
Evidences:
1. `console.error`, `console.warn` both works fine.
2. Other userscript manager not reproducing the same bug, like Greasemonkey and Tampermonkey. Plus the script has been used for years.
3. [CRITICAL] running `console.log` in the console and clicking the link leads to a code fragment like this: `(console.log=function(){})`. So definitely the implementation has been changed indeed.

#### Environment:
- OS: macOS Sonoma 14.2.1
- Browser: Firefox 123.0.1
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
The workaround is to run your script earlier and make a copy of `console` like this:

```js
// @run-at        document-start
// ==/UserScript==

const console = Object.assign({}, window.console);
addEventListener('DOMContentLoaded', () => {
  // main code
}, {once: true});
```
