### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by shinji-ikari** [violentmonkey/violentmonkey#2054]
**Motivation**

![图片](https://github.com/violentmonkey/violentmonkey/assets/12407493/783caa70-ad78-46c9-aa63-028f6a56c403)
![图片](https://github.com/violentmonkey/violentmonkey/assets/12407493/9d91a592-e4ad-4960-81fc-9eb87f554d6b)

https://github.com/violentmonkey/violentmonkey/issues/2053

sorry for the multiple unrelated problems in 2053 issue.
and it's not sync problem so it's not a bug.

i don't use sync at all. i don't even notice this funtion until you mention it. the default set is no.
already try re-install violent moneky also with new profile.

hmmm, let me try this way: 

1.  i set violentmonkey tool bar icon shows how many scripts running at current website 

2. close firefox, run firefox,  i could see the script number on violentmonkey icon, and the scripts works fine.

3. when first go into violentmonkey control panel, the installed script always like the second picture, all empty until 2-5 minute later , scripts will show up immediately. after this, it won't be like this again. it will show up immediately until restart firefox.

sometimes it kind of confuse me, is something broken and my scripts all gone? or it just too slow to load out all scripts.

**Proposed Solution**

hope a warn or hint to show like : scripts is loading , please wait few seconds or minutes. 
with words to know all is fine, it just need some time to load out.

**Use Cases**

can tell people that things still fine?

**Comment by tophf** [comment]
I can't reproduce this problem, I have never seen anything like this, and I can't even think how this behavior is physically possible, so I can't fix it. Please open the devtools console and see if there are errors. Also check `about:debugging` -> This Firefox -> `Inspect` in Violentmonkey entry.

**Comment by shinji-ikari** [comment]
![1](https://github.com/violentmonkey/violentmonkey/assets/12407493/dae402b2-d875-4f21-9ff0-a716fbc55c55)
![2](https://github.com/violentmonkey/violentmonkey/assets/12407493/19c53463-c6cb-4601-8e7c-868f2c597f39)
![3](https://github.com/violentmonkey/violentmonkey/assets/12407493/1d4a8713-9bf1-4af9-947a-05ba0af40071)
![4](https://github.com/violentmonkey/violentmonkey/assets/12407493/3dc40a2c-4c2f-4241-a919-280eef56b604)

![图片](https://github.com/violentmonkey/violentmonkey/assets/12407493/c512ce56-6d8a-44e7-8502-cf02916ef3fd)

`check about:debugging -> This Firefox -> Inspect in Violentmonkey entry.` by this.
figure out why....
some scripts cause the issue, 
looks like download the icon from website but 403 forbidden....so it won't show scripts until it finally timeout to stop?
just weird why the it's not the same time to wait. sometimes it's fast done in 1 minute, sometimes it take longer in 5 minutes.
i tried to delete some scripts that contain the 403 website, and it goes fast....

 1. picture is restart firefox and run inspect violentmonkey entry
 2. mouse move to violentmonkey icon, it cause some `选择器错误导致忽略规则集` i don't why
 3. open the  violentmonkey control panel, more `选择器错误导致忽略规则集`
 4. 5. after all load out.

i repeat the moves for several times. and delete some involved script to repeat it several times. and yes. the script can't load icon maybe something more to cause it load out slow.

```
Missing required resources. Try vacuuming database in options. 
Array [ "https://*/favicon.ico", "https://**/favicon.ico" ]
index.js:1:148238
选择器错误导致忽略规则集。 index.css:1:6311
选择器错误导致忽略规则集。 index.css:1:6430
选择器错误导致忽略规则集。 index.css:1:6555
选择器错误导致忽略规则集。 index.css:1:6789
选择器错误导致忽略规则集。 index.css:1:6843
选择器错误导致忽略规则集。 index.css:1:6989
选择器错误导致忽略规则集。 index.css:1:7037
选择器错误导致忽略规则集。 index.css:1:6311
选择器错误导致忽略规则集。 index.css:1:6430
选择器错误导致忽略规则集。 index.css:1:6555
选择器错误导致忽略规则集。 index.css:1:6789
选择器错误导致忽略规则集。 index.css:1:6843
选择器错误导致忽略规则集。 index.css:1:6989
选择器错误导致忽略规则集。 index.css:1:7037
未知属性 '-moz-border-radius'。  声明被丢弃。 index.css:1:19619
未知属性 '-moz-box-shadow'。  声明被丢弃。 index.css:1:21897
XHRGET
https://*/favicon.ico
[HTTP/2 403 Forbidden 1079ms]

XHRGET
https://**/favicon.ico

Object { url: "https://*/favicon.ico", status: 403, headers: Headers(6), data: Blob }

TypeError: NetworkError when attempting to fetch resource.
https://**/favicon.ico
GET
https://*/favicon.ico
[HTTP/2 403 Forbidden 262ms]

GET
https://*/favicon.ico
```

**Comment by tophf** [comment]
Thanks. Indeed, it looks like network request is delaying the UI, which is a bug. I'll fix it. Meanwhile you can edit the bad scripts and fix these incorrect favicons.
