### ISSUE TITLE
[BUG] Script doesn't load on first time

### ISSUE THREAD

**Issue by domgom** [violentmonkey/violentmonkey#2055]
### Sequence of actions:
1. Load the matched page. Violent monkey icon is grayed out.
2. Refresh the matched page. Violent monkey icon shows 1 active script.

### Problem:
Script won't load unless I refresh the page.

### Expected result:
Script loads all the time without requiring a page refresh.

#### Environment:
- OS: MacOS 14.3.1 (23D60)
- Browser: Firefox 124.0 
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
I can't reproduce the problem and this is the only such report, so you'll have to provide more info. My only guess so far is that you navigate a modern SPA site which reuses the same page and just fakes the URL change.

**Comment by domgom** [comment]
I realised 
`https://mydomain.com/start/#/*` didn't work and
`https://mydomain.com/start/*` did work.

Thanks.
