### ISSUE TITLE
No AMO updates

### ISSUE THREAD

**Issue by HouyiTheArcher** [violentmonkey/violentmonkey#206]
Currently there is only outdated version of Violentmonkey available on addons.mozilla.org.

**Comment by gera2ld** [comment]
Because the review takes quite long time, new versions will not be published to AMO in the near feature. Please install from [releases](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by marsjaninzmarsa** [comment]
Will not be published cause of being reviewed, not because of not being sent for review, right?

**Comment by gera2ld** [comment]
@marsjaninzmarsa Not sure what you mean...
I talked with the reviewer, and was told that the add-on is relatively complex, so the review takes longer time no matter in or not in the admin queue. Review of each earlier version takes about half a year or even longer, which is almost impossible for me to fix bugs in time. So I decide to self-host the new versions.
The reviewer also said they are working on a new review system, which would be much faster. Maybe VM will be published to AMO again when they are ready.

**Comment by HouyiTheArcher** [comment]
Okay, thank you for the explanation. I'll be checking the "releases" page here.

**Comment by ivysrono** [comment]
@gera2ld https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/
