### ISSUE TITLE
[Feature] Show update progress when user click "update all" in the option page.

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2063]
**Motivation**

I have many scripts. When I click "update all" in the option page, the update progress is unknown to me. I want to know how many left and whether it is all checked.

**Proposed Solution**

<img width="286" alt="Screen Shot 2024-04-06 at 15 51 20" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/b8e9307d-bf37-4263-a03f-cfa38b84bb77">

Show a progress message after the update button, when it is clicked.
* "Update Check: 13 / 40 scripts"
* "Update Check: Completed"

**Use Cases**

**Comment by tophf** [comment]
Arguably it takes just a couple of seconds for most users, so I don't want to introduce unnecessary info, since we already display the status on each script. We can 1) show the progress in the update icon's tooltip and 2) we can animate this icon e.g. rotate it.

**Comment by cyfung1031** [comment]
> We can 1) show the progress in the update icon's tooltip and 2) we can animate this icon e.g. rotate it.

That's also good!
