### ISSUE TITLE
[BUG] Violentmonkey >= 2.16.0 is not working in Waterfox Classic

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2064]
### Sequence of actions: 
N/A

### Problem: 

Violentmonkey can work in [Waterfox Classic](https://classic.waterfox.net/) for version 2.15.0 or below.

Now it cannot open the option page from the Browser Action Menu.
The option page can be opened from browser menu `Add-ons > Violentmonkey > Preferences`
But the script list is empty.

The console window shows that it cannot connect to the background page.

After installing 2.15.0 back, the scripts appear again.

#### Environment:
- OS: macOS Monterey 12.6.1
- Browser: Waterfox Classic 2022.11 (64-bit) 
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
The background console in about:debugging says `Incorrect argument types for tabs.onUpdated`, so it's a bug in Waterfox, which despite being based on Firefox 68, doesn't implement filtering in tabs.onUpdated. I'll restore the workaround we've used in the older Violnemonkey.
