### ISSUE TITLE
[BUG] `GM.xmlHttpRequest()` returns non-200 response

### ISSUE THREAD

**Issue by adamlui** [violentmonkey/violentmonkey#2068]
### Sequence of actions: 
1. Install [GitHub Star History](https://greasyfork.org/en/scripts/473377-github-star-history) userscript
2. Visit https://github.com/violentmonkey/violentmonkey (or any repo) with script active in Violentmonkey
3. Observe in console that `insertStarHistory()` failed to fetch image

### Problem: 
`GitHub Star History ⭐.user.js:416 Error loading star history chart: Error: Failed to fetch image at insertStarHistory (GitHub Star History ⭐.user.js:391:19)`

### Expected result:  
Return 200 instead of some `abort` obj as observed when response logging is added to the function, like Tampermonkey successfully does when running the same function in Chrome, Edge, Vivaldi, Firefox, Opera, Ghost, QQ & Whale

#### Devtools console contents:

When response logging is added:

![image](https://github.com/violentmonkey/violentmonkey/assets/10906554/39f2c602-5eb0-480f-9556-75fb3c51a1d0)

#### Environment:
- OS: Windows
- Browser: Vivaldi Version 6.6.3271.57 (Official Build) (64-bit) (I don't use VM/Vivaldi, but a user [reported the issue](https://github.com/adamlui/userscripts/issues/74) in this env, so that's where I confirmed his suspicion the function doesn't work)
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
We implement GM.xmlHttpRequest per [the original specification](https://wiki.greasespot.net/GM.xmlHttpRequest) which says `undefined` is returned and we augment it by returning the same control object with `abort` as we do for [GM_xmlhttpRequest](https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest). Tampermonkey goes further and returns a Promise with the same `abort` function.

I'll do the same in Violentmonkey only because it makes sense conceptually, but I don't recommend using it in any public script because it'll be incompatible with other platforms that implement the specification.

**Comment by adamlui** [comment]
But the function returns 200 in Tampermonkey is the issue here (the img URL should be valid and return a blob)

**Comment by tophf** [comment]
I know. Did you read my comment fully? Your code uses a nonstandard feature implemented only by Tampermonkey. If you want your code to be compatible you need to use `onload` and other callbacks.

**Comment by tophf** [comment]
You already do it correctly in updateCheck().

**Comment by adamlui** [comment]
Indeed I read your comment fully, in it you imply it is intentional for TM to not return 200 because TM offers a "bonus" feature of also returning a promise, something you do not offer.

However what my comment is explaining, TM does not return an `abort` at all because the img URL is valid 

![image](https://github.com/violentmonkey/violentmonkey/assets/10906554/230d3541-fd82-46d5-94ba-5b6d16d955e4)

It returns a blob which VM does not, so the "bonus" feature you reference is not the cause in difference of behavior

**Comment by tophf** [comment]
No, you are looking at the awaited result, not at the returned value.

**Comment by adamlui** [comment]
`You already do it correctly in updateCheck().`

Ok what is the "correct" way you want me to refactor the function to work with your manager?

**Comment by adamlui** [comment]
> No, you are looking at the awaited result, not at the returned value.

The awaited result is not 200 in VM but 200 in TM...

**Comment by adamlui** [comment]
So I added onload to fix it right, also it's interesting you called Tampermonkey "nonstandard" because they are the standard manager most authors recommend and have over 10,000,000 users on Chrome store vs. VM has 900,000, so it would be wise to avoid this mindset and instead try to catch up with how they implement things if you also want to become a standard one day

**Comment by tophf** [comment]
You're looking at the awaited result i.e. `await GM.xmlHttpRequest()`. 

To see the returned result of the function you should look at `GM.xmlHttpRequest()`. You'll see that in the specification it's `undefined`, in Violentmonkey it's a control object with `abort` inside, in Tampermonkey it's `Promise` with `abort` inside.

You can't use `await` anyway except Tampermonkey if you want your script to be compatible with other specification-compliant managers.

You can use the same approach you've already used in your updateCheck().

You can also combine it with the standard promisification technique:

```js
const res = await new Promise((resolve, reject) => GM.xmlHttpRequest({onload: resolve, onerror:reject}))
```

>  so it would be wise to avoid this mindset and instead try to catch up with how they implement things

Tampermonkey's approach is not always wise.

> if you also want to become a standard one day

But we don't.

**Comment by adamlui** [comment]
But they are standard nonetheless so if users of scripts complain it doesn't work in what they understand to be non-standard way, authors will advise them to switch to TM, so it's still good to adhere to standards even if "not always wise" so users don't leave VM

**Comment by adamlui** [comment]
(I didn't advise the complainant to leave VM but another benefit is authors will be more incentivized to endorse VM if it works without refactor from workign TM version)

**Comment by tophf** [comment]
We'll evaluate every case when it's reported. Our goals are different, we don't earn money on this extension.

**Comment by adamlui** [comment]
In this case it seems you have concluded "makes sense conceptually" is why you will copy TM, but my broad point remains they are the standard so it is strange to call them non-standard to justify your implementation is not "broken"

**Comment by tophf** [comment]
There is a historical userscript specification, which is standard. Just because Tampermonkey is popular doesn't change this. Like I said, not everything it implements makes sense.

**Comment by adamlui** [comment]
Well VHS was historically a standard but is not today. So it's the same like if I started a new car company and it has five wheels instead of four the ccurrent biggest company already releases. A driver complains of a side effect gas is guzzled more.. I tell him "you are used to non-standard driving on four wheels, it is not wise my way is wiser it is not broken" is a peculiar way of describing the issue

**Comment by adamlui** [comment]
No one really uses Greasemonkey anymore because it's not actively maintained/updated w/ new functions TM author innovates so TM is truly the standard as my analogy is trying to elucidate

**Comment by adamlui** [comment]
But GM author Aaron Boodman absolutely invented the standard not discrediting him at all

**Comment by tophf** [comment]
The old classic specification is used in many places, including built-in support in Chrome and browsers like AdGuard. TM is not the new standard, it's just a playground where the author experiments with new stuff. We occasionally but regularly implement things that were proven to be useful.

**Comment by adamlui** [comment]
For some reason I thought Google deprecated native userscript support is why the largest userscript repositories like Greasy Fork recommend installing a manager, but whatever the reason, GF is an extremely-high-trafficked site (probably because userscripts are popular in Asia where browsers like QQ pre-install TM and link to GF) that advises users to install a manager, so it is more than a "playground" but a source for stable extended functionality millions of users come to rely on authors for nowadays

**Comment by tophf** [comment]
Playground is a term in software that denotes a place where you can experiment with stuff. This is what the author of TM does a lot. We adopt some of these. We're not interested in adopting everything.

**Comment by adamlui** [comment]
Google plays with many experiments too, yet their Search is pretty standard, and so is TM in terms of it is the most used manager, recommended by the most-trafficked site that is the repository of the most userscripts and the most used source for installing new ones. Yes TM experiments with stuff (he releases them in a playground ver) but the main extension is absolutely standard by every definition of the word (also adopts stuff from experiments to become new standard)

**Comment by tophf** [comment]
Google is participating in a standards committees where other browser vendors discuss the new experiments and not all of them are accepted by them. TM's author does nothing of that.

**Comment by adamlui** [comment]
That's beacuse userscript has been a really niche standard for a long time until it took off in Asia after QQ started bundling TM, but once/if it gets big enough, I imagine he will likely be invited to such a committee

**Comment by tophf** [comment]
When userscripts were niche 10-20 years ago there were many authors collaborating on its standards. TM's author doesn't seem interested.

**Comment by adamlui** [comment]
Oh I do not doubt he is highly profit-driven instead, I'm just explaining why Google is in standards committees and he will probably get the invite then reject it based on your observation

**Comment by adamlui** [comment]
(if it means less revenue)

**Comment by tophf** [comment]
Google and other vendors were always participating in standards committees, while Microsoft Internet Explorer didn't, so I think the proclivity to collaboration vs solo experimentation is something basic, inherent.

**Comment by adamlui** [comment]
> We'll evaluate every case when it's reported. Our goals are different, we don't earn money on this extension.

This is another very strange statement, what makes you think making an API easier/closer to a widely adopted standard for authors is only useful for earning money?

**Comment by tophf** [comment]
You act in a very hostile manner, which either means I hurt your feelings or you're just inherently toxic. While we could theoretically resolve this, but I don't see the need as Violentmonkey is more of a hobby project and we don't have the need to prove anything to anyone.

**Comment by adamlui** [comment]
What do you think constructive even means if not exactly that? Also calling you a dictator _is_ constructive, it's to elucidate you are under a false impression this is somehow a "group" project with your insistent use of "we" for decisions you are making unilaterally (the word does not necessarily mean mass murderer, it's just an apt and helpful description of your behavior that is harming the project's progress)

**Comment by adamlui** [comment]
Not even saying you are obligated to further the progress for the public good, just trying to help you realize it is run as a dictatorship so your constant use of "we" in justifying all the decisions you are self-making is incorrect

**Comment by adamlui** [comment]
Every comment I make is constructive btw. If you set anger aside and read them with a neutral tone, there is much to learn if you will just reflect on what I'm saying

**Comment by adamlui** [comment]
For example, by copying TM like you proclaim you will in this instance, fewer users of popular scripts like mine will complain something didn't work in VM and end up switching sides. You can constantly deny profit is a motive, but you cannot deny user growth is vital to why this project exists (if no one ends up using it why did you start working on it?) so it is also very peculiar you keep mentioning money when I constructively point out how you will get more users

**Comment by tophf** [comment]
Your original report was helpful, thanks. I understood your arguments, there's no need to reiterate. I don't consider your comments that start after the issue was completed as constructive - it's the textbook example of a nonconstructive heated discussion - and the more you try to force me to see them as such the less likely it's going to happen. I'm not angry, I'm just seeing myself in you and that fellow, I still occasionally behave in a very similar hostile manner and absolutely refuse to admit, just like you. I didn't realize it myself until I saw it here.

**Comment by adamlui** [comment]
I agree we are quite similar and that my tone can be perceived as hostile but I was only matching how you tend to engage with the public who are only trying to help you, not I do it indiscriminately to everyone (if you review how you talk to others, you will see what I mean, it is somewhat duragatory tone too)

**Comment by adamlui** [comment]
When people contribute to my projects I am vvery positive and grateful, I only matched your tone here beacuse you started off criticizing lack of reading comprehension, so I used it as an opportunity to relentlessly point out your subsequent contradictions without remorse knowing it can be irritating but also it is helpful if reflected on neutrally (the biggest of which was this is a "we" project but you kept stating solo decisions)

**Comment by tophf** [comment]
Well, escalation doesn't work on me because I remember going very far throughout my life, so I'm not afraid to go all the way. I recently started to learn not to escalate. It's hard though because no one taught me that. This is why I locked the issue in an attempt to just move on. I did it clumsily though, which only complicated things, for which I'm sorry.

**Comment by adamlui** [comment]
No apologies are necessary I got thicc skin and I myself do not regret my actions as I am always my true self matching the vibes of those I engage, but you got me curious about going very far throughout life, what did you do?

**Comment by tophf** [comment]
I didn't value my life for a long time so I didn't know when to stop and got myself in situations where I nearly died several times.
