### ISSUE TITLE
Why did you lock https://github.com/violentmonkey/violentmonkey/issues/2068

### ISSUE THREAD

**Issue by listerine420** [violentmonkey/violentmonkey#2069]
I didn't see any hostility from @adamlui at all, he was just pointing out your contradictions completely related to the issue at hand

**Comment by adamlui** [comment]
lol

**Comment by adamlui** [comment]
who are you @listerine420 idrc about this project and will stop recommendign it on all my repo homepages, but indeed I was trying to foster wider compatibility

**Comment by listerine420** [comment]
I use your ChatGPT scripts and you show up in feed sometimes

**Comment by tophf** [comment]
> I didn't see any hostility

While I personally was much more toxic towards people when I was younger, but now I don't find that kind of communication constructive, i.e. it's a waste of time. 

> indeed I was trying to foster wider compatibility

Violentmonkey is a hobby project, it's kinda in maintenance mode, so your passion did indeed fell on deaf ears, so to speak. Occasionally one of us becomes enthusiastic and we implement stuff, but that's rare. Anyone is welcome to join us, just ilke I joined a few years ago, but we certainly won't appreciate anyone in combative mood.

**Comment by tophf** [comment]
Our definitions differ, then.

**Comment by tophf** [comment]
Anyway, the only important thing out of all this useless fuss is that GM.xmlHttpRequest in new versions of Violentmonkey will be compatible with Tampermonkey.
