### ISSUE TITLE
为何在amo经常出现没更新的更新？

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#207]
![default](https://user-images.githubusercontent.com/2649544/30266330-98fb4e9a-9711-11e7-994b-405b70835e12.png)

点进去还是2.6.3
出现了N次这样的情况了。

**Comment by gera2ld** [comment]
看不懂你在说什么

**Comment by ivysrono** [comment]
看更新日期，9月11号，上了今天的最近更新榜

**Comment by gera2ld** [comment]
因为审核太慢，近期都不发布到AMO了，新版见[releases](https://github.com/violentmonkey/violentmonkey/releases)。

**Comment by ivysrono** [comment]
算了，在解决 CSP 和支持 WebDav 之前，我还是先用 TM 对付着吧。
对了，能否帮个忙：
https://github.com/ivysrono/Scripts/blob/master/Auto-copy-guerrillamail.user.js
写了个小脚本，为何 GM_setClipboard 语句就是无效？

**Comment by gera2ld** [comment]
因为Firefox下面的`GM_setClipboard`支持有问题。。

**Comment by ivysrono** [comment]
囧，果然是Chrome下能用，泪奔
有啥办法在Firefox下实现类似功能不？

**Comment by gera2ld** [comment]
先记个bug吧

**Comment by ivysrono** [comment]
不好意思，再请教下，有没有语句能判断 GM_setClipboard 是否生效？
我想做到如果不生效就不弹出桌面通知。

**Comment by gera2ld** [comment]
@ivysrono 目前没有办法判断，下个版本会加入对Firefox的支持

**Comment by ivysrono** [comment]
啊，我还以为不支持是因为Firefox的bug呢，原来扩展能搞定的？

**Comment by gera2ld** [comment]
是因为Firefox限制比较多，只能用个有副作用的方案来解决，副作用是会导致页面selection发生变化

**Comment by ivysrono** [comment]
https://github.com/esterTion/Youku-HTML5-Player/issues/70#issuecomment-331323886
今天开始突然变成机器自动审核了，大概以后和chrome一个情况了
