### ISSUE TITLE
But why do you keep locking issues to have the last word

### ISSUE THREAD

**Issue by listerine420** [violentmonkey/violentmonkey#2070]
Does @adamlui or I piss you off or something?

**Comment by listerine420** [comment]
I didn't add the bug label that was automated, my only issue is the way you maintain this open source project

**Comment by adamlui** [comment]
😭 chill dude he's gonna ban you I know the type

**Comment by listerine420** [comment]
I'm posing a legitimate question, I find issue with the way he locks legitimate issues to have final words, even if it hurts open source community to stunt the growth of constructive discussion that would eliminate obstacles to fixing issues with non-standard implementation of things

**Comment by tophf** [comment]
> Does @adamlui or I piss you off or something?

There's no need to discuss something that's already implemented. With an exception for the original report, I consider all comments off-topic and superfluous. I don't want to continue the off-topic discussion that switched to using ad hominem, because it never ends up constructively.

**Comment by tophf** [comment]
> chill dude he's gonna ban you I know the type

Such passive-aggressive attitude is also part of that hostility I saw, it's not constructive and once such slide starts, there's usually no way to reconcile due to pride or whatever. I'm only interested in code and discussing code, so anyone who's interested in that is more than welcome here.

**Comment by adamlui** [comment]
It is neither implemented nor off-topic to discuss why Violent Monkey should not deviate from the most popular User Script manager. Ad hominem refers to attacking one's character, but no such thing occurred. He only pointed out **why** the deviation is occurring, it is because you made a false claim this is somehow a group project but he used the word 'dictator' to succinctly reveal the phenomenon, and you got mad because it has negative connotation to you when it can be used innocuously too. So you tuned out as soon as you got mad, and his constructive feedback 'fell on deaf ears' as you both admitted which actually had been occurring from the very beginning before you got mad really. So that is the reason this project progresses so slowly. And he tried to guide it in the right direction. But you tuned out after getting mad. So you are the cause not anyone else.

**Comment by tophf** [comment]
> Also it is very peculiar you keep saying "we" to refer to uni-lateral decisions you are blatantly making as the dictator of this "open" source project in this thread alone (you literally said "I (not we) will do the same in Violentmonkey only because it makes sense conceptually" when justifying why you will copy TM's innovator, so you are the driver, stop trying to make it sound like others have any input, anything I said fell on deaf ears because obviously it's your project not mine or "ours" I have no control over your decisions

What is this if not a hostile ad hominem?

**Comment by adamlui** [comment]
have you heard of the phrase "benevolent dictator"? did you know it is not malicious?

**Comment by adamlui** [comment]
do you realize I even gave you thumbs up for giving me the code to fix my script to accomodate your non-standard implemtnation of GM.xhr? does someone who holds malice trying to attack one's character do that?

**Comment by tophf** [comment]
The word dictator doesn't concern me. I see the entire comment as a hostile attack on me. I don't see any benefit in any of these comments as they are about abstract perception. I'm only interested in discussion concrete use cases and code.

**Comment by listerine420** [comment]
> There's no need to discuss something that's already implemented. With an exception for the original report, I consider all comments off-topic and superfluous. I don't want to continue the off-topic discussion that switched to using ad hominem, because it never ends up constructively.

It is neither implemented nor off-topic to discuss why Violent Monkey should not deviate from the most popular User Script manager. Ad hominem refers to attacking one's character, but no such thing occurred. He only pointed out why the deviation is occurring, it is because you made a false claim this is somehow a group project but he used the word 'dictator' to succinctly reveal the phenomenon, and you got mad because it has negative connotation to you when it can be used innocuously too. So you tuned out as soon as you got mad, and his constructive feedback 'fell on deaf ears' as you both admitted which actually had been occurring from the very beginning before you got mad really. So that is the reason this project progresses so slowly. And he tried to guide it in the right direction, showing you concrete use cases by his script's users and the millions of others who use Tamper Monkey. But you tuned out after getting mad. So you are the cause not anyone else.

**Comment by tophf** [comment]
You are repeating the same comment to which I already answered. It doesn't look like you even try to find common ground.

**Comment by listerine420** [comment]
I didn't ask you a question. I repeated no comment also.

**Comment by tophf** [comment]
This is the first time: https://github.com/violentmonkey/violentmonkey/issues/2070#issuecomment-2047196426
This is the second time: https://github.com/violentmonkey/violentmonkey/issues/2070#issuecomment-2047205910

**Comment by tophf** [comment]
90% or more of the text is the same. We're going in circles.

**Comment by listerine420** [comment]
Your first link is to a single-line question 'Does @adamlui or I piss you off or something?'

Your second link is to a comment that does not require answering, but is simply a response to youur false claim it is somehow off-topic to discuss why Violent Monkey should not deviate from Tamper Monkey to benefit the community. This does not go in circles in any way at all.

**Comment by listerine420** [comment]
i.e. 0% of the text is the same

**Comment by tophf** [comment]
The first comment:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/1e956177-9776-4e10-8e7d-97900482baac)

The second comment:

![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/394e5d4d-7072-4e2e-b7bc-060e4451f590)

90% or more of the text is the same. We're going in circles. Anyway, if you think you somehow can force me to jump through the hoops are you mistaken.

**Comment by listerine420** [comment]
I don't know why you are seeing duplicates but your link is to a single-line question not duplicate text

**Comment by listerine420** [comment]
Also it did not require answering because it is not a question

**Comment by tophf** [comment]
The first comment was by adamlui, the second comment was by listerine420. I guess these two nicks are both yours.

**Comment by listerine420** [comment]
Or you are bugging out

**Comment by tophf** [comment]
:-)

**Comment by listerine420** [comment]
Regardless of bug or not it is not a question so you should not feel so obliged to 'answer' things but instead soak in what is being said

**Comment by tophf** [comment]
Sure.
