### ISSUE TITLE
[BUG] blob url download with GM_download doesn't work

### ISSUE THREAD

**Issue by eai04191** [violentmonkey/violentmonkey#2072]
```js
// ==UserScript==
// @name         GM_download sample
// @author       Eai <eai@mizle.net>
// @license      MIT
// @version      1.0.0
// @match        https://example.com/
// @grant        GM_registerMenuCommand
// @grant        GM_download
// ==/UserScript==
/* global GM_registerMenuCommand */
/* global GM_download */

function main() {
    const sampleBlob = new Blob(["Hello, world!"], { type: "text/plain" });
    const url = window.URL.createObjectURL(sampleBlob);
    GM_download(url, "hello.txt");
}

(() => {
    GM_registerMenuCommand("Download", main);
})();
```

### Sequence of actions: 
1. Install the script and open example.com
2. Select Download from the menu

### Problem: 

File will not be downloaded.

For release version, nothing is displayed.
For beta version, an error will be output to console.

### Expected result:  

The file will be downloaded.

Works as expected with Tampermonkey in Firefox, Violentmonkey in Chrome.

#### Devtools console contents:
```
Uncaught TypeError: yn is not a function
    Pe moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    post moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    $e moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    Ye moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    GM_download moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    main moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/ GM_download sample.user.js#1:16
    Command moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    onHandle moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
    Le moz-extension://fef9b40d-d2bd-4e39-bf7f-b2e258cf5346/sandbox/injected-web.js:1
injected.js:formatted:1193:19
```

![image](https://github.com/violentmonkey/violentmonkey/assets/3516343/edea613b-a4b2-4145-bd8b-9cb36819d5d7)

Perhaps yn means getTabUserAgent?

https://github.com/violentmonkey/violentmonkey/blob/8626cd9bb8fd2533ce6e221939d6633389cfc8cc/src/injected/content/requests.js#L53

#### Environment:
- OS: Windows
- Browser: Firefox 124.0.2 
- Violentmonkey Version: BETA v2.18.2

**Comment by tophf** [comment]
Until the fix is published the workaround is to add `// @grant GM_xmlhttpRequest`

**Comment by eai04191** [comment]
Thanks. I immediately added GM_xmlhttpRequest to the grant, but no errors occur in either the release version or the BETA version, and it doesn't seem to work as expected.

**Comment by tophf** [comment]
In `about:debugging` console for the extension I see an error saying blob: cannot be downloaded. I guess the fix will be to download them in our content script in the tab, gonna try that...

**Comment by tophf** [comment]
Until the fix is published the only workaround is to replicate GM_download explicitly:

```js
const el = document.createElement('a');
el.download = "hello.txt";
el.href = url;
el.click();
```
