### ISSUE TITLE
[BUG] Is it something wrong with this part of code?

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2075]
https://github.com/violentmonkey/violentmonkey/blob/f3b9fb2ba2e908da8f207fc0b0e4a3138b303ebe/src/injected/web/gm-api.js#L15-L140

<img width="1005" alt="Screen Shot 2024-04-18 at 7 18 28" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/441d4cd1-058f-485e-9e18-7047073de3aa">

It seems that it created nested functions.
Or due to any object reference chain? (WeakRef should solve this case)

**Comment by tophf** [comment]
I don't see anything wrong.
