### ISSUE TITLE
[BUG] functions in @require library do not exist after just imported from zip

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2077]
### Sequence of actions: 
1.  export full data (zip, all scripts) from 2.18.0
2. remove existing beta version
3. install 2.18.3 beta (downloaded from chrome store)
4. in the existing tab (like youtube), refresh the tab so that the userscripts shall load

### Problem: 

` XXXX is undefined ` messages show (because not existing function is called - not provided in the context)
(not just one script. my case is two scripts (say script#A and script#B) )

### Expected result:  

No Error

#### Environment:
- OS: MacOS
- Browser: Brave 1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64) 
- Violentmonkey Version: 2.18.3

## Remarks

then I reinstalled the script. no use.

Then I created another script to test. (same script meta, just diff. script name). The script ok.

Then script#A and script#B both work.

I believe the `@require` script was not yet downloaded from internet once "imported from zip"

**Comment by tophf** [comment]
There should be an error in console about missing dependencies. I guess we should immediately download everything right after import and add an option to export dependencies into the backup in order to make it complete.

**Comment by cyfung1031** [comment]
> There should be an error in console about missing dependencies. I guess we should immediately download everything right after import and add an option to export dependencies into the backup in order to make it complete.

Download dependencies shall be part of the import process. 
The message should change to OK / completed / finished after the downloading

**Comment by tophf** [comment]
Actually it already happens, but we don't display the progress now.

**Comment by cyfung1031** [comment]
> Actually it already happens, but we don't display the progress now.

I think it could be like update error
If all the network requests are fetched at the same time, the dependency scripts could not be downloaded due to server response.

**Comment by tophf** [comment]
No, we make the requests sequentially with a delay.
