### ISSUE TITLE
[BUG] Dropbox authorization doesn't work

### ISSUE THREAD

**Issue by huyz** [violentmonkey/violentmonkey#2078]
### Sequence of actions: 
1. In Settings, select `Dropbox` for Sync
2. Click `Authorize`
3. Click `Allow`

### Problem: 

After Dropbox authorization, I get redirected to
https://violentmonkey.github.io/auth_dropbox.html?code=XXXX&state=XXX

which says:
![screenshot 2024-04-20T162701Z@2x](https://github.com/violentmonkey/violentmonkey/assets/128394/408fa277-c045-4539-bcd2-cd054d43ef63)

Settings continue to say:
![screenshot 2024-04-20T162724Z@2x](https://github.com/violentmonkey/violentmonkey/assets/128394/91133ac6-360b-4767-a0bc-309eef1cc3af)

### Expected result:  
Some page indicating success. And the Settings shouldn't say `Not authorized yet.`

#### Devtools console contents:
![screenshot 2024-04-20T162834Z@2x](https://github.com/violentmonkey/violentmonkey/assets/128394/60cc15ea-0f1e-407d-ae48-8273c3589e92)

#### Environment:
- OS: macOS 14.4 (Sonoma) (ARM64) 
- Browser: Brave: Version 1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64)
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
Sounds like a bug in the browser.

**Comment by huyz** [comment]
It sure does seem like a browser thing.

I've tried:

- Arc ✅ works
- In Brave, tried a bunch of things ❌
	- disabling blocking of third-party cookies
	- disabling shields
	- disabling filter lists
	- disabling many extensions including uBlock Origin, Disconnect, etc.
	- incognito mode

I'm out of ideas…

**Comment by gera2ld** [comment]
Cannot reproduce.

- Could you try to disable all other extensions?
- Could you check the extension background console to see if any error occurs?

**Comment by tophf** [comment]
We will have to switch to chrome.identity anyway, I guess, because webRequestBlocking is not available in ManifestV3 for normal extensions.

**Comment by huyz** [comment]
Ok I figured it out. I had forgotten that I had clicked on `This Can Read and Change Site Data` and selected `when you click the extension` and forgotten to allow extension access on the page https://violentmonkey.github.io/

![screenshot 2024-04-24T094819Z@2x](https://github.com/violentmonkey/violentmonkey/assets/128394/e897e026-75ac-4762-a1f2-c2895dc277d4)
