### ISSUE TITLE
issue with 2.8.8 version not present in 2.6.4

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#208]
https://greasyfork.org/en/scripts/18671-inject2download
this user script after updating to version 2.8.8(from 2.6.4) works really bad and unreliably with latest firefox 57 for android(mac os version works well)
it often wont show media url download(as it is supoposed to ) can someone tell me why?
reverting to version 2.6.3 everything works well

test url:
https://openload.co/embed/c28ycAO2yIc

**Comment by gera2ld** [comment]
You'd better fill the issue template with a minimal reproduction.

**Comment by gera2ld** [comment]
Cannot reproduce, need more info.

**Comment by ale82to** [comment]
sorry bug report is very messy
anyway the problem is secondary to another user script https://greasyfork.org/en/scripts/28552-better-openload-embeds
so if u install
1https://greasyfork.org/en/scripts/18671-inject2download
2 https://greasyfork.org/en/scripts/28552-better-openload-embed
and then visit an openload webpage like https://openload.co/embed/kKLaw0VRVA0
stream url wont be shown as it should(screen shot of the issue https://ibb.co/imHArv)
using violent monkey 2.6.4 i have not any problems at all.
  after playaround ...... i discovered that editing better-openload-embed user script i can solve the issue
chanching    clearInterval(tmrstreamurl);
    }
   },100);
  }
 }); 


to    clearInterval(tmrstreamurl);
    }
   },1000);
  }
 });
  

i dont really know why violent monkey 2.8.8 has so many issue i really hope that can be fixed

**Comment by ale82to** [comment]
so any news  ?

**Comment by NudeSpoons** [comment]
@gera2ld Can you update this issue, please?

**Comment by tophf** [comment]
Violentmonkey has changed and improved its injection since 2017 so it should be working fine now.
