### ISSUE TITLE
[Feature] Export a Single Userscript

### ISSUE THREAD

**Issue by bumprat** [violentmonkey/violentmonkey#2081]
**Motivation**
There seems to be no easy way to export a single userscript on the script list view. 

**Proposed Solution**
Add single userscript export feature.

**Use Cases**
Select one or multiple userscripts and export as zip, which can be imported on another machine.
Or on the settings page, select which scripts to export after clicking the "export as zip" button.

Thanks for making this wonderful browser extension.

**Comment by tophf** [comment]
How often do you need it? If it's rare then you can manually delete the extra files in the zip.

**Comment by bumprat** [comment]
> How often do you need it? If it's rare then you can manually delete the extra files in the zip.

OK. I write my own scripts and share with others occasionally.

**Comment by eternal-sorrow** [comment]
I just needed it to copy one script to my mobile Firefox. Turns out the editor doesn't work on mobile, so I cant just copy it as a text. I can't also import the script from URL for some reason.
