### ISSUE TITLE
[BUG] Doesn't match `*://addons.mozilla.org/*`

### ISSUE THREAD

**Issue by a-pav** [violentmonkey/violentmonkey#2085]
### Sequence of actions: 
1. I intent to change outgoing links on `*://addons.mozilla.org/*` to their respective direct links and this is my script:
```js
// ==UserScript==
// @name		addons.mozilla.org - Direct outgoing links.
// @description	Direct outgoing links.
// @namespace	a-pav
// @author		a-pav
// @version		1.0
// @grant		none
// @match		*://*.mozilla.org/*
// @run-at		document-idle
// @icon 		https://addons.mozilla.org/favicon.ico
// ==/UserScript==

'use strict';

(() => {
	alert('Hello from direct outgoing!');
	document.querySelectorAll('a[href*="outgoing.prod"]').forEach((e) => {
		e.href = e.title;
	});
})();

```
2. Open an extension page on https://addons.mozilla.org/.
### Problem: 
Script is not matched for https://addons.mozilla.org/ pages and I don't get the alert  `Hello from direct outgoing!` while I'm on the site (but on https://blog.mozilla.org/ the alert is shown.)

Violentmonkey doesn't even show this script as matched for the website while I'm on https://addons.mozilla.org/!
### Expected result:  
Normal execution. See the alert and script as a match for the website.

I tried `// @inject-into content` and `// @unwrap` without success.
#### Devtools console contents:
None!
#### Environment:
- OS: Linux
- Browser: Firefox Developer Edition 126.0b5 (64-bit)
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
Mozilla doesn't want you to access its sites by default.
To allow access:
1. open `about:config`
2. right-click the list, click 'New', then 'Boolean', paste `privacy.resistFingerprinting.block_mozAddonManager`, then OK, `true`, OK
3. Remove this domain from `extensions.webextensions.restrictedDomains`
