### ISSUE TITLE
[BUG] Cannot edit script values in some mobile device due to UI layout issue

### ISSUE THREAD

**Issue by orionlee** [violentmonkey/violentmonkey#2088]
On Samsung Galaxy Tab S6 with Firefox for Android, when I try to edit the values (those managed by GM_get/setValue) of a script in the Script > Values tab
- I cannot save the values because the buttons are missing (both in landscape and portrait). See screenshots below.
- for scripts that do not have any values, the buttons do show up.
- The issue does not happen on another device (Google Pixel 3a).
- I cannot reproduce it using desktop Firefox in responsive design mode, simulating the tablet.

Screenshots for:
- [portrait](https://github.com/violentmonkey/violentmonkey/assets/250644/0b9891bf-653f-4fd3-a60b-f53332ac113f)
- [landscape](https://github.com/violentmonkey/violentmonkey/assets/250644/f014bb3d-ae48-4126-b957-ea6ad3c0a60f)

### Expected result:  

The Ok / Apply / Cancel buttons should show up.

#### Devtools console contents:

Did not obtain.

#### Environment:
- OS: Android 12
- Browser: Firefox for Android 125.3
- Device: Samsung Galaxy Tab S6 (1600 X 2560 pixels) 
  - On the browser: `devicePixelRatio`: 2.22, `screen.height`: 720,  `screen.width`: 1152
- Violentmonkey Version: 2.18.0

**Comment by orionlee** [comment]
In landscape mode, there are other UI layout issues. The Code and Settings tabs are not visible, and the Values tab is barely accessible.

[screenshot](https://github.com/violentmonkey/violentmonkey/assets/250644/15c61d79-36e9-44e6-bd57-d97229a454b8)

One can workaround it by rotating the device to portrait mode.

**Comment by tophf** [comment]
Try [beta](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by tophf** [comment]
I see the same in beta.

@gera2ld, could you look at this? https://github.com/violentmonkey/violentmonkey/blob/7b83beafb63d91d612bc9ba9e0ddfae8cab5a87e/src/options/views/edit/index.vue#L521 Removing `position: static` fixes the issues but IIRC you added it to allow showing the address bar. I only have an emulator and I can't trust it.

**Comment by orionlee** [comment]
I tried Kiwi browser with both released v2.18.0 and beta v2.18.3 on Galaxy Tab S6. The settings tab is fully functional with beta in portrait mode.

- landscape : the script UI (with code/settings/values tab) does not show up when I click a script (both beta and release)
  - I could tell the DOM elements have been created though, because after I click a script and rotate the device to portrait mode, the UI shows up.
- portrait mode:
  - beta: the full UI shows up, and is functional. ([screenshot](https://github.com/violentmonkey/violentmonkey/assets/250644/e2324a74-e5ce-4a88-9a16-3fa8fdaec376))
  - release: it works with UI issues. 
    - When I first click the Values tab, it shows a functional the JSON edit UI ([screenshot](https://github.com/violentmonkey/violentmonkey/assets/250644/afef4e00-c206-470e-ad3a-8d5d41d82326))
      - Onn Firefox for Android, it also shows the JSON edit UI without the Ok/Apply/Cancel button
    - After I click the cancel button, the table UI shows up ([screenshot](https://github.com/violentmonkey/violentmonkey/assets/250644/b566dd79-7ba8-47db-8fe3-7c043f133349))
