### ISSUE TITLE
viewtube userscript is  no longer working with 2.8.8 version on firefox for android nighlty 57

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#209]
viewtube userscript(https://greasyfork.org/en/scripts/2984-viewtube)is no longer working with 2.8.8 version as other user scripts everthing s fine with 2.6.4 version in firefox v57 nighlty for android.
whats wrong with 2.8.8 version?????
can please someone look into the issue??????????

**Comment by ale82to** [comment]
why did u close this bug ,problem is also present on Firefox desktop

**Comment by gera2ld** [comment]
Please do not remove the issue template and fill it.
