### ISSUE TITLE
[BUG] Case-sensitive in the search field?

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2090]
I think it should be a bug. it should not be case sensitive.

For example, I have installed a script call "YouTube test script". I cannot search it with the word "Youtube".

I did not see any search engine do the case-sensitive search. I believe this should be a bug.

Or you might add the option (with syntax) to search it case-insensitive?

**Comment by tophf** [comment]
I have an arguably good solution:
* `text` is case-insensitive regardless of MixedCaseLetters
* `"text"` is case-sensitive, you can combine modes e.g. `"foo" bar`
* `/re/` is case-sensitive
* `/re/i` is case-insensitive
