### ISSUE TITLE
[Feature] Download BETA

### ISSUE THREAD

**Issue by nightznero** [violentmonkey/violentmonkey#2094]
Helloz!

I would like to get option like `Download BETA` as is on Tamper.
![Screenshot_20240505_100638](https://github.com/violentmonkey/violentmonkey/assets/61750641/d0eba30c-5508-4291-9506-bc4c17649abd)
One of my scripts requires this option to properly working and bcs of that I m forced to stick with Tamper.
If Devs would add it into Violent l would really appreciate it and right back to Violent over Tamper.
Best Regards and have sunny day, NIGHTZNERO.

**Comment by tophf** [comment]
It's already reported in #1349.
