### ISSUE TITLE
[Feature] Custom Whitelist (Website Domain) for every userscript

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2096]
**Motivation**

I want to visit some websites which is related to payment etc, like banking, travel ticket, etc.

I have installed many scripts, they apply to all https domains

For daily usage, they are convenient. But I don't want them to disrupt my login and usage in these website.

And I don't want to turn the entire VM on/off cause I want to use the userscripts in my other browser tabs.

**Proposed Solution**

Make a whitelist session in VM option page. So users can type their domains that do not want any exclusion of userscripts.

**Use Cases**

Banking, Travel Ticket, Hotel Booking, etc.

**Comment by cyfung1031** [comment]
> AFAICT this is already implemented, see https://violentmonkey.github.io/posts/smart-rules-for-blacklist/#whitelist-patterns

i am not saying the `@exclude` per script.
I am saying the customized list inputed by the user himself.
it is a setting in VM not in the individual scripts.

**Comment by cyfung1031** [comment]
OK I just found it in the VM page. 
(the link above could not really visualize how to add the whitelist in VM)

Thanks.

**Comment by tophf** [comment]
While the documentation and UI can be improved, AFAICT the functionality itself is already implemented. Maybe you can explain what you want to achieve in more detail.

**Comment by tophf** [comment]
I guess we could rename `Blacklist` to `Blacklist and whitelist` and add 2 simple examples below the input. @gera2ld?

**Comment by gera2ld** [comment]
Yeah the current wording is confusing, we should update it.

**Comment by cyfung1031** [comment]
@tophf  @gera2ld  

In the textbox, I typed
`@match https://*.facebook.com/*`
(I thought like match this url then blacklist)

but in fact it is just `https://*.facebook.com/*`

I feel quite confusing that why blacklist textarea `@match` means `@exclude`
blacklist's exclude = `@exclude https://*.facebook.com/*` = `https://*.facebook.com/*` = blacklist

**Comment by tophf** [comment]
Yes, the documentation and examples can be improved.

input | result
-|-
`*.fb.com` | blacklist this domain pattern (safe)
`https://*.fb.com/*`<br>`@exclude-match https://*.fb.com/*` | blacklist using the match syntax (safe)
`@exclude https://*.fb.com/*` | blacklist using the unsafe syntax which matches `http://fake.com/.fb.com/`

Whitelist means you re-allow something blocked by a bigger pattern like `*` by using `@match` or `@include`:
```
*
@match https://*.fb.com/*
```
