### ISSUE TITLE
[BUG] disable cache of @require

### ISSUE THREAD

**Issue by viocha** [violentmonkey/violentmonkey#2097]
### Problem: 
The required scripts nerver get updated to the latest version after the script was first installed. I can't find any way to update the required resources or disable the internal cache of violentmonkey.

I used the following code to declare the resouces from github.

```js
// @require     https://raw.githubusercontent.com/.......
```

### Expected result:  
The script manager should check for updates of required resources periodically or provide one button to update mannually or provide one option to disable the cache.

#### Environment:
- OS: Windows
- Browser: Chrome 123 
- Violentmonkey Version:

**Comment by tophf** [comment]
It should be fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases), AFAIK. Can you try it?

**Comment by Tamarindo94** [comment]
This is happening to me on windows 10, librewolf v129.0-1 (based on Firefox), Violentmonkey v2.20.0.
The cached required scripts never reload.
Can the issue be reopened?

**Comment by F9y4ng** [comment]
@tophf @derjanb

This problem exists not only on Violentmonkey, but also on Tampermonkey. When auto-updating scripts, if you encounter network issues (especially in mainland China), that cause `@require` content to not download successfully, there is no obvious way to re-download `@require` content. This will cause the code to report errors.

The only way to do this is to change the code version number, save it, and manually update it so that the VM or TM can re-update the code for `@require` to re-download.

**Comment by tophf** [comment]
@F9y4ng, does it help in Tampermonkey if you use Subresource Integrity hashes in the URL?

**Comment by tophf** [comment]
Oh and I guess it would make sense to add `⟳` button in the dependency viewer in the editor to force an update...

**Comment by F9y4ng** [comment]
> @F9y4ng, does it help in Tampermonkey if you use Subresource Integrity hashes in the URL?

No, I'm using Subresource Integrity hashes in my current code and it doesn't help the problem.

> Oh and I guess it would make sense to add ⟳ button in the dependency viewer in the editor to force an update...

Will it be hidden too deep for users to find it? 

The average script user can't even figure out what's causing the problem at all, just that the script is reporting an error. It would be nice if the `@require` failed process could be detected and the download retried automatically. If multiple attempts (such as 3 times) fail, the user will be prompted on the list page to manually update the `@require` resource.

**Comment by JourneyOver** [comment]
Wouldn't mind having a button of some kind to update the cache for the `@require` sources without actually having to edit the url in the `@require`. Tampermonkey does have a way to do this in it's extension that you can update/delete/edit the `@require` sources easily whenever you want -- 
![image](https://github.com/user-attachments/assets/1d438647-f743-4a7c-876c-55ffe0af8e7d)

**Comment by F9y4ng** [comment]
> Wouldn't mind having a button of some kind to update the cache for the `@require` sources without actually having to edit the url in the `@require`. Tampermonkey does have a way to do this in it's extension that you can update/delete/edit the `@require` sources easily whenever you want --

No, if you encounter network issues when auto-updating scripts, `@require` content will not be downloaded successfully, and no buttons will appear at this time. Hopefully, you've encountered this issue and not just guesswork.
