### ISSUE TITLE
[BUG] GM.xmlHttpRequest arraybuffer bug on Brave beta

### ISSUE THREAD

**Issue by TuxedoTako** [violentmonkey/violentmonkey#2098]
There is an issue with responseType: 'arraybuffer' on GM.xmlHttpRequest on Brave beta. This also happens on Tampermonkey: https://github.com/Tampermonkey/tampermonkey/issues/2056 , so it might be an issue on Brave's side.

### Sequence of actions: 
1. Install this userscript:

  ```js
    // ==UserScript==
  // @name         GM.xmlHttpRequest arraybuffer bug
  // @namespace    http://tampermonkey.net/
  // @version      0.0.0
  // @description  Reproduce a bug on brave beta
  // @author       Tuxedo Takodachi
  // @match        https://github.com/*
  // @grant        GM.xmlHttpRequest
  // @grant        GM_registerMenuCommand
  // @connect      www.tampermonkey.net
  // ==/UserScript==

  (function () {
    'use strict';
      debugger;

      GM_registerMenuCommand('test', e => {
          GM.xmlHttpRequest({
              method: "GET",
              url: 'https://violentmonkey.github.io/static/vm-6437e4e5a400c6eff1c23ead4d549b0a.png',
              responseType: 'arraybuffer',
              onload(xhr) {
                  console.log(xhr);
              },
              onerror(e) {
                  console.error(e);
              },
              onabort(e) {
                  console.error(e);
              },
          });
      });
  })();
  ```

2. Reload this page, or open any github.com page
4. Trigger the 'test' action from the extension pop-up

### Problem:

```
TypeError: Failed to fetch
    at yn (injected.js:1:11187)
    at HttpRequested (injected.js:1:12203)
    at injected.js:1:5434
    at p (injected.js:1:2718)
```

This issue isn't propagated to the `onerror` callback.

If `responseType: 'arraybuffer',` is commented out, the request works.

### Expected result:

The request works, or the `onerror` callback is called.

#### Devtools console contents:

```
Greaselion script loaded: githubBase.ts
injected.js:1 TypeError: Failed to fetch
    at yn (injected.js:1:11187)
    at HttpRequested (injected.js:1:12203)
    at injected.js:1:5434
    at p (injected.js:1:2718)
```

#### Environment:
- OS: Windows 10
- Browser: Brave 1.67.78 Chromium: 125.0.6422.41 (Official build) beta (64-bits)
- Violentmonkey Version: 2.18.0, BETA 2.18.3

**Comment by tophf** [comment]
Since it works in Chrome, it must be a bug in Brave.

**Comment by tophf** [comment]
Works for me in Brave 1.52.129, which I had on my PC, gonna update it now...

**Comment by Martii** [comment]
@TuxedoTako 

Nice find... this explains why one of my scripts stopped working in Brave sometime within the last few months... works in any other browser but Brave.

**Comment by tophf** [comment]
Just finished bisecting their nightly builds and found [v1.66.52](https://github.com/brave/brave-browser/releases/tag/v1.66.52) is the first broken release.

**Comment by tophf** [comment]
Judging by the [commit log](https://github.com/brave/brave-core/compare/v1.66.51...v1.66.52) the problem is https://github.com/brave/brave-core/pull/22619

**Comment by Martii** [comment]
@tophf 

I'm running `Version 1.65.132 Chromium: 124.0.6367.202 (Official Build) (64-bit)` though.

**Comment by tophf** [comment]
They may have back-ported the same commit into an older version or the problem in your case is different.

**Comment by Martii** [comment]
Here's where I believe it stopped working for my use case *(have a few newer releases to recheck to be sure but seems about the correct time that the `responseType: 'arraybuffer',` started failing... I'm also using Braves PPA normally but using flatpak so I can swap out versions faster and not corrupt/taint my base system)* :

``` console
$ flatpak remote-info --log flathub com.brave.Browser
        ID: com.brave.Browser
       Ref: app/com.brave.Browser/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 175.2 MB
 Installed: 394.3 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08


    Commit: aff9735714e0d3fab37e952adc55c484eceb20f6b7f7e240f1ebf4bd6bed86d3
   Subject: Update brave.zip to 1.64.113 (29eb9583)
      Date: 2024-03-27 16:49:44 +0000
   
    Commit: 1694228668731a1a2961ac256b05efaa0af9de852f8cb58a39aec44136dff01c
   Subject: Update brave.zip to 1.64.109 (1356ac20)
      Date: 2024-03-20 16:46:18 +0000


$ # Works for below here

$ sudo flatpak update --commit=1694228668731a1a2961ac256b05efaa0af9de852f8cb58a39aec44136dff01c com.brave.Browser
$ # Version 1.64.109 Chromium: 123.0.6312.58 (Official Build) unknown (64-bit)


$ # Stops working below for here

$ sudo flatpak update --commit=aff9735714e0d3fab37e952adc55c484eceb20f6b7f7e240f1ebf4bd6bed86d3 com.brave.Browser
$ # Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) unknown (64-bit)
```

**Comment by tophf** [comment]
The userscript posted here definitely fails because of the commit I found, but indeed there may have been earlier commits that broke this for a while and then something else fixed it. You can try bisecting brave builds yourself like I did here.

**Comment by tophf** [comment]
Ah, sorry, you already found the range: https://github.com/brave/brave-core/compare/v1.64.109...v1.64.113
I don't see anything obvious there though. Might be something in Chromium.

**Comment by Martii** [comment]
Works in actual, current, Chromium though. Checking out older versions of Chromium won't be a quick and easy thing. The script I'm using resembles TuxedoTako simplified version very closely with a different endpoint and it never returns from the call *(slight difference on resultant)*. Perhaps @goodov can utilize my range to assist in https://github.com/brave/brave-browser/issues/38256

I appreciate the look and assistance. Thanks.
