### ISSUE TITLE
[BUG] Import from URL not working when ViolentMonkey is installed on Kiwi browser

### ISSUE THREAD

**Issue by oeloo** [violentmonkey/violentmonkey#2101]
### Sequence of actions: 
1. Install Kiwi browser on Android (https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) and then install ViolentMonkey extension
2. In ViolentMonkey extension: click on '+' icon then 'import from URL'
3. Enter the URL to the userscript 

### Problem:
The userscript you want to import is not being added to your userscript list.
Refreshing the webpage does not show it as well: it has not been imported.

### Expected result:  
Successful import: the userscript you have just imported shows up in the userscript list.

#### Environment:
- OS: Android v13
- Browser: Kiwi browser v124.0.6327.4
- Violentmonkey Version: v2.18.0

**Comment by tophf** [comment]
Can you show the URL? Maybe it's not a direct link to the actual code of the script but to its html page?

**Comment by oeloo** [comment]
You are correct, importing from URL when installed in Kiwi browser works.  I was not properly logged on to have access to the URL, my fault.

**Comment by tophf** [comment]
So I guess the fix here on our side would be to display an error with an excerpt from the response in such cases.

**Comment by oeloo** [comment]
Yes it was on my side, you can close this issue. Thanks for your specif query about the url, that was the mistake I did.
