### ISSUE TITLE
Script not active on drive.usercontent.google.com

### ISSUE THREAD

**Issue by aztecrabbit** [violentmonkey/violentmonkey#2102]
### Sequence of actions: 
1. `@match https://drive.usercontent.google.com/download*`
2. go to that url
3. script not active

### Problem: 
even if `@match` is `*://*/*`

#### Environment:
- OS: Arch Linux
- Browser: Firefox Nightly v127.0a1 (2024-05-05)
- Violentmonkey Version: v2.18.0

**Comment by tophf** [comment]
Please show an example URL where I can test it.

**Comment by tophf** [comment]
If you mean `drive.usercontent.google.com/download` then it responds with `sandbox` CSP, which is a known bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1411641 fixed in Firefox 128 a few days ago.
