### ISSUE TITLE
[BUG] Can't create a new userscript

### ISSUE THREAD

**Issue by GuiReboucas** [violentmonkey/violentmonkey#2108]
### Sequence of actions: 
1. Try to create a new script 
2. Click "New" and "New"
3. "_new" appears in the url but nothing changes 

### Problem: 
Error in trying to create a new userscript
### Expected result:  
Editor for creating the script opens
#### Devtools console contents:
Nothing
#### Environment:
- OS: Windows
- Browser: Firefox 126.0 
- Violentmonkey Version: 2.19.0

**Comment by tophf** [comment]
Works for me. I can't imagine why it wouldn't work. Is there an error in console? What happens if you click `+` in the popup?

**Comment by tophf** [comment]
> but they're not especially useful since the code is minified

They're useful, I regularly use them to find the corresponding source just by looking, so please paste the error here and if it has a call stack please include it too (it may be shown only after you click the triangle icon to the left of the error message).

**Comment by tophf** [comment]
You were right, these aren't helpful because it's from the UI framework, so even if it showed the actual names I wouldn't know what caused it. Apparently there's a bug in our UI code, but so far I couldn't reproduce the problem. I wonder if it occurs only in a container or with a particular setting in Firefox's preferences...

**Comment by gera2ld** [comment]
@colons did you modify the *Custom Script Template* in Settings? It happens when the template is invalid.

Because `script.meta` is set to false here:

https://github.com/violentmonkey/violentmonkey/blob/6de7986d3a844aef11610bfdd3c8e91500d3af82/src/background/utils/script.js#L76

cc @tophf

**Comment by tophf** [comment]
On it!
