### ISSUE TITLE
2.8.9 new rights request

### ISSUE THREAD

**Issue by AL3x3y0** [violentmonkey/violentmonkey#211]
![image](https://user-images.githubusercontent.com/29476322/30519770-268b4fac-9baf-11e7-85a3-7f8111904f3d.png)

> Changing the copied and pasted data

Why and for what?

**Comment by phyber** [comment]
Digging through the recent commits, it looks like this was a fix for a Firefox issue.
https://github.com/violentmonkey/violentmonkey/commit/bc2957437e911869c9d6a76bbe485bdedfd83ede

**Comment by gera2ld** [comment]
For `GM_setClipboard` to work on Firefox. Thanks @phyber .
