### ISSUE TITLE
[BUG] Impossible to access to ViolentMonkey settings from ViolentMonkey current webpage script list

### ISSUE THREAD

**Issue by oeloo** [violentmonkey/violentmonkey#2110]
### Sequence of actions: 
1. Use Kiwi browser on Android (this issue does not happen with Chrome for Windows browser)
2. Click on ViolentMonkey extension Icon
3.Then click on the gear icon to access to ViolentMonkey settings

### Problem: 
"TypeError: Error in invocation of tabs.create(object createProperties, optional function callback): Error at parameter 'createProperties': Error at property 'index': Invalid type: expected integer, found number.
    at Proxy.<anonymous> (background/index.js:1:1463)
    at Object.TabOpen (background/index.js:1:126326)
    at async yc (background/index.js:1:188408)"
![image](https://github.com/violentmonkey/violentmonkey/assets/98819304/d609d1de-7302-4028-b41d-85535163c737)

### Expected result:
The display of the global settings of ViolentMonkey

#### Devtools console contents:
"TypeError: Error in invocation of tabs.create(object createProperties, optional function callback): Error at parameter 'createProperties': Error at property 'index': Invalid type: expected integer, found number.
    at Proxy.<anonymous> (background/index.js:1:1463)
    at Object.TabOpen (background/index.js:1:126326)
    at async yc (background/index.js:1:188408)"

#### Environment:
- OS: Windows 11 (up to date as of now)
- Browser: Kiwi  (up to date as of now
- Violentmonkey Version: 2.19.0

**Comment by tophf** [comment]
I've added a workaround, but it looks like a bug in Kiwi: `index` is undefined, but the [documentation](https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab) says `index` is not optional.

**Comment by oeloo** [comment]
Thanks. Will your workaround for this Kiwi bug be available in the future update of Violentmonkey?

**Comment by tophf** [comment]
Yes.
