### ISSUE TITLE
[BUG] MediaSession API doesn't seem to work

### ISSUE THREAD

**Issue by aminomancer** [violentmonkey/violentmonkey#2113]
### Sequence of actions: 
1. Try this script:

	```js
	// ==UserScript==
	// @name           Better YouTube Media Key Handlers
	// @version        1.0.0
	// @author         aminomancer
	// @namespace      https://github.com/aminomancer
	// @match          http*://www.youtube.*/*
	// ==/UserScript==
	
	navigator.mediaSession.setActionHandler("play", function () {
	  console.log("GREETINGS;");
	});
	```

2. Go to YouTube, hit the "play" media key

### Expected:

The video should not play (there can only be one handler at a time for each action) and "GREETINGS" should be logged in the console.

### Actual:

The script has no effect whatsoever. To be clear, I've tried this with many variations. I've tried all relevant values and combinations for `@run-at`, `@inject-into`, `@grant`, and `@unwrap`. I've tried `unsafeWindow.navigator...` and `window.navigator...` and `navigator...` and none works.

#### Environment:
- OS: Windows
- Browser: Firefox Nightly 128
- Violentmonkey Version: 2.19.0

Thank you!

**Comment by tophf** [comment]
Works for me in Chrome, so I guess Firefox doesn't implement it fully.

**Comment by aminomancer** [comment]
It works fine in Firefox, just not in a userscript. I've tested it in console and I could also test it in a webextension. Is there some reason why it would work elsewhere but not in a userscript?

**Comment by tophf** [comment]
I was wrong, it's the same in Chrome. I was confused by the Play button being ignored in Firefox (I had to restart it).

So apparently youtube overrides your handler and you need to run your code later?

**Comment by tophf** [comment]
In other words, this is how the API is designed and I don't see anything we can do about it.

**Comment by aminomancer** [comment]
Honestly I don't think it's that. That was one of the things I thought might be the issue in my troubleshooting, so I also tried this pattern:

```js
let addListener = () => navigator.mediaSession.setActionHandler("play", function () {
  console.log("GREETINGS;");
});

addListener();

setTimeout(addListener, 10000);
```

**Comment by tophf** [comment]
But your new code works for me and I don't see any other theoretically possible explanation.

**Comment by aminomancer** [comment]
In that case I suppose you're right. It doesn't work for me, but maybe I need to try other asynchronous methods. It feels like youtube's loading is somehow hampered by the timeout, even though it should not be blocking. Maybe the script is causing youtube to set its action handler later than usual.

I'll see what else I can do. Thanks for testing.

**Comment by tophf** [comment]
Judging by the documentation for setActionHandler, this is how it's designed to work. It's not like addEventListener, but like `elem.onclick = foo` which overwrites the old listener.

You'll have to implement cascading manually, e.g.:
```js
const playCallbacks = new Set();
const M = navigator.mediaSession;
M.setActionHandler("play", info => {
  console.log("GREETINGS;");
  for (const fn of playCallbacks)
    try { fn(info); } catch (err) { console.log(err); }
});
M.setActionHandler = new Proxy(M.setActionHandler, {
  apply(fn, thisArg, args) {
    if (args[0] === 'play') playCallbacks.add(args[1]);
    else Reflect.apply(fn, thisArg, args);
  }
});
```

**Comment by aminomancer** [comment]
Thanks! Yeah that makes sense. I won't need cascading since I just want to override nexttrack and previoustrack (youtube's shuffling gets stuck in loops sometimes), but I can do that too with a proxy. By breaking on setActionHandler I found that youtube actually sets the action handlers 3+ times, starting early and continuously attempting it at least 2 times. Kinda weird but I guess that explains it.
