### ISSUE TITLE
Release 2.19.0 for Edge

### ISSUE THREAD

**Issue by tobbexiv** [violentmonkey/violentmonkey#2114]
Hi,

I have seen that release 2.19.0 was release some time ago and is available for Chrome and Firefox. Is there a specific reason why Edge is still stuck on 2.18.0? Would be great if Edge could also get the latest changes.

Thank you and best regards,
Tobias

**Comment by tophf** [comment]
The automatic upload job has failed when 2.19 was released. I've re-tried it now successfully, so it should be published soon.
