### ISSUE TITLE
[Feature] Setting to allow XHR responses to set cookies

### ISSUE THREAD

**Issue by grablair** [violentmonkey/violentmonkey#2118]
**Motivation**
It seems that [this release](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.15.0) (this commit: https://github.com/violentmonkey/violentmonkey/commit/712df2b67a31d66ca0d93b65549045a7c3ebd535) last year was made to improve parity with Tampermonkey, which changed how it allows XHR responses to set cookies. I have been using an old TM version until recently, when I upgraded from TM 5.1.1 to 5.2.0, which included the change in behavior I am referring to (TM 5.1.1 did not filter out `set-cookie` headers). In response, I started looking for other userscript managers to determine if that behavior change is isolated to TM, but it seems VM also adopted the same behavior change.

This is breaking many of the userscripts used within the company I work for. All of our internal sites perform SSO authentication in the following way:

1. Go to target URL
2. Service checks to see if there are SSO cookies present. If so, validates them and then determines authZ. If authorized, process request.
3. If the SSO cookies are not present, or if they are expired, then the target site responds with a `set-cookie` header, containing an SSO forgery protection token. It then redirects the user to our internal auth service. 
4. The internal auth service authenticates the user (via credentials or session cookies), generates a token for the initial target URL, and then redirects the user back to the initial target URL with the token added to the request.
5. The initial site takes the token from the auth request and stores it in a cookie, and redirects it to the original URL, without the token in the request.
6. Return to step 2 (since the SSO tokens are now present and valid, the request is then processed)

By filtering out `set-cookie` headers, we just get put on an infinite loop, since no SSO cookies would have been set. You can temporarily alleviate this by going to the target site manually, but our SSO tokens don't have a long liveness (5-10 mins) before they need to be refreshed, so it won't last very long. Additionally, since we have hundreds of internal sites which each store their own SSO tokens, the user would have to visit every one, every 5-10 minutes.

**Proposed Solution**

Short-term: some global setting that allows cookies to be set by background XHR response headers. That should unblock the people in my company.

Long-term: not sure...

There's a possibility I am just missing some setting, and I apologize if that is the case!

The change to remove the `set-cookie` header was a fairly big backwards-incompatible change, though I do understand the motive. Are there any processes in place for the various userscript manager teams to come to consensus on these types of behaviors?

**Use Cases**
Covered in the motivation section above

**Comment by tophf** [comment]
Quoting myself from the PR:

> It should be an option in GM_xmlhttpRequest, not in the extension, otherwise it'll break scripts that don't expect it. And I'm not convinced we should add it. Try opening an issue in Tampermonkey, its author likes to add features, so if we like his solution we can implement it here as well.

Also, why don't you write a separate extension instead of relying on userscripts?

@gera2ld, WDYT?

**Comment by grablair** [comment]
Thanks for your swift response, @tophf !

---

> It should be an option in GM_xmlhttpRequest, not in the extension

Not against this at all. That was what I initially intended but I wasn't sure how maintainers would feel, so I figured I'd publish the "simplest" solution, which took 10 minutes to implement, and then get input on it.

> otherwise it'll break scripts that don't expect it

Didn't the change from last year already break scripts that _did_ expect it? (https://github.com/violentmonkey/violentmonkey/issues/2118)

> Try opening an issue in Tampermonkey, its author likes to add features, so if we like his solution we can implement it here as well.

I intend on doing so. I came here first because this is a true open source project that I can actually contribute to rather than just ask for features from. 

> Also, why don't you write a separate extension instead of relying on userscripts?

The company I work for is Amazon. There are thousands of internal websites owned and maintained by thousands of different teams. There are a plethora of userscripts in use, with many different goals and purposes, and that have been in use for many years to create usecase-specific modifications to websites owned by other teams. Should internal teams write better websites? Yes, but I can't control what other teams prioritize. Some userscripts also exist to improve internal sites that are in keeping-the-lights-on mode. 

Writing our own extensions for each usecase isn't really feasible, and creating a monolithic extension with all these improvements is not the right move either.

Creating an Amazon-internal userscript manager isn't a bad idea, but I also believe in the greater good open source projects provide, so would rather spend my time trying to find ways to improve the capabilities for all users. There are surely other large companies whose employees use userscripts who also have similar SSO authN processes, which would also benefit from open-source improvements to support those usecases.

**Comment by tophf** [comment]
> Didn't the change from last year already break scripts that did expect it? 

FWIW, I can argue the old behavior was an oversight, a bug, which you've abused :-)

**Comment by tophf** [comment]
> There are surely other large companies whose employees use userscripts who also have similar SSO authN processes

Sounds plausible to me.

I guess the solution may be either something explicit like `retainCookies: boolean` or an indirect `firstParty: true` or smth.

**Comment by grablair** [comment]
FYI: I opened a similar ticket to Tampermonkey: https://github.com/Tampermonkey/tampermonkey/issues/2094. The way this process breaks there is actually slightly different.

---

> FWIW, I can argue the old behavior was an oversight, a bug, which you've abused :-)

Perhaps ;) doesn't mean nothing should be done to help users who _did_ rely on the functionality. (what a convoluted sentence).

> I guess the solution may be either an explicit retainCookies: true or an indirect firstParty: true, naming TBD.

Sounds good to me. I suppose we can wait and see what the folk(s) over at TM do with my report and touch back on this then?

**Comment by tophf** [comment]
A workaround may be possible, actually. Violentmonkey passes the real `set-cookie` headers to GM_xmlhttpRequest's callbacks in `responseHeaders` property, so you can reuse them in subsequent requests explicitly as `{headers: {cookie: '........'}}`, the only inconvenience is that you'll need to parse the header, but it's probably trivial because you only need to extract the name/value pair.

**Comment by gera2ld** [comment]
Oh, I didn't expect the change. I prefer to retain cookies by default in non-anonymous mode. Or at least we should add an option to retain the cookies.
To be honest, it's more intuitive to me to update the cookies. I never expect a case where we send existing cookies but ignore the updates. It's very common that some cookies are one-time and need to be updated after each request, e.g., csrf-token.

**Comment by tophf** [comment]
> I prefer to retain cookies by default in non-anonymous mode

The problem is that we have `non-anonymous mode` enabled by default for cross-origin requests, which contradicts behavior of the modern web platform for cross-origin requests i.e. `fetch` default is `credentials: 'omit'`.

**Comment by gera2ld** [comment]
IMO `GM_xmlhttpRequest` is an API to allow a userscript to send a request without being limited by the same-origin policy, so it doesn't matter how `fetch` works by default, it's more important for `GM_xmlhttpRequest` to keep the original behavior. Authors can choose to use `fetch` instead if they want.

Any concerns if we only ignore `set-cookie` in `anonymous` mode or with an explicit option?

**Comment by tophf** [comment]
The problem is mentioned in #1835: userscripts need make a cross-origin request (i.e. `fetch` can't be used) without affecting the browser's cookie state e.g. to make a request to the site on behalf of a different user.

**Comment by tophf** [comment]
> or with an explicit option

That's what I suggested above in https://github.com/violentmonkey/violentmonkey/issues/2118#issuecomment-2170465930

**Comment by gera2ld** [comment]
> without affecting the browser's cookie state e.g. to make a request to the site on behalf of a different user.

This appears to be a new feature rather than a change to the default behavior. Therefore, I suggest adding an explicit option for it.

**Comment by tophf** [comment]
Maybe, but I'd like to wait a little to see what Tampermonkey does, there's no rush anyway because this issue is the only complaint since the new behavior was implemented a year ago, so I'm not sure the original behavior of GMxhr makes sense.

**Comment by tophf** [comment]
I think we should retain the cookies only for this userscript's subsequent GMxhr by default, so there may be no need for an additional option.

**Comment by tophf** [comment]
> Tampermonkey always stores received cookies in the browser's cookie store except when `anonymous` is set.

So assuming this is indeed so, my guess in #1835 was wrong and there is another way to make sure that script works, which we need to find, while restoring the original historical behavior of GMxhr here.

**Comment by tophf** [comment]
Indeed, Tampermonkey now breaks that script, so I guess it further shifts the balance in favor of restoring the original behavior.
