### ISSUE TITLE
[BUG] 2.19.2 works fine in FF, refuses to install on Edge Chromium Canary 128.0.2672.0

### ISSUE THREAD

**Issue by 514guy** [violentmonkey/violentmonkey#2128]
### Sequence of actions: 
1. Not a function of scripts.
2.
3.

### Problem: 
Error on install unpacked extension is in Manifest.json:
`ErrorVariable __MSG_updateScriptsInTab__ used but not defined.`

### Expected result:  
Installs, as on Firefox.

#### Devtools console contents:
as above error
#### Environment:
- OS: Windows
- Browser: Edge Chromium 128.0.2672.0 
- Violentmonkey Version: Currently 2.19.1, since I cannot install 2.19.2.

**Comment by tophf** [comment]
@gera2ld, can you cancel 2.19.2 in web store?

**Comment by yomtovkamhi** [comment]
[violentmonkey_2024-06-25_17.01.27 (2).zip](https://github.com/user-attachments/files/15979833/violentmonkey_2024-06-25_17.01.27.2.zip)

**Comment by gera2ld** [comment]
SFLR 2.19.3 is already published.
