### ISSUE TITLE
[BUG] GM_openInTab with option "insert" does not open in tab next to script tab

### ISSUE THREAD

**Issue by chasingdragonflies** [violentmonkey/violentmonkey#2134]
Script:
```Javascript
const id1 = GM.registerMenuCommand('Open GOM', onClick, { autoClose: true })

function onClick(event) {
  var knnlink = window.location.href
  var gomlink = knnlink.replace("mozilla.org/knn/", "mozilla.org/gom/")
  let tabControl = GM.openInTab(gomlink, { insert: true, active: true, pinned: false})
}
```

### Sequence of actions: 
1. Open 5 different tabs
2. Run script in 2nd tab and open menu button of the VM script.

### Problem: 
It will open a new tab after the last tab and will become the 6th tab.

### Expected result:  
It should insert new tab after the 2nd tab.

#### Environment:
- OS: Android
- Browser: Firefox Android 127.0.2 
- Violentmonkey Version: 2.19

**Comment by tophf** [comment]
Since it works in a desktop Firefox for me, evidently it's a bug in Firefox for android.

**Comment by tophf** [comment]
These are entirely different actions: extensions API vs the built-in UI.

**Comment by tophf** [comment]
https://bugzil.la/1906411
