### ISSUE TITLE
[Feature] make one userscript having both page part and isolated content part 

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2138]
**Motivation**

My script is mostly working on page context, but sometime i want to use GM functions which are only in GM isolated environment.

I cannot access GM functions if i set the script with `@inject-into page`
(For example, `GM.setValue` and `GM.getValue` are not useable so the script settings can be only stored in `localStorage`)

Currently we can use GM isolated environment (delete `@inject-into page`) and inject the script into the page. This is working but have two problems.

Problem1. The script is dynamically injected into the page, so we cannot debug it easily. If we use js file, we can click the js filename with line number to debug in devtools. 

Problem2. The script might not be immediately run in document-start as we use document.createElement('script') and then append to the documentElement.  In document-start, it is the very beginning execution that the documentElement can be null

We cannot control when the injected script will be executed. 

**Proposed Solution**

We should be able to define different contexts in the same userscript. I would suggest the following 

```js
// ==UserScript==
// @name        New script
// @namespace   abc.com
// @match       https://....
// @grant       GM_openInTab
// @version     1.0
// @author      -
// ==/UserScript==

({
    "page": function() {
            console.log("this is executed from page context")
            console.log("GM_openInTab is NOT defined", `${typeof GM_openInTab} is undefined`);
    },
    "content": function() {
          console.log("this is executed from isolated content context");
          console.log("GM_openInTab is defined", `${typeof GM_openInTab} is function`);
    },
    "context-menu": function() {
        GM_openInTab("https://website.net");
    }
})

``` 

VM shall prepare the static js file for injection so that the script is debuggable. (Including refresh of the page)

If we consider `@require` as well.

```js
// ==UserScript==
// @name        New script
// @namespace   abc.com
// @match       https://....
// @grant       GM_openInTab
// @version     1.0
// @author      -
// ==/UserScript==

[
    {
        "require": ["url1", "url2", ...],
        "page": function () {
            console.log("this is executed from page context")
            console.log("GM_openInTab is NOT defined", `${typeof GM_openInTab} is undefined`);
        }
    },
    {
        "require": ["url1", "url2", ...],
        "content": function () {
            console.log("this is executed from isolated content context");
            console.log("GM_openInTab is defined", `${typeof GM_openInTab} is function`);
        },
    },
    {
        "context-menu": function () {
            GM_openInTab("https://website.net");
        }
    }
]

``` 

As a proper javascript file, you can also define `GM_inject` so that it will be `GM_inject({...})` or `GM_inject([{...},{...}])`
if `@grant GM_inject` is specified, the GM_inject must be called in the top-level without `async/await`

**Use Cases**

**Comment by tophf** [comment]
> Problem1. The script is dynamically injected into the page, so we cannot debug it easily. If we use js file, we can click the js filename with line number to debug in devtools.

I always debug it easily and click the js filename to open this exact place in devtools editor.

> Problem2. The script might not be immediately run in document-start as we use document.createElement('script') and then append to the documentElement. In document-start, it is the very beginning execution that the documentElement can be null

No, it can never be null in Violentmonkey, which injects only after documentElement appears.

---

I don't see a convincing example of why this feature is necessary.

**Comment by tophf** [comment]
> I cannot access GM functions if i set the script with @inject-into page

Why? It works for everyone else.

> The script is dynamically injected into the page, so we cannot debug it easily

If you mean your script creates a new script element, then simply add a `// #sourceURL` comment like Violentmonkey does. This script won't be able to use GM functions directly, indeed, but you can use messages via `CustomEvent` with a random id to avoid collisions.

**Comment by tophf** [comment]
All these are standard features, so there are lots of examples. In short it'll be something like this:

```js
const eventId = 'foo' + Math.random();
scriptElem.textContent = `(${(eventId) => {
  addEventListener(eventId, e => {
    console.log(e.detail);
    dispatchEvent(new CustomEvent(eventId + '*', {detail: {foo: 2}}));
  });
}})(${eventId})
// #sourceURL=cyfung://name/file.js
`;
.........
addEventListener(eventId + '*', e => console.log(e.detail));
dispatchEvent(new CustomEvent(eventId, {detail: {foo: 1}}));
```

**Comment by tophf** [comment]
There was a typo in my code, `#` and ` ` should be swapped like this: `//# sourceURL=`

**Comment by cyfung1031** [comment]
@tophf 


The file link would be different for `foo:2` among `@inject-into page` and `@inject-into content`.
Is this intended behavior? 




```js
// ==UserScript==
// @name        New script github.com
// @namespace   Violentmonkey Scripts
// @match       https://github.com/violentmonkey/violentmonkey/issues/2138*
// @grant       none
// @version     1.0
// @author      -
// @description 7/9/2024, 6:40:43 PM
// @inject-into content
// @grant       GM_openInTab
// @grant       GM_addElement
// ==/UserScript==

document.myVar = (document.myVar||0) | 1;

const eventId = 'foo' + Math.floor(Math.random() * Date.now()); 
const textContent = `(${(eventId) => {

  document.myVar = (document.myVar||0) | 2;
  addEventListener(eventId, e => {
    console.log(e.detail);
    console.log('page')
    dispatchEvent(new CustomEvent(eventId + '*', {detail: {foo: 2}}));
  });
}})("${eventId}")
//# sourceURL=cyfung://name/myfile.js
`;

GM_addElement('script', {
  textContent: textContent
}); 

addEventListener(eventId + '*', e => console.log(e.detail));
dispatchEvent(new CustomEvent(eventId, {detail: {foo: 1}}));

console.log('content')
```

----------

`// @inject-into content`

<img width="373" alt="Screen Shot 2024-07-09 at 19 10 52" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/af61fe4f-8586-4609-a87d-800f09aab988">


`// @inject-into page`

<img width="369" alt="Screen Shot 2024-07-09 at 19 11 15" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/2315d403-c59c-43d1-876a-eabac9178ae0">

**Comment by tophf** [comment]
Violentmonkey exports `console.log` from the content script in Firefox to give userscripts access to the original function not spoofed by the web page or other userscripts. Apparently Firefox uses its original source, not the caller.
