### ISSUE TITLE
Magic TLD support in Violentmonkey

### ISSUE THREAD

**Issue by eberhardweber** [violentmonkey/violentmonkey#214]
### What is the problem?

Scripts with the .tld suffix (also called "Magic TLD") in them do not currently seem to work with Violentmonkey. It seems VM might lack an implementation similar to Greasemonkey's [Magic TLD](https://wiki.greasespot.net/Magic_TLD).

The utilization of .tld is often something like this (eBay and Google would be other good examples):
`// @include          *://*.amazon.tld/*`

### How to reproduce it?
1. Install and activate a script with a Magic TLD in it, like [Amazon Smile Redirect](https://greasyfork.org/en/scripts/33073-amazon-smile-redirect/code)
2. Go to one of the TLDs
3. No redirection happens, i.e. magic TLD doesn't seem to activate

### What is the expected result?

Magic TLD support would be really cool for script authors!

### What is the actual result?

.tld doesn't seem to be supported right now

**Comment by gera2ld** [comment]
This feature has increased the package size for ~40KB. :worried: Maybe I should make it optional.
