### ISSUE TITLE
[BUG] @require never reloads

### ISSUE THREAD

**Issue by personalmountains** [violentmonkey/violentmonkey#2145]
Windows 10, Firefox 128.0, Violentmonkey 2.20.0

It looks like #2097 was never fixed properly. I can't find any way to reload `@require` directives from localhost. It used to be that saving a dummy edit in the script and reloading the page would refresh the dependencies, but not for the past few weeks. Going in the `@require` tab and clicking the script URL shows the outdated version. Clicking the arrow opens the script in a new tab with the (obviously) correct version.

Would it be possible to permanently disable caching of all resources on `127.0.0.1` and `localhost`?

**Comment by tophf** [comment]
#2097 was about caching when updating and it's already fixed for local URLs. The editor wasn't fixed.

**Comment by personalmountains** [comment]
I just tried 2.20.2 and it seems to be reloading `@require` resources correctly when saving from the editor. Thanks for that.

However, just reloading the page doesn't reload the resources, it still requires a dummy edit. Would it be possible to permanently disable caching of all resources on `127.0.0.1` and `localhost` and fetch the resources every time a page is refreshed?

**Comment by tophf** [comment]
I don't think so, because it would require synchronous blocking XMLHttpRequest in the background script, which is only possible in ManifestV2 and anyway it's terrible for performance as all the other requests would be paused for the duration from any other script and even Violentmonkey's UI would be blocked.

**Comment by tophf** [comment]
Correction: the synchronous XHR is only necessary with synchronous page mode in ManifestV2. Anyway, this approach won't work in ManifestV3 where the scripts are registered in the internal API when saving/updating.
