### ISSUE TITLE
[BUG] ViolentMonkey does not run on IDNs

### ISSUE THREAD

**Issue by SedapnyaTidur** [violentmonkey/violentmonkey#2149]
### Sequence of actions: 
1. Open this website https://한국인터넷정보센터.한국/fileDownload/webzine/201407.pdf
2.
3.

### Expected result:  
VM runs on websites with an international domain name.
#### Environment:
- OS: Android
- Browser: Firefox 128.0.1 
- Violentmonkey Version: 2.20.0

**Comment by tophf** [comment]
It actually works on normal pages:

![image](https://github.com/user-attachments/assets/2fd1cb4a-6dbe-4374-b483-c5c85d59039c)

The problem is that Firefox's PDF viewer doesn't allow any extensions, you can see the same in https://pdfobject.com/pdf/sample.pdf

**Comment by SedapnyaTidur** [comment]
Well one more thing, is there a plan to support about:blank like TamperMonkey and FireMonkey do? It can be used by a userscript to show a settings/preferences page.

**Comment by tophf** [comment]
I don't know what you mean, please open a new issue and show an example of code, a screenshot, etc.

**Comment by SedapnyaTidur** [comment]
Not sure about that it is just a very minor issue. What i meant was `@match about:blank` support.

**Comment by tophf** [comment]
I still don't understand, please open a new issue and show an example of code, a screenshot, etc.
