### ISSUE TITLE
White bar/Violentmonkey 2.8.9

### ISSUE THREAD

**Issue by KingThunder** [violentmonkey/violentmonkey#215]
### What is the problem?
This white bar when i click on the icon.
### How to reproduce it?
1. Put Violentmonkey on ">>"
2. Click on Violentmonkey

### What is the expected result?
To show it normally

### What is the actual result?
This
![sem titulo1](https://user-images.githubusercontent.com/8484744/30696130-ee293af2-9eb0-11e7-95ed-691890a0d67a.png)
![sem titulo](https://user-images.githubusercontent.com/8484744/30696129-ee27d9a0-9eb0-11e7-9935-4090f5b1ad03.png)

### Environment
- Browser: Firefox Nightly
- Browser version: 57.0a1 (2017-09-20) (64-bit)
- Violentmonkey version: 2.8.9
- OS: Windows 7 x64

**Comment by gera2ld** [comment]
Closing since this is a [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1373490) [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1387615).
