### ISSUE TITLE
[BUG] GM.info.platform gets the wrong browser version in MAXTHON 

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [violentmonkey/violentmonkey#2150]
### Problem: 

GM.info.platform gets the wrong browser version in MAXTHON, `browserVersion` should be `109.0.0.0`.

**GM.info.platform**:
```json
{
    "arch": "x86-64",
    "os": "win",
    "browserBrand": "Chromium",
    "brand": "Chromium",
    "browserName": "chrome",
    "name": "chrome",
    "browserVersion": "7.2.2.3200",
    "version": "7.2.2.3200"
}
```

**navigator.userAgentData**:
```json
{
    "brands": [
        {
            "brand": "Chromium",
            "version": "109"
        },
        {
            "brand": "Not_A Brand",
            "version": "99"
        }
    ],
    "mobile": false,
    "platform": "Windows"
}
```
#### Environment:
- OS: Windows11
- Browser: MAXTHON 7.2.2.3200 (Chromium 190.0.0.0)
- Violentmonkey Version: BETA v2.20.1

**Comment by tophf** [comment]
The version of Maxthon is 7.2.2.3200, so the result is correct.

**Comment by tophf** [comment]
That said, the brand is incorrect, so I wonder if we should expose both versions: from the brand and from navigator.userAgent...

**Comment by tophf** [comment]
Another problem is deciding whether we want to expose the values obtained in the background script of the extension or from the extension's content script in the tab. The latter will match the devtools' network conditions override that a developer may want to customize during tests...

**Comment by tophf** [comment]
FWIW, I don't really see the need for exposing `platform`, I haven't found any meaningful example after running a search in 100,000 scripts on greasyfork...

**Comment by Xia0xia0Xia0** [comment]
In Tampermonkey 5.1.1, GM.info.userAgentData returns the same data as navigator.userAgentData. The userAgent data obtained from the extension's API (which is not affected by other extensions that modify the UA) is correct for the TM, but not for the VM.

If you think this is not an ISSUE, please close it. 

Thank you for your reply.

**Comment by tophf** [comment]
`browserVersion` contains the version of the browser, not the brand's version. This is the intended behavior.

The next beta will also add `GM.info.userAgentData`, which will contain the safe data values of the tab's `navigator.userAgentData` without Tampermonkey's additions (architecture and bitness), because we already provide those in `GM_info.platform`.

**Comment by Xia0xia0Xia0** [comment]
> The userAgentData object will be present only if the browser actually has it, because I don't think it's a good idea to provide an incomplete and unreliable fake object the way TM does it.

I think Tampermonkey only used `navigator.userAgentData`'s JSON format, because in Firefox and Safari use Tampermonkey to output `GM.info.userAgentData` in a similar format to `navigator.userAgentData` in Chrome, so it should only use a similar JSON structure, not the value of `navigator.userAgentData` directly.

**Comment by tophf** [comment]
I think you misunderstood that quote: it's about browsers that don't have a built-in `navigator.userAgentData`.

**Comment by tophf** [comment]
To elaborate: there's no reliable way of making that information in unsupported browsers and there's no official polyfill for navigator.userAgentData, so Tampermonkey uses its own algorithm of guessing those values.

**Comment by Xia0xia0Xia0** [comment]
I don't think you understood what I meant, perhaps I wasn't clear?

Tampermonkey's `GM.info.userAgentData` is an object that uses the JSON format of `navigator.userAgentData`, not NavigatorUAData data structure.

Tampermonkey `GM.info.userAgentData` in Firefox：
![screenshot_2024-07-28_20-31-47](https://github.com/user-attachments/assets/416e2eb8-d50f-4991-98c5-d46387876ad6)

**Comment by tophf** [comment]
I understood you, but I don't see how it's related to what I wrote.

**Comment by Xia0xia0Xia0** [comment]
Hmmm... TM's `GM.info.userAgentData` can get the real browser information, and won't be affected by other extensions (e.g. User-Agent Switcher and Manager) modifying the browser's UA information. I guess the same goes for VM's `GM.info.platform`.

Back to this ISSUE, the browser information returned by the VM's `GM.info.platform` is missing the brand version, which should be more important than the browser's own version. After all, the brand version affects the compatibility of scripts and styles.

That's what I'm trying to say. I'm sorry that my English is not very good and maybe it will cause you misunderstanding.

**Comment by tophf** [comment]
Sounds like what I wrote in my first comments. To reiterate: 

> The next beta will also add GM.info.userAgentData, which will contain the safe data values of the tab's navigator.userAgentData

**Comment by Xia0xia0Xia0** [comment]
BTW. I found this.

![screenshot_2024-07-28_20-57-05](https://github.com/user-attachments/assets/bacf6f45-6484-46d3-9a1a-e2b602def514)

When will the MV3 compatible version of VM be released?

**Comment by tophf** [comment]
I don't know and there's a separate issue for that.

**Comment by Xia0xia0Xia0** [comment]
> Sounds like what I wrote in my first comments. To reiterate:
> 
> > The next beta will also add GM.info.userAgentData, which will contain the safe data values of the tab's navigator.userAgentData

It would be nice to have the same output in both Chrome and Firefox as TM, it would save a lot of work (just for me 😛 ).

**Comment by tophf** [comment]
As I explained two times: there's no reliable way of making that information in unsupported browsers and there's no official polyfill for navigator.userAgentData, so Tampermonkey uses its own algorithm of guessing those values. Violentmonkey can't just steal that algorithm.

**Comment by tophf** [comment]
...and if write our own algorithm or use someone else's polyfill, it will be incompatible with Tampermonkey. You can encourage browser makers to implement this API.

**Comment by Xia0xia0Xia0** [comment]
Well, just implement your current plan for the time being.

Hope to see Violentmonkey (MV3) released soon.

Thanks for your patience and replies.

**Comment by Xia0xia0Xia0** [comment]
Hi, @tophf 

[BETA v2.20.2](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.20.2) does not seem to solve the problem of not being able to obtain the real brandVersion. GM_info.userAgentData still obtains a value that can be forged and modified, but GM_info.platform still cannot obtain the real brandVersion in MAXTHON. 

So how should I obtain the real brandVersion that cannot be forged and modified through the Violentmonkey API?

**Comment by tophf** [comment]
Use GM_info.userAgent or GM_info.userAgentData.

**Comment by tophf** [comment]
> GM_info.userAgentData still obtains a value that can be forged and modified

What do you mean?

**Comment by Xia0xia0Xia0** [comment]
The brands value obtained by GM_info.userAgent or GM_info.userAgentData will be modified by other extensions, so the real value cannot be obtained.

**Comment by tophf** [comment]
Looks like you misunderstood the description of GM_info.userAgent and GM_info.userAgentData.

Only the physical user explicitly and knowingly can open devtools or about:config and change the data there. Other extensions can't change them unless they use chrome.debugger API that's only allowed for special debugging extensions in the web store and it shows a warning in the entire browser all the time it's being used (this API allows doing almost everything devtools itself can do).

The same applies to `GM_info.platform` in Chrome, the only difference being that to change it the user will have to use devtools for the background script of the extension.

In Firefox there's an unforgeable `browser.runtime.getBrowserInfo` which we use for GM_info.platform, but it's not implemented in Chromium browsers.

**Comment by Xia0xia0Xia0** [comment]
> Only the physical user explicitly and knowingly can open devtools or about:config and change the data there. Other extensions can't change them unless they use chrome.debugger API that's only allowed for special debugging extensions in the web store and it shows a warning in the entire browser all the time it's being used (this API allows doing almost everything devtools itself can do).

Extension `User-Agent Switcher and Manager` can modify GM_info.userAgent and GM_info.userAgentData.

But the value obtained by GM_info.platform will not be affected by DevTools or other extensions (such as `User-Agent Switcher and Manager`), but it does not provide brand and brandVersion information.

I don’t know if I described it clearly.

**Comment by tophf** [comment]
> Extension User-Agent Switcher and Manager can modify GM_info.userAgent and GM_info.userAgentData

It can't, I've just verified.

> But the value obtained by GM_info.platform will not be affected by DevTools

It will be influenced by devtools in the background script as I described above.

**Comment by Xia0xia0Xia0** [comment]
> It can't, I've just verified.

It worked after I cleared my browser cache and restarted it, it only affects it if you change it through DevTools, `User-Agent Switcher and Manager` doesn't work for it anymore. It's weird.

Are these APIs GM_info.userAgent and GM_info.userAgentData also provided in Firefox and Gecko-based browsers?

**Comment by tophf** [comment]
> User-Agent Switcher and Manager doesn't work for it anymore.

This is the correct behavior, because this extension doesn't use chrome.debugger API. If what you described were true, it would be a critical bug in the browser's implementation of security boundary for extensions.

> GM_info.userAgent and GM_info.userAgentData also provided in Firefox and Gecko-based browsers?

* userAgent is a safe copy of navigator.userAgent, so it's implemented in all browsers.
* userAgentData is a safe copy of navigator.userAgentData, so it's only implemented in Chromium-based browsers.

**Comment by Xia0xia0Xia0** [comment]
Thanks for your help, all my questions have been answered. 👍

**Comment by F9y4ng** [comment]
> Hmmm... TM's `GM.info.userAgentData` can get the real browser information, and won't be affected by other extensions (e.g. User-Agent Switcher and Manager) modifying the browser's UA information. I guess the same goes for VM's `GM.info.platform`.
> 
> Back to this ISSUE, the browser information returned by the VM's `GM.info.platform` is missing the brand version, which should be more important than the browser's own version. After all, the brand version affects the compatibility of scripts and css.
> 
> That's what I'm trying to say. I'm sorry that my English is not very good and maybe it will cause you misunderstanding.

The browser information obtained by extensions is not absolutely correct. This is especially true for unofficial or third-party forkes of the Chromium browser, whose developers don't follow the agreed-upon data structures for defining browser information, but instead arbitrarily modify browser brand and brand version information. This can cause extensions to fetch browser information that is not correct. This is the case with Maxthon as you mentioned. 

So i think @tophf is right about that.

**Comment by tophf** [comment]
GM_info.platform.browserVersion in Chromium-based browsers is parsed from navigator.userAgent of the background script, not from navigator.userAgentData.brands, because it's a browserVersion, not browserBrandVersion. In other browsers we use browser.runtime.getBrowserVersion, which is implemented only in Gecko/Firefox, AFAIK, and potentially some obscure browsers like Orion.

**Comment by tophf** [comment]
Correction: in modern Chromium-based browsers [we use](https://github.com/violentmonkey/violentmonkey/blob/e5a9f063a37102b1ebc44eac15caab29c3aeeed5/src/background/utils/ua.js#L29) navigator.userAgentData.getHighEntropyValues(['uaFullVersion']).

**Comment by F9y4ng** [comment]
> Edit: in modern Chromium-based browsers [we use](https://github.com/violentmonkey/violentmonkey/blob/e5a9f063a37102b1ebc44eac15caab29c3aeeed5/src/background/utils/ua.js#L29) navigator.userAgentData.getHighEntropyValues(['uaFullVersion']).

Hi @tophf, 

`uaFullVersion` is Deprecated. see [#uafullversion](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues#uafullversion). `fullVersionList` should be used instead.

And MAXTHON return navigator.userAgentData.getHighEntropyValues(['fullVersionList']) like this:

```JSON
{
    "fullVersionList": [
        {
            "brand": "Chromium",
            "version": "7.2.2.3200"
        },
        {
            "brand": "Not_A Brand",
            "version": "99.0.0.0"
        }
    ]
}
```

I think this is very irresponsible brand information. The correct brand information should be:

```JSON
{
    "fullVersionList": [
        {
            "brand": "Maxthon",
            "version": "7.2.2.3200"
        },
        {
            "brand": "Chromium",
            "version": "109.0.0.0"
        },
        {
            "brand": "Not_A Brand",
            "version": "99.0.0.0"
        }
    ]
}
```

Of course, this has nothing to do with the extension itself, as I mentioned above, it's a problem caused by the browser developers.

**Comment by F9y4ng** [comment]
Hi, @tophf

After I tested the v2.20.2 BETA today, I suggest to restore the original data structure of `GM_info.platform`:
```JSON
{
    "arch": "x86-64",
    "os": "win",
    "browserBrand": "Brave",
    "brand": "Brave",
    "browserName": "chrome",
    "name": "chrome",
    "browserVersion": "127.0.0.0",
    "version": "127.0.0.0"
}
```
Even with the addition of the two new APIs `GM_info.userAgent, GM_info.userAgentData`, it's best to keep `GM_info.platform` unchanged because the data structure of `GM_info.platform` changed in v2.20.2 BETA:
```JSON
{
    "arch": "x86-64",
    "os": "win",
    "browserName": "chrome",
    "browserVersion": "127.0.0.0"
}
```
It lost some attribute data, which meant that much of the previous code had to be changed with it. Thanks.

**Comment by tophf** [comment]
I've removed those aliases, because no one used them.

**Comment by F9y4ng** [comment]
> I've removed those aliases, because no one used them.

😭 I used them. At least keep one of `brand` and `browserBrand`.

**Comment by tophf** [comment]
No, there's no point now that userAgentData is present.

**Comment by F9y4ng** [comment]
when someone use VM2.20.0 or ealier, sameone use VM2.20.2 and later， my previous code would have reported errors, and I would have needed to add a lot of extra work to make it compatible with two different versions of the VM, the changes to the original API were very unreasonable.

**Comment by tophf** [comment]
Simply don't support beta versions?

**Comment by tophf** [comment]
> a lot of extra work

Really?

**Comment by F9y4ng** [comment]
> Really?

Okay, you win, I'll go upgrade the code compatibility. 😫

**Comment by tophf** [comment]
BTW userAgentData itself is experimental and is only supported in Chromium, because this API is inherently problematic according to Mozilla and Apple.

**Comment by F9y4ng** [comment]
> > a lot of extra work
> 
> Really?

Because I not only need to be compatible with the Violentmonkey, but also the Tampermonkey, and also be compatible with other script managers that do not provide APIs such as Userscirpts, Greasemonkey, Scirptcat, etc. So a lot of extra work. Anyway, I've got plans to rewrite that part of the functionality.

**Comment by tophf** [comment]
I forgot to mention that now `browserName` is equal to `browserBrand`, which is why the latter is redundant. You can see it in the [latest CI build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml).

**Comment by F9y4ng** [comment]
> I forgot to mention that now `browserName` is equal to `browserBrand` in browsers that don't have getBrowserInfo(), i.e. in Chromium-based browsers, which is why `browserBrand` is redundant. You can try the [latest CI build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml).

MAXTHON / VM2.20.2 BETA / injected-web.js reports error.

Why not just use `getHighEntropyValues([
"architecture",
"bitness",
"formFactor",
"fullVersionList",
"model",
"platformVersion",
"wow64"])` to return all `getHighEntropyValues`'s values (and let the script author choose which values ​​to use), but instead return getHighEntropyValues() method?

## Console
![screenshot_2024-08-09_18-07-38](https://github.com/user-attachments/assets/a0203332-3ba6-40a1-89ab-a56b551a2a5f)

## Code:
```JS
// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://example.com/*
// @grant       unsafeWindow
// @version     1.0
// @author      -
// @description Test GM_info.userAgentData
// ==/UserScript==

(async function(){
  const uad = GM_info.userAgentData;
  const u = await uad.getHighEntropyValues(["fullVersionList"]);
  console.log(u)
})()
```

**Comment by tophf** [comment]
> no access

Sounds like Maxthon is broken. I'll add try-catch.

> Why not just [...] return all getHighEntropyValues's values 

1. Only 0.0001% of scripts need that info.
2. It's asynchronous, so getting it would delay the script. Violentmonkey provides a safe live mirror of the tab's userAgentData, so it reflects the changes in devtools device emulation or network condition, i.e. the developer will be able to simulate behavior on the target device. Judging by the fact that Tampermonkey provides some of this info synchronously it is obtained in the background script, which makes the described simulation scenario impossible.

**Comment by tophf** [comment]
Turns out Maxthon simply doesn't implement navigator.userAgentData.

**Comment by F9y4ng** [comment]
> It's asynchronous, so getting it would delay the script.

This reason is consistent with my idea.

Thanks for the fix.

**Comment by tophf** [comment]
> This reason is consistent with my idea.

Not sure if you agree or disagree. My point is that we would have to delay injection of all scripts to put those values into userAgentData object directly.

**Comment by F9y4ng** [comment]
I agree with this point, especially for scripts that `@run-at document-start`, which is crucial.

For my userscripts, I would like to be able to get the actual browser brand name, browser engine (chromium) name, and engine version through the extension, which is enough, the browser brand version is not very useful. Like @Xia0xia0Xia0 said, after all, browser style and script compatibility is judged based on the browser engine version.

For now, Violentmonkey has done well enough for browsers that can strictly adhere to the `navigator.userAgentData` data construction (such as Brave, etc.).
