### ISSUE TITLE
[问题] Chrome提示此扩展将很快被强制停止怎么办？

### ISSUE THREAD

**Issue by easythd** [violentmonkey/violentmonkey#2152]
在Chrome扩展中心和在Chrome商店都提示说
“這項擴充功能未遵循 Chrome 擴充功能的最佳做法，因此系統可能會在近期內停止支援。”
这个要怎么办？暂时是启用了，但提示说启用也是临时的，很快会被强制停止

**Comment by tophf** [comment]
See #1934.

P.S. You can click the menu in the warning and then click "Keep for now".
