### ISSUE TITLE
Help to Clear cache cookies ...

### ISSUE THREAD

**Issue by funmolde** [violentmonkey/violentmonkey#2157]
Hello, I can't create a script to delete from a site: cache , cacheStorage ,cookies ,indexedDB ,localStorage.
Is there a way to do this?
Chrome extensions work but not with violentmonkey.
What's the point of violentmonkeyif it can't do the same thing as the extensions?
Thank you -_-

Edge : 127.0.2651.74 (Version officielle) (64 bits)
OS: (Windows 11 64bits)

**Comment by tophf** [comment]
There's no such API for userscripts.
