### ISSUE TITLE
[BUG] Violentmonkey backup issues.

### ISSUE THREAD

**Issue by Koitoouav** [violentmonkey/violentmonkey#2158]
My Violentmonkey BETA cannot open or function properly. I want to back up the scripts inside it, but I cannot do so through the Violentmonkey settings. What should I do?

**Comment by tophf** [comment]
This is the first time I see such a problem reported, so I don't know exactly.
1. What is your browser and version?
2. What is the version of Violentmonkey?
3. Is Violentmonkey enabled in `chrome://extensions` or in `about:addons` page?

**Comment by tophf** [comment]
1. Did it work previously? When?
2. Are there errors in the [background console](/a/10258029)?
3. Do you see the Violentmonkey's icon in the toolbar?
