### ISSUE TITLE
[BUG] Chrome Webstore warning: This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions

### ISSUE THREAD

**Issue by alaa9jo** [violentmonkey/violentmonkey#2163]
When you visit Chrome Webstore, there is warning on the extension page [link](https://chromewebstore.google.com/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag), (below is a screenshot):

![image](https://github.com/user-attachments/assets/64840e73-ff3b-4406-a017-c05bb2d0c603)

I also noticed a similar warning on the Chrome installed extensions page (chrome://extensions/), below is a screenshot:

![image](https://github.com/user-attachments/assets/f028bd08-c6e8-469a-917a-4e4777c4fb54)

How is that going to effect the current users who use this extension ? 

#### Environment:
- OS: Windows 11
- Browser: Chrome 127.0.6533.100

**Comment by tophf** [comment]
See #1934.

**Comment by ntt77** [comment]
#1934 doesn't answer the question.
Will you create a new MV3 support extension or not?

**Comment by tophf** [comment]
It's not removed.

**Comment by tophf** [comment]
Although I guess the browser may hide it unless you enabled these ManifestV2 flags:
https://stackoverflow.com/questions/79283218

**Comment by auxsvr** [comment]
Just saw this today: ![Image](https://github.com/user-attachments/assets/4a675341-6711-48c5-b463-6773b95c362b)
The only setting that allowed me to install it was chrome://flags/#extension-manifest-v2-deprecation-disabled. I think most people will have no idea that this setting even exists, which effectively means that the webstore no longer provides violentmonkey to them.
