### ISSUE TITLE
GM_addStyle should return HTMLStyleElement

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#217]
### What is the problem?

`GM_addStyle` should return HTMLStyleElement created with given CSS text. This behavior can be conformed on GreaseMonkey and Tampermonkey.

### How to reproduce it?

```javascript
// ==UserScript==
// @name        Test
// @namespace   https://github.com/tiansh/
// @include     *example.com*
// @version     1
// @grant       GM_addStyle
// ==/UserScript==

const style = GM_addStyle('');
console.log(style);
```
Add this script and open example.com

### What is the expected result?
A `<style>` tag should be logged on console.

### What is the actual result?
Got `undefined`

### Environment
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
- Violentmonkey version: 2.8.9
- OS: Microsoft Windows [version 10.0.15063]

**Comment by gera2ld** [comment]
The `<style>` tag is created asynchronously to avoid CSP issues, e.g. add style to `https://github.com` with `GM_addStyle`. So it is not possible to return it synchronously now. Maybe we will make the API asynchronous and return a Promise resolving the `<style>` tag in the future.

**Comment by gera2ld** [comment]
What about returning an object with a method to get the `<style>` element asynchronously?
``` js
var res = GM_addStyle('...');
res.getEl(function (el) {
  // `el` is the `<style>` element
});
```

**Comment by tiansh** [comment]
A `Promise` should be better than an trivial object, IMO.

**Comment by tiansh** [comment]
And maybe it's better to switch to Promise with a brand new API, which is what GreaseMonkey currently doing in 4.0 alpha channel. Maybe just wait a moment and see what will happen next is a wise way.

**Comment by gera2ld** [comment]
It's good to switch to a new Promise-style API in the future.
As for now, I am trying to keep the existing APIs work on different browsers, including those without Promise support yet. Since a Promise polyfill is relatively large, I think it not good to inject a polyfill to every page. By renaming `getEl` to `then`, we can get a Promise-style API without being polyfilled:

```js
var res = GM_addStyle('...');
res.then(function (el) {
  // `el` is the `<style>` element
});
```
