### ISSUE TITLE
[BUG] Problems with @match and @exclude on my own script

### ISSUE THREAD

**Issue by OutshineIssue** [violentmonkey/violentmonkey#2171]
### Problem: 

More often than not, I'm dealing with ViolentMonkey ignoring these two specifically with a script on a website with some kind of special URL. This URL goes like this:

> subdomain2.subdomain1.domain.com/folder/?=gibberish

Only the domain and folder are persistent, so basically I'm doing

`@match *://*.subdomain.domain.com/folder/*`

It worked the first time, but sometimes I see that the script isn't running. For the seek of trying, I changed the match to

`@match *://*.*.domain.com/folder/*`

and it worked, but then again I change it back to the original because at one point it stops running again. Needles to say, this also applies for @exclude

### Expected result:  

The script works 100% of the time.

#### Environment:
- OS: Windows
- Browser: Firefox Nightly 131 
- Violentmonkey Version: 2.20.0

**Comment by tophf** [comment]
Without a real example the only explanation is already shown in the popup:

> The script didn't exist or didn't match the URL when the page loaded, which happens in Single-Page Application sites like fb or instagram that are using fake navigation. You can reload the tab to run the script. To fix the script use @match for the entire site and then detect changes using MutationObserver or window.navigation API.

**Comment by OutshineIssue** [comment]
It seems like the website is indeed a single page application site, but it is frameworked so it barely uses explicit ids to make use of the mutation observer. Unless I want to observe a div within a div within a div ad infinitum, I'm going to need another method. Isn't there an alternative?

**Comment by tophf** [comment]
You can check `location.href` inside MutationObserver to see which page you are on and act accordingly.
