### ISSUE TITLE
[Feature] Scripts source link

### ISSUE THREAD

**Issue by atlantis451** [violentmonkey/violentmonkey#2175]
**Motivation**

The user installed violentmonkey but didn't know where to download the script

**Proposed Solution**

```
[Greasy Fork](https://greasyfork.org)
[OpenUserJS](https://openuserjs.org)
[Userscripts](https://userscripts-mirror.org/index.html)
[Userscript](https://www.userscript.zone)
[git script](https://gist.github.com/search?l=JavaScript&o=desc&q=%22%3D%3DUserScript%3D%3D%22&s=updated)
```

* Add link at the red mark
![55255](https://github.com/user-attachments/assets/64497bcb-f85b-447d-b9d2-da814d67b40d)

**Comment by tophf** [comment]
Violentmonkey already shows `Find scripts for this site` in the popup for greasyfork an openuserjs. I guess we can show these two sites in the dashboard when there are no scripts installed. As for the other sites, they are not moderated as strictly as the two we already support, so I don't want to add them.

**Comment by tophf** [comment]
Actually, the dashboard already has links for greasyfork and openuserjs too, but they're "hidden" inside the `+` menu. I guess we should simply expand this menu by default when there are no script.
