### ISSUE TITLE
[BUG] `Uncaught (in promise) Error: No current window` thrown in `browserWindows.getCurrent`

### ISSUE THREAD

**Issue by bnichell** [violentmonkey/violentmonkey#2185]
### Sequence of actions: 
1. Open google.com with following script:

```js
// ==UserScript==
// @name        Violentmonkey-Test
// @namespace   test-env
// @version     1.0.0
// @description Test Violentmonkey issue
// @run-at      document-start
// ==/UserScript==
 
console.log('Test script loaded');
```

### Problem: 
After the last ViolentMonkey update, a user of a script I am developing reports that after some time of use they are seeing following error messages on pages that are matched by a script (also with the minimal script provided above on google.com):

> The script didn’t exist or didn’t match the URL when the page loaded, which happens in Single-Page Application sites like fb or instagram that are using fake navigation. You can reload the tab to run the script To fix the script use @match for the entire site and then detect changes using MutationObserver or window.navigation API.

After uninstalling and reinstalling the script the issue disappears and reappears again after some time.

The issue seems to be related to following change:
https://github.com/violentmonkey/violentmonkey/commit/90c37e98fdd7c58148275844205c8acf8f62c523#diff-94e114406a29cb9d88951e20cfc81ec4b351396b605380f7c902a9f8176acfc7L678-R680

The error is thrown at following statement (`getCurrent`):
```js
    checkedVivaldi = browserWindows.getCurrent().then(checkVivaldi);
```

### Expected result:  

The scripts are executed correctly without the observed error.

#### Devtools console contents:
```
injected.js:1  Uncaught (in promise) Error: No current window
    at Proxy.<anonymous> (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:1411)
    at fc (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:183759)
    at GetInjected (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:184172)
    at Lc (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:190705)
    at Ac (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:190652)
    at d (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/background/index.js:1:1767)
Error: callstack before invoking sendMessage:
    at Proxy.<anonymous> (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:2232)
    at je (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:3326)
    at Ne (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:3438)
    at je (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:3309)
    at nt (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:4595)
    at chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:14212
    at chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:14542
    at chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/injected.js:1:15295
(anonymous) @ injected.js:1
```

#### Environment:
- OS: Windows
- Browser: Microsoft Edge for Business, Version 128.0.2739.67 (Official build) (64-bit)
- Violentmonkey Version: Violentmonkey 2.21.0 and 2.22.0

**Comment by tophf** [comment]
Looks like every browser is bent on breaking browser.windows API in a different way...

**Comment by tophf** [comment]
This change was added in 2.22 but not in 2.21, so it can't be related.

**Comment by tophf** [comment]
2.21 was checking the injected tab's window, not `current`, could you re-test it? Also please test 2.20 which wasn't checking any window.

**Comment by bnichell** [comment]
The initial report to us mentioned 2.2.1, so it might have had a similar behavior in the previous version on the `browserWindows.get(obj)`.

When I checked it on the users device they already were on 2.2.2 (which I confirmed).

Perhaps something like the following could avoid the issue:
```
function checkVivaldi(obj, maxTries = 10) {
  if (obj.vivExtData/*new*/ || obj.extData/*old*/) {
    setBrowserName('Vivaldi');
  } else if (!checkedVivaldi) { // skipping when we're in the nested self-call
    checkedVivaldi = browserWindows.getCurrent().then(checkVivaldi).catch(async () => {
      await makePause(50);
      if (maxTries > 0) checkVivaldi(obj, maxTries - 1);
    });
    return;
  }
  checkedVivaldi = true;
}
```

**Comment by tophf** [comment]
Yeah, but I'll do something different because I don't want to delay injection just to check for a not very popular browser. The current code was also delaying it, so it wasn't good either.

**Comment by carlosjeurissen** [comment]
Seems somewhere in between Vivaldi 6.0 and 6.7, Vivaldi removed the `vivExtData` and `extData` properties. So this nolonger works to detect Vivaldi.

**Comment by tophf** [comment]
Works for me in Vivaldi 7.x.

**Comment by carlosjeurissen** [comment]
@tophf Thanks for verifying! Seems Vivaldi only removed `vivExtData` from [tabs.Tab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab). While keeping it around for [windows.Window](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/Window)
