### ISSUE TITLE
2.8.9版本哔哩哔哩（bilibili.com）播放器调整脚本的设置无法保存

### ISSUE THREAD

**Issue by Asteroids89** [violentmonkey/violentmonkey#219]
暴力猴版本： v2.8.9 ，
浏览器 ：Google Chrome 61.0.3163.100（正式版本）（64 位）
问题：哔哩哔哩（bilibili.com）播放器调整脚本的设置无法保存
附关于脚本作者的分析：https://greasyfork.org/zh-CN/forum/discussion/29600/x

**Comment by gera2ld** [comment]
保存完设置，页面会立马关闭或者刷新吗？

**Comment by Asteroids89** [comment]
感谢修复，静待新版本~~
