### ISSUE TITLE
[BUG] GM.download doesn't resolve in Firefox 130

### ISSUE THREAD

**Issue by andrewsuzuki** [violentmonkey/violentmonkey#2190]
```js
// ==UserScript==
// @name        GM.download await test 2024-09-19
// @namespace   Violentmonkey Scripts
// @match       https://*/*
// @grant       GM.download
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

(async () => {
  await GM.download({
    name: 'foo.txt',
    url: `data:text/plain;charset=utf-8,bar`,
  });
  window.alert('UNREACHABLE');
})();
```

It downloads, but doesn't resolve. `window.alert` is never called. Worked fine in Firefox 129.

#### Environment:
- OS: macOS
- Browser: Firefox 130
- Violentmonkey Version: 2.23.0

**Comment by tophf** [comment]
It worked in 130.0.0 but fails in 130.0.1, apparently because SafePromiseConstructor stopped working, which is either a bug in Firefox or an intentional change. I'll bisect Firefox builds later.

**Comment by tophf** [comment]
Interestingly, this works:

```js
GM.download({
    name: 'foo.txt',
    url: `data:text/plain;charset=utf-8,bar`,
  }).then(() => alert('OK'));
```
