### ISSUE TITLE
[BUG] Uncaught (in promise) TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rolandotownsend** [violentmonkey/violentmonkey#2193]
### Sequence of actions: 
1. Install a script
2. Open a website

### Problem: 
I just updated to Violentmonkey 2.23.0 and now no scripts are running, see error below.
In the popup it always says "Scripts disabled".

### Expected result:  
Scripts work

#### Devtools console contents:
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at chrome-extension://j…injected.js:1:12274
    at chrome-extension://j…injected.js:1:14507
    at Array.forEach (<anonymous>)
    at chrome-extension://j…injected.js:1:14496
(anonymous)	@	chrome-extension://j…nfdag/injected.js:1
(anonymous)	@	chrome-extension://j…nfdag/injected.js:1
(anonymous)	@	chrome-extension://j…nfdag/injected.js:1
Promise.catch		
(anonymous)	@	chrome-extension://j…nfdag/injected.js:1
(anonymous)	@	chrome-extension://j…nfdag/injected.js:1

#### Environment:
- OS: Linux
- Browser: ungoogled-chromium 128.0.6613.84 
- Violentmonkey Version: 2.23.0

**Comment by tophf** [comment]
It works for me in a Windows build of ungoogled-chromium and looking at the code it can only happen if this browser removed navigator.userAgentData getter while leaving the property itself, which is really weird. I'll add a check for the same just in case.

**Comment by tophf** [comment]
Also works for me in a Linux build of ungoogled-chromium (portable), so I guess your build is broken. Anyway, I've added a check for reliability.

**Comment by Ahrotahn** [comment]
Ungooged-chromium has a flag that allows removing clienthints and userAgentData.  It used to return null, but that was changed in 128.0.6613.137 to return an empty object instead so that the changes in 2.21.0 wouldn't cause issues.  You likely tested with a newer build that included that change.
