### ISSUE TITLE
[BUG] GM.setValue doesn't resolve on Firefox 130 in certain conditions

### ISSUE THREAD

**Issue by Totto16** [violentmonkey/violentmonkey#2195]
# Sequence of actions: 

- Use Firefox >= 130
-  use `GM.setValue` in certain ways, see below 
- the promise doesn't resolve correctly 

# Problem

When using `GM.setValue` it wan't resolve, if we set any value , but only in certain conditions, it seems to me, as if it set the same content, it works, otherwise not. 

After some thought and looking around, it seems to me, as this is related to #2190
If it sets the value and has to do something, it returns a Promise, that doesn't work, otherwise it returns no promise, and await does the correct thing. It may already be fixed in 2.24.0, but that isn't out yet on Firefox 😓 

## Script 1

```javascript
// ==UserScript==
// @name        GM.setValue await test 1 - 2024-09-22
// @namespace   Violentmonkey Scripts
// @match       https://*/*
// @grant        GM.setValue
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

(async () => {
    await GM.setValue('test', 1)
    window.alert('UNREACHABLE');
})();
```

This script doesn't work the first time, it sets the value for the key correctly, but doesn't resolve, the second time it works.

## Script 2

```javascript
// ==UserScript==
// @name        GM.setValue await test 2 - 2024-09-22
// @namespace   Violentmonkey Scripts
// @match       https://*/*
// @grant        GM.setValue
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

(async () => {
    await GM.setValue('test', 1);
    await GM.setValue('test', 2);
    window.alert('UNREACHABLE');
})();
```

This script never works. But you can see, that on each refresh, the value circulates between 1 and 2.

#### Environment:
- OS: Linux - Ubuntu 24.04
- Browser: Firefox 130.0.1
- Violentmonkey Version: 2.23.0

## Works as expected in
- Chromium 131.0.6734.0

**Comment by Totto16** [comment]
I manually checked the latest version 2.24.0 and it works there, I just assumed, that I have the newest version, but I hadn't, mayn Firefox takes a long time to approve those updates 😓

**Comment by Sv443** [comment]
I also just ran across this issue and after a bit of investigating, it seems to not want to save longer strings?  
In the following screenshot I am saving two values that are short and a third that is a very long encoded string and saving the long string works once after page load and then never again, but the number and bool work fine every time:  
  
![image](https://github.com/user-attachments/assets/1a9329ff-48ad-46ca-b41b-44ddbd4d2b5c)
  
What I find really weird is that it works once but then every consecutive call there's no Promise rejection, no error being thrown, nothing, the code in that async function call just ceases execution, as if it were a `prompt()` waiting for user input.  
  
I can also confirm the affected version range to be from v2.21 to v2.23 (inclusive). v2.20 and v2.24 work as expected.

**Comment by Totto16** [comment]
> I also just ran across this issue and after a bit of investigating, it seems to not want to save longer strings? In the following screenshot I am saving two values that are short and a third that is a very long encoded string and saving the long string works once after page load and then never again, but the number and bool work fine every time:
> 
> ![image](https://private-user-images.githubusercontent.com/38158426/369964526-1a9329ff-48ad-46ca-b41b-44ddbd4d2b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTQwNTEsIm5iZiI6MTcyNzExMzc1MSwicGF0aCI6Ii8zODE1ODQyNi8zNjk5NjQ1MjYtMWE5MzI5ZmYtNDhhZC00NmNhLWI0MWItNDRkZGJkNGQyYjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE3NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OTQ3ODE0OGYxMjBhMTI1ZTI2NjJkOTI1MTQwNDllN2I1MTVhZjIzMmVhNjc3YmRlMTFhNmY0MzJlNWUwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wIx65GdntRgTGEbrNSJO129MNb-MTp85iEGh3pVPvyE)
> 
> What I find really weird is that it works once but then every consecutive call there's no Promise rejection, no error being thrown, nothing, the code in that async function call just ceases execution, as if it were a `prompt()` waiting for user input.
> 
> I can also confirm the affected version range to be from v2.21 to v2.23 (inclusive). v2.20 and v2.24 work as expected.

Yeah, that is really strange 🤔  But as long as it works in the newer versions again, it is not worth investigating more 😓

**Comment by Sv443** [comment]
Yeah I just find it interesting, also I was looking for potential temporary workarounds lol.
