### ISSUE TITLE
[BUG] 部分脚本不触发下载

### ISSUE THREAD

**Issue by aotemande** [violentmonkey/violentmonkey#2197]
## 问题复现
脚本：[推特媒体下载](https://greasyfork.org/zh-CN/scripts/495368-twitter-x-media-downloader)

yandex浏览器安装最新油猴插件无法正常下载媒体文件，手机和pc均无法。测试chrome和edge，也无法正常下载（这两个浏览器是小概率可以触发下载，基本稳定不触发文件下载）

## 比对：
但是脚本猫scriptcat可以正常使用，怀疑是版本问题？

**Comment by tophf** [comment]
Looks like you are reporting a problem with Tampermonkey, but this repository is for Violentmonkey. This script works for me in Chrome.

**Comment by aotemande** [comment]
Sorry, it may be that there is a problem with my expression. I'm talking about&nbsp;Violentmonkey.&nbsp;It cannot download files normally through the script now. I have the impression that it will be okay in April and May.


明知爱这种男孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "violentmonkey/violentmonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [violentmonkey/violentmonkey] [BUG] 部分脚本不触发下载 (Issue #2197)





 
Looks like you are reporting a problem with Tampermonkey, but this repository is for Violentmonkey. This script works for me in Chrome.

**Comment by aotemande** [comment]
> Sorry, it may be that there is a problem with my expression. I'm talking about&nbsp;Violentmonkey.&nbsp;It cannot download files normally through the script now. I have the impression that it will be okay in April and May.

**Comment by tophf** [comment]
Version of Violentmonkey?
Version of Yandex browser?
Is it mobile or desktop?

**Comment by aotemande** [comment]
PC version：24.7.3.1250 (64-bit)
Mobile version：beta 24.7.9
Violentmonkey verrsion 2.24.0，I tried from version 2.20 to the current one, it seems to be abnormal.
And&nbsp;I also experimented with the latest&nbsp; mobile iceraven browser. When using the ViolentMonkey and this twitter script, the browser crashes directly






明知爱这种男孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "violentmonkey/violentmonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [violentmonkey/violentmonkey] [BUG] 部分脚本不触发下载 (Issue #2197)





 
Version of Violentmonkey?
 Version of Yandex browser?
 Is it mobile or desktop?

**Comment by tophf** [comment]
It works for me in Chrome, so I guess it's a bug in those browsers.

**Comment by aotemande** [comment]
emm，ok，I will try it with chrome to see this situation.




明知爱这种男孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "violentmonkey/violentmonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [violentmonkey/violentmonkey] [BUG] 部分脚本不触发下载 (Issue #2197)





 
It works for me in Chrome, so I guess it's a bug in those browsers.

**Comment by tophf** [comment]
In Yandex browser I see an error in devtools console from this userscript, clicking which opens `if (medias.length > 0) {` line in the script. It means that those browsers don't have `extended_entities` in the network response, which is either a bug in the browser or in the script. I don't see how Violentmonkey can influence that.

**Comment by tophf** [comment]
I found a workaround, which you can suggest to the author of the script:

```js
      if(medias == undefined){
          medias = JSON.parse(json.card.legacy.binding_values[0].value.string_value).media_entities;
          medias = Object.values(medias);
      }
```

**Comment by tophf** [comment]
It's from https://greasyfork.org/en/scripts/509630-twitter-media-downloader

**Comment by aotemande** [comment]
Ooops！！Thanks so much，I love Violentmonkey！


明知爱这种男孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "violentmonkey/violentmonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [violentmonkey/violentmonkey] [BUG] 部分脚本不触发下载 (Issue #2197)






I found a workaround, which you can suggest to the author of the script:
      if(medias == undefined){          medias = JSON.parse(json.card.legacy.binding_values[0].value.string_value).media_entities;          medias = Object.values(medias);      }

**Comment by aotemande** [comment]
It looks like a new version？I can have a try tonight！





明知爱这种男孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "violentmonkey/violentmonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [violentmonkey/violentmonkey] [BUG] 部分脚本不触发下载 (Issue #2197)






It's from https://greasyfork.org/en/scripts/509630-twitter-media-downloader
