### ISSUE TITLE
[BUG] `GM.xmlHttpRequest` unable to send request in firefox when `data` is `ArrayBuffer`

### ISSUE THREAD

**Issue by esterTion** [violentmonkey/violentmonkey#2198]
### Sequence of actions: 
```Javascript
// ==UserScript==
// @grant GM.xmlHttpRequest
// ==/UserScript==

const data = new Uint8Array(8);
GM.xmlHttpRequest({
  method: 'POST',
  url: 'https://example.com/',
  data,
  responseType: 'arraybuffer',
  onload: res => console.log(res.response)
  onerror: error => console.error(error)
});

```

### Problem: 
Request will always fail

### Expected result:  
Request with buffer as request body is sent

#### Devtools console contents:
* `Error: String contains an invalid character` when data is `Uint8Array`
* `Error: a.indexOf is not a function` when data is `ArrayBuffer`

#### Environment:
- OS: Windows
- Browser: Firefox 130.0.1 
- Violentmonkey Version: 2.23.0

This is likely due to a typo in [src/injected/web/requests.js:212](https://github.com/violentmonkey/violentmonkey/blob/master/src/injected/web/requests.js#L212), `IS_FIREFOX` is `bool` value and therefore will never `>= 56`. 
I can confirm when `IS_FIREFOX >= 56` check passes and `data` is assigned with `[data]`, not `[data, 'bin']`, the request indeed succeeds. 
This check should probably be changed to `(IS_FIREFOX && FIREFOX >= 56)` ?

This error does not occur in other browsers.

**Comment by tophf** [comment]
This code works for me and I don't see any of these errors. IS_FIREFOX is overwritten with the version number before injection occurs and debugging in devtools for the web page shows it's `130` in requests.js as expected. Devtools for the extension's background page shows the request is sent correctly with 8 zero bytes payload.

**Comment by esterTion** [comment]
![图片](https://github.com/user-attachments/assets/ef1efa7a-6120-451b-8b46-75324d98371d)
Mine is still true when the check happens, where did this get overwritten? Isn't this variable a `const`?

**Comment by tophf** [comment]
It's a function parameter, not a const, overwritten in https://github.com/violentmonkey/violentmonkey/blob/da484666347e88ed9672f137f76745ea6b866fcc/src/injected/content/inject.js#L135, so I just can't imagine how it can be `true`.

**Comment by tophf** [comment]
I see how it can happen: sometimes we call injectPageSandbox before injectScripts(), I'll fix it.

**Comment by esterTion** [comment]
Yeah I was about to comment about this. Inject mode on `auto` will use `page` inject mode instead of `content`. This works fine in `content` inject mode.

**Comment by tophf** [comment]
FWIW, it works fine in both modes for me. The code path that may call injectPageSandbox earlier activates only when the site is greasyfork/sleazyfork, so if your site isn't one of those, it's not the cause of the bug.

**Comment by esterTion** [comment]
I was testing a new script on `localhost`, not sure if that matters. 
Anyway as you already found the root cause, I'll set `@inject-into content` for now while waiting for the next version. Thanks.

**Comment by tophf** [comment]
No, if your site isn't greazyfork/sleazyfork, the code path I found cannot be the cause, i.e. it's an impossible outcome, AFAICT.

**Comment by tophf** [comment]
Uhm, I'm wrong, that code path runs for all sites...
