### ISSUE TITLE
Release more often to AMO?

### ISSUE THREAD

**Issue by yoasif** [violentmonkey/violentmonkey#220]
### What is the problem?

The VM FAQ states that users should install from Github due to the AMO review process. 

### How to reproduce it?

1. Install from AMO

### What is the expected result?

get the latest version of VM

### What is the actual result?

get an older version of VM

### Environment
- Browser: Firefox
- Browser version: any
- Violentmonkey version: 
- OS: any

Mozilla [announced](https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/) that extension reviews will get a lot shorter due to the move to WebExtensions. 

> Add-ons built on the WebExtensions API will now be automatically reviewed. This means we will publish add-ons shortly after uploading.

Will it be possible to keep in sync with Github now and remove the recommendation to install from Github?

**Comment by gera2ld** [comment]
Released as v2.8.10f
