### ISSUE TITLE
[Feature] new incognito window

### ISSUE THREAD

**Issue by TechComet** [violentmonkey/violentmonkey#2200]
**Motivation**
in want to use to change default `incognito window` shortcut in firefox using violentmonkey shortcut

**Proposed Solution**
open incognito window from violentmonkey

**Use Cases**
!

**Comment by tophf** [comment]
I don't see how this is specific to userscripts, so I think it would make more sense if you find an extension that deals with browser shortcuts and suggest its author to add such a shortcut.
