### ISSUE TITLE
[Feature] automatic disable Violentmonkey in Bank Website (default black list)

### ISSUE THREAD

**Issue by TechComet** [violentmonkey/violentmonkey#2201]
**Motivation**
automatic disable Violentmonkey in Bank Website

**Proposed Solution**
automatic disable Violentmonkey
and change Violentmonkey icon to disable icon or gray icon
default black list like local bank, paypal.com, more..

**Use Cases**
safe data for local bank, paypal.com, more..

**Comment by tophf** [comment]
You can already do it by adding the site to Blacklist option in Violentmonkey. We can't know which site is a banking site because all lists are incomplete and may not contain this user's bank. I guess we can add a command in `...` menu to add the current site to the blacklist.
