### ISSUE TITLE
[BUG] Couldn't install seripts in private browsing mode on Fenix (Firefox for Android)

### ISSUE THREAD

**Issue by 0x391F** [violentmonkey/violentmonkey#2203]
### Sequence of actions: 
1. Enter private browsing mode on Fenix
2. Install a script from https://greasyfork.org/

### Problem: 
Nothing happen. This bug only happens in private browsing mode

### Expected result:  
It should work well as same as normal browsing mode. 

#### Environment:
- OS: Xiaomi HyperOS 1.0.10.0.UNRCNXM (Android 14)
- Browser: Fenix 131.0
- Violentmonkey Version: 2.26.0

**Comment by tophf** [comment]
Sounds like you didn't allow this extension to run in private windows:

![image](https://github.com/user-attachments/assets/71298675-a5c4-4433-be53-a726a7578084)

**Comment by tophf** [comment]
Ah, sorry, I see the problem with this option enabled too...
