### ISSUE TITLE
[BUG] [Firefox] GreasyFork.org's `external.Violentmonkey.isInstalled` is not a Promise object. Await not working.

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#2206]
1. Go to https://greasyfork.org/en/scripts
2. Open Console and execute `external.Violentmonkey.isInstalled("1","2") instanceof Promise`
3. Result is false.

<img width="450" alt="Screen Shot 2024-10-13 at 14 24 00" src="https://github.com/user-attachments/assets/0f0b4f29-b6a2-4eda-a493-aaf3f5b3d1fd">

4. Execute
```js
(async function(){
console.log('Log1')
const value = await external.Violentmonkey.isInstalled("1","2")
console.log('Log2', value)
})()
```

5. await not working
<img width="453" alt="Screen Shot 2024-10-13 at 14 24 49" src="https://github.com/user-attachments/assets/2c6d8fd2-3e53-48d8-84e3-6e9c6d14d704">

**Comment by tophf** [comment]
Until a new version is released, the workaround is to use `.then`:

```js
external.Violentmonkey.isInstalled("1","2").then(res => ...)
```
