### ISSUE TITLE
[BUG] Synchronous  page  mode seems to be invalid?

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [violentmonkey/violentmonkey#2213]
### Problem: 

I tried 2.26.0 and 2.26.2 and they both have the script loading delay issue, which didn't exist in previous versions, and it seems that Synchronous page mode is not working. Is it possible to check its validity?

And how do I go back to a previous version in the extension store?

Thanks.

#### Environment:
- OS: Windows11
- Browser: Chrome 130
- Violentmonkey Version:2.26.0

**Comment by tophf** [comment]
I can't reproduce the problem. Everything works as usual for me. Please provide a more detailed description.

**Comment by tophf** [comment]
Maybe your script doesn't actually run in the `page` mode? You can verify it by adding `console.log(GM_info.injectInto)`

**Comment by tophf** [comment]
Well, I don't see how I can help without a reproducible test case...

**Comment by tophf** [comment]
Assuming your previous version was 2.25.0, there were no changes in the source code related to injection in Chrome.

**Comment by Xia0xia0Xia0** [comment]
What I can confirm is that it works fine under Firefox, but it doesn't work under Chrome. The same is 2.26.0.

**Comment by tophf** [comment]
Well, there's literally nothing I can do based on this info if you don't try to meet me halfway. I guess there's something else interfering. Try disabling all other extensions, make sure the script actually run in the page mode by adding `console.log(GM_info.injectInto)`.

**Comment by Xia0xia0Xia0** [comment]
The value of GM_info.objectInto is page, the role of the script is to write the style in document-start, the following is the animation effect:

![111](https://github.com/user-attachments/assets/ea7e3ef0-c6c5-4f9f-ab4a-ecf8386c2dc0)

I also tested TM5.1.1, and the version before VM2.26.0 also has the same effect, which is perfect:

![2222](https://github.com/user-attachments/assets/0da0db99-83a5-44bb-b511-c4c213a5ac60)

**Comment by tophf** [comment]
Still nothing I can do. Try disabling all other extensions.

**Comment by Xia0xia0Xia0** [comment]
I turned on privacy mode and only turned on one extension of the VM, but the problem remained. I no longer know what to do with it.

**Comment by tophf** [comment]
Synchronous page mode doesn't work in incognito mode, it's explained in the info next to the option.

**Comment by Xia0xia0Xia0** [comment]
I created a new Chrome user with completely blank settings and only installed one VM extension. The animation shows the result:

![333](https://github.com/user-attachments/assets/91b0de99-4974-4771-88fd-a54ede13f170)

**Comment by tophf** [comment]
The only explanation I see is a bug in the browser that is triggered by something I can't reproduce here.

**Comment by tophf** [comment]
Will you provide me with a way to reproduce the problem? You still haven't shown the code/script you're using.

**Comment by Xia0xia0Xia0** [comment]
https://greasyfork.org/en/scripts/24204
https://greasyfork.org/en/scripts/416688
https://greasyfork.org/en/scripts/419215

the scripts i used.

**Comment by tophf** [comment]
I've tried these scripts in a new profile and everything works as it should, no delays, no glitches.

Do you see Violentmonkey's `blob` in devtools network monitor?
![image](https://github.com/user-attachments/assets/9bfdb91f-5d8f-4c91-904d-6826ec4d5fdb)

**Comment by tophf** [comment]
Well in that case the option is actually working and the problem you observe is caused by something else.

**Comment by Xia0xia0Xia0** [comment]
Is it possible to make the loading timing of document-start a bit faster? Maybe the problem is solved. Maybe a 50ms boost would make a big difference. Thanks for your patience in replying.👍

**Comment by tophf** [comment]
It's is already at document_start + exactly `0` ms.

**Comment by tophf** [comment]
You can see that the scripts run at the real document_start for yourself by setting a breakpoint on the first line of the script:

![image](https://github.com/user-attachments/assets/393e65c5-2df7-4e6b-8266-a3cc35e3c13a)

Now switch to the Elements panel and you'll see just the `<html>` tag and a `<div>` with this userscript inside:

![image](https://github.com/user-attachments/assets/22d7b1ed-e8b8-4966-afe0-64feb0d33662)

**Comment by tophf** [comment]
You can also verify it by enabling this checkbox in devtools:

![image](https://github.com/user-attachments/assets/47cebf8c-cea4-4ecd-838d-a4566ff3698b)

When you reload the page you'll see Violentmonkey runs at document_start its `inject-web`, `inject`, iframe script, sandbox script, and then it immediately runs the userscript, while DOM only has `<html>` and a `<div>` for this script. This means that it's the real `document_start`.

It means there's no problem whatsoever in the option, it works as it always did. The problem is caused by something else.

**Comment by Xia0xia0Xia0** [comment]
I don’t know if I should say it, but the loading speed of these scripts in TM5.1.1 is indeed faster than that of VM from a visible perspective. I don’t know what magic TM used, that's why I wondered if it was possible to optimize the loading timing of the script.

**Comment by tophf** [comment]
There's no such thing as magic. I investigated what happens and I confirmed that the option works exactly as it always did, at the exact document_start.

**Comment by tophf** [comment]
I've debugged this userscript and I found that the problem is caused by its use of `uad.getHighEntropyValues(["bitness", "architecture", "fullVersionList"])` which Violentmonkey sends to the browser and evidently it is super slow in Chrome, so the result is returned when the page is already rendered.

It looks like this userscript doesn't even need this info and just extracts it unnecessarily, so you can suggest the author to remove this code.

**Comment by tophf** [comment]
To elaborate, suggest the author to use `GM_info.platform`, which synchronously provides the real info about the browser, obtained from the background script of the extension, so it's not affected by devtools of the web page tab.

**Comment by tophf** [comment]
For a personal workaround you can install a slightly older version of this userscript before it added the abovementioned code:
https://greasyfork.org/en/scripts/416688?version=1421288

**Comment by Xia0xia0Xia0** [comment]
Yes indeed, I modified 

```js
const vmuad = null; 
//         const vmuad = voucher.startsWith("Violentmonkey") && GMinfo.platform ? await getVMUserAgentData(GMinfo.platform) : null;
``` 

and it loaded fine.

Thank you, I will report this issue to the script author.

**Comment by Xia0xia0Xia0** [comment]
But if instead of passing uad.getHighEntropyValues, use GM_info.platform, then you don't get the browser's kernel version, only the browser version, and that version number doesn't seem to do much. I've mentioned this before in the other issue. A lot of Chromium browser compatibility is kernel version related, not so much browser version. And in this script, many situations are also used to determine the browser kernel version.

**Comment by tophf** [comment]
GM_info.platform contains the same full version number that you get from getHighEntropyValues.

**Comment by Xia0xia0Xia0** [comment]
> GM_info.platform contains the same full version number that you get from getHighEntropyValues.

In some weird browsers, it gets the browser version. Such as MAXTHON

![screenshot_2024-10-24_17-08-01](https://github.com/user-attachments/assets/ee0b9ed7-e64b-4b23-b75d-ad2b1f65ae38)

But the correct information was obtained through the script that would cause the delayed loading problem.

Anyway, I'll give the script author feedback on this issue and see if he has any way to solve it.

Thank you!

**Comment by tophf** [comment]
Does `GM_info.userAgent` list the version of Chromium in Maxthon?

**Comment by Xia0xia0Xia0** [comment]
> Does `GM_info.userAgent` list the version of Chromium in Maxthon?

![Uploading screenshot_2024-10-24_17-34-32.png…]()

**Comment by tophf** [comment]
No, I meant `GM_info.userAgent`, not `GM_info.userAgentData`, which you already showed.

**Comment by Xia0xia0Xia0** [comment]
> No, I meant `GM_info.userAgent`, not `GM_info.userAgentData`, which you already showed.

GM_info.userAgent 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by tophf** [comment]
So it contains the version of Chromium which has the same reliability as getHighEntropyValues, and it can be used synchronously.

**Comment by tophf** [comment]
Ah, it misses the build number part though (0.0.0), but is it really important?

**Comment by Xia0xia0Xia0** [comment]
> Ah, it misses the build number part though (0.0.0), but is it really important?

The major version number is very important, for example 109 is enough. Many styles and script compatibility can be queried at caniuse.com, many of which are related to the kernel version. For example, Chromium's recently updated 128 kernel has made great changes to CSS zoom property. Firefox also started to support CSS zoom property in 126. These need to be judged according to the main kernel version.

**Comment by tophf** [comment]
So the main version (109 in this case) is enough and there's no need for the full version (109.0.1234.2).

**Comment by Xia0xia0Xia0** [comment]
> So the main version (109 in this case) is enough and there's no need for the full version (109.0.1234.2).

Right, so the same delay problem as CHROME does not occur in MAXTHON, because the uad.getHighEntropyValues ​​method in MAXTHON will report an error, and the script captures the error and obtains the value of GMinfo.userAgentData.brands.

```js
if (GMinfo.userAgentData?.brands?.[0]) {
  try {
    return { ...(await getUserAgentDataHighEntropyValues(GMinfo.userAgentData)), voucher };
  } catch (e) {
    brands = [...GMinfo.userAgentData.brands, ...brands];
  }
}
```

**Comment by tophf** [comment]
What delay problem? I suggest using `GM_info.userAgent` to extract `109`, it's synchronous, so there's no delay.

**Comment by Xia0xia0Xia0** [comment]
What `GM_info.userAgent` gets is not necessarily the real kernel information, like Supermium. this is where you need to use uad.getHighEntropyValues to get it, here's what I found.

**Comment by tophf** [comment]
Then you can use GM_info.platform.browserVersion which Violentmonkey gets from getHighEntropyValues in the background script.

**Comment by tophf** [comment]
Or do you mean that in Supermium there are two items in the `brands` array, one for Chromium and one for Supermium?

**Comment by Xia0xia0Xia0** [comment]
But there is no way to tell if the information obtained is real or not. 

I forked the code in the font rendering script about recognizing the browser kernel version, it can accurately detect the exact kernel information including maxthon,superium,chrome,brave,edge and so on, but there is a problem with the script loading delay.

**Comment by tophf** [comment]
What do you mean "real"?

**Comment by Xia0xia0Xia0** [comment]
> What do you mean "real"?

maxthon --> 109 (not 7.2.2.3200)
superium --> 126 (not 127.0)

**Comment by tophf** [comment]
I don't understand. We just found out that in Maxthon you can get 109 from GM_info.userAgent. It is real, reliable, and synchronous. Regarding Superium, what does it say in GM_info.userAgent, GM_info.userAgentData, GM_info.platform?

**Comment by Xia0xia0Xia0** [comment]
![screenshot_2024-10-24_18-16-52](https://github.com/user-attachments/assets/eb8d7a60-a207-491e-b5f7-27f1a7893678)

**Comment by tophf** [comment]
So it looks like Supermium is bugged because it gives different results for navigator.userAgentData?

**Comment by tophf** [comment]
What if you use the old reliable userAgent string that the entire web has been using for 20+ years, which we synchronously expose in `GM_info.userAgent`? It contains 127, the correct version for Supermium.

**Comment by Xia0xia0Xia0** [comment]
I assume Supermium changed ua/uad to 127 for some compatibility issue as well.

**Comment by tophf** [comment]
I doubt it. They would have changed it in all places.

**Comment by tophf** [comment]
Anyway I don't the need to use `getHighEntropyValues` because all the data is already present in other parts of GM_info.

**Comment by tophf** [comment]
BTW, sometimes I try not to rely on the version number and test for features in DOM/JS/CSS that are known to appear or disappear in this version using MDN or caniuse sites. For example, `window.AbortSignal` was added in [Firefox 57](https://caniuse.com/abortcontroller).

**Comment by Xia0xia0Xia0** [comment]
> BTW, sometimes I try not to rely on the version number and test for features in DOM/JS/CSS that are known to appear or disappear in this version using MDN or caniuse sites.

Some do, some don't. For example, after updating to Chromium 128 (https://developer.chrome.com/release-notes/128), the value of Element.getBoundingClientRect() will change under css zoom property, which is different from the previous version, and this cannot be found by MDN or caniuse.

**Comment by tophf** [comment]
That's not what I meant. I'm testing for the existence of something, not for its behavior.

**Comment by Xia0xia0Xia0** [comment]
> That's not what I meant. I'm testing for the existence of something, not for its behavior.

I understand what you mean.😀

What I expressed above is that some problems can only be identified by the kernel version number, and there is no other better way.

**Comment by Xia0xia0Xia0** [comment]
> That's true, but I meant that you can detect the version itself by other features that were added or removed.

Hmmm... That's a good way to do it, but it's not necessarily true that every version has a new or deprecated API. I think the validity would be greatly increased by combining it with version number comparisons.

**Comment by tophf** [comment]
No delays, because it would be prepared just once when the extension starts. When we migrate to MV3 we'll also do it once when the browser is updated.

**Comment by Xia0xia0Xia0** [comment]
Looking forward to it.

**Comment by Xia0xia0Xia0** [comment]
I'm also looked at about an issue with the value of `GM_info.userAgentData` in TM5.3.1(MV3) not updating in `UserScripts API Dynamic` mode https://github.com/Tampermonkey/tampermonkey/issues/2164, and the recent intensive Chromium update enables me to reproduce it locally. I wonder how VM handles `document-start` after migrating to MV3, and if this type of issue is also involved?

**Comment by tophf** [comment]
TM's author will have to fix it in the source code. In case it's a bug in the browser, the only solution would be to keep the last version in storage and compare it to the current version on each start of the browser, so that when it changes the extension will re-register its controller script (which sends the value synchronously to the userscript when it wants to read GM_info property for userAgentData). At least this is how I would do in MV3 to avoid re-registering all userscripts.
