### ISSUE TITLE
[BUG] Data URL icons not considered valid if script is installed from file

### ISSUE THREAD

**Issue by tobbexiv** [violentmonkey/violentmonkey#2214]
### Sequence of actions:

1. Install below userscript by C&P in the VM editor. --> The icon is showing as intended.
2. Delete script and install again from external file. --> The icon is not visible anymore. If having a look at the code, it seems that the new URL sanitizing function considers the data URL as invalid (`data:,Invalid URL data:image/svg+xml;utf8,<svg width='10' height='10' xmlns='http://www.w3.org/2000/svg'><circle style='fill:red' cx='5' cy='5' r='5'/></svg>`

https://github.com/violentmonkey/violentmonkey/commit/8081d778426a5844446b0dba8a27136cc97179cb#diff-b2ac728164fb06dcd8810bb614fec6ac3250875c881d76dbbe0ed5ac1a4ac1cbR37

```
// ==UserScript==
// @name        Data icon broken
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @icon  data:image/svg+xml;utf8,<svg width='10' height='10' xmlns='http://www.w3.org/2000/svg'><circle style='fill:red' cx='5' cy='5' r='5'/></svg>
//
// ==/UserScript==
```

### Problem:

Icons set via data URLs are not being considered valid anymore if script is installed from file.

Might be that this also applies to other parts which were previously considered valid and are now broken. But, The icon is the only one I found and use.

### Expected result:

Icons set via data URLs are being considered valid independet from installation source.

#### Devtools console contents:

n/a

#### Environment:

- OS: Windows
- Browser: Edge 130.0.2849.46
- Violentmonkey Version: 2.27.0

**Comment by jesus2099** [comment]
I have [the same bug](https://github.com/jesus2099/konami-command/issues/872) when updating or installing userscripts from GitHub (not local file).
