### ISSUE TITLE
[BUG] The script is not inserted correctly during iframe src property asynchronous loading.

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#2215]
### Problem: 
When the iframe src property is loaded asynchronously, the script is not inserted correctly. But it is normal when loading synchronously.

Asynchronously loaded websites: https://wqbook.wqxuetang.com/deep/read/epub?bid=3226999

synchronously　loaded websites:　https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

Test code:
```js
// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       GM_getValue
// @version     1.0
// @author      -
// @description 2024/10/26
// @run-at      document-start
// ==/UserScript==

(function() {
    'use strict';
    document.documentElement.setAttribute("test","test iframe")
})();
```

#### Environment:
- OS: Windows 10
- Browser: All Chromium / All Firefox
- Violentmonkey Version: All Versions

**Comment by tophf** [comment]
It runs in all iframes, which you can see by adding `console.log(location.href, document, document.documentElement)`. I guess the site uses document.write() to rewrite the html. It should be possible to detect via MutationObserver.

**Comment by F9y4ng** [comment]
I tried to observe the change of the src property of the iframe via mutationObserver on the parent page and tried to reinsert the test attribute, which only works on chrome 130, but not on brave, edge, Firefox.

**Comment by F9y4ng** [comment]
I've solved it. Thanks for reply.

**Comment by tophf** [comment]
I meant observing `.observe(document, {....})` inside the iframe and checking document.documentElement.
