### ISSUE TITLE
[BUG] GM.xmlHttpRequest unable to fetch local file in 2.27.0

### ISSUE THREAD

**Issue by divinity76** [violentmonkey/violentmonkey#2216]
### Sequence of actions: 
1. Install ViolentMonkey version 2.27.0 (this issue is new in 2.27.0)
2. ensure ViolentMonkey have `Allow access to file URLs` in extension settings page ( chrome://extensions/?id=jinjaccalgkegednnccohejagnlnfdag )
3. ensure you have a `C:\test.txt` file with the content `test`
4. Run the code
```js
// ==UserScript==
// @name        New script hackerwars.io
// @namespace   Violentmonkey Scripts
// @match       https://example.com/*
// @grant       GM.xmlHttpRequest
// @grant       unsafeWindow
// @version     1.0
// @author      -
// @description 10/19/2024, 7:59:16 PM
// ==/UserScript==

GM.xmlHttpRequest({
        method: "GET",
        url: "file:///C:/test.txt",
        onload: function (response) {
            console.log(response.responseText);
        },
        onerror: function(){
          console.log("GM loader error!");
          console.log(arguments);
        }
});

```

### Problem: 
This used to work, but after updating to 2.27.0 just a few minutes ago, I now get
```
Error: Blacklisted URL file:///C:/test.txt
```
### Expected result:  
test
#### Devtools console contents:
Arguments [Error: Blacklisted URL file:///C:/test.txt, callee: ƒ, Symbol(Symbol.iterator): ƒ]0: Error: Blacklisted URL file:///C:/test.txtmessage: "Blacklisted URL file:///C:/test.txt"stack: "Error: Blacklisted URL file:///C:/test.txt"[[Prototype]]: Objectcallee: ƒ ()arguments: nullcaller: nulllength: 0name: "onerror"prototype: {}[[FunctionLocation]]: New script hackerwars.io.user.js:20[[Prototype]]: ƒ ()[[Scopes]]: Scopes[5]length: 1Symbol(Symbol.iterator): ƒ values()[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

#### Environment:
- OS: Windows Server 2019 version 1809 
- Browser: Chrome 130.0.6723.70
- Violentmonkey Version: 2.27.0

**Comment by divinity76** [comment]
This is actually intentional and was introduced in 58268295e0376f49dccb4e001795400e787638da

Seems it was intended to only apply on new installations, but seems it applied to everyone (I don't really mind that)

Closing.

**Comment by tophf** [comment]
Well, this is a bug, because the intention was to apply only to new installations, but conceptually it's a good restriction to have by default, so I'll wait for a while and see whether it's something that should be fixed or kept. I also contemplate adding an option in each script's settings to allow bypassing the global blacklist, which would make sense for scripts written by the user.

**Comment by greentore** [comment]
I think per script setting would be a good solution. I have a script that I'm testing on a local html page and `@match file://*/*` pattern is only set in dev builds.

**Comment by divinity76** [comment]
Seems this issue popped up again, Firefox 128.12.0esr, Violentmonkey 2.31.0,
  but now it cannot be disabled/bypassed in config, apparently.

ping @tophf  re-open this issue or make a new issue?
