### ISSUE TITLE
[BUG] The icon of the script is a hard-coded icon and is no longer displayed.

### ISSUE THREAD

**Issue by ChinaGodMan** [violentmonkey/violentmonkey#2220]
The icon of the script is a hard-coded icon and is no longer displayed.

like this
```
// @icon         data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIHZlcnNpb249IjE
```
<br>It used to be fine, but things have changed since upgrading to 2.27.0
![image](https://github.com/user-attachments/assets/c0728f15-21e7-46a5-bd39-2a06a0c8e256)

#### Environment:
- OS: Windows
- Browser: Chrome 129.0.6668.101（official version） （x64）
- Violentmonkey Version: v2.27.0

**Comment by tophf** [comment]
Should be already fixed in 2.28.0.
