### ISSUE TITLE
[BUG] Data URL icons invalid when installing from greasyfork and using chrome

### ISSUE THREAD

**Issue by resykano** [violentmonkey/violentmonkey#2221]
1. Install this script (manual creation with copy the code does not lead to the error):
https://greasyfork.org/en/scripts/508413
2. After installation the scripts icon can not be loaded. See installed scripts in greasemonkey.

It's a greasemonkey bug because:
1. in other browsers it works and in chrome also with tampermonkey
2. during installation of the script in greasemonkey the icon is visible
3. edit the script, remove a line from the header, such as the @match line, save, remove another @match line and save, remove the @author line and save, then the icon is visible.

#### Environment:
- OS: Windows
- Browser: Chrome 130.0.6723.92
- Violentmonkey BETA Version: v2.26.2

**Comment by tophf** [comment]
AFAIK, this is already fixed in 2.28.0

**Comment by resykano** [comment]
Ah, thought it's in the BETA yet. Yes, it works with 2.28.0. Thank you.
