### ISSUE TITLE
[BUG] `// @icon data:image/png;base64,...` is invalid in Supermium `2.28.0`

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#2222]
### Problem: 
`// @icon data:image/png;base64,...` is invalid in Supermium, the image link is resolved to `data:,Invalid URL data:image/png;base64,...`

![screenshot_2024-11-03_22-13-26](https://github.com/user-attachments/assets/77b9752b-d318-40b8-821d-6ca95dc90b43)

#### Environment:
- OS: Win10
- Browser: Supermium 126.0.6478.254
- Violentmonkey Version: 2.28.0

**Comment by tophf** [comment]
I can't reproduce the problem in 2.28.0, because it contains 188f732116fb788b00c7bdfdc1d79af5c328ec9d which fixed this bug, so I guess you're using an older version of Violentmonkey.

**Comment by F9y4ng** [comment]
![screenshot_2024-11-03_22-38-44](https://github.com/user-attachments/assets/797363be-49cc-4b34-b5a4-c4c1feec3cee)

**Comment by tophf** [comment]
I look at the source code and I can't see how this can happen, I can't reproduce it either. Do you see it in Chrome?

**Comment by tophf** [comment]
Also, what's the URL of the script so I can try it myself?

**Comment by F9y4ng** [comment]
It works in Chrome, but not in Supermium.

Script: https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js

**Comment by tophf** [comment]
Supermium 126.0.6478.254 R4, no problem... I wonder if somehow the database remembered the old incorrect value from the previous bugged version? Try running `await browser.storage.local.get('scr:999')` in devtools console of any Violentmonkey page where 999 is the id of your installed script, then see if the output has `pathMap` with this broken URL.

**Comment by F9y4ng** [comment]
![Uploading screenshot_2024-11-03_22-56-26.png…]()

**Comment by tophf** [comment]
> where 999 is the id of your installed script

**Comment by tophf** [comment]
Yeah, so the simplest fix for you is to remove the script and install it again. I'll add a check in Violentmonkey to do it automatically on startup.

**Comment by F9y4ng** [comment]
I deleted the script and reinstalled it and the icons came back, so it should be a problem caused by corrupted data.

**Comment by F9y4ng** [comment]
I would like to add something that might help you, before this version I was using `// @icon https://.....`, and adjusted to `data:image/png;base64` as of version 2024.11.02.1. The script was updated yesterday, the VM extension was just updated tonight.
