### ISSUE TITLE
[BUG] Error in GM.SetValue

### ISSUE THREAD

**Issue by Totto16** [violentmonkey/violentmonkey#2228]
# General
There is a strange error in a niche case of using `GM.setValue`

The error is `TypeError: U is not a constructor`

This occurs, when you open a window with `window.open` (or unsafeWindow) and than use `GM.setValue`.
But only, if the window and opened url have the same origin, if they don't it works just fine.

### Minimal Script

```js
// ==UserScript==
// @name        GM.setValue in opened window - 2024-11-12
// @namespace   Violentmonkey Scripts
// @match       https://*/*
// @grant        GM.setValue
// @version     1.0
// @author      Totto16
// @description -
// ==/UserScript==

const URLtoOpen = 'https://violentmonkey.github.io/';

function wasOpenend() {
    return window.location.toString() === URLtoOpen;
}

(async () => {
    if (!wasOpenend()) {
        await GM.setValue('test', { test: 1 });

        console.log(`successfully set (origin)`);

        unsafeWindow.open(URLtoOpen, '_blank');

        return;
    }

    await GM.setValue('test', { test: 2 });
    console.log(`successfully set (opened)`);
})();


```

### Sequence of actions: 
1. install the script from above
2. goto `https://violentmonkey.github.io/api/gm/`
3. see a window to `https://violentmonkey.github.io/` open
4. go to that console
5. see the error

### Devtools console contents:

![image](https://github.com/user-attachments/assets/ab9efe15-c48e-496f-a245-fdb6e13b63d9)
![image](https://github.com/user-attachments/assets/72cee8b4-3a1e-4764-840e-a89a8b7edee8)

### Notes

Also tested with VM version 2.27.0, there it doesn't work
But with VM version 2.24.1 it does work correctly without error.

### Environment:
- OS: Linux
- Browser: Firefox 132.0.1
- Violentmonkey Version: 2.28.0

**Comment by tophf** [comment]
Until the new version is published, here's the workaround:
```js
open(URLtoOpen, '_blank', 'noopener')
```
