### ISSUE TITLE
Nextcloud Support

### ISSUE THREAD

**Issue by AdamBryantSkybox** [violentmonkey/violentmonkey#224]
In this case, would it be possible to just have a generic "folder sync" support feature?
Would love to have a single sync method, though for now I am using Dropbox for it. I host my own nextcloud server.

**Comment by gera2ld** [comment]
maybe duplicate of #100

**Comment by AdamBryantSkybox** [comment]
Yes, Nextcloud uses WebDav.

**Comment by NudeSpoons** [comment]
@gera2ld As @AdamBryantSkybox agrees that this is a duplicate of #100, I suggest that this issue be likewise given the `enhancement` label, plus a new `duplicate` label, and then closed.  I presume that only you can do so.

**Comment by gera2ld** [comment]
close as duplicate of #100
