### ISSUE TITLE
[BUG] Unable to save new script

### ISSUE THREAD

**Issue by vertigo220** [violentmonkey/violentmonkey#2244]
### Sequence of actions: 
1. Added Bypass_All_Shortlinks.user.js and named "Bypass All Shorteners"
2. Tried adding adsbypasser.lite.es7.user.js and naming "Ads Bypasser Lite" (though name doesn't matter, despite error suggesting usiing a different name) and disabling
3. Got error "A script like this is already installed. Please either use a different @name and @namespace here or edit that script instead."

### Expected result:  

I expect to be able to add more than one script. I added one, and when trying to add a second, it gives an error and won't add/save it.

#### Environment:
- OS: Windows
- Browser: Chrome [Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)
- Violentmonkey Version: 2.28.0

**Comment by tophf** [comment]
I can't reproduce the issue, the steps 1 and 2 work for me. The error says that you already have a script that has the same name+namespace, which can only happen if this is indeed so.
