### ISSUE TITLE
[BUG] latest github release link isn't detected

### ISSUE THREAD

**Issue by dvirtz** [violentmonkey/violentmonkey#2246]
### Sequence of actions: 
I'm publishing a userscript as a GitHub release asset. According to https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release, I can give users a link to the latest released script via `https://github.com/<owner>/<repo>/releases/latest/download/userscript.user.js`, but violentmonkey doesn't detect this link and doesn't suggest to install the script like it does with a link to the specific version.
For example, https://github.com/dvirtz/musicbrainz-scripts/releases/latest/download/setlistfm-musicbrainz-import.user.js is not detected while https://github.com/dvirtz/musicbrainz-scripts/releases/download/%40dvirtz%2Fsetlistfm-musicbrainz-import-v1.2.1/setlistfm-musicbrainz-import.user.js is.

### Problem: 
violentmonkey doesn't suggest to install the linked script

### Expected result:  
violentmonkey suggests to install the linked script

#### Environment:
- OS: Windows
- Browser: Chrome 131.0.6778.86
- Violentmonkey Version: 2.28.0

**Comment by tophf** [comment]
The first link doesn't work for me with or without Violentmonkey. It says `ERR_INVALID_RESPONSE`.

**Comment by dvirtz** [comment]
Thanks for the prompt response.
I didn't think you'd be so quick so I was cutting another release. The link should work now.

**Comment by tophf** [comment]
Thanks, the fix works for the first link now.

**Comment by dvirtz** [comment]
It also works for me with the beta release, thanks again
