### ISSUE TITLE
[Feature] access chrome.debugger from userscripts

### ISSUE THREAD

**Issue by divinity76** [violentmonkey/violentmonkey#2249]
**Motivation**

I want to generate click events with [isTrusted: true](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted)

**Proposed Solution**

Chromium-specific, give userscripts access to [chrome.debugger](https://developer.chrome.com/docs/extensions/reference/api/debugger) and [chrome.tabs](https://developer.chrome.com/docs/extensions/reference/api/tabs). This would require adding `permissions: debugger, tabs` to manifest.yml , and make access opt-in like 
```js
// @grant    chrome.debugger
// @grant    chrome.tabs
```
then userscripts can generate "trusted" click events like
```js
chrome.tabs.query({ currentWindow: true }, function(tabs) {
    const target = { tabId: tabs[0].id };
    chrome.debugger.attach(target, "1.2", function() {
        const x = 557;
        const y = 204;
        const button = "left";
        chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mouseMoved", x, y });
        chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mousePressed", button, x, y, clickCount: 1 });
        chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mouseReleased", button, x, y, clickCount: 1 });
    });
});
```
-or- maybe make a 
```js
GM.click=function(x, y, button = "left") {
    chrome.tabs.query({ currentWindow: true }, function (tabs) {
        const target = { tabId: tabs[0].id };
        chrome.debugger.attach(target, "1.2", function () {
            chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mouseMoved", x, y });
            chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mousePressed", button, x, y, clickCount: 1 });
            chrome.debugger.sendCommand(target, "Input.dispatchMouseEvent", { type: "mouseReleased", button, x, y, clickCount: 1 });
        });
    });
};
```
api, if giving direct chrome.debugger access is scary.
(unfortunately this is Chromium-family specific, I don't have a solution for Firefox users)
**Use Cases**
automation

**Comment by tophf** [comment]
Generally we don't add browser-specific features, but even if we add it, this permission cannot be optional and it's insanely powerful, so it's likely to be even rejected on the extension web store due to our extension's purpose not being debugging-related.

**Comment by tophf** [comment]
Try overriding EventTarget.prototype.addEventListener so that your listener sets isTrusted and calls the original listener. You'll also have to override removeEventListener and maintain a Map between the original listener and your override.
