### ISSUE TITLE
[Feature] access key/id of opened sub-tabs

### ISSUE THREAD

**Issue by RoadRoller01** [violentmonkey/violentmonkey#2253]
**Motivation**

I want to open multiple tabs with the same parent tab href
and be able to communicate with each one individually.
 
**Proposed Solution**

I want `GM_openInTab` to also return the key/id of the tab,
and be able to get the key/id as a child tab 
Suggestions: `GM_getTabId `or through `GM_info`

So i can communicate with theme via `setValue`/`getValue` separately.

I have tried various methods, and I believe this is the only solution.
Nonetheless, if you have another solution, I would love hearing it

**Use Cases**

I will write it next time if you insist, I need to go now

**Comment by tophf** [comment]
Why can't it be done with [GM_addValueChangeListener](https://violentmonkey.github.io/api/gm/#gm_addvaluechangelistener)?

**Comment by RoadRoller01** [comment]
Since there are multiple instances or tabs,
let’s say two; it would be impossible for the parent to send a message to the first tab and a different message to the second tab without a unique identifier. To solve this, we can assign a value using the tab ID as a key. Each child tab can then use `GM_addValueChangeListener` with its respective tab ID as the key to listen for changes.

**Note**: In my use case, all sub-tabs share the same href/URL, and their number is dynamic (not fixed).

**Comment by tophf** [comment]
While your idea would make it easier but you can already do it. You can generate a random id using `Math.random()` or `peformance.now()` in the main tab's GM_addValueChangeListener:

```js
const tabs = {};
GM_addValueChangeListener('handshake', (name, old, val, remote) => {
  if (remote && val) {
    const id = performance.now();
    tabs[id] = val;
    GM_setValue(name, id);
  }
});
```

and the new tab initiates a handshake:

```js
(async () => {
  while (GM_getValue('handshake')) // another tab is doing it now
    await waitForNewValue('handshake', 1000); // the communication time is ~1ms but the tab may be blocked by JS script
  GM_setValue('handshake', true);
  const myId = await waitForNewValue('handshake', 1000, true);
})();
function waitForNewValue(name, timeout, remove) {
  return new Promise(resolve => {
    const timer = timeout && setTimeout(cb, timeout);
    const id = GM_addValueChangeListener(name, cb);
    function cb(key, old, val) {
      GM_removeValueChangeListener(id);
      if (timer && key) clearTimeout(timer);
      if (remove) GM_deleteValue(name);
      resolve(val);
    }
  });
}
```

**Comment by tophf** [comment]
To send messages to a tab you would use GM_addValueChangeListener with another value in storage e.g. `'broadcast'` for broadcasting and `'message:' + myId` to target an individual tab.

To track the existence of tabs you can use `navigator.locks` API as they all belong to the same origin.

**Comment by RoadRoller01** [comment]
The order of tabs will be lost

**Comment by tophf** [comment]
Well then open tabs sequentially one by one, it'll simplify the code greatly as there will be no need to await on handshake.

**Comment by RoadRoller01** [comment]
if they wore three tabs, the second and third will fight for the second place

**Comment by tophf** [comment]
Not if you open them *sequentially* as I suggested.

**Comment by RoadRoller01** [comment]
yes, but it not an automation or bot userscript, its user script, so the time between opening tabs depends to the user speed, and it will be unstable.

**Comment by tophf** [comment]
A user can't open two tabs simultaneously or faster than 1ms. Even if some superhuman manages to do it faster than 50ms, it's not an issue if you run your script at document_start.

The problem with ordering may be caused by a network delay, which could cause the 2nd tab to start loading later than the 3rd especially if the 3rd one is focused. To account for that you can try sending `performance.timeOrigin` instead of `true` in the handshake and then sort the map accordingly.

**Comment by RoadRoller01** [comment]
Nice, I will give it a try.
