### ISSUE TITLE
[BUG] Userscripts still execute after Violentmonkey is toggled off

### ISSUE THREAD

**Issue by clem2** [violentmonkey/violentmonkey#2257]
### Sequence of actions: 
1. Install a userscript
2. Open page it applies to
3. Toggle off Vm
4. Reload page or open page in new tab

### Problem: 
The userscript is still executed despite Vm being toggled off. This issue first appeared in v2.22

### Expected result:  
Userscripts are actually disabled when Vm is toggled off
#### Environment:
- OS: Windows 10
- Browser:  Firefox 133.0.3
- Violentmonkey Version: 2.29

**Comment by clem2** [comment]
The issue is still present with a new browser profile.  It happens on this page: [fedex](https://www.fedex.com/fedextrack/?trknbr=111111111111&trkqual=2460573000~111111111111~FX)
```
// ==UserScript==
// @name		Fedex Tracking
// @match		https://www.fedex.com/wtrk/track/*
// @require		https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js
// @require		https://gist.githubusercontent.com/kepkin/ff99090c410ab1b5c8fa/raw/a1e229b38cb6eb169556ae9b5e751e5c81d59929/waitForKeyElements.js
// @version		0.1
// ==/UserScript==


waitForKeyElements('#shipmentIdentifier', j => { document.title = j[0].textContent; }, true);

```

**Comment by tophf** [comment]
I still can't reproduce it and looking at the source code it can't depend on the site.

**Comment by tophf** [comment]
> This issue first appeared in v2.22

Can you try both [2.21](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.21.0) and [2.22](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.22.0) as a temporary extension? It can be loaded on `about:debugging` page. To restore the normal extension you can restart the browser, i.e. don't press the remove button for the temporary extension.

**Comment by clem2** [comment]
Same result. BTW, I'm using portableapps.com Firefox, and this issue also happens with tete009's Firefox build in portable mode.

**Comment by tophf** [comment]
Same result in 2.21 or what?

**Comment by tophf** [comment]
I found one theoretical possibility where it can happen and fixed it: [vm.zip](https://github.com/user-attachments/files/18184384/vm.zip)
Does this build fix it for you?

**Comment by tophf** [comment]
BTW I just reproduced the problem in the portable Firefox, and my fix worked for me.

**Comment by tophf** [comment]
Until a fixed build is published you can disable `Alternative page mode in Firefox` in the options -> `Advanced` section.

**Comment by tophf** [comment]
Another workaround is to add an empty script that with `@run-at document-start`.
