### ISSUE TITLE
[BUG] MenuCommand not registering with Chrome(Opera or Brave)

### ISSUE THREAD

**Issue by Aphexus** [violentmonkey/violentmonkey#2258]
Similar or same to this issue:
https://github.com/Tampermonkey/tampermonkey/issues/1506

The code works in without issues in Tampermonkey.

So this seems to be a patch VM missed.

It does show it from the drop down, as in the TM issue but I can't use my code as such because it requires window/page focus and clicking on the extension loses focus(and window.focus() does not work).

Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
    at Object.cb (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/foo.user.js#6:66:25)
    at Boolean.Command (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/sandbox/injected-web.js:1:15998)
    at Object.onHandle (chrome-extension://opokoaglpekkimldnlggpoagmjegichg/sandbox/injected-web.js:1:3136)
    at chrome-extension://opokoaglpekkimldnlggpoagmjegichg/sandbox/injected-web.js:1:3968

**Comment by tophf** [comment]
> The code works in without issues in Tampermonkey.

Doesn't work for me in Tampermonkey:

```js
GM_registerMenuCommand('foo', () => {
  navigator.clipboard.writeText('text').then(() => alert('OK'), err => alert(err.message));
});
```

**Comment by Aphexus** [comment]
> I don't see how this relates to the mentioned issue based on your error stack. I also don't understand how the error stack relates to "MenuCommand not registering".
> 
> **Please fill the issue template to make things clear.**
> 
> According to your error stack, it seems you had issues with `navigator.clipboard.writeText`, in that case you may try `GM_setClipboard` instead.


If you read the text I wrote right before the error message you might understand. I will post it here again for completeness and to highlight it so it is not miss it and so it is very very clear as I wouldn't want to violate any rules: ### **_"It does show it from the drop down, as in the TM issue but I can't use my code as such because it requires window/page focus and clicking on the extension loses focus(and window.focus() does not work)."_**

The simple fact is, regardless of the error message, is that the RMB on a page DOES NOT have the registered command. Ignore the error message COMPLETELY if it confuses you. It is irrelevant to the actual problem except that VM is realizing I'm registering a command.

The question is why is it not showing in chrome browsers but works in firefox.

How much clearer can I be?

**Comment by Aphexus** [comment]
> > The code works in without issues in Tampermonkey.
> 
> Doesn't work for me in Tampermonkey:
> 
> ```js
> GM_registerMenuCommand('foo', () => {
>   navigator.clipboard.writeText('text').then(() => alert('OK'), err => alert(err.message));
> });
> ```

Yes, but are you doing it in Chrome or Firefox? It works fine in Firefox. As the title says, it does not work in chrome so you are just demonstrating the issue also happens on your end. It does work in Firefox unless you think I'm a liar or trickster.

**Comment by gera2ld** [comment]
> How much clearer can I be?

Oh really? You deleted our issue template, failed to provide browser information, left an error stack without any useful explanataion, wasted our time guessing what you need, and now you're behaving like this?

Please fill the issue template (explain what is expected and what is the actual result, and provide a minimal reproduction) if you want to continue.

**Comment by Aphexus** [comment]
> > How much clearer can I be?
> 
> Oh really? You deleted our issue template, failed to provide browser information, left an error stack without any useful explanataion, wasted our time guessing what you need, and now you're behaving like this?
> 
> Please fill the issue template (explain what is expected and what is the actual result, and provide a minimal reproduction) if you want to continue.

Yeah, you want me to do all the work for you. Should I also hunt the bug down and write the patch? If you can understand the issue from the title then you maybe need to figure out a different line of work.

Or should I come to your house and hold your hand and push F8 to step through the debug lines code for you? Maybe I can put my 20TB's of drive space into an image and mail it to you so you can have my complete system to you can see. I'll spend 100 hours making a tutorial how to open chrome and what GM_registerMenuCommand does. 

Which one should it be? I could also dress up in a girly outfit and shave my legs if it motivates you more? Maybe if you make a larger number of hoops to jump through it will be more productive and exciting?

Good news is that I don't really care. If you want your software to have simple bugs in it then that is on you, not me. But if I wanted to do all the work I would fork the project or just write my own extension.

You do you and I'll do me but one thing I won't do for you is be your eyes and brain so stop asking.

[Of course let us know the predicable obligatory response archetype for posterity]

**Comment by tophf** [comment]
Gee, so much bile and sarcasm, I don't think there's any point in continuing. Maybe someone more cooperative else will report this problem if it really exists.

**Comment by tophf** [comment]
Now that we've silenced this immeasurably valuable source of information, I can only guess the user was invoking the command from the context menu on the web page, because it activates the document, thus enabling the clipboard API per the web specification. AFAIK there's no way to activate the document when invoking from the popup because that is a different window and extensions don't have an API to focus the tab's contents (we can only focus the tab as a whole).

So, the issue should be solved when Violentmonkey implements commands in the context menu: #1407.
