### ISSUE TITLE
[Feature] Violentmonkey for Pale Moon

### ISSUE THREAD

**Issue by SecondCityOsD** [violentmonkey/violentmonkey#2261]
Pale Moon browser is in dire need of a little bit of attention from you to fork your extension to its browser engine. It's engine and the way the extensions works on the browser will require very minimal maintenance on your end.

Pale Moon is based on Firefox version 52 and it supports XUL and XPCOM (Legacy Firefox addons) which is much superior to MV2.
https://en.wikipedia.org/wiki/Pale_Moon

It doesn't share the same API as the current Firefox engine.

**Motivation**

There is absolutely no userscript manager for Pale Moon browser, let alone an equivalent to Violentmonkey there.

**Comment by tophf** [comment]
It's not feasible because it'll require rewriting most of the extension. The classic Firefox engine always had Greasemonkey userscript extension, so maybe Palemoon can use it too.
