### ISSUE TITLE
[BUG] Letters are randomly replaced with numbers in export zip file name

### ISSUE THREAD

**Issue by NewsGuyTor** [violentmonkey/violentmonkey#2262]
### Sequence of actions: 
1. Try to customize the export file name
2. Type the wrong letter
3. Get a number instead

Just look at this, I'm typing every letter from a-z: 

https://github.com/user-attachments/assets/72fba6c2-e9b2-4938-8cd1-3554344d5f32

Kinda cool and weird bug

#### Devtools console contents:
Nothing

#### Environment:
- OS: Windows and macOS
- Browser: Firefox Developer Edition 134.0b10 (64-bit)
- Violentmonkey Version: 2.29.1

**Comment by tophf** [comment]
The name is a pattern with "magical" syntax e.g. `mm` is replaced with minutes, `ss` with hours. Click the `(i)` icon to see the documentation. To prevent magic behavior you can surround the text like `[text]`.
