### ISSUE TITLE
Auto-refresh current tab when Userscript is switched on

### ISSUE THREAD

**Issue by Filyus** [Violentmonkey/Violentmonkey#23]
Hello! Can you add option to auto-refresh current tab when Userscript is switched on?

**Comment by gera2ld** [comment]
I don't think this is necessary though, this will be taken into account in the future. BTW, I am wondering in what cases will a user switch a script on and off frequently?

**Comment by Filyus** [comment]
It is very necessary when writing script to compare page with and without script.
