### ISSUE TITLE
VM, uMatrix, WebExt wierdness/conflicts

### ISSUE THREAD

**Issue by atomGit** [violentmonkey/violentmonkey#231]
### What is the problem?
after first installing the [Linkify Plus Plus](https://greasyfork.org/en/scripts/4255-linkify-plus-plus) VM script, the script wasn't working [on a test page](https://rawgit.com/eight04/linkify-plus-plus/master/demo/demo.html) - VM seems to have been blocked because disabling uMatrix solved the problem

however, for whatever reason, VM started working at some point with uM enabled and no rule changes

i've noticed other oddities with VM as well - at one point it wouldn't load any scripts and, as i recall, i had to disable it, then cancel the disable

also when trying to install a script from a URL, it always errors out

i suspect this is possibly more involved than just VM here - this crap going on with the transition to WebExt is raising all kinds of havoc and uBlock O and uMatrix seem to be right in the middle of some of that

### How to reproduce it?
1. remove all traces of VM and install fresh
2. install the Linkify script above
3. test it on the test page linked to above

### Environment
- Browser: FF v55.1.0.1
- Violentmonkey version: 2.8.10f
- uMatrix version: 1.0.0 (legacy)
- OS: Mint Linux

**Comment by zJelly** [comment]
It's uMatrix blocking the `moz-extension-scheme` class, which Firefox added for WebExtensions.
Similar issue here: https://github.com/WaldiPL/webpageScanner/issues/8
It was fixed for me by adding `matrix-off: moz-extension-scheme true` to my rules (and later entirely bypassed by switching to the WebExtension version of uMatrix).

**Comment by atomGit** [comment]
i already had that rule in uM so there must be some other weirdness happening 

maybe i shouldn't have opened a ticket - i think i have to be content with waiting until the dust settles with all this WebExt stuff

**Comment by fsproede** [comment]
@atomGit The demo page already includes the linkify script. There is no VM needed for this page. ;)

Try it on http://yellow5.us/firefox/testcases.txt

**Comment by atomGit** [comment]
whatever was going on here isn't going on anymore so i'll close ths
