### ISSUE TITLE
Close the popup after opening dashboard

### ISSUE THREAD

**Issue by CrendKing** [violentmonkey/violentmonkey#238]
### What is the problem?
Normally for an addon, after opening the option page, the popup window is closed, since user clearly wants to focus on the option page, and the popup just blocks the vision. This is not the case of Violentmonkey on Firefox. On Chrome, the popup automatically closes. Looks like a bug.

### How to reproduce it?
1. Click addon button to bring out popup.
2. Click "Open Dashboard".

### What is the expected result?
After the dashboard opened, popup should hide.

### What is the actual result?
After the dashboard opened, popup lingers.

### Environment
- Browser: Firefox
- Browser version: 58 nightly
- Violentmonkey version: v2.8.13f
- OS: Windows 10

**Comment by gera2ld** [comment]
This is a browser behavior which cannot be controlled by the extension. Perhaps you can file a issue for Firefox.

**Comment by CrendKing** [comment]
Maybe you misunderstand my question. One way to achieve the behavior is to add `window.close()` after `browser.runtime.openOptionsPage()`:

`
diff --git a/src/popup/views/app.vue b/src/popup/views/app.vue
index 61d4713..694d6ca 100644
--- a/src/popup/views/app.vue
+++ b/src/popup/views/app.vue
@@ -110,6 +110,7 @@ export default {
     },
     onManage() {
       browser.runtime.openOptionsPage();
+      window.close();
     },
     onFindScripts(item) {
       let domain;
`

I'm not sure why Chrome does not require this line to close the popup. I think it would be better to have consistent user experience across all browsers.

**Comment by gera2ld** [comment]
@CrendKing I see, it's good to be fixed that way.
