### ISSUE TITLE
Feature request: More editor options?

### ISSUE THREAD

**Issue by CrendKing** [violentmonkey/violentmonkey#242]
### What is the problem?
CodeMirror provides many options such as indentUnit, tabSize, theme, highlight, etc. Plan to support some of the essentials?

### How to reproduce it?
1. Open any script
2. Try to find option to, say change indentation spaces

### What is the expected result?
Some options to control the editor. For example, the one [Stylus](https://github.com/openstyles/stylus) provides (Stylus uses CodeMirror as well).
The "Custom Style" editor should share the options as well.

### What is the actual result?
Currently Violentmonkey does not provide any option to control the editor.

### Environment
- Browser: Firefox
- Browser version: 58 nightly
- Violentmonkey version: 2.8.13
- OS: Windows 10

**Comment by gera2ld** [comment]
You can append any CSS in "Custom Style", including that applied to CodeMirror.

I don't think it a good idea to edit or develop scripts in such an editor, because it can never be as convenient and powerful as your local editor. Since [an alternative is provided](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/), I don't think it necessary to provide a lot of options for an editor.

**Comment by CrendKing** [comment]
About the custom style, I meant if the script editor can be configured to have 4 space indentation, that editor should have 4 space indentation too.

I personally would prefer having the options, since CodeMirror already have those features implemented. Of course, if you feel the editor options are not needed, feel free to close the issue.

**Comment by Mattwmaster58** [comment]
> I don't think it a good idea to edit or develop scripts in such an editor, because it can never be as convenient and powerful as your local editor. Since an alternative is provided, I don't think it necessary to provide a lot of options for an editor.

This option isn't available in Firefox though that might get [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960) eventually. Besides, I think features like auto completion would be useful for quick edits. Alternatively, you could use a lighter editor like [Ace](https://ace.c9.io/) which supports just the basics

**Comment by Herohtar** [comment]
A few editor options would be nice. It's very convenient to be able to edit the script in place instead of copying it to/from somewhere else. If possible some syntax checking would be a great feature.
