### ISSUE TITLE
firefox issue with adsbypasser 6.2.1 version

### ISSUE THREAD

**Issue by maszd** [violentmonkey/violentmonkey#244]
### What is the problem?
all script just deleted after installed adsbypasser scripts version 6.2.1 

### How to reproduce it?
1. install adsbypasser from https://adsbypasser.github.io/
2. select full or lite version
3. close firefox and open again, all script just deleted

### Environment
- Browser: Firefox 
- Browser version: 56.0.1
- Violentmonkey version: v2.8.13
- OS: Windows 7 64bit

**Comment by KingThunder** [comment]
What antivirus do you use?

**Comment by maszd** [comment]
thanks, yes iam use eset nod32 8, problem only on firefox but working fine with chrome.

**Comment by tophf** [comment]
This is not something that can be handled by Violentmonkey, AFAICT.
