### ISSUE TITLE
Version 2.8.14 Not Working in Chrome

### ISSUE THREAD

**Issue by cyberrufus** [violentmonkey/violentmonkey#249]
### What is the problem?
Updated to 2.8.14 and scripts don't work in Chromium browsers.
### How to reproduce it?
1.Update extension
2.Visit page that uses script.
3.Script not functioning.

### What is the expected result?
Script working.
### What is the actual result?
Script not functioning.
### Environment
- Browser:Chrome Stable/Dev/Canary All three tested.
- Browser version:Chrome
- Violentmonkey version:
- OS:Win10 x64

**Comment by cyberrufus** [comment]
New version not functioning in Firefox either.

**Comment by matoro** [comment]
Yup broken as well here.  Firefox 56.0.2 on Linux x64.  So it's not an OS problem.

**Comment by Burnyx** [comment]
Can confirm doesn't work after the last update.

**Comment by bhauer** [comment]
Behavior is presently sporadic in Firefox 57b12 on Windows 10. When userscripts fail to run, refreshing the page several times and/or clicking on the Violentmonkey toolbar button and then reloading seems to eventually get userscripts to resume working.

**Comment by trobotham** [comment]
having this issue in FF 57 dev edition as well on macos, currently works fine in no containers but when using containers, everything is broke.

**Comment by thedward** [comment]
None of my scripts are working, Chrome on Linux.
