### ISSUE TITLE
功能建议：“为此站点查找脚本”功能使用基础域名

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#25]
建议在点击“为此站点查找脚本”时使用基础域名（base domain）而非当前完整域名进行搜索。
例如： 

* `tieba.baidu.com` -> `baidu.com`
* `item.taobao.com` -> `taobao.com`

可以使用 http://www.publicsuffix.org/ 找基础域名，具体的工作方式可以参考 [火狐扩展 Greasy Scripts 的实现](https://github.com/Ede123/greasy-scripts/blob/73d85318ebcf51926f440924b69fad021651b3b8/content/greasyscripts.jsm#L57) 不过我不清楚这东西在 Opera 上是不是方便。

**Comment by gera2ld** [comment]
有道理，我以为这个功能很少有人用。不过贴吧这个其实还是用`tieba.baidu.com`比较好，很多脚本是贴吧专用的，正是因为这个当时才只去掉`www.`的前缀。

**Comment by gera2ld** [comment]
但是我觉得这个功能集成在扩展里不太好，要是有第三方页面直接提供这个功能就好了。
