### ISSUE TITLE
Userscripts not working on 4chan.org (and maybe on other sites)

### ISSUE THREAD

**Issue by guicale** [violentmonkey/violentmonkey#250]
### What is the problem?
Since the latest update (to version 2.8.14), no scripts work on 4chan.org and the JavaScript console displays the following:
`Loading failed for the <script> with source “blob:https://boards.4chan.org/fad8158a-fcd3-42da-8613-7dc0f38f84b7”.`
`Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://boards.4chan.org/fad8158a-fcd3-42da-8613-7dc0f38f84b7 (“default-src https://boards.4chan.org * data: 'unsafe-inline' 'unsafe-eval'”).`
This error makes it seem like the issue was caused by commit 796cddd9f19b1b627a7f4e2071e96d766d76eef4, so it probably affects other sites that apply the same [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) rules as 4chan.org. I have also tested that Violentmonkey still works on most other websites.

### How to reproduce it?
1. Install a userscript for 4chan.org (such as [4chan X](https://www.4chan-x.net/))
2. Visit any board on 4chan (such as [/g/](https://boards.4chan.org/g/))

### What is the expected result?
The userscript should work correctly

### What is the actual result?
Script never actually executes

### Environment
- Browser: Firefox
- Browser version: 56.0.1
- Violentmonkey version: 2.8.14
- OS: Arch Linux

**Comment by bnscv** [comment]
This update broke 'Mouseover Popup Image Viewer' on 4chan, and other sites, like Reddit too. Also, there's no option to configure the script anymore.
4chan X is working though.

**Comment by guicale** [comment]
It doesn't work for me and I've already tried reinstalling both 4chan X and Violentmonkey. I also use other userscripts on 4chan and none of them work. Are you using the latest version by ccd0?

**Comment by bnscv** [comment]
I'm using 4chan X's last stable version, 1.13.13.2. It seems to be working ok with Violentmonkey 2.8.14.
But, as I said, another script is not. So maybe there's something to do with that.

**Comment by guicale** [comment]
After some more testing, it seem like the cause of the issue was actually uBlock Origin, so I'm gonna close the issue now. Maybe you problem is also caused by uBlock Origin?

**Comment by bnscv** [comment]
It seems that even if I disable uBlock Origin on 4chan, Mouseover Popup Image Viewer still doesn't work. So I think it's not the same problem.
