### ISSUE TITLE
adblockers stopping script from performing

### ISSUE THREAD

**Issue by dlfsjdfjodifjsodifjsdo** [violentmonkey/violentmonkey#252]
ublock origin @ default settings stop 4chanX+violentmonkey from working. They are fully updated. All on firefox 56.0.2 . Had to whitelist 4chan.org in ublock origin for it to work.

works on tampermonkey by default so this is not an issue with the script.

**Comment by guicale** [comment]
To fix this without having to whitelist 4chan.org, add `4chan.org 4chan.org * allow` to your uBlock rules.

**Comment by BoBeR182** [comment]
Violentmonkey also works but some ublock filters can interfere with it on 4chan-x, putting on

@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'

on custom ublock filters solves it.

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
it's happening again. Same problem

**Comment by n00b42** [comment]
Tried the mentioned filter and some others on my own, can not get the following script to work on 4chan:
https://github.com/nicholas-s-perkins/4chanImageViewer/tree/master/bin

**Comment by KonoromiHimaries** [comment]
@gorhill

**Comment by tophf** [comment]
See https://violentmonkey.github.io/posts/inject-into-context/
