### ISSUE TITLE
不能工作

### ISSUE THREAD

**Issue by letterk** [violentmonkey/violentmonkey#253]
2.8.14 2.8.15 这两个新版不兼容firefox57
2.8.13正常

**Comment by gera2ld** [comment]
具体一点？我测试 v2.8.15 + Firefox 56/57/58 都正常啊

**Comment by letterk** [comment]
firefox57b10
https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
这个脚本失效

**Comment by gera2ld** [comment]
我特意装了个新的Firefox57b12，然后装这个脚本，一切正常。2.8.15应该已经修复了不兼容的问题。

**Comment by letterk** [comment]
升级到Firefox57b12, 2.8.15版本, 这个脚本确实不能工作
http://www.yunlaige.com/html/4/4384/4102436.html
比如这个网页, 正常情况下, 右下角应该会多出来一个圆形按钮

**Comment by letterk** [comment]
我看了下, 好像只有这个脚本有问题
其他脚本都还能工作, 我再向脚本作者反馈下

**Comment by rcyggdra** [comment]
Chromium 61.0.3163.100+暴力猴 2.8.15 也是很多脚本不能工作，
自动翻页，iqiyi的1080P之类的，换到Tampermonkey工作没问题。

**Comment by gera2ld** [comment]
确认bug了，编码问题 orz
