### ISSUE TITLE
Last updated text

### ISSUE THREAD

**Issue by grenzor** [violentmonkey/violentmonkey#257]
I think a "Last updated: *" under a script's author's name/version number can be useful to see when a script was last updated. Can it be added?

**Comment by gera2ld** [comment]
Good idea.

**Comment by grenzor** [comment]
Works fine for scripts that regularly update but noticed all scripts that have not updated since using latest version of VM are stuck on last updated "1m" forever (all are showing same date as updated 10/3/2017). Possible bug or maybe a way to fix this?

**Comment by gera2ld** [comment]
@grenzor Does it show the correct last update time when you mouse over the `1m`?

**Comment by grenzor** [comment]
All the scripts with 1m have the same updated date (from what I can deduce the date showing is the date I originally installed VM and added these scripts). I think this date makes sense but it should show the actual time from the installed date instead of "1m".

**Comment by gera2ld** [comment]
Oh, I see, it's not a bug, `1m` means `1 month`. Maybe it's better to show the actual days. I'll change it later.
