### ISSUE TITLE
在工具列下拉選單裡增加檢查腳本更新按鈕

### ISSUE THREAD

**Issue by hdd60311** [violentmonkey/violentmonkey#259]
目前要進控制台裡才能檢查更新感覺略累贅，希望能直接在下拉選單增加檢查更新按鈕
並且在未發現更新時也彈出提示窗口

**Comment by gera2ld** [comment]
为什么要经常手动检查更新？我希望弱化这个概念，用户正常情况下不需要自己去关心脚本更新的问题。

**Comment by hdd60311** [comment]
只是希望在想手動檢查時圖個方便罷了，至少在設定裡加個設置項讓需要者自行開啟這樣不為過吧

**Comment by gera2ld** [comment]
我感觉没有这个需求，如果其他人觉得有需要再打开吧
