### ISSUE TITLE
correct options for @run-at

### ISSUE THREAD

**Issue by seriych** [Violentmonkey/Violentmonkey#26]
you use "-" in 'document-start', 'document-idle' and 'document-end', but it must be "_": 'document_start', 'document_idle' and 'document_end'

**Comment by gera2ld** [comment]
You should look at the document first.
http://wiki.greasespot.net/Metadata_Block#.40run-at

**Comment by Crystal-RainSlide** [comment]
Try using HTTPS if anyone can't reach the link upon: https://wiki.greasespot.net/Metadata_Block#.40run-at
