### ISSUE TITLE
Import from tampermonkey

### ISSUE THREAD

**Issue by rayman89** [violentmonkey/violentmonkey#260]
Is it possible/could you make it possible to import the exported zip scripts from tampermonkey on violentmonkey?

**Comment by gera2ld** [comment]
Maybe not. Actually Violentmonkey can import any zip file with `*.user.js` in it. Does this help?

**Comment by rayman89** [comment]
I tried but is not importing.

**Comment by rayman89** [comment]
New version fixed the issue.

**Comment by gera2ld** [comment]
Actually the new version has nothing to do with this... closing since it works.

**Comment by mustaqimM** [comment]
@gera2ld Importing a Tampermonkey zip doesn't work now, also there is no confirmation of what happened when importing, so the user can't know unless switching to the scripts tab.

**Comment by glubsy** [comment]
For people landing here after looking for importing from tampermonkey: it works just fine. 
Good work ViolentMonkey team!
