### ISSUE TITLE
// @noframes support

### ISSUE THREAD

**Issue by abpvn** [violentmonkey/violentmonkey#263]
### What is the problem?
Current violentmokey not support ``@noframes``

### Environment
- Browser: Opera
- Browser version: 48.0.2685.52 (PGO)
- Violentmonkey version: v2.5.7
- OS: Windows

**Comment by gera2ld** [comment]
Please note that Opera version has not been updated for a long time because the Opera team won't review the extension, it is too complicated and they have no time to review, as they said.
So if you want to use the new features, please install it from the Chrome Web Store.
