### ISSUE TITLE
Violentmonkey keeps messing up profile on firefox update

### ISSUE THREAD

**Issue by rayman89** [violentmonkey/violentmonkey#264]
A month ago when firefox 56 beta updated to 57 violentmonkey endded up messing the profile and itself not displaying it's scripts so I remade my profile from scratch and now with the update of firefox release 56.0 to 56.0.2 caused violentmonkey button to not appear anywhere. It's options page when oppen from the addon manager sometimes fail to lead and the import/export and vaccum buttons to not work. Uninstalling and installing the addon again does not work and I'm not willing to go to the hassle of remaking the profile again.

**Comment by gera2ld** [comment]
Violentmonkey did not and has no permission to mess the profile. I don't know why this happened but I don't think it has anything to do with the extension. Sometimes I just need to clean the profile to solve strange problems in Firefox. Sometimes even Firefox itself shows a message telling me to revert to a clean profile if it has been used for a time. I think it may have some compatibility issues on upgrades.

BTW, vacuum is buggy in the latest release and will be fixed soon.

**Comment by rayman89** [comment]
It only happens to me with this addon and I have a lot of addons intalled.

I dont think is expected behavior to be remaking your profile frequently. 

If you could check what is the issue relating firefox updates and violentmonkey problems, even if it's not the fault of the addon and it's firefox fault somehow, maybe there is some workaround or something to prevent it or a new bug to open on bugzilla. 

I really wanna use violentmonkey over tampermonkey but this issues prevent me to do so and it's a shame becasue I really like this addon.
