### ISSUE TITLE
Back button history lost with window.location.href

### ISSUE THREAD

**Issue by Luke-Baker** [violentmonkey/violentmonkey#267]
### How to reproduce it?
1. Install the following script:
```
// ==UserScript==
// @name window.location.href test
// @namespace Violentmonkey Scripts
// @match http://www.gocomics.com/*
// @grant none
// ==/UserScript==

var met = document.querySelector('head > meta[property="og:image"]');
if (met) window.location.href = met.content;
// same result with window.location.assign(met.content);
```
2. Right-click [this link](http://www.gocomics.com/fminus/) and choose Open in New Tab.

### What is the expected result?
The browser navigates to the image. The Back button remains available. This is how Greasemonkey 3.17 behaves.

### What is the actual result?
The browser navigates to the image, but the Back button is grayed out. Basically, it acts like `window.location.replace`

### Environment
- Browser: Firefox / Nightly / Opera
- Browser version: 56.0.2 x64 / 58.0a1 20171104100412 x64 / 45.0.2552.888 x64
- Violentmonkey version: 2.8.17 / 2.8.17 / 2.5.7
- OS: Windows 10

**Comment by gera2ld** [comment]
It's the default browser behavior. The current page will be added to history only if `location.href='...'` is from a user initiated action. Though I have not found a reference, it seems to be true after a few tests. See [stackoverflow](https://stackoverflow.com/a/1137633/4238335).

Closing as a won't-fix. I don't think we should change the default behavior.

As for Greasemonkey v3, it works in a completely different way which will not work in later versions of Firefox, so the results might be different.

**Comment by Luke-Baker** [comment]
> It's the default browser behavior. The current page will be added to history only if location.href='...' is from a user initiated action.

Huh. How weird and nonsensical. After testing with a local HTML file, it does seem to be the case. A script clicking an element isn't user-initiated action either, but thankfully that does retain Back button history.
```
// ==UserScript==
// @name window.location.href test
// @namespace Violentmonkey Scripts
// @match http://www.gocomics.com/*
// @grant none
// ==/UserScript==

var met = document.querySelector('head > meta[property="og:image"]');
var goto = document.createElement("a");
if (met) {
    goto.href = met.content;
    goto.click();
}
```
> As for Greasemonkey v3, it works in a completely different way which will not work in later versions of Firefox, so the results might be different.

They're not. In Nightly, Greasemonkey 4.1 beta2 — a webextension — retains the desired behavior.
