### ISSUE TITLE
Userscript functions in 2.8.13 but not 2.8.17

### ISSUE THREAD

**Issue by the-nothingman** [violentmonkey/violentmonkey#269]
### What is the problem?
https://openuserjs.org/scripts/Darkaeluz/webnovel.com_skip_video_ads
This userscript functions perfected in 2.8.13 but if violentmonkey is updated to 2.8.17 it ceases to function for an unknown reason

### How to reproduce it?
1.install 2.8.17 and userscript 
2. to to a page on webnovel.com with blocked chapters (ex as of this time https://www.webnovel.com/book/6838665602002005/24086330241774940/Throne-of-Magical-Arcana/The-Darkness-underneath-the-Explosion)

### What is the expected result?
ad should automatically unblock
### What is the actual result?
Nothing happens

### Environment
- Browser: Firefox
- Browser version: 56.0.2
- Violentmonkey version: 2.8.17
- OS: Windows 10

However when downgraded everything works as expected, I'm not sure what broken in the update.

**Comment by gera2ld** [comment]
In v2.8.17 the injection is delayed (see #256), and it seems to run into a bug of Firefox.

**Comment by gera2ld** [comment]
Upstream bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1408996>
