### ISSUE TITLE
"dcoument is not defined" sometimes occur if script set run-at document-start

### ISSUE THREAD

**Issue by smovie** [violentmonkey/violentmonkey#272]
### What is the problem?
"dcoument is not defined" sometimes occur if script set run-at document-start
### How to reproduce it?
1.
2.
3.

### Environment
- Browser: firefox
- Browser version: 57
- Violentmonkey version: 2.8.17
- OS: win7 x64

**Comment by gera2ld** [comment]
Cannot reproduce, need more info. At least the related code or context where the error occurs. Please reopen this issue if you have more details.
