### ISSUE TITLE
Scripts not working properly after page reload

### ISSUE THREAD

**Issue by mikhaelkh** [violentmonkey/violentmonkey#277]
### How to reproduce it?
0. Install [YouTube h264ify](https://openuserjs.org/scripts/nikisby/YouTube_h264ify)
1. Go to https://www.youtube.com/html5
2. Reload the page ignoring cache (Ctrl+Shift+R)
3. Reload the page (Ctrl+R)

### What is the expected result?
After steps 1, 2, 3 `WebM VP8` and `MSE & WebM VP9` should be red.

### What is the actual result?
After steps 1, 2 `WebM VP8` and `MSE & WebM VP9` are red.
After step 3 `WebM VP8` and `MSE & WebM VP9` are blue.

### Environment
- Browser: Google Chrome
- Browser version: 62.0.3202.89 (Official Build) (64-bit)
- Violentmonkey version: v2.8.18
- OS: Windows 10 x64 v1607 (14393.1770)

**Comment by gera2ld** [comment]
Related to #246 , I'll look into this.

**Comment by mikhaelkh** [comment]
* Browser version: 62.0.3202.94 (Official Build) (64-bit)
* Violentmonkey version: v2.8.19

No changes. After step 3 `WebM VP8` and `MSE & WebM VP9` are still blue.

**Comment by gera2ld** [comment]
This script requires `@run-at document-start`, which means *as soon as possible*. It might be run after the page scripts as injected in a web extension, leading to your actual result. It could be ensured to be run before the page scripts in Greasemonkey v3, but I don't think it the same in web extensions.
What Violentmonkey can do is to try to inject the script as soon as possible, in which case your actual result may still happen. In my test, `WebM VP8` and `MSE & WebM VP9` is red in most times.

**Comment by gera2ld** [comment]
Oh sorry, the released version has a bug, making it no difference with v2.8.18.

**Comment by gera2ld** [comment]
Can you confirm on v2.8.20?

**Comment by mikhaelkh** [comment]
@gera2ld, no bug on v2.8.20.
