### ISSUE TITLE
Script isn't loaded on first page load.

### ISSUE THREAD

**Issue by Zenivo** [violentmonkey/violentmonkey#279]
### What is the problem?
Youtube Center doesn't load in time. If I load a YouTube video, the script is unloaded, the video plays for a split second, then the page reloads and the script has succesfully loaded.
### How to reproduce it?
1. Load any YouTube video
2. You should see the video load.
3. The page then reloads.

### What is the expected result?
The page and script should immediately load.

### What is the actual result?
The page loads, the script doesn't. The page then reloads and the script is loaded.

### Environment
- Browser: Chrome
- Browser version: Version 62.0.3202.89 (Official Build) (64-bit)
- Violentmonkey version: v2.8.18
- OS: Windows 10

**Comment by BondiBear** [comment]
Same issue with FF57 64

**Comment by eberhardweber** [comment]
This also concerns Iridium. In my experience, if I open/restart Firefox with a Youtube page as an open tab, Violentmonkey doesn't have time to activate itself before the page actually loads, and as such, the script doesn't have time load either.

**Comment by BondiBear** [comment]
This applies to opening new tabs as well for the script 'Dollchan'.
Works with Tampermonkey, though.

**Comment by Zenivo** [comment]
Can confirm Tampermonkey works just fine.

**Comment by gera2ld** [comment]
Please provide links to the scripts.

**Comment by BondiBear** [comment]
[https://github.com/SthephanShinkufag/Dollchan-Extension-Tools](url)
[https://github.com/ParticleCore/Iridium](url)

**Comment by Zenivo** [comment]
https://github.com/YePpHa/YouTubeCenter

**Comment by tophf** [comment]
Seems to be fixed.
