### ISSUE TITLE
谷歌翻譯提示框擴展在特定站點無法正常工作

### ISSUE THREAD

**Issue by hdd60311** [violentmonkey/violentmonkey#280]
使用58beta3, 暴力猴2.8.18
火狐58開始暴力猴可以在原本受CSP問題影響的站點(Github、Twitter等)作用腳本了，不過[谷歌翻譯提示框](https://github.com/ningfei/Google-Translator-Tooltip-Expanded)這擴展測試在github雖然能顯示翻譯圖示但是觸發後會向下圖這樣卡在loading無法正常顯示翻譯，Twitter試過倒是能正常工作
![screenshot-2017-11-15 ningfei google-translator-tooltip-expanded](https://user-images.githubusercontent.com/5089290/32791375-d5219f98-c99b-11e7-816e-8ec784f31afc.png)

**Comment by gera2ld** [comment]
这个脚本用了`eval`，这是不允许的。

**Comment by hdd60311** [comment]
?這具體是啥意思，那怎麼在twitter就正常運作

**Comment by gera2ld** [comment]
@hdd60311 twitter的CSP限制没有github的严格，twitter的CSP头里有`'unsafe-eval'`，意思是允许在代码里执行`eval`，而github不允许。

暴力猴不会修改页面的CSP，所以如果页面禁止的话，这类代码是不会被执行的。

另外，从FF58开始，暴力猴只是可以注入用户脚本到页面了（在此之前暴力猴本身也无法在此类页面中运行），并不是允许在这些页面内随意地插入第三方的脚本或者执行`eval`。
也就是说，如果在暴力猴上安装了A脚本，而A脚本又强行注入一个B或者`eval`一个C，那个暴力猴只保证A能运行，B和C依然会受到CSP的限制而可能不被运行。
