### ISSUE TITLE
Support for jar:file://

### ISSUE THREAD

**Issue by thiesw** [violentmonkey/violentmonkey#281]
ViolentMonkey works fine for local files opened via `file://`
But it does NOT work for a file opened via `jar:file://`  (e.g. very ueful for local JavaDoc via  jar:file:///d:/Java/jdk-8u152-docs-all.zip!/docs/api/index.html)
The fix should be very easy: at the place where the URL protocol is checked (search for "file:" in source), adding "jar:" should do it.

**Comment by gera2ld** [comment]
Why is a userscript in a jar file?

**Comment by thiesw** [comment]
It is not the userscript in a jar file.
I open a URL `jar:file://....`   and an existing, installed userscript should be activated for this URL (this has a quite generic  `// @include       */allclasses-frame.html`)

**Comment by gera2ld** [comment]
According to match patterns [here](https://developer.chrome.com/extensions/match_patterns), no such protocol is allowed. And I cannot load such protocol in my browser. 😕

**Comment by thiesw** [comment]
Hm, you are right.
I web-searched a bit and `jar:file://`  (the whole "`jar:`" thing) seems to be a Firefox specific extension (see [here](https://www.fxsitecompat.com/en-CA/docs/2015/jar-protocol-support-has-been-disabled-by-default/)) - quite useful in my opinion.
So a have to use a tool like Pismo File Mount to mount a *.jar file as drive or directory and open via standard `file://`
(In Greasemonkey before WebExtensions this was very very easy to add, so my hope was similar in this case.)

**Comment by gera2ld** [comment]
Since this is a Firefox-only and likely deprecated feature (disabled by default), I think it won't be implemented in the near future.
