### ISSUE TITLE
Add polyfill for GM.* APIs

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#283]
It's cool to support `GM.*` APIs on the side of current ones. And TM had already do so in beta channel. And these APIs may be implement on top of current ones with a thin polyfill. So, maybe it's time to add such supports.

**Comment by Lomanic** [comment]
Related link on the Greasemonkey blog https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

**Comment by kkot** [comment]
Direct link to polyfill: https://github.com/greasemonkey/gm4-polyfill/

**Comment by ivysrono** [comment]
+1

**Comment by JuniorJPDJ** [comment]
+1 we need it
