### ISSUE TITLE
Empty Script Editor in Windows XP and Vivaldi

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#284]
I will understand that you close this as won’t fix because it’s outdated OS.
But I thought it was worth submitting it anyway.

### What is the problem?

I use Vivaldi on Windows XP, thus the latest version is 1.0.435.46 (outdated).
I have a bug that looks like #87.
When I install a script, the Script Editor is opened but just an empty grey window.
I can install and the script works.
When I click the </> button to see script code, the same empty grey Script Editor appears.
Code and settings tabs are visible but only settings has displayable content.

### How to reproduce it?
1. Launch Vivaldi for Windows XP (1.0.435.46)
2. CTRL+SHIFT+E, Install Violentmonkey 2.8.18
3. Install any user script

### What is the expected result?

Script should be displayed in Script Editor.

### What is the actual result?

It is not.

### Environment
- Browser: Vivaldi
- Browser version: 1.0.435.46 (last Windows XP version)
- Violentmonkey version: 2.8.18
- OS: Windows XP

**Comment by gera2ld** [comment]
It might be a style issue, I have met it in other old browsers (like Maxthon v4.4). It's better if you can attach a screenshot.

**Comment by thinkpad4** [comment]
I'm seeing that on a old version of Chrome too.  https://i.imgur.com/J7QWpwQ.jpg

**Comment by gera2ld** [comment]
@thinkpad4 Thanks, I can confirm it now.
The old browsers do not work well with `flex`. I'll look into this and try to find a workaround.

**Comment by thinkpad4** [comment]
Thank you very much

**Comment by thinkpad4** [comment]
What does Flex do?  and why can't older browser work well with it?

**Comment by gera2ld** [comment]
@thinkpad4 It's a relatively new CSS feature to build layouts on browsers. Web and browsers are developing very fast these years, there are many new features coming out and implemented on new versions of browsers. In old browsers, some of the new features has a workaround in a very complexed way, wasting a lot of time, some just can't work. That's why we don't like old browsers.

**Comment by thinkpad4** [comment]
Thank you for explaining

**Comment by jesus2099** [comment]
@gera2ld, once again, thank you **very** much!
You have updated my old XP machine!

**Comment by thinkpad4** [comment]
@gera2ld Thank you very much
