### ISSUE TITLE
Feature request: Added Firefox Sync as a Sync option.

### ISSUE THREAD

**Issue by winneon** [violentmonkey/violentmonkey#286]
It would be incredibly useful to existing Firefox users to implement Firefox Sync as a Sync option. The other options work fine, but in the interest of lesser services for more functionality, adding Firefox Sync seems like a no-brainer.

**Comment by gera2ld** [comment]
This is not an extension for Firefox at the first place.
On the other side, it seems not possible for a web extension to sync large data like scripts.
So this is a won't-fix.

**Comment by winneon** [comment]
Understandable. Thank you for responding so quickly!

**Comment by cellulosa** [comment]
how about syncing the url to the scripts?
