### ISSUE TITLE
[feature request] Script Grouping

### ISSUE THREAD

**Issue by grenzor** [violentmonkey/violentmonkey#287]
I think adding the ability for the user to create/move/delete groups can be useful. It is easier on viewing in the dashboard especially when there are many scripts and you want to group some together under one group name header because they are scripts for the same site, scripts that perform similar tasks etc.

**Comment by grenzor** [comment]
Just thought I would add some info to this as I didn't really explain in the top post how this would look like maybe this post might give a little better understanding of what I had in mind, which was for something like tab headers for each group.

So when Dashboard is opened it will look for example when 2 groups (Group1 & Group2) are created by user:
| **All** | **Group1** | **Group2** |
By default All will show all scripts, Group1 when clicked will show scripts grouped as Group1 and similar for Group2
Also users could choose if scripts can be in multiple groups. Tickboxes in the script's options could accomplish this I think like:
[ ] Group1
[ ] Group2

**Comment by gera2ld** [comment]
I think it's more of a `tag` than a `group`.
It's a good idea but I'm wondering if it's worth that work to add such a feature.
In my opinion, a normal user would just install some scripts and surf the Internet as usual. Sometimes they might open the dashboard and remove some of the scripts.
Here comes the question, why do users need to open the dashboard and manage their scripts very often?

**Comment by grenzor** [comment]
I agree that if you have only have a few scripts more likely most users won't really need this. Only after I started using more scripts (like 6-7+) did I realize it could be a useful thing to have. I'm not sure how many users use a lot of scripts but I would guess the more advanced/micromanaging users would be the ones using more. 

I don't know much programming and thought it would be a relatively simple tag/group feature but based on your comment I'm guessing it's not that simple. Either way my opinion is it's a useful feature for users who use a lot of scripts but I think it's best for you to decide if you think it is too much work to implement this feature mainly for advanced users.

**Comment by AWilyFox** [comment]
Advanced users who write their own scripts and who have many scripts installed open the dashboard frequently and would benefit from being able to tidy up scripts into groups. Ordinary users who don't write their own scripts, probably don't open the dashboard very much and probably wouldn't benefit much from grouping.

**Comment by AWilyFox** [comment]
Advanced users who write their own scripts and who have many scripts installed open the dashboard frequently and would benefit from being able to tidy up scripts into groups. Ordinary users who don't write their own scripts, probably don't open the dashboard very much and probably wouldn't benefit much from grouping.

Anyway it would be a nice feature (TM), and thanks Gerald for your great work on VM.

**Comment by Cyberavater** [comment]
Feature Request: Script customization by folder?
It'd be nice if I could customize scripts to different folders according to their usage.

**Comment by Cyberavater** [comment]
> Here comes the question, why do users need to open the dashboard and manage their scripts very often?

In my case, there are so many scripts and often I need to test and remove outdated/unusable scripts.
Thus, this is would be a very useful feature if you ask me. So, please re-consider about working on this feature if you have time for it that is.

**Comment by orionlee** [comment]
One possibility, without adding new concepts such as group, tag, folder etc. is to use the existing `@namespace`, `@match` / `@include`.

With the current UI, one can narrow to a group of related scripts by using the search code mechanism, e.g., using `/@namespace\s*the_name_to_narrow/` in code search. 

Similarly, one could possibly narrow down scripts for a particular domain with `/@(match|include).*domain_to_narrow/`.

---

With such schemes, possible enhancements would include:
1. allow users to specify namespace in custom metadata
2. Small UI tweak in dashboard to make filter by namespace match/include domain easier (without writing a regex every time)
3. In dashboard, an option to list scripts grouped by namespace / domain

**Comment by Crystal-RainSlide** [comment]
Personally I installed & wrote 100+ scripts in ViolentMonkey, and I managed-to-manage them though using a format like `sitename - scriptname` for script names, and massive sorting, and some css to make the scripts come in columns. I think I will out of tricks when the amount doubles. Search won't help any more if you have to use it for reaching almost every script out of a small reachable range.

Still personally, the classic Folder and Tag model, which can be seen in Firefox's bookmarks system and a fair lot of other softwares, works everytime for me. Folders do the separation and nesting, and tags do the filtering and provides some metadata.

A possible design in ascii, borders not included:
```
Folders

> Folder 1
> Folder 2
  > Subfolder 1
> Folder 3
[ ] Show all scripts
    from every folder

Tags

[ ] Tag 1             
[ ] Tag 2             
[ ] Tag 3             

[ ] Disable tags
```

After all, for users who don't need this feature, they may have a switch in the settings, and this feature can be turned off by default, if ViolentMonkey tends to fit them.

----

Will there be something like `@tags` in the metadata block in the future if the tag grouping is also accepted by other script manager 🤔?

**Comment by orionlee** [comment]
> Will there be something like `@tags` in the metadata block in the future 

Folder like UI can still be done with without `@tags` by grouping:
- `@namespace`
- domain names (the scripts work on), deduced from `@include` / `@match`

**Comment by mon-jai** [comment]
+1 on this

**Comment by Eikosa** [comment]
Was there a date when this feature was coming?

**Comment by cyfung1031** [comment]
@tophf  @gera2ld  When this will come? This issue 287 has been open for 6 years more.

**Comment by gera2ld** [comment]
Wow, time flies. I'll work on tags + searching enhancement + batch actions, resolving this issue too.

**Comment by cyfung1031** [comment]
> Wow, time flies. I'll work on tags + searching enhancement + batch actions, resolving this issue too.

Yes. I agree tagging shall help.

e.g. tags: youtube, twitter, broken.
One script can have multiple tags. Search by filter then can list them all. (e.g. broken or youtube)
there would buttons for the group, like "delete", "enable", "disable", etc.
(not sure multiple selection is needed or not)
(not sure searching multiple tags, e.g. broken + youtube, is needed or not)

**Comment by mon-jai** [comment]
Maybe also exporting/importing a group as `.user.js` files too? That would be useful for script authors.
