### ISSUE TITLE
Discard of encoding while drag-and-drop scripts

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#289]
### How to reproduce it?
1. Write JS code in any external editor with cyrillic characters inside (e.g in comments or string variables).
2. Save file in UTF-8 encoding.
3. Drag-and-drop this file into FF57 window while VM control panel is open.
4. VM will import this script with cyrillic characters being gibberish.

### What is the expected result?
I expext all symbols to be unchanged before and after installing script using drag-and-drop.

### What is the actual result?
Gibberish for non-English unicode characters.

### Environment
- Browser: Mozilla Firefox
- Browser version: 57
- Violentmonkey version: 2.8.18
- OS: Manjaro Linux

**Comment by gera2ld** [comment]
This is the browser behavior, the extension could not change the default encoding. You may either change that in your browser preferences or load the script via an HTTP server.

**Comment by soviet-man** [comment]
It is much-much more simplier to do Copy-Paste from editor to internal VM editor than running http server

**Comment by gera2ld** [comment]
@soviet-man It's not a bug of Firefox, just a default preference that does not fit everyone.
