### ISSUE TITLE
2.8.19 is also not working on csp websites.

### ISSUE THREAD

**Issue by rezad1393** [violentmonkey/violentmonkey#291]
2.8.19 is also not working.

you confused the order.
blobs are not run at csp pages. not the other way around.

use blobs for all websites. then use script.textContent for csp limited ones.

**Comment by gera2ld** [comment]
Using blob delays the first injection thus breaks some scripts. I'm sure using `textContent` won't work for CSP limited pages.

**Comment by rezad1393** [comment]
you changes something in 2.8.13 to 2.8.14 that wont work on csp websites.
I am tired of explaining it again and again .
I am no longer interested in this bug.
have fun
