### ISSUE TITLE
exclusions for single script

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#293]
I would like to have exclusions for single script in Violentmonkey.
Only methot is to add manually this: // @exclude  https://www.name.com*
I would prefer a graphical interface likeother "monkeys", is it possibile?
Thanks

**Comment by gera2ld** [comment]
You can add this in script settings, without change the code.

![image](https://user-images.githubusercontent.com/3139113/33171231-6d971064-d086-11e7-8747-9dcc2ccb7ca2.png)
