### ISSUE TITLE
[Bug] All Scripts Disappear every time I Quit Firefox 57+

### ISSUE THREAD

**Issue by pootz10** [violentmonkey/violentmonkey#296]
### What is the problem?
First of all I'd like to say this is a report.

Well, a few days ago I was searching for how to transfer all my greasemonkey userscripts to tampermonkey or violentmonkey since this [greasemonkey recommendation](http://www.greasespot.net/2017/09/greasemonkey-4-for-users.html)
By using the import function of tampermonkey I released that every time I quit FF my userscripts was disappearing, then I decided to try it on violentmonkey, which showed the same issue.

So I decided to ask help on tampermonkey github session creating [this topic](https://github.com/Tampermonkey/tampermonkey/issues/470) and we finally come to a solution, that was setting the code below on the addon debug console (addons:debugging)
`localStorage.setItem('#storage', 'localStorage')`
as this was tagged as a bug for tampermonkey creator and since I experienced the same issue on violentmonkey, I decided to support violentmonkey trying to use the same solution that was give to me there and the "solution" also worked for violentmonkey!
Now the scripts isn't disappearing after firefox quits, by setting to local storage.

So I'd like to let violentmonkey creator know about this too.

Some scripts of mine that worked on greasemonkey wasn't working on tampermonkey, while on violentmonkey they are doing fine.

### Environment
- Browser: Firefox
- Browser version: 57.0
- Violentmonkey version: v2.8.20
- OS: Windows 7

**Comment by xlollomanx** [comment]
This did not happened to me...same setup but on windows 10.

**Comment by flussence** [comment]
I'm having the same problem actually... on Chromium 63. One script I added months ago stays put, but if I add any now and restart the browser they vanish.

**Comment by TheBestPessimist** [comment]
I have also started having this issue: even though i'm syncing via google drive, now all my browsers have no userscripts available. I have lost them all :(

**Comment by tophf** [comment]
Closing as there was quite a few bugs in Firefox and Chromium back in 2017 that caused loss of db in other extensions as well.
