### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by Luke-Baker** [violentmonkey/violentmonkey#299]
### What is the problem?
Every time I close a tab, two instances of this error message pop up in the Browser Console. This doesn't happen with Violentmonkey disabled.

### How to reproduce it?
1. Close a tab.

### What is the expected result?
Closing tabs doesn't pollute the console with error messages.

### What is the actual result?
Two instances of `Error: Could not establish connection. Receiving end does not exist. (2) undefined` are logged to the console.

### Environment
- Browser: Nightly
- Browser version: 59.0a1 build 20171130101246
- Violentmonkey version: 2.8.20
- No scripts
- All other add-ons disabled
- OS: Windows 10 x64

**Comment by gera2ld** [comment]
Are you using the released version from AMO?

**Comment by gera2ld** [comment]
Oh, I see, it will be seen on Firefox if a message could not be sent successfully.

**Comment by GitCurious** [comment]
I am seeing this error with ViolentMonkey [2.9.1] in Firefox [59.0.2] and Waterfox [56.1]

is it something that I should be worried about or just a cosmetic glitch in the error console ?

**Comment by gera2ld** [comment]
@GitCurious It's just a warning when a broadcast has no listeners. It should be ignored and I'll try to fix this by suppressing the messages.

**Comment by GitCurious** [comment]
Thanks Gerald - I won`t worry about it now.

I only recently saw this message due to changing over to TM after realising the other two weren`t as good.
