### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by kuehlschrank** [Violentmonkey/Violentmonkey#30]
Opera 34.0.2036.31
Violentmonkey 2.1.10.4

Global functions like setTimeout() and alert() throw "TypeError: Illegal invocation" when `@grant` is not "none".

```javascript
// ==UserScript==
// @name         Test
// @include      *
// @grant        GM_setValue
// ==/UserScript==

alert("yo"); // doesn't work
```

Tampermonkey encountered the same issue starting from Chrome 47:
https://forum.tampermonkey.net/viewtopic.php?f=17&t=1324

**Comment by tiansh** [comment]
The same...

```javascript
// ==UserScript==
// @name setTimeout test
// @description no description
// @include *://*/*
// @grant GM_xmlhttpRequest
// ==/UserScript==

setTimeout(function () { alert('hello world'); }, 1000);
```

A possible workaround:

```javascript
setTimeout.bind(null)(function () { alert.bind(null)('hello world'); }, 1000);
```

**Comment by tiansh** [comment]
Thank you for fix this issue. When will the new version availiable from addons.opera.com ?

**Comment by gera2ld** [comment]
@tiansh already published.
