### ISSUE TITLE
New v2.8.21 is not working

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#300]
I disabled adblocker (uOrigin) and Privacy Badger but it is not working nevertheless.

Even this simple script is not wotking: 

```
// ==UserScript==
// @name YA.RU_test
// @namespace test
// @include https://ya.ru
// @grant none
// ==/UserScript==

console.info("YA.RU");
```
Yesterday (with v2.8.20) everything was fine.

**Comment by Apache02** [comment]
Confirm this bug. Not working on Firefox 56 and 57.

Error in browser's console (Alt+Ctrl+J):
> TypeError: l is not a function  injected.js:1:2369
