### ISSUE TITLE
GM_xmlhttpRequest should ask for username/password of HTTP authentication

### ISSUE THREAD

**Issue by JackieKu** [violentmonkey/violentmonkey#301]
### What is the problem?
When the site requires HTTP authentication (server returns 401 Unauthorized) and `withCredentials` is set to `true`, the browser built-in dialog should be displayed for the user to input the credential.
This is the behavior of legacy GreaseMonkey.

### How to reproduce it?
```
GM_xmlhttpRequest({
	method : 'POST',
	url : 'https://URL-THAT-REQUIRES-AUTHENTICATION',
	withCredentials: true,
        ...
});
```

### What is the expected result?
Ask the user for the credential via the browser built-in popup dialog.

### What is the actual result?
It fails without asking for credential.

### Environment
- Browser: Firefox Desktop
- Browser version: 57.0
- Violentmonkey version: v2.8.22
- OS: Windows 10

**Comment by gera2ld** [comment]
It is not supported since the request is sent from the background in a web extension. Perhaps you need to check the response status and header and prompt for user / password in your script.

**Comment by JackieKu** [comment]
I found it works as expected in Firefox Android. Perhaps we can file a bug of Firefox desktop?

**Comment by janekptacijarabaci** [comment]
The same result (Firefox 60 Nightly - 2018-02-20):
Greasemonkey 4.2
Tampermonkey 4.6.5703

Throws an error:
```
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE)
[nsIDOMWindowUtils.isParentWindowMainWidgetVisible]
nsPrompter.js:339
```

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1217876
(https://bugzilla.mozilla.org/show_bug.cgi?id=1217876#c45)

**Comment by tophf** [comment]
Extensions can't force the browser to show this dialog.
