### ISSUE TITLE
Doesn't run when JavaScript is disabled

### ISSUE THREAD

**Issue by AWilyFox** [violentmonkey/violentmonkey#302]
### What is the problem?
Violentmonkey doesn't seem to run userscripts when JavaScript is disabled for a site, for example, by using an addon such as uMatrix or NoScript to disable JavaScript. Being able to run userscripts even when JavaScript was disabled on a site is an essential use-case for me. It was one of the strengths of the old Greasemonkey that it could do this reliably.

### How to reproduce it?
1. Install Violentmonkey and uMatrix.
2. Install a userscript for a site.
3. Disable JavaScript for that site.
4. Visit a site where the userscript should be active.
4. Notice that the userscript is not run.
5. Enable JavaScript for that site
6. Visit the same site again.
7. Notice that the userscript is now run.

This is not compatible with the old Greasemonkey.

### What is the expected result?
VM should run userscripts even when JavaScript is disabled. This would make it compatible with the old Greasemonkey.

### What is the actual result?
Userscripts don't work when JavaScript is disabled.

### Environment
- Browser: Firefox
- Browser version: 57.1
- Violentmonkey version: 2.8.22
- OS: Mac OS X 10.13, Windows 8.1

**Comment by alphabug** [comment]
You can block JS from ub0's advanced user mode matrix and it won't affect VM userscripts -- so just allow all JS from uMatrix (if you still want to keep it for its other features) and block with ub0.  It's my current workaround until Firefox/uMatrix/VM rolls out a proper fix.

**Comment by mk-pmb** [comment]
This lack of feature is the primary showstopper for me atm.
Does anyone know whether Tampermonkey can do it?

What's ub0? Can't find it in Firefox addons.

**Comment by alphabug** [comment]
Yeah, sorry for the confusion, I meant uBlock Origin when I wrote ub0. I stuck with abbreviating it that way because of how it used to be branded when I started using it. Back in early 2015, when it first forked from uBlock, it went by names like uBlock° and uBlock₀.

In my brief test, Tampermonkey doesn't work with scripts disabled. I had to allow inline scripts for userscripts to run. Violentmonkey is able to bypass this and run with all normal page scripts disabled.

**Comment by mk-pmb** [comment]
Thanks! Since your last sentence

> Violentmonkey is able to bypass this and run with all normal page scripts disabled.

contradicts the first sentence from OP

> Violentmonkey doesn't seem to run userscripts when JavaScript is disabled for a site,

there may be a chance at least. I won't check it myself though, since I already solved my problem by just downgrading Greasemonkey.

**Comment by alphabug** [comment]
> contradicts the first sentence from OP

OP only looked at blocking with uMatrix and NoScript. As far as I know, only the combination of blocking scripts with uBlock Origin and running userscripts with Violentmonkey works in Firefox. I haven't tried Greasemonkey because they were slow to migrate to 57+ and were missing important features.

**Comment by Faberman** [comment]
I've updated from version 2.8.28 and noticed this behavior. This is really frustrating, so I downgraded back to 2.8.28 - it works even with disabled JS.

**Comment by Atavic** [comment]
uBo can solve this: https://github.com/violentmonkey/violentmonkey/issues/335#issuecomment-360348624

**Comment by Thorin-Oakenpants** [comment]
From https://github.com/ghacksuserjs/ghacks-user.js/issues/505#issuecomment-421750680

> > [ME] why does uBO blocking JS still allow usrscripts to work, but uM doesn't?
> 
> [GORHILL] No clue. I tried to find out how VM injects its user scripts but the code is all webpacked and minimized and just too tedious to step in, so best is just to ask the author of VM.

So on behalf of gorhill, I'll ask the question. Maybe the answer will provide a solution for uM to behave the same way as uBO. Thanks :)

**Comment by mk-pmb** [comment]
I'm not sure how/why this works or if it's even the right place, but telling by path names, this could be the injection code: https://github.com/violentmonkey/violentmonkey/blob/master/src/injected/utils/index.js#L21

**Comment by alphabug** [comment]
> 
> 
> I'm not sure how/why this works or if it's even the right place, but telling by path names, this could be the injection code: https://github.com/violentmonkey/violentmonkey/blob/master/src/injected/utils/index.js#L21

That is indeed the crucial injection code. uBO blocking + VM isn't as powerful as it used to be since Mozilla rejected the practice of injecting userscripts into CSP enabled sites. I'm currently using a modified VM that reverts 0d61d1f to continue injecting them as blobs and somehow bypassing CSP.

**Comment by chocolateboy** [comment]
Just encountered this with [this script](https://greasyfork.org/en/scripts/39308-digg-highlighter) and:

- Platform: Linux (Arch)
- uBlock Origin: 1.18.6
- Violentmonkey: 2.10.4
- Browser: Firefox 66.0.3

The userscript works if JavaScript is enabled/whitelisted for the domain. It doesn't work if JavaScript is disabled, though it does still appear in the "Matched scripts" menu.

Adding the [CSP workaround](https://violentmonkey.github.io/2018/11/23/inject-into-context/) fixes it, though the site itself doesn't use CSP:

```javascript
// ==UserScript==                                                                
// @name          Digg Highlighter                                               
// ...
// @inject-into   content
// ==/UserScript==
```
This issue may apply to all sites with JavaScript disabled, but I've only confirmed it on digg.com so far (I tend to have JavaScript whitelisted for sites I use userscripts on), though I now realize I've probably encountered the same issue (and same workaround) on at least [one other site](https://github.com/chocolateboy/userscripts/commit/9c26e2dae14f143532ee557904c2ea0d12f41074#diff-5283fc4c73455023c0e0c52433d90e6d) (Amazon).

**Comment by tophf** [comment]
See https://violentmonkey.github.io/posts/inject-into-context/
