### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by jarryson** [violentmonkey/violentmonkey#303]
Hope to support Safari and Edge.

Is it on schedule or someting?

**Comment by 2lei** [comment]
I also need this

**Comment by filbo** [comment]
See also Tampermonkey/tampermonkey#558 about changes in future Safari releases (tldr: looks like moving _further away_ from WebExtension support ?!?)

**Comment by FranklinYu** [comment]
Support for Safari App Extension seems possible: https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-536183545

**Comment by tophf** [comment]
Safari's own API and architecture for the extensions was already completely different from Chrome/Firefox, and now it's even more different, foreign, alien, and complicated. Only someone who's proficient in Safari API for apps/extensions could tackle this task, which is why `help wanted` label is there. The probability of such a person picking up this task is, let's be honest, almost zero.

**Comment by tophf** [comment]
Safari will support WebExtensions so now this is more doable.
https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by filbo** [comment]
> Safari will support WebExtensions so now this is more doable.

That isn't what they've said, not at all.  They will support WebExtensions _APIs_.  And from what I've seen, it's a spotty subset of them which will make compatibility fairly difficult.

They will not _at all_ support WebExtensions packaging (.zip with the Google-specified manifests etc.).  Whether your extension uses WebExtensions APIs or Apple private ones, either one will still have to be packaged as an 'App Extension', with an embedded Swift or Objective C binary; and packaging has to be done on an Apple device; and you have to pay $99/year developer program fee to be able to put apps in the Apple 'store'.

None of that is insurmountable, but if the effort to keep an extension compatible between Chrome & Firefox is a walk around the block, the effort to add Safari to the mix is a half-marathon.

**Comment by tophf** [comment]
Eek, indeed there's [too many things missing](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility) so this is still not worth the hassle.

**Comment by filbo** [comment]
I crudely compared the JS in a downloaded copy of VM, vs. the not-supported list in that link, and didn't see any outages.  But the scan was very crude.

Seems to me the barriers are the ridiculous wrong packaging and developer extortion.

**Comment by tophf** [comment]
* no WebRequestBlocking, no webRequest opt_extraInfoSpec, no webRequest.HTTPHeaders cookies = no GM_xmlHttpRequest
* no tabs.execute runAt = no `@run-at` in content mode

**Comment by filbo** [comment]
> no WebRequestBlocking, no webRequest opt_extraInfoSpec, no webRequest.HTTPHeaders cookies = no GM_xmlHttpRequest

VM doesn't use any of those as far as I can see, although it does request WebRequestBlocking in its manifest (perhaps so userscripts can use it?).  Would not expect GM_xmlHttpRequest() to need any of that.

> no tabs.execute runAt = no @run-at in content mode

... looks like a problem.  Not fatal to all uses, but limiting.

**Comment by tophf** [comment]
VM uses all of these. WebRequestBlocking, opt_extraInfoSpec are needed for GMxhr to work at all, the ability to override the `cookies` header is needed for the anonymous GMxhr mode and for userscripts that want to set a custom cookies header.

**Comment by FranklinYu** [comment]
> coupled with the exorbitant $99 fee it's the last straw.

Any idea whether side loading the extension is possible? If so we can distribute binary on GitHub.

**Comment by tophf** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by tophf** [comment]
Actually I'm closing this because having it open won't improve the near zero chance that someone will do it for us. This is one of those miraculous things that would be nice to have but there's no reason to expect them to happen in real life. If it happens, it happens.
