### ISSUE TITLE
Require local files

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#304]
Can I load local files? If I can what should I do for it. Because by default, this line does nothing

`// @require file:///home/username/script.js`

**Comment by gera2ld** [comment]
No. Besides security concern, a script is supposed to work on different devices, so it does not make sense to require a local file.

**Comment by soviet-man** [comment]
But in Greasemonkey it can be done
https://stackoverflow.com/a/13888886

So VM is not fully compatible with GM.

**Comment by gera2ld** [comment]
It's never fully compatible because they are based on different APIs with different permissions. Requiring local files can be implemented on Chrome but not Firefox because Firefox does not allow it, so even Greasemonkey v4.0+ might not support it.
