### ISSUE TITLE
gm_ function issue

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [violentmonkey/violentmonkey#307]
### How to reproduce it?
```javascript
// ==UserScript==
// @name        test
// @include     *://*/*
// @grant       GM_addStyle
// ==/UserScript==

window.alert("GM_addStyle is: " + typeof GM_addStyle);
if (false){ 
    //this code is not executed obviously
    function GM_addStyle(txt){ 
        //not important
    }
}
```

### What is the expected result?
GM_addStyle is: function 

### What is the actual result?
GM_addStyle is: undefined.  However, if you remove the ```if (false){...``` block entirely, you will get the expected "GM_addStyle is: function" alert box.

### Environment
- Browser:chrome
- Browser version: 64.0.3282.15 
- Violentmonkey version: 2.8.21
- OS:windows

Sorry I'm having a hard time giving a description to this bug because I have no idea why something like this would happen.  Basically GM_addStyle is undefined at the start of the script if the script contains a definition for a function of the same name even if that code is never actualized/ran.  In the example given, CM_addStyle should be defined because: 1- the function is never redefined.  2- the redefinition happens after the alert.

**Comment by gera2ld** [comment]
This is related to some basic knowledge of JavaScript... You can learn it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#Function_declaration_hoisting) (keyword: **hoisting**).

Closing since it has nothing to do with Violentmonkey.

**Comment by jscher2000** [comment]
Fortunately, GM_addStyle() is the least necessary and most easily replaced special function. For example:

```
function GHHbD_addStyle(txt){
    var s=document.createElement('style');
    s.appendChild(document.createTextNode(txt));
    document.body.appendChild(s);
}
```

Your prefix can be anything you like, and the Violentmonkey editor has find and replace.

**Comment by fsproede** [comment]
@glachancecmaisonneuve 
In ES2015 "undefined" **is** the expected result.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions#Block-level_functions

In previous versions the behaviour was unspecified. In FF `function GM_addStyle(txt)` was a function _statement_ (not hoisted), while in Chrome it was a function _declaration_ (hoisted).

http://kangax.github.io/nfe/#function-statements
http://www.i-avington.com/Posts/Post/javascript-hoisting-firefox-ifthen-statements
