### ISSUE TITLE
Number of running scripts on badge > total number of installed scripts

### ISSUE THREAD

**Issue by B00ze64** [violentmonkey/violentmonkey#308]
Good day.

Not sure if this new behavior or a bug, but I noticed recently that the badge on the ViolentMonkey icon shows more running scripts than I have installed scripts. For example, on https://start.duckduckgo.com, it tells me 6 scripts are running, but when I click on the ViolentMonkey icon, only 3 scripts are running. I think this is new; I had never seen more than 4 scripts running on a web page (I have 4 scripts installed) and recently I have seen the badge show up to 10 running scripts on some sites...

### Environment ###

- Browser: Firefox
- Browser version: 52 ESR
- Violentmonkey version: 2.8.22
- OS: Windows 7

**Comment by gera2ld** [comment]
It's the total number of scripts run in all frames in that tab. Perhaps we should only count scripts in the top level document?

**Comment by B00ze64** [comment]
Is this new behavior? If it's always been like this then it might be best not to touch it. What happens if you only count scripts running in top level, and there is a script that only runs in a frame but not in top level?

**Comment by gera2ld** [comment]
It's not a new behavior, but the count is not always correct in earlier versions. It means that sometimes scripts running in frames are not counted though they should be.
If we only count the scripts in the top level document and there is only a script running in a frame, we get zero.

**Comment by mikhaelkh** [comment]
@gera2ld IMHO you should give user the choice like in Tampermonkey: either put the number of running scripts instances or the number of unique running scripts.

**Comment by B00ze64** [comment]
> If we only count the scripts in the top level document and there is only a script running in a frame, we get zero.

Then it is better to leave things as they are, or as @mikhaelkh suggested, count the number of unique running scripts. Counting only top level, giving zero when scripts are only running in frames, is no good; the badge helps the user see if some scripts are running, in case something goes wrong the user can quickly see which extensions are modifying the webpage; zero is no good. I guess we should either close this bug, of make it a count of unique scripts, either way is good with me.

Best Regards,

**Comment by gera2ld** [comment]
Thanks @B00ze64 @mikhaelkh , I think it's a good to count either unique scripts or total number, I will add an option for this.
