### ISSUE TITLE
It is necessary to monitor change of the URL page

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#309]
### What is the problem?
Some sites can change the URL of the page without reload. Even if the new URL matches the user script, Violentmonkey will not activate it.
### How to reproduce it?
1. Install the script:
```
// ==UserScript==
// @name _TEST_
// @namespace _TEST_
// @match https://www.youtube.com/watch?*
// @grant none
// @noframes
// ==/UserScript==
unsafeWindow.console.log("_TEST_");
```
2. Go to [https://www.youtube.com](https://www.youtube.com).
3. Click on any video (note that the page URL now matches the script).

### What is the expected result?
A message will be displayed in the console.
### What is the actual result?
Nothing happens. But the message will be displayed if to reload the page.
### Environment
- Browser: firefox
- Browser version: 57
- Violentmonkey version:  2.8.22
- OS: windows 7

**Comment by gera2ld** [comment]
I don't think it's Violentmonkey's job to do this. Instead the script should do it.

Once a script runs in a page, it cannot be removed. In most cases, a script is not supposed to run repeatedly in a page. So if the page URL changes without reload, the JavaScript context is not changed, and scripts should not be re-injected.

Closing as a won't-fix.
