### ISSUE TITLE
2.2.0 = not work!

### ISSUE THREAD

**Issue by led9** [Violentmonkey/Violentmonkey#31]
![1](https://cloud.githubusercontent.com/assets/7848312/11873668/a0c23524-a4fd-11e5-94ac-528de8badeb7.jpg)

It does not respond to mouse clicking.
my scripts do not work!
I can not open / edit any of the script:
If I try to create a new script, then after clicking on the "Save" / "Save and Close" = nothing happens. After clicking the "close" message appears - "changes are not saved, quit?"

Opera_beta_30.0.1835.49

p.s. Maybe you have a pest wound up there?

**Comment by gera2ld** [comment]
I have tested it on the latest Opera and Chrome, and it all works.
Maybe you should upgrade your Opera. The new version has used a few APIs that are only supported by the latest Opera or Chrome. I will add polyfills for these APIs in the next release.
