### ISSUE TITLE
建议 请考虑提供标签控制接口

### ISSUE THREAD

**Issue by woolition** [violentmonkey/violentmonkey#310]
### 原因
兼容了GreasyMonkey提供的API是好事,但是一个扩展如果只是提供了别人已经实现了的接口,那永远只能是落后于原来的扩展.
应该有自己的特色才能提高市场占有率.所以,请考虑提供标签控制接口.
比如,
1 获取当前标签 ID,index 等功能
2 切换标签功能
3 移动标签功能

**Comment by gera2ld** [comment]
标准是需要大家一起创建，一起遵守的，自己搞些特立独行的东西并没有什么意义。
标签控制功能权限太高了，滥用容易影响体验或者导致安全问题，我觉得userscript应该是在页面内提供辅助功能的脚本，如果需要那么高的权限，建议直接用extension来实现。
