### ISSUE TITLE
Can not update script

### ISSUE THREAD

**Issue by T1mL3arn** [violentmonkey/violentmonkey#311]
### What is the problem?
Can not update script, if it is self-hosted. 
### How to reproduce it?
1. Create simple script like this one
```js
// ==UserScript==
// @name test update bug
// @match *://*/*
// ==/UserScript==

console.log('hello world');
```
2. cd to script's folder and run local server, similar to described [here](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/). I used `npm http-server`
3. Install script
3.1. Set update and download links in script's settings tab to your local server (e.g. http://localhost:8000/test.user.js)
4. Change locale script file (e.g. rewrite log message) and save changes
5. Check updates for script in VM
6. Open script's text in VM

### What is the expected result?
Script changed.
### What is the actual result?
Script did not change. VM prints info like `updates not found`
### Environment
- Browser: FF57
- Violentmonkey version: v2.8.22
- OS: Win7

**Comment by gera2ld** [comment]
When checking for updates, the `@version` is compared. The script will be updated only if the `@version` meta block of the new script is **greater than** that of the old script.
So if no `@version` is provided, there will always be no update.

**Comment by gera2ld** [comment]
If you are trying to develop a script and keep up with local updates, you may follow the instructions [here](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/).
