### ISSUE TITLE
[bug] 纵横中文网无法 @require vue

### ISSUE THREAD

**Issue by ywzhaiqi** [violentmonkey/violentmonkey#312]
### What is the problem?

纵横中文网 小说阅读页无法 require vue。

具体错误信息：
>ReferenceError: Vue is not defined
>
>Uncaught Error: Mismatched anonymous define() module: function (){"use strict";function e(e){return

### How to reproduce it?

打开 [这个网址](http://book.zongheng.com/chapter/523438/8521196.html)，加载如下脚本。
```js
// ==UserScript==
// @name my test
// @namespace Violentmonkey Scripts
// @match http://book.zongheng.com/*
// @grant none
// @require        https://cdn.staticfile.org/vue/2.2.6/vue.min.js
// ==/UserScript==

console.log(Vue)
```

### Environment
- Browser: Chromium
- Browser version: 62.0.3202.94
- Violentmonkey version:  2.8.21
- OS: Windows 10

**Comment by gera2ld** [comment]
因为那个网站用了requirejs，导致umd挂载vue失败了。。
你可以使用`@run-at document-start`，在它加载requirejs之前先加载vue，或者把vue改造一下不要用umd。。
由于这跟violentmonkey没啥关系，目前也没啥好办法完全避免这种问题，这个issue就先关了。

**Comment by ywzhaiqi** [comment]
我不知道 violentmonkey 是怎么加载的，Tampermonkey 可正常 require.

**Comment by gera2ld** [comment]
@ywzhaiqi 它覆盖了几个特殊方法，可以部分解决这种问题。。我也加一下吧
