### ISSUE TITLE
[feature suggestion] add method to run userscripts from within other extensions

### ISSUE THREAD

**Issue by elypter** [violentmonkey/violentmonkey#317]
my idea is to let an adblocker do all the pattern matching and if there is a match on a site then a command akin to script:inject(...) (which doesnt exist yet) executes the userscript and submits parameters such as the element that matched and the rule, filterlist and extension that triggered the execution. the execution should wait for the filter process to finish and submit all matches at once if there are more than one so the script has all data it needs when it is run.

the userscript then only has to do the modifications. this would allow each of the extensions do what it is best at. the (ad)blocker at searching for patterns and userscripts at modifying and fixing the site. it would also have performance benefits as not the adblocker and each of the userscripts have to loop over every element on the page individually but only once in the adblocker.

**Comment by gera2ld** [comment]
Thanks for your idea, but I don't this will work. It requires adblocker to be modified to provide data for other extensions, why would they do that? If what you want is just to modify the filtered elements, then it's better for adblock to do it.

Closing as won't-fix.
