### ISSUE TITLE
Bad userscript support in Violentmonkey [Chromium version]

### ISSUE THREAD

**Issue by nfsmaniac** [Violentmonkey/Violentmonkey#32]
Hi,
in all versions (since v2.0.0.2 release) of Violentmonkey for Opera 15+ (and other browsers based on stock Chromium) there is several problems with userscripts. Some don't work correctly and some scripts probably even don't load (for example script settings of script isn't in the Violentmonkey menu).

Opera Presto (<12) and Maxthon version seem working well. So I think, in scripts isn't a problem (Tampermonkey and Greasemonkey also OK).
I have compared source code of Presto, Maxthon and Chromium version (it seems they all are in many parts of code very similar, some part completely different because of some difference between browsers). So I tried to do some porting (Maxthon/Presto version -> Chromium) myself, but result wasn't good, because I don't have good skills in developing extensions.

Examples of problematic userscripts:
Userscript | Description
------------ | -------------
[ČSFD Movie Preview](https://greasyfork.org/cs/scripts/3821-csfd-movie-preview) | For example [THERE](http://www.csfd.cz/hledat/?q=batman) if you hover mouse on link of movie name, it should popup a box with a preview of the movie profile).

[ČSFD IMDB Rating](https://greasyfork.org/cs/scripts/3822-csfd-imdb-rating)
[Universal Links Checker v7](https://greasyfork.org/cs/scripts/6746-universal-links-checker-v7)
[W.A.R Link Checker (Customized)](http://warlc.5gbfree.com/viewtopic.php?t=12)
------------ | -------------
...and more.

Could you take a look at it, please? Thank you!

**Comment by gera2ld** [comment]
*ČSFD Movie Preview* and *ČSFD IMDB Rating* work with the latest Violentmonkey for me. Which version of Opera are you using?

**Comment by nfsmaniac** [comment]
Ah, sorry. I tried it again with the new Violentmonkey 2.2.0 downloaded from Opera and it works for me now too (Opera 34).
But other mentioned scripts still really don't work for me. Tried ALL Violentmonkey releases downloaded from GitHub on Opera 34 (and also on Vivaldi, where Violentmonkey works quite good for me).

**Comment by gera2ld** [comment]
The other mentioned scripts, what's the real problem? They can't be installed or just don't work? There might be a bug preventing installation of some scripts which will be fixed soon.

**Comment by nfsmaniac** [comment]
Perfect - now I see, that the problem is in latest 2.2.0 release (partly) fixed!
My mistake is that i made this bug report based on previous releases (like 2.1.10.4).

The real problem was that they weren't working. In Opera Presto and Maxthon Violentmonkey (or in other browser with other extension like Greasemonkey) scripts worked correctly.

------------

I describe the problem:
We have clean Violentmonkey (<= 2.1.10.4) installed and we're installing [THIS SCRIPT](http://warlc.5gbfree.com/viewtopic.php?t=12]).

## Comparison between Opera Presto Violentmonkey and Chropera Violentmonkey:

### Opera 12.17
1.
![opera12_script-install](https://cloud.githubusercontent.com/assets/3188999/11942303/defb2748-a835-11e5-96ec-786417cfc8a8.png)
2. **GO TO THIS [TEST PAGE](http://pdmail.8u.cz/testpage.html)**
![opera12_script-commands](https://cloud.githubusercontent.com/assets/3188999/11942347/2d982d56-a836-11e5-9c7e-1431cdf925d3.png)
3.
![opera12_link-checked](https://cloud.githubusercontent.com/assets/3188999/11942399/80f0915a-a836-11e5-8342-9e5e626c2951.png)

------------

### Opera 34
1.
![opera34_script-install](https://cloud.githubusercontent.com/assets/3188999/11942431/c8d403e4-a836-11e5-96c6-8a100da78a26.png)
2. **GO TO THIS [TEST PAGE](http://pdmail.8u.cz/testpage.html)**
3.
![opera34_script-commands](https://cloud.githubusercontent.com/assets/3188999/11942439/d70aa6c0-a836-11e5-8bc8-5c00d2297d20.png)


------------
Why I wrote, that in 2.2.0 release it is partly fixed? Because script is finally working in the new release. But the bug described on image number 1 (under Opera 34) is still a present.

**Comment by gera2ld** [comment]
Thank you very much for the clear description.
I think this is due to the bug I mentioned above. The script isn't correctly installed because of the bug, so it cannot actually run even though its name appeared in the list. This will be fixed soon.

**Comment by nfsmaniac** [comment]
Thank you and good luck with fixing!
Just a little another problem:
If i download directly the master branch from Github (with latest fixes) and install it extracted in developer mode, any menu items won't load:
![violentmonkey_menu](https://cloud.githubusercontent.com/assets/3188999/11957662/40eb4d7e-a8c3-11e5-9be1-d0ce55657ab9.png)

When I did it few weeks before, the menu worked (or you can try it with my [outdated fork](https://github.com/nfsmaniac/Violentmonkey) of Violentmonkey).

**Comment by gera2ld** [comment]
The source code has separated files for each view and template, which will be packed together in the end. If you want to run from the code, you need to install the dependencies and build the code with `gulp` first.

**Comment by nfsmaniac** [comment]
Thanks. I tried it with Node.js that was installed along with Visual Studio Community. Probably I am doing something wrong, but in current state - it doesn't like the gulpfile.js :-(
```
C:\Users\...>npm install -g gulp
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
C:\Users\...\AppData\Roaming\npm\gulp -> C:\Users\...\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
gulp@3.9.0 C:\Users\...\AppData\Roaming\npm\node_modules\gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── chalk@1.1.1 (escape-string-regexp@1.0.4, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, defaults@1.0.3, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, strip-bom@1.0.0, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, fancy-log@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, gulplog@1.0.0, vinyl@0.5.3, multipipe@0.1.2, lodash.template@3.6.2, through2@2.0.0, dateformat@1.0.12)

C:\Users\...>gulp
[16:10:36] No gulpfile found

C:\Users\...\Documents\Violentmonkey>npm install gulp --save-dev
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
gulp@3.9.0 node_modules\gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── chalk@1.1.1 (supports-color@2.0.0, ansi-styles@2.1.0, escape-string-regexp@1.0.4, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (rechoir@0.6.2, extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, mkdirp@0.5.1, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, fancy-log@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, gulplog@1.0.0, vinyl@0.5.3, multipipe@0.1.2, through2@2.0.0, lodash.template@3.6.2, dateformat@1.0.12)

C:\Users\...\Documents\Violentmonkey>npm install -g node-dependencies
npm WARN engine npm@1.3.1: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.1, but bundled package wasn't found in unpacked tree
C:\Users\...\AppData\Roaming\npm\node-dependencies -> C:\Users\...\AppData\Roaming\npm\node_modules\node-dependencies\bin\node-dependencies
node-dependencies@0.3.1 C:\Users\...\AppData\Roaming\npm\node_modules\node-dependencies
├── async@0.2.9
├── underscore@1.4.4
├── optimist@0.6.0 (wordwrap@0.0.2, minimist@0.0.1)
└── npm@1.3.1

C:\Users\...\Documents\Violentmonkey>gulp
C:\Users\...\Documents\Violentmonkey\gulpfile.js:3
const gulp = require('gulp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\...\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\...AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
```
I've also tried to install dependencies locally first - without `-g` parameter, but console said me, dependencies should be installed globally.
`npm WARN prefer global node-dependencies@0.3.1 should be installed with -g`
I am novice to Node.js and Gulp.js, so please be patient. Thank you!

**Comment by gera2ld** [comment]
The problem seems to be that you are using an obsolete Node.js. I think I can post a built version here.

Here is the built version: [dist.zip](https://github.com/Violentmonkey/Violentmonkey/files/72580/dist.zip)

**Comment by nfsmaniac** [comment]
Thank you very much for the build!
Back to the problem:

:white_check_mark: Script installation **fixed**
:white_check_mark: Issue with scripts **fixed**

So I think, my problem was resolved and this thread can be closed.
Thanks for help and code fixes.
