### ISSUE TITLE
Badge shows script running on chrome:// and moz-extension:// pages

### ISSUE THREAD

**Issue by rubaboo** [violentmonkey/violentmonkey#321]
### What is the problem?
I have a total of 1 script installed. It does not include chrome://* nor moz-extension://*. I even added those as excludes. Yet the badge still shows 1 script running on those pages.

### How to reproduce it?
1. Navigate to chrome://browser/content/places/places.xul
2. Observe the badge on the VM button.

### What is the expected result?
No badge.

### What is the actual result?
The badge on the button shows 1 script running.

### Environment
- Browser: Firefox 57.0.3
- Browser version: 57.0.3
- Violentmonkey version: v2.8.23
- OS: Windows 7

**Comment by gera2ld** [comment]
This should be a Firefox issue and seems not to occur any more. Please reopen if you still have the issue.
