### ISSUE TITLE
[Feature suggestion] Add the ability to import code into Custom Style section

### ISSUE THREAD

**Issue by overdodactyl** [violentmonkey/violentmonkey#323]
Is there any chance it would be possible to allow the use of `@import` statements in the custom style section?

Use case:  I've designed a theme (including CodeMirror) to mimic Firefox's inspector/developer toolbox in dark mode and have it posted in my [ShadowFox](https://github.com/overdodactyl/ShadowFox) repo.  It would be great if other users could implement the code without having to manually copy/paste and update.  Some extensions/websites (such as ProtonMail) that have a custom css section allow you to import from a raw file.

For example:

```css
@import url("https://raw.githubusercontent.com/overdodactyl/ShadowFox/master/webextensions/violentmonkey.css");
```

I wasn't able to get anything like this to work in Violentmonkey.

If curious/relevant, here's the link and screenshots:

https://github.com/overdodactyl/ShadowFox/blob/master/webextensions/violentmonkey.css

![screen shot 2018-01-06 at 5 17 19 pm](https://user-images.githubusercontent.com/33071129/34645357-9daf2ab4-f342-11e7-9671-a5f05b55aa95.png)

![screen shot 2018-01-06 at 5 17 43 pm](https://user-images.githubusercontent.com/33071129/34645360-a774dbfc-f342-11e7-8b44-f2fa7caaa3ea.png)

Thanks for your time and the amazing extension!

**Comment by gera2ld** [comment]
It actually worked by using `@import`. The only problem is that GitHub serves the file with mimetype of `text/plain`, which makes it ignored by the browser. See [the solution on StackOverflow](https://stackoverflow.com/questions/7780550/referencing-a-css-file-in-github-repo-as-stylesheet-in-a-html-file).

**Comment by overdodactyl** [comment]
Oh awesome, thank you so much! I apologize for wasting your time with this then :)

**Comment by Tristar7** [comment]
@overdodactyl 

How to use it now? Your repo changed a lot and the needed code is split into several files now it seems.
