### ISSUE TITLE
[bug report] Script cannot be launched on www.tumblr.com/dashboard

### ISSUE THREAD

**Issue by yybot1** [violentmonkey/violentmonkey#327]
### What is the problem?
[bug report] Script cannot be launched on www.tumblr.com/dashboard

Script can be launched on most of pages on tumblr.com but doesn't work on www.tumblr.com/dashboard

I tried TamperMonkey on Firefox and my script works well.

### Environment
- Browser: Firefox 
- Browser version: 57.0.4 
- Violentmonkey version: 2.8.24
- OS: windows 7

The following is a test script, works well on any posts on tumblr.com but doesn't work on www.tumblr.com/dashboard, I tried TamperMonkey and this script works well on www.tumblr.com/dashboard

```
// ==UserScript==
// @name        tumblr_test
// @require     http://code.jquery.com/jquery-1.11.3.min.js
// @include     *.tumblr.com/post/*
// @include     https://www.tumblr.com/dashboard
// @version     0.1
// @grant       none
// ==/UserScript==

function pageTest() {

  alert("Run pageTest")

  $(document).ready(function() {

    alert("Run pageTest - document ready")

  })
}

pageTest()

```

**Comment by gera2ld** [comment]
Works for me on Firefox 58. In Firefox 57 CSP issues (#173) might prevent some scripts from working. Tampermonkey has optimized for CSP issues in some unusual way so it works.

![default](https://user-images.githubusercontent.com/3139113/34832176-19d30fae-f724-11e7-8f4b-572d401bc67d.png)
