### ISSUE TITLE
PopUp menu Hover state graphical bug

### ISSUE THREAD

**Issue by Acid-Crash** [violentmonkey/violentmonkey#328]
### What is the problem?
When navigating popup menu graphical issues appear

### How to reproduce it?
1. Click navbar button to open popUp
2. Make few hovers over menuitems and browser window
3. The following bug appears
![violentmonkey](https://user-images.githubusercontent.com/32600318/34828072-fa685c30-f6e4-11e7-9173-30c2cb23bff2.png)

### What is the expected result?
Styling for hover state should be applied to the actual hovered element
### What is the actual result?
Styling for hover state doesn't process correctly for the menu elements

### Environment
- Browser: Firefox
- Browser version: 57.0.4 (64-bit)
- Violentmonkey version: 2.8.24
- OS: Win10 x64

**Comment by gera2ld** [comment]
They are just CSS and Violentmonkey is not in charge of rendering.
I can reproduce this only in Firefox on Windows, but not Firefox on Mac OS or Chrome, so this is likely a Firefox issue.
