### ISSUE TITLE
GM_xmlhttpRequest synchronous can't work

### ISSUE THREAD

**Issue by yixuanzi** [violentmonkey/violentmonkey#329]
### What is the problem?
```javascript
function getpagewithgmxhr(url,asyc=true){
  var page=null
  GM_xmlhttpRequest({
    method: 'GET',
    url: url,
    synchronous:asyc,
    onload: function(result) {
      page=result.responseText;
    }
  });
  return page
}
```
I have a function like this, but when i use the parameter of synchronous set the value is true,
the request still work with asynchronous,why???

thanks

### What is the expected result?
I want the  GM_xmlhttpRequest is work with asynchronous that the parameter of synchronous is true

### What is the actual result?
It's is still work with asynchronous style!!!

### Environment
- Browser: Firefox
- Browser version: 57.0 (64-bit)
- Violentmonkey version: 2.8.24
- OS: debian

**Comment by gera2ld** [comment]
It's not supported since the beginning. I will add this to the document.
BTW, I don't think you want to freeze the browser and stay unresponsive until the request is finished.

**Comment by mk-pmb** [comment]
>  BTW, I don't think you want to freeze the browser and stay unresponsive until the request is finished.

Hi, I want that. In my case, the server on localhost responds quickly enough that I don't mind. Is there any way to make it work with modern Firefox?

**Comment by tophf** [comment]
There is no synchronous cross-process communication API for extension, so there's nothing we can do. You can try using the standard synchronous XMLHttpRequest from the web page directly.
