### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by adipiciu** [Violentmonkey/Violentmonkey#33]
Error running script: 
TypeError: Cannot read property 'xxx' of undefined

This error appears for variables created with the eval() function, after Opera 34 upgrade.

**Comment by gera2ld** [comment]
Can you give a more detailed example please?

**Comment by adipiciu** [comment]
I have an extension which uses eval() to get some variables from the source page. When I try to access those variables in the extension, I get error from Violentmonkey, because they are null. The script works in tampermonkey, and also it worked before Opera upgraded a few days ago.

I tested with Violentmonkey release v2.1.10.1 and it works. The problem is from some edits somewhere in December.

**Comment by gera2ld** [comment]
You'd better provide a piece of code or a script that reproduces the problem, otherwise I can hardly figure out what the problem really is.

**Comment by adipiciu** [comment]
Try
https://greasyfork.org/en/scripts/5923-travian-resource-bar-plus
I don't have other example.

**Comment by nfsmaniac** [comment]
I'm not sure, what's the real problem. I have registered there and tested the script.
My analysis:
![travian](https://cloud.githubusercontent.com/assets/3188999/12012312/cf651fd8-acee-11e5-8ce1-407b3b7cde51.png)

The first box seems working without problems.
But the second box doesn't appear if you use Violentmonkey 2.2.0 public release from 17th December.
It doesn't work even on the current development 'master' branch on GitHub (with the latest fixes; v2.2.1).

The second box worked for me with some archived Violentmonkey development version dated approximately on the 5th of December (based on file timestamp, which could be overwritten, so some code comparing is needed).

You can try this Violentmonkey development version: [Violentmonkey-old-master.zip](https://github.com/Violentmonkey/Violentmonkey/files/72840/Violentmonkey-old-master.zip)
Extract, on Opera extensions page enable developer mode and load extracted extension (you are loading the `src` folder, where `manifest.json` is located)

**Comment by adipiciu** [comment]
With this I get:
Error running script:
TypeError: Illegal invocation
Illegal invocation

This was exactly after Opera was upgraded in the beginning of December. After some updates on violentmonkey, the script started but can't use variables created with eval(). That is why the second window doesn't appear. The script works on opera with tampermonkey and also on chrome.

**Comment by gera2ld** [comment]
Thank you guys, I think the problem is located now.

**Comment by adipiciu** [comment]
I build and compiled the new version and it works. Thanks! Waiting to be officially released.
P.S. I have a minor request. Can you add in the About window the Violentmonkey version?

**Comment by nfsmaniac** [comment]
I've made a pull request.
You can download my build with this feature now: [dist.zip](https://github.com/Violentmonkey/Violentmonkey/files/73590/dist.zip)
