### ISSUE TITLE
Cannot re-enable extension after disabling it

### ISSUE THREAD

**Issue by Matthewus** [violentmonkey/violentmonkey#331]
### What is the problem?
Cannot re-enable extension after disabling it.
### How to reproduce it?
1. Disable extension
2. Re-enable it

### What is the expected result?
Extension working again
### What is the actual result?
Extension not working, toolbar icon does not show up, cannot access settings from about:addons
### Environment
- Browser: Firefox
- Browser version: 57.0.4 x64
- Violentmonkey version: 2.8.24
- OS: Windows 10 x64

This is what i see in the console: 
![violentm](https://user-images.githubusercontent.com/9383850/34980357-8b68491c-faa4-11e7-8c70-e7ccfc46a3ba.png)

**Comment by gera2ld** [comment]
Cannot reproduce, and I don't think this has anything to do with the extension itself. 😕

**Comment by Matthewus** [comment]
So this a Firefox bug?

**Comment by gera2ld** [comment]
I'm not sure, maybe something wrong with the paths.
