### ISSUE TITLE
[Feature] A couple of feature requests for making it easier to use.

### ISSUE THREAD

**Issue by Betsy25** [violentmonkey/violentmonkey#332]
### What is the problem?
1. Scripts are ordered randomly? in the script list ?
2. Easier option to edit a script.

### How to improve it.
1. Have an option to sort scripts alphabetically in the script overview.
2. Being able to right-click a script in the popup to go directly into the edit mode for the script.

### Environment
- Browser: Firefox
- Browser version: 59a1 (nightly) 
- Violentmonkey version: 2.8.24 
- OS: Win7 64x

**Comment by gera2ld** [comment]
1. like this?
![image](https://user-images.githubusercontent.com/3139113/35022471-1c51c346-fb71-11e7-9385-5149c28daf50.png)

**Comment by Betsy25** [comment]
Oops, somehow I looked over that one. 😊 
What's your idea about the second one @gera2ld ?

**Comment by gera2ld** [comment]
Good catch.
2 is a good idea, maybe I'll add it in the future.

**Comment by Betsy25** [comment]
Thanks a lot @gera2ld, little nitpick, using average to long length script titles doesn't draw the "active" sign in the popup menu.
(Screenshot)[http://images2.imagebam.com/af/71/2f/ba8374725780393.jpg)
... "AAK-Cont userscript for uBlock Origin" script is active, however due to the title length, the "active" symbol isn't drawn.
