### ISSUE TITLE
Per-script "notify updates" option

### ISSUE THREAD

**Issue by mikhaelkh** [violentmonkey/violentmonkey#333]
Scripts have different level of trust and frequency of updates, hence it can be convenient for scripts to have some settings that are different from global, e.g.
- Automatically check scripts for updates
- Notify script updates

**Comment by franklinyu** [comment]
Also the website whitelist and blacklist.

**Comment by gera2ld** [comment]
@mikhaelkh It's OK to notify updates for certain scripts. Can we just set a smaller time interval to check updates for all scripts? So we don't need to set it for every single script, global settings are enough.
@franklinyu What's wrong with whitelist and blacklist? They should have been supported.

**Comment by franklinyu** [comment]
@gera2ld I was asking for a per-script blacklist. Currently there is only global blacklist.

**Comment by gera2ld** [comment]
@franklinyu you can define custom rules (whitelist / blacklist) in script settings, it's supported since the beginning.

**Comment by gera2ld** [comment]
edit script > switch to settings tab > add rules
