### ISSUE TITLE
NoScript blocks scripts (works with Greasemonkey)

### ISSUE THREAD

**Issue by marak8** [violentmonkey/violentmonkey#335]
The following script should add tabs for predefined languages (see `languages` constant) on Wikipedia. It works in Tapermonkey (latest Chrome), Greasemonkey (latest Firefox, 57), but not in Violentmonkey (latest Firefox, 57). Pasting the anonymous function in Firefox 57 console makes the tab appear. Violentmonkey reports the script as being active.

    // ==UserScript==
    // @name         Wikipedia language tabs
    // @namespace    marek
    // @version      0.1
    // @description  Adds tabs for favourite languages
    // @author       marek
    // @match        https://*.wikipedia.org/*
    // ==/UserScript==
    /* jshint esnext: true */
    
    (function(){
    "use strict";
    
    const languages = ['en', 'de'];
    
    const menu = document.querySelector('#p-namespaces > ul');
    
    if (!menu)
    	throw 'No menu';
    
    languages.forEach(lang => {
    	const link = document.querySelector(`.interwiki-${lang} > a`);
    	if (link) {
    		const span = document.createElement('span');
    		span.appendChild(link);
    		const item = document.createElement('li');
    		item.appendChild(span);
    		menu.appendChild(item);
    	}
    });
    
    })();

**Comment by gera2ld** [comment]
It works for me like this:
![image](https://user-images.githubusercontent.com/3139113/35202888-4211ca34-ff60-11e7-9378-5763e59d87a5.png)

**Comment by gera2ld** [comment]
Is there any error message in your console?

**Comment by marak8** [comment]
There're some errors

	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: (function() {
		var _addEventListener;....
	Hanse:1
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: (function (ERROR) {

		const V8_STACK_....
	Hanse:1
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: window["_gaUserPrefs"] = { ioo : functio....
	Hanse:1
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: call to eval() or related function blocked by CSP.
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: document.documentElement.className = doc....
	Hanse:6
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: (window.RLQ=window.RLQ||[]).push(functio....
	Hanse:7
	Content Security Policy: The page’s settings blocked the loading of a resource at https://en.wikipedia.org/w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector (“script-src 'none'”).
	Loading failed for the <script> with source “blob:https://en.wikipedia.org/91bcbf49-5b5b-40c6-8af1-b55debef291e”.
	Hanse:1
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: (function(a){var b=document.createElemen....
	Hanse:1
	Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://en.wikipedia.org/91bcbf49-5b5b-40c6-8af1-b55debef291e (“script-src 'none'”).
	Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'none'”). Source: (window.RLQ=window.RLQ||[]).push(functio....
	Hanse:2092

I'm using bunch of blocking extensions like uBlock. I'll try with them disabled.

**Comment by marak8** [comment]
It doesn't work with NoScript. I realize this is not your concern but could you please point me to the right direction to solve this problem without disabling NoScript? It's quite popular extension and give other *monkeys kind of works with it, it'd be nice to make the best monkey work with it too. :-)

**Comment by alphabug** [comment]
Blocking scripts has been discussed in issue #302. Basically, it is possible to block scripts with uBlock Origin while keeping Violentmonkey userscripts active. Enable advanced user mode in the settings and set the popup matrix to be something like this and click the lock to save the setting. 
![image](https://user-images.githubusercontent.com/32154100/35368807-0621edd4-013a-11e8-9271-36a7388ea0fa.png)
More info on using the matrix: https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by tophf** [comment]
See https://violentmonkey.github.io/posts/inject-into-context/
