### ISSUE TITLE
Lack of GM_download support on Chrome

### ISSUE THREAD

**Issue by wpigoury** [violentmonkey/violentmonkey#338]
### What is the problem?
Scripts using GM_download function fail with error:
> Uncaught ReferenceError: GM_download is not defined

Same scripts work as expected with Tampermonkey.
Sample script below:
`// ==UserScript==`
`// @name          GM_download test`
`// @namespace     GM_download test`
`// @match         *://*/*`
`// @grant         GM_download`
`// ==/UserScript==`

`GM_download({ 'url': 'https://www.google.fr/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png', 'name': 'google_logo.png', 'saveAs': false });`

### How to reproduce it?
1. Install Violentmonkey
2. Add GM_download test script
3. Browse any page

### What is the expected result?
The script should trigger automatically on load the download of the Google logo in a file named google_logo.png.

### What is the actual result?
Nothing happens except an error in the console > Uncaught ReferenceError: GM_download is not defined

### Environment
- Browser: Chrome
- Browser version: 63.0.3239.132 (64 bits)
- Violentmonkey version: 2.8.27
- OS: Windows 10

**Comment by pendave** [comment]
https://gist.github.com/ccloli/832a8350b822f3ff5094

**Comment by wpigoury** [comment]
Thanks @pendave, I'm already using this kind of workaround but I still think it would be better if GM_download was natively supported by ViolentMonkey.
