### ISSUE TITLE
google drive 同步后，文件存放哪里了？另外怎么彻底删除一个脚本？本地删了，是灰色的，过两天又启用了。

### ISSUE THREAD

**Issue by zhaozhejun** [violentmonkey/violentmonkey#344]
google drive 同步后，文件存放哪里了？另外怎么彻底删除一个脚本？本地删了，是灰色的，过两天又启用了。
![default](https://user-images.githubusercontent.com/22097252/35949468-94feddb4-0cac-11e8-80c4-a895da027135.PNG)
how to complete delete this？？

**Comment by gera2ld** [comment]
刷新一下

**Comment by zhaozhejun** [comment]
请问哪里刷新？？

**Comment by gera2ld** [comment]
刷新一下，灰色的就没有了。
如果过几天又同步回来了，说明你在别的电脑或浏览器上有这些脚本。
