### ISSUE TITLE
Warning "Script too large, opening in read-only mode"

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#346]
It is OK?
How to edit scripts  now?

**Comment by gera2ld** [comment]
Why do you want to edit a compressed script in the browser?

**Comment by soviet-man** [comment]
Why is it compressed? It is just about 800 lines large -- not so large indeed.

**Comment by gera2ld** [comment]
Actually the reason it is read-only is that it has very long lines (longer than 10k), the size of the whole script does not matter that much.

**Comment by gera2ld** [comment]
Do you mean your scripts are readable and not compressed but they have very long lines?

**Comment by soviet-man** [comment]
I have small image in base64 encoding inside CSS rule
`background-image : url(data:image/png;base64, . . . . . . . . . )`

So one line become large.

**Comment by gera2ld** [comment]
I suggest you to edit the script in a text editor, as described [here](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/).
I'll look into this issue further.

**Comment by soviet-man** [comment]
@gera2ld, I am talking about somthing like this
https://gist.github.com/jhafner/5678927#file-bgnoise-css

**Comment by tophf** [comment]
Fixed in 9bba6fc95f235fc56c8370e4473285eb41f19896
