### ISSUE TITLE
suddenly not working on Facebook

### ISSUE THREAD

**Issue by filbo** [violentmonkey/violentmonkey#347]
I use and contribute to the development of SocialFixer (socialfixer.com), a Facebook extension.  For years I've been using it in Chrome-based Opera, under Violentmonkey: currently opera-developer version 52.0.2838.0 with Violentmonkey 2.5.7.

Minutes ago, I reloaded an Facebook (FB) tab which previously had Social Fixer (SFx) working in it; and suddenly it was absent.  Looking in the Javascript console I see:

injected.js:809 Uncaught (in promise) TypeError: Cannot read property 'scripts' of undefined
    at loadScript (injected.js:809)
loadScript @ injected.js:809
Promise.then (async)
initCommunicator @ injected.js:827
(anonymous) @ injected.js:829
(anonymous) @ injected.js:831

I suspect FB have just rolled out some change which affects startup sequencing and breaks VM.

**Comment by gera2ld** [comment]
Might be related with #295, which has been fixed since v2.8.22. I cannot reproduce it here. Can you provide a minimal reproduction? (which script? which page?)

It seems that Opera will not accept and publish any new versions of the extension, so if you are still using Opera, I think you should remove the obsolete version installed from Opera add-ons, and reinstall it from Chrome web store. See introductions [here](https://violentmonkey.github.io/get-it/).

**Comment by filbo** [comment]
Hi, yeah, I discovered about an hour ago that I was on a very back-rev version, and installed 2.8.28 from Chrome store.  But I am unable to retrieve my Social Fixer settings from the old version since I can't get it to start up.

Which script?  I don't think it matters since it happened while VM was trying to inject the script; its contents could have been 'var foo = 1;' and it would still have failed.  On facebook.com, from a logged-in FB account, though I don't know if that's significant.

When I installed 2.8.28 (beside 2.5.7), it did not pick up the scripts & script-saved-data from 2.5.7; and this is not surprising since it had a different gibberishId 'jinjaccalgkegednnccohejagnlnfdag' instead of 'niofholngoecgnpgamgbiiijcjlllpge'.  I wonder if I were to surgically replace the contents of 'niof...' with 'jinj...', while Opera not running, would it then awaken 2.8.28 attached to the old 2.5.7 data?  I would probably have to edit some internal packaging metadata of 2.8.28 -- though perhaps not, I see zero instances of 'jinj' in the contents.

So the other significant question is: will 2.8.28 successfully read and update the old saved data from 2.5.7; or will it freak out and wipe me clean to a blank slate?

**Comment by filbo** [comment]
(that is, I don't know if it's significant that FB was able to detect live login cookies for a working account; I suspect FB have done something evil like overriding array prototype, and the smaller [but still absurdly huge] codeset they shove down to a not-logged-in page would probably contain whatever low-level framework stuff introduced this)

(I also suspect that this will silently go away in a few days, like most of their worst changes: when they discover the 75 other things all over *their* codebase which it breaks...)

**Comment by gera2ld** [comment]
They are two different add-ons with different IDs, so there will be no automatic data migration. You can export all data from the old add-on (Settings > Data export > Export to zip), and then import it to the new add-on (Settings > Data import > Import from zip).

**Comment by filbo** [comment]
Hmmm.  Should have thought of that myself...

So, that brings up two immediate issues:

(1) with 2.5.7 -- I can click on 'export to zip' but it doesn't do anything other than grey out that option upon clicking.
(2) with 2.8.28 (where I've reinstalled the SFx script and imported an old but mostly usable set of options) -- clicking on 'export to zip' fails with: 'No webpage was found for the web address: blob:chrome-extension://jinjaccalgkegednnccohejagnlnfdag/288d92f3-e7dc-4ce5-93c6-58421942e23f'

bleah.

**Comment by filbo** [comment]
And yes, I know they're of different IDs; I was proposing to lie to Opera by copying the 2.8.28-Chrome-package set of files into the 2.5.57-Opera-package directory, so that Opera would give 2.8.28 access to 2.5.57's data.  This would work if your internal data representation is identical *or* the newer version will be smart enough to recognize this as a surprise upgrade and perform whatever data structure upgrading is necessary.

**Comment by gera2ld** [comment]
Copy package files from new version to old version should do the job.

About the two issues mentions above, (1) might be related with broken data, it's better if you can paste the background console logs.

**Comment by filbo** [comment]
I think I've rescued all the config data I needed by other means, so now the entire 2.5.7 installation, including its scripts & their sub-data, are experimental playground.

'background console logs'?  Hmmm.  I tried an export, then went into browser console of the VM management page, saw:

app.js:1566 Invalid current service: undefined
service @ app.js:1566

app.js:1425 TypeError: Cannot read property 'scripts' of undefined
    at app.js:1485
(anonymous) @ app.js:1425

On reload, 'Invalid current service' appears before I do anything; and 'TypeError: Cannot read property 'scripts' of undefined' doesn't appear at all, even when I try to export.  ... and then randomly, asynchronously, appears some time later.

**Comment by filbo** [comment]
Hmmm.  So I moved aside the old 2.5.7 directory, made a new directory of the same name, copied the 2.8.28 files into it (in a '2.8.28' subdirectory), restarted Opera, Opera said the extension 'may have been corrupted' and wouldn't run it.  It offered to 'repair' it, I said yes, suddenly 2.5.7 was installed again -- perhaps it re-downloaded and reinstalled from the Opera 'store'.

Now trying again except I'll lie and put the files in a '2.5.7' subdirectory...

**Comment by filbo** [comment]
Nope, still 'may have been corrupted'.

Meh.  I destroy the 2.5.7 install and continue with 2.8.28.

**Comment by gera2ld** [comment]
Opera may have done something to validate the code...

To see *background console logs*:
- Go to *Extensions* (chrome://extensions)
- Turn on *Developer mode*
- Click *Inspect views: background/index.html*
- switch to console tab

> (2) with 2.8.28 (where I've reinstalled the SFx script and imported an old but mostly usable set of options) -- clicking on 'export to zip' fails with: 'No webpage was found for the web address: blob:chrome-extension://jinjaccalgkegednnccohejagnlnfdag/288d92f3-e7dc-4ce5-93c6-58421942e23f'

Does this still happen? Can you provide some more information please? (OS, CPU, memory, etc.) I guess it's related to the performance of your computer.

**Comment by filbo** [comment]
Now at work:

- I updated Opera to latest (opera-developer 52.0.2864.0 based on Chrome 65.0.3325.52)
- Installed Chrome-store Violentmonkey (2.8.28) as I had none installed
- Created a script with the '+' button, changing the template only by changing its name to 'New Script blah'
- Clicked on Settings, Export to zip
- URL bar changed to 'blob:chrome-extension://jinjaccalgkegednnccohejagnlnfdag/020214ab-4395-486b-8a3e-4184f2b078c4'
- Page contents displayed:

This site can’t be reached

The webpage at blob:chrome-extension://jinjaccalgkegednnccohejagnlnfdag/020214ab-4395-486b-8a3e-4184f2b078c4 might be temporarily down or it may have moved permanently to a new web address.
- I tried substituting to 'blob:opera-extension://...', and both versions without 'blob:', all to no avail.  Chrome-based Opera responds to opera: in place of chrome:, and *usually* but I think not always also responds to the chrome: versions of the various internal URLs.

I suspect Opera is not implementing this sort of loopback URL, or responds to it in a different format which I don't know how to transform to.

**Comment by filbo** [comment]
Looking at the background console of this newly installed VM, it reportsL

Upgrade database...
Uncaught undefined

both on 'app.js:1'.  After prettyprinting, I see these are at lines 640 and 649, a console.info() and then an immediately executed anonymous function with 'e.onupgradeneeded = function() { throw t() }'

**Comment by filbo** [comment]
In opera:extensions Error box, I see:

TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

and cannot get more out of that as the styling of the error window is utterly screwed up (what I get for running a pre-beta browser build...)

**Comment by gera2ld** [comment]
Thank you for your patience.
`blob:` URL is generated by native APIs and works for me here, so there is no need to doubt the format. The problem might be: the `blob:` URL is revoked before downloading starts. That's why I asked for system information.
`Uncaught undefined` should be caused by broken data. No reponse to export might also be related to this. Can you provide the error line info please? (something like app.js:1:1234) It's better if we also get stack info. (click on the error to show lines of messages)

**Comment by filbo** [comment]
As I said, the styling of the error window was utterly screwed up.  I was only able to get the 'TypeError:...' part by hovering it and retyping, since the line was chopped in half vertically and would not expand.  Now at home, will try again here...

**Comment by filbo** [comment]
Ok, at home I am still getting the blob URL not found, but no 'Uncaught undefined'.  The only error shown in opera:extensions for VM is << Unrecognized manifest key 'applications'. >> (complaining about the thing that Firefox wants), and it appears to be only a warning.  It shows 'Inspect views:
background/index.html options/index.html#settings'; both of those views show nothing in their consoles, even after invoking the blob-not-found behavior.

Man.  Ok, two more screwy details:

(1) by repeatedly clicking on 'Export to zip', then 'back' when it failed, and watching the console window for options/index.html#settings, I eventually saw a quick flash of some sort of permissions denied message about the blob: URL.  It was literally visible for 1/4 second, I was just able to make out the 'red x circle' and that it was some sort of permissions error about 'blob', then gone (i.e.: by then what I was looking at was instead the console window for new page 'chrome-error://chromewebdata/').

(2) twice out of maybe 20 attempts, instead of an internal-404 page, I actually *got* the downloaded data.  Sort of.  I got a display page of binary gibberish, starting with 'PK[gibberish]', obviously a .zip file.  Obviously the intended download data.  But it did not invoke a download dialog (or store it without asking); and its right-click menu had 'save' greyed out!  Like so:

![blob](https://user-images.githubusercontent.com/3022180/36242906-65fc7694-11d3-11e8-92f4-5e93159ed5d7.png)

'Inspect element' on the gibberish actually works, and 'Copy outerHTML' on the gibberish gets me a paste buffer of the .zip data -- but so far I haven't found anything I can paste it into which takes a sufficiently raw view of things to not corrupt it.  `cat > junk` followed by pasting, resulted in an EOF received somewhere along the way, then the shell interpreting a bunch of noise; `gvim` accepted the paste and pretended it was OK but did something (probably some sort of newline modification) that hosed it.

Hmmm, or maybe it's being damaged on entry to the copy buffer.  I pasted into `gvim`, `gedit`, and `pluma`, and the results were identical in all cases.

**Comment by filbo** [comment]
And thank you for your patience as well.  I can tell you're (rightly) pissed at Opera for wimping out on reviewing your extension.

**Comment by filbo** [comment]
For the record, the home machine has 16GiB RAM and a 2-core (4-thread) 3.7GHz Intel Core i3-4170; which should still be plenty fast enough...

**Comment by gera2ld** [comment]
1. This is no error, just some improper messages.
   > Upgrade database...
   > Uncaught undefined

2. When no script is selected, the export button won't work. I will handle this in the next release.
   > TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

3. I will add a delay of 3s before the blob URL is revoked, hope downloading will work.
   > This site can’t be reached

**Comment by filbo** [comment]
After updating to 2.8.29, export is working fine on Opera.  There's about a 1s delay somewhere in the procedure, so if you were quickly revoking the internal loopback URL I can see where that might have broken it.

Meanwhile the original topic of this 'issue' (scripts not being properly injected on Opera) was due to the old Opera-store version I was running.  Both are fixed, closing this.  Thanks!
