### ISSUE TITLE
Since last update the font is displayed in Serif format

### ISSUE THREAD

**Issue by andrei030** [violentmonkey/violentmonkey#350]
![sin titulo](https://user-images.githubusercontent.com/476269/36234430-4a5be13c-11eb-11e8-84b2-6f4ed5b76ec1.png)
### What is the problem?
Since last update the font is displayed in Serif format in Firefox

### How to reproduce it?
N/A

### What is the expected result?
Sans Serif

### What is the actual result?
Serif

### Environment
- Browser: Firefox
- Browser version: 58.0.2
- Violentmonkey version: 2.8.28
- OS: Windows 10

**Comment by gera2ld** [comment]
The issue seems to exist for a long time due to postcss/postcss-scss#79 but should not affect most of the layouts. Firefox seems to render it incorrectly after recent updates.

**Comment by gera2ld** [comment]
close by f769a67
