### ISSUE TITLE
不支持 svg 的 @icon

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#352]
https://greasyfork.org/zh-CN/scripts/30268-github-issue-show-status
`// @icon        https://assets-cdn.github.com/pinned-octocat.svg`

![default](https://user-images.githubusercontent.com/2649544/36352943-d14e4196-14fa-11e8-9afd-e4ef30bc5e1e.png)

**Comment by perdolka** [comment]
Apparently, Violentmonkey doesn't support svg icons ? 
I also tried to install my script with svg icon and got the same result.

**Comment by ivysrono** [comment]
2.8.29：
Chrome：OK
Firefox 58 x64：No
![default](https://user-images.githubusercontent.com/2649544/36595452-2ff86d76-18dd-11e8-8881-e00a68f8cd21.png)

**Comment by gera2ld** [comment]
Works for me on Firefox. Did you try reinstalling the script?

**Comment by ivysrono** [comment]
Yeah, Firefox need reinstall, Chrome is ok directly.
Thanks.
