### ISSUE TITLE
很难删掉不用了的脚本

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#353]
![default](https://user-images.githubusercontent.com/2649544/36352957-fc1205de-14fa-11e8-8bfc-215abc439c7d.png)

这个问题其实持续很久了，应该说直接在greasymonkey上也有。不管怎么点删除，下次重启后还是存在。甚至到onedrive里删掉也没用。大概率重现，反正我基本没碰到一次性删掉的。

Edit: 又测试了下，如果关掉同步，可以正常删除，开着同步，会从云端同步下来。如果删远端，就从本地同步到云端去，反正删不掉。

**Comment by gera2ld** [comment]
灰色【已删除】的状态就是已经删掉了，只是可以撤销，这是个特性，不是bug。

同步又会回来的问题是bug，我这边无法重现，2.8.29可能修复了这个问题。。

**Comment by ivysrono** [comment]
2.8.29 的确不能重现这个问题了。
