### ISSUE TITLE
@downloadURL & @updateURL in the script

### ISSUE THREAD

**Issue by perdolka** [violentmonkey/violentmonkey#355]
- Browser: FF
- Browser version: 56.0.2 (x64)
- Violentmonkey version: 2.8.28
- OS: Win 10 (x64)

Hi. 
I read that information:
https://stackoverflow.com/questions/38023717/why-is-usage-of-the-downloadurl-updateurl-keys-called-unusual-and-how-do-they
And I have a same question about Violentmonkey.
Do I need the @downloadURL & @updateURL (in the script, not Violentmonkey options) to get the script update, or update works without them?

**Comment by gera2ld** [comment]
They will be set to the last installed URL by default, so they are not necessary to appear in the source code.
