### ISSUE TITLE
Script too large

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#356]
why this?

<a href='https://postimages.org/' target='_blank'><img src='https://s14.postimg.org/4t2nlxhxd/Catt.png' border='0' alt='Catt'/></a>

too large? why?
so I can modify in any way?

**Comment by soviet-man** [comment]
It means there are too long lines.

**Comment by gabri25ele** [comment]
yes, I suppose, but it is impossible, with others "monkeys" I don't have problem.
