### ISSUE TITLE
脚本数量过多显示不全咋办

### ISSUE THREAD

**Issue by zetalpha** [Violentmonkey/Violentmonkey#36]
![default](https://cloud.githubusercontent.com/assets/11816197/12034715/e020d830-ae6f-11e5-9c1c-edc2b9109129.JPG)

**Comment by gera2ld** [comment]
咦，浏览器应该会自动限制高度的啊，你没有滚动条么？什么浏览器？

**Comment by zetalpha** [comment]
vivladi

**Comment by zetalpha** [comment]
还有为什么安装脚本加载很久~

**Comment by zetalpha** [comment]
改成800px 比较合适吧 400px太小了
