### ISSUE TITLE
那个……有考虑新增一个在脚本的设置页面配置脚本储存的数据的功能吗

### ISSUE THREAD

**Issue by AnnAngela** [violentmonkey/violentmonkey#360]
RT，GM是有这个功能的，能够在脚本的设置页面新增、删除、修改脚本通过`GM_setValue`等方法储存的数据的，不知道VM有没有相关计划=w=

**Comment by gera2ld** [comment]
这个可以有

**Comment by qrqhuang** [comment]
same question.

**Comment by tophf** [comment]
It's already implemented.

**Comment by qrqhuang** [comment]
sorry. I mean is there a web UI for user to manage gm values.

like this screenshot in grease monkey  [where-does-gm-setvalue-store-data](https://stackoverflow.com/questions/16823686/where-does-gm-setvalue-store-data)

![image](https://user-images.githubusercontent.com/17166063/89094451-a0b73c00-d3f6-11ea-9d55-da4c80d6ea0e.png)

**Comment by tophf** [comment]
Yes, it's already implemented.

**Comment by qrqhuang** [comment]
Oh.  I just found that.  Great job。

**Comment by tophf** [comment]
On a relate note, we don't have an import/export of the entire storage though so I'll add it for the ease of transferring individual scripts+data, also from/to Tampermonkey.

**Comment by SekiBetu** [comment]
> On a related note, we don't have an import/export of the entire storage though so I'll add it for the ease of transferring individual scripts+data, also from/to Tampermonkey.

+1, this fuction is very useful
