### ISSUE TITLE
If the url icon is invalid, the control panel is always block whith a div

### ISSUE THREAD

**Issue by sdavidg** [violentmonkey/violentmonkey#362]
### What is the problem?
If the url icon is invalid, the control panel is always block whith a div
### How to reproduce it?
1. Create this new script:
```
// ==UserScript==
// @name TEST
// @description TEST
// @version 1
// @namespace TEST
// @match *
// @grant none
// @icon https://bvd2.nl/images/icon64.png
// ==/UserScript==
function demo() {}
```
2. Close "Control panel"
3. Open "Control panel"

### What is the expected result?
The control panel should work
### What is the actual result?
Error: Could not establish connection. Receiving end does not exist. undefined
TypeError: e is undefined  browser.js:1:3238
Error: Could not establish connection. Receiving end does not exist. undefined

### Environment
- Browser: Firefox
- Browser version: 58.0.2 (64-bit)
- Violentmonkey version: 2.8.29
- OS: W7

**Comment by gera2ld** [comment]
Seems to be Firefox only.
