### ISSUE TITLE
disable script in the popup for the current site

### ISSUE THREAD

**Issue by KonoromiHimaries** [violentmonkey/violentmonkey#367]
### What is the problem?
https://github.com/violentmonkey/violentmonkey/issues/366

### How to reproduce it?
1. disable single script with the popup panel

example. https://greasyfork.org/pl/scripts/30974-autoplay-disabled-for-html5-videos-pause-on-switch-tab
![2018-03-05-](https://user-images.githubusercontent.com/5884000/36967183-5697040e-205f-11e8-8689-9c0b9f4ba691.png)

### What is the expected result?
blocked this script per this single site

### What is the actual result?
blocked this script per all sites

### Environment
- Browser: chrome
- Browser version: 64.0.3282.186
- Violentmonkey version: v2.8.29
- OS: win10

**Comment by gera2ld** [comment]
Currently it is the expected behavior to block a script in all sites.

**Comment by KonoromiHimaries** [comment]
> Currently it is the expected behavior to block a script in all sites.

there is no point in duplicating functions
this feature is already supported by the main panel
![2018-03-13-violentmonkey](https://user-images.githubusercontent.com/5884000/37340784-76bbbf2a-26bf-11e8-939d-a49262dd998b.png)

**Comment by gera2ld** [comment]
The switch in popup menu is much easier to be found, so you don't need to open the dashboard and find the script by yourself. I don't think they are just duplicate.

**Comment by KonoromiHimaries** [comment]
> Do you expect that?

add some button to i do can block script per single specific site, this is what i'm expect.

**Comment by elypter** [comment]
it would also be helpful to be able to enable/disable on an url, subdomain and domain basis

**Comment by IRlyLikeBac0n** [comment]
Hey is this issue still being worked on? If so, could you also work in a way to exclude sites from the sub-frames too? Thanks
