### ISSUE TITLE
some scripts won't work in in violent monkey 

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#369]
honestly I m super disappointed byby violent monkey this userscript (https://greasyfork.org/it/scripts/12367-open-links-in-new-tab/code?version=148492)

which forces forces every link to open in new tab is not working with violent monkey,instead works perfectly with TAMPERMONKEY,why is happening this ?

**Comment by gera2ld** [comment]
Works for me.
Please fill the issue template, otherwise it's just a waste of time for both of us. Maybe you can use Tampermonkey instead.
