### ISSUE TITLE
cltrKey altKey not working

### ISSUE THREAD

**Issue by pikopikopikopiko** [violentmonkey/violentmonkey#370]
not sure if it was the firefox update (59) or violentmonkey update (....30) but now cltrkeys are broken
$(function() {
document.body.addEventListener('keydown', function (e) {
  alert(e.ctrlKey);
});
})

ctrl + any of Fnumer (or any special keys like arrows, pageup and so on) gives true 
while ctrl + any of chars gives false

ok folks this is Firefox 59 issue I think because pure javascript does not work too, but any solution?

**Comment by gera2ld** [comment]
Maybe you should file a issue to Firefox. There is no solution here.

**Comment by Thorin-Oakenpants** [comment]
Do you have `privacy.resistFingerprinting` enabled and are using FF59+?

In FF59+ see [Bugzilla 1222285](https://bugzilla.mozilla.org/show_bug.cgi?id=1222285) - spoof keyboard events and suppress keyboard modifier events (FF59+)
 - Spoofing mimics the content language of the document. Currently it only supports en-US. Modifier events suppressed are SHIFT, CTRL and both ALT keys. Chrome (that is the FF interface) is not affected.

Hopefully in FF59.0.2 (not yet released) see [Bugzilla 1433592](https://bugzilla.mozilla.org/show_bug.cgi?id=1433592) - don't spoof/suppress CTRL key (its too universally used)

**Comment by pikopikopikopiko** [comment]
Thorin-Oakenpants thank You, You saved my day, funny thing no issue unless upgrade to 59, thank you again!

**Comment by Thorin-Oakenpants** [comment]
59.0.2 is now released and that fix is in there. So your ctrl key is ok, can't do much about your alt keys

>  funny thing no issue unless upgrade to 59

That's because the patch for suppressing modifier keys didn't land until 59
