### ISSUE TITLE
Script doesn't get applied when site is loaded in sidebar

### ISSUE THREAD

**Issue by d-desch** [violentmonkey/violentmonkey#376]
### How to reproduce it?
1. Create a script with `// @match *://*/*` and `console.log('script applied');` as code
2. Create a bookmark which loads in Sidebar (checkbox in new/edit bookmark dialog)
3. Click on the bookmark

### What is the expected result?
The script should get applied

### What is the actual result?
The script doesn't get applied 

### Environment
- Browser: Firefox ESR
- Browser version: 52.7.0
- Violentmonkey version: 2.8.27
- OS: Windows 10 Pro (1709)

**Comment by gera2ld** [comment]
I think this is likely a feature of Firefox though I did not find an explicit description yet.

According to the [document](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Sidebars):
> Sidebar documents get access to the same set of privileged JavaScript APIs that the extension's background and popup scripts get.

I think this indicates that sidebar documents are different from those in main window. So they might not be injected by content scripts. There is even no "Inspect Element" in its context menu.

**Comment by d-desch** [comment]
Ok, thanks.
Do you think it's gerneral possible to inject scripts in the sidebar?

**Comment by gera2ld** [comment]
I don't think it possible.
Closing since this is not a Violentmonkey issue.
