### ISSUE TITLE
Missing latest version on AMO??

### ISSUE THREAD

**Issue by xxz12102** [violentmonkey/violentmonkey#378]
[AMO](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)
> Version
> 2.6.3
> Last updated
> 4 months ago (Dec 1, 2017)

**Comment by gera2ld** [comment]
They put it down due to the injection via blob, which was introduced to fix #173 .

**Comment by mk-pmb** [comment]
Is there a recommended way how to install the latest version in Firefox? Couldn't find it in the readme or on the website.

**Comment by Mattwmaster58** [comment]
@mk-pmb  2.9.0 was just uploaded to AMO yesterday if you're interested.

**Comment by mk-pmb** [comment]
Thanks! With 2.9.0, installing my user script works.
