### ISSUE TITLE
"Error loading dependencies."

### ISSUE THREAD

**Issue by mk-pmb** [violentmonkey/violentmonkey#381]
### What is the problem?

I can't install my user script.

### How to reproduce it?
1. Visit https://gist.github.com/mk-pmb/a69f3baf91941072d0ae2527632614f0
2. Click the "raw" button next to `foo.user.js`

### What is the expected result?

Script installs

### What is the actual result?

Below the greyed-out "confirm install" button it says "Error loading dependencies."

### Environment
- Browser: Firefox
- Browser version: 57
- Violentmonkey version: 2.6.3
- OS: Ubuntu

**Comment by gera2ld** [comment]
See #378

**Comment by mk-pmb** [comment]
Thanks! Maybe add a big warning near the top of the readme?

**Comment by mk-pmb** [comment]
I still get the same error now with v2.9.0, Firefox v59.
I updated the URL in my first post.

**Comment by mk-pmb** [comment]
Seems like I misunderstood how to use the `@require`; when I remove the `@resource` entry for my `@require`d file, it seems to install again.

**Comment by mirt001** [comment]
> 
> 
> See #378

This leads to a 404. It would be useful to include the solution in the comment itself, if at all possible
