### ISSUE TITLE
Doesn't run on github.com

### ISSUE THREAD

**Issue by noscript** [violentmonkey/violentmonkey#383]
### What is the problem?

Scripts don't run on github.com

### How to reproduce it?
1. Create a script:
```
// ==UserScript==
// @name Hello World
// @namespace Violentmonkey Scripts
// @include *
// @grant none
// ==/UserScript==

(() => {
  alert("hello world");
})();
```
2. Visit https://github.com

### What is the expected result?

Alert with "hello world".

### What is the actual result?

Nothing.

### Environment
- Browser: Firefox
- Browser version: 61.0a1 (2018-04-02) Nightly
- Violentmonkey version: v2.9.0
- OS: Linux x86_64

**Comment by gera2ld** [comment]
Firefox reviewers have rejected the workaround.
https://github.com/violentmonkey/violentmonkey/blob/c94aeba8a3a713db98143217ffda17c03ea51bdf/src/injected/utils/index.js#L50-L52

**Comment by noscript** [comment]
Is there a workaround? At least the script works in latest Greasemonkey.

**Comment by gera2ld** [comment]
Greasemonkey does not run scripts in the real page. However, Violentmonkey needs to run in the real page to get `unsafeWindow` working since there is no `wrappedJSObject` in Chrome.

**Comment by gera2ld** [comment]
See #385
