### ISSUE TITLE
How to fetch remote files dynamically? (no GM_xmlHttpRequest?)

### ISSUE THREAD

**Issue by mk-pmb** [violentmonkey/violentmonkey#387]
### What is the problem?

I can't find (in the docs here or over at Greasespot Wiki) a violentmonkey-compatible way to fetch remote files dynamically.

### How to reproduce it?
1. Visit https://gist.github.com/mk-pmb/3a8faa4cbc7410fbfaccdedfac6360f5
2. Click the "raw" button to install.
3. Visit http://spaceweb.pimpmybyte.de/ (or a gist) and observe console.

### What is the expected result?

```text
monkey version: Violentmonkey 2.9.0
monkey foo features: {
  "GM": null,
  "GM_info": "object",
  "GM_getResourceUrl": null,
  "GM_xmlHttpRequest": "function",
  "GM_getResourceText": "function",
  "gm_info": null,
  "gm_getResourceUrl": null,
  "gm_xmlHttpRequest": null
}
monkey foo xhr: Object { … }
```

### What is the actual result?

```diff
   "GM_getResourceUrl": null,
-  "GM_xmlHttpRequest": "function",
+  "GM_xmlHttpRequest": null,
   "GM_getResourceText": "function",
@@ … @@
 }
-monkey foo xhr: Object { … }
+ReferenceError: GM_xmlHttpRequest is not defined
```

### Environment
- Browser: Firefox
- Browser version: 56
- Violentmonkey version: 2.9.0
- OS: Ubuntu trusty

**Comment by mk-pmb** [comment]
Will the fetch API (`window.fetch`) be privileged/unrestricted when called from within a UserScript?

**Comment by mk-pmb** [comment]
Thanks! Where can I look up such details about the VM API? Could have save me many hours of debugging since I had to guess from the Greasespot Wiki and they only had [the new API with uppercase H](https://wiki.greasespot.net/GM.xmlHttpRequest).

**Comment by alphabug** [comment]
VM follows the old GM3 API, so, use an old version of the GM wiki page.  https://wiki.greasespot.net/index.php?title=Greasemonkey_Manual:API&oldid=7385

The only difference that I know of is that VM additionally supports @exclude-match in the metadata block.
