### ISSUE TITLE
blank match rule in settings resolves to *://*/*

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [violentmonkey/violentmonkey#388]
### What is the problem?
disabling match rules by unchecking "match originals" and without specifying new rules makes a script run everywhere.

### How to reproduce it?
1. Use the following script.

```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match *://github.com/*
// @grant none
// ==/UserScript==
alert('test');
```

2. 
![image](https://user-images.githubusercontent.com/8885056/38491101-f5d9d4c8-3bb8-11e8-9a69-07e4f665cee5.png)

### What is the expected result?
Script doesn't run anywhere, as no matches are defined for this script.

### What is the actual result?
Script runs everywhere.

### Environment
- Browser: Chrome
- Browser version: 67.0.3390.0
- Violentmonkey version: 2.9.0
- OS: Windows

**Comment by gera2ld** [comment]
I think this commit should be reverted. According to [greasemonkey document](https://wiki.greasespot.net/Include_and_exclude_rules), blank rules should match everything.
