### ISSUE TITLE
GM_xmlhttpRequest GET transformed into a HEAD?

### ISSUE THREAD

**Issue by OhSoGood** [violentmonkey/violentmonkey#392]
Hi,

Thanks for ViolentMonkey, I really like it!

I am trying to use that script https://greasyfork.org/fr/scripts/21921-dealabs-compagnon on its targeted website. This site basically performs this:
```
            GM_xmlhttpRequest({
                url: urlchiffree,
                method: "GET",
                onload: function(response) {
                    var link = response.finalUrl;
                    link = decodeURIComponent(link);
                    removeaffiliate(link);
                },

```
Pretty simple, but the issue is that, in the Firefox console, it's always a HEAD request which is done. What am I missing? Is there a trick somewhere, a bug, or could another extensions or setting of Firefox transform the GET into a HEAD?

Any idea appreciated!

**Comment by alphabug** [comment]
You should look at the entire urlcleaner function. In that script, GM_XHR is called as backup inside a normal XHR HEAD request. So you will always have a HEAD request and sometimes both HEAD and GET.

**Comment by OhSoGood** [comment]
My bad, I went too fast reading it. Thanks for having taken the time to help me.
