### ISSUE TITLE
add hotkey example in documentation

### ISSUE THREAD

**Issue by edgimar** [violentmonkey/violentmonkey#393]
Since hotkeys aren't handled as a feature of the violentmonkey extension, it would be helpful to provide users with information in the online documentation on how to "bind" their scripts to hotkeys.  As an example, see [this script](https://gist.github.com/edgimar/44522bfdde53a3e128288fb00056360e).

**Comment by gera2ld** [comment]
See https://github.com/violentmonkey/vm-shortcut

**Comment by edgimar** [comment]
Thanks for working on this -- I do think it would be good to have an example that doesn't add another dependency, however.  Maybe add the vm-shortcut code into the libraries bundled with violentmonkey?

**Comment by gera2ld** [comment]
I don't think it should be bundled with Violentmonkey since it does not require any special APIs. It's just pure JavaScript and works with other script manager (such as Greasemonkey) too.

**Comment by edgimar** [comment]
That is a valid point, but couldn't both objectives be achived (bundling, and making accessible to other script managers)?  So maybe leave vm-shortcut as it's own repository, but add it as a git submodule in the violentmonkey repo, and make it so that when someone installs violentmonkey in their browser, they can begin to use `registerShortcut` in their scripts without needing to do anything else.
