### ISSUE TITLE
Version 2.9.2 doesn't seem to load scripts inside an iframe

### ISSUE THREAD

**Issue by noamparn** [violentmonkey/violentmonkey#398]
### What is the problem?
Version 2.9.2 doesn't seem to load scripts inside an iframe. Those same scripts load just fine if the page inside the iframe is opened in its own tab. Downgrading to 2.9.1 works to get those scripts to load inside the iframe, too. 

### How to reproduce it?
1. Install add-on version 2.9.2 
2. Refresh the page

### What is the expected result?
Scripts should load

### What is the actual result?
Scripts don't load
### Environment
- Browser: Firefox ESR
- Browser version: 52.7.3
- Violentmonkey version: 2.9.2
- OS: Windows 10

**Comment by ale82to** [comment]
same problem on an android i m speechless !

**Comment by gctommy** [comment]
+💯

**Comment by gera2ld** [comment]
Please upgrade to v2.9.4
