### ISSUE TITLE
GM_setValue data not synced between tabs

### ISSUE THREAD

**Issue by ccd0** [Violentmonkey/Violentmonkey#40]
If I open two tabs, change a value in one tab with GM_setValue, then try to read it in the other tab with GM_getValue, the second tab doesn't see the change.

Here's a test case. Open http://www.example.com/ in two tabs, shift-click in one tab to increase x, and click in the other to read x.

	// ==UserScript==
	// @name GM_getValue test
	// @namespace test
	// @include http://www.example.com/
	// @grant GM_getValue
	// @grant GM_setValue
	// ==/UserScript==
	
	document.addEventListener('click', function(e) {
		if (e.shiftKey) {
			var x = GM_getValue('x') || 0;
			x++;
			GM_setValue('x', x);
			document.body.textContent = 'set: x=' + x;
		} else {
			var x = GM_getValue('x') || 0;
			document.body.textContent = 'get: x=' + x;
		}
	}, false);

Tested with Violentmonkey 2.2.2, Opera 34.0.2036.31, Windows 10 64-bit.

**Comment by gera2ld** [comment]
This is a known issue, but is it really necessary?

**Comment by ccd0** [comment]
Yes, otherwise you get data loss.
To give an example from a script I'm maintaining, 4chan X adds a button to hide posts on 4chan, storing the list of hidden posts with GM_setValue. Say you have https://boards.4chan.org/c/thread/2570357 open in one tab and http://boards.4chan.org/c/thread/2539836 in another. (I'm deliberately using http and https in this example because if they're on the same origin, 4chan X will attempt to sync data using localStorage.) If you hide a few posts in the first thread, then hide some more posts in the second thread, then reload the first thread, the posts you hid in the first thread reappear!

**Comment by gera2ld** [comment]
I thought `GM_getValue` and `GM_setValue` are mostly used to share data among tabs with different domains in which case data sync might not be so necessary. I prefer using `localStorage` to share data that needs synced since `localStorage` is built-in and synchronous.

Anyway, data sync sounds reasonable. This feature will be added soon.
