### ISSUE TITLE
v2.9.2 Stopped working with jQuery

### ISSUE THREAD

**Issue by pikopikopikopiko** [violentmonkey/violentmonkey#400]
not a single alert("hello"); works with jquery on Windows Server with Firefox x64, 
this issue appears only with v2.9.2 only I had to revert to 2.9.1 and all works again

simple alert("hello") was working but 
$(function () {
alert("hello");
})
does not

v2.9.1 works ok on any website

**Comment by krystian3w** [comment]
Yeah.

My 2 little scripts + "Resize YT To Window Size" script no works 🤣.

**Comment by TheOneBehindYou** [comment]
Yes the last update broke some scripts. Those two I use for example: https://greasyfork.org/fr/scripts/38530-google-view-image-button and https://greasyfork.org/fr/scripts/6856-youtube-toggle-comments.
Revert to previous version (2.9.1) in order to use them.

**Comment by GavinBrelstaff** [comment]
How do I revert to 2.9.1 ?

**Comment by krystian3w** [comment]
Block update and click all versions in mozilla store addons.

**Comment by Phyxion** [comment]
2.9.3 not working here either, almost all my scripts broke, reverted back to 2.9.1.

**Comment by krystian3w** [comment]
@Phyxion  create new issue maybe other changes blocked your script (no affected with jQuery).

**Comment by gera2ld** [comment]
Please upgrade to v2.9.4
