### ISSUE TITLE
about:debugging throws an error

### ISSUE THREAD

**Issue by theWalkingDuck** [violentmonkey/violentmonkey#402]
running `about:debugging` throws the following error

```
      Reading manifest: Error processing options_page: 
      An unexpected property was found in the WebExtension manifest.
```

### Environment
- Browser: Firefox
- Browser version: 59.0.2
- Violentmonkey version: 2.9.2 + 2.9.3
- OS: Linux

**Comment by gera2ld** [comment]
It's just a warning.
