### ISSUE TITLE
What about wiki?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#405]
In details of latest 2.9.4 version I read:
• add **GM_unregisterMenuCommand**

So I suppose **GM_registerMenuCommand** function exists as well.

What these functions about? I tried to find answer in VM wiki, but I failed.

If there detailed VM wiki?

**Comment by gera2ld** [comment]
See Wiki [here](https://violentmonkey.github.io/api/gm.html#GM-unregisterMenuCommand).
See also #396 .

**Comment by soviet-man** [comment]
Thank you for wiki link.

I have another question. Why are commands of scripts placed in one list?
I can make script1 with command
`GM_registerMenuCommand( 'press me', () => { alert( 'pressed' ) } ) `
and script2 with command
`GM_registerMenuCommand( 'press me', () => { alert( 'pressed' ) } ) `

These commands looks the same

**Comment by gera2ld** [comment]
Because it takes too much space to display information about scripts.
Generally, there shouldn't be too many or too similar menu items, otherwise it would be hard for the user to find what he or she wants and the menu becomes useless. So I think scripts should add proper names for their menus.
