### ISSUE TITLE
Firefox CSP issue

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#408]
Just #173 again.

**Comment by Dezaimasu** [comment]
Can confirm. Latest Nightly version (2018-05-29).
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: !function e(a){var b=document.querySelec....`

It works only with security.csp.enable=false which disables CSP check completely.

**Comment by afontenot** [comment]
This hasn't been discussed in several months. Is any kind of fix incoming? I can't get any scripts working on Twitter.

**Comment by noscript** [comment]
I have to use both Greasemonkey and Violentmonkey simultaneously as both are broken at the moment:
* Greasemonkey doesn't run on iframes (https://github.com/greasemonkey/greasemonkey/issues/2574)
* Violentmonkey doesn't run on pages with Content Security Policy manifest (https://github.com/violentmonkey/violentmonkey/issues/408)

**Comment by gwarser** [comment]
https://violentmonkey.github.io/2018/11/23/inject-into-context/
