### ISSUE TITLE
lots of UserScript works way worse on latest version than 2.8.14f

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#411]
### How to reproduce it?
1 install viewtube UserScript https://greasyfork.org/it/scripts/2984-viewtube

2.with violent monkey 2.9. 4 sometime script fails with tampermonkey 2.8.14 f everything works as expectwd
3.
can someone explain why lots of UserScripts works better with violentmonkey 2.8.14f version rather than latest version 2.9.4 with Firefox for Android ?
view tube is an example but many others like Instagram native player (https://greasyfork.org/it/scripts/27180-instagram-native-player) works perfectly with version 2.8.14f instead with latest 2.9.4 version in order to make it work i ve got to reload the page. 

### Environment
- Browser: Firefox both stable and nighlty 
- Browser version:Android
- Violentmonkey version:2.9.4
- OS:Android marshmallow

**Comment by ale82to** [comment]
any any news ?

**Comment by tophf** [comment]
Can't do anything without a definitive sequence of steps to reproduce the problem.
