### ISSUE TITLE
[Feature Request] GM_config

### ISSUE THREAD

**Issue by chocolateboy** [violentmonkey/violentmonkey#414]
So far, Violentmonkey has done a great job of achieving parity with classic Greasemonkey. :tada: Now that the dust has settled, perhaps it's worth considering adding an enhancement or two to the platform?

One thing forks such as [Scriptish](https://github.com/scriptish/scriptish) did is add support for [new APIs](https://github.com/scriptish/scriptish/wiki/Manual%3A-API), in the same way browsers prototype and pioneer extensions to the web platform. One piece that's missing from the userscript puzzle is a way to present the user with a config/settings page. There's an [appetite for this](https://stackoverflow.com/q/14594346), but the solutions are either [unattractive](https://i.imgur.com/RTf9c15.png) or [unmaintained](https://github.com/odyniec/MonkeyConfig). If it was built-in, with a common/core API, it could make userscripts the natural choice for the sizeable number of customizable pagemods that don't otherwise need to be full-blown extensions.

It's clear from Violentmonkey's UI/UX and its website that design is an interest. This is an opportunity to leverage that interest in a way that could benefit the whole ecosystem and help to re-establish userscripts as the go-to platform for portable browser-extensions. MUGA!

## UI, Usage, API, Notes

**Edit**: Moved [here](https://github.com/chocolateboy/userscripts/wiki/GM_config).

## See Also

* [Legacy Spec for Firefox-Addon Preference Pages](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/High-Level_APIs/simple-prefs)
* [MonkeyConfig](https://github.com/odyniec/MonkeyConfig)
* [sizzlemctwizzle/GM_config](https://github.com/sizzlemctwizzle/GM_config)

**Comment by eight04** [comment]
There are some discussions about config API in Greasemonkey too:
https://github.com/greasemonkey/greasemonkey/issues/2714

**Comment by chocolateboy** [comment]
I've moved the details of this proposal to a wiki page, so it's a) versioned and b) something anyone can contribute to:

https://github.com/chocolateboy/userscripts/wiki/GM_config

Feel free to discuss the proposal here and/or make changes there.

**Comment by chocolateboy** [comment]
https://github.com/mozilla-services/react-jsonschema-form

**Comment by tophf** [comment]
There should be some unified effort between engines so we will consider implementing this only if Tampermonkey does it first. As for Greasemonkey, its stance is evidently to provide only the bare minimum or even less than that.

**Comment by tophf** [comment]
Closing due to the lack of any progress in Tampermonkey and @gera2ld's usual reluctance to ship stuff that can be implemented by userscript authors in JS.

**Comment by gera2ld** [comment]
I think this can be implemented in [vm-ui](https://github.com/violentmonkey/vm-ui) as pure JavaScript, in a script-manager-agnostic way.

Ref: https://github.com/violentmonkey/vm-ui/issues/1
