### ISSUE TITLE
Compatibility with Firefox Multi-Account Container

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#415]
Add compatibility with [Firefox Multi-Account Container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) and other [container related extensions](https://addons.mozilla.org/en-US/firefox/search/?q=container). Currently, `GM_xmlhttpRequest` would fail when browsing in a container.

Here are more details about [containers in Firefox](https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/).

**Comment by tophf** [comment]
Should be fixed because gmxhr is now using tab's `cookieStoreId` in Firefox.
