### ISSUE TITLE
ig helper Instagram Downloader is not working with version 2.9.5

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#418]
### How to reproduce it?
1.install latest violentkonkey 2.9.5
2.install ig helper user script (https://greasyfork.org/it/scripts/22660-ig-helper-download-instagram-pic-vids) 
3.

### What is the expected result?
pressing download button should download pics

### What is the actual result?
NOTHING HAPPEN 
### Environment
- Browser:Firefox nighlty 62
- Browser version:62
- Violentmonkey version:2.9.5
- OS:android marshmallow 

reverting to old version 2.9.4
everything woks as expected can please someone tell me why every single update of violent monkey breaks something ?n

**Comment by gera2ld** [comment]
Closing since this is a bug of the script.

**Comment by ale82to** [comment]
how can be a bug of the script if with violent monkey 2.9.4 works ?

**Comment by mittya** [comment]
@gera2ld is right, the script's bug.

@ale82to Userscript is fixed.

You can close the issue :slightly_smiling_face:

**Comment by ale82to** [comment]
yes thank you a i reported th e bug to the the author and today update fixed the issie
