### ISSUE TITLE
某腳本在暴力猴下出現異常的問題

### ISSUE THREAD

**Issue by hdd60311** [violentmonkey/violentmonkey#419]
https://greasyfork.org/zh-TW/scripts/368445-term-ptt-cc-%E8%87%AA%E5%8B%95%E7%99%BB%E5%85%A5
在火狐和chrome都一樣，這腳本從0.2.3版開始在暴力猴下進入https://term.ptt.cc/ 會停在黑畫面沒有反應，0.2.2版正常，在Tampermonkey都是正常運作。(已問過腳本作者說建議來這報issue)

**Comment by gera2ld** [comment]
我看了下这个脚本就是有问题的吧，这个脚本的88行`WebSocket`改成`_WebSocket`就好了。

**Comment by kryptoniancode** [comment]
WebSocket feature in userscript similar to GM_xmlhttpRequest like GM_webSocket.
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

**Motivation**


I want to use websocket for request with url `wss://`. It is not possible with `GM_xmlhttpRequest`, I have tried but the request changed to `https`.

**Proposed Solution**


Similar to WebSocket class present in browser.

**Use Cases**

**Comment by tophf** [comment]
As the name suggests GM_xmlhttpRequest is for http requests, also the way WebSocket API is used is entirely different, so we won't add it there. It might make sense to add a new function like GM_webSocket though.

**Comment by kryptoniancode** [comment]
Thanks, looking for the feature to be added to the amazing extension.
