### ISSUE TITLE
Implement real @run-at document-start

### ISSUE THREAD

**Issue by KOLANICH** [violentmonkey/violentmonkey#420]
I'm interested in `document-start`.

**Comment by gera2ld** [comment]
`document-start` is not guaranteed.

**Comment by KOLANICH** [comment]
1 It seems that runAt is not implemented at all. Do I understand right?
2 Can `contentScripts.register` solve this issue?

**Comment by gera2ld** [comment]
1. `@run-at document-start` is not guaranteed, the script is just injected ASAP.
2. `contentScripts.register` should help, but Chrome does not support it.

**Comment by KOLANICH** [comment]
1. Searched one more time by downloading and grepping, now I see it is used.
2. Should we implement the separate logic for the browsers with this API?

**Comment by gera2ld** [comment]
> Should we implement the separate logic for the browsers with this API?

Personally, I don't use Firefox as my primary browser, and I don't want to take much time on Firefox-only features. Anyway it's good to have a way to implement it and PRs are welcome.

**Comment by bfred-it** [comment]
> `contentScripts.register` should help, but Chrome does not support it.

You can use the [Chrome polyfill for `browser.contentScript.register`](https://github.com/bfred-it/content-scripts-register-polyfill#readme) for that API

**Comment by gera2ld** [comment]
@bfred-it Nice idea.

But I wonder whether `document-start` is reliable in this polyfill. In the listener there are several asynchronous functions, but the tab is loading and it would not wait for the listener to finish its asynchronous tasks.
Consequently, at the time when scripts are injected, the tab may have been loaded already.
I think it makes no difference with the current Violentmonkey way, to inject ASAP.

**Comment by bfred-it** [comment]
> But I wonder if `document-start` is reliable in this polyfill

I did verify that the CSS works correctly (without FUOC) with `document_start` but I didn't verify the speed of the scripts.

I expect the native Firefox `register()` API to behave as well as the regular `content_script` injection via manifest.json, while the polyfill uses `tabs.executeScript` to inject the script on `tabs.onUpdated`, which is the fastest way I'm aware of.

How are scripts currently injected in `violentmonkey`?

**Comment by gera2ld** [comment]
Just made an experiment and the conclusion is, **even injecting script on tab update synchronously, `document_start` cannot be ensured.**

Here is my code:

```js
chrome.tabs.onUpdated.addListener((id, changedInfo, tab) => {
  if (changedInfo.status === 'loading') {
    browser.tabs.executeScript(id, {
      code: 'console.log(Date.now(), document.head.outerHTML);',
      runAt: 'document_start',
    });
  }
});
```

The console shows lots of elements in `document.head`, including script elements, which means we have already lost the `document_start` chance.

I think it impossible to implement such a feature without support of native browser because of racing between threads.

**Comment by gera2ld** [comment]
> How are scripts currently injected in violentmonkey?

Currently Violentmonkey injects its runtime scripts at `document_start` which can be ensured by the browser, and loads everything asynchronously. Scripts are injected once loaded.

**Comment by bfred-it** [comment]
I think you can only compare it to what regular extensions allow via manifest.json. What's the output of something like this?

```json
{
	"content_scripts": [{
		"js": ["file.js"],
		"matches": "<all_urls>"
	}]
}
```
```js
// file.js
console.log(Date.now(), document.head.outerHTML);
```

**Comment by gera2ld** [comment]
```
{
	"content_scripts": [{
		"js": ["file.js"],
		"matches": "<all_urls>"
	}]
}
```
In this way `document.head` is `null` since the script runs before everything else, as expected.

Scripts are different from CSS because they execute. Once excuted, they cannot revert unless the page reloads. So if a script asks to run at `document_start`, it is possible that it needs to hack something before other scripts are loaded. In such cases *"asap, hopefully before first paint"* is not enough.

So `document_start` does mean *"before everything else"* for userscripts to do magic things.
Otherwise it has little difference with `document_body`.

**Comment by tophf** [comment]
@gera2ld what about implementing the **real** `document-start` for **userscripts**?

* In Chrome this can be done using [webRequest + cookies + synchronous XHR](https://stackoverflow.com/a/45105934) trick (also implemented in TM).

  The upside is that userscripts will be able to augment sites deeply/seemlessly by modifying stuff/DOM/API before the page scripts in `<head>` do.

  The downside is that it'll spam the console with deprecation warnings about syncXHR (negligible; can be hidden via console filter for good). And of course it'll stop working in ManifestV3. I doubt they'll get around to implementing proper support for dynamic content script code provided in a string.

  There are some rare cases when this trick will run too late: superfast navigation like when the page is shown on history back or its html is small and the server is superfast.

* In Firefox there's a native API [browser.contentScripts.register](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register) so you can use to register scripts individually with matches, globs, runAt, and code like `injectScript(${JSON.stringify(script)})` that'll run injectScript function in the content script.

**Comment by tiansh** [comment]
If I don't need `GM_getValue`, but only `GM.getValue`. Is it possible to get real document-start?

**Comment by tophf** [comment]
As I said above it is possible. Either implement it yourself (and open a pull request) or wait for someone else to do it. There's no timetable so no one knows when and if this will be implemented.

**Comment by tophf** [comment]
I'm closing this as the new 2.12.8 (currently beta) should be fast enough to be running userscripts before the first page script. If people show us examples where it doesn't, we will probably merge #1100 or find another solution.

**Comment by tophf** [comment]
Now that we inject much less data at document-start, the next release will have a synchronous (instant) inject mode, disabled by default.

![image](https://user-images.githubusercontent.com/1310400/140660030-6c43ec61-905d-4b82-b9da-ecb8fc1779ea.png)
