### ISSUE TITLE
Problems using JQuery in ViolentMonkey on Jira

### ISSUE THREAD

**Issue by fenjen** [violentmonkey/violentmonkey#421]
### What is the problem?
In [Jira](https://www.atlassian.com/software/jira), when I open an issue, I can trigger a click on the tabs "Text" or "Visual" by executing this command in the browser console:
`$('a[role="tab"]:contains("Text")').click();`
But when I enable a ViolentMonkey script with `@require jquery`, this doesn't work any more. (Even in browser console.)

### How to reproduce it?
1. Find a Jira installation
2. Click on "Create"
3. Switch to `Visual` tab if not already selected
4. In the JS console, run `$('a[role="tab"]:contains("Text")').click();`
5. Notice the change
6. Create a ViolentMonkey script with the contents below
7. Repeat steps 2-4
8. Notice the click is not triggered

```
// ==UserScript==
// @name Jira
// @namespace Violentmonkey Scripts
// @match ...
// @require https://code.jquery.com/jquery-1.7.2.min.js
// @grant none
// ==/UserScript==
```
(I tried all major JQuery versions.)

### What is the expected result?
I can trigger the click event from ViolentMonkey (and from the browser console).

### What is the actual result?
Click event is not triggered with the command `$('a[role="tab"]:contains("Text")').click();` - the tab won't change when ViolentMonkey is enabled and `@require`s JQuery.

### Environment
- Browser: Firefox Developer Edition
- Browser version: 61.0b8 (64-bit)
- Violentmonkey version: 2.9.5
- OS: Windows 10

In order to gain access to JQuery, I also tried to `@grant unsafeWindow`, for accessing `$`. This worked once, but now I'm unable to revive this behaviour.

**Comment by gera2ld** [comment]
Sorry but I don't have an account for Jira and cannot reproduce the issue.
Is there any error in your console?
Can you add `console.log($)` to see if jQuery is successfully loaded?

**Comment by steffenbr** [comment]
Without ViolentMonkey, I get
```
> console.log($)
function j()
> console.log(jQuery.fn.jquery)
1.7.2
```

1. In ViolentMonkey with this script:
```
// ==UserScript==
// @name Jira
// @namespace Violentmonkey Scripts
// @match *://jira.macmon.local/*
// @grant unsafeWindow
// ==/UserScript==
console.log($);
console.log(typeof $);
console.log(unsafeWindow.$);
console.log(typeof unsafeWindow.jQuery);
console.log(window.wrappedJSObject);
```
I get this:
```
undefined
undefined
undefined
function
undefined
```

2. In ViolentMonkey with
```
// ==UserScript==
// @name Jira
// @namespace Violentmonkey Scripts
// @match *://jira.macmon.local/*
// @grant unsafeWindow
// @require https://code.jquery.com/jquery-1.7.2.min.js
// ==/UserScript==
console.log($);
console.log(typeof $);
console.log(unsafeWindow.$);
console.log(typeof unsafeWindow.jQuery);
console.log(window.wrappedJSObject);
```
I get this:
```
function e()
function
undefined
function
undefined
```

Generally, if a site uses JQuery, a) do I have to b) should I or c) should I not `@require` it in order to make it available in my ViolentMonkey scripts? And if so, do I have to address the same version?

**Comment by gera2ld** [comment]
You can use `unsafeWindow.$` directly: `var $ = unsafeWindow.$;`.
Requiring a new one should also be OK.

The script should have worked since you have got `$` correctly. Maybe there is something wrong with the lower level operations. Sorry but I am not able to debug it since there is no reproduction for me.

**Comment by tophf** [comment]
Try also https://api.jquery.com/jQuery.noConflict
