### ISSUE TITLE
Accessing and editing files with the help of NiklasGollenstede's native-ext

### ISSUE THREAD

**Issue by brunoais** [violentmonkey/violentmonkey#423]
Even if as an extension to violentmonkey, are there any opinions or tests for making code to work in conjunction with [NiklasGollenstede's native-ext](https://github.com/NiklasGollenstede/native-ext) to provide file editing in the user's preferred editor?

I'm aware of the attempts made to make this less painful by using a python server... But I do believe that we could use `native-ext` to remove that requirement altogether

**Comment by gera2ld** [comment]
Like this? https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/

**Comment by brunoais** [comment]
Yes, except:
1. There would be no need for a server managed by the script maintainer/editor
2. The files in the file system could always stay in sync with the ones stored in the DB, so there wouldn't even be the need to go to the menu to edit the file in the first place (AKA: How it could have been if this hadn't been made directly into a webextension extension format)
3. The user's editor of choice could be opened for the file without the need for the user to open it himself and then track where the file to be edit is.

IMO, that would be better as an extension for this extension, btw.

**Comment by brunoais** [comment]
@gera2ld any more comments?

**Comment by gera2ld** [comment]
@brunoais That's a good idea except that it requires another extension to be installed. Anyway, it's OK for me since it's optional.

Unfortunately I don't have much time working on this recently, so PRs are welcome.

**Comment by brunoais** [comment]
@gera2ld My idea exactly. 
Hum.... May you please give me minor guidance? It would save me a lot of hours if you can point me to:

1. VM: Creating events:
1.1. Announcing a script had been created/edited (on the internal editor)
1.2. Announcing a script is being loaded into the page (giving the script's content and modification date along with the event; allows another chance to get a script update from the file system)
1.3. Announcing when the user wants to edit the file (opens the user's favourite editor for that file)
1.3.1. The file also becomes watched for changes, so any changes made are directly announced back to VM. (see 2.1)
1.3.2. It may be a good idea to allow the user to choose which editor to use (external or internal), even with the extension active.
2. VM: Event listeners (I can create the listeners themselves but I need to know what functions to call)
2.1. What functions to call to store an edited file (externally; includes content and modification date)
2.1.1. Note: An edited file is usually the user script but it can also be a resource it uses.

Additionally, How should the extension request for the script in the file(s) every time a userscript is wanted?
1. User sees unwatched file updates **right away** OR
2. User sees unwatched file updates on the **subsequent page reload**.

With those elements, I can plan better and work on the VM extension more easily.

Thank you for the interest!

**Comment by gera2ld** [comment]
Sorry for the late response.

I have implemented some methods to support plugins here: https://github.com/violentmonkey/violentmonkey/commit/316001844d7ee641a470cda9e12c90bb6402d0d5

There are two events:
- `scriptEdit` indicates that user requests to edit the script (not implemented yet)
- `scriptChanged` indicates that a script is changed, either created or updated, and you may sync it to the file system.

Does that satisfy your demand?

**Comment by brunoais** [comment]
Unfortunately, no. There's a need to send events on both ends or to open a communications channel.
If you choose pure events approach (seems to be the easiest), then you need to place listeners for the external sender. For that, you need to use [`onMessageExternal`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessageExternal). For example,

	browser.runtime.onMessageExternal.addListener(function(request, sender, responseChannel) {
		
		if (!isExternalAccessAllowed(request, sender)) {
			sendResponse({
				status: 'ACCESS_DENIED', // <- Or whatever you prefer
				message: 'You are not authorized to communicate with ViolentMonkey',
			});
			return;
		}
		// ... Whatever code to handle the event
	})

Additionally, when starting the script, there's a need to know which scripts to communicate to. A practical example is what Simple Tab Groups did:
(starting up) https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/background.js#L2188
(broadcasting an event) https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/background.js#L245
(listen to another addon's message) https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/background.js#L1499

For the event manager you did, what I can see is something that would have to be packed with your extension..... 

As for those two:
`scriptEdit` and `scriptChanged` work just fine for the objectives here. A request for edit and an announce that an edit was made. Both can be used in both ways.
There's just the handshake missing, which would be to receive an announce that my extension is alive, ready to receive events and wanting to know the ids, names and timestamp (change date) tuples of all scripts.

**Comment by gera2ld** [comment]
I'm just providing a way to communicate with the database in Violentmonkey. It can be wrapped in any way you like to communicate with an external extension.

I don't have much time investigating communication with other extensions. So I just offer common and low-level APIs to be used by plugins, external extensions, whatever else. For example, the sync-to-cloud feature can be moved to a plugin in the future.

**Comment by gera2ld** [comment]
@brunoais Thanks a lot for your time and interest. 😄

**Comment by brunoais** [comment]
@gera2ld Status update:
I'm having huge headaches with `vue.js` and the dev env. It is costing me a lot of time figuring it out how to make each part work. Do you mind if I just make in plain javascript (without frameworks) and then you give me some help to translate it into how you organized your code?

I'm doing well on my own extension so far. After having the [situation fixed with me](https://github.com/NiklasGollenstede/native-ext/issues/4), I started making tests with it and I'm having good progress.
So far, I already successfully:

1. Communicate with node.js using native-ext (still failing to communicate back, for some reason)
2. Communicate with violentmonkey and get an answer using a promise (still have no code to load any violentmonkey's data)
3. Simple extension id validation. If such id is not known, it responds with a message telling it is denied.

**Comment by brunoais** [comment]
Just a status update.
This is going very slow but not abandoned. Life just came and then holidays came.... I will come back to this next time I'm stable.... hopefully in the weekend next week

**Comment by brunoais** [comment]
Hey. I didn't forget this but my life (almost) went to hell in terms of free time. When can I pick this up again.... I wish I knew... If someone else wants to pick up... feel free to.... My hands are (as figure of speech) tied.....

**Comment by tophf** [comment]
Closing due to the lack of progress. We'll probably just add the new Native File System API.

**Comment by brunoais** [comment]
Ok. Sorry about it. I really got into too much in my hands.
