### ISSUE TITLE
Version 2,9.5 not working

### ISSUE THREAD

**Issue by daveginberry** [violentmonkey/violentmonkey#424]
### What is the problem?
Was updated in the background about Tue 26th Jun 2018 on a Dell Latitude E6430 running Ubuntu 18.04 LTS and Firefox 60.0.2 64 bit.  (this is a relatively new installation of Ubuntu - over 1 week ago with fresh install and all has been working fine including violentnonkey scripts until the auto update)
Noticed when scripts just stopped working.  The dashboard will not open when pressing on the monkey icon on the bar - only this URL is displayed which is an empty page.

moz-extension://f550c409-a23a-40d5-82aa-bb6dbb240b42/options/index.html

The monkey icon says scripts are disabled!  in a greyed out colour and cannot be clicked on.

From the firefox addons page choosing preferences results in the same blank URL.  

What can be done to fix?  Have I lost my scripts?  Is there anyway of reverting?

Help!

**Comment by gera2ld** [comment]
Perhaps your profile data is broken?
This happened to me several times. It seems that data can be broken sometimes after Firefox gets updated. As a result, the extension is unable to load its data and get initialized.
All I could do was to remove the profile data and reinstall everything. That's why I don't use Firefox.

**Comment by gera2ld** [comment]
BTW, Violentmonkey was last updated 21 days before, so it's unlikely a Violentmonkey issue?

**Comment by daveginberry** [comment]
Luckily I had copies of my scripts elsewhere so yes, I ended up removing ViolentMonkey 2.9.5 extension, re-installing it and then copying and pasting each of my scripts.  
Nobody should have to do this - if the act of upgrading the addon is not resilient enough to retain scripts then there is little point in using the addon. :(

**Comment by gera2ld** [comment]
Glad you have your data back.

The update is managed by Firefox. Violentmonkey can do nothing before Firefox provides data to it.

So if the data is broken during update by Firefox, Violentmonkey will not work. It's just an extension which requires the browser (Firefox) to provide everything to it correctly.

FYI, the storage module of Violentmonkey has not been changed for a long time. I have no idea why Firefox breaks it sometimes on update and I don't think there is anything I can do in Violentmonkey.
