### ISSUE TITLE
Experimental Scratchpad API

### ISSUE THREAD

**Issue by KOLANICH** [violentmonkey/violentmonkey#425]
https://github.com/KOLANICH/webext-experiment-scratchpad
I guess the editor they have is much better quality than the one made here. So maybe we should use it instead of what we have.

**Comment by gera2ld** [comment]
It looks great but it's just a tool of Firefox. I don't want this extension to be tied to Firefox. Maybe we can find some way to support it as a plugin.

**Comment by KOLANICH** [comment]
>I don't want this extension to be tied to Firefox.

It is possible to include this API this only to FF version of the addon. Of course it'd require some abstraction layer qnd separation of the code for different browsers into different files.

**Comment by gera2ld** [comment]
I had tried compiling Violentmonkey multiple times for each browser and found it a mess to manage the different versions. I think it's a better idea to maintain one piece of code and get same or slightly different results at runtime.

**Comment by KOLANICH** [comment]
>I had tried compiling Violentmonkey multiple times for each browser and found it a mess to manage the different versions.

Not quite different versions, the same version but with one of 2 modules with the same interface.

IMHO bloating each addon with unworking (at least on Android, on each website using codemirror (including addons) there are huge problems (like disappearing tokens) inputting text using screen keyboards, and sometimes even on desktop, + troubles with copying and pasting) codemirror is not a very good idea. Even though Scratchpad is built upon codemirror itself now.

**Comment by tophf** [comment]
Firefox won't be implementing Scratchpad API, see https://bugzil.la/1472263#c5
IDK if related but the Scratchpad panel was also removed from devtools, see https://bugzil.la/1565380
