### ISSUE TITLE
@match doesn't works when location.hash exists

### ISSUE THREAD

**Issue by maple3142** [violentmonkey/violentmonkey#426]
### What is the problem?
`@match https://example.com/` doesn't works on `https://example.com/#hash`

### How to reproduce it?
1. Use the following script
```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match  https://example.com/
// @grant none
// ==/UserScript==
alert('ok')
```
2. Go to https://example.com/#123
3. Then go to https://example.com/

### What is the expected result?

Both 2 and 3 step show the alert.

### What is the actual result?

Alert won't show in the second step.

### Environment
- Browser: CentBrowser
- Browser version: 3.4.3.39 (Chromium 66.0.3359.181)
- Violentmonkey version: 2.9.5
- OS: win10 x64

**Comment by qrqhuang** [comment]
I got a website all route by hash location.


Ｍy case :  

Define: 
`// @match       http://example.com/`

Id  like to 

match `http://example.com/`  website root home
not match `http://example.com/#hash`

Is there any solution with current version ?

Now I have to  determine from `location.hash`

**Comment by gera2ld** [comment]
You need to handle `hashchange` events and match `location.hash`.

Please open a new issue if you have other questions.
