### ISSUE TITLE
Violentmonkey -> Setting -> Export to zip = not work!

### ISSUE THREAD

**Issue by led9** [violentmonkey/violentmonkey#43]
Error = "The server could not find the file"
download address = 
blob:chrome-extension%3A//jinjaccalgkegednnccohejagnlnfdag/c2fc510e-c63c-4445-8591-925e59ca1b0a

In new Opera on chromium:
http://www.opera.com/blogs/desktop/2016/02/initial-opera-developer-37-release/

**Comment by gera2ld** [comment]
This error seems to occur only in the latest developer version of Opera.

**Comment by svnpenn** [comment]
https://github.com/violentmonkey/violentmonkey/issues/113
