### ISSUE TITLE
Violentmonkey doesn't work on binance.com with Firefox

### ISSUE THREAD

**Issue by realuser** [violentmonkey/violentmonkey#436]
### What is the problem?

Minimal violentmonkey script doesn't work on binance.com Is it related to CSP (Content Security Policy)? 

Binance has this header:
content-security-policy: block-all-mixed-content; scrip…ct-src 'none'; base-uri 'self'

Exact same violentmonkey script works on chrome.

### How to reproduce it?
1.  Add the following script to violentmonkey:

```
// ==UserScript==
// @name Binance Test
// @namespace Violentmonkey Scripts
// @match https://www.binance.com/*
// require https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
// @grant none
// ==/UserScript==

console.log("hello world");

```

2. Visit https://www.binance.com

### What is the expected result?
Console displays
`hello world`

### What is the actual result?

Console does not display `hello world`.
Also console displays the following (not sure if related):
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: !function e(a){var b=document.querySelec....

### Environment
- Browser: Firefox
- Browser version:  61.0.2 (64-bit)
- Violentmonkey version: v2.9.5
- OS: Windows 10 Pro 64-bit (Version 1803 [10.0.17134.191])

**Comment by T1mL3arn** [comment]
Looks like #408.
