### ISSUE TITLE
GM_setValue sometimes failed

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#437]
**Reproduce**

1. Install the test script given below;
2. Navigate to https://www.example.com/
3. Hit "Write" Button, and wait it finish;
4. Hit "Read" Button, and wait it finish;
    * You may got "Reading value502 failed, got (void 0)";
    * If it finished successfully, continue the following steps;
5. Hit "Delete" Button, and wait it finish;
6. Try again from step 3.

**Expected**

The test should pass

**Actural**
It failed sometimes

**Environment**
Firefox 61.0.2 + VM 2.9.5
Chrome 68.0.3440.106 + VM 2.9.5

Test script:

```javascript
// ==UserScript==
// @name      Test GM_*value
// @namespace https://github.com/tiansh
// @match     *://*.example.com/*
// @grant     GM_getValue
// @grant     GM_setValue
// @grant     GM_deleteValue
// ==/UserScript==

const body = document.body;
body.innerHTML = `
<div>
  <input type="number" id="size" name="size" />
  <button id="write">Write</button>
  <button id="read">Read</button>
  <button id="delete">Delete</button>
  <button id="clear" style="float: right">Clear Output</button>
  <ol id="result"></ol>
</div>
`;
const writeButton = document.getElementById('write');
const readButton = document.getElementById('read');
const deleteButton = document.getElementById('delete');
const clearButton = document.getElementById('clear');
const result = document.getElementById('result');

let testSize = 2000;
const testSizeInput = document.getElementById('size');
testSizeInput.value = testSize;
testSizeInput.addEventListener('input', () => { testSize = +testSizeInput.value });

const output = function (text) {
  text.split('\n').map(line => {
    const container = document.createElement('li');
    container.textContent = line;
    result.appendChild(container);
  });
};
const clearOutput = function () {
  result.innerHTML = '';
};


const runTest = function (test) {
  const tests = Array(testSize).fill(0).map((_, i) => i);
  const run = tests.map(i => Promise.resolve().then(test(i)));
  return Promise.all(run);
};

const runWrite = function () {
  return runTest(i => GM_setValue('value' + i, i))
    .then(() => output('Write Finished successfully'), e => output(`Test failed: ${e}`));
};

const runRead = function () {
  return runTest(i => {
    const value = GM_getValue('value' + i);
    if (value === i) return;
    const strValue = value === (void 0) ? '(void 0)' : JSON.stringify(strValue);
    output(`Reading value${i} failed, got ${strValue}`);
  }).then(() => output('Read Finished successfully'), e => output(`Test failed: ${e}`));
};

const runDelete = function () {
  return runTest(i => GM_deleteValue('value' + i))
    .then(() => output('Delete Finished successfully'), e => output(`Test failed: ${e}`));
};

const withDelay = function () {
  output('pause...');
  return new Promise(resolve => setTimeout(resolve, 100));
};

writeButton.addEventListener('click', function () { runWrite(); });
readButton.addEventListener('click', function () { runRead(); });
deleteButton.addEventListener('click', function () { runDelete(); }); 
clearButton.addEventListener('click', function () { clearOutput(); });
```

<img width="607" alt="Screen shot of errors" src="https://user-images.githubusercontent.com/6500326/44706701-d4400c00-aae5-11e8-86d2-e39d87a28c96.png">

----

My script sometime failed to write configures. And I found out that disable and re-enable VM could make everything work again. I had tried to reduce my use case. But I'm not sure if this bug is actually what I meet on my script...

**Comment by gera2ld** [comment]
I can only reproduce it by clicking *read* right after *write finished*.
Actually the data is updated asynchronously, so it might take some time (~ms) for the new data to be ready. Is that your case?

**Comment by tiansh** [comment]
Aha, I had a double check after reading your post. You are right. It's not what I want to reproduce. I don't know. I will try to reproduce it later if I was in the same trouble next time...

My issue is the [timer](https://github.com/violentmonkey/violentmonkey/blob/9e672d5590aea144840681b6f2ce0c267d57fc13/src/background/utils/values.js#L59) is always truthy, and the [Promise chain](https://github.com/violentmonkey/violentmonkey/blob/9e672d5590aea144840681b6f2ce0c267d57fc13/src/background/utils/values.js#L85) seems failed somehow and never cleared the timer. I had saw this some times. But not very easy to reproduce.

**Comment by tophf** [comment]
Violentmonkey uses synchronous access to value storage so the data is **always** ready. That leaves the only option: the userscript is wrong. And indeed it is:

```js
tests.map(i => Promise.resolve().then(test(i)));
```

This makes no technical sense. If you wanted to postpone execution of `test` function you would need this:

```js
tests.map(i => Promise.resolve().then(() => test(i)));
```
