### ISSUE TITLE
Can only have one custom script

### ISSUE THREAD

**Issue by crdeutsch** [violentmonkey/violentmonkey#44]
Adding my own script using the "New" button works fine.

When I try add a second one using "New" the other script I had is deleted (or over written)

![image](https://cloud.githubusercontent.com/assets/404765/13204952/b1de17d8-d8a1-11e5-8009-eb3f7b596620.png)

**Comment by gera2ld** [comment]
Do they have different `@name`s?
Scripts with same `@namespace`s and `@name`s will be regarded as the same.

**Comment by crdeutsch** [comment]
Ah! You're correct. They had the same name and namespace.

I was changing the name here instead:
![image](https://cloud.githubusercontent.com/assets/404765/13222421/7230990e-d945-11e5-82d2-eee3163a9ef8.png)
