### ISSUE TITLE
Question mark in match pattern and version 2.9.6

### ISSUE THREAD

**Issue by sheddup** [violentmonkey/violentmonkey#442]
### What is the problem?
After upgrading to 2.9.6 I noticed one of my userscripts that utilizes this match pattern `// @match https://www.youtube.com/results?*` no longer runs, if I remove the question mark from the match pattern `// @match https://www.youtube.com/results*` and refresh the page my userscript is now running.  
Just curious is this desired behavior in 2.9.6 or a bug?
### How to reproduce it?
1.
2.
3.

### What is the expected result?
userscript running on pages matching`https://www.youtube.com/results?*`
### What is the actual result?
userscript doesn't run on pages matching `https://www.youtube.com/results?*`
### Environment
- Browser: Waterfox
- Browser version: 56.2.2
- Violentmonkey version: 2.9.6
- OS:Win10

**Comment by gera2ld** [comment]
According to the document [here](https://developer.chrome.com/extensions/match_patterns), match rules only works on the protocol/scheme, host, and pathname of a URL. So it was a bug and now fixed.
See also #426 .
