### ISSUE TITLE
Option to allow '@match'-ing query or hash

### ISSUE THREAD

**Issue by Sajito** [violentmonkey/violentmonkey#443]
### What is the problem?
Problem is related to #426 and the corresponding fix a342714815c8dbf5fa20f475b333055d50515219.
It's now impossible to match agains query or hash params, which is quite inconvenient on pages which define the current view by hash or query params.
An option to enable matching for those params would be nice. Alternatively check `@match` URL for query params or hash params and match for those, if they are present.

### How to reproduce it?
Same steps as in #426 

### What is the expected result?
1. 
```
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match  https://example.com/#page=2
// @grant none
// ==/UserScript==
alert('ok')
```

2. Go to `https://example.com/#page=2`
3. Script won't load at all

### What is the actual result?
1. Script should match that page

### Environment
- Browser: Firefox
- Browser version: 62.0
- Violentmonkey version: 2.9.6
- OS: Windows 10 1803

**Comment by gera2ld** [comment]
How about this way?
If either `?` or `#` appears, the rule should match query or hash, otherwise it matches only the scheme, host and pathname.

**Comment by Sajito** [comment]
I think that's the most convenient solution to this request
