### ISSUE TITLE
exclude/include in the other way

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#447]
is possible, for one script, to exclude all the sites (in general) and specify the only site to enable that script?

**Comment by gera2ld** [comment]
![image](https://user-images.githubusercontent.com/3139113/45354501-56edbe80-b5f0-11e8-9cd8-1331cf6dc170.png)

Open script editor, switch to "Settings" tab:
1. Uncheck "Keep original"s
2. Add your own `@include` or `@match` rules.
