### ISSUE TITLE
Possible regression with 2.9.6?

### ISSUE THREAD

**Issue by ImSpecial** [violentmonkey/violentmonkey#448]
### What is the problem?
First off, this might not be a ViolentMonkey issue, it might be a Steam/outdated script problem, in that case disregard. Anyways, the problem is that I use this simple [Script to Bypass Steams Age Verification](https://greasyfork.org/en/scripts/1519-automatically-bypass-steam-age-verification/code) that pops up on a lot of Steam pages, it has always worked until recently and the only thing I noticed was ViolentMonkey had updated to 2.9.6.
### How to reproduce it?
1. Go to a "Mature" game page like [This One.](https://store.steampowered.com/agecheck/app/287700/)
2. Should auto submit, but doesn't.

### What is the expected result?
Sets your birthday to 1950 and submits the form.
### What is the actual result?
Sets your birthday to 1950 and **does not** submits the form.
### Environment
- Browser: Firefox
- Browser version: 62.0
- Violentmonkey version: 2.9.6
- OS: Windows 10 64-bit 1803 17134.254

**Comment by chylex** [comment]
Steam recently changed their age verification page, the script needs to be updated; nothing to do with Violentmonkey.

**Comment by ImSpecial** [comment]
I see, thanks for looking into it and confirming. I'll have to look into finding a new script then, or figure out how to fix the current one.
