### ISSUE TITLE
matrix 

### ISSUE THREAD

**Issue by bollingered** [violentmonkey/violentmonkey#45]
Do you have a comparison table of ViolentMonkey  vs TamperMonkey on chromium?

**Comment by gera2ld** [comment]
Sorry no. Violentmonkey is just designed to run scripts and check for updates, maybe not so powerful as TamperMonkey.

**Comment by jesus2099** [comment]
@bollingered if you have a list of Tampermonkey features that are important for you, I am a Violentmonkey user, I can tell you if I have them.
