### ISSUE TITLE
Support responseType='arrayBuffer'?

### ISSUE THREAD

**Issue by maple3142** [violentmonkey/violentmonkey#457]
### What is the problem?

`GM_xmlhttpRequest` doesn't support `responseType='arrayBuffer``

### How to reproduce it?
1. Install the following script and navigate to any page.
2. Open console.

script:
```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match *://*/*
// @grant GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: 'GET',
  url: 'https://example.com/',
  responseType: 'arrayBuffer',
  onload: xhr=>console.log(xhr.response),
  onerror: console.error
})
```

### What is the expected result?

An `ArrayBuffer` object.

### What is the actual result?

A string.

### Environment
- Browser: Chrome
- Browser version: 69.0.3497.100
- Violentmonkey version: v2.9.7
- OS: Windows 10 x64

**Comment by gera2ld** [comment]
Try `arraybuffer` instead of `arrayBuffer`.
