### ISSUE TITLE
do not support @match http*:// ?

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#458]
TM supports `// @match   http*://*`
VM not.
Why?

**Comment by gwarser** [comment]
Invalid sheme? 

https://developer.chrome.com/extensions/match_patterns

    <scheme> := '*' | 'http' | 'https' | 'file' | 'ftp'

**Comment by gera2ld** [comment]
This is not supported.
BTW, `@match *://*` is actually the same as `@match http*://*` since `*` as scheme matches either `http` or `https`.

**Comment by ivysrono** [comment]
@gera2Id 我知道他们是一样的，问题是不少现有脚本写的http＊，于是就又是tm兼容性好的例证了。
