### ISSUE TITLE
Bad markup for `msgNewVersion` message

### ISSUE THREAD

**Issue by T1mL3arn** [violentmonkey/violentmonkey#461]
### What is the problem?

![vm bad markup screen](https://user-images.githubusercontent.com/9349164/46931125-17057580-d08d-11e8-8850-a4c1e99f6bad.jpg)

### How to reproduce it?

1. Create a script and publish it somewhere.
2. Script must be with `@updateURL` meta
3. Create a new script in VM and paste code from the first script to new.
4. Save and close.
at this time we have a script with no `@downloadURL` meta but with  `@updateURL`.
5. Rise version of the first script and click "check update" icon.  

### What is the expected result?

Message with no `<span>` tags.

### What is the actual result?

See screenshot above.

Looks like the problem is [there](https://github.com/violentmonkey/violentmonkey/blob/9e672d5590aea144840681b6f2ce0c267d57fc13/src/background/utils/update.js#L44).

### Environment

- Violentmonkey version: 2.9.7

**Comment by gera2ld** [comment]
fixed via #462
