### ISSUE TITLE
ublock origin is preventing violentmonky from injecting scripts

### ISSUE THREAD

**Issue by moham96** [violentmonkey/violentmonkey#464]
### What is the problem?
violentmonkey and ublock origin are in conflict in some sites, for example
http://xxxwebdlxxx.org/img-5b392d724b75f.html (NSFW)

### How to reproduce it?
1. install [ublock origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) ,update the filters and enable them
2.install a userscript inside violentmonkey,for example https://gist.github.com/gera2ld/1c14672b77ade31ad8f0984725de18fc
3.add this match to the userscript:
`// @match http://xxxwebdlxxx.org/*`
4. now head over to the url http://xxxwebdlxxx.org/img-5b392d724b75f.html
you'll see that ublock origin has blocked all the scripts on the page including the scripts injected by violentmonkey,so no userscript is running

### What is the expected result?
I'm not sure what to expect, shouldn't the injected script be running regradless of the ad blocking ? or is this an expected behavior ?how can I solve or workaround this ? should this be reported to the ublock origin guys instead ?
### What is the actual result?
userscripts not running
### Environment
- Browser: firefox
- Browser version:62.0.3
- Violentmonkey version:2.9.7
- OS:manjaro linux

**Comment by gwarser** [comment]
CSP. https://github.com/violentmonkey/violentmonkey/issues/408
uBO inserts `||xxxwebdlxxx.org^$csp=script-src 'self' data:`

**Comment by moham96** [comment]
@gwarser I missed that duplicate, thanks
