### ISSUE TITLE
Script execution disabled, stuck at Installed Scripts tab

### ISSUE THREAD

**Issue by mefromac** [violentmonkey/violentmonkey#467]
### What is the problem?
Scripts don't execute anymore, the Installed Scripts tab just shows "Loading"

### How to reproduce it?
1. Click Violentmonkey icon -> says "Scripts disabled" (greyed out, not clickable)
2. Got to "Open Dashboard" -> see only "Loading..."
3. Try adding scripts, in my case https://github.com/mefromac/duolingo-skill-strength/blob/master/skill-strength.user.js , which should have been already present -> No change

### What is the expected result?
- Scripts executing ...
- Scripts tab showing my installed scripts

### What is the actual result?
- no execution
- no scripts shown, window keeps saying "Loading..." 

### Environment
- Browser: Firefox
- Browser version: 62.0.3 (64-bit)
- Violentmonkey version: v2.9.8
- OS: Linux Mint 18 Cinnamon

**Comment by dameon6** [comment]
Same issue here.  Installed Scripts are now missing, scripts were fully functional and available last night. Cannot install any scripts.

**Environment**

- Browser: Firefox
- Browser Version: 64.0b3 (64-bit)
- Violentmonkey version: v2.9.8 (reports as v2.9.8, firefox reports as 2.9.9 on app site)
- OS: Windows 10

**Comment by gwarser** [comment]
https://github.com/violentmonkey/violentmonkey/issues/466

**Comment by mefromac** [comment]
Ok, thanks. Didn't see the other (closed) issue and for some reason the automatic update didn't work. De- and re-installing brought me to v2.9.9, which works again.
