### ISSUE TITLE
"Track local file before this window is closed" doesn't work in Firefox

### ISSUE THREAD

**Issue by pmorch** [violentmonkey/violentmonkey#469]
### What is the problem?

I cannot get violentmonkey to update the script "automatically" before the window is closed [as advertised](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script).

### How to reproduce it?

1. Install violentmonkey
2. Serve a local directory with [npm install http-server](https://github.com/indexzero/http-server#readme)'s `http-server -c-1`. (The -c-1 sends a header: `cache-control: max-age=-1` to ensure that Firefox caching is disabled.)
3. Violentmonkey->new->Install from URL->enter URL
4. Ensure that options->"Track local file before this window is closed" is checked.
5. Click "Confirm Installation"
6. Leave window open

I used npm http-server that lets me control the caching. [How to edit scripts with your favorite editor? - Violentmonkey](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/) suggests using `python3 -m http.server` which I tried also with the same result.

### What is the expected result?

I expect that violentmonkey periodically will re-query the URL and update the script while the  window with the script in it is open.

### What is the actual result?

Both wireshark and the console report that URL is never queried again. Hence the script is never updated.

### Environment
- Browser: Firefox 
- Browser version: 63.0 in a brand new profile
- Violentmonkey version: v2.9.9
- OS: Ubuntu 18.04

### The HTTP packets

Request:
```
GET /greasemonkey_gm_scripts/Modify_Jira_page_title/Modify_Jira_page_title.user.js HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
If-Modified-Since: Mon, 29 Oct 2018 15:51:16 GMT
If-None-Match: W/"3412012-841-2018-10-29T15:51:16.992Z"
```
Response:

```
HTTP/1.1 200 OK
server: ecstatic-3.3.0
cache-control: max-age=-1
last-modified: Mon, 29 Oct 2018 16:23:45 GMT
etag: W/"3412012-836-2018-10-29T16:23:45.287Z"
content-length: 836
content-type: application/javascript; charset=UTF-8
Date: Mon, 29 Oct 2018 16:24:00 GMT
Connection: keep-alive

// ==UserScript==
// @name        Modify Jira page <title>
// @namespace   http://www.morch.com
// @include     https://capmon.atlassian.net/*
// @version     1
// @grant       none
// ==/UserScript==

// The purpose of this script is to turn:
// [CM-1862] Some title. - Capmon JIRA
// into
// CM-1862: Some title.

function modifyTitle() {
    var titleElem=document.getElementsByTagName('title')[0]
    var title=titleElem.innerHTML;
    var matches;
    if (matches=title.match(/\[(.*?)\] (.*) - Capmon JIRA/)) {
        var bugID=matches[1];
        var bugText=matches[2];
        var newTitle=bugID + ": " + bugText;
        if (matches=window.location.href.match(/\?jql=/)) {
            newTitle = 'Issue List: ' + newTitle;
        }
        titleElem.innerHTML=newTitle;
    }
}
modifyTitle();
setInterval(modifyTitle, 2000);
```

**Comment by gera2ld** [comment]
Try using `localhost` as hostname. I'll update the rule to check whether a script is from local server.

**Comment by pmorch** [comment]
Thanks! That worked.

I just noticed that [Make sure the hostname is localhost and the script name ends with .user.js.](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script) actually explicitly says:
> Make sure the hostname is localhost and the script name ends with .user.js.

So: my bad.

**Comment by Bumbadawg** [comment]
@pmorch Hi, it seems this issue is back. 
FF67, Linux.
The script ends in .user.js. Server is running with cache disabled.
I tried to register the script via localhost and file:/// protocols. 

Both had "Track local file before this window is closed" greyed out.

**Comment by pmorch** [comment]
@Bumbadawg: I don't think you'll get violentmonkey under firefox to work with file:/// protocol. See https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#known-issues

**Comment by Bumbadawg** [comment]
Indeed @pmorch cheers, i read that one and your comments above. Lil or no hope for file protocol. Mentionning also the localhost:80 issue, i can open it but "_Track local file before this window is closed_" is greyed out.
