### ISSUE TITLE
Change the text "✖ Scripts enabled" to "✖ Scripts disabled" when scripts disabled

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#47]
Change the text, and also keep the cross mark:
->
✔ Scripts enabled
✖ Scripts disabled

----

前两天收到用户反馈“用的是opera，摁启用了也用不了[泪]第一次的时候有用，忽然就用不了了”，
问了半天怎么配置的，最后……
[![a6a7dc31gw1f278z4ygs4j20bq052dgf 1](https://cloud.githubusercontent.com/assets/6500326/14058900/ec35c10a-f382-11e5-9425-8745af6120ec.jpg)](http://ww3.sinaimg.cn/large/a6a7dc31gw1f278z4ygs4j20bq052dgf.jpg)
而且后来还有一个情况一样的……
所以建议可以改一下这东西的描述……
比如 “脚本已启用” / ”脚本已禁用”

**Comment by gera2ld** [comment]
哈哈，这个可以有
