### ISSUE TITLE
save/close buttons not working when trying to save a new script

### ISSUE THREAD

**Issue by Roko131** [violentmonkey/violentmonkey#470]
### What is the problem?
Can't save new script
### How to reproduce it?
1. open dashboard
2. go to installed scripts
3. click the + sign & New for adding new script
4. write something in script text editor
5. try to save or close - none of the buttons work

### What is the expected result?
Save button should save script
Close button should close screen
Close & Save button should close and save
### What is the actual result?
Nothing happens- can't leave screen, none of the right top buttons work: save | save & close | close
### Environment
- Browser: Firefox
- Browser version: 63 64bit
- Violentmonkey version: v2.9.9
- OS: Ubuntu 18:04 (but it also happens in my windows 10 machine)

### More Info
It was working fine yesterday- I guess the new commit broke something?
It (buttons not working) only happen when trying to add a new script
Buttons do work when editing an existing script

![image](https://user-images.githubusercontent.com/3532929/47781235-e6b50c80-dd05-11e8-83f4-c2cca6adc1e0.png)

**Comment by gera2ld** [comment]
There should be a modal to be confirmed but it's behind the editor window due to incorrect `z-index`.
As a workaround, you may try changing a new `@name`.
