### ISSUE TITLE
GM_registerMenuCommand execute duplicate handler

### ISSUE THREAD

**Issue by hoang-rio** [violentmonkey/violentmonkey#478]
### What is the problem?
Handler function of `GM_registerMenuCommand` execute many time if page has iframe
### How to reproduce it?
1. Create a script execute in all page and iframe
2. Register a hadler with `GM_registerMenuCommand` with `GM_openInTab`
3. Open a page have iframe
4. Click script menu and click registed menu

### What is the expected result?
Open mutiple tab with single click. Number of open tab equal with number of iframe in page + 1
### What is the actual result?
Open only one tab
### Environment
- Browser: Chrome
- Browser version: Lastest
- Violentmonkey version: 2.9.10
- OS: Windows 10

**Comment by gera2ld** [comment]
This is a feature that allows you to register menu commands from iframes.

You may either use [`@noframes`](https://violentmonkey.github.io/api/metadata-block/#noframes) to inject the script only into the top level page or check before calling `GM_registerMenuCommand` by yourself.
