### ISSUE TITLE
Support Tampermonkey's GM_addValueChangeListener api

### ISSUE THREAD

**Issue by larubbio** [violentmonkey/violentmonkey#483]
### What is the problem?

Scripts that are currently running in Tampermonkey have access to an api [GM_addValueChangeListener](https://tampermonkey.net/documentation.php#GM_addValueChangeListener) that enables a script executing in one tab to be notified when a script in another tab changes a value.  Adding support fir this API and [GM_removeValueChangeListener](https://tampermonkey.net/documentation.php#GM_removeValueChangeListener) will enable some scripts that can only run in TamperMonkey to also run in ViolentMonkey.

**Comment by tophf** [comment]
I want to implement this.
I guess I'll peek inside TM to ensure a compatible implementation.
