### ISSUE TITLE
GM_xmlhttpRequest vs fetch

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#484]
I was in situation when **GM_xmlhttpRequest** does not work because of blocking request. In the same case built-in **fetch** does work. Why is that?

Why cross-domain **GM_xmlhttpRequest** does not work in all cases, but **fetch** does?

Does **GM_xmlhttpRequest** have any advantages over **fetch** or everything that can be done with **GM_xmlhttpRequest** can also be done with **fetch** as well? And therefore there is no need in **GM_xmlhttpRequest**?

**Comment by gera2ld** [comment]
Please provide a minimal reproduction.

**Comment by soviet-man** [comment]
Here is detailed example
```
// ==UserScript==
// @name       test5
// @namespace  test
// @include    https://www.reddit.com/r/cars
// @grant      GM_xmlhttpRequest
// ==/UserScript==

// this function will return title of web page
function get_title( text ) {
   let parser = new DOMParser()
   let doc = parser.parseFromString( text, 'text/html' )
   return doc.title
}

// Now, I am at https://www.reddit.com/r/cars
// I request data from page on the same origin -- https://www.reddit.com/r/cars/comments/a4usor/weekly_what_car_should_i_buy_megathread/
let url = 'https://www.reddit.com/r/cars/comments/a4usor/weekly_what_car_should_i_buy_megathread/'

//----------
// GM_xmlhttpRequest example
GM_xmlhttpRequest( {
   'method' : 'GET',
   'url' : url,
   onload  : response => {
      console.info( 'GM_xmlhttpRequest - good' )
      console.info( 'title -', get_title( response.responseText ) )
   },
   onerror : response => {
      console.error( 'GM_xmlhttpRequest - bad' )
   },
} )

//----------
// fetch exmaple
fetch( url )
.then( response => response.text() )
.then( text => {
   console.info( 'fetch - good' )
   console.info( 'title -', get_title( text ) )
} )
.catch( err => {
   console.error( 'fetch - bad' )
} )

```

**Comment by soviet-man** [comment]
I typed everything to reproduce the problem. The script is very simple. I don't understand what do you mean. And it does not work for me (only **fetch** works)

**Comment by soviet-man** [comment]
And again example when `GM_xmlhttpRequest` does not work, but `fetch` does

```
// ==UserScript==
// @name       test4
// @namespace  Violentmonkey Scripts
// @include    *
// @grant      GM_xmlhttpRequest
// ==/UserScript==

let url = 'https://news.mail.ru'

GM_xmlhttpRequest( {
   'method' : 'GET',
   'url' : url,
   onload  : response => {
      let parser = new DOMParser()
      let doc = parser.parseFromString( text, 'text/html' )
      console.info( 'title =', doc.title )
   },
   onerror : response => console.error( response ),
} )

fetch( url )
.then( response => response.text() )
.then( text => {
   let parser = new DOMParser()
   let doc = parser.parseFromString( text, 'text/html' )
   console.info( 'title =', doc.title )
} )
.catch( err => console.error( err ) )
```

**Comment by gwarser** [comment]
Firefox content blocking?

>The resource at “https://www.reddit.com/r/cars/comments/a4usor/weekly_what_car_should_i_buy_megathread/” was blocked because content blocking is enabled.


This required additional slash on the end 

>// @include    https://www.reddit.com/r/cars


>Being in twitter.com

Does not work at all (CSP? Requires inject-into?)

**Comment by gera2ld** [comment]
Can you debug the extension and see if there are errors in the console of the background?
1. Type `about:debugging` in the address bar.
1. Click *Debug* in the panel of Violentmonkey.
1. Execute your script and see if there are errors.

**Comment by gera2ld** [comment]
According to [the document of content blocking](https://support.mozilla.org/en-US/kb/content-blocking), Firefox v63+ can block third-party tracking cookies with content blocking turned on.
As a result, all requests with third-party cookies are blocked, including those started by `GM_xmlhttpRequest`.
By default, `fetch` will not send cookies, unless the `credentials` option is set properly. (See [here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) for more details.) I think that's exactly why they behave differently.

**Comment by gera2ld** [comment]
Just added anonymous mode for GM_xmlhttpRequest, you can use it in the next version to avoid sending cookies:
```js
GM_xmlhttpRequest({
  anonymous: true,
  // ...
});
```

**Comment by soviet-man** [comment]
It did not help with `anonymous: true
`
![default](https://user-images.githubusercontent.com/33825590/50546496-89700580-0c39-11e9-9c09-ee5997b6488a.png)
