### ISSUE TITLE
[2.10.0, FF 64.0] Violentmonkey rarely will not inject scripts

### ISSUE THREAD

**Issue by Tharn** [violentmonkey/violentmonkey#485]
### What is the problem?
Rarely, when opening a Youtube page with Iridium loaded (https://github.com/ParticleCore/Iridium), none of the controls / script bits will be injected into the video page. Violentmonkey icon still shows in the address bar, and scripts still show as loaded in the popup.

When this happens, reloading or closing and re-opening the page will not fix it. The only fix is to restart the browser.

### How to reproduce it?
It happens erratically. I have not been able to reproduce it. Basically one would have to use Violentmonkey over a period of weeks to run into this issue once or twice.

I can say for sure that this is not a 2.10 issue, but that it happened before in 2.9.6. or so.

### Environment
- Browser: Firefox x64 no-EME
- Browser version: 64.0
- Violentmonkey version: 2.10.0
- OS: Windows x64 8.1

**Comment by tophf** [comment]
See if it's fixed in the current VM.
Anyway, without a definitive steps-to-reproduce sequence this is not actionable.
