### ISSUE TITLE
Injects even with no scripts to run, causing Firefox CSP errors (regression from 2.9.10)

### ISSUE THREAD

**Issue by andersk** [violentmonkey/violentmonkey#486]
### What is the problem?
In 2.8.17 I fixed Violentmonkey to skip injecting the loader when there are no scripts to run on the current page (#256). But in 2.10.0, Violentmonkey has regressed to always injecting the loader again.

This causes CSP errors in Firefox (yes, still) and is generally an unfriendly thing to do whether it causes visible errors or not.

### How to reproduce it?
Visit github.com in Firefox and check the console.

### What is the expected result?
Violentmonkey should know there are no scripts to run and skip injecting the loader.

### What is the actual result?
Violentmonkey injects the loader anyway, causing a CSP error.

### Environment
- Browser: Firefox
- Browser version: 64
- Violentmonkey version: 2.10.0
- OS: Ubuntu 18.10

**Comment by andersk** [comment]
This regressed again between 2.12.4 and 2.12.5. Can you reopen this?

**Comment by tophf** [comment]
It didn't really regress. Violentmonkey 2.12.5 and newer injects the loader before the page scripts can run in order 1) to prevent pages from hacking into VM's internal message listener and abusing all the power of the extension by intercepting the moment the sandbox script element is created, and 2) to save the native JS globals that some pages override and thus break our functionality or may use to hack into VM and abuse its power.

There's a PR #850 to remedy this exact problem but then I decided it's not worth the added complexity. I could reconsider this of course or implement an alternative workaround to patch the CSP of the page like Tampermonkey can do, but the real solution to this problem - assuming Mozilla doesn't want to exempt extensions from page CSP like Chrome does - is to use browser.userScripts API (#604).

**Comment by tophf** [comment]
FWIW, in the new [beta 2.13.0.12](https://github.com/violentmonkey/violentmonkey/releases) it's possible to enable `Synchronous` injection mode, which will intelligently use `content` mode on CSP-protected pages and won't inject anything if there are no scripts for the current page.

**Comment by tophf** [comment]
The new [beta 2.13.0.15](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.15) injects the sandbox only when there's a matching script that runs in page mode.
