### ISSUE TITLE
Make VM highlight search field when nothing is found

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#488]
Now, search field is not highlighted at all whether something is found or not

![default](https://user-images.githubusercontent.com/33825590/50263050-05da3b80-0425-11e9-8a9e-c51f6bb78d04.png)

It would be great if search field is highlighted (with pink color) if nothing is found, like in any text editor or Firefox

![default](https://user-images.githubusercontent.com/33825590/50263152-7f722980-0425-11e9-8c91-667980d7b98e.png)

**Comment by soviet-man** [comment]
Only thin border becomes red when nothing is found. It is almost unnoticeable.

![изображение](https://user-images.githubusercontent.com/33825590/54105463-2e4e5200-43e4-11e9-9194-cb987839a739.png)

I hoped background color becomes pink in this case.

**Comment by gera2ld** [comment]
> And it would be great if there will be space between field's caption and field itself.

Totally agree.

How about this?

![image](https://user-images.githubusercontent.com/3139113/54115504-865a7800-4427-11e9-83f8-661a9d6aa9b7.png)

**Comment by soviet-man** [comment]
Yes. That is better.

**Comment by soviet-man** [comment]
Why VM does not highlight search field if nothing is found? It used to highlight it.

**Comment by tophf** [comment]
I've missed that CSS when switching input types to enable autocomplete.

**Comment by tophf** [comment]
Until the fixed version is released you can add the following code in Violentmonkey settings -> Advanced -> Custom style:

```css
.editor-search .is-error {
  border-color: #e85600;
  background: #e8560010;
}
```

**Comment by soviet-man** [comment]
It would be better to used monospaced font in search field. This is code editor and programmers search for code.

**Comment by tophf** [comment]
Maybe but all(?) popular IDEs use a standard font (not monospace) in that input by default.

**Comment by soviet-man** [comment]
No. This is Geany, popular text editor for programming
![изображение](https://user-images.githubusercontent.com/33825590/71475946-baa2f780-27f3-11ea-9952-7c36b02be90f.png)

**Comment by tophf** [comment]
Okay, some obscure editors use a monospace font.

**Comment by soviet-man** [comment]
You, guys, allow to type not only plain text in that field, but also regular expression. Do you really want people to enter regexp not being monospaced?

**Comment by tophf** [comment]
I just want the UI to be standard and all major IDE/editors use a standard font there. You can easily change the font with the following CSS:

```css
.editor-search input {
  font-family: monospace;
}
```

**Comment by soviet-man** [comment]
Thanks you
