### ISSUE TITLE
simple script works in TM but not VM

### ISSUE THREAD

**Issue by k1nghat** [violentmonkey/violentmonkey#489]
### What is the problem?
script doesnt work on any page but works on TM. i cant even get the extension icon to show that there is a script working on the page.
https://paste.debian.net/hidden/3220567e/
### How to reproduce it?
1. load script from local file.
2. go to any page and notice no console action.
3. works in TM

### What is the expected result?
console readout of `document.title`
### What is the actual result?
empty console
### Environment
- Browser: chrome
- Browser version: 71 stable
- Violentmonkey version: v2.10.0
- OS: linux (KDE Neon)

**Comment by Herohtar** [comment]
I'm not sure of the exact reason, but the problem is your `@match` lines. If you add slashes to the end (turning them into `https://*/` and `http://*/`) then it should work.

**Comment by k1nghat** [comment]
> The problem is your `@match` lines. If you want to match all pages, you should write a single match line like so: `@match *://*/*` or `@match <all_urls>`
> 
> See https://violentmonkey.github.io/api/matching/, and more specifically https://developer.chrome.com/extensions/match_patterns

tyvm @Herohtar! im making progress but im not seeing the output in console correctly: 

![image](https://user-images.githubusercontent.com/16073360/50311945-7bb5c580-046c-11e9-8600-29d1a8e07e13.png)


![image](https://user-images.githubusercontent.com/16073360/50311896-5b860680-046c-11e9-8a33-bb446afb374e.png)

**Comment by gera2ld** [comment]
There is something wrong with `document.title` of https://violentmonkey.github.io/ . The title is empty when the script executes. So your script actually worked.
