### ISSUE TITLE
Disable Automatically check scripts for updates every day

### ISSUE THREAD

**Issue by kevinsimper** [violentmonkey/violentmonkey#492]
The feature "Automatically check scripts for updates every day" is activated by default and it is a feature that has some privacy concerns.

Should this be disabled by default? 

Both the website owner and everyone on the network would know you are using a particular/any greasemonkey script and could use it to pinpoint you.

**Comment by gera2ld** [comment]
This is an interesting and good point I'd never thought of. Thanks for point it out.
I think we should let the user choose whether to update it automatically on installation.

**Comment by tophf** [comment]
Closing in favor of #577.

**Comment by AlexByte** [comment]
How will they know?
> Both the website owner and everyone on the network would know you are using a particular/any greasemonkey script and could use it to pinpoint you.
