### ISSUE TITLE
Add links to documentation

### ISSUE THREAD

**Issue by kevinsimper** [violentmonkey/violentmonkey#493]
It could be nice for beginners to userscripts to link to the documentation from the script editor and maybe also a getting started guide 👍 

It is nice that you can click "Create a script" super easily 👍

**Comment by tophf** [comment]
I only see similar approach in consumer-level apps that are aimed specifically at total newbies. Writing code, on the other hand, requires skill. To obtain that skill everyone chooses their own path. There are thousands of methods to learn programming in general and lots of tutorials/ways for userscript-specific info. If someone is capable to learn programming then certainly they'll be able to type a few keywords in their preferred search engine or ask a friend, etc. I don't see the benefit of adding a couple of links that would only work for English-speaking learners, nor would I want to see a long list of multi-language resources/tutorials that someone would have to curate and update. Moreover Violentmonkey's primary purpose is to just run the scripts, not to be a newbie-friendly IDE or a guide into the world of userscripts.

What we can certainly do is to add a link to https://violentmonkey.github.io/api/ for example inside the `?` sub-tab inside the editor.
