### ISSUE TITLE
There is a thief who stole your extension!

### ISSUE THREAD

**Issue by AnnAngela** [violentmonkey/violentmonkey#495]
Chrome Extension Store: https://chrome.google.com/webstore/detail/ace-script/mjbepbhonbojpoaenhckjocchgfiaofo
Github: https://github.com/acestream/webextension
This thief copyed your extension and only modified the logo to deceive users to think that is your extension, and added a advertisement popup to annoy user. I had been deceived for a while.
Please take a look at it!

**Comment by gera2ld** [comment]
This project is licensed under MIT, so... maybe... let it go? 😃
