### ISSUE TITLE
tvtropes breaks violentmonkey

### ISSUE THREAD

**Issue by cyisfor** [violentmonkey/violentmonkey#496]
### What is the problem?

I wrote a user script to deal with the awful predatory javascript on tvtropes.org, and it just... didn't do anything. Convinced I did something wrong, I replaced my script with `console.log("test");` still nothing. I tried adding `@grant GM_log` then `GM_log("test");` but still nothing. Violentmonkey's badge popup lists my scripts as one of the active scripts for that site, and there's no meaningful error message I can find in the browser console, but even the most basic test script won't run.

So then, I added an @include rule not just for https://tvtropes.org/* but also for http://127.0.0.1/test/ and loaded a page on my local test server. My test script did run in this case, and "[Violentmonkey][No TVTropes stupidity] test" printed out perfectly well in the browser console. Yet loading it on tvtropes.org seems to report that it worked on Violentmonkey's badge, then doesn't do anything at all.

I also tried messing with that "page" vs "auto" injection mode, but setting it to "auto" didn't help make it work on tvtropes.org. Setting `@injection-mode content` didn't help either. To be fair, I have no idea if GM_log works in content mode. But if it does, then my script succeeds on a normal test site, but silently fails on tvtropes.org.

The only error message that appeared in the browser console at all for tvtropes.org was
```Error: WebExtension context not found! ExtensionParent.jsm:1021:13 ```

That error happens even when Violentmonkey is disabled though, so it's probably unrelated.

### How to reproduce it?
1.
```javascript
// ==UserScript==
// @name TVTropes thing
// @namespace Violentmonkey Scripts
// @include https://tvtropes.org/*
// @include https://tvtropes.org
// @include http://127.0.0.1/test/
// @injection-mode content
// @grant GM_log
// ==/UserScript==

GM_log("this script really should run no matter what");
```

2. Open the browser console (Ctrl+Shift+J)
3. Load https://tvtropes.org
4. Observe the browser console.
5. Start up a test HTTP server locally
6. Load http://127.0.0.1/test/
7. Observe the browser console.

### What is the expected result?

It logs the message in the browser console, when both websites are loaded.

### What is the actual result?

It doesn't work for https://tvtropes.org

### Environment
- Browser: Firefox
- Browser version: 63.0.3
- Violentmonkey version: 2.10.0
- OS: Gentoo

**Comment by gera2ld** [comment]
Does this issue still happen? It works for me with Firefox beta / nightly, no matter whether `@inject-into` is set.

![image](https://user-images.githubusercontent.com/3139113/51013602-68df6e00-159e-11e9-8e18-1534a9010182.png)

**Comment by gwarser** [comment]
Conflict with uBO.
Works with these exception filters:

```
tvtropes.org#@#+js(abort-on-property-read.js, stop)
tvtropes.org#@#+js(abort-on-property-read.js, Uint8Array)
```
