### ISSUE TITLE
Violentmonkey not working with Burlesco userscript

### ISSUE THREAD

**Issue by KingThunder** [violentmonkey/violentmonkey#497]
### How to reproduce it?
1. Install userscript from https://burles.co/
2. Visit: https://oglobo.globo.com/brasil/morreu-esse-assunto-diz-mourao-sobre-promocao-de-filho-no-bb-23362389

### What is the expected result?

It should show the article with the userscript.

### What is the actual result?

Not working.

### Environment
- Browser: Google Chrome (64-bit)
- Browser version:  71.0.3578.98
- Violentmonkey version: 2.10.1
- OS: Windows 10 x64

**Comment by tophf** [comment]
The script is using `@webRequest` meta key that's implemented only in Tampermonkey, no one else has it.

**Comment by tophf** [comment]
Depends on #583.
