### ISSUE TITLE
GM_download window

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#498]
When I execute `GM_download` function, first window I see is window asking whether to open remote file using installed application or save it as local file. After I choose "save as local file" I see standard OS save window. 

So, can this first window be omitted in order to save file? Just like when I press right mouse button and then click "Save as". Otherwise, there is no advantage over "right click + save as"

**Comment by gera2ld** [comment]
`GM_download` just mimics a download behavior, as if you click on a URL to download a file. It's your browser who decides whether to download it immediately as Chrome does or prompt a modal to ask for your decision as Firefox does by default.

So I guess you are using Firefox. Please finish the issue template with your browser information and don't let me guess next time.

**Comment by soviet-man** [comment]
Sorry. I understood.
My browser is **Firefox** and my OS is **Manjaro Linux**
