### ISSUE TITLE
希望可以在这里直接下载到crx文件

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#50]
因为总有人问打不开应用商店，哪里可以下载到crx文件……
TM的话网盘上有不少，然后这边的找不到……

**Comment by gera2ld** [comment]
加上百度网盘的链接了：https://gerald.top/code/vm-nex

**Comment by tiansh** [comment]
您好，那个链接挂掉了……

**Comment by gera2ld** [comment]
@tiansh 直接用GitHub的release好了。但是现在Chrome不是不让自己通过文件安装CRX吗？

**Comment by tiansh** [comment]
我不知道，只是有不少用户和我抱怨说网盘挂了，没法安装暴力猴，我自己倒是不会用网盘……
