### ISSUE TITLE
Can make the install guide tab opened in new window?

### ISSUE THREAD

**Issue by GoogleBeEvil** [violentmonkey/violentmonkey#502]
作者是原子？那直接就中文了
能不能把安装脚本的页面做成弹窗模式或者做个开关选项，就像ublock original那个“打开网络请求记录器”

**Comment by kliop00023** [comment]
其他猴子没有的话估计都是......

**Comment by gera2ld** [comment]
什么弹窗模式？什么开关选项？完全看不懂。

**Comment by kliop00023** [comment]
后来才懂有种插件能右键开链接弹窗，但即使没有，安后也会自动关啊。。。
