### ISSUE TITLE
Violentmonkey and manifest V3

### ISSUE THREAD

**Issue by ameshkov** [violentmonkey/violentmonkey#505]
Hi, this thread seems to be relevant to Violentmonkey as well, I guess it makes sense to comment there:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/hQeJzPbG-js

**Comment by tophf** [comment]
With the info available so far, ManifestV3 will kill Violentmonkey, Tampermonkey, Stylus, Stylish, and similar extensions. Google's engineers are either lying or evading such questions when asked directly. There's nothing we can do about that.

**Comment by andre-st** [comment]
Chromium's Manifest V2 support ends next year (2023)

**Comment by Poopooracoocoo** [comment]
An update on this: Firefox for Android will _ONLY_ have general availability of manifest v3 (MV3) extensions. _Not_ MV2 extensions.
