### ISSUE TITLE
How to get cookies from GM_xmlhttpRequest?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#507]
I can set cookies in request via `details.headers.cookie`
But how can I get response cookies? In response object I have only `responseHeaders` field with no information about cookies. However using Firefox WebTools I can see what  cookies are set by response.

**Comment by gera2ld** [comment]
It's not supported.

The Set-Cookie header is on the forbidden header list:
https://fetch.spec.whatwg.org/#forbidden-response-header-name

**Comment by soviet-man** [comment]
How can I get response cookies then?

**Comment by gera2ld** [comment]
You can get cookies of current domain via `document.cookie`. You cannot access cookies from other domains due to security concerns.

**Comment by soviet-man** [comment]
I checked it already.
`document.cookie` is empty string after parse response.responseText as HTMLDocument.
