### ISSUE TITLE
Scheduling autoexport of userscripts to a file system

### ISSUE THREAD

**Issue by DRSAgile** [violentmonkey/violentmonkey#508]
### What is the problem?

Firefox Developer Edition is beta software which regularly causes breakage of extensions, especially right after updates between beta versions. For example, like in my case today, after an update to version 66 beta 4, ViolentMonkey was not able to load any scripts or even show them in the options for a while. It did eventually work, but _localStorage_ does not sound to be reliable in those circumstances, and it is poorly accessible to users in case of malfunction.

The ViolentMonkey extension does allow manual export, but due to the human factor, it is unreliable in terms of how after user can remember to do it.

### How to reproduce it?
See above.

### What is the expected result?
Regularly exported to a file system userscripts.

### What is the actual result?
Only manual export capability.

### Environment
- Browser: Firefox Developer Edition 
- Browser version: 66.0b4
- Violentmonkey version: 2.10.1
- OS: Windows 10 64-bit (fully updated)

**Comment by gera2ld** [comment]
First, it's the problem of Firefox that breaks storage of extensions.

According to [the document](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage), `browser.storage` is the recommended place for extensions to store data at. So I think it's Firefox's job to make it more reliable.

> Although this API is similar to Window.localStorage it is recommended that you don't use Window.localStorage in the extension code to store extension-related data. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the storage.local API will be correctly persisted in these scenarios.

Second, the extension does not have permission to write files directly.

Currently it requires a user operation (e.g. click on the button) to trigger a download of the backup. Though this could be implemented with another extension API, it would be much too heavy to require an extra permission for such a case. Users may be confused about why and what I want to do.

So, I'm closing this as won't fix. The *sync service* might be another choice.
