### ISSUE TITLE
关于同步的一些问题

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#51]
看了下设置，似乎不支持 google account 同步？
至于dropbox/onedrive的支持，是手动还是自动备份？能否做到同一账号授权，多台机子之间同步？能否同步脚本状态，如启用/禁用？
另外，是否考虑发firefox版？如果能通过onedrive等同步，那就可以做到跨浏览器同步，就太棒了。

**Comment by gera2ld** [comment]
1. 不支持Google account同步。
1. 网盘同步都是自动的，授权同一个账号并勾选同步后，多个浏览器之间都可以同步，包括脚本状态、自定义信息，暂时 **不支持脚本数据（GM_setValue）的同步** 。
1. 暂时不考虑开发Firefox版，目前支持基于Chromium的各种浏览器（Chrome、Opera、Vivaldi、QQ浏览器等），傲游版也即将加入同步支持，这些浏览器之间都是可以互相同步的。

**Comment by renyouguo** [comment]
Firefox 46 正式版已经发布，开始统一 API，与 Chromium 类无比接近了，不知可否考虑下。
Tampermonkey Beta 已支持 Firefox 46，并计划支持 Android 版 Firefox，虽然试了下还很不完善。

**Comment by LiteCoder** [comment]
傲游浏览器 同步到onedrive 提示同步出错！
