### ISSUE TITLE
Some keywords are not highligted

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#510]
Some keywords associated with classes are highlighted, but some -- are not.
For example, keywords like **class**, **extends**, **static** are highlighted, but keyword **constructor** -- is not. Maybe some other keywords are not highlighted as well.

It would be nice that all keywords are highlighed in the next release.

**Comment by soviet-man** [comment]
Example
![default](https://user-images.githubusercontent.com/33825590/52595022-f5ab6f00-2e5d-11e9-9a31-f6dd00ef2b0f.png)

Constructor is not highlighted.

**Comment by gera2ld** [comment]
This is by design, and `constructor` is not a keyword.

FYI, syntax highlight is implemented by [CodeMirror](https://codemirror.net). If you still think it a problem, you may file a issue there.

**Comment by soviet-man** [comment]
Why can not I use code-autocompletion then? Or checnging theme?
