### ISSUE TITLE
Custom script [feature request]

### ISSUE THREAD

**Issue by SuperOP535** [violentmonkey/violentmonkey#518]
Either allow:
1. normal userscripts to run on the -extension page
or
2. a custom script input alongside custom style input in the advanced settings.

##### Why?
Because it makes it a lot easier to customize the editor, right now we can only edit the theme and look of it but if you add this then one can change the settings and stuff. Method 1 may be abused by malicious scripts if not done correctly. If you do consider this (you really should) please make the editor object global.

**Comment by gera2ld** [comment]
This is not possible since both Chrome and Firefox do not allow arbitrary code to execute in extension pages. Even in web pages it takes a long time for me to find a way to inject arbitrary code, and it might be blocked (#505) in the future.

**Comment by SuperOP535** [comment]
Thank you for answering, I guess I will build my own version of the extension then...
