### ISSUE TITLE
对OpenUserJS支持不好

### ISSUE THREAD

**Issue by renyouguo** [violentmonkey/violentmonkey#52]
About | V2EX自动领取每日签到登录奖励 | Userscripts | OpenUserJS - https://openuserjs.org/scripts/myejin/V2EX%E8%87%AA%E5%8A%A8%E9%A2%86%E5%8F%96%E6%AF%8F%E6%97%A5%E7%AD%BE%E5%88%B0%E7%99%BB%E5%BD%95%E5%A5%96%E5%8A%B1

这个站点里的所有脚本，点击安装后，获取的都是一个html，于是连名字也没有了。

**Comment by gera2ld** [comment]
Related to violentmonkey/violentmonkey-oex#40

**Comment by gera2ld** [comment]
之前还奇怪为什么在Chrome下会正常的，现在果然还是坏了。。。
