### ISSUE TITLE
Invalid encoding for script from local filesystem

### ISSUE THREAD

**Issue by npocmu** [violentmonkey/violentmonkey#521]
### What is the problem?
ViolentMonkey open local files with invalid encoding

### How to reproduce it?
1. Use menu command `File/Open file` or press Ctrl-O
2. Select some user script  having UTF-8 encoding from local disk.
3. Press Enter

ViolentMonkey opens install script page but script has invalid encoding.

### What is the expected result?
Open script as Unicode (UTF-8)
I'm use Greasemonkey before and never got such problem. 

### What is the actual result?
Invalid encoding of script. Seems as ViolentMonkey rely on default browser settings for open a file.
But when file opened in browser its allow to change it encoding, but with ViolentMonkey is not.

Solution: treat all local file as having UTF-8 encding as GreaseMonkey does (i suppose)

### Environment
- Firefox:
- 52.0.1:
- v2.10.1:
- Windows XP:

**Comment by tophf** [comment]
Any example file for tests?

**Comment by npocmu** [comment]
There are localization in  different languages in lines from 1777 up to 9451.
When opens as described in issue it broken.
