### ISSUE TITLE
Chrome由71升级到72后，部分脚本失效了

### ISSUE THREAD

**Issue by ckz1211** [violentmonkey/violentmonkey#524]
差不多一个月前，Chrome后台强制自动升级，由71升级到72.
因为Chrome 72 因为增加了一些限制，导致了油猴类扩展的一些功能失效然后部分脚本就失效了。
之后不久，Tampermonkey很快更新了兼容Chrome 72的新版本4.8，解决了这个问题。
不过我还是更喜欢用暴力猴，就等了一个月。这个月暴力猴的Chrome版终于更新新版本2.10.2，但我测试了以后，发现还是没能兼容Chrome 72（当然71以下旧版Chrome还是没问题）

**Comment by gera2ld** [comment]
举个例子？

**Comment by ckz1211** [comment]
> 举个例子？

这个脚本：
https://greasyfork.org/zh-CN/scripts/33087
还有这个：
https://github.com/hymbz/ComicReadScript
https://greasyfork.org/zh-CN/scripts/374903
在Chrome 72里，无法显示被隐藏章节的图片，一直显示图片载入中……
换了便携版(无自动升级功能)的Chrome 71后，这两个脚本恢复正常。

**Comment by gera2ld** [comment]
fixed in 32691c370c9a8f56a302396cba0c198e1aaef6cb
