### ISSUE TITLE
Is it possible to use regex in @match field in an userscript settings tab?

### ISSUE THREAD

**Issue by leewdch** [violentmonkey/violentmonkey#525]
A rule like this works fine
`webbbsite.com/*`
but something like this doesn't
`\w{1,5}site.[a-z]{2,4}\/.*`
is it because I can't use regex outside of the userscript lines?

**Comment by gera2ld** [comment]
Because regex is not valid [match pattern](https://developer.chrome.com/extensions/match_patterns).

**Comment by MidStein** [comment]
Just going to chime in to say that @include can be used for matching with regular expressions. https://violentmonkey.github.io/api/matching/#include--exclude
