### ISSUE TITLE
Reduce editor header height when window height is small

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#526]
Some suggestions for changing interface

**Old interface**
![изображение](https://user-images.githubusercontent.com/33825590/54120820-c90d5780-4409-11e9-8ba6-068eb183fe5d.png)

**New interface**
![изображение](https://user-images.githubusercontent.com/33825590/54120824-d1659280-4409-11e9-9882-2e64b95427cf.png)

This saves some vertical space.

1) Name of currently editing script can be written as caption of main tab instead of immutable caption "Code" ("Код")
2) Link "How to edit with your favorite editor?" can be moved to Settings pane.
3) Some space added between buttons "Save", "Save and Exit", "Exit". By the way, I dont think there is a need for 3 buttons. Two buttons -- "Save" and "Exit" -- would be enough.
4) As a result upper bar becomes empty, and everything can be moved up.
This saves about 35px of vertical space.

**Comment by gera2ld** [comment]
1. Good idea.
2. "How to edit with your favorite editor?" is helpful to people who is trying to edit a script here but do not like the editor. If it is moved somewhere else, it become useless and does not make sense. But I can make the link title shorter, something like changing the text to an icon.
3. It's OK to remove "Save and Exit", though I use it very often.
4. The "empty" bar actually has a message area, in which messages are displayed when code lines are too long for the editor to handle. Maybe I can change it into a row at the top of the code area, and hide it when there is no message.

**Comment by T1mL3arn** [comment]
>"How to edit with your favorite editor?" 

@gera2ld don't remove the link, please. It is better to have that link as it is in text-form.

**Comment by tophf** [comment]
I've combined the two panels into one in my own custom CSS:
![image](https://user-images.githubusercontent.com/1310400/65800229-99902380-e17e-11e9-8f02-f3ad461dfe96.png)
