### ISSUE TITLE
能否自定义安装脚本的排序

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#53]
貌似现在是按照安装顺序排列的。
能否提供自定义选项，可以按照名称/更新日期 等等排序。
最好在设置里面有个默认排序模式的选项。

**Comment by gera2ld** [comment]
这个排序决定了脚本的运行顺序，所以按名称/日期之类的不太合理吧。。现在可以自己拖动调整顺序吧

**Comment by renyouguo** [comment]
哦，习惯了GM的模式，管理器默认按照名称排序，执行顺序与管理器显示顺序貌似没啥关系。

**Comment by gera2ld** [comment]
确实可以把执行顺序提出来当成一个排序指标，这个以后再做吧

**Comment by ivysrono** [comment]
一年过去了……
作为一名Firefox用户，看到终于适配了 WebExtension 真是高兴啊，虽然还没有过审ε=ε=ε=┏(゜ロ゜;)┛

**Comment by gera2ld** [comment]
我觉得搜索功能可以替代排序，先关闭此issue，如果仍有需求再打开吧
