### ISSUE TITLE
strict mode?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#533]
Can I execute JavaScript code in strict mode inside my userscript?
If I can, where should I type `'use strict'` directive?

**Comment by gera2ld** [comment]
At the very beginning, just as you can do in a normal script.

**Comment by soviet-man** [comment]
VM says "Неверный формат" ("Wrong format")

![изображение](https://user-images.githubusercontent.com/33825590/54730798-e5448d80-4b9b-11e9-8f5b-56291a95962e.png)

**Comment by soviet-man** [comment]
Thank you. I thought at the very beginning info about userscript must be placed.

Like this
```
// ==UserScript==
// @name MyName
// @namespace MyNamespace
// @include     *
// @grant       GM_notification
// ==/UserScript==
```

**Comment by gera2ld** [comment]
`'use strict';` should be placed before any other statements. Comments are ignored, so either before or after the metadata block (actually comments) is ok.
