### ISSUE TITLE
How to debug userscript?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#534]
Can I walk through my code line-by-line like with usual JS script?
Or I can debug only by inserting `console.log` after each line?

**Comment by gera2ld** [comment]
Please try [MDN](https://developer.mozilla.org/en-US/):
- [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)

**Comment by soviet-man** [comment]
Thank you very much!

**Comment by douglasg14b** [comment]
Debugger doesn't hit break[point son violentmonkey userscripts , and network requests from userscripts don't show up on the networking tab either 🤔
