### ISSUE TITLE
`Installing script` ERR_UNSAFE_REDIRECT

### ISSUE THREAD

**Issue by mikhaelkh** [violentmonkey/violentmonkey#537]
### What is the problem?
Behavior changed when click on Install this script button or `*.user.js` links.

### How to reproduce it?
Open https://greasyfork.org/en/scripts/2312 and click `Install this script`
Open https://github.com/ParticleCore/Particle/wiki/Download and click `GitHub`

### What is the expected result?
VM scipt install dialog opens in new tab

### What is the actual result?
1. VM scipt install dialogs opens in new tabs - 2 instantly, third may open after about 5 seconds
1. GF tab has error `ERR_UNSAFE_REDIRECT` and message `This site can’t be reached`.

### Environment
- Browser: Chromium
- Browser version: 73.0.3683.86 (Official Build) (64-bit)
- Violentmonkey version: v2.10.3
- OS: Windows 10 v1607 x64

**Comment by mikhaelkh** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/667 - similar issue in Tampermonkey

**Comment by gera2ld** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/667#issuecomment-480170882
