### ISSUE TITLE
[Feature Request] Firefox new UserScripts WebExtensions API

### ISSUE THREAD

**Issue by Acid-Crash** [violentmonkey/violentmonkey#538]
There was some news that Firefox is planning to add new API for userScripts
Reference can be found here
https://www.ghacks.net/2019/03/27/firefox-support-user-scripts-api/
https://blog.mozilla.org/addons/2019/03/26/extensions-in-firefox-67/

Do you have any plans on supporting this?

### Environment
- Browser: Firefox

**Comment by tophf** [comment]
Let's close this and keep #604.
