### ISSUE TITLE
https://github.com/violentmonkey/violentmonkey/releases/tag/v2.3.8

### ISSUE THREAD

**Issue by Martii** [violentmonkey/violentmonkey#54]
Me again. ;) :)

When I install this in a clean profile it says "2.3.7" in `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 OPR/35.0.2066.37` *(a little older but it is what my distro gives me)*

Until the next time? :)

**Comment by gera2ld** [comment]
Thank you very much for pointing this out. It was the wrong file...
