### ISSUE TITLE
SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by cnleo** [violentmonkey/violentmonkey#540]
I get this error in Chrome/Vivaldi on this page https://www.techrepublic.com/.
Not sure, is it one of the CSP send by techrepublic or something else.

CSP send by thechrepublic:
content-security-policy: frame-ancestors 'self' *.techrepublic.com *.ampproject.org *.amp.cloudflare.com; default-src https: blob: 'unsafe-inline' 'unsafe-eval'; font-src https: blob: data:; img-src https: data: android-webview-video-poster: blob:; form-action https:; block-all-mixed-content; media-src https: blob: data:;

### How to reproduce it?
```
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match <all_urls>
// @grant none
// @run-at start
// ==/UserScript==

if (!!document.styleSheets[0] && !!document.styleSheets[0].rules && document.styleSheets[0].rules.length > 0){
  // never exceed
}
// nope
```

### What is the expected result?
Userscript should run continuously.

### What is the actual result?
Script hold on Security Error by `document.styleSheets[0].rules`

### Environment
- Browser: Vivaldi
- Browser version: 2.4.1488.35 (Stable channel) (32-Bit) // equal to Chrome/73.0.3683.88
- Violentmonkey version: 2.10.3
- OS: Windows 7 64bit

**Comment by gera2ld** [comment]
See <https://stackoverflow.com/a/49161468/4238335>
