### ISSUE TITLE
不支持 // @match https://www.google.*/search*

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#541]
### What is the problem?
我知道 VM 不支持 `@match http*://` 这种写法，虽然很多脚本这么写的用不了还是忍了。
今天又踩了个大坑，不认 `// @match https://www.google.*/search*`
搞了很久才想到改成 include.
自己写的还能改，别人写的就麻烦了。
还是希望能支持下，尤其是写成  `@match http*://` 的太多了。

### Environment
- Browser: Fx x64
- Browser version: 66
- Violentmonkey version: 2.10.3
- OS: Windows

**Comment by soviet-man** [comment]
I don't know Chinese at all. So I had to use online translator.
As I understood, you are complaining about `match` keyword and its limits. 
I always use `include` keyword. For simple cases -- `include` with **wildcards** `*`. For complex cases -- `include` with **regexp** enclosed in slashes. It never lets me down.

**Comment by maple3142** [comment]
@soviet-man The problem is that many scripts written by others use `match` like this, and it works on other script managers.

**Comment by FlandreDaisuki** [comment]
match pattern
https://developer.chrome.com/apps/match_patterns
use `include`

**Comment by tophf** [comment]
@cyfung1031, since you've opened a separate issue #2527 I've removed the comment to avoid duplication.
