### ISSUE TITLE
[Feature request] Sorting scripts by recently updated / installed

### ISSUE THREAD

**Issue by krisu5** [violentmonkey/violentmonkey#543]
Would be useful, when you don't notice that script(s) were updated or when multiple updates happen at the same time. Or when you install a script for few minutes, but want it to uninstall it after all.

**Comment by soviet-man** [comment]
Actually order of scripts really matters. Can sorting break this order?

**Comment by gera2ld** [comment]
@soviet-man Sorting just helps maintaining scripts, without breaking the executing order which is one of the sorting methods.
