### ISSUE TITLE
部分脚本导致violentmonkey抛出TypeError

### ISSUE THREAD

**Issue by KCCat** [violentmonkey/violentmonkey#547]
### What is the problem?
部分脚本导致violentmonkey抛出TypeError. 

[脚本页面](https://greasyfork.org/zh-TW/scripts/19619-ehtagbuilder)
[脚本执行页面](https://github.com/Mapaler/EhTagTranslator)

错误信息
```
[Violentmonkey][page][EhTagBuilder] 
TypeError: Cannot read property 'XXX' of undefined
Cannot read property 'XXX' of undefined
 ```
XXX为浏览器首选语言字段(如"zh_CN"). 
手动在控制台执行脚本可以正常运行.

### Environment
- Browser: Chromium 
- Browser version: 73.0.3683.103 
- Violentmonkey version: 2.10.3 
- OS: Arch Linux

**Comment by gera2ld** [comment]
脚本的问题，`GM_info.script.name_i18n[lang]` 执行会报错，可以向脚本作者反馈
