### ISSUE TITLE
功能建议：在脚本网站greasy fork等脚本页面显示是否已安装此脚本

### ISSUE THREAD

**Issue by X-hood** [violentmonkey/violentmonkey#548]
### What is the problem?
在脚本资源网站如：https://greasyfork.org/zh-CN 上，点击某个脚本，不管是否已安装，按钮显示文字都是“安装此脚本”，能否像Tampermonkey那样判断是否已安装，当已经安装后显示“重新安装”，有大量名字相近的脚本，容易造成不便。
### How to reproduce it?
1.
2.
3.

### Environment
- Browser:Google Chrome
- Browser version: 72.0.3626.121
- Violentmonkey version:v2.10.3
- OS:

**Comment by gera2ld** [comment]
See [vm-detector](https://github.com/violentmonkey/vm-detector).

**Comment by maple3142** [comment]
@gera2ld Why not file an issue to https://github.com/JasonBarnabe/greasyfork to ask for a support for VM? Just like what TM has done.

**Comment by X-hood** [comment]
> 见[vm-detector](https://github.com/violentmonkey/vm-detector)。

好的，谢谢。没想到还要为此再安装一个脚本。虽然原理上应该没有啥区别。
