### ISSUE TITLE
`requestAnimationFrame` does not work

### ISSUE THREAD

**Issue by fsproede** [violentmonkey/violentmonkey#55]
In https://greasyfork.org/de/scripts/4255-linkify-plus-plus?version=116878 the "function* generateRanges(node, filter)" declaration in line 113 doesn't work.

The script works with Tampermonkey. Tested in Opera and Chrome.

**Comment by gera2ld** [comment]
I think the error occurs due to wrong context for `requestAnimationFrame`.

**Comment by fsproede** [comment]
Yes, I was mistaken. The line 113 error occurred in  Maxthon with Violentmonkey. and in Palemoon with Greasemonkey.

In VM/Opera, VM/Chrome the error was: TypeError: Illegal invocation
In Maxthon/VM the error was: Unexpected token *

**Comment by gera2ld** [comment]
Maxthon does not support generators. Violentmonkey cannot help.
