### ISSUE TITLE
2.10.4 break scripts for www.sis001.com

### ISSUE THREAD

**Issue by 15556133244** [violentmonkey/violentmonkey#550]
```
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match https://www.sis001.com/forum/index.php
// @grant none
// ==/UserScript==
console.log('test')
```

log nothing
`SyntaxError: unexpected token: ')'`
`injected.js:1`

**Comment by edwcb** [comment]
Change script setting to run at document start it will not break.

**Comment by gera2ld** [comment]
This page has overridden `Array.prototype.push` with a broken implementation, breaking Violentmonkey as a result. I'll fix this later.

**Comment by 15556133244** [comment]
@gera2ld 2.10.5 does not fix this issue.
