### ISSUE TITLE
[Question] Meaning of 'current language' in 'About' page

### ISSUE THREAD

**Issue by jakseb** [violentmonkey/violentmonkey#553]
Page 'About Violentmonkey' contains text 'Current Language: {code}'. What does this exactly mean? Is this supposed to refer to:
* the language of the browser's UI or
* the language of Violentmonkey's UI or
* something else (e.g. the most preferred language for websites)?

**Comment by gera2ld** [comment]
It's the language of the browser's UI, usually also the language of the system. It's useful if you want to contribute to the translation but don't know what your language code is, that's why it's beside "Help with translation".

**Comment by jakseb** [comment]
So here it should be `pl` or `pl-PL` instead of `en-US`, right? (The browser's UI is in Polish, but the most preferred language for websites is set to `en-US`).
![screenshot](https://user-images.githubusercontent.com/23054974/56851552-acbd6f80-6910-11e9-849a-9fd30c49e412.png)
If so, this line: 
https://github.com/violentmonkey/violentmonkey/blob/1c205e703b58d560ddbb0b9d3a9fce8efa9bd5f1/src/options/views/tab-about.vue#L32
should be changed to use `browser.i18n.getUILanguage()`.

**Comment by jakseb** [comment]
By the way, @gera2ld could you delete #549? I posted that unintentionally.

**Comment by gera2ld** [comment]
@jakseb It seems GitHub does not support removing an issue completely.

**Comment by gera2ld** [comment]
> should be changed to use `browser.i18n.getUILanguage()`.

@jakseb You are right.
