### ISSUE TITLE
2.10.4 do not support Android

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#554]
Why？

**Comment by gera2ld** [comment]
It works for me.

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/56816917-07a28880-6877-11e9-8233-84bf125a2fa8.png)
https://addons.mozilla.org/zh-CN/firefox/addon/violentmonkey/versions/
是不是发布的时候没选上Android

**Comment by gera2ld** [comment]
@ivysrono My fault. v2.10.5 will work in Firefox Android.
