### ISSUE TITLE
On Kiwi Browser, Can't Authorize Google Drive for Sync

### ISSUE THREAD

**Issue by thedward** [violentmonkey/violentmonkey#555]
I'm using Kiwi Browser, which is basically a fork of Chromium with (among other changes) extension support enabled. 

The good news is that, aside from syncing, Violentmonkey works as expected on Kiwi Browser.

### What is the problem?

When using the Chrome extension on [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser), authorizing Google Drive for sync fails.

### How to reproduce it?

1. Install [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser).
2. Install [Violentmonkey from the Chrome Web Store](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag?utm_source=chrome-ntp-icon).
3. On the Violentmonkey settings page, under 'Sync', after 'Sync to', select the Google Drive option.
4. Click the authorize button.

### What is the expected result?

I expect to be redirected to a Google authorization page, choose a Google account to use, then be redirected back to the Violentmonkey settings where sync is now enabled.

### What is the actual result?

I get redirected to the Google authorization page, choose my Google account and instead of getting redirected to the Violentmonkey settings page, the browser is redirected to:

`https://violentmonkey.github.io/auth_googledrive.html?code=<authorization code redacted>&scope=https://www.googleapis.com/auth/drive.appdata`

Where I see this:

![image](https://user-images.githubusercontent.com/213372/56934630-44a68f00-6ab2-11e9-88c5-0b947f3f3e2e.png)

### Environment

- Browser: Kiwi Browser
- Browser version: 73.0.3683.90
- Violentmonkey version: v2.10.4
- OS:Android / Version 9 / April 5, 2019 Security Patch Level

**Comment by gera2ld** [comment]
same as #667 , fixed in v2.12.1
