### ISSUE TITLE
能否支持在容器标签页打开地址

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#556]
就是 openInTab 魔法，能否指定在自定义的 yyymmdd 容器标签页打开？
现在应该是不能实现的。
Firefox的容器标签页很好用，不清楚chrome是否也有类似的功能。

**Comment by Riajyuu** [comment]
@ivysrono Firefox 容器标签页有完成webext接口 毫无问题
关于chrome类似功能 相关patch已被chromium驳回

**Comment by gera2ld** [comment]
similar to #415

**Comment by gera2ld** [comment]
我觉得指定容器太复杂了，还要提供选择容器的方法了，最好是就在当前容器打开。

**Comment by tiansh** [comment]
GM_xhr 支持容器的最好办法是把请求放到 content script 而不是 backend script 里面去……

**Comment by tiansh** [comment]
现在  Chrome 隐身窗口的 GM_xhr 怎么解决的？（在主窗口和隐身窗口登录不同的账号，xhr会把谁的 cookies 带上？）这个按理说和容器是一个概念。

**Comment by gera2ld** [comment]
> GM_xhr 支持容器的最好办法是把请求放到 content script 而不是 backend script 里面去……

有道理，最开始其实是放 content script 里的，后来为了实现一些高级功能移到了 background。我看看能不能在 content script 里实现。。

> 现在 Chrome 隐身窗口的 GM_xhr 怎么解决的？

这块应该用的是普通窗口的 cookie 。

**Comment by Riajyuu** [comment]
@gera2ld 
> 有道理，最开始其实是放 content script 里的，后来为了实现一些高级功能移到了 background。我看看能不能在 content script 里实现。。

很明显不能

**Comment by gera2ld** [comment]
@tiansh 这个方案不行，当页面是 HTTPS 时，HTTP 请求会被 block，所以还是得放到 background。

**Comment by gera2ld** [comment]
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

> To improve security, cross-origin fetches will soon be disallowed from content scripts in Chrome Extensions.  Such requests can be made from extension background pages instead, and relayed to content scripts when needed.

**Comment by tiansh** [comment]
> 
> 
> https://www.chromium.org/Home/chromium-security/extension-content-script-fetches
> 
> > To improve security, cross-origin fetches will soon be disallowed from content scripts in Chrome Extensions.  Such requests can be made from extension background pages instead, and relayed to content scripts when needed.

很迷了，如果扩展能泄漏权限导致fetch提权，那一样可以用 iframe 提权，所以感觉这说法莫名其妙的。而且文章也没说 cookies 要怎么带……
