### ISSUE TITLE
Download failed. Please check your connection (Firefox)

### ISSUE THREAD

**Issue by gigelduru** [violentmonkey/violentmonkey#557]
I am getting that error in Firefox when I try to add the extension from here https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
"Download failed. Please check your connection"
I've tried it on multiple PCs.

P.S: I need it to work on Firefox

**Comment by wingedonezero** [comment]
Its because firefox disabled a ton of addons in the 57 update mine that i had installed doesn't work either and has been disabled. They are only allowing 100% webextentions and ones with easily readable code i read. So idk why this one was removed/disabled but hopefully we can get some input.

**Comment by wingedonezero** [comment]
Actually look here its with a ton of add-ons https://news.ycombinator.com/item?id=19823465

**Comment by gera2ld** [comment]
See also:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
- https://twitter.com/firefox/status/1124527050490933248

**Comment by gera2ld** [comment]
Closing as I think this one has been fixed by Firefox.
