### ISSUE TITLE
Feature Request: Include change history in the name of the file created in "Export to ZIP file"

### ISSUE THREAD

**Issue by ua7** [violentmonkey/violentmonkey#558]
The file name created in "Export to ZIP file" is, for example, "scripts_2019-05-03_20.00.00.zip" at present, but how about the idea of automatically adding the update history to this?
For example, if you installed the script foo from the previous export, edited the bar script, and created a baz script,
The zip file is named something like "scripts_2019-05-03_20.00.00 installed_foo_2019-05-02_20.00.00 modified_bar_2019-05-02_21.00.00 created_baz_2019-05-02_22.00.00.zip".
If the file name length exceeds about 120  (preferably changeable) characters, it should be cropped automatically.

### What is the problem?
You can not quickly find the version you are looking for from the exported zips.

### How to reproduce it?
1.Export to ZIP.

### What is the expected result?
You will be able to quickly find the version you are looking for from the exported zips.

### Environment
- Browser: Firefox Developer Edition
- Browser version: 67.0b16 (x64)
- Violentmonkey version: v2.10.4
- OS: Windows 7 x64

**Comment by gera2ld** [comment]
I don't think this is a good idea since the changes may be very frequent and the suggested name is not so readable. Here comes a question, why would you export scripts so often?

**Comment by ua7** [comment]
The "modified" in the previous example only means that the user has modified the script himself. Updates by downloading from greasyfork etc. are not included. Also, if you want to avoid any effort, "installed" is unnecessary.
So this is a lightweight kind of logging and version control of the user's programming history. That's why exports are frequent.
My example may be difficult to read, but I don't care about the details of the format, so please think as you like. Anyway, the extra space of the file name of the current export file is not used for other purposes, so it is more useful than no information even if it is not beautiful or difficult to read. Besides, since the prefix is ​​kept as it is, if the user only looks at the first part, it is the same as before.

**Comment by gera2ld** [comment]
In my opinion:
- To a normal user, exports are used for backup, not so often. Perhaps sync service is a better choice.
- To an advanced user who modifies scripts frequently, it's better to [edit them locally](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/), and manage them with a version control system.

I don't think filenames with very limited information can help you find the correct version after a lot of modification.

**Comment by tophf** [comment]
There's no backup software that does what the OP suggests so even if someone may find it useful, this is certainly not something that should be implemented in Violentmonkey. Instead, a separate tool or script should be used that compares two zips (or two unpacked directories) and outputs the differences to a file and so on. There should be existing tools/scripts like that.
