### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by Bushido1** [violentmonkey/violentmonkey#56]
Hello,

I have authorized violentmonkey app with Dropbox. After clicking button ,,Sync", the message ,,Sync error!" appears. Why?

**Comment by gera2ld** [comment]
Normally it's because you are not able to connect to Dropbox domains. In other cases you may open the background console of the extension and see the log lines for details.

**Comment by Bushido1** [comment]
I'm having this problem in Google Chrome & Opera. How can I connect to Dropbox domains in order to sync with it and how can I open the background console of the extension?

**Comment by gera2ld** [comment]
Do you connect to Dropbox directly or via proxies?

Steps to see the logs:

1. Open URL `chrome://extensions/`.
1. Find `Violentmonkey > Inspect views` and click on **background page**.
1. Switch to `Console` panel. There will be the log info.

**Comment by Bushido1** [comment]
I'm using Adguard ,,IP-address hide" function in their Stealth mode. I disabled their service, but still sync error. No other proxies, as far as I know.
What comes up in Console panel is attached here.
![5](https://cloud.githubusercontent.com/assets/11409601/15268789/dd6d5ed0-19f2-11e6-9d31-70544b46c118.jpg)

**Comment by gera2ld** [comment]
I think this is a bug...

**Comment by Bushido1** [comment]
I think too because it is also not reachable via web browser.
![6](https://cloud.githubusercontent.com/assets/11409601/15268891/9a0eab2c-19f6-11e6-84f4-d2d1fdd55b16.jpg)

**Comment by gera2ld** [comment]
This is reasonable because it is unreachable via browser and should be fetched with payloads programmatically.
