### ISSUE TITLE
Can not debug

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#560]
After I put `debugger` line in my code, Firefox opens debugger not on that line but somewhere inside _ExtensionContent.jsm_

![изображение](https://user-images.githubusercontent.com/33825590/57413172-dec9ae00-71fb-11e9-881c-5d3c57fc9fd0.png)

**Comment by gera2ld** [comment]
That is Firefox, just try another browser.

**Comment by soviet-man** [comment]
I can not debug the code
After I put `debugger` in my code Firefox stops at that line. But after pressing F10, it steps not to the next line, but immediately to the end of function. I have to debug with console.log after each line.
I wrote simple html page with JS. Debugger works as expected -- F10 steps line by line. Only ViolentMonkey has troubles.
