### ISSUE TITLE
Some sync issues

### ISSUE THREAD

**Issue by FreeDreamWings** [violentmonkey/violentmonkey#561]
### What is the problem?
Here are some sync problems in sync with Onedrive.

### How to reproduce it?
When I use sync with Onedrive ,it always shows that sync error.I find it may be caused by a JS from https://greasyfork.org/en/scripts/379893-%E7%99%BE%E5%BA%A6%E6%96%87%E5%BA%93%E6%96%87%E6%A1%A3%E5%85%8D%E8%B4%B9%E4%B8%8B%E8%BD%BD-%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E8%87%AA%E7%94%B1%E5%A4%8D%E5%88%B6-%E7%A7%BB%E9%99%A4%E7%99%BE%E5%BA%A6%E6%96%87%E5%BA%93%E7%BD%91%E9%A1%B5%E4%B8%AD%E7%9A%84%E5%B9%BF%E5%91%8A-%E8%A7%A3%E9%99%A4%E5%A4%A7%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99%E5%A4%8D%E5%88%B6-%E5%89%AA%E5%88%87-%E9%80%89%E6%8B%A9%E6%96%87%E6%9C%AC-%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E7%AD%89%E9%99%90%E5%88%B6.When I delete the JS,it can sync normally.And when I delete that JS's @namespace line(Here is a problem when I copy that JS's code and build a JS in violentmonkey by myself,so I delete that line to solve),and use google drive to sync,it can also sync normally.And can you add some new netdiscs like https://pan.baidu.com to sync.

### Environment
- Browser: Firefox ,Chrome
- Browser version: Firefox 66.0.5,Chrome 74.0.3729.131
- Violentmonkey version: v2.10.5
- OS: Windows 10 Home Edition 1809

**Comment by tophf** [comment]
Is it fixed in VM2.12.1?

**Comment by FreeDreamWings** [comment]
It has been fixed in VM2.12.1.Thank you.
