### ISSUE TITLE
知乎伪装ua不成功

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#562]
```
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match https://www.zhihu.com/*
// @grant none
// @inject-into   auto
// ==/UserScript==
if (navigator.userAgent.includes('Mobile')) {
  Object.defineProperty(navigator, 'userAgent', {
    value: 'Mobile'
  });
}
```
知乎移动端如果ua是单独的'Mobile'就能使用大部分功能，加入些乱七八糟的就会提示用APP。
但为什么这样伪装不行？同样的方法在别的网站都生效了。

**Comment by gera2ld** [comment]
大概是因为知乎的CSP屏蔽了inline script，导致脚本是在content script里执行的，所以无法改变page的navigator。

**Comment by gera2ld** [comment]
[文档](https://violentmonkey.github.io/2018/11/23/inject-into-context/#mode-content)里说了：

> The content context is an isolated world, scripts in this context have no access to JavaScript objects from page context.

**Comment by ivysrono** [comment]
thanks
