### ISSUE TITLE
Broken parsing on a small snippet

### ISSUE THREAD

**Issue by Kein** [violentmonkey/violentmonkey#565]
### What is the problem?
Unable to load userscript

### How to reproduce it?
1. Add script: https://pastebin.com/raw/ZANXGZj1
2. Try to load
3. ???

### What is the expected result?
It loads and works since a valid JS

### What is the actual result?
```
Uncaught ReferenceError: M is not defined
    at <anonymous>:1:352
    at <anonymous>:1:4352
    at Object.post (<anonymous>:1:4369)
    at k (<anonymous>:1:15423)
    at M (<anonymous>:1:15495)
    at LoadScripts.l.a.load (<anonymous>:1:9433)
(anonymous) @ VM446:1
(anonymous) @ VM417:1
(anonymous) @ VM417:1
k @ VM417:1
M @ VM417:1
LoadScripts.l.a.load @ VM417:1
Promise.then (async)
(anonymous) @ VM417:1
18:08:10.256 
```

### Environment
- Browser: Chromium
- Browser version: 76
- Violentmonkey version: 2.10.5
- OS: Windows 7

**Comment by gera2ld** [comment]
Can you provide a URL to reproduce this issue? I cannot reproduce it by setting `@match` to `*://*/*`.

**Comment by Kein** [comment]
https://steamcommunity.com/groups/archiasf/discussions/1/1651043958639045547/

https://steamcommunity.com/app/730/discussions/0/1649918058735582893/

few random

**Comment by Kein** [comment]
I reproduced it with just

```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match *://*/*
// @grant none
// ==/UserScript==

console.log("meh");
```

I'm more than confused now. Other scripts work fine.

**Comment by gera2ld** [comment]
Problem confirmed. They have changed the prototype of `Array`, kind of evil.

**Comment by Kein** [comment]
`They`?
![image](https://user-images.githubusercontent.com/623756/57611341-5476a680-757b-11e9-9108-57cc39abc1c6.png)
