### ISSUE TITLE
Will it be easy for me to change the Violentmonkey icons?

### ISSUE THREAD

**Issue by gaveitatry** [violentmonkey/violentmonkey#567]
I'm still stuck on Firefox 56.0.2 and Greasemonkey 3, but I am making the effort to switch to Firefox 66.0.5 and use an updated script editor.  For some reason Greasemonkey 4 does not seem to have word wrap, and I don't like dealing with scrollbars just to see all the text.  Tampermonkey is okay, I guess.  I never used it before.  But Violentmonkey seems pretty dang good, although I'm not sure why you did not implement ALL of the suggested changes here (https://github.com/violentmonkey/violentmonkey/issues/526) because every suggestion he made was 100% awesome.  So anyway, if I am going to be looking at this Violetmonkey icon all of the time, I want it to be a good looking icon.  In the navigation bar, in the tab, and wherever else it appears.  I want to change the navigation bar icon the most.  And then maybe tab icon.  Will this be hard to do?  Do I just look for the .xpi in the extensions folder, unzip it, and find out where the icons are stored and replace them?  If so, that would be easy.  But would I still get notified of updates and still get the most up-to-date version?

**Comment by roryokane** [comment]
What replacement icons are you thinking of using? If they are just tweaked versions of the existing icons, you could try to make them the official icons, and then you wouldn’t have to worry about updates.

**Comment by gaveitatry** [comment]
I took a Greasemonkey icon from their WIkipedia page.  Then I unzippled the Violetmonkey xpi and replaces all of the opacity:1 icons with that Greasemonkey icon and just restored their original names.  But that didn't work.  Maybe it's because I have to resize the Greasemonkey icon first.  Hell if I know.  I also don't like the purple indicator.  It looks ugly.  I agree indicators are useful, just not too crazy about that one.  These are all things that I figured I could change easily, but there are some other things I want to change too.  Like the drop down menu when you click on the Violetmonkey navigation bar icon.  I want to get rid of that "Visit Website" section and those boxes that appear in that section since they are redundant.  I'd also like to make the toggle on/off button bigger and more apparent.  But I figured these changes would be harder to make because then Firefox might consider it an unsigned web extension and then it won't work.  So I was just focused on the icons for now.  Not sure if I'll get the icon change to work, or if it is even worth it.  Maybe I'll just get used to the default ones.  I really like your web extension by the way.  I was a huge fan of Greasemonkey 3, but Greasemonkey 4 sucks.  They don't even have word wrap anymore.  I glanced at Tampermonkey and it seems to do more of what I want, but Violetmonkey's UI is way better than Tampermonkey so I went with Violetmonkey.  I was just hoping to tweak some things.

**Comment by gaveitatry** [comment]
I'll go ahead and close this dumb Issue and worry about it later.  I like VioletMonkey, and I would like to make customization to it one day.  But haven't figured out how to do that stuff yet.  I left you a five star review on Firefox Extensions by the way.  Thanks for your web extension and all that you do!
