### ISSUE TITLE
Script commands should be expanded by default

### ISSUE THREAD

**Issue by jamesgecko** [violentmonkey/violentmonkey#569]
### What is the problem?

I use a script that adds some commands to the ViolentMonkey extension menu.
Every time I use one of these commands, I have to click the extension button, then click to expand the "Script commands" menu, then click on the command. It's only one more click, but I use this command all the time.

1. It would be super handy if the script commands menu item was expanded by default.
2. The menu items are weird. The menu doesn't close after I click on one of them, unlike every other menu on my computer.

![Jun-05-2019 15-49-15](https://user-images.githubusercontent.com/44252/58985524-827d8e00-87a9-11e9-8589-efff5fe7f048.gif)

### How to reproduce it?
1. Click ViolentMonkey button
2. Click "Script commands"
3. Click command

### What is the desired workflow?
1. Click ViolentMonkey button
3. Click command

### Environment
- Browser: Firefox Developer Edition
- Browser version: 68b
- Violentmonkey version: 1.10.5
- OS: macOS

**Comment by gera2ld** [comment]
They are expanded by default now.
