### ISSUE TITLE
How can update  Maxthon extension to new version

### ISSUE THREAD

**Issue by ctorbaoglu** [violentmonkey/violentmonkey#571]
How can update  Maxthon extension to new 2.10.5 version.
Is there a way to convert githup zip file or chrome extension file to Maxthon's extension.

Thanks

### Environment
- Browser: Maxthon
- Browser version: 5.3.800
- Violentmonkey version: 2.8.4
- OS: Windows 10

**Comment by gera2ld** [comment]
There is no such way.
They are two different extensions and based on different APIs. See https://github.com/violentmonkey/violentmonkey-mx .
