### ISSUE TITLE
checking for update failed even @version changed

### ISSUE THREAD

**Issue by xxyyzz2050** [violentmonkey/violentmonkey#572]
in my script I change the value of @version 
```
// ==UserScript==
// @name test
// @version 1.03
// ==/UserScript==
```
but when I check for updates it says: No updates found

**Comment by gera2ld** [comment]
What's the version of your script on server?

**Comment by xxyyzz2050** [comment]
on browser: 1.0.1, on server: 1.0.3  @gera2ld

**Comment by gera2ld** [comment]
But the code you provided above shows `1.03`, which is the same as `1.3`.
Please provide a minimal reproduction, including metablocks of the script on browser and that on server.

**Comment by xxyyzz2050** [comment]
it's a typo, even that 1.3 still > 1.01

**Comment by gera2ld** [comment]
![image](https://user-images.githubusercontent.com/3139113/59256309-45604280-8c66-11e9-9222-77cb583edee1.png)

![image](https://user-images.githubusercontent.com/3139113/59256351-55782200-8c66-11e9-80b6-66747ca75d0e.png)

I followed the steps and it just worked.

**Comment by gera2ld** [comment]
Please make a reproduction and reopen it.

**Comment by codingthat** [comment]
Just saw this (following the steps in https://github.com/violentmonkey/violentmonkey/issues/572#issuecomment-500734396 ) but the refusal to update was from 0.0.1b to 0.0.1c.  When I instead set it to 1.0.0 it worked.

**Comment by tophf** [comment]
The above version strings were really quirky so maybe Violentmonkey should simply restrict the version format to [semantic versioning](https://semver.org/) which is used almost everywhere in the software industry.
