### ISSUE TITLE
Github sort Content not working in Violentmonkey (only)

### ISSUE THREAD

**Issue by MysteryIII** [violentmonkey/violentmonkey#574]
### What is the problem?
The Userscript "GitHub sort Content" by Mottie is not working in Violentmonkey. However if you use it in Tampermonkey there is no problem at all.
### How to reproduce it?
1. Install the script: https://github.com/Mottie/GitHub-userscripts/blob/master/github-sort-content.user.js
2. Go to any repository

### What is the expected result?
There should be a sort able table with all the files. 
### What is the actual result?
No changes at all.

### Environment
- Browser: Mozilla Firefox
- Browser version: 67.0.2
- Violentmonkey version: 2.10.5
- OS:Any

**Comment by gera2ld** [comment]
Short answer: change "Default injection mode" to `auto` in your settings panel.

Long answer:
It's blocked by CSP. See https://github.com/violentmonkey/violentmonkey/issues/408#issuecomment-441665795
