### ISSUE TITLE
Media doesn't open

### ISSUE THREAD

**Issue by DimoNline** [violentmonkey/violentmonkey#575]
Media doesn't open when script enabled, console prints some errors

### Environment
- Browser: Chrome
- Browser version: Last
- Violentmonkey version: Last
- OS: windows
![image](https://user-images.githubusercontent.com/19239834/59466839-f1588800-8e36-11e9-9bd1-c821a00e29e0.png)

**Comment by gera2ld** [comment]
Don't know what u r talking about... Please fill the issue template.
