### ISSUE TITLE
window.opener null with GM_openInTab

### ISSUE THREAD

**Issue by jimdonohue** [violentmonkey/violentmonkey#578]
### What is the problem?
The window.opener reference is not set when using GM_openInTab, probably related to bug #69  

### How to reproduce it?
```
// ==UserScript==
// @name         script
// @match        https://github.com/*
// @grant        GM_openInTab
// ==/UserScript==

GM_openInTab('https://example.com', true);    // window.opener is null in new window
window.open('https://example.com', '_blank'); // window.opener references this window in new window
```

### What is the expected result?
The new window should have window.opener set as a reference to the [script's] source window

### What is the actual result?
window.opener is null in the window loaded in the new tab

### Environment
- Browser: Chrome
- Browser version: 75
- Violentmonkey version: 2.10.5
- OS: Windows 10

**Comment by gera2ld** [comment]
`window.opener` is not supposed to reference the source window in such case, since `GM_openInTab` works quite differently with `window.open`.
PRs are welcome if you have a way to fix this and not breaking the existing method. 😄

**Comment by tophf** [comment]
What PRs? There's no way to fix this.
