### ISSUE TITLE
Add support to webRequest API

### ISSUE THREAD

**Issue by rodorgas** [violentmonkey/violentmonkey#583]
The WebExtension API provides the ability to block requests, which is very useful in many user cases. I'm willing to implement this feature, compatible with TamperMonkey current implementation (https://github.com/Tampermonkey/tampermonkey/issues/397).

Is this feature desirable in violentmonkey?

**Comment by tophf** [comment]
I guess the absence of any reaction means that an answer can be given only upon seeing your implementation.

**Comment by tophf** [comment]
After all, such a powerful feature definitely seems out of the scope of userscripts. Those who want this should use a [dedicated extension](https://chrome.google.com/webstore/search/webrequest?_category=extensions) or Tampermonkey.

**Comment by tophf** [comment]
We intentionally keep our userScripts implementation close to its specification. If you want to see it substantially extended then it should be a coordinated effort between all implementations, which is unrealistic in this case, particularly because webRequest is too powerful.

**Comment by Couchy** [comment]
Tampermonkey's GM_webRequest is actually more like declarativeNetRequest (the dumbed-down MV3 replacement of webRequest) but with an additional callback parameter for when a rule is triggered. I think the callback is the only thing that wouldn't work on MV3.

**Comment by vwkd** [comment]
This should be revisited. Perhaps similar to how Userscripts did it https://github.com/quoid/userscripts/issues/238
