### ISSUE TITLE
Violentmonkey breaks Firefox's XML view

### ISSUE THREAD

**Issue by gabrielfin** [violentmonkey/violentmonkey#584]
### What is the problem?
When viewing an XML file in Firefox and having any userscript active, the XML is shown as plain text instead of an XML tree. Disabling all active userscripts fixes the issue.

### How to reproduce it?
1. Create a userscript that runs on any page
2. Visit https://www.w3schools.com/xml/note.xml

### What is the expected result?
The XML file should be shown in a tree structure, with collapsable nodes, etc, like this:
![screenshot](https://user-images.githubusercontent.com/787075/60686673-9c7dbf80-9e80-11e9-94c5-7c96d5f3cd69.png)

### What is the actual result?
The XML is shown like this (it's probably being interpreted as HTML):
![screenshot2](https://user-images.githubusercontent.com/787075/60686683-aa334500-9e80-11e9-95a7-41fb04fa4f31.png)

### Environment
- Browser: Firefox
- Browser version: 68.0b14. Although its been happening for a long time. I even thought that Firefox removed the feature.
- Violentmonkey version: 2.10.5
- OS: Ubuntu 18.04

**Comment by 3v1n0** [comment]
This also breaks completely working on XML files, not only the appearance of them.

In fact, on that very page try to apply this userscript (based on https://stackoverflow.com/a/27790587/210151)
```javascript
// ==UserScript==
// @name        _XML renderer / styler
// @description stylesheet for xml results
// @include     https://www.w3schools.com/xml/note.xml
// @grant       none
// ==/UserScript==

//-- Warning, multiline str is new in JS. Only Firefox supports at the moment.
var xsl_str = `<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="html"/>
    <xsl:template match="/">
        <html>
            <head>
                <title>My super new note format!</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <style type="text/css">
                    body { padding: 0 2em; }
                    .noteCtr {
                        border: 1px solid gray;
                        border-radius: 1ex;
                        padding: 0;
                        background: #FAFAFA;
                    }
                    .messPeople { font-size: 1em; margin: 1ex 1em; }
                    .messHeading { background: lightcyan; margin: 0 1.6ex; }
                    .messHeading::after { content: ":"; }
                    .noteCtr > p {
                        background: white;
                        padding: 1em;
                        margin: 0 1em 1.5ex 1em;
                    }
                </style>
            </head>
            <body>
                <xsl:for-each select="note">
                    <div class="noteCtr">
                        <h3 class="messPeople">
                            <xsl:value-of select="from"/>
                            --&gt;
                            <xsl:value-of select="to"/>
                        </h3>
                        <h3 class="messHeading"> <xsl:value-of select="heading"/> </h3>
                        <p> <xsl:value-of select="body"/> </p>
                    </div>
                </xsl:for-each>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
`;

var processor   = new XSLTProcessor ();
var dataXSL     = new DOMParser ().parseFromString (xsl_str, "text/xml");

processor.importStylesheet (dataXSL);

var newDoc      = processor.transformToDocument (document);

//-- These next lines swap the new, processed doc in for the old one...
window.content  = newDoc;

document.replaceChild (
    document.importNode (newDoc.documentElement, true),
    document.documentElement
);
```

And this won't even load.

**Comment by szc126** [comment]
The XML file referenced in the original post is displayed correctly. However, I have found that https://ext.nicovideo.jp/api/getthumbinfo/sm9 still displays incorrectly, with concatenated text.

**Comment by gabrielfin** [comment]
Has this been shipped in 2.11.2? I'm using that version but I'm still experiencing the issue...

**Comment by gabrielfin** [comment]
@gera2ld I keep having this issue in 2.13.3
I don't think this was ever fixed for me

**Comment by tophf** [comment]
It was certainly fixed and works correctly for me ever since.
I've just verified the correct behavior in FF52, 91, and 106.

**Comment by tophf** [comment]
Indeed, XML documents don't support inline styles. 
See https://www.w3.org/Style/styling-XML.en.html
