### ISSUE TITLE
violentmonkey's GM_addStyle return promise, tampermonkey return style element

### ISSUE THREAD

**Issue by smovie** [violentmonkey/violentmonkey#585]
### What is the problem?
when delete style added by GM_addStyle, violentmonkey should use then(el=>el.remove()), tampermonkey just use remove().

### How to reproduce it?
1. 
2. 
3.

### What is the expected result?
return same type with tampermonkey

### What is the actual result?
return promise

### Environment
- Browser: firefox 
- Browser version: 68
- Violentmonkey version: 2.10.5
- OS: win7 x64

**Comment by gera2ld** [comment]
The difference in implementations leads to this result, which is as expected.

The following code works for both Tampermonkey and Violentmonkey:

```js
const style = await GM_addStyle('...');
```

**Comment by tophf** [comment]
Fixed in #620.
