### ISSUE TITLE
feature - execute code in the context of background page

### ISSUE THREAD

**Issue by Alino** [violentmonkey/violentmonkey#586]
Is this possible?
This is a feature I need, to be able to run OIDC client library in the background for different kind of userscripts so that users can authenticate from these scripts.

The reason why I cannot do this from content script, is that the OIDC server does not allow to authenticate user from any website. But the OIDC client URI could be set to
```chrome-extension://jinjaccalgkegednnccohejagnlnfdag/*```
which would allow background page to handle auth.

**Comment by gera2ld** [comment]
No, this is not possible.
Chrome and Firefox do not allow running arbitrary code in the background page because it is dangerous and out of control, making extension review useless.
IMHO you need to build an extension in such case.

**Comment by Alino** [comment]
Thank you Gerald for your reply, and for making this extension.
In case anyone is interested, in authenticating from userscripts via Oidc, I made a fork of violentmonkey where I added new API to expose the Oidc.userManager object.

https://github.com/Alino/violentmonkey/commit/c5a3aedba61ee9fd5cd1fef44726667da3fe59c3

so now I can do something like this in userscripts

```javascript
// ==UserScript==
// @name ViolentMonkey login example
// @namespace Violentmonkey Scripts
// @match http://www.dsl.sk/
// @grant GM_oidc
// ==/UserScript==

var userManager = GM_oidc(loginSettings);
console.log(userManager);
userManager.signinPopup()
    .then(() => {
        console.log('sign in success');
    }).catch((err) => {
        console.log(err);
    });
```
