### ISSUE TITLE
Export ignores "Export script data" check box

### ISSUE THREAD

**Issue by john-cj** [violentmonkey/violentmonkey#588]
### What is the problem?

Export ignores "Export script data" check box.

### How to reproduce it?
1. You have 2 scripts installed.
2. Click "Settings", disable "Export script data" check box, click "Export to zip".
3. The zip file will contain 3 files. The third one is `violentmonkey` file.

### What is the expected result?

Since "Export script data" is disabled, the zip file should contain only 2 files. Just scripts, without `violentmonkey` file.

### Environment
- Browser: Chrome
- Browser version: Version 75.0.3770.142 (Official Build) (32-bit)
- Violentmonkey version: 2.10.5
- OS: Windows 7 32-bit, without SP.

**Comment by gera2ld** [comment]
This is the expected behavior.

Script data refers to the data stored with `GM_setValue`, which should be excluded in your case.

The `Violentmonkey` file contains other meta info such as the position of scripts, whether they are enabled, whether they should be updated automatically, etc.

**Comment by john-cj** [comment]
Thanks. By the way, do you like the idea to have an option to import scripts directly from directory, instead of zip?
