### ISSUE TITLE
Indent with tabs

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#596]
Quite like #364 which introduced some configuration item for indentation with spaces.
Could we get a new setup to allow indentation with single tabulation characters?

> Indent with 🔘 2️⃣ Space characters or with 🔘 Tabulation character

**Comment by tophf** [comment]
As the [documentation says](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/) Violentmonkey doesn't want to enhance its built-in editor. Everyone misses a different feature compared to a full-fledged editor of choice.

That said, what about a text box like that for custom CSS where the users can paste a json with CodeMirror options using the values [documented on CodeMirror's site](https://codemirror.net/doc/manual.html#config)? The support cost for that is low - some type checks maybe and maybe a small list of forbidden properties. Coupled with custom CSS even CodeMirror themes would be usable easily. The use case here is an occasional quick fix or working with a really small script so you don't want to set it up in your favorite IDE.

@gera2ld, if you don't mind I could try mocking something up.

**Comment by jesus2099** [comment]
I don't remember how I did to make **Indent with Tabs** working in Violentmonkey.
If I find a settings that works, I will paste them here for next time I have to reinstall again.

**Comment by jesus2099** [comment]
Apparently, here is the settings that works:

```js
{
	"indentUnit": 4,
	"indentWithTabs": true,
	"tabSize": 4,
}
```

I don't show the other values, that are not related to **Indent with tabs.**
