### ISSUE TITLE
Make default injection setting to auto for Firefox (and still page for others)

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey#597]
Related to #173 Firefox Content Security Policy issue.

I have an example of github script that falls into that category: INSTALL-USER-SCRIPT.
Tested [this current version](https://github.com/jesus2099/konami-command/blob/d655dfc1170f76198cd9ca9cf320831336a61cc8/INSTALL-USER-SCRIPT.user.js) in https://github.com/jesus2099/konami-command/issues/447 .

This script still works in Vivaldi with Violentmonkey and on Firefox with either Greasemonkey or Tampermonkey but indeed no longer works on Firefox with Violentmonkey.

It works if I add `// @inject-into content` or `// @inject-into auto`.

But as it works with no changes on those other environments, I would expect it to work on FF+VM as well, without this specific code change.

The default injection setting is set to `page` for all browsers alike.
Wouldn't it be good to set it to `auto` for Firefox (only)?
It seems that it could maintain previous script behaviour.

**Comment by tophf** [comment]
#712 will switch to `auto` for every browser.
