### ISSUE TITLE
Support sending cookies with XHR in Firefox [Developer Edition]

### ISSUE THREAD

**Issue by dsedivec** [violentmonkey/violentmonkey#606]
## What is the problem?

Violentmonkey's `GM_xmlhttpRequest` sends cookies with the request in Chrome, but not in Firefox Developer Edition.  This prevents using APIs which require cookies (ex. APIs where the user has already logged in).  It would be nice if Violentmonkey could support sending cookies with XHR in Firefox.

In my case, it prevents me using a userscript to inject some additional information from [Jenkins](https://jenkins.io/) to our separate ticketing system.

### How to reproduce it?

Unfortunately our Jenkins instance is not accessible outside of our network, so I cannot provide a URL to it, but I will explain what I am doing.

1. Userscript such as:

```js
// ==UserScript==
// @name Jenkins status on tickets
// @namespace Violentmonkey Scripts
// @match https://ticket-server/*
// @grant GM_xmlhttpRequest
// @require https://code.jquery.com/jquery-3.3.1.min.js
// ==/UserScript==
'use strict';
/* ...get branchCell and branchName from the ticket page here... */
const uri = `https://jenkins-server/job/blah/job/${branchName}/lastBuild/api/json`;
const req = GM_xmlhttpRequest({
  method: "GET",
  url: uri,
  onload: function(response) {
    const lastBuild = JSON.parse(response.responseText);
    const resultTimeStamp = new Date(lastBuild["timestamp"]).toString();
    $(branchCell).append(`<br>${lastBuild["result"]} at ${resultTimeStamp}`);
  },
});
```

2. I log into https://jenkins-server first.
3. Now I view a ticket on https://ticket-server that triggers the above user script.

### What is the expected result?

The request is sent to jenkins-server including cookies.

### What is the actual result?

No cookies are sent with the request in Firefox.  (This same userscript works fine in Chrome+Violentmonkey, though.)

Error from Firefox add-ons debug console:

> Request to access cookie or storage on “\<URL\>” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

### Environment
- Browser: Firefox Developer Edition
- Browser version: 70.0b4 (64-bit)
- Violentmonkey version:  2.11.2
- OS: macOS 10.13.6 (17G8030)

Cross-origin request sends cookies on same box with same script using Chrome 76.0.3809.132 (Official Build) (64-bit) and Violentmonkey 2.11.2.

Note that [Greasemonkey seems to support this on Firefox using `withCredentials` as part v4's new `GM.xmlHttpRequest` function](https://github.com/greasemonkey/greasemonkey/blob/80b179bc5ecb9af12c771c998aed4e81b9ca0d74/src/bg/on-user-script-xhr.js#L125-L149).

I apologize that I haven't a reproduction URL to test this with offhand.  Anything you'd want to XHR that requires cookies to provide a proper response should make for a test URL, I'd think.

Thank you!

**Comment by tophf** [comment]
I guess we could copypaste this code from GM4 but that would require adding a `cookie` permission to manifest.json, which usually disables the extension on update until the user confirms the new permissions. It's possible to use `optional_permissions` though and make a button in the options page to grant it, which is okayish UX-wise, but first we need to confirm this trick solves this case. Someone will have to compile a patched Violentmonkey and ask the reporter to test it. @gera2ld, thoughts?

**Comment by tophf** [comment]
I wonder if it's sufficient to use the built-in XMLHttpRequet's `withCredentials` without copying the cookies explicitly... Can you try the attached modified Violentmonkey that supports widthCredentials in gmxhr, @dsedivec ? It's a dev build version (not minified/optimized) for the ease of debugging. Unpack it and don't forget to disable the main VM extension, see also the [instruction](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/).

The extension: [vm-dev.zip](https://github.com/violentmonkey/violentmonkey/files/3883633/vm-dev.zip)

And modify your code:
```js
GM_xmlhttpRequest({
  withCredentials: true,
  ..............
})
```

**Comment by qsniyg** [comment]
@tophf I haven't tried Violentmonkey, but my addon has the same issue, and adding withCredentials doesn't fix it.

Personally I just queried the cookies for that URL with the chrome.cookies API, then created a simple cookie header if it was not already specified: https://github.com/qsniyg/maxurl/commit/cef44a9f48fbb984dad22f96e5bf4c967978b2f1

**Comment by tophf** [comment]
Thanks. Looks like we'll have to implement a UI page to grant optional permissions such as `cookies` on demand from a userscript in Firefox because we definitely wouldn't want to add it to the main permissions and get the extension automatically disabled on update.

**Comment by qsniyg** [comment]
@tophf AFAIK it doesn't request any additional user permissions. I added the `cookies` permission and there was no change in users disabling my addon.

**Comment by qsniyg** [comment]
This being said (adding an extra comment as it's unrelated to the previous one), there is an issue where cookies will "leak" from non-private browsing to private browsing ([TamperMonkey faced this issue](https://github.com/Tampermonkey/tampermonkey/issues/816)).

**Comment by tophf** [comment]
Indeed, there's [no warning](https://developer.chrome.com/extensions/permission_warnings) for `cookies`, yay. Thanks for the info.
