### ISSUE TITLE
fetch request with "same-origin" fails with the directive "@inject-into content"

### ISSUE THREAD

**Issue by roger21** [violentmonkey/violentmonkey#609]
### What is the problem?

A request with the fetch API using the mode "same-origin" fails with a "same-origin" error on scripts using the "@inject-into content" directive :
`Fetch API cannot load https://forum.hardware.fr/. Request mode is "same-origin" but the URL's origin is not same as the request origin chrome-extension://jinjaccalgkegednnccohejagnlnfdag.`

The problem does not exist with Firefox or Chromium 79+ or Tampermonkey (any browser any version) or Greasemonkey.

The problem does not exist w/o "@inject-into content" or with "@inject-into page" instead.

The problem is avoided if the mode of the fetch request is omitted or changed to "cors".

The problem only exists with chromium based browsers version < 79 (and Violentmonkey).

### How to reproduce it?

1. install the script https://paste.debian.net/plainh/20f1c0ac
2. go to the page https://forum.hardware.fr/ (can be any page but it has to match the fetch request url's domain and protocol in the script).
3. wait 2 seconds and read the alert popup

### What is the expected result?

the alert should read "test fetch same origin vivaldi : OK"

### What is the actual result?

the alert reads "test fetch same origin vivaldi : ERROR"
with the error message in the console:
`Fetch API cannot load https://forum.hardware.fr/. Request mode is "same-origin" but the URL's origin is not same as the request origin chrome-extension://jinjaccalgkegednnccohejagnlnfdag.`

### Environment
- Browser: Chromium and Vivaldi
- Browser version: Chromium 77.0.3865.75 (Build officiel) (64 bits), Chromium 78.0.3901.0 (Build officiel) (64 bits), Vivaldi 2.8.1664.35 (Stable channel) (64 bits)
- Violentmonkey version: 2.11.2
- OS: win 7 64

The error does not exist on Firefox 69.0.1 (64 bits) with Greasemonkey, Violentmonkey or Tampermonkey.

The error does not exist on any version of Chromium (77, 78, 79) with Tampermonkey.

The error does not exist with Chromium 79.0.3917.0 (64 bits) or 79.0.3921.0 (64 bits) with Violentmonkey.

**Comment by tophf** [comment]
This is a known bug in Chrome which is in Chrome 79 (currently Canary), see https://crbug.com/940068.

**Comment by tophf** [comment]
In Tampermonkey your script works because TM doesn't support `@inject-into content` so it's not affected by the bug. Why are you using this FF-targeted mode in Chrome anyway?

**Comment by roger21** [comment]
i use `@inject-into content` because of the "GM bug" https://github.com/violentmonkey/violentmonkey/issues/607 it affects both browser and using `@inject-into content`fixes it

and then because the same script has to work everywhere

**Comment by tophf** [comment]
Would `@inject-into auto` work for you?

**Comment by roger21** [comment]
no, why would i take the chance of ending up into an `@inject-into page` which i know creates a major bug (still #607) ?

i switched to `cors` instead of  `same-origin` since i have full control of the url in this case, it's just as fine

thx

**Comment by tophf** [comment]
Closing since it's a bug in Chrome, which is fixed in v79 (stable channel in December, 10).
