### ISSUE TITLE
Getting "Error loading dependencies" when trying to load YADG user script.

### ISSUE THREAD

**Issue by fiskhandlarn** [violentmonkey/violentmonkey#617]
### What is the problem?
Userscript isn't installed.

### How to reproduce it?
1. Visit https://rawgit.com/SavageCore/yadg-pth-userscript/master/pth_yadg.user.js

### What is the expected result?
Script installs.

### What is the actual result?
Below the greyed-out "confirm install" button it says "Error loading dependencies."

### Environment
- Browser: Firefox
- Browser version: 69.0.1 (64-bit)
- Violentmonkey version: 2.11.2
- OS: Windows 10 Pro

**Comment by gera2ld** [comment]
I can reproduce it.

For me, it's just as the notice shows, "Error loading dependencies."
A required script (<https://yadg.cc/static/js/jsandbox.min.js>) is unable to be downloaded. The server just hangs and leads to a timeout error.

**Comment by fiskhandlarn** [comment]
@gera2ld Ah, I see. Not an issue with violentmonkey then. Thanks! 
I guess I'll wait until the dependency works again then. Closing the issue in the meantime.

**Comment by xinnnsavage** [comment]
@resource brsCSS
[↗](https://assets.aiwebextensions.com/styles/rising-stars/css/black.min.css?v=891df10#sha256-XXTVJUEWrx/FwnEXbj5DcnIjwJtFAEAp0CdT6pV1+n8=)https://assets.aiwebextensions.com/styles/rising-stars/css/black.min.css?v=891df10#sha256-XXTVJUEWrx/FwnEXbj5DcnIjwJtFAEAp0CdT6pV1+n8=
@resource wrsCSS
[↗](https://assets.aiwebextensions.com/styles/rising-stars/css/white.min.css?v=891df10#sha256-7epqkWDhCgDP7Lv/ASLvlqbOn4D5GpnGolOUl65e9j8=)https://assets.aiwebextensions.com/styles/rising-stars/css/white.min.css?v=891df10#sha256-7epqkWDhCgDP7Lv/ASLvlqbOn4D5GpnGolOUl65e9j8=

**Comment by xinnnsavage** [comment]
mine says this?
