### ISSUE TITLE
Skip running polyfills in modern browsers

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey#622]
Currently Violentmonkey spends 6-12ms on each page load of every web page on my i7 4GHz machine to [install polyfills](https://github.com/violentmonkey/violentmonkey/blob/master/src/common/polyfills.js) for features that are implemented natively since 2016 in all modern browsers. 

polyfill           | Chrome | Firefox 
-------------------|--------|--------
Object.assign      | 45     | 34
Object.values      | 54     | 47
Array.includes     | 47     | 43
Array.find         | 45     | 25
Array.findIndex   | 45     | 37
String.includes    | 41     | 40
String.startsWith | 41     | 17
String.endsWith   | 41     | 17
String.repeat      | 41     | 24

Chrome 41-45 is 2015, 54 is 2016.
Firefox 17 is 2012, 47 is 2016.

![profiler](https://user-images.githubusercontent.com/1310400/65812113-2b258280-e1cb-11e9-83d1-36f2ed86c1b1.png)

It takes more time than the actually required code of all other content scripts combined! This is a ridiculous amount of time (also half a 60fps frame) for such a trivial task, especially since it's not needed in 99.999% of cases. On a slower machine the time wasted will be bigger of course.

How we can solve it:

1. Abandon support for those presumably 0.001% of users who may still use a pre-2016 browser, but it probably requires analytics, which is frowned upon (see #602).

2. Find another, faster set of polyfills

3. Write the faster polyfills ourselves

4. Add a runtime check of `navigator.userAgent` and write it into the output script using a webpack hook. While rewriting the output is hackish, there's probably no other way to add a runtime condition to code built from a static `import`.

**Comment by gera2ld** [comment]
I am working on this. I am going to support only Chrome >= 55, Firefox >= 52 and replace Promise chains with native `async / await`.

FYI, here is the application usage data for Firefox users: https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/statistics/
I don't have one for other browsers and I don't want to spend much time on older browsers. See also #602 .

**Comment by tophf** [comment]
There's a [wrapper-webpack-plugin](https://github.com/levp/wrapper-webpack-plugin) that probably can wrap the polyfills in a check I proposed. Yay more hacks :rofl:

**Comment by gera2ld** [comment]
There is no difference if we have to wrap the code to the final package. `core-js` also checks before applying polyfills. I think we will be happier developing without considering the old browser. 😄

**Comment by tophf** [comment]
core-js performs in-depth checks while I meant to check navigator.userAgent.
