### ISSUE TITLE
@grant GM_xmlhttpRequest

### ISSUE THREAD

**Issue by Adelstone** [violentmonkey/violentmonkey#63]
Allowing this feature prevents the execution of the script. In Firefox with grease monkey my script works fine, but with violentmonkey it is not the same thing. Please test it, even the primitive script with just one console.log on window.onload doesn't work if @grant GM_xmlhttpRequest is set :-(

**Comment by gera2ld** [comment]
Works for me. Can you provide a more detailed example?

**Comment by gera2ld** [comment]
Oh, you mean `window.onload = ...` does not work? I think you should use `unsafeWindow.onload = ...`. I'll check whether this should be implemented to `window` too...

**Comment by Adelstone** [comment]
Many thanks for the prompt answer. This code doesn't work

```
// ==UserScript==
// @name        Kommentar make-up
// @namespace   germany.ru
// @version     1.6.0
// @grant       GM_xmlhttpRequest
// @match       http://*.germany.ru/newreply.pl*
// @match       http://*.germany.ru/editpost.pl*
// @match       http://*.germany.ru/newpost.pl*
// @match		http://*.germany.ru/dialog/*
// @match		http://*.germany.ru/cgi-bin/my/dialog.cgi*
// ==/UserScript==
window.onload = function(){
  console.log('!');
}
```

This code works fine 

```
// ==UserScript==
// @name        Kommentar make-up
// @namespace   germany.ru
// @version     1.6.0
// @grant       none
// @match       http://*.germany.ru/newreply.pl*
// @match       http://*.germany.ru/editpost.pl*
// @match       http://*.germany.ru/newpost.pl*
// @match		http://*.germany.ru/dialog/*
// @match		http://*.germany.ru/cgi-bin/my/dialog.cgi*
// ==/UserScript==
window.onload = function(){
  console.log('!');
}
```
I am using Violentmonkey v1.6 with Opera 39.0.2256.48
As you see the only difference is the @grant attribute.
