### ISSUE TITLE
Add Support to GM_notification API

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#65]
Documentation https://tampermonkey.net/documentation.php#GM_notification

This API show desktop notification to user. The difference between this one to `Notification` is that this API do not need grant permission from user.

Monkeys | Status
----|----
Greasemonkey | greasemonkey/greasemonkey#1194 (Not sure if it will be added)
Tampermonkey | _(Yes)_

(This API is first introduced by Scriptish.)

**Comment by gera2ld** [comment]
supported since v2.5.0
