### ISSUE TITLE
与dexie.js似乎有兼容性问题

### ISSUE THREAD

**Issue by vanjoge** [violentmonkey/violentmonkey#659]
### 测试代码如下

```html
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match https://www.baidu.com/
// @grant        GM_getValue
// @require https://unpkg.com/dexie@2.0.4/dist/dexie.js
// ==/UserScript==

(function () {
    'use strict';
  let db = new Dexie("tmpcache"); 
  db.version(1).stores({ cache: "key, html, ts" });
  db.cache.get("a", function (data){
    console.log(data);
  });
})();
```

去掉// @grant GM_getValue 后不再报错，

tampermonkey没有问题。

### 环境
- Browser:chrome73 firefox69
- Violentmonkey version: v2.11.2
- OS: win10

**Comment by tophf** [comment]
@gera2ld we can probably hook Object.defineProperty and defineProperties in injected-web to suppress this error.

**Comment by gera2ld** [comment]
@tophf It's easier to just add `configurable: true` to `Object.defineProperties`.

**Comment by tophf** [comment]
Wouldn't it defeat the purpose of sandboxing?

**Comment by tophf** [comment]
I meant configurable:true will allow the page to undo the traps set by defineProtectedProperty.
