### ISSUE TITLE
Sync error with Google Drive

### ISSUE THREAD

**Issue by mwisnicki** [violentmonkey/violentmonkey#667]
### What is the problem?
Syncing to Google Drive errors out every time

### How to reproduce it?
1. Install VioletMonkey
2. Connect to Google Drive
3. Accept authorization
4. Wait for sync to complete ("Sync will start soon...")

### What is the expected result?
Never got that far but probably should say OK

### What is the actual result?
Sync error!

### Environment
- Browser: Chrome
- Browser version: 78.0.3904.70 (Official Build) (64-bit)
- Violentmonkey version: 2.11.2
- OS: Windows 10

**Comment by mwisnicki** [comment]
I haven't seen anything in the webtools console on VioletMonkey extension page but I'm guessing the code executes in some different context.

**Comment by tophf** [comment]
Try inspecting the [background page console](https://stackoverflow.com/a/10258029).

**Comment by mwisnicki** [comment]
Thanks, that was useful:

```
index.js:1 Ready to sync: Google Drive
index.js:1 Failed syncing: Google Drive
index.js:1 TypeError: Cannot read property 'info' of undefined
    at index.js:1
```

and I saw 2 successful requests:

1. https://www.googleapis.com/oauth2/v3/tokeninfo
2. https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&fields=files(id%2Cname%2Csize)

The latter responded with

```
{
 "files": []
}
```
