### ISSUE TITLE
Updates aren't applied until restarting the browser

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#673]
### What is the problem?

For some reason, the userscripts don't get updated until the browser/profile is restarted. I've had a browser profile running for almost a month now, and scripts aren't updated, but right after restarting the browser, they are all updated (they've been updated multiple times throughout the month).

### How to reproduce it?
1. Update a userscript
2. Wait a few days (sometime after the update interval)
3. The userscript still isn't updated in Violentmonkey, but after restarting the browser, it will be updated

### What is the expected result?
The scripts are updated as new updates are found

### What is the actual result?
The scripts are not updated until the browser is restarted

### Environment
- Browser: Chrome
- Browser version: 77.0.3865.90
- Violentmonkey version: 2.11.2
- OS: Linux

**Comment by tophf** [comment]
Sounds like a caching problem.
Maybe VM should set no-cache headers: https://stackoverflow.com/a/48969579/

**Comment by gera2ld** [comment]
@qsniyg Did you try a click on "Check all for update"? I'm not sure if this is an issue related to the timers.

**Comment by qsniyg** [comment]
@gera2ld "Automatically check scripts for updates every day" is enabled, if that's your question

**Comment by gera2ld** [comment]
@qsniyg I mean click "Check all for updates" button manually.
![image](https://user-images.githubusercontent.com/3139113/68120790-2f1e9000-ff41-11e9-99f6-cf7379433770.png)

The automatic check relies on a timer and the timer might be unreliable in some circumstance. So I want to make sure if this is the problem here.

**Comment by qsniyg** [comment]
@gera2ld Yes, clicking that button updates the userscripts for me.

**Comment by qsniyg** [comment]
Seems to work properly now! Just got a notification, haven't touched the browser at all.

**Comment by gera2ld** [comment]
@qsniyg That's because the extension is updated and restarted. The problem is not fixed yet and some more investigation is needed.

**Comment by qsniyg** [comment]
Ah okay, thanks for letting me know.

**Comment by qsniyg** [comment]
Unless Violentmonkey was updated yesterday and today (just a few minutes ago), I received update notifications for scripts I have installed, so I believe this is fixed.
