### ISSUE TITLE
Pressing "Check all for updates" breaks the extension interface

### ISSUE THREAD

**Issue by Dooogurt** [violentmonkey/violentmonkey#68]
I've been having this issue for a while using the most recent versions of Violent Monkey for Opera and Google Chrome. When you manually press "Check all for Update' It'll break the extension interface. For instance. This is before pressing it. 
![violentmonkey_-_google_chrome_2016-10-29_06-48-26](https://cloud.githubusercontent.com/assets/10239012/19828998/1d1173de-9da4-11e6-8b14-fc896b7348a9.jpg)

This is after it, it happens when you go to the settings menu, then back to  installed scripts
![violentmonkey_-_google_chrome_2016-10-29_06-48-46](https://cloud.githubusercontent.com/assets/10239012/19829004/3a584e68-9da4-11e6-9793-305f20fd162f.jpg)

Also the scripts used to say if they were updating or there wasn't an update, now the installed script doesn't say a thing, although you can still edit the scripts via its button.

**Comment by gera2ld** [comment]
Thanks for the detailed report.
