### ISSUE TITLE
Web page stuck using GitHub Dark script

### ISSUE THREAD

**Issue by KaKi87** [violentmonkey/violentmonkey#683]
### What is the problem?

The web page is stuck when [GitHub-Dark-Script](https://github.com/StylishThemes/GitHub-Dark-Script) is installed and activated.

### How to reproduce it?
1. Install GitHub Dark Script
2. Load any GitHub page
3. Observe

### What is the expected result?

The web page loads properly.

### What is the actual result?

The web page is stuck, the browser and/or the system could crash on low configurations.

### Environment
- Browser: Brave
- Browser version: 0.70.122
- Violentmonkey version: 2.12.0
- OS: Ubuntu 18.04.3

Also confirmed on :
- Arch Linux, Firefox 69.0b7
- Ubuntu 18.04, Firefox 70.0.1
- Chromium

[Related issue](https://github.com/StylishThemes/GitHub-Dark-Script/issues/72)

Thanks

**Comment by tophf** [comment]
Bisected to a8a4e016. The issue is caused by `gm4-polyfill.js`, which apparently gets confused by the new return format of GM_addStyle. Removing it fixes the bug. I'll see what we can do to prevent the bug in VM.

**Comment by tophf** [comment]
The simplest fix is to add `GM.addStyle` alias, which we didn't add because it's not GM4-compatible. Thoughts, @gera2ld?

**Comment by tophf** [comment]
Temporary workarounds:
* remove `@require ........gm4-polyfill.js`
* replace `GM.addStyle(` call with `GM_addStyle(`

**Comment by tophf** [comment]
Actually it'd be nice to release an additional Violentmonkey beta in the web store. As evidenced by the experience with other extensions, there are thousands of people who like to install bleeding edge stuff and help test it.

**Comment by gera2ld** [comment]
Should be fixed in v2.12.1.
