### ISSUE TITLE
GM_setClipboard() has stopped working

### ISSUE THREAD

**Issue by ua7** [violentmonkey/violentmonkey#685]
### What is the problem?
I feel like GM_setClipboard() has stopped working.
Is this a bug or is this the intended specification?
Personally, I hope GM_setClipboard() will be kept.

### How to reproduce it?
1.use GM_setClipboard("foo") in any userscript

### What is the expected result?
foo is copied to the clipboard

### What is the actual result?
Nothing happens

### Environment
- Browser: Firefox Dev x64
- Browser version: 71.0b7
- Violentmonkey version: 2.12.0
- OS: Windows7 x64

**Comment by tophf** [comment]
Indeed, doesn't work in FF, but works in Chrome. Investigating.
