### ISSUE TITLE
[Suggestion][Firefox] Wrap code of userscript in try..catch when using injection into the content context

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#692]
When using `@inject-into content` mode in Firefox, it is difficult to debug scripts, since errors are not displayed in the console. But this can be solved by using try..catch:
```
try {
    // code of userscript
} catch (e) {
    console.error("==UserScript==", e);
}
```

**Comment by tophf** [comment]
Gee, what a delight, Firefox doesn't display the errors in content scripts and it's a known bug https://bugzil.la/1410932 which hasn't been fixed for many years so it would make sense for VM to do what you suggest, indeed.
