### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [violentmonkey/violentmonkey#693]
Nit: https://addons.mozilla.org/addon/violentmonkey/versions/2.12.1/updateinfo/ and other update pages are empty, and so we don't see release notes at AMO. 

Maybe publish notes to AMO in the future? 

In the meantime I see https://github.com/violentmonkey/violentmonkey/releases

Thanks

**Comment by gera2ld** [comment]
I didn't notice there was such a feature in AMO. 😂See mozilla/addons#1135

**Comment by grahamperrin** [comment]
Looking forward to notes for 2.12.4

TIA
