### ISSUE TITLE
[Suggestion][Firefox] Assign window.wrappedJSObject to unsafeWindow when using injection into the content context

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#702]
This will allow userscripts to access the global scope of page.

**Comment by tophf** [comment]
I'm not sure it's a good idea and not just because wrappedJSObject is Firefox-only, but because `unsafeWindow` always belongs to the real context of the userscript, which is the **content script's** `window` in case of `@inject-into content`. Userscripts may want to access all three contexts individually.

**Comment by tophf** [comment]
On the other hand it'd be super convenient for normal userscripts that only need the page context, but the user specified the global injection mode as `content` in VM settings.

**Comment by sn260591** [comment]
It will also improve compatibility with old userscripts written for greasemonkey3.

**Comment by tophf** [comment]
>It will also improve compatibility with old userscripts written for greasemonkey3.

Yes, that's what I meant in my second comment above.

**Comment by tophf** [comment]
@gera2ld what if the injection mode selector will have a third item `auto, wrap` or `auto, wrappedJSObject` that's shown only in FF? The explanation will be added in the linked page. As for `@inject-into`, maybe add `auto,wrap` and `content,wrap` values.

**Comment by gera2ld** [comment]
@tophf Good idea. I think we can add a Firefox only mode `wrap`, listing them in `@inject-into` and picking the first one that works.

```js
// Try `page` first; if not working, try `wrap` if in Firefox; finally fallback to `content`
// @inject-into page wrap content
```

BTW, I think `auto` could be an alias for `page wrap content` as described above, since it was designed to try to access the real `unsafeWindow`.

**Comment by gera2ld** [comment]
This change causes problem (#733) that can hardly be fixed. So we will remove it in the next version. 😅
