### ISSUE TITLE
Can't reorder on Firefox for Android (and other touch device)

### ISSUE THREAD

**Issue by pingu8007** [violentmonkey/violentmonkey#720]
### What is the problem?
Can not reorder on touch device

### How to reproduce it?
1. Install Firefox for Android
2. Install some scripts
3. Long press/swipe/press and drag/whatever

### What is the expected result?
Show button to reorder/Drag and drop to reorder

### What is the actual result?
Nothing happen

### Environment
- Browser: Firefox for Android
- Browser version: 68.2.1
- Violentmonkey version: 2.12.1
- OS: Android 9

**Comment by tophf** [comment]
Same in Chrome on Android (e.g. Yandex or Kiwi). I've tried using `pointermove` and `pointerup` events but it didn't help. Maybe the entire drag'n'drop code should be simplified using the standard `drag*` events.

**Comment by tophf** [comment]
Ah, some progress: `touch*` events can be used successfully.
