### ISSUE TITLE
最新版（2.12.1）脚本又被iframe屏蔽了

### ISSUE THREAD

**Issue by smzh369** [violentmonkey/violentmonkey#723]
### What is the problem?
在*://www.huya.com/*上运行的脚本被页面内的iframe屏蔽
```
// ==UserScript==
// @name         虎牙免登陆（修复版）
// @namespace    https://greasyfork.org/
// @version      1.1.1
// @description  虎牙免登陆看高清
// @author       smzh369
// @match        *://www.huya.com/*
// @grant        none
// @require      http://code.jquery.com/jquery-1.7.2.min.js
// ==/UserScript==

(function() {
  console.log(document);
  $(document).ready(function(){
    $('#player-login-tip-wrap').remove();
    VPlayer.prototype.checkLogin(true);
  });
})();
```

### How to reproduce it?
打开虎牙直播任一页面

### What is the expected result?
之前一直到2.11.2都是正常的

### What is the actual result?
在2.12.1下所有在*://www.huya.com/*上运行的脚本都失效了，如果把地址改为*://*.huya.com/*可以发现脚本会运行在页面内的iframe里。试过改inject-mode无效。

### Environment
- Browser:firefox
- Browser version:70
- Violentmonkey version:2.12.1
- OS:win10 1903

**Comment by tophf** [comment]
FWIW I didn't understand the description as I don't speak the language but it looks like a typical case of conflicting jQuery version because the site is using jQuery 1.11.1. The correct fix is to use [jQuery.noConflict()](https://api.jquery.com/jQuery.noConflict) or to simply remove `@require` line.

**Comment by smzh369** [comment]
> 
> 
> FWIW I didn't understand the description as I don't speak the language but it looks like a typical case of conflicting jQuery version because the site is using jQuery 1.11.1. The correct fix is to use [jQuery.noConflict()](https://api.jquery.com/jQuery.noConflict) or to simply remove `@require` line.

Thank you for your reply but it's not the jQuery's matter. It is similar to #394

**Comment by machsix** [comment]
my script works fine on the website

**Comment by Crystal-RainSlide** [comment]
Equivalent without jQuery, for testing and for anyone who need it:

``` JavaScript
(function() {
  console.log(document);
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('player-login-tip-wrap').remove();
    VPlayer.prototype.checkLogin(true);
  });
})();
```

**Comment by tophf** [comment]
@Crystal-RainSlide could you explain to me how do I use it to reproduce the bug? Like what should I see and what happens instead. Because at this point it's unclear to me how this entire issue report is specific/related to Violentmonkey.

**Comment by Crystal-RainSlide** [comment]
@tophf I'd like to make further help, but I never use huya.com, and thus know a little about this. This user script seems to remove a limition that only logined users may view the video in higher resolution. But, after some exploration on huya.com with a clean Firefox profile, I didn't found any iframes on its video pages and didn't meet any limitions on video resolution. 🤔

**Comment by tophf** [comment]
Ah, thanks, hopefully it'll help.

**Comment by tophf** [comment]
Nope, it doesn't.

**Comment by smzh369** [comment]
Oh, I forgot this...But it seems OK now in 2.12.4

**Comment by smzh369** [comment]
> 
> 
> @tophf I'd like to make further help, but I never use huya.com, and thus know a little about this. This user script seems to remove a limition that only logined users may view the video in higher resolution. But, after some exploration on huya.com with a clean Firefox profile, I didn't found any iframes on its video pages and didn't meet any limitions on video resolution. 🤔 And I'm sure I don't have a account.

Thank you for your investigation. The limit only works when you watch a live video more than 10 min.
But never mind, now it's fine in 2.12.4
