### ISSUE TITLE
huge size js isnt supported to be edit or shown

### ISSUE THREAD

**Issue by GoogleBeEvil** [violentmonkey/violentmonkey#724]
### What is the problem?
huge size js isnt supported to be edit or shown

### How to reproduce it?
1.https://github.com/the1812/Bilibili-Evolved   this script is about 1.45 mb， while install it via vm，nothing shown  on  the installing page，and you can not edit anything
2.https://github.com/the1812/Bilibili-Evolved/issues/158  issue related

### Environment
- Browser:firefox
- Browser version: v69.0.1
- Violentmonkey version: AMO currrent version
- OS:win 10

**Comment by gera2ld** [comment]
It seems to be a network problem. I waited for a few minutes and finally everything came out and worked.
To make sure what the real problem is, you could try download it first and then install from local file.

**Comment by tophf** [comment]
Works for me *immediately* in the `master` branch. Fixed by #718.

**Comment by GoogleBeEvil** [comment]
No,I do not think it's net work matter,just something else for i up load
the scripts to greasyfork and install from greasyfork,the same result
,waiting 30 min ,nothing is  loaded just blank page.have test my
network,isnt GFWED
BTW:copy and paste the scripts to vm editor to create local scripts,it does
work well .

**Comment by GoogleBeEvil** [comment]
OK,seem to wait until the new version on amo
