### ISSUE TITLE
[Suggestion] Use monaco editor for script editing?

### ISSUE THREAD

**Issue by maple3142** [violentmonkey/violentmonkey#725]
https://microsoft.github.io/monaco-editor/
Monaco editor is the text editing component used in vscode, and it can be easily used on webpages.
I think it is good enough to replace current editor. Any thoughts?

**Comment by tophf** [comment]
It's a huge behemoth, megabytes of code even in minified form. Simply use your favorite local IDE and keep the installation tab open as described in the built-in hint in the editor: https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/

**Comment by tophf** [comment]
Actually a dupe of #363.
