### ISSUE TITLE
2.12.2 break the sites v2

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#735]
GitHub - Unable to edit your posts in Issues.
Yandex Disk - Unable to go to folder / archive

Reproduced. Breaks the specified sites with the mode of injection "auto" and "page". Regardless of the activated scripts, you can do without scripts.

**Comment by wvxwxvw** [comment]
I'm not a scriptwriter or a programmer. I found out by multiple tests. Understand further on your own.

**Comment by gera2ld** [comment]
Closing as duplicate of #733
