### ISSUE TITLE
Стили оформления для Violentmonkey

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#737]
Where can I get CSS for Violentmonkey?
Dark background, light font. Colors I can fix myself, it would be something to start from.

**Comment by tophf** [comment]
A simple built-in dark theme switch will be implemented one day (probably soon): #456.

* [SuperOP535](https://github.com/SuperOP535/Violentmonkey-Theme)
* [ShadowFox](https://github.com/overdodactyl/ShadowFox)
* [tophf](https://gist.github.com/tophf/cc109b0ba5cb98353c9ea51579c85ae2) - this one changes the layout heavily

**Comment by wvxwxvw** [comment]
Thanks. All right. I'll try to edit your style, otherwise the buttons are closed with text in the menu.

And ShadowFox did not work for me, neither with Chrome nor from the extension settings.
