### ISSUE TITLE
Ctrl-F search stops working; no Ctrl-G search-again; etc.

### ISSUE THREAD

**Issue by filbo** [violentmonkey/violentmonkey#74]
1. Go to VM console, "Installed scripts" tab, click 'Edit' to edit a script.  Click inside the script text, then hit Ctrl-F.  Search for something; it works.

Click 'Close' in the lower right corner to return to the list of installed scripts.

Click 'Edit' to edit the script again; click inside the script text; hit Ctrl-F.  Nothing happens.

Hit Ctrl-R to reload the tab, 'Edit', Ctrl-F -- it works again.  Until next time you close or save-and-close the script.

Some related smaller bugs:

2. If you click outside the script text, e.g. in the grey area near the words "Script Editor", Ctrl-F instead invokes the browser's "search in page", which can't find the script contents.  (Also: Ctrl-F, type something, hit Enter, Ctrl-F again -- focus has shifted and you again get browser's search.)

3. Neither browser- nor Violentmonkey-search can find the line numbers displayed for the script.

4. Ctrl-G "search again for what I just searched for" seems not to be implemented.

5. I expect Ctrl-Shift-F to mean "search for what I am about to type, backwards"; and Ctrl-Shift-G "search for what I last searched, backwards".  

6. Ctrl-F always empties the search field: would like it to come up with the previous value all-selected so that typing would replace it, but clicking (to unselect) and typing would not.  Also should not immediately search for that resurrected value (that's for Ctrl-G).

... and now, looking at *.js, I see this stuff is implemented by CodeMirror and apparently intends to provide Ctrl-G, Ctrl-Shift-G, but somehow doesn't....

**Comment by gera2ld** [comment]
Thank you very much for the description.

1,2,4 confirmed. 5 partially confirmed and needs inspection since such hotkeys might be captured by the browser before the page can handle it. (e.g. C-S-F on Chrome on Mac OS)

3 is as expected.

6 can be an enhancement.

Actually, the editor is never designed to edit scripts in the browser. It was designed just to view scripts. If you need to edit scripts locally a lot, it's highly recommended to edit a local file with your preferred editor, then drag the script file into browser, checking the *tracking* option.


![1](https://cloud.githubusercontent.com/assets/3139113/20821447/8368df5c-b87d-11e6-8e8c-46d7459c21fb.png)

**Comment by filbo** [comment]
That "Track local file" option looked interesting, but the wording is utterly unclear as to what it might do.  Apparently, bind an already existing file to VM's attention?  Or, immediately stash the edit buffer into that file and subsequently track it?  Where is a good description of this?

I find in-script-manager editing incredibly convenient for a rapid development cycle.  Using an external editor would disrupt somewhat, even though the internal editor is light years away from what I'd really want.  So, would prefer to fix it as much as is doable, even if I'm technically following the "wrong" path...

I should add (to my litany of editor whines):

7. When file lines are insanely long (like: minified _Vue_ or the like, all shoved onto 1-3 lines of up to 32KiB) -- scrolling up and down through them is very laggy.  There's like a 1-2 second lurch on my dev machine (a 1-lung Core i3-2310M laptop).

FOR tracking purposes, would you like me to punch out any of these into separate "issues"?  Which #s?

**Comment by filbo** [comment]
Can 3 also be an enhancement?  It's almost like it's taunting me, displaying line numbers which are completely inactive, not beneficially usable...

The CodeMirror code has a tunable key binding system.  Is there a way to actually make use of that in VM -- a way (besides making my own private build of VM) to inject an alternative set of bindings into my setup?  I could probably fix a couple of my issues with just that.
