### ISSUE TITLE
Set firstPartyDomain to null in cookies.getAll

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#746]
In https://github.com/violentmonkey/violentmonkey/commit/335bf9660799a298b8776e98fca1e04533d8204a#diff-c6e107c9d095d5cc5e885f66b1458c82R204, `firstPartyDomain` is unset, which causes it to fail in TOR Browser (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies)

I was notified of it here on my addon: https://github.com/qsniyg/maxurl/issues/170. My fix was just to add `firstPartyDomain: null` to the cookies.getAll request: https://github.com/qsniyg/maxurl/commit/39a8ab1ccfeaa9eef204dfe55d47205676d1c80d

**Comment by tophf** [comment]
Great, thank you!

**Comment by tophf** [comment]
@gera2ld I see you're here, so who will fix this - you or me?

**Comment by gera2ld** [comment]
You can fix it now if you have time 😄 . I don't have time on this until night.
