### ISSUE TITLE
All scripts don't work when change user agent in firefox

### ISSUE THREAD

**Issue by BUG-P** [violentmonkey/violentmonkey#750]
### What is the problem?

all the scripts don't work when change user agent in firefox

### How to reproduce it?
1. about:config->change devtools.responsive.userAgent string
2. install [this extension](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) then change user agent 

### console log
~~~
Error: Permission denied to access property "cmd" website_name:1:3380
    onHandle website_url:1
    c website_url:1
    d moz-extension://scripts_id/injected.js:1
    d moz-extension://scripts_id/injected.js:1
    g moz-extension://scripts_id/injected.js:1
    P moz-extension://scripts_id/injected.js:1
    AsyncFunctionNext self-hosted:839
~~~
### Environment
- Browser: Firefox
- Browser version: 68.3.0esr
- Violentmonkey version:v2.12.3
- OS:windows 10

**Comment by tophf** [comment]
We should use browser.runtime.getPlatformInfo(), I guess.

**Comment by gera2ld** [comment]
> We should use browser.runtime.getBrowserInfo(), I guess.

Sounds reasonable, but only Firefox supports it, we need to fallback to `userAgent` in other browsers.
