### ISSUE TITLE
Unable to update, edit or delete userscript

### ISSUE THREAD

**Issue by Glandos** [violentmonkey/violentmonkey#757]
### What is the problem?
I am able to install a userscript, but once it is installed, it is impossible to edit and delete it. Update also fails.

### How to reproduce it?
1. Install Violentmonkey on a fresh profile
2. Install https://greasyfork.org/scripts/23602-tout-mz/code/Tout_MZ.user.js
3. Try to edit the script using internal editor and save

### What is the expected result?
The save should be ok.

### What is the actual result?
I have a popup saying `{}`.

The browser console shows the following errors:
```
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:1009:17
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
```

### Environment
- Browser: Firefox
- Browser version: 71.0
- Violentmonkey version: 2.12.3
- OS: Debian/sid

**Comment by tophf** [comment]
I can't reproduce neither in Linux Mint nor in Windows.
I don't have Debian though.

@Glandos, try reproducing in a portable Firefox. I suspect you may have some `about:config` setting that causes the problem because the error messages are about some internal Firefox code, not from Violentmonkey.

**Comment by Glandos** [comment]
Thanks for your time. It was linked to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946249 It was a compiler bug. Now It's fixed.
