### ISSUE TITLE
userscripts compatiable issue

### ISSUE THREAD

**Issue by GoogleBeEvil** [violentmonkey/violentmonkey#762]
some scripts doesnt work with VM,
https://greasyfork.org/zh-CN/scripts/31207-贴吧显示真实id  as example. there should be an option but on VM,it's missing and the main function of the scripts is broken

http://tieba.baidu.com/p/6397077946 as the test page
the main function is show the true username or id （imwilliamwang in that post） not the nick name（王知鱼）
### Environment
- Browser: firefox 71
- Violentmonkey version:AMO LATEST current 2019-12-18
- OS:Windows 10

**Comment by tophf** [comment]
Seems to work for me.
At least the result is identical in Violentmonkey and Tampermonkey both in Chrome/Firefox:
![image](https://user-images.githubusercontent.com/1310400/71055854-2b00a780-2168-11ea-8c59-19600bf2d02b.png)

**Comment by GoogleBeEvil** [comment]
network problem 
closed
