### ISSUE TITLE
get browser info in user scripts

### ISSUE THREAD

**Issue by Alino** [violentmonkey/violentmonkey#763]
Is there an API to check browser inside user scripts?
for example 
```javascript
if (browser == 'firefox') {
// do stuff
}

**Comment by tophf** [comment]
There is none currently so you'll have to use various indirect methods (look for examples yourself) or rely on navigator.userAgent, which is unreliable, of course, as it can be overriden.

@gera2ld what about exposing this info (via GetInjected) as `GM_info.platform` object: `{ browser, version, os, arch }`, all fields are strings.

**Comment by Alino** [comment]
thank you for reply, and for considering this as an enchantment. I have already [checked some indirect methods](https://www.gregoryvarghese.com/how-to-get-browser-name-and-version-via-javascript/) before. But was just curious if this can be done nicely within an API, so that the user scripts don't have to include this function in its code.

**Comment by gera2ld** [comment]
`GM_info.platform` is a good idea but I'm afraid we cannot get all those fields in a reliable way. Maybe we can just give the information provided by [browser.runtime.getBrowserInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo).

**Comment by tophf** [comment]
My idea was to expose the info from both getBrowserInfo and getPlatformInfo which we already use in the background page.

**Comment by machsix** [comment]
There is no need to add this function in userscript manager. `navigator.userAgent` gives you useragent. If you need more complex functions. there are tons of npm package like

- browser-detect
- detect-browser

You can use webpack to bind the package into your userscript. The first one can even be directly "required".

**Comment by Alino** [comment]
maybe it's correct to not to implement this natively within an API, also due to script compatibility with other greasemonkey alternatives.

**Comment by tophf** [comment]
> There is no need to add this function in userscript manager. `navigator.userAgent` gives you useragent

Wrong. Other extensions can and do override the userAgent string in the page context so it's totally unreliable there. And even in content mode, the useragent string may be changed to pretty much anything while debugging the tab in devtools mobile-compatible mode.

The point of `GM_info.platform` is to expose the info obtained from the specialized API in the background page context of the extension that's not affected by the above factors.
