### ISSUE TITLE
[Firefox] window.wrappedJSObject is undefined if the userscript has any grant.

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#765]
1. Install script:
```
// ==UserScript==
// @name Grant Test
// @grant GM_info
// ==/UserScript==
console.log("window.wrappedJSObject:", typeof window.wrappedJSObject);
```
2. Open https://github.com

In the console there will be a message:
`window.wrappedJSObject: undefined`

If set the `@grant` field to none or delete it, then the userscript works as it should:
`window.wrappedJSObject: object`

**Comment by tophf** [comment]
When a valid `@grant` is present and it's not `none`, the `window` object is a userscript wrapper so AFAIK this is working as intended. You should use `unsafeWindow.wrappedJSObject` in this case.

Note, wrappedJSObject is exposed by Firefox only in `content` injection mode:

```js
// @grant       GM_info
// @inject-into content
```

**Comment by tophf** [comment]
OTOH I don't have a preference as I don't use this feature so let's mimic Greasemonkey4 or Tampermonkey. Someone who's interested in solving this should run the tests there...

**Comment by tophf** [comment]
Turns out FF doesn't expose `wrappedJSObject` via `Object.getOwnPropertyNames` at all so I guess it means we should explicitly add it. Also GM4 sets `unsafeWindow` to `window.wrappedJSObject` which AFAIK breaks the old scripts that don't properly use cloneInto() as we recently learned.

**Comment by laniakea64** [comment]
Hi, I'm seeing what looks like this same issue in Violentmonkey 2.12.8rc14, Firefox 80.0, new profile.

Test script:
```
// ==UserScript==
// @name Grant Test
// @inject-into content
// @grant GM_info
// ==/UserScript==
console.log("window.wrappedJSObject:", typeof window.wrappedJSObject);
```

As in the original description, changing grant to `@grant none` makes `window.wrappedJSObject` accessible again.

**Comment by tophf** [comment]
@laniakea64 I can't reproduce the problem neither in VM2.17 nor in RC.

**Comment by tophf** [comment]
@laniakea64 oh I see it in RC, but not in VM2.17, thanks.

**Comment by laniakea64** [comment]
I confirm that a `yarn build:firefox` from latest git fixed this issue.  Thanks @tophf for the fast fix! :smiley:
