### ISSUE TITLE
如何屏蔽或绕过页内alert？

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#776]
某网站，如果服务器满了，点击会alert，导致后续userjs无法执行。
这个alert似乎是经过服务器判断的，不能通过改写点击按钮绑定函数解决。
```
window.alert = function(a) {
  console.log.call(this, a);
};
```
我尝试了上面这段代码，没用。类似的也没用。
如果最前面加上 const 或 let 就会导致更多的破坏。

**Comment by tophf** [comment]
You need `@grant none`

```js
// ==UserScript==
// @name foo
// @grant none
// ==/UserScript==
window.alert = console.log;
```

or `unsafeWindow`

```js
unsafeWindow.alert = unsafeWindow.console.log;
```

**Comment by maple3142** [comment]
https://violentmonkey.github.io/api/metadata-block/#run-at
Maybe this would work.

**Comment by ivysrono** [comment]
I found this: https://stackoverflow.com/questions/42686055/how-to-dismiss-alert-in-firefox-webextensions
Do not support firefox?

**Comment by tophf** [comment]
No, Violentmonkey doesn't use `chrome.debugger` so it's not related.

**Comment by gera2ld** [comment]
@ivysrono can we close this now?

**Comment by ivysrono** [comment]
Although not successful, thank you all.
