### ISSUE TITLE
@require vs pasted scirpt into UserScript

### ISSUE THREAD

**Issue by Tithen-Firion** [violentmonkey/violentmonkey#78]
I wrote small `xhrHijacker`. When I [@require](https://greasyfork.org/pl/scripts/26654-netflix-subtitle-downloader?version=170159) it my UserScript fails. But when I just [paste it into my UserScript](https://greasyfork.org/pl/scripts/26654-netflix-subtitle-downloader?version=171060) - everything works fine.

**Comment by gera2ld** [comment]
That's because your hijacker code ends with `}` and the next piece of code starts with `(`, which makes them executed as a function call. I'll fix this soon.

A workaround is to add a `;` at the end of your code.
