### ISSUE TITLE
window vs unsafeWindow vs globalThis

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#782]
What to use inside VM script to access global object?
Please explain the difference.

**Comment by tophf** [comment]
It depends on which context you want to access and how your userscript is injected (`@inject-into` mode). There are many good explanations/tutorials for unsafeWindow/window, here's a random one I've just googled up: https://stackoverflow.com/a/10828021. As for `globalThis`, it's just an alias for `window` in case of userscripts.

**Comment by soviet-man** [comment]
I use `auto` mode.

**Comment by tophf** [comment]
I can't help further without actual specifics like the code/site and so on. For general info on unsafeWindow you can find a tutorial: https://www.google.com/search?q=unsafeWindow+vs+window
