### ISSUE TITLE
An option to have only 1 version of a script

### ISSUE THREAD

**Issue by john-cj** [violentmonkey/violentmonkey#784]
A kind of feature request.

My scripts are stored in a regular directory on my computer. For example, `c:\userscripts`. When I add them to Violentmonkey, I end up with 2 versions of the script: the first version stored in `c:\userscripts` and the second version is stored in Violentmonkey.

It is quite confusing because it is easy to forgot whether any difference between these 2 versions, and which version is the most up-to-date.

Here is a draft of my idea:

1. You drag your script from the file manager to Violentmonkey dashboard.
2. Alongside with "Edit", "Disable", and "Refresh" buttons, there should be another one -- "Local". When you press this button, the script becomes ... local (duh!). Such scripts could be viewed in Violentmonkey, but not edited. The edit field should be slightly dimmed. On the other hand, the script should immediately reflect any changes introduced to it in `c:\userscripts`.

So, to edit your script, you need to open it locally on your file system, edit, and that's it! And you will be free from "2 versions issue".

**Comment by tophf** [comment]
Direct access to file system is tricky in WebExtensions - it won't work in Firefox and requires user consent in Chrome where it'll grant the entire computer's file system to an extension so this is not something that users should enable normally. A simple solution will come once the Native FileSystem API is implemented and enabled for extensions which could happen this year, who knows. We'll see.

The only cross-browser solution would be to support NiklasGollenstede's native-ext, see #423.
As for Chrome-only solution it's tracked in #430.

Right now you can use a local web server. See also [How to edit scripts with your favorite editor?](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/) if you haven't already.
