### ISSUE TITLE
How to empty trash bin?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#785]
I moved some unneeded userscripts to trash bin but I can't see how I can empty it.

**Comment by tophf** [comment]
Currently there's no such function: the scripts are removed automatically.
I guess we should add a button to empty the bin to match the common UI norms.

**Comment by soviet-man** [comment]
Automatically? How does this happen?

**Comment by tophf** [comment]
After 7 days.

**Comment by soviet-man** [comment]
I don't have any message about it although it is important.

**Comment by tophf** [comment]
![image](https://user-images.githubusercontent.com/1310400/71872810-8d791200-312e-11ea-9324-19a01ee2c3c1.png)

**Comment by soviet-man** [comment]
![изображение](https://user-images.githubusercontent.com/33825590/71873087-59522100-312f-11ea-9ea1-ae1793dfe249.png)

Translation into English 
"Removed scripts will be kept until cleared"

**Comment by tophf** [comment]
I see there's a new translation on transifex:
![image](https://user-images.githubusercontent.com/1310400/71876592-23fe0100-3138-11ea-860e-082294b90efb.png)

@gerald, how do you fetch from transifex? I don't see such a command in package.json

**Comment by soviet-man** [comment]
Can I switch between different languages of UI?

**Comment by tophf** [comment]
Extensions use the browser's language.

**Comment by gera2ld** [comment]
> @gerald, how do you fetch from transifex? I don't see such a command in package.json

Not implemented yet. I'll look into this later, maybe add another action.
