### ISSUE TITLE
Possible port for Microsoft Edge?

### ISSUE THREAD

**Issue by kowith337** [violentmonkey/violentmonkey#79]
Have any plan for release to Microsoft Edge?
Wish to see, even just for side-load test.
Because I'm not satisfy to use TM (Any platform).

**Comment by bershan2** [comment]
@kowith337 Microsoft Edge only recently got support for extensions at all (with the Creators Update, which not everyone has) and [many API functions are missing](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs).

**Comment by franklinyu** [comment]
@bershan2 I think it may help to keep a list of those missing features that we need, so that we know when we can begin porting to Edge (and we can also vote and feedback to Microsoft).

**Comment by danmarshall** [comment]
I was able to install into the new Edge Insider, from the Chrome store :)  so, maybe no further work will be needed once the new Edge is released.

**Comment by kowith337** [comment]
Sorry about not update this isue for a while.

In case if MS directly use Chromium for new Edge, all chrome add-ons will more (or fully) compatible to use.

**Comment by tophf** [comment]
Edge is now Chromium-based so it should run Violentmonkey as is.
