### ISSUE TITLE
How to use "webRequest" and "webRequestBlocking" API in userscripts ?

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#80]
@gera2ld VM already has the permissions to use those. As the title suggests, I want to use those two chrome APIs in a userscript. How do I do that ?

**Comment by gera2ld** [comment]
They are not supposed to be used directly from a script. The scripts should use `GM_*` [APIs](https://wiki.greasespot.net/Greasemonkey_Manual:API) and not care about how they are implemented.

I think you might create an extension to use Chrome APIs directly.

**Comment by uBlock-user** [comment]
Nevermind, I found what I was looking for.
