### ISSUE TITLE
"Export to zip" outputs .txt file of the .zip file

### ISSUE THREAD

**Issue by KLaurence** [violentmonkey/violentmonkey#812]
### What is the problem?
It's simply a problem with ViolentMonkey exporting wrongly. When you export scripts to a .zip file, as Violentmonkey allows so in the extension's options, the file that the extension exports that should apparently have the .zip extension instead have the .txt extension. Changing the extension of the resulting .txt file to .zip results in a valid .zip file, containing the .user.js files of the scripts as well as what I can only guess is the current options Violentmonkey is set at.

### How to reproduce it?
1. Export scripts to a .zip file.

### What is the expected result?
Violentmonkey exports a .zip file.

### What is the actual result?
Violentmonkey exports a .txt file.

### Environment
- Browser: Google Chrome
- Browser version: 79.0.3945.130
- Violentmonkey version: v2.12.4
- OS: Windows

**Comment by gera2ld** [comment]
It seems that the latest Chrome changes the extension to `.txt` if blob type is not set correctly.
