### ISSUE TITLE
Chromium Edge: Stuck on authorizing Google Drive 

### ISSUE THREAD

**Issue by JackieKu** [violentmonkey/violentmonkey#815]
# What is the problem?

Cannot sync scripts from Google Drive with Chromium based Edge.

### How to reproduce it?
1. Select Google Drive and click Authorize.
2. Grant the access from the popup page. 

### What is the expected result?

It should start syncing.

### What is the actual result?

It kept showing "Authorizing".

This log seems to relevant:
```
index.html:1 Uncaught (in promise) Object
index.js:1 POST https://www.googleapis.com/oauth2/v4/token 400
(anonymous) @ common.js:1
g @ common.js:1
(anonymous) @ index.js:1
Promise.then (async)
loadData @ index.js:1
authorized @ index.js:1
checkAuth @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
index.html:1 Uncaught (in promise) {url: "https://www.googleapis.com/oauth2/v4/token", data: {…}, xhr: XMLHttpRequest, status: 400}
Promise.then (async)
checkAuth @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```
```json
{error: "invalid_grant", error_description: "Malformed auth code."}
```

[xhr_token.har.txt](https://github.com/violentmonkey/violentmonkey/files/4082245/xhr_token.har.txt)

### Environment
- Browser: Edge 
- Browser version: 79.0.309.68 (Official build) (64-bit)
- Violentmonkey version: 2.12.4
- OS: Windows 10 18363

**Comment by tophf** [comment]
If the same works in Chromium/Chrome then it must be a bug in Edge. Can you verify that? Because if that's so, maybe we can't fix it or rather maybe it's something that should be reported and fixed in Edge itself to benefit everyone.

**Comment by tophf** [comment]
Also make sure your system time is correct as it's one of the [common failure reasons](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35).

**Comment by JackieKu** [comment]
> If the same works in Chromium/Chrome then it must be a bug in Edge. Can you verify that? 
Just reinstalled the Chrome to verify it. It worked fine.

> Also make sure your system time is correct

The time is correct.

**Comment by tophf** [comment]
Some progress: turns out Edge encodes the `code` URL parameter twice. Investigating further...
