### ISSUE TITLE
WebDAV Sync button is disabled

### ISSUE THREAD

**Issue by leewdch** [violentmonkey/violentmonkey#823]
### What is the problem?
WebDAV Sync button is disabled

### What is the expected result?
I'm not able to test for successful connection to my local webdav

### What is the actual result?
Sync button remains disabled even after filling all the info (ip, user, pass)
I tried using cadaver on a WSL session from another computer and it connected without issues

### Environment
- Browser: Firefox
- Browser version: 72.0.1
- Violentmonkey version: v2.12.4
- OS: Windows 10

**Comment by tophf** [comment]
The URL currently should be in the form of `http://host/` - it must end on `/` and start with a scheme. I'm working on a fix right now to make it more human-friendly...
