### ISSUE TITLE
[Feature request] Top-level await

### ISSUE THREAD

**Issue by kkocdko** [violentmonkey/violentmonkey#833]
<https://github.com/tc39/proposal-top-level-await>

This can reduce some redundant code.

Just replace `(()=>{})()` with `(async()=>{})()` in `/src/injected/web/load-scripts.js`.

Should I take a PR?

**Comment by tophf** [comment]
It's still a Stage-3 proposal: https://github.com/tc39/proposal-top-level-await
Currently it's not even implemented in Chrome: https://crbug.com/1022182
So we'll wait for the above unless other monkey engines implement this.

**Comment by kkocdko** [comment]
OK, I wait.

**Comment by tophf** [comment]
So it's shipped both in Chrome (still not in stable though) and Firefox and now we can enable it I guess, but maybe we should wait until it's enabled at least in Tampermonkey so people don't start publishing non-working scripts. WDYT @gera2ld?

**Comment by gera2ld** [comment]
I think top-level await may be helpful to small userscripts using asynchronous functions. That being said, it's not so necessary because it does not make a big difference when there are no ES modules, for instance in userscripts as we don't need to wait for imports.

A simple implementation I can think of would be just to wrap all scripts with `(async () => { ... })()`, which seems to be a trivial change. It's good to me if it does not break the injection of normal scripts.

> maybe we should wait until it's enabled at least in Tampermonkey so people don't start publishing non-working scripts

I think it's the script authors' responsibility to test their scripts in different script managers. Even now we are not 100% compliant with Tampermonkey, for example, we support `context` as a global variable while they don't.

**Comment by tophf** [comment]
Rereading the specification I see it's a thing for modules that **does not work in normal scripts**:

> Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

So we should not implement it.

**Comment by darkred** [comment]
> maybe we should wait until it's enabled at least in Tampermonkey so people don't start publishing non-working scrip

I just wanted to mention that Tampermonkey has implemented (experimentally) top-level await support  
in its latest Chrome+Firefox betas 4.12.6123, published a week ago.
Available by default, no need to manually enable a specific setting.

**Comment by tophf** [comment]
Maybe TM's developer didn't read the specification just like I didn't initially. Now that I did, implementing it doesn't make much sense to me.

**Comment by darkred** [comment]
> Maybe TM's developer didn't read the specification

You are probably right. I don't see a related issue in the TM repo either.
In order to facilitate the discussion, I'm kindly cc'ing TM developer, @derjanb, in case he'd like to share his opinion on this.

**Comment by darkred** [comment]
I'd like to mention that in today's TM beta version [4.12.6124](https://www.tampermonkey.net/changelog.php?version=4.12.6124&ext=gcal&show=gcal), 
the feature still exists, and it's now configurable (enable/disabled) in Settings:

> Make top-level await support configurable

![2020-12-31_130937](https://user-images.githubusercontent.com/723651/103408018-774b3980-4b69-11eb-9939-73a2d6c451f9.jpg)

**Comment by darkred** [comment]
Here is a yesterday's [tweet](https://twitter.com/SpiderMonkeyJS/status/1380533609669480448) via the SpiderMonkeyJS twitter account regarding Firefox 89 *(currently in Nightly)* :

> Top Level Await has landed in Firefox 89 🎉 expect to see it on release (assuming all goes well) in May!
> 
> More details here:
> https://spidermonkey.dev/blog/2021/04/05/top-level-await-ships.html

**Comment by darkred** [comment]
Here is the related info by TM's author who replied to my question [here](https://github.com/Tampermonkey/tampermonkey/issues/1236#issuecomment-860446451) :

> The actual use case is something like your example script. It is no longer necessary to wrap the code in an asynchronous function.
> 
> I understand that Tampermonkey's top-level await support doesn't fit into any of the specs mentioned, but none of those specifies a userscript environment. Userscripts in Tampermonkey are always wrapped into a function (which now has the async attribute), and this is something that userscript authors need to be aware of in any case.
> 
> Therefore top-level await provides more flexibility while not breaking things. The option to disable it was only added to provide a workaround if problems become obvious.

**Comment by tophf** [comment]
The author of Tampermonkey implements a lot of functions unilaterally thus segregating the field and making the code non-portable. Right now this feature is an edge case for a few enthusiasts who don't care about backward compatibility. I don't see the need to implement it until it becomes widely used.

**Comment by essential-existence** [comment]
Hello. I think it would be very convenient. In node.js, this has been implemented for a long time, along with es-modules

**Comment by tophf** [comment]
Top-level await is only for ES modules, so we should not enable it by default.

**Comment by tophf** [comment]
On the other hand, we can add an option in each script's settings (not a global one), disabled by default, with a warning.

**Comment by mon-jai** [comment]
@tophf Maybe adding ES6 module support as well?

**Comment by tophf** [comment]
>Maybe adding ES6 module support as well?

It's impossible to implement even conceptually.

**Comment by mon-jai** [comment]
@tophf Maybe we could bundle babel/swc and compile userscripts to conformant syntax?

Input:

```js
import $ from "https://esm.sh/jquery"

const response = await fetch("https://www.example.com/")
const text = await response.text()

$("div").text(text)
```

Output:

```js
(async () => {
  const { default: $ } = await import("https://esm.sh/jquery")

  const response = await fetch("https://www.example.com/")
  const text = await response.text()

  $("div").text(text)
})()
```

**Comment by tophf** [comment]
Dynamic import is a special case because it is available in normal scripts by definition i.e. it doesn't require any special treatment in Violentmonkey. Note that such import will fail on a site with a strict CSP.

**Comment by tophf** [comment]
BTW I haven't yet seen a convincing usage example of top-level await for userscripts. Awaiting an import is an anti-example.

**Comment by scarf005** [comment]
> > Maybe adding ES6 module support as well?
> 
> It's impossible to implement even conceptually.

> Awaiting an import is an anti-example.

hi, could i get an insight with the reason on
1. why ES modules are impossible for userscripts, and
2. why awaiting imports cannot be an usage example for top-level awaits?

**Comment by tophf** [comment]
> ES modules are impossible for userscripts

API for userscripts such as `chrome.userScripts` or `chrome.scripting` doesn't support ES modules.

> why awaiting imports cannot be an usage example for top-level awaits

Because it can take a very long time, like a second or even more in some cases, so the effect of the userscript's main code will be noticeably delayed. Userscripts already have `@require` and `@resource` for this purpose which are locally cached.

**Comment by tophf** [comment]
Found one sensible example: the script should only run after an element is detected via MutationObserver.

VM 2.19.2+ will support `// @top-level-await` in the metablock.

**Comment by karlhorky** [comment]
I wanted to try this out today, and saw that `2.19.0` is the latest version published in [the Chrome Web Store](https://chromewebstore.google.com/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)

![Screenshot 2024-07-07 at 15 13 14](https://github.com/violentmonkey/violentmonkey/assets/1935696/cedd8480-c1dc-419b-9609-336b2e4f80e2)


When is it planned to publish `2.19.2` or newer?

**Comment by tophf** [comment]
You can use it in [beta](https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg) or install it as an [unpacked extension](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by karlhorky** [comment]
Now that `2.20.0` is in [the Chrome Web Store](https://chromewebstore.google.com/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag), I gave it a try, with adding [`// @top-level-await`](https://github.com/violentmonkey/violentmonkey/issues/833#issuecomment-2185016529), and it's working 🙌 

PR here if you're interested in the code:

- https://github.com/karlhorky/userscripts/pull/43
