### ISSUE TITLE
[Feature Request] Linting in the editor

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#836]
My suggestion is to have **linting** in the editor. 

My linter of choice is **ESLint**. I prefer ESLint over JSHint way more. 
Also [ESLint is far more popular than JSHint](http://www.npmtrends.com/jshint-vs-eslint).  

Note that, in order ESLint to work, [you need to specify a configuration file](https://eslint.org/docs/user-guide/getting-started), 
[something that's not necessary with JSHint](http://jshint.com/docs/).

For comparison: 
- Greasemonkey doesn't offer linting, 
- Tampermonkey offers ESLint but partially (with "partially" I mean, that: 
    - without using a config file, i.e. after a TM fresh install, many/most errors covered by ESLint's "recommended" rules are not highlighted in the editor, and 
    - using a config file (in TM Settings|Editor|'Custom Linter Config'), is currently mostly ignored._

P.S. Thank you for work with Violentmonkey! 
It's always great to have more alternatives, especially with userscript managers!

**Comment by tophf** [comment]
Linters are huge: JSHint is 500kB minified, ESLint is ~3MB.
The entire Violentmonkey package is 1.3MB while our own JS code is only 0.2MB.

Given that the preferred method of editing in Violentmonkey is [to use an external editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/), I don't think a linter larger than say 100kB minified will ever be added and there are no such linters, but let's see what gera2ld thinks...

**Comment by gera2ld** [comment]
I think this is not likely to be integrated due to the huge size and little benefit.
Maybe I'll create an online editor someday, based on monaco so that we can get plenty of amazing features from VSCode, as well as many userscript-only features.

But for now, if the question is whether to integrate such features into Violentmonkey locally, the answer is no.

**Comment by edswangren** [comment]
> Linters are huge: JSHint is 500kB minified, ESLint is ~1MB minifed (in Tampermonkey at least). Compare that to the entire Violentmonkey package: 1.3MB minified, own JS code being only 0.2MB.
> 
> Given that the preferred method of editing in Violentmonkey is [to use an external editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/), I don't think a linter larger than say 100kB minified will ever be added and there are no such linters, but let's see what @gera2ld thinks...

I understand this is old but I still feel the need to point out how absurd it is to believe this and say it unironically.  ffs, honestly.

**Comment by tophf** [comment]
@edswangren, you have achieved your goal of annoying me, so please don't do it anymore.
