### ISSUE TITLE
Supplrt URI Templates

### ISSUE THREAD

**Issue by KOLANICH** [violentmonkey/violentmonkey#838]
https://tools.ietf.org/html/rfc6570

**Comment by tophf** [comment]
Is this something you want to add to `@matches` or maybe even an additional meta key? Which other monkey engines support that? How is this even related to Violentmonkey or userscripts in general? What advantages will it offer? Right now I don't see any reason to support this.

**Comment by KOLANICH** [comment]
>Right now I don't see any reason to support this.

In fact neither do I since everyone already uses regexps and this syntax is more limited than regexps. Though the drawback of regexps is that I have to escape dots and other special characters.

**Comment by tophf** [comment]
Then we'll only implement this if other engines do.
