### ISSUE TITLE
Please add support for Firefox using Webextension api

### ISSUE THREAD

**Issue by AlexBeLi** [violentmonkey/violentmonkey#84]
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)

**Comment by AlexBeLi** [comment]
Some incompatibilites related with deprecation chrome.api.getDetails()
https://bugs.chromium.org/p/chromium/issues/detail?id=111354
https://github.com/zacyu/bilibili-helper/pull/247/files

**Comment by gera2ld** [comment]
Thanks, @AlexBeLi 👍

**Comment by gera2ld** [comment]
closed via release [v2.5.8](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.5.8)

**Comment by AlexBeLi** [comment]
Thanks, all works great:) Maybe it make sense to add addon on addons.mozilla.org?

**Comment by gera2ld** [comment]
@AlexBeLi just received a mail from addons.mozilla.org, rejected. 😞 There are some security issues to be dealt with.

**Comment by uBlock-user** [comment]
@gera2ld they also removed the extension from the addon page, says not found on addons.mozilla.org

**Comment by AlexBeLi** [comment]
Mozilla is very strange organization. They add Webextension API and this good, but they remove support XUL what lead to deprecating many addons such as CTR (409 333 users) , DownThemAll (1 179 944 users),  etc. 
"It’s fascinating how Mozilla manages to always find the exactly right words — to make their most avid browser enthusiasts feel absolutely miserable!" nmaier

**Comment by zJelly** [comment]
The extension appears on mozilla's site now (as of this post): https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
But when I click install, Firefox tells me the extension is corrupt.

**Comment by r-a-y** [comment]
I've tried 2.6.3 via Chrome Store Foxified and it works fine in FIrefox 53.

One issue I'm seeing is the "Export to zip" function doesn't work.  If I click on the button, the button momentarily greys out and comes back to normal, but I do not see a prompt to save the file.

**Comment by AlexBeLi** [comment]
Maybe make sense to add Development Channel on AMO like [https://addons.mozilla.org/ru/firefox/addon/ublock-origin/](https://addons.mozilla.org/ru/firefox/addon/ublock-origin/)?

**Comment by gera2ld** [comment]
Finally approved.
