### ISSUE TITLE
Blob URLs don't work on incognito tabs anymore

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#843]
### What is the problem?

Blob URLs don't work on incognito tabs after https://github.com/violentmonkey/violentmonkey/commit/e203a9da1134d09ca69d6e093b3b9b383df8353d

### How to reproduce it?

```
// ==UserScript==
// @name        XHR blob test
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       GM_xmlhttpRequest
// @version     1.0
// @author      -
// ==/UserScript==

GM_xmlhttpRequest({
  url: "https://www.google.com/",
  method: "GET",
  responseType: "blob",
  onload: function(resp) {}
});
```

### What is the expected result?

No errors on incognito tabs

### What is the actual result?

```VM5605 injected.js:1388 GET blob:chrome-extension://jgmllhakjkdpjncdmabfibgjompbhpai/a54b8bff-d2cb-42a0-811c-a4800abff831 net::ERR_FILE_NOT_FOUND```

There aren't any errors on non-incognito tabs though.

### Environment
- Browser: Chromium
- Browser version: 79.0.3945.130
- Violentmonkey version: Latest git (https://github.com/violentmonkey/violentmonkey/commit/e21da6f3faea1836baf3c3db5ddd1ba3a2ebbb3e)
- OS: Linux

**Comment by tophf** [comment]
Yeah, Chrome doesn't allow extensions to access their own chrome-extension:// URLs in incognito, I forgot about that. I guess we'll have to send the blob as a string in 64MB (or lesser) chunks.
