### ISSUE TITLE
window.close() feature

### ISSUE THREAD

**Issue by invollt** [violentmonkey/violentmonkey#85]
Please add **window.close()** feature, which works with **// @grant   window.close**
It is currently exists in TamperMonkey, but I prefer ViolentMonkey.

**Comment by jsEveryDay** [comment]
Its not worth it... Chrome hates it.
Even if TamperMonkey has managed to come up with a fix, count the days until next chrome update... to be disabled. So would you write a script that may or may not work in a few days?

**Comment by gera2ld** [comment]
Actually Chrome extension does have the permission to close a tab. I think we can support it if there is no security concerns.
