### ISSUE TITLE
Some problem with page codding

### ISSUE THREAD

**Issue by OmTatSat** [violentmonkey/violentmonkey#851]
# What is the problem?
At some pages, script refuse work normal, and start give numbers instead of words
Example page http://russiahousenews.info/health/sol-zhizn-lechenie

### How to reproduce it?
1. Install
[Enhanced word highlight.txt](https://github.com/violentmonkey/violentmonkey/files/4145014/Enhanced.word.highlight.txt)

2. open https://www.google.com/search?client=firefox-b-e&sxsrf=ACYBGNSLEmpoxOfyI2AY9skiA_Mtjfz-DQ%3A1580670480394&ei=EB43XozaF6uWjga2zq7oDg&q=%D0%B8%D0%B7%D0%BE%D1%82%D0%BE%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D1%80%D0%B0%D1%81%D1%82%D0%B2%D0%BE%D1%80+russiahousenews.info&oq=%D0%B8%D0%B7%D0%BE%D1%82%D0%BE%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D1%80%D0%B0%D1%81%D1%82%D0%B2%D0%BE%D1%80+russiahousenews.info&gs_l=psy-ab.3...15717.20261..20688...0.4..0.651.885.2-1j5-1......0....2j1..gws-wiz.......0i71j33i160.oyMIlLybEZg&ved=0ahUKEwiMovazyLPnAhUri8MKHTanC-0Q4dUDCAo&uact=5
3. open http://russiahousenews.info/health/sol-zhizn-lechenie

### What is the expected result?
![Соль жизни_ Белое спасение от белой смерти - russiahousenews info_health_sol-zhizn-lechenie - Mozilla Firefox 02-02-2020 в 21 23 53](https://user-images.githubusercontent.com/25341911/73613876-8694d080-4602-11ea-9f17-8cd0e1dfe1f0.PNG)

### What is the actual result?

![Соль жизни_ Белое спасение от белой смерти - russiahousenews info_health_sol-zhizn-lechenie - Mozilla Firefox 02-02-2020 в 21 10 03](https://user-images.githubusercontent.com/25341911/73613749-526ce000-4601-11ea-9084-42f3cb231b32.PNG)

page without script
![Соль жизни_ Белое спасение от белой смерти - russiahousenews info_health_sol-zhizn-lechenie - Mozilla Firefox 02-02-2020 в 21 13 47](https://user-images.githubusercontent.com/25341911/73613748-526ce000-4601-11ea-96c2-cd82588289be.PNG)
When i change page coding in saved webpage, script works fine. Also script works fine at this page, when using Greasemonkey. Also when using Tampermonkey script has this bug too.

### Environment
- Browser: Firefox
- Browser version: 68.4.2esr x64
- Violentmonkey version: v2.12.4
- OS: win10 x64

**Comment by tophf** [comment]
There's no bug in Chrome.

In Firefox the bug disappears if you add `// @inject-into content` to the metadata block of the script or switch the global injection mode to `content` in advanced settings of Violentmonkey. This mode is exactly what Greasemonkey uses.

This fact makes me think it's either a bug in the site itself or in Firefox. Either way I have no idea how to fix it and I can't really spend more than a few minutes in FF's devtools as it's just unbearably painful to use when debugging userscripts and extensions.

**Comment by OmTatSat** [comment]
> 
> 
> There's no bug in Chrome.
> 
> In Firefox the bug disappears if you add `// @inject-into content` to the metadata block of the script or switch the global injection mode to `content` in advanced settings of Violentmonkey. This mode is exactly what Greasemonkey uses.
> 
> This fact makes me think it's either a bug in the site itself or in Firefox. Either way I have no idea how to fix it and I can't really spend more than a few minutes in FF's devtools as it's just unbearably painful to use when debugging userscripts and extensions.

Wow, I’ve been suffering for several months, I’ve been trying to solve the problem for 2 days, and you decided it in a couple of seconds!) Cool, many thanks!

**Comment by tophf** [comment]
Er, I see it in Chrome as well... it means I can investigate it!

**Comment by OmTatSat** [comment]
> Er, I see it in Chrome as well... it means I can investigate it!

Great, i will be glad to fix this bug for good.  But i can use already suggested fix without pain)

**Comment by tophf** [comment]
Nailed it: the site uses `mootools.js` which adds `test` method on strings which fools the userscript into thinking it's a RegExp. This is why switching to `content` injection mode fixes the problem as this mode fully isolates all JavaScript from the page unlike the lightweight sandbox imitation of Violentmonkey/Tampermonkey.

The proper fix is to replace `w.test` with `w instanceof RegExp` in the userscript's line 416.

**Comment by OmTatSat** [comment]
> Nailed it: the site uses `mootools.js` which adds `test` method on strings which fools the userscript into thinking it's a RegExp. This is why switching to `content` injection mode fixes the problem as this mode fully isolates all JavaScript from the page unlike the lightweight sandbox imitation of Violentmonkey/Tampermonkey.
> 
> The proper fix is to replace `w.test` with `w instanceof RegExp` in the userscript's line 416.

So fast! You are like superman!) 
Replaced w.test with w instanceof RegExp . And it works like a charm.
I like to know, are there any side effects of using // @inject-into content
In case some similar will happen with another scripts)

**Comment by tophf** [comment]
> are there any side effects of using // @inject-into content

See https://violentmonkey.github.io/posts/inject-into-context/

**Comment by OmTatSat** [comment]
> See https://violentmonkey.github.io/posts/inject-into-context/
Ok, i see limitations, thank you very much fo your help! I wish you good luck!
