### ISSUE TITLE
onclose don't work at tab close

### ISSUE THREAD

**Issue by OmTatSat** [violentmonkey/violentmonkey#857]
# What is the problem?
onclose don't work
### How to reproduce it?
let tabControl = GM_openInTab(url);
tabControl.onclose = () => GM_setValue(ST_PRE, '');

### What is the expected result?
ST_PRE is blank
### What is the actual result?
ST_PRE have value that it have before tab close

### Environment
   - Browser: Firefox
   - Browser version: 68.4.2esr x64
   - Violentmonkey version: v2.12.4
   - OS: win10 x64

**Comment by tophf** [comment]
1. The code is incomplete and thus invalid so I can't reproduce the problem
2. `onclose` is actually getting sent as I can see by using `console.log`

**Comment by OmTatSat** [comment]
1. [onclose.txt](https://github.com/violentmonkey/violentmonkey/files/4158025/onclose.txt)
2. How i can see console.log?

Step to recreate:
1. open https://www.google.com/search?client=firefox-b-e&q=test
word highlight ui must show test
2. close tab
3. open https://2ip.ua/ru/services/ip-service/speedtest
word highlight ui must not show
but, it is show word highlight ui with word test in it.
It is stored in ST_PRE, and must be blanked on tab close
`let tabControl = GM_openInTab(url);
tabControl.onclose = () => GM_setValue(ST_PRE, '');`

**Comment by tophf** [comment]
I won't be debugging your entire script again so you need to make a small script that demonstrates the problem.

> How i can see console.log?

```js
tabControl.onclose = () => console.log('closed');
```

**Comment by OmTatSat** [comment]
> I won't be debugging your entire script again so you need to make a small script that demonstrates the problem.

// ==UserScript==
// @name           test Enhanced word highlight_without_update
// @namespace      http://userscriptssssss.org/users/86496
// @description    Enhanced keywords highlight for Search Engines and All !
// @include        http://*
// @include        https://*
// @include        file://*
// @noframes
// @exclude        http://maps.google.com/*
// @exclude        http://kinosvit.tv/*
// @run-at         document-idle
// @grant          GM_log
// @grant          GM_xmlhttpRequest
// @grant          GM_getValue
// @grant          GM_setValue
// @grant        GM.notification
// @grant    GM_addValueChangeListener
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @version        1.5.9
// ==/UserScript==


GM_setValue('testName', 'id6');

let tabControl = GM_openInTab(url);
tabControl.onclose = () => GM_setValue('testName', '');
 

1. Open any site, we have testName with id6
2. Close tab, we still have testName with id6, testName is not blanked with onclose

**Comment by tophf** [comment]
This is still an invalid script because `url` is not defined. And I don't see how you check the value is blank. If I use a valid url string I see the value being blanked successfully.

```js
GM_setValue('testName', 'id6');
console.log('start', GM_getValue('testName'));

document.body.onclick = () => {
  let tabControl = GM_openInTab('https://www.example.org');
  tabControl.onclose = () => {
    GM_setValue('testName', '');
    console.log('closed', GM_getValue('testName'));
  };
};
```

**Comment by OmTatSat** [comment]
I checked the value here 
![test Enhanced word highlight_without_update - Violentmonkey - Mozilla Firefox 02-05-2020 в 12 01 35](https://user-images.githubusercontent.com/25341911/73831740-7c93ed00-480f-11ea-91e1-caf6605b0eef.PNG)
I see, it is worked, but i want it worked in another way. How we can use onClose without opening new tab?

**Comment by tophf** [comment]
There's no way and I don't understand what you want. See the [documentation for GM_openInTab](https://violentmonkey.github.io/api/gm/#gm_openintab):

>onclose [...] will be called when the opened tab is closed.

Anyway there's no bug here.
