### ISSUE TITLE
Slovak language cannot be load

### ISSUE THREAD

**Issue by kubalav** [violentmonkey/violentmonkey#860]
Slovak language cannot be load due wrong language code.
current code: `sk_SK`
required code: `sk`

If I create "sk" folder with translation file, it's working.

**Comment by tophf** [comment]
chrome.i18n [says](https://developer.chrome.com/extensions/i18n#overview-locales) it supports [webstore's locales](https://developer.chrome.com/webstore/i18n#localeTable) and there's only `sk`.
Is there a reason VM uses `sk_SK`, @gera2ld?

**Comment by gera2ld** [comment]
Sorry I didn't know the difference between them. I'll fix this soon.

**Comment by tophf** [comment]
Judging by the commit log it's related to Transifex, they probably use the long code.
