### ISSUE TITLE
Steam Economy Enhancer userscript: problem with latest update and Firefox

### ISSUE THREAD

**Issue by Floyd77** [violentmonkey/violentmonkey#861]
### What is the problem?
Steam Economy Enhancer userscript for Firefox is broken with version 2.12.5. This bug was reported [here](https://github.com/Nuklon/Steam-Economy-Enhancer/issues/144), several users can reproduce it.

### How to reproduce it?
1. Update to version 2.12.5 for Firefox
2. Update to version 2.12.5 for Chrome
3. Install and try the userscript on both browsers.

### What is the expected result?
It should work as it does on 2.12.4. I downgraded to confirm.

### What is the actual result?
The script freezes the entire inventory on Firefox.

### Environment
- Browser: Firefox
- Browser version: 72.0.2
- Violentmonkey version: 2.12.5
- OS: Windows 7 x64

**Comment by tophf** [comment]
I don't use steam so I can't reproduce the bug. Could you post a detailed instruction with preferably publicly available URLs that I can open and what the page should look like (a screenshot)?

**Comment by tophf** [comment]
Ah, I think I found [one](https://steamcommunity.com/profiles/76561198006363388/inventory/) myself and I see the delay.

**Comment by Floyd77** [comment]
> 
> 
> I don't use steam so I can't reproduce the bug. Could you post a detailed instruction with preferably publicly available URLs that I can open and what the page should look like (a screenshot)?

I did not think about it but yes, you need a Steam account to check all the features by yourself, because that userscript only works with the user inventory. I think you could also check the script with any public inventory available. [Sample profile](https://steamcommunity.com/id/Myrsan/inventory/) (taken from [this list](https://steamdb.info/badges/?badgeid=13)).

If you want to try all the features you can [create a test account](https://store.steampowered.com/join/) or I can do it for yourself and send it to you, whatever you wish. Thanks.

**Comment by Floyd77** [comment]
> 
> 
> Ah, I think I found [one](https://steamcommunity.com/profiles/76561198006363388/inventory/) myself and I see the delay.

That's it, if you could check it with Chrome you will see how it should work and how it worked with previous version on Firefox too.

**Comment by tophf** [comment]
Debugging extension's page scripts in Firefox is almost entirely impossible so I can't even say if it's a bug in Firefox's implementation of Proxy or not... The error displayed in the console says "too much recursion" and shows thousands of nested `extend` calls used by some jQuery library. I've already tried blindly rearranging various parts of our wrapper Proxy but so far unsuccessful. Well, in the worst case we can revert Proxy at least in Firefox.

**Comment by tophf** [comment]
Geeee, nailed it. Firefox returns `[object Object]` on our window proxy so jquery.ui starts cloning its recursive properties like `self` and `window`. Chrome returns `[object Window]` so I guess it's a bug in Firefox. Gonna upload a fix soon.

**Comment by Floyd77** [comment]
Thanks a lot!
