### ISSUE TITLE
Chrome Dev, no longer overriding functions from within violentmonkey with GM_** enabled

### ISSUE THREAD

**Issue by kazkas1234** [violentmonkey/violentmonkey#866]
### How to reproduce it?
Let's say website has a function like this in source files that does something:
function Something () {console.log("Something")}

We can usually override that function like this:
Something = () => {console.log("This is mine now")}

However after recent Chrome Dev edition update this is no longer possible when // @grant        GM_xmlhttpRequest (or any other GM_ command I believe) is enabled. But overriding still works when it isn't.

However it still works fine with Tampermonkey or when using older Chrome.

### What is the expected result?
function changes to whatever it's being told to change
### What is the actual result?
nothing changes
### Environment
- Browser: Chrome Developer Edition
- Browser version: Version 81.0.4044.9 (Official Build) dev (64-bit)
- Violentmonkey version: v2.12.6
- OS: W10 x64

**Comment by tophf** [comment]
Post a complete script please, otherwise this sounds like the intended and perfectly correct behavior whereas the old one was definitely a bug.

**Comment by ivysrono** [comment]
when not using `@grant none`,we can use 
```
window.eval(`unsafeWindow.Something = 'blabla';`))
```
However, we can not use `GM_*` in eval? @tophf

**Comment by tophf** [comment]
@ivysrono no it doesn't work and it shouldn't work. Sites can also block eval by their CSP. Anyway, there's no need for `eval`: the correct method is `unsafeWindow` as shown in my comment above.
