### ISSUE TITLE
[Feature Request] Expose in the UI the @require and @resource externals

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#869]
My suggestion is to be able to view the `@require` and `@resource` files that are loaded with userscripts, in an extra tab named "Externals", i.e.: `Code | Settings | Values | Externals`. 

This way the user will be able to directly check whether the relevant `@require`/`@resource` files are actually existent, and also be able to inspect the `@require` contents. Like Tampermonkey.

Additionally this will facilitate in offering an option in ViolentMonkey
to also check for updates for the `@require` Externals (i.e. not only for the scripts themselves), 
and to view in the "Externals" tab the date each such file was last updated.

Thank you!

**Comment by tophf** [comment]
Just because TM has something doesn't mean we should copy it. For example in all the years of using and writing userscripts I've viewed an external script just once in nits UI. I also don't see the usefulness of a separate update option.

What we can and should do, at the very least, is to list the URLs of those externals that failed to load, probably both a) in the editor after saving and b) in the dashboard e.g. as a clickable error link on a script card.

**Comment by darkred** [comment]
First of all, thanks for the quick response.

> Just because TM has something doesn't mean we should copy it. For example in all the years of using and writing userscripts I've viewed an external script just once in its UI. 

Just to be clear, I'm not asking this feature just because I'm used to it in TM.
And, I agree with your that being able to view externals doesn't facilitate in writing scripts.

But, as user of any script, incl.my own, I think it's useful to know that the require/resource files are indeed currently loaded ok in VM, and view their size: 
*for reference [here](https://github.com/Tampermonkey/tampermonkey/issues/518) is a case that had occurred to me in TM where all my installed scripts'externals had become 0 bytes due to a TM bug*.

And, as a user of scripts written by others, I find it useful as a security measure, to be able to directly verify that the loaded `@require` external scripts are indeed as their name suggests, and not some malicious code.

**Comment by tophf** [comment]
Hmm I guess it may make sense even for users especially since more people are now concerned with security than in the past.

**Comment by tophf** [comment]
Minor progress: #879 will show HTTP errors on updating resources/requires/icon.

**Comment by darkred** [comment]
@tophf thanks for adding this feature!
