### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#872]
What you have going on with the sync translations with Transifex? The translations differ.

I found a discrepancy, wanted to fix it, and found that I had already fixed it, but this fix was not included in the extension. How so? Repository says that it was updated 10 days ago, and I made corrections on Transifex 12 days ago.

=)

**Comment by gera2ld** [comment]
@wvxwxvw Could you please provide an example? I just checked Transifex and found translations in VM almost up to date (except those to be merged in #865).

**Comment by wvxwxvw** [comment]
"labelNotifyThisUpdated": {

**Comment by wvxwxvw** [comment]
I wanted to rewrite this line, but decided not to touch it yet to show you the fact of the anomaly.

Its would share on different strings, and not so as now. The meaning is slightly blurred because of this string continuation.

**Comment by gera2ld** [comment]
Is this your expected translation? If this is true, it may not be a problem because it's already included in #865.

![image](https://user-images.githubusercontent.com/3139113/74492968-a2a24700-4f0b-11ea-8d61-d82fd09217a4.png)

**Comment by wvxwxvw** [comment]
Yes, I see now. Apparently I didn’t look there yesterday.
