### ISSUE TITLE
[BUG REPORT] Did the line wrapping quit working?

### ISSUE THREAD

**Issue by gaveitatry02** [violentmonkey/violentmonkey#873]
I had to reformat my computer this weekend.  Now, four days later, I was trying to edit a script.  By the way, there was a Windows update yesterday and also a Mozilla Firefox update yesterday.  I'm currently using Firefox 73.0.  And I updated all my add-ons today, including ViolentMonkey.  So anyway, none of my lines in my script will line wrap.

I have this in Settings:
```
{
  "lineWrapping": true
}
```

But it's not doing anything.

Did something break?  If so, how do I get it fixed?

**Comment by tophf** [comment]
Works for me. See if you can reproduce this in a new freshly created Firefox profile.

**Comment by tophf** [comment]
A-ha! I can reproduce this when opening the editor from the popup. Investigating further.

**Comment by tophf** [comment]
Until the new version is released please open the editor from dashboard, not from the popup.

**Comment by gaveitatry02** [comment]
Sorry for being impatient.  I know you are working really hard on the unreleased next version.  And I know you probably don't have an ETA yet.  But it has been 1 month and 19 days, and I'm wondering why the https://github.com/violentmonkey/violentmonkey/pull/874 hasn't been implemented yet.  I miss being able to edit scripts directly from the websites.

**Comment by tophf** [comment]
It was fixed in #874 at once.

**Comment by tophf** [comment]
Maybe you could help us release the new version by testing the attached zip as a [temporary extension](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)? Just make sure to export a full backup in VM settings.

[vm-pr943.zip](https://github.com/violentmonkey/violentmonkey/files/4418853/vm-pr943.zip)

**Comment by gaveitatry02** [comment]
Sorry for the delayed response.  I didn't realize that you had replied.

I recently made the switch from latest Mozilla Firefox to Firefox Portable.  Not sure if that changes anything.

I unzipped the temporary extension, typed "about:debugging" in the URL bar, selected "This Firefox" and clicked on "Load Temporary Add-on".  Then I opened the extracted folder and randomly selected a file.

This created a Violentmonkey entry on my about:debugging page, but it had a bunch of Warning Details as follows:

Warning details

`Reading manifest: Warning processing permissions: Error processing permissions.9: Value "declarativeContent" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["bookmarks"], be one of ["find"], be one of ["history"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab", "tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["browsingData"], be one of ["captivePortal"], be one of ["devtools"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["pkcs11"], be one of ["geckoProfiler"], be one of ["sessions"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["management"], be one of ["networkStatus"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]`

Warning details

`Reading manifest: Warning processing options_page: An unexpected property was found in the WebExtension manifest.`

I wasn't sure if it worked.  I think I might have removed it.  But anyway, I went back to my Add-ons Manager, found my old Violentmonkey extension that was installed around February 14, 2020.  I disabled it.  Then I re-added the temporary Violentmonkey extension again.  It appeared on my Add-ons Manager page as a Violentmonkey that was installed today, instead of February 14.  I didn't see the older version of Violentmonkey in the disabled section.

I then went to an anime website, opened up my script from the website, and line breaks were back.  Also, it appears it remembered and kept all my user scripts, so that's good.  Not sure how I can help you test anything.  I did make a lot of scripts, but I'm a noob who has no idea what I am doing.  I just play around till something works and the page looks the way that I want it to.

Thanks for your reply and trying to help me with this matter.  For now, I have the line breaks I want.  I'll try to remember to backup my data when your new release comes out and I make the switch to the official, non-temporary extension.

**Comment by tophf** [comment]
* The warnings can be ignored, they're informational.
* The temporary extension replaces the main one while Firefox is running. Restarting Firefox will restore the main extension automatically.
* The data storage of the temporary extension is the same as the main extension's.

So everything's fine. If possible keep using this temporary extension.

**Comment by gaveitatry02** [comment]
Thank you for the second reply.  But it's only been a few minutes, and it is no longer working for me.  I didn't close the browser or do anything.  But I opened up the anime page again, and the script was not running.  I clicked the Violentmonkey icon and it didn't pull up a window.  I went to the about:debugger page, and the Violentmonkey icon was grayed out.

Also, I restart the browser a lot and don't want to keep refreshing or readding the tempoary addon.

So I think I'll just go back to using the main extension.

If I install the older version of Violentmonkey, do I have to install it as a temporary addon too?

Any chance you can give a rough estimate as to when the next version will come out?  Two weeks?  Or longer?

Sorry for the trouble.

**Comment by tophf** [comment]
You can find a tutorial on installing older versions of extensions. In short: backup data, remove the extension, visit the addons site, open history link, install the old version, disable auto-update in the addon manager. It'll be permanent now.

**Comment by gaveitatry02** [comment]
Thank you.  The older version trick did the job and was easy.  It was the perfect solution.  Thank you so much for your help and have a great day, week, month, and year!

**Comment by jesus2099** [comment]
For the record, it also fixed [the same Issue in Vivaldi](https://github.com/violentmonkey/violentmonkey/pull/652#issuecomment-698826946) (Chromium based browser).
