### ISSUE TITLE
[Feature Request] 加个载入/更新时忽略缓存的选项

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#875]
这两天用了 jsDelivr 发现缓存问题很严重，当需要立即更新的时候说啥也检查不到，得关掉 VM，强制刷新，再开启 VM，再安装才行。能否在 VM 中加个一律忽略缓存的选项？

**Comment by tophf** [comment]
Merging into #876: fixing that will fix this.
