### ISSUE TITLE
Add git as a sync option [feature]

### ISSUE THREAD

**Issue by TilCreator** [violentmonkey/violentmonkey#878]
It would be extremely nice to sync all scripts with a git repository, that would not only add a very powerful sync option but also allows fast and easy sharing of scripts.
There are already some pure JS implementations of the git client.

**Comment by tophf** [comment]
While it might be nice in case there is a **really** small library for that, not a monster like isomorphic-git. Practically though a more powerful solution might be to run a local WebDAV server and a normal standalone git sync executed from cron/scheduler job or by a watcher utility that detects changes in the designated directory.

**Comment by TilCreator** [comment]
I guess using the local git binary is also unwanted, because that would require file system access and execution of the git binary?

**Comment by tophf** [comment]
To run a local program extensions need `nativeMessaging` API, which is a huge hammer and hence is even more problematic.

**Comment by TilCreator** [comment]
I can't really find any better solution than the local WebDAV server when trying to keep the size and complexity low.
So I'm closing this for now and will post a more specific example setup here when I get to it.
