### ISSUE TITLE
breaks mega.nz on Chromium

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#88]
![](https://camo.githubusercontent.com/fc7a386ae5406347968db59186b58f422c01dda8/68747470733a2f2f692e6779617a6f2e636f6d2f63383764343432663366333362313437386333356336313334343466613131302e706e67)

Steps to Reproduce

- Install Hello World script from here - https://gist.github.com/uBlock-user/54b5005ebb03837e850d8c9a11e109da/raw/d70ce830391cd5be8dc9620a075616748389e232/Hello%2520World.user.js

- Visit https://mega.nz/#!Lgt0iZ7K!SKiaeRDaOGjZyXtT5pFJDS6pw1e-fOkvRZtu82Fvehc

For ref - https://github.com/X01X012013/AdBlockProtector/issues/113

@gera2ld Cannot reproduce this issue with the same script on TM Beta, so I believe this is a VM bug.

**Comment by gera2ld** [comment]
Will be fixed in the next release.

**Comment by gera2ld** [comment]
fixed in v2.6.0

**Comment by uBlock-user** [comment]
Thanks works fine as expected.
