### ISSUE TITLE
Sandbox leak when using `Object.defineProperty(window ...`

### ISSUE THREAD

**Issue by kkocdko** [violentmonkey/violentmonkey#885]
```js
// ==UserScript==
// @name      Demo
// @match     *://*/*
// ==/UserScript==

Object.defineProperty(window, 'foo', {
  value () {
    alert('leaking')
  }
})
```
Then the `foo` function will be assigned directly to `window`, without `unsafeWindow`.

Tampermonkey didn't have the problem.

### Environment
- Browser: Firefox 73.0.1 (64bit)
- Violentmonkey version: 2.12.7
- OS: Windows 10 1607 LTSB

**Comment by tophf** [comment]
Scripts without any `@grant` value are running as though `@grant none` is specified, that is without sandbox. We chose to follow Greasemonkey in that regard so blame Violentmonkey for deviating.
