### ISSUE TITLE
Edge addons listing legit?

### ISSUE THREAD

**Issue by zmni** [violentmonkey/violentmonkey#893]
This page: https://microsoftedge.microsoft.com/addons/detail/jeokchcoaikafalmgagcpcgcfiplcdpd

Is it officially from you guys? I want to install it but [this page](https://violentmonkey.github.io/get-it/#edge) says it is not yet supported.

**Comment by tophf** [comment]
Doesn't look like ours because it removed `"homepage_url": "https://violentmonkey.github.io/"` from manifest.json, used a different `"key"` so the extension's id changed and removed all translations except English. The actual code is identical though to the extension in Google's web store.

**Comment by zmni** [comment]
Thank you for the info, better wait for official then. Do I need to report it? Or do you want to handle it first?

**Comment by gera2ld** [comment]
The official version is being reviewed. It will be published soon, hopefully.
Thank you for your information.

**Comment by zmni** [comment]
This one isn't it? https://microsoftedge.microsoft.com/addons/detail/eeagobfjdenkkddmbclomhiblgggliao

**Comment by gera2ld** [comment]
@zmni That's it.

A link to the Edge addon has been added to the website here: https://violentmonkey.github.io/get-it/

**Comment by tophf** [comment]
Maybe add a badge to README as well?
![image](https://user-images.githubusercontent.com/1310400/76930452-925cfd80-68f7-11ea-9b6b-18569f46fec2.png)
