### ISSUE TITLE
False Octal SyntaxError

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#895]
### What is the problem?
Browser complains about octal values

### How to reproduce it?
Add the following line to any javascript file
```
const test = "\2713\0020"
```
It is commonoly used as a check mark (✓ or ✔) within stylesheets.

### What is the expected result?
To be parsed without a problem

### What is the actual result?
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead

### Environment
- Browser: Firefox
- Browser version: 73
- Violentmonkey version: v2.12.7
- OS: Linux Manjaro

**Comment by tophf** [comment]
Can't reproduce. This is either a problem in your full script which cannot be seen in the excerpt you've posted or it's a Linux distro's fault like Debian's devs sometimes think they're smarter than browser developers and "fix" things in browsers thus breaking something.

**Comment by twifty** [comment]
I dug into it a little further. It appears to only error when the value is within an es6 class. Here is a minimal script:
```
// ==UserScript==
// @name        Tick Test
// @namespace   Violentmonkey Scripts
// @version     1.0
// @author      Twifty
// @run-at					document-end
// @charset					UTF-8
// ==/UserScript==


class Test {
  constructor () {
    this.test = "\2713\0020"
  }
  
  log value () {
    return this.test
  }
}

console.log(test)
```
Not sure if related, but the script doesn't load on github, I tested it on translate.google.com

**Comment by tophf** [comment]
Same error is seen when opening an HTML file with this script directly:
```html
<script>
class Test {
  constructor () {
    this.test = "\2713\0020"
  }
}
</script>
```

It means the issue is not related to Violentmonkey. I see the error both in Chrome and FF so it's either a bug in both (hard to believe to occasionally happens) or this is an intended behavior documented somewhere in JS specs.

**Comment by tophf** [comment]
Yep, quoting https://tc39.es/ecma262/#sec-strict-mode-code

>All parts of a ClassDeclaration or a ClassExpression are strict mode code.

**Comment by twifty** [comment]
Ahh, that makes sense. The value is normally used in a css `content` property. My code had the css script as a class property, to be later added to a shadow DOM. Since it was part of a string within a class, and strict mode in place, it would error out.

Learn something new every day.
