### ISSUE TITLE
建议把已激活脚本排在最前面

### ISSUE THREAD

**Issue by visualwind** [violentmonkey/violentmonkey#898]
建议把已激活脚本排在最前面

**Comment by tophf** [comment]
?

**Comment by visualwind** [comment]
像这样
![QQ拼音截图未命名](https://user-images.githubusercontent.com/12063393/76140708-30e79400-6098-11ea-83c4-1e9c2380d0a9.png)

**Comment by tophf** [comment]
![image](https://user-images.githubusercontent.com/1310400/76140749-945ccc00-606e-11ea-95b1-0a02e94d58df.png)

**Comment by visualwind** [comment]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/12063393/76140806-05b17480-6099-11ea-9e9f-c828d7bea374.png)
我发现别的备份压缩包里多了两个文件

**Comment by tophf** [comment]
Unfortunately google-translate doesn't help me to understand your last comment so let's summon @gera2ld.

**Comment by tophf** [comment]
I guess the problem is that the option isn't saved in the backup. I see there is indeed a bug with that so I'll investigate.

**Comment by gera2ld** [comment]
The last comment is a duplicate of #889 , script options and script values are not synced properly at the moment.
