### ISSUE TITLE
@match with regex not working

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#901]
### What is the problem?
Any form of regex in the @match/@include tags are not working

### How to reproduce it?
Take for example `/https:\/\/guide\.v2fly\.org\/.*/`, it should match `https://guide.v2fly.org/prep/install.html` but doesn't. Did the test for leading/trailing '/' get removed?

### Environment
- Browser: Firefox
- Browser version: 73
- Violentmonkey version: 2.12.7
- OS: Linux

**Comment by tophf** [comment]
Please post an actual script as I can't reproduce the problem.

```js
// ==UserScript==
// @name        test v2fly
// @include     /https:\/\/guide\.v2fly\.org\/.*/
// @grant       none
// ==/UserScript==
alert('ok')
```

**Comment by twifty** [comment]
```
// ==UserScript==
// @name        test v2fly
// @match       /https:\/\/guide\.v2fly\.org\/.*/
// @grant       none
// ==/UserScript==
alert('ok')
```
Notice I said `@match` but you used `@include`

The API docs state that `@match` is prefered over `@include`. Are they not the same?

**Comment by tophf** [comment]
They're not the same, `@match` uses a stricter syntax that doesn't allow regexps, see https://violentmonkey.github.io/api/matching/ for an overview and https://developer.chrome.com/extensions/match_patterns for the actual definition of the syntax.

**Comment by twifty** [comment]
Ok. The API doesn't say that `@match` doesn't include regexps. Not to be nitpicky, but you match against a pattern and include from a list (I would allow globs as part of that list). Perhaps the docs could be updated to make that clear.

**Comment by tophf** [comment]
I'd say this is kinda implicitly stated by not listing regexps in `@match` while listing them in `@include` and moreover there's a link to the actual syntax. But if we get an influx of issues like this one, we'll have to add a clarification, I guess.

**Comment by twifty** [comment]
TBH, with GreaseMonkey and TamperMonkey also using the same scripts, I thought that @include was an older, soon to be obsolete key, and that the docs used old examples. When I read them I was only looking at the regexp syntax. It never occurred that they were not interchangeable.
