### ISSUE TITLE
Can not open window to edit userscript by pressing right button

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#905]
If I open VM menu with list of userscripts, I can't open window to edit them by pressing right button `</>`. i can only switch on and off

![изображение](https://user-images.githubusercontent.com/33825590/76169846-67530b00-618d-11ea-869b-08a4eb6928a5.png)

**Comment by tophf** [comment]
Can't reproduce neither in Firefox nor in Chrome.

1. Can you open the script by right-clicking (or wheel-clicking) its name?
2. Open `about:debugging`, click `Inspect` in Violentmonkey's entry, switch to `Console`, copypaste the contents here.

**Comment by soviet-man** [comment]
I just found out that I can't do it private windows. In regular windows I can do it (open to edit)

**Comment by soviet-man** [comment]
Right-clicking or middle-clicking on userscripts' name as well as left-clicking on `</>` button do nothing in private windows. All these operations in regular windows work as it should.
