### ISSUE TITLE
Wasted 20 minutes and couldn't find a simple Hello World

### ISSUE THREAD

**Issue by zed-b** [violentmonkey/violentmonkey#909]
Wasted 20 minutes and couldn't find a simple Hello World.

Wrote a simple console.log("Hello World") but it never outputted anything in the browser console. I'm probably doing something dumb, but my point is it could be made more beginner friendly.

**Comment by tophf** [comment]
Violentmonkey is an engine that runs userscripts efficiently, its goal is definitely not to be a beginner-friendly editor of scripts. Use any userscript tutorial to learn how to write them.

**Comment by gera2ld** [comment]
Violentmonkey is designed to be friendly to users first, not the developers.
But I'm still curious why would it be hard to create a Hello World.

The steps below worked for me:
- Open Violentmonkey dashboard
- Click the plus icon, then "New"
- Add `console.log("Hello World")`
- Save

Then I got `Hello World` in console of every new tab.
@zed-b could you tell which step is confusing?

**Comment by zed-b** [comment]
It seems I somehow changed the @match to just *, and it doesn't work. I assumed it was a wildcard * match like in console.

**Comment by gera2ld** [comment]
Ah, this is not something related to the UI/UX of Violentmonkey, so I think it's a won't-fix here. But I guess we can find some way to detect and warn invalid metadata in the future.
