### ISSUE TITLE
Manual Update check broken with v2.6.0

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#91]
Steps to Reproduce

- Create a script named HelloWorld.user.js like this - https://gist.github.com/uBlock-user/81b4b8908e4c4a53a1b524a3aa179bb1#file-hello-world-user-js

- Install it. 

- Increment the version or add/remove some piece of code and save the created script.

- Open Dashboard and click `Check for Updates` and it will result in **No update found**.

@gera2ld This looks like a regression bug. Auto update check is also broke probably.

**Comment by uBlock-user** [comment]
Wow was that a quick fix ?

**Comment by gera2ld** [comment]
It was my fault to use the wrong variable names after refactor. I've added tests for such functions. This will be fixed in the next release.

**Comment by uBlock-user** [comment]
Also it seems Blacklist doesn't seem to run as intended. For example I added `192.168.0.1` in the Blacklist so scripts won't run on that address and yet scripts are loaded.

**Comment by gera2ld** [comment]
Blacklist works for me. Each line is an `@exclude` rule, so you should write `http://192.168.0.1/*`.

**Comment by uBlock-user** [comment]
Is that the format ? I thought you only had to add the domain.

**Comment by gera2ld** [comment]
See <https://wiki.greasespot.net/Include_and_exclude_rules>.
Domain rules are not enough if we want to exclude specific URLs based on pathnames.

**Comment by gera2ld** [comment]
You may start a new issue to discuss about the format of blacklist if you have better ideas.

**Comment by uBlock-user** [comment]
I will do that. Thanks.
