### ISSUE TITLE
Firefox does not stop on keyword 'debugger'

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#914]
I don't know whether it is VM issue or Firefox issue, but if I put `debugger` keyword inside my userscript to debug it, Firefox won't stop.
I have to debug only using `console.log` statements. It is very inconvenient.

**Comment by tophf** [comment]
`debugger` statement is a part of JavaScript language, Violentmonkey doesn't have influence over that.

You can switch your userscript to `content` [injection mode](https://violentmonkey.github.io/posts/inject-into-context/) for better debugging in Firefox, but for `page` injection mode you'll have to use Chrome because sensible debugging of such scripts is not implemented in Firefox at all.

**Comment by soviet-man** [comment]
How can I open userscript to set breakpoint if don't see any of my userscripts here?

![изображение](https://user-images.githubusercontent.com/33825590/76707952-5d3c8980-6704-11ea-9ba9-a348a83db038.png)

**Comment by tophf** [comment]
Assuming you've already switched to `content` mode, there's another option in devtools settings that you need to enable:

![image](https://user-images.githubusercontent.com/1310400/76708009-b3a9c800-6704-11ea-8fba-6bb8f0200f35.png)

**Comment by soviet-man** [comment]
OK. I enable that option in browser settings.
Now I have that menu in left pane of Debugger tab.

![изображение](https://user-images.githubusercontent.com/33825590/76708227-47c85f00-6706-11ea-890b-8c87f6042795.png)

Firefox don't understand unicode (cyrillic) symbols?
By the way, I know that font I use in Firefox can render many unicode symbols, but here I have a mess.

**Comment by tophf** [comment]
No problem in Chrome so I guess it's a bug in Firefox.
![image](https://user-images.githubusercontent.com/1310400/76708327-fec4da80-6706-11ea-9eb2-a0d5ed549738.png)

**Comment by soviet-man** [comment]
It looks like I have to rename my userscripts.
Why do you insist on `content` injection mode? Is it better?

**Comment by tophf** [comment]
I don't insist. It's just the only way in Firefox to see the script names in devtools and debug them properly.

**Comment by soviet-man** [comment]
If I switch to `content` injection mode, I have not any of my userscript in Violentmoney subfolder

![изображение](https://user-images.githubusercontent.com/33825590/76708821-df2fb100-670a-11ea-8c67-a2184ed912c3.png)

**Comment by tophf** [comment]
Oh, this is also what I see here so I was wrong about the listing... Firefox is awesome.

**Comment by soviet-man** [comment]
Where are all my userscripts? I did nothing

![изображение](https://user-images.githubusercontent.com/33825590/77643144-e3ac6300-6f6f-11ea-87a2-839dbfb5b03f.png)

**Comment by tophf** [comment]
We didn't do anything either. Judging by the above it looks like you (or the site) switched to the `content` injection mode. It can happen in Firefox on sites that forbid `page` mode because of Content Security Policy of the site.

**Comment by soviet-man** [comment]
Great. So now I can't debug anything that works for twitter.com

**Comment by tophf** [comment]
You should be able to debug it by using `debugger` statement in the userscript. In `content` mode it should work correctly, and your code should show up in devtools when `debugger` statement is executed.

**Comment by soviet-man** [comment]
Inserting 
`// @inject-info content`
does not help with `debugger` keyword. Firefox stops in the middle of nowhere, so I can't debug.

**Comment by tophf** [comment]
You seem to have a typo: `info` should be `into`

**Comment by soviet-man** [comment]
Yes, it's my typo when I typed text here. I my userscript copypasted that string from VM site in order not to make mistake. No change. I can't debug.

**Comment by tophf** [comment]
In that case you have two options: 1) try a different userscript manager e.g. Tampermonkey that has an option to patch site's `CSP`, maybe also try Greasemonkey or Firemonkey. 2) Use another extension to remove `Content-Security-Policy` HTTP header on that site.

**Comment by soviet-man** [comment]
Tampermonkey is proprietary software. I don't trust it.

**Comment by soviet-man** [comment]
I tried _FireMonkey_ and _GreaseMonkeey_. Both **don't show** enabled userscripts in Firefox Debugger pane (so I can't set breakpoints to debug them), BUT userscripts work!
_ViolentMonkey_ **shows** enabled userscripts in Firefox Debugger pane (so I can debug), BUT on some sites userscripts **don't work** unlike _FireMonkey_ or _GreaseMonkey_.
I am tired of these paradoxes!

**Comment by tophf** [comment]
Well, I can't help without trying those scripts myself. As for being tired, I can't even begin to describe how frustrated with Firefox devtools I am myself having encountered lots of similarly nonsensical bugs over the years.
