### ISSUE TITLE
GM_getResourceText breaks with surrogate pairs

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#916]
### What is the problem?
```
// ==UserScript==
// @name              Resource Test
// @version           1.0.0
// @match             *
// @run-at            document-end
// @charset           UTF-8
// @resource        cedict https://raw.githubusercontent.com/twifty/ff-translate/master/cedict_1_0_ts_utf-8_mdbg.txt
// @grant           GM_getResourceText
// ==/UserScript==

const tmp = `㞗 㞗 [qiu2] /(dialect) penis/dick/
㞙 㞙 [niao4] /old variant of 尿[niao4]/
㞞 𪨊 [song2] /(coll.) semen/weak and incompetent/
㟁 岸 [an4] /variant of 岸[an4]/
㠀 岛 [dao3] /variant of 島|岛[dao3]/
㠯 以 [yi3] /old variant of 以[yi3]/`

var expected = tmp.split(/\r?\n/).filter(line => line[0] !== '#')
console.log(expected)

var cedict = GM_getResourceText("cedict").split(/\r?\n/).filter(line => line[0] !== '#')
cedict = cedict.slice(159, 165)
console.log(cedict)

expected = [...expected[2]]
cedict = [...cedict[2]]

console.log(expected, expected[2].length, expected[2].charCodeAt(0).toString(16), expected[2].charCodeAt(1).toString(16))
console.log(cedict,   cedict[2].length,   cedict[2].charCodeAt(0).toString(16),   cedict[3].charCodeAt(0).toString(16))
```

### How to reproduce it?
The example script fetches a resource which contains a Chinese character from the unicode supplementary plane (U+010000 → U+10FFFF) represented as the surrogate pair (\uD86A\uDE0A). I expect the string returned from `GM_getResourceText` to contain that surrogate pair, instead it has been transformed into the byte sequence (\u0AA8\uA81B).

### Environment
- Browser: firefox
- Browser version: 74
- Violentmonkey version:  2.12.7
- OS: Linux

I've had a quick look into the source:
https://github.com/violentmonkey/violentmonkey/blob/470a92d29d37e1aafe8f7dd66a0e6f999de40121/src/injected/utils/helpers.js#L42
This only accounts for a sequence of 3 bytes, but UTF8 encoding of the supplementary plane always produces 4 byte sequences.

**Comment by tophf** [comment]
Fixed in #908.
BTW There seems to be a typo in your code: the last line should end with `cedict[2].charCodeAt(1).toString(16)`

**Comment by twifty** [comment]
That isn't a typo. Each char in the `cedict` array is of length 1. I read the next char in the array, unlike the `expected` array which has a single entry of length 2 (for the surrogate pair).

**Comment by tophf** [comment]
`cedict` array is exactly the same as `expected`, byte-for-byte, char-for-char, because GM_getResourceText decodes it to a standard JS string.

**Comment by twifty** [comment]
No it isn't. `expected[2]` is of length 1, wheras `cedict[2]` is of length 1. `expected` has correctly split the surrogate pair. `cedict` has not because the string returned from `GM_getResourceText` is corrupted.

**Comment by tophf** [comment]
You probably mean the current Violentmonkey, but I'm talking about the fixed one from #908. Now the output is absolutely identical.

**Comment by tophf** [comment]
It'd be helpful if you test it too, here's a zip to be loaded as an unpacked extension.
[vm-pr908.zip](https://github.com/violentmonkey/violentmonkey/files/4341680/vm-pr908.zip)

**Comment by twifty** [comment]
Oh, I haven't tested #908 yet. My browser is currently running an intensive task, so I won't get a chance to test it for at least another 24 hours.

I couldn't find the code which stores the resource, but I'm guessing it was stored as UTF8. Did any byte convertion account for surrogates? I see from the push that the decode is now correctly handled.

**Comment by tophf** [comment]
The internal storage keeps the bytes of the original resource unchanged, https://github.com/violentmonkey/violentmonkey/blob/master/src/background/utils/storage-fetch.js#L9-L12.

**Comment by twifty** [comment]
All looks good to me. I'll test the new version later tomorrow and update if anything not working as expected. Thanks for the quick fix BTW.

**Comment by tophf** [comment]
GM_getResourceText will be ~15 times faster: 0.15 s instead of 2.5 s.
