### ISSUE TITLE
Values editor should auto-refresh

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#919]
### What is the problem?
While creating a script with the built-in editor open, if I call `GM_setValue('a', {})`, having NOT opened the Values tab yet, then opening the tab, the set value will be displayed. Any later calls to `GM_setValue`, either modifying an existing key or adding new, the values are missing.

Within the Values tab, either adding or deleting keys, doesn't refresh the list to include those keys added from within the script.

Sure, I can refresh the tab, but that breaks code folding and scroll positions in the Code tab.

The Values tab is great for quickly viewing/deleting while debugging a script.

A possible solution would be to call `setTimer` within the Value tab to check for updates, or include a 'refresh' button.

### Environment
- Browser: firefox
- Browser version: latest
- Violentmonkey version: latest
- OS: linux

**Comment by tophf** [comment]
Yeah it doesn't.
