### ISSUE TITLE
Proposed Blacklist Format

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#92]
Current format requires you to add the domain with a protocol and a specific pathname.
 
Example:  To add `192.168.0.1` you will need to add - `http://192.168.0.1/*` or `*://192.168.0.1/*`

I suggest you remove that requirement and make it as simple as adding just `192.168.0.1` or `192.168.*.*`

Protocol shouldn't matter if you're going to blacklist a domain after all. Ultimately, I want you to add support for domain based exclusions, so those like me who simply want to blacklist the domain rather than the pathname can do effortlessly.

**Comment by gera2ld** [comment]
What if we just want to exclude `http://example.com/foo/*` but include `http://example.com/bar/*`?
We can define prefixes to tell whether the rule refers to a domain or a pattern (like AdBlock Plus does), but that makes it a lot more complexed.
I think it is OK to just reuse the `@exclude` rules.
Hoping for more ideas.

**Comment by uBlock-user** [comment]
You misunderstand me, I'm suggesting to make protocol and pathname based rules **optional**

I simply want to add `192.168.0.1` or `192.168.*.*`  rather than adding the whole specific pathname like `http://192.168.0.1/*`.  

What do you think ?

**Comment by gera2ld** [comment]
I think we can change the `@exclude` rules to `@exclude-match` rules. In that case, each rule should follow [match patterns](https://developer.chrome.com/extensions/match_patterns) here, and it is easy to find out the exceptions. For exceptions, we can have domain-only rule like `192.168.0.1` or `@exclude` rules started with `@exclude`. Here is a full example:

```
# match rules
*://www.google.com/*

# domains
www.google.com

# exclude rules
@exclude http://*
```

**Comment by uBlock-user** [comment]
So with that, can I add `example.com` simply ?

**Comment by gera2ld** [comment]
Sure, because that will be recognized as *domain* rules.

**Comment by uBlock-user** [comment]
Will it support wild card like `*` ? Like adding `example.*`

**Comment by gera2ld** [comment]
Yes, domain rules will be transformed into match rules automatically, so `example.com` will be transformed into `@match *://example.com/*`, and `example.*` will be transformed into `@match *://example.*/*`.
A rule without slashes will be recognized as a domain. Glob rules should be prefixed with `@exclude` explicitly.

I think I will write a post to introduce it later.
