### ISSUE TITLE
[feature request] highlight matching words

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#922]
The one thing I miss more than anything is the ability to double click a variable/function name in the editor and have all instances of that name become highlighted. It makes for finding values much easier. Could this feature be implemented into VM built-in editor?

Out of curiosity, which editor is VM using? I've noticed it is very similar the atom editor.

**Comment by tophf** [comment]
VM is using CodeMirror and it has match-highlighter addon which is very small so we can add it, I guess.

**Comment by tophf** [comment]
Turns out we're already loading this addon but we didn't add a CSS rule for `.cm-matchhighlight`...

**Comment by twifty** [comment]
Workaround works perfectly. Thanks
