### ISSUE TITLE
[feaure request] Prevent navigating away from editor

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#930]
If I had a penny for the number of times I've accidentally refreshed the editor tab, rather than the test page, only to lose all my code folding...

Would it be possible to listen to window "beforeunload" within the editor, and prompt the user if they really want to leave/refresh? To prevent annoyances to users who would not like this feature, perhaps it could be toggled on/off in the Settings pane.

**Comment by tophf** [comment]
Already implemented in the upcoming version via #867.

**Comment by twifty** [comment]
After having a quick look at that push, it appears as though the dialog will only display if unsaved changes are pending. If that is the case, then it is not the feature I requested.

Very often I save my work, switch tabs and reload the test page. Sometimes though, I hit reload before switching tabs, which reloads the editor. This is what I want to avoid.

Is it possible to put a checkbox in the Settings pane for something like "Always warn when leaving page"?

**Comment by tophf** [comment]
This is not how editors work in general AFAIK so no.

**Comment by twifty** [comment]
And most editors do not have a refresh button in the window. Also most editors do not do the editing within the same window as testing.

**Comment by tophf** [comment]
I meant in-browser editors, of course.

**Comment by tophf** [comment]
Note, the preferred method of editing in Violentmonkey is via an [external editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/).
