### ISSUE TITLE
Bug when highlighting strings

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#937]
Imagine this code
![изображение](https://user-images.githubusercontent.com/33825590/77647636-d4311800-6f77-11ea-8208-4f9908bcb774.png)

If I put new `?.` operator after `input` field meaning this field can be omitted, then highlighting of strings below will change

![изображение](https://user-images.githubusercontent.com/33825590/77647825-2a9e5680-6f78-11ea-97fe-419ec48d9645.png)

**Comment by tophf** [comment]
CodeMirror doesn't support it yet.

**Comment by tophf** [comment]
You can report the issue to CodeMirror repository if you can reproduce it in their [demo](https://codemirror.net/demo/complete.html) but make sure to post the code as text because no one will type your code manually.

**Comment by tophf** [comment]
I've reported it and the fix is included in CodeMirror 5.54 which was released just now so it'll be included in our next release (when @gera2ld has time).
