### ISSUE TITLE
Running userscripts in Firefox Picture-in-Picture windows

### ISSUE THREAD

**Issue by xcasxcursex** [violentmonkey/violentmonkey#939]
### What is the problem?
I have not been able to get my userscripts to run in the Firefox PiP window

### How to reproduce it?
1. Play a video in firefox
2. Click the Picture-in-Picture button on the right, to create a popup window
3. Scripts run in the opening tab where the video element exists

### What is the expected result?
Do the same things in the PiP window, that I do in a normal FF tab.

For example, I have a script which adds a mouse listener to the video element so that I can scroll to fade the video brightness

### What is the actual result?
Script runs in the tab where the video was before it moved into the PiP window

For example, the original tab fades but the video in the PiP window stays at full brightness

It is entirely possible I suck at JS and need to do something special to detect the opening of the new window and run extra script to add a listener to the new element, but how to go about knowing that has occurred?
Apologies if this is a "I suck, gitgud" question and not actually a problem with VM. Advice would be appreciated, I looked around and came up blank.

### Environment
- Browser: Firefox Nightly
- Browser version: 76.0a1
- Violentmonkey version: 2.12.7
- OS: Win10 1909

**Comment by tophf** [comment]
It can't be inspected even in the built-in devtools. Per specification it's not a DOM window/page so scripts can't run there.

**Comment by xcasxcursex** [comment]
> It can't be inspected even in the built-in devtools. Per specification it's not a DOM window/page so scripts can't run there.

I can inspect it with the devtools enough to see that scripts do run there.

![image](https://user-images.githubusercontent.com/58130821/77706240-f6797300-7015-11ea-84dd-2092d2840d72.png)

But that is with the browser toolbox (as opposed to the content toolbox), so I guess what's happening is that it is all running as chrome, so userscripts can't run there without a userchrome.js hack of some sort. Thanks for the tip, now I know why I was failing. Sorry to bother you.

**Comment by tophf** [comment]
Well yeah, I forgot about the browser toolbox in Firefox as it's almost completely useless in modern Firefox. Anyway, the PiP feature is implemented intentionally in such a limited way, see the spec and w3c discussions for more info.
