### ISSUE TITLE
Blob objects are broken under Bing

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#944]
```
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *
// @include     *
// @grant       none
// @version     1.0
// @author      -
// ==/UserScript==

console.log(new Blob([1,2,3]));
```

It returns `cValue {}` instead of a `Blob` object.

**Comment by tophf** [comment]
What does "under Bing" mean? I can't reproduce the problem.

**Comment by qsniyg** [comment]
Sorry, forgot to mention that this is due to uBlock origin, but it used to work with VM. Same issue as earlier: https://github.com/violentmonkey/violentmonkey/issues/883

That being said, TM now exhibits the same issue as well, maybe uBlock just got stronger or something?

**Comment by tophf** [comment]
There's nothing we can do as your script is `@grant none` so it's using the page objects directly, which we don't control (and should not control). Theoretically we could do something in our sandbox when some `@grant ` is not `none` but that's expensive: making a copy of all global objects takes 50ms on 4GHz i7.

You can try to extract the native built-ins yourself by abusing the fact that extensions can't process some types of same-origin iframes in Chrome at least:

```js
const {Blob} = getNativeTypes(['Blob']);
console.log(new Blob(['test']));

function getNativeTypes(types) {
  const res = {};
  const el = document.createElement('iframe');
  el.srcdoc = '';
  // el.src = 'javascript:0'; // alternative method
  document.documentElement.appendChild(el);
  const frameWnd = el.contentWindow;
  for (const t of types) res[t] = frameWnd[t];
  el.remove();
  return res;
}
```

**Comment by qsniyg** [comment]
It fails without `@grant none` as well, I just forgot to remove it for the example script.

**Comment by tophf** [comment]
Yes, I know and my comment addressed both cases.

BTW the master branch runs earlier than uBlock in Chrome on fast sites like bing.com so if your script is running at `document-start`, you can save the native types at the beginning of your script like this:

```js
const {Blob} = window;
```

**Comment by tophf** [comment]
@qsniyg, why do you use an extension that overrides Blob? To me this entire situation looks like you're shooting yourself in the foot and trying to guard against this by wearing steel boots.

**Comment by qsniyg** [comment]
@tophf Indeed, it's quite annoying haha. It seems like most of the time I spend working on this userscript is just to safeguard against either extensions breaking things, or websites overriding native functions, breaking things.

Thanks for the iframe trick by the way, it's super useful! :)
