### ISSUE TITLE
Unable to set the window object in git master

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#945]
```
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *
// @include     *
// @grant       GM_xmlhttpRequest
// @version     1.0
// @author      -
// @run-at      document-end
// ==/UserScript==

try {
    var w = window;
    window = w;
    console.log("Success");
} catch (e) {
    console.error(e);
}
```

This works on 2.12.7 (and Tampermonkey), but not on the latest master. I know it's not _supposed_ to be done, but it does kind of come in handy for my userscript (as it can be used in a headless scenario).

**Comment by tophf** [comment]
The new behavior is correct because `window` is *unforgeable* per specification.
If you run `Object.getOwnPropertyDescriptor(window, 'window')` you will see `configurable` is `false`.
There are about 10 such properties.

**Comment by tophf** [comment]
This can be rewritten in a spec-compliant fashion:

```js
var w = this.window, window = w;
```

**Comment by qsniyg** [comment]
Thanks! :)
