### ISSUE TITLE
In your code editor highlighting and indenting works partially

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#951]
In my code listing some variables are highlighted, while others are not.
Sometimes indent (when I press `Tab` button) is 3 spaces (as I explicitly set), sometimes it reset to default 2 spaces.

Firefox v74.0.1, VM v2.12.7

**Comment by tophf** [comment]
Can't help without the code.

**Comment by tophf** [comment]
And your editor options in VM settings.

**Comment by soviet-man** [comment]
Part of my code with weird highlighting
![изображение](https://user-images.githubusercontent.com/33825590/78581553-b055b800-783c-11ea-8039-b7203ea69616.png)

Settings of VM with 3 spaces for indent while I have 2 spaces for real.
![изображение](https://user-images.githubusercontent.com/33825590/78581667-d8ddb200-783c-11ea-818f-f5796a09b3b9.png)

**Comment by tophf** [comment]
Paste the code as text here.

**Comment by soviet-man** [comment]
```
      this._count += 1
      let data = await this.data( response )
      if ( !data ) { return }
      this._next = data.next
      delete data.next
```

```
{
  "lineWrapping": false,
  "indentWithTabs": false,
  "indentUnit": 3,
  "tabSize": 3,
  "undoDepth": 200
}
```

**Comment by tophf** [comment]
1. Post the complete code that exhibits the problem after pasting it in the editor alone
2. Specify what's weird about highlighting.
3. If the same is observed in [CodeMirror demo](https://codemirror.net/demo/complete.html) then report it in CodeMirror repository, not here.

Regarding the tab size, describe the exact sequence of actions. And by **exact** I mean where to place the cursor, what to press, and so on. Right now it sounds like you think it'll always insert 3 spaces but this is not how `Tab` key works: it aligns to the nearest boundary so in case of `3` it'll insert as many spaces as needed to reach column 4, 7, 10, 11.

**Comment by soviet-man** [comment]
Full code of class

```
class Aggregator_Media extends Aggregator {
   //================================================
   constructor() {
      super()
   }
   //================================================
   init( input ) {
      super.init( input )
   }
   //================================================
   async aggregate() {
      if ( !this._next ) { return }
      let response = await console.AA.base.xhr( this._next )
      if ( response.status >= 400 ) {
         if ( !response.context?.continue_if_error ) {
            if ( response.status !== 404 ) {
               alert( `${ response.status } ${ response.statusText }\n${ JSON.stringify( this._next, null, 3 ) }` )
            }
            return
         }
      }
      this._count += 1
      let data = await this.data( response )
      if ( !data ) { return }
      this._next = data.next
      delete data.next
      //---
      let n = this._next?.url || this._next
      if ( typeof n === 'string' && n.startsWith( '/' ) ) {
         n = ( new URL( response.finalUrl ) ).origin + n
         if ( this._next?.url ) { this._next.url = n } else { this._next = n }
      }
      //---
      filter_inplace( data.media, x => {
         if ( x.type instanceof Function && !x.id ) { return true }
         let id = x.id || id_of_flat_object( x )
         if ( this._found[ id ] ) { return false }
         this._found[ id ] = true
         return true
      } )
      //---
      return data
   }
   //================================================
   async data( response ) {}
   //================================================
}
```

**Comment by soviet-man** [comment]
CodeMirror has buggy highlighting as I expected

**Comment by tophf** [comment]
Yeah it's a simple editor so naturally it has issues. The preferred method of editing in Violentmonkey is to [use an external editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/) anyway.

**Comment by soviet-man** [comment]
So I have to start local web server? NO WAY!

**Comment by tophf** [comment]
That'll be unnecessary in the upcoming version, it'll be able to read files directly, sorry it takes so long but gera2ld is busy. Currently you can install the [release candidate](https://github.com/violentmonkey/violentmonkey/releases/) or use a simple server like [HFS](https://www.rejetto.com/hfs/) with GUI if you don't like "installing" stuff.
