### ISSUE TITLE
Refreshing the values tab doesn't work correctly (still don't work in 2.12.8rc2)

### ISSUE THREAD

**Issue by Mehavoid** [violentmonkey/violentmonkey#957]
### What is the problem?
Refreshing the values tab doesn't work correctly

### How to reproduce it?
1. Open tab "values" of you want script
2. Try click on navigation button
3. ...
4. Profit!

Screencast v2.12.7 https://i.imgur.com/JO7yEID.mp4

### What is the expected result?
Refreshing tab
### What is the actual result?
Tab not refreshing after click on buttons

In 2.12.7 No errors in the console.
In 2.12.8rc2 after open value tab if the list of keys is empty
```
vue.js:1 TypeError: Cannot read property 'id' of undefined
    at active (index.js:1)
    at un.run (vue.js:1)
    at cn (vue.js:1)
    at Array.<anonymous> (vue.js:1)
    at Kt (vue.js:1)
```
In 12.2.8rc2 attempt to add a key if the list of keys is empty
```
TypeError: Cannot destructure property 'id' of 'this.script.props' as it is undefined.
    at a.updateValue (index.js:1)
    at a.onSave (index.js:1)
    at Ut (vue.js:1)
    at HTMLButtonElement.n (vue.js:1)
    at HTMLButtonElement.i._wrapper (vue.js:1)
```
In 12.2.8rc2 refreshing the values tab still doesn't work correctly
### Environment
- Browser:  Ungoogled Chromium
- Browser version: 80.0.3987.149 (Developer Build)
- Violentmonkey version: 2.12.7 and 12.2.8rc2
- OS: Linux (Debian 10)

**Comment by tophf** [comment]
Please test the fix: [vm-pr958.zip](https://github.com/violentmonkey/violentmonkey/files/4464097/vm-pr958.zip)

**Comment by Mehavoid** [comment]
Yes, you fixed it, thank you!
