### ISSUE TITLE
Action required by AMO reviewer

### ISSUE THREAD

**Issue by gera2ld** [violentmonkey/violentmonkey#959]
> Please add a privacy policy to this add-on that details which user data is being sent and to what services. The critical things to describe in the policy are how your extension collects, uses, stores, and shares or discloses information about people.If your add-on makes it apparent to websites that it is installed, this must also be mentioned. The policy should be about the extension only, not a copy of the website's privacy policy. It should also be the actual text, as opposed to a link to a privacy policy on a website. The privacy policy can be added in the add-on settings under “Manage Authors & License” on AMO.

**Comment by tophf** [comment]
>If your add-on makes it apparent to websites that it is installed, this must also be mentioned. 

VM exposes an API to show the installation status of the currently displayed script on greasyfork. BTW I wonder if we should make it optional... TM has such an option.

**Comment by gera2ld** [comment]
That's a good point, especially for Firefox users who care a lot about privacy.

**Comment by tophf** [comment]
I'll make a PR then.
