### ISSUE TITLE
Option to disable the injected code wrapping

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#966]
I need the option to disable the code wrapping.

```js
(function(){with(this)((define,module,exports)=>{

...my code

})()}).call(VMink8zbw6t62bef)
```

I use third-party code, and this wrapping breaks the work. I have no problem with "User JavaScript and CSS", that injects the code without any changing.

`console.log(this);`
It prints `GM` object. I need `this` to be `window` object.

**Comment by AlttiRi** [comment]
OK, the workaround:
```js
this.unsafeWindow.userscript123 = function() {

...the code

};
this.unsafeWindow.userscript123();
```

**Comment by tophf** [comment]
We won't remove the wrapper because we don't use a specialized API for sandboxing (there's no such API in Chrome, for example) so that would leak functions and global variables of many userscripts that don't use an IIFE. Many userscripts don't use it as there was never such a need (userscripts historically ran in a sandbox in Firefox).

What we can do is remove custom `this` and use the real `window` **for userscripts with `@grant none` only** (or no grants at all which is an equivalent).

**Comment by AlttiRi** [comment]
I mean just the option in the user interface, that is disabled by default. Any way I have already found the workaround.

**Comment by tophf** [comment]
AFAICT that option would be useful only for one person in the entire world so we won't be adding it. The ability to turn off sandboxing (even the pathetic imitation we have), which is a inherent feature of any userscript engine, isn't something that should be exposed as an option in UI anyway.

**Comment by tophf** [comment]
Assuming your script is not `@grant none`, it would make sense to fix our sandbox so it works with your third-party code if you could share the script.

**Comment by AlttiRi** [comment]
> Assuming your script is not @grant none

Yeah, you are right.

> if you could share the script.

It's 15k of lines. I think some part of this code uses pattern "module" with passing `this` to IIFE.

**Comment by tophf** [comment]
The amount of lines doesn't frighten me. I want to debug the code because our sandboxing proxy should be transparent so I suppose there might be a bug in our implementation or we can add a special workaround for your case. If you don't want to share the code maybe you could test the upcoming [release candidate](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by AlttiRi** [comment]
I have rechecked the script work, and I should say that my workaround it's not ideal.

I get the exception when the code reads `window.variable.foo` where `variable` is a variable defined in window context. `var variable = {foo: "var"};`, for example.

**Comment by tophf** [comment]
Userscripts with some `@grant` except `none` run in a sandbox so they have their own `window` and to access the page they should use `unsafeWindow` instead. This is how userscripts has always worked.

**Comment by tophf** [comment]
If that variable is defined in your script (or dependencies) then we can't map it into the sandboxed `window` unfortunately.

**Comment by AlttiRi** [comment]
I have checked the beta version, it works the same way as the code with my hack that I wrote above. I think it can break the already existing userscripts, that use the same hack that change `this` to original `window` object.

**Comment by AlttiRi** [comment]
I just need the way to add JavaScript code as is. With no changing like a wrapping. Some other extension works the same way, and it's OK. The way to it either UI option, or the new declaration word like `@wrapping none`.

I need insert the original JS code of a site with minor changes (I block whole JS execution with uBO, and insert code as userscript after).

**Comment by gera2ld** [comment]
This is how userscript works. `this === unsafeWindow` only if `@grant none` is declared.

In your case you can either avoid using `GM_*` functions or wrap your code with `(function(){ ... }).call(unsafeWindow)`.
If you want to break the rules of userscript, you'd better create another extension yourself.

**Comment by tophf** [comment]
> I think it will break the already existing userscripts, that use the same hack that changes this to original window object.

I'd like to see a real example of such a script.

**Comment by AlttiRi** [comment]
`alert(this.unsafeWindow === window);`
`true` now, `false` in beta.

I talk especially about a userscript that **does not** use any GM_ function from the first my message here.

**Comment by tophf** [comment]
>this.unsafeWindow

Thanks, I'll look into that.

>I talk especially about a userscript that does not use any GM_ function from the first my message here.

We need to expose `GM_info` and `unsafeWindow` for scripts that don't have any explicit `@grant` so we would have to pollute the global scope for that. Your idea of running the code as-is can only be implemented in Violentmonkey when we'll use browser.userScripts API in Firefox. Please use a different extension for now.

**Comment by chocolateboy** [comment]
> We need to expose define, module, and exports for grant-less scripts

Why? First I've heard of this. Is this documented anywhere?

**Comment by tophf** [comment]
Because many scripts use JS libraries from NPM and elsewhere that use the standard/legacy module format detection, which you can see at the beginning of such scripts. If we don't provide an undefined value for `define`, `module`, and `exports`, these scripts will fail on pages that use one of these module formats themselves.

**Comment by chocolateboy** [comment]
Ah, I see: you ensure they're *undefined*. Thought you were saying you *define* them.

FYI, there are solutions for script developers who want to use CommonJS modules (which aren't available as UMD builds):

- use a service which [translates CommonJS modules to UMD bundles](https://github.com/JasonBarnabe/greasyfork/issues/618), e.g, [bundle.run](https://bundle.run/)
- use a fake CommonJS shim, e.g. [UncommonJS](https://github.com/chocolateboy/uncommonjs)

**Comment by AlttiRi** [comment]
The changes is still listed in the description here https://github.com/violentmonkey/violentmonkey/releases

> "set `this` to `window` for scripts with `@grant none` (or no grant entries at all), #966"

**Comment by tophf** [comment]
Oops.

**Comment by AlttiRi** [comment]
The other workaround for this issue (that will work 100 % as expected) is put all code to a string and inject it manually from the usercript:

```js
const code = `console.log("my-injected-code", this)`;

const script = document.createElement("script");
const blob = new Blob([code]);
script.src = URL.createObjectURL(blob);
document.querySelector("head").append(script);
```

**But it's a pain** due to problems like this: `Octal escape sequences are not allowed in template strings.`.
It requires to escape a lot of things. 
And there is no syntactic highlighting.



**So why not to add `@plain-inject` options as you have added `@inject-into`?**
`@plain-inject` will inject the script to the page without any the wrapping. And the option should be ignored if there is some `@grant`.

It will not break the existing code, but it allows to use the extension as loader of a JS code.
Just put a JS code as a userscript with `@plain-inject` and it will work like it was common script loaded from the page. No any problem with `this`.

**Comment by tophf** [comment]
Use that other extension. Why should we add this mode for just one user or maybe two?

**Comment by tophf** [comment]
We already have an incompatible `@inject-into` which is a pain for us and for developers so let it be the last nonstandard thing we add.

**Comment by AlttiRi** [comment]
**Damn this. I did it.**

The problem code:
```js
function demo() {
  console.log("this", this);
  console.log("window", window);  
  
  var AAA = {
      key: "value-AAA"
  }
  
  console.log("this.AAA", this.AAA); // !
  console.log("window.AAA.key", window.AAA.key); // !
}
```

The wrapping to a function with the changing of function's context will not help for this code.

So wrap it to a function, but then extract the function's content thank to `toString` method to bypass any problem with escaping. And inject it manually.

```js
function runFunctionContentInWebPageContext(func) {
    const script = document.createElement("script");

    const funcText = func.toString();
    console.log(funcText);
  
    const funcName = func.name;
    const code = funcText.slice(`"function ${funcName}() {`.length, -1);
  
    const blob = new Blob([code]);
    script.src = URL.createObjectURL(blob);
    document.querySelector("head").append(script);
  
    URL.revokeObjectURL(blob);
    script.remove();
}
```
Or use `script.textContent = code;` instead of `script.src = URL.createObjectURL(blob);` if the page that has no enabled CSP.

<details>
<summary>Full UserScript code</summary>

```js
// ==UserScript==
// @name        example.com
// @namespace   Violentmonkey Scripts
// @match       https://example.com/
// ==/UserScript==

runFunctionContentInWebPageContext(demo);

function demo() {
  console.log("this", this);
  console.log("window", window);  
  
  var AAA = {
      key: "value-AAA"
  }
  
  console.log("this.AAA", this.AAA);
  console.log("window.AAA.key", window.AAA.key);
}

function runFunctionContentInWebPageContext(func) {
    const script = document.createElement("script");

    const funcText = func.toString();
    console.log(funcText);
  
    const funcName = func.name;
    const code = funcText.slice(`"function ${funcName}() {`.length, -1);
  
    const blob = new Blob([code]);
    script.src = URL.createObjectURL(blob);
    document.querySelector("head").append(script);
  
    URL.revokeObjectURL(blob);
    script.remove();
}
```
</details>

<details>
<summary>Wrapped</summary>

```js
(function(){with(this)((define,module,exports)=>{// ==UserScript==
// @name        example.com
// @namespace   Violentmonkey Scripts
// @match       https://example.com/
// ==/UserScript==

runFunctionContentInWebPageContext(demo);

function demo() {
  console.log("this", this);
  console.log("window", window);  
  
  var AAA = {
      key: "value-AAA"
  }
  
  console.log("this.AAA", this.AAA);
  console.log("window.AAA.key", window.AAA.key);
}

function runFunctionContentInWebPageContext(func) {
    const script = document.createElement("script");

    const funcText = func.toString();
    console.log(funcText);
  
    const funcName = func.name;
    const code = funcText.slice(`"function ${funcName}() {`.length, -1);
  
    const blob = new Blob([code]);
    script.src = URL.createObjectURL(blob);
    document.querySelector("head").append(script);
  
    URL.revokeObjectURL(blob);
    script.remove();
}
})()}).call(VMinkfoinbx79f3f)
```
</details>
