### ISSUE TITLE
GM_download redirects to a blob: URL when name is blank

### ISSUE THREAD

**Issue by qsniyg** [violentmonkey/violentmonkey#968]
### What is the problem?

It redirects to a `blob:` URL.

### How to reproduce it?

```js
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       GM_download
// @version     1.0
// @author      -
// ==/UserScript==

GM_download({
  url: "https://google.com/12345.gif"
  // also happens if name: "", or name: undefined
})
```

### What is the expected result?

It shouldn't redirect to `blob:`. I know it's a required property, but I believe it should instead return an error instead (as TM does).

I discovered this because I accidentally left the name to a blank string, which caused this issue.

### Environment
- Browser: Chromium 
- Browser version: 80
- Violentmonkey version: 2.12.7
- OS: Linux

**Comment by tophf** [comment]
I can repro in Firefox but not in Chromium. Anyway we should extract the name from the URL if it's not provided.

**Comment by tophf** [comment]
OTOH, as suggested, throwing an error would be simpler and it'll match TM.

**Comment by tophf** [comment]
Hmm, TM doesn't show any errors and doesn't do anything at all when `name` is missing or empty, which seems like a definite bug to me so we won't be replicating this behavior. We'll throw an error like we do on a missing `url`.

**Comment by tophf** [comment]
Fixed in 91134fa8eada7215bc677ad5b1d4bf08a2344d72

**Comment by qsniyg** [comment]
TM shows an error though:

```
// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *
// @include     *
// @grant       GM_download
// @version     1.0
// @connect     *
// @author      -
// ==/UserScript==

GM_download({
  url: "https://google.com/12345.gif",
  onerror: function(error) {
      console.log(error); // {error: "not_whitelisted"}
  }
  // also happens if name: "", or name: undefined
})
```

According to https://gist.github.com/janekptacijarabaci/6eafe7f1e474e2daf23e906222e2b7fd, this means that the extension is not whitelisted.

Does the `throw new Error` call the `onerror` callback, as the spec suggests?

**Comment by tophf** [comment]
No, `throw` stops script execution entirely just like it would if the `url` is missing.

**Comment by qsniyg** [comment]
Would it be possible for this be changed to match TM and GM's (at least according to the polyfill) behavior then by using `onerror` instead? I understand that the try/catch method makes more sense from a javascript standpoint, but it also creates more problems for people who want to use the function, as they now need to implement two error handlers doing the exact same thing (one in try/catch, the other in `onerror`).

I don't personally mind doing this (close to a thousand lines of code in my userscript is dedicated to workarounds for things like this, a few more isn't going to be that big of a deal haha), but other developers probably won't be aware of the differences, and rely on TM's documentation/behavior.

**Comment by tophf** [comment]
GM_download may be invoked as GM_download(url, name) so there's no onerror to invoke. Theoretically we could check if onerror is provided and call that but the case we're looking at here is a blank or missing name which is a conceptual error so throwing on that looks like the proper solution.
