### ISSUE TITLE
GM_xmlhttpRequest sends a bad request when method is omitted

### ISSUE THREAD

**Issue by jkhsjdhjs** [violentmonkey/violentmonkey#970]
### What is the problem?
When calling `GM_xmlhttpRequest` without passing a `method` in the `details` object, `method` will be `undefined`. The resulting HTTP request will start with: `undefined /path HTTP/1.1`.
According to the documentation, `method` is not required: https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest

### What is the expected result?
`method` defaulting to `GET`.

### What is the actual result?
`method` is `undefined`.

### Environment
- Browser: Firefox Nightly
- Browser version: 77.0a1
- Violentmonkey version: v2.12.7
- OS: Arch Linux 

### Possible Solutions
- mark `method` as required in the documentation
- make `method` default to `GET` (which is what Tampermonkey does)

**Comment by tophf** [comment]
Ah, indeed, this has frustrated me too a couple of times. Let's go with TM's solution as it both makes sense and is convenient.

**Comment by tophf** [comment]
Fixed via f8b1771a.

**Comment by jkhsjdhjs** [comment]
That was probably the quickest fix I've ever seen. Thanks!
