### ISSUE TITLE
Add support for Prettier

### ISSUE THREAD

**Issue by dutzi** [violentmonkey/violentmonkey#971]
Hey,

This is a feature request for [Prettier](https://prettier.io/) support.

It would be awesome if once saved the document will be auto-formatted using Prettier.

That's it :)

**Comment by tophf** [comment]
No, it's a big library, ~700kiB minified.
The entire js code in Violentmonkey extension is ~700kiB.

The built-in editor is only for trivial modifications.
Use an [external editor or IDE](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/) as your main editor.
