### ISSUE TITLE
Give users the option to bind a keyboard shortcut to update all scripts

### ISSUE THREAD

**Issue by dutzi** [violentmonkey/violentmonkey#973]
My workflow working on a webpack based, work-related userscript is as follows:

1. Make changes to a js file (served locally using [webpack-userscript](https://github.com/momocow/webpack-userscript))
2. Save changes
3. Navigate to ViolentMonkey's Dashboard
4. Hit Check for updates

Having a global (global within Chrome, that is) shortcut assigned to Check for updates could eliminate steps 3 and 4, making the development feedback loop *much* shorter.

**Comment by tophf** [comment]
The preferred method of editing in Violentmonkey is via an [external editor](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/): the script will automatically update while you keep the confirmation tab open, no need to press anything.

**Comment by dutzi** [comment]
I see, what about adding a button in the popup menu, "Check for updates", that goes over all installed scripts and check for updates?

It existed in TamperMonkey and was useful when I was deploying an update to my script. All my peers had to do was click that button, unlike now when they'll need to enter the dashbaord.

**Comment by tophf** [comment]
The popup has a lot of buttons already so that's a no.

Technically we could add a hotkey (it's simple to implement) but first we need to understand why you don't want to use the more convenient method that I suggested above.

**Comment by dutzi** [comment]
I am, and it's great. I dropped the need for a hotkey, was just hoping for a button as some of my co-workers who use my script aren't into doing a lot clicking and facing complex UIs on the way...

**Comment by tophf** [comment]
We can add an item to the right-click menu on the extension icon in the browser toolbar, however I still want to understand why they need to update so often and do it manually. Maybe you can simplify the workflow for your colleagues by using `@require` and put the main script code somewhere in the network (or a web site).
