### ISSUE TITLE
[feature request] support authentication via browser.identity api

### ISSUE THREAD

**Issue by Alino** [violentmonkey/violentmonkey#974]
I need to write user scripts which are using api calls requiring an auth token.
This token can be obtained after identity server is setup with the redirect URI.
This redirect URI has to be static, (there is already browser API for this _browser.identity.getRedirectURL()_)

Can we somehow expose browser.identity webextension API to user scripts, so that our scripts can achieve this?

browser.identity -> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity

**Comment by tophf** [comment]
We don't add methods to the standard userscripts API unless it's supported by the more widespread userscript managers like Tampermonkey or Greasemonkey.

**Comment by Alino** [comment]
thanks for reply, I have just added same request to Tampermonkey repo https://github.com/Tampermonkey/tampermonkey/issues/911
Will see how this goes, and I might also talk to greasemonkey team later
