### ISSUE TITLE
問一下關於新版violentmonkey無法執行某個腳本問題

### ISSUE THREAD

**Issue by i9602097** [violentmonkey/violentmonkey#98]
我一直到有用[tiebaAllsign](https://greasyfork.org/scripts/152)配合Violentmonkey使用
但是在先前Violentmonkey更新後該腳本不能再正常運作
詳情在該腳本的[Issue](https://greasyfork.org/zh-TW/forum/discussion/21725/)中詳細提及
問題是我用回Opera以及Opera add-ons上的Violentmonkey卻工作正常
後來發現Opera add-ons上的Violentmonkey版本比較舊
改裝Chrome WebStore上的Violentmonkey新版便會出現同樣問題
與瀏覽器版本應該無關
但是我主力用Chrome無法安裝舊版Violentmonkey
所以想問一下這是不是新版的Bug
如果不是Bug而是新版有意安排而令腳本無法正常執行
那應如何自行修改腳本讓腳本能在新版Violentmonkey上正常運作
抱歉因為不太熟識UserScript所以特意上來請教

**Comment by gera2ld** [comment]
测试了一下，把脚本里的那些`"cookie" : encodeURIComponent(document.cookie),`都注释掉就好了。

旧版Violentmonkey有个bug(#89)是无法设置`cookie`头，即遇到上述代码会出错忽略，而新版支持`cookie`头了，所以就异常了。

**Comment by i9602097** [comment]
感謝回應，我理解這是由於新版Violentmonkey修正了以前的問題
才會導致腳本問題浮現
我先把回應帶回去腳本作者處討論
並且感謝Violentmonkey開發者能抽空回應腳本問題
