### ISSUE TITLE
Page doesn't load properly once jquery is declared

### ISSUE THREAD

**Issue by rbigr** [violentmonkey/violentmonkey#984]
### What is the problem?
After loading a page using jquery `@require` statement the user avatars don't appear. 

### How to reproduce it?
1. Load the following script.

```js
// ==UserScript==
// @name        Test
// @namespace   Violentmonkey Scripts
// @match       https://*.wykop.pl/*
// @grant       none
// @version     1.0
// @author      -
// @description 4/25/2020, 4:18:42 PM
// @require     https://code.jquery.com/jquery-3.5.0.min.js
// ==/UserScript==
```

2. Go to wykop.pl/mikroblog

3. Scroll down and look at the user avatars.

### What is the expected result?
The Avatars are showing up.

### What is the actual result?
Some users have white squares instead of avatars.

### Additional information
No problem with Greasemonkey.
Same result with older jqeuery versions, like 1.9.
The script doesn't contain any body but the result is the same when `alert($)` as body

### Environment
- Browser: Firefox
- Browser version: 68.7.0
- Violentmonkey version: 2.12.7
- OS: Linux 5.4

**Comment by tophf** [comment]
When `@grant none` is specified the script runs in page context just like any page script. This is how Violentmonkey and Tampermonkey work whereas Greasemonkey always runs userscripts in a browser sandbox.

Either specify `@inject-into content` to run the script in [`content` mode ](https://violentmonkey.github.io/posts/inject-into-context/) or use the standard `jQuery.noconflict()`

```js
// ==UserScript==
// @name        Test
// @match       https://*.wykop.pl/*
// @grant       none
// @require     https://code.jquery.com/jquery-3.5.0.min.js
// ==/UserScript==

const $ = jQuery.noConflict();
```

**Comment by rbigr** [comment]
@tophf Thank you, especially for explaining the differences. Actually, it works now.
