### ISSUE TITLE
exclude rules not work with particular script?

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#985]
**What is the problem?**

@exclude rules not work with script **Recaptcha clicker** (https://greasyfork.org/it/scripts/376404-recaptcha-clicker)

**What is the expected result?**

blocked this script on a single site
for example http://totaldebrid.org/
I edit so:
![Annotazione 2020-04-28 114659](https://user-images.githubusercontent.com/33927879/80473178-0dc5bc00-8946-11ea-9cfe-15e98bcc6278.png)

**What is the actual result?**

The script continue to work in any site

    Browser: Firefox
    Browser version: 75.0
    Violentmonkey version: 2.12.7
    OS: Windows 10

**Comment by tophf** [comment]
This script doesn't run on totaldebrid.org. It has `@match http*://www.google.com/recaptcha/*` so it only runs on google recaptcha URL. The recaptcha creates an iframe with that URL where the picture is shown and where the script runs.

Userscripts don't have a mechanism to exclude top-level tab URL for a script that runs in an iframe.

You can modify this userscript to also run everywhere so the two instances of the same script can communicate (e.g. via top.postMessage) and the top-level instance will tell the iframe instance the real tab URL.
