### ISSUE TITLE
VM does not allow changing the User-Agent in requests

### ISSUE THREAD

**Issue by Mehavoid** [violentmonkey/violentmonkey#989]
### What is the actual result?
```
(function() {
    'use strict';

    GM_xmlhttpRequest({
        url: '/',
        method: 'GET',
        headers: {
            'Test': 'is worked!',
            'User-Agent': 'is not worked :('
        },
        onload: console.log,
        onerror: console.error
    })

})()
```
Request Headers
```Request Headers
Sec-Fetch-Dest: empty
Test: is worked!
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/80.0.3987.149 Safari/537.36
VM-Verify: k9xhryz99859
```

### Environment
- Browser: Ungoogled Chromium
- Browser version: 80.0.3987.149 (Developer Build)
- Violentmonkey version: 2.12.7
- OS: Linux (Debian 10)

**Comment by tophf** [comment]
Assuming you're looking at the correct [devtools of the background page](https://stackoverflow.com/a/10258029), your script works for me correctly in Google Chrome both under Windows and Linux Mint so I guess it's a problem in Debian or in your build of Chromium.

**Comment by WhiteSevs** [comment]
在Kiwi Browser 124.0.6327.2上有时候会触发这个问题，无法设置`User-Agent`，且会有`VM-Verify`这个参数在`Request Headers`内@tophf

**Comment by tophf** [comment]
> VM-Verify

Sounds like webRequestBlocking is not working in Kiwi browser.
