### ISSUE TITLE
同步数据库能否加密

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#99]
现在全部明文存储看着很难过……
能否像 KeePass 一样，先行加密再同步到云盘？
当然为了方便，可以预设密码或密钥自动解密。

**Comment by gera2ld** [comment]
这种东西加密有什么意义吗？而且那个内容又不是给人看的。。。

**Comment by ivysrono** [comment]
强迫症，不想让云盘服务商知道我用了哪些脚本……

**Comment by gera2ld** [comment]
感觉意义不大，而且以后如果支持webdav就没这个担心了吧

**Comment by ivysrono** [comment]
BTW，amo一直不给过审的理由是啥？
