### ISSUE TITLE
[feature request] Add keyboard shortcut to deactivate Violentmonkey in Firefox

### ISSUE THREAD

**Issue by DrJackaal** [violentmonkey/violentmonkey#990]
![Untitled](https://user-images.githubusercontent.com/29663671/81423587-477e9a00-9172-11ea-9a6b-3ed4002c77e8.jpg)

**Comment by tophf** [comment]
Do you mean the on/off switch in the popup or something else?

![image](https://user-images.githubusercontent.com/1310400/81423832-ab4a9800-915d-11ea-988e-5cc25692e9b9.png)

**Comment by DrJackaal** [comment]
> 
> 
> Do you mean the on/off switch in the popup or something else?
> 
> ![image](https://user-images.githubusercontent.com/1310400/81423832-ab4a9800-915d-11ea-988e-5cc25692e9b9.png)

yes but can be deactivated by keyboard shortcut

**Comment by tophf** [comment]
This toggle is not related to your initial screenshot which shows a hotkey to show the extension popup menu so I don't understand what you mean exactly.

**Comment by tophf** [comment]
The hotkey for "Activate extension" shows the extension popup menu.
The toggle in the popup on my screenshot switches script injection.
