### ISSUE TITLE
[NSFW][Bug report]Incompatability with nhentai

### ISSUE THREAD

**Issue by machsix** [violentmonkey/violentmonkey#991]
### What is the problem?
Scripts don't work on nhentai.net
### How to reproduce it?
1. Sample script
```js
// ==UserScript==
// @name        New script - nhentai.net
// @namespace   Violentmonkey Scripts
// @match       https://nhentai.net/*
// @grant       none
// @version     1.0
// @author      -
// @description 5/10/2020, 11:47:09 PM
// ==/UserScript==

(function() {
  alert("test");
  console.log("test");
 })();
```
2. Open page like [https://nhentai.net/g/312760/2/](https://nhentai.net/g/312760/2/)

### What is the expected result?
An alert should appear also `test` should appear in the console

### What is the actual result?
None of the behaviors appear. Console log:
![Capture](https://user-images.githubusercontent.com/28209092/81522787-c3ffad00-9319-11ea-9863-b32236826765.PNG)

### Environment
- Browser: Firefox
- Browser version:  76.0.1
- Violentmonkey version: v2.12.7
- OS: Windows

### Other comments:
Windows Edge (Chromium core) with violentmonkey have similar issue. Edge with Tampermonkey works but the console log keeps refreshing. If I use `ublock origin` to block the script `https://static.nhentai.net/js/combined.1d8cbb9eacc7.js`, violentmonkey works properly

**Comment by tophf** [comment]
Seems to be fixed in the release candidate, https://github.com/violentmonkey/violentmonkey/releases
