### ISSUE TITLE
some way to start GM.xmlHttpRequest earlier?

### ISSUE THREAD

**Issue by divinity76** [violentmonkey/violentmonkey#992]
### What is the problem?

on pages that have some components that loads slowly, GM.xmlHttpRequest() seems to fire very slowly as well, for example i have this little test script:
```js
// ==UserScript==
// @name        GM.xhr tests
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @match       *://youtube.com/*
// @match       *://www.youtube.com/*
// @grant       GM.xmlHttpRequest
// @version     0.1
// @author      -
// @description 2020-17-05, 11:13:20 PM
// ==/UserScript==
(function(){
  let evalStart=Date.now();
  GM.xmlHttpRequest({
    method:"GET",
    url:"http://127.0.0.1/30kb.txt",
    onload:function(ev){
      let evalEnd=Date.now();
      console.log("complete! seconds: "+( (evalEnd-evalStart)/1000  )   );
    }
  });
})();
```
and on websites that loads fast (like http://example.org/ ) , this script outputs stuff like:
```
complete! seconds: 0.168
```
here it loads in less than 0.2 seconds, which is fine. but on websites that have some components (eg images) that loads very slowly, gm.xmlHttpRequest() also loads very slowly, for example on https://www.youtube.com/ i get outputs like:
```
complete! seconds: 2.056
complete! seconds: 3.287
```
(i have a very slow internet connection, it's a 10mbit-capped dodgy 4G internet connection =/ )

i think GM.xmlHttpRequest() waits for the window.load ( https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event ) event to fire before it fires itself.. the load event waits for everything to be loaded, including all images, hence the delay

is there some way to fire GM.xmlHttpRequest earlier? for example, if i can fire it on the window.DOMContentLoaded -event instead of the window.load -event , that would be great, DOMContentLoaded fires after all the HTML has been loaded, and doesn't wait for images

### How to reproduce it?
1. make http://127.0.0.1/30kb.txt a valid url (i use nginx)
2. enable script
```js
// ==UserScript==
// @name        GM.xhr tests
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @match       *://youtube.com/*
// @match       *://www.youtube.com/*
// @grant       GM.xmlHttpRequest
// @version     0.1
// @author      -
// @description 2020-17-05, 11:13:20 PM
// ==/UserScript==
(function(){
  let evalStart=Date.now();
  GM.xmlHttpRequest({
    method:"GET",
    url:"http://127.0.0.1/30kb.txt",
    onload:function(ev){
      let evalEnd=Date.now();
      console.log("complete! seconds: "+( (evalEnd-evalStart)/1000  )   );
    }
  });
})();
```
3. go to http://example.org and see the time (it should be fast, even on a slow internet connection)
4. go to https://www.youtube.com/ and see the time (it should be *much* slower, at least if you got a slow internet connection

### What is the expected result?

GM.xmlHttpRequest fires on the window.DOMContentLoaded event

### What is the actual result?

GML.xmlHttpRequest fires on the window.load event

### Environment
- Browser: Firefox
- Browser version: 76.0.1 (64-bit)
- Violentmonkey version: 2.12.7
- OS: Xubuntu Linux 18.04, uname -a: Linux dev2020 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tophf** [comment]
GM.xmlHttpRequest doesn't wait for anything. The only explanation for the observed behavior can be that the browser has a limit on outgoing connections and waits for the current queue to complete before starting the new request. And indeed, postponing the call with `setTimeout` to 5 or 10 seconds makes it as fast as possible.

**Comment by tophf** [comment]
Actually, it's the JavaScript code of the site. It has a **lot** of scripts and they take a lot of time to initialize. Since JavaScript is single-threaded per each execution context it means your userscript's onload callback can't run until the page has finished running its own code. If you run Firefox profiler (or devtools profiler in Chrome) you will see. It's... terrible.

**Comment by divinity76** [comment]
@tophf  i see, thanks for the explanation :)
