### ISSUE TITLE
[Firefox] Can't modify page properties on sites which use CSP

### ISSUE THREAD

**Issue by chocolateboy** [violentmonkey/violentmonkey#997]
This is my abiding issue with Violentmonkey (which I :heart: - thank you!), but I can't see an open issue for it. There are related closed issues, and [this issue](https://github.com/violentmonkey/violentmonkey/issues/604) may point the way to a fix, but I thought it'd be better to track the bug explicitly rather than inferring it from the [documentation](https://violentmonkey.github.io/posts/inject-into-context/#mode-content)<sup>[1]</sup> and scattered comments.

### What is the problem?

It's not possible to modify/mutate direct or nested properties of a page's window object with the following combination:

- Violentmonkey for Firefox
- sites which use [CSP](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) (e.g. GitHub, Google, Twitter)

Sites which use CSP don't run in Violentmonkey for Firefox unless [`@inject-into content`](https://violentmonkey.github.io/posts/inject-into-context/#mode-content) is enabled, but `@inject-into content` is not compatible with `@grant none`, which is needed to modify page objects.

Userscript engines this works in:

- Tampermonkey (tested on Firefox)

Userscript engines this doesn't work in:

- [Greasemonkey](https://github.com/greasemonkey/greasemonkey/issues/3015)<sup>[2]</sup>
- FireMonkey<sup>[3]</sup>

### How to reproduce it?

```javascript
// ==UserScript==
// @name          Hook XHR#open
// @version       0.0.1
// @include       https://twitter.com/*
// @include       https://github.com/*
// @include       https://*.google.tld/*
// @grant         none
// @inject-into   content
// ==/UserScript==

function hookXHROpen (oldOpen) {
    return function open (...args) {
        console.warn('inside XHR#open')
        return oldOpen.apply(this, args)
    }
}

// or unsafeWindow...
window.XMLHttpRequest.prototype.open = hookXHROpen(
    window.XMLHttpRequest.prototype.open
)
```

### What is the expected result?

XHR#open should be hooked and the message should be logged on those sites.

### What is the actual result?

XHR#open isn't hooked and the message isn't logged.

### Related issues

- https://github.com/violentmonkey/violentmonkey/issues/107
- https://github.com/violentmonkey/violentmonkey/issues/172
- https://github.com/violentmonkey/violentmonkey/issues/173
- https://github.com/violentmonkey/violentmonkey/issues/408
- https://github.com/violentmonkey/violentmonkey/issues/487
- https://github.com/violentmonkey/violentmonkey/issues/604

### Environment

- Browser: Firefox v76.0.1
- Violentmonkey: v2.12.7
- OS: Linux (Arch)

### Footnotes

1. "Scripts requiring access to JavaScript objects in the web page will not work in [`@inject-into content`] mode."
2. "GM4 does not yet support `@grant none`."
3. `@grant none` isn't supported. [`unsafeWindow` is](https://github.com/erosman/support/issues/80) but I couldn't get the XHR#open hook to work.

**Comment by chocolateboy** [comment]
Incidentally, I'd prefer to use `unsafeWindow` rather than `@grant none`, but that doesn't work either (i.e. doesn't allow the underlying `window` object to be modified) if `@inject-into content` is used.

**Comment by tophf** [comment]
AFAIK Tampermonkey rewrites the CSP response header to allow its script elements. We could do it as well but it seems quite radical, I'm not even sure Mozilla will allow it in the future, they dislike addons rewriting CSP last time I heard.

`unsafeWindow.wrappedJSObject` works for me in Violentmonkey:

```js
// ==UserScript==
// @name        test wrappedJSObject
// @match       https://www.google.com/*
// @grant       GM_foo
// @run-at      document-start
// @inject-into content
// ==/UserScript==

const pageWnd = unsafeWindow.wrappedJSObject;
const p = pageWnd.XMLHttpRequest.prototype;
const {open} = p;
const xhrOpen = function (method, url) {
  console.warn('intercepted', url);
  return open.apply(this, arguments);
}
p.open = exportFunction(xhrOpen, pageWnd);
```

**Comment by chocolateboy** [comment]
This ended up being quite fiddly to get working. While I appreciate the fact that a workaround exists, I still think this is a bug and that `unsafeWindow` should work out of the box without the need for engine-specific workarounds.

For anyone else who needs a working example of this in action, see [here](https://greasyfork.org/en/scripts/404632-twitter-direct).

In particular, note that getting `Object.defineProperty` to work (e.g. to modify a XHR response) may be non-obvious:

### This doesn't work

```javascript
const descriptor = cloneInto({ value: json }, unsafeWindow.wrappedJSObject)
Object.defineProperty(xhr, 'responseText', descriptor)
```

### This works

```javascript
const descriptor = cloneInto({ value: json }, unsafeWindow.wrappedJSObject)
unsafeWindow.wrappedJSObject.Object.defineProperty(xhr, 'responseText', descriptor)
```

**Comment by tophf** [comment]
We couldn't make `unsafeWindow` work like this by default because we need to support legacy scripts which is the entire point of using Violentmonkey in Firefox instead of Greasemonkey/Firemonkey. We tried it already but failed because the userscripts need to knowingly and correctly use exportFunction/cloneInto. When they don't their code breaks in various unexpected ways if they expose stuff into unsafeWindow like e.g. `unsafeWindow.foo = () => console.log('123');`

>This works

Yep. Every global builtin such as `Object` belongs to `window` of a respective execution context, this is how JS does things.

**Comment by chocolateboy** [comment]
> We couldn't make unsafeWindow work like this by default because we need to support legacy scripts which is the entire point of using Violentmonkey in Firefox instead of Greasemonkey/Firemonkey.

Legacy scripts expect `unsafeWindow` to just work, the way it works in Greasemonkey 3 and Tampermonkey — i.e. direct mutation of the page's object's. That's not currently how it works in Violentmonkey on sites which use CSP. Because of its non-conforming behavior, I don't think it should even be called `unsafeWindow` in this context.

> We tried it already but failed

That's why I think this bug should remain open until its either [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) in Firefox, or Violentmonkey/Firefox migrates to the [new userscript API](https://github.com/violentmonkey/violentmonkey/issues/604).

**Comment by tophf** [comment]
The problem was that if such code overrides a standard window property via unsafeWindow it will completely break a lot of pages which actually happened last time we tried.

**Comment by chocolateboy** [comment]
Than call it `safeWindow`? The point is, it differs from the standard/expected behavior.

**[Tampermonkey](https://www.tampermonkey.net/documentation.php)**

> The `unsafeWindow` object provides **full access** to the pages javascript functions and variables.

**[Greasemonkey 3](https://wiki.greasespot.net/index.php?title=UnsafeWindow&oldid=7050)**

> This API object allows a User script to access "custom" properties--variable and functions defined in the page--set by the web page. The unsafeWindow object is shorthand for `window.wrappedJSObject`. It is the **raw window object** inside the XPCNativeWrapper provided by the Greasemonkey [sandbox](https://wiki.greasespot.net/Sandbox).

**Comment by tophf** [comment]
Tampermonkey modifies CSP of the sites which is rather intrusive. I'm not convinced we should do the same as I explained above.

Greasemonkey 3 doesn't run anymore in modern Firefox 57+.

Greasemonkey 4 doesn't care about compatibility with the older scripts so we can't follow suit.

Anyway AFAIK there aren't that many scripts that are affected by this predicament as people don't normally use the `content` mode. As for me, I don't use Firefox, the same applies to gera2ld, so there's no one to spearhead development of such browser-specific things as wrappedJSObject and the extensive reasearch/testing of the existing userscripts it entails.

**Comment by sn260591** [comment]
> 
> 
> This ended up being quite fiddly to get working. While I appreciate the fact that a workaround exists, I still think this is a bug and that `unsafeWindow` should work out of the box without the need for engine-specific workarounds.
> 
> For anyone else who needs a working example of this in action, see [here](https://greasyfork.org/en/scripts/404632-twitter-direct).
> 
> In particular, note that getting `Object.defineProperty` to work (e.g. to modify a XHR response) may be non-obvious:
> ### This doesn't work
> 
> ```js
> const descriptor = cloneInto({ value: json }, unsafeWindow.wrappedJSObject)
> Object.defineProperty(xhr, 'responseText', descriptor)
> ```
> 
> ### This works
> 
> ```js
> const descriptor = cloneInto({ value: json }, unsafeWindow.wrappedJSObject)
> unsafeWindow.wrappedJSObject.Object.defineProperty(xhr, 'responseText', descriptor)
> ```

In this case, there is no need to clone the `descriptor`.
`cloneInto` and `exportFunction` are needed only for objects and functions that the page code accesses directly. I recommend that you read the [official documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts).

**Comment by chocolateboy** [comment]
> In this case, there is no need to clone the descriptor.

Thanks!

Unfortunately, that doesn't appear to work for me [in this case](https://github.com/chocolateboy/userscripts/blob/455b377ea69186832ae5cd8177a0e666d73ba4e7/src/twitter-direct.user.js#L102-L103) ([install](https://github.com/chocolateboy/userscripts/raw/no-clone-descriptor/src/twitter-direct.user.js)), but I can't see an error message (the script just hangs), so it's possible I've overlooked something.

> `cloneInto` and `exportFunction` are needed only for objects and functions that the page code accesses directly.

Where does it say that?

>  I recommend that you read the official documentation.

I recommend that this is provided by the userscript engine as `unsafeWindow` so that userscript developers don't need to be versed with low-level details of Firefox addon development to reimplement a standard userscript API.

**Comment by sn260591** [comment]
> Unfortunately, that doesn't appear to work for me [in this case](https://github.com/chocolateboy/userscripts/blob/455b377ea69186832ae5cd8177a0e666d73ba4e7/src/twitter-direct.user.js#L102-L103) ([install](https://github.com/chocolateboy/userscripts/raw/no-clone-descriptor/src/twitter-direct.user.js)), but I can't see an error message (the script just hangs), so it's possible I've overlooked something. Do you have an example of it working without the clone?

Use `Object.defineProperty` without `Compat.unsafeWindow`.

> Where does it say that?

This conclusion is drawn from the documentation and my observations.

**Comment by sn260591** [comment]
> Yeah, [that doesn't work](https://github.com/chocolateboy/userscripts/blob/4a3365b8c296e88b7871289af1a574679256f155/src/twitter-direct.user.js#L102-L103) either ([install](https://github.com/chocolateboy/userscripts/raw/4a3365b8c296e88b7871289af1a574679256f155/src/twitter-direct.user.js)). It doesn't modify the XHR object in the page (why would it?).

You must export [this function](https://github.com/chocolateboy/userscripts/blob/455b377ea69186832ae5cd8177a0e666d73ba4e7/src/twitter-direct.user.js#L116), because it is called by xhr, which is in the page scope.

> I look forward to seeing a working example to confirm this.

Something like that?
```
// ==UserScript==
// @name test
// @match *://*/*
// @inject-into content
// @run-at document-start
// ==/UserScript==

const originalLog = console.log;
const func = exportFunction(() => originalLog("fake message"), unsafeWindow.wrappedJSObject);
Object.defineProperty(unsafeWindow.wrappedJSObject.console, "log", { value: func });
```

**Comment by chocolateboy** [comment]
> You must export [this function](https://github.com/chocolateboy/userscripts/blob/455b377ea69186832ae5cd8177a0e666d73ba4e7/src/twitter-direct.user.js#L116), because it is called by xhr, which is in the page scope.

We should take this to [my repo](https://github.com/chocolateboy/userscripts) rather than further derailing this issue (if you have a particular fix or feature in mind), but, to be clear, that function (and the userscript) works fine without that, and doesn't work with your suggested changes.

As for the example you've given, I don't see any difference between that and assigning directly to `console.log`, e.g.:

```javascript
unsafeWindow.wrappedJSObject.console.log = func
```

\- which is what the script already does, [e.g.](https://github.com/chocolateboy/userscripts/blob/47387b07caaac4b3cfd7b53199905c2a536a5a81/src/twitter-direct.user.js#L155-L158):

```javascript
unsafeWindow.wrappedJSObject.XMLHttpRequest.prototype.send = func
```

**Comment by sn260591** [comment]
@chocolateboy How to determine that your script is working properly?


> As for the example you've given, I don't see any difference between that and assigning directly to `console.log`, e.g.:
> 
> ```js
> unsafeWindow.wrappedJSObject.console.log = func
> ```

Try execute `console.log("test")` in the web console. Without exporting the function, an error will occur.

**Comment by sn260591** [comment]
@chocolateboy I apologize for misleading you. It seems that your method is the only working one, although it has a strange implementation.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/violentmonkey/violentmonkey/issues/997#event-3411827214

This is closed as "completed", yet I still can't run [`Vencord/builds/blob/3e8df1080608588e8ad377c2bce8e30babac5522/Vencord.user.js`](https://github.com/Vencord/builds/blob/3e8df1080608588e8ad377c2bce8e30babac5522/Vencord.user.js#L22C4-L24C61:~:text=this%20UserScript%20DOES%20NOT%20work,//%20https://github.com/violentmonkey/violentmonkey/issues/997) due to this. [^1] In `violentmonkey-2.31.0.xpi`'s `popup/index.html`, I see: [^2]

> The script didn't exist or didn't match the URL when the page loaded, which happens in Single-Page Application sites, like FB or Instagram, that  are using fake navigation. You can reload the tab to run the script. To fix the script, use `@match` for the entire site, then detect changes using `MutationObserver` or the `window.navigation` API.

[^1]: [`Vendicated/Vencord/blob/e447dec67b3e9b06df8dfe6204287fcc2a8bab07/browser/userscript.meta.js#L22C4-L24C61`](https://github.com/Vendicated/Vencord/blob/e447dec67b3e9b06df8dfe6204287fcc2a8bab07/browser/userscript.meta.js#L22C4-L24C61:~:text=this%20UserScript%20DOES%20NOT%20work,//%20https://github.com/violentmonkey/violentmonkey/issues/997)

[^2]: [`discord.com/channels/1015060230222131221/1026515880080842772/1381204415007952936`](https://canary.discord.com/channels/1015060230222131221/1026515880080842772/1381204415007952936#:~:text=Roke%20B.-,:,MutationObserver%20or%20the%20window.navigation%20API.,-I'd%20have%20reported)

<details>

![Image](https://github.com/user-attachments/assets/61c2d83d-7bc2-423d-8e4e-cab7bcef701d)

</details>

However, [`tampermonkey.net/xpi/firefox-current-beta.xpi`](https://www.tampermonkey.net/xpi/firefox-current-beta.xpi) does not:

![Image](https://github.com/user-attachments/assets/a3eb1f04-a13a-4dde-a3fe-f90d64ef8e28)

If relevant, it merely prompts me:

![Image](https://github.com/user-attachments/assets/7d0c54e4-acc4-4d4d-92e0-30283e5ba04d)

Can this not be achieved in VM?
