### ISSUE TITLE
Confirm Installation button should stand out

### ISSUE THREAD

**Issue by dutzi** [violentmonkey/violentmonkey#998]
Since it's the main CTA, Confirm Installation button should stand out, for example:

![image](https://user-images.githubusercontent.com/927310/83599873-f5b11000-a575-11ea-8156-c16b63c91aec.png)

O/w it takes some time to find it since they all blend in with the background.

**Comment by tophf** [comment]
One can argue that making installation harder ensures the users who managed to accomplish it know what they're doing. Joking aside, I agree, but I think the entire confirmation UI needs a major overhaul so I don't see the urgent need to fix this one thing.

**Comment by tophf** [comment]
This will be tracked in #1121.
